### ISSUE TITLE
When are tables created?

### ISSUE THREAD

**Issue by Rainer-Lang** [Raizlabs/DBFlow#100]
If I save a model DBLow creates the table, right?

but initial:
Does DBFlow creates tables or do I have to use SQLiteOpenHelper.onCreate() to create tables?
I'm getting an error: "no such table: Devices" if I make a select-statement.

**Comment by agrosner** [comment]
If you add a table after initialization of the app, you need to increment the database version. DBFlow creates the tables in the ```FlowSQliteHelper.onCreate()``` or ```onUpgrade()```. So when the app launches it opens this helper and the methods are all automatically handled for you.

**Comment by Rainer-Lang** [comment]
@agrosner Thanks. Is there something about "FlowSQliteHelper" in the docu so I can read a bit and learn more about this great lib?

**Comment by agrosner** [comment]
Not that aspect. I apologize. Do you have sources linked for this library in your project? If not I can help you set that up so you can easily dive into this library's source to help.

**Comment by Rainer-Lang** [comment]
I have only this in my gradle:
apt 'com.raizlabs.android:DBFlow-Compiler:1.5.3'
mod "com.raizlabs.android:{DBFlow-Core, DBFlow}:1.5.3"
