### ISSUE TITLE
Update fails if updating a primary key

### ISSUE THREAD

**Issue by Motoharujap** [Raizlabs/DBFlow#1000]
DBFlow Version 3.1.1:
Issue Kind (Bug):

Description: 

I have a table with two primary keys (autoincrement disabled on both). 
Here it is
```
@Table(database = JuiceDatabase.class)
public class Test extends BaseModel {
    @Column
    @PrimaryKey
    private long externalObjectA_ID;
    @Column
    @PrimaryKey
    private long externalObjectB_ID;
    
    @Column
    private String aField;
}
```
When I do:
test.setAField("Value");
test.update();

everything is OK.

But when I do:

test.setExternalObjectB_ID(12345);
test.update();

update fails.

I dug in the library's code a bit and found that when a query is composed it looks like
`UPDATE Test SET externalObjectA_ID = ?, externalObjectB_ID = ?, aField = ? WHERE externalObjectA_ID = %an old value of this field% AND externalObjectB_ID = %a !!!NEW!!! value of this field% AND aField = "Value"`

Of course I have no such record in my DB yet because I'm updating it! Of course this query will fail to execute and this happens only if I update one of my primary keys.

**Comment by agrosner** [comment]
You shouldn't ever change the primary key of the objects you create. Rather you should `delete()` existing first, then `insert()` this new object. If a primary key needs to change, I recommend you make it `Unique` instead.
