### ISSUE TITLE
Leaking Context when asynchronously querying a list

### ISSUE THREAD

**Issue by jguerinet** [Raizlabs/DBFlow#1004]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Bug/Question
Description: 
Hi, 

I'm currently using DBFlow in a RecyclerView adapter to query a list of objects and display them. I have an `update()` method that asynchronously queries a DB and updates the views after the results are received in this fashion: 

```
SQLite.select()
                .from(ClassA.class)
                .where(condition)
                .async()
                .queryListResultCallback((transaction, tResult) -> {
                    if (tResult == null) {
                        return;
                    }

                    listItems.clear();
                    listItems.addAll(tResult);

                    // Update the view 
                    notifyDataSetChanged();
                })
                .execute();
```

When running LeakCanary on my app, a leak is caught when leaving this list view:  (DefaultTransactionQueue -> Transaction -> QueryResultListCallback -> RecyclerView -> Context)

So I'm wondering: 
- Is there a way to avoid this leak? I assumed that the transaction was done after it ran, so I'm not sure why it's still referenced in memory 
- Is there maybe a better way to do this kind of operation to avoid this?

Thanks and great library! 
Julien

**Comment by agrosner** [comment]
is it possible that youve left the view before the transaction actually executes?

**Comment by agrosner** [comment]
closing. you probably want to isolate this call from your fragment/activity class and provide a callback by which you can register/deregister.

**Comment by jguerinet** [comment]
Hey @agrosner, 

Sorry for the lack of response, I've been a bit busy. I don't leave the view before the transaction actually executes. I'll give some more detail on what I am doing and provide an example as soon as I have some free time.
