### ISSUE TITLE
TypeConverter problem

### ISSUE THREAD

**Issue by carmas123** [Raizlabs/DBFlow#1005]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Bug

Description: 
The @Column(typeConverter = myConverter) is not applied when convert a value to string in Where clause.

**Comment by agrosner** [comment]
yep this is a bug. What ill have to do is essentially pull down the type converter into the new `TypeConvertedProperty` class when it is custom. Working on this now. Should go in 4.0.0-beta2

**Comment by agrosner** [comment]
in `develop` now.
