### ISSUE TITLE
[Question]SQLiteOpenHelper And DBFlow

### ISSUE THREAD

**Issue by SnakeEys** [Raizlabs/DBFlow#1007]
When I use SQLiteOpenHelper(DBHelper) to create a table in a db file(such as demo.db), while DBFlow was unable to create another table after that in the same db file and the exception are as follows:

no such table: table-name (code 1), while compiling: INSERT/SELECT.... However, the table created by SQLiteOpenHelper can be accessed by DBFlow. And this situation can be totally converted on the contrary.

What makes me confused is that when I use openOrCreateDatabase(), the above situation will no longer occur.

If there were 2 tables in the same .db file, Both table1 and table2 can be accessed by SQLiteOpenHelper and DBFlow.

That's the problem what I have met, is it a bug(I beg not)? Or any other reasons?

Best Regards.

**Comment by agrosner** [comment]
once you create and open a db, run creations you cannot create another table until you perform a [migration](https://github.com/Raizlabs/DBFlow/blob/master/usage2/Migrations.md)
