### ISSUE TITLE
Where clause with Calendar!!!

### ISSUE THREAD

**Issue by robertio4** [Raizlabs/DBFlow#1008]
DBFlow Version: 3.1.1
Issue Kind: Question

Description: 

Hello, I want to execute the next query:

`SQLite.select()
                    .from(Object.class)
                    .where(Object_Table.fechaPrevista.eq(getFecha()))
                    .queryList();`

The data type of the column 'fechaPrevista' and 'fecha' is Calendar, the value is the same. The select should return 5 results but returns 0.

I am doing something wrong? There is any other way to do the 'where'?

**Comment by obuiron** [comment]
Hello,

Seem it's an issue with [CalandarConverter](https://github.com/Raizlabs/DBFlow/blob/3.1.1/dbflow-core/src/main/java/com/raizlabs/android/dbflow/converter/CalendarConverter.java).

----

Query : ```SQLite.select().from(Author.class).where(Author_Table.calendar.eq(calendar)).getQuery());```
SQL generated query  : 
```
SELECT * FROM `Author` WHERE `calendar`='java.util.GregorianCalendar[time=100,areFieldsSet=true,lenient=true,zone=Europe/Paris,firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=1970,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=1,HOUR_OF_DAY=1,MINUTE=0,SECOND=0,MILLISECOND=100,ZONE_OFFSET=3600000,DST_OFFSET=0]'
```

But with java.util.Date work fine.
Query : ```SQLite.select().from(Author.class).where(Author_Table.date.eq(date)).getQuery());```
SQL generated query  : 
```
SELECT * FROM `Author` WHERE `date`=100 
```

----

I think issue come from [BaseCondition.convertValueToString(...)](https://github.com/Raizlabs/DBFlow/blob/3.1.1/dbflow/src/main/java/com/raizlabs/android/dbflow/sql/language/BaseCondition.java#L46) cause value.getClass() on Calandar.getInstance() return a GregorianCalendar instance.

```Calendar.getInstance().getClass()``` --> ```class java.util.GregorianCalendar```
```Calendar.getInstance().getClass().getSuperclass()``` --> ```class java.util.Calendar```

BaseCondition.convertValueToString(...) :
```
TypeConverter typeConverter = FlowManager.getTypeConverterForClass(value.getClass());
if (typeConverter != null) {
  value = typeConverter.getDBValue(value);
}
```
Should be, to allow convertion based on super class : 
```
TypeConverter typeConverter = FlowManager.getTypeConverterForClass(value.getClass());
if (typeConverter != null) {
  value = typeConverter.getDBValue(value);
}else{
  typeConverter = FlowManager.getTypeConverterForClass(value.getClass().getSuperclass());
  if (typeConverter != null) {
    value = typeConverter.getDBValue(value);
  }
}
```

**Comment by agrosner** [comment]
now included is `@TypeConverter(allowedSubTypes = {})` which by default the lib now allows `GregorianCalendar` instances. for other types you can override the default converters too, meaning you can have more flexibility. in `develop` 4.0.0-beta4
