### ISSUE TITLE
Return empty list instead of null within QueryResultListCallback

### ISSUE THREAD

**Issue by erawhctim** [Raizlabs/DBFlow#1009]
DBFlow Version: **3.1.1**
Issue Kind (Bug, Question, Feature): **Feature**

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: Would it make sense to return an empty list in the event of an empty query, transaction error, etc, instead of a `@Nullable` one? Right now I have a custom list callback that handles this scenario to guarantee the list returned is never `null`, but it seems like a useful addition to the API so I figured I'd bring it up here for disucssion.

**Comment by agrosner** [comment]
sounds good to me. follows pattern of `ModelQueriable.queryList()`

**Comment by agrosner** [comment]
in `develop`.
