### ISSUE TITLE
Trigger creation in DBFlow.

### ISSUE THREAD

**Issue by TeddyGammel** [Raizlabs/DBFlow#1010]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Triggers

After inserting a record on Table A, I would like to insert another record on Table B via a trigger.
Table A schema is (id INT PRIMARY KEY, name TEXT, rootId INT)
Table B schema is (id INT PRIMARY KEY, name TEXT)

Now I would like to add the following trigger:
CREATE TRIGGER trigger_name AFTER INSERT ON A BEGIN INSERT INTO B (id, name) VALUES(NEW.rootId, dummyname); END;

How can I add the id value of B with rootId value of A via the DBFlow library?

Thank you.

**Comment by TeddyGammel** [comment]
DBFlow team, any update on this?

**Comment by TeddyGammel** [comment]
@agrosner , request help on this matter. Thank you.

**Comment by agrosner** [comment]
```java

Trigger.create("trigger_name").after()
  .insert(A.class)
  .begin(new Insert(B.class)
    .columns(id, name).values(...))
  .enable();

```

This should help. Sorry for late reply.
