### ISSUE TITLE
Observability

### ISSUE THREAD

**Issue by RimonGazi** [Raizlabs/DBFlow#1012]
https://github.com/Raizlabs/DBFlow/blob/master/usage2/Observability.md
Describe the Observability but i dont understand how i know which filed is changed and and how i get the 
changed value .

**Comment by aimanbaharum** [comment]
I'm facing the same issue as well. How do we register for a model changed (save, insert, delete, update) and observe it from a different class?

**Comment by RimonGazi** [comment]
Register the Observer:

FlowContentObserver observer = new FlowContentObserver();

onCreate
observer.registerForContentChanges(context, MyModelClass.class);
observer.addModelChangeListener(new OnModelStateChangedListener() {
  @Override
  public void onModelStateChanged(@Nullable Class<? extends Model> table, BaseModel.Action action, @NonNull SQLCondition[] primaryKeyValues) {
    // do something here
  }
});

onDestroy
observer.unregisterForContentChanges(context);
