### ISSUE TITLE
Error callback does not get called

### ISSUE THREAD

**Issue by narendrakothamire** [Raizlabs/DBFlow#1014]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Bug

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
Error callback does not get called if i try to delete a row that does not exist also when update the row that does not exist

**Comment by agrosner** [comment]
Sorry for the late reply, what callback are you speaking of?

**Comment by narendrakothamire** [comment]
If i do transaction, I get success and error callback like this

transaction
    .success(new Transaction.Success() {
       @Override
       public void onSuccess(Transaction transaction) {
          // called post-execution on the UI thread.
       }
   })
   .error(new Transaction.Error() {
       @Override
       public void onError(Transaction transaction, Throwable error) {
          // call if any errors occur in the transaction.
       }
   });

**Comment by agrosner** [comment]
you can create a custom `ITransaction` which holds onto the value for you:
```
public class DeleteTransaction implements ITransaction {

        boolean success = false;

        private final BaseModel model;

        public DeleteTransaction(BaseModel model) {
            this.model = model;
        }

        @Override
        public void execute(DatabaseWrapper databaseWrapper) {
            success = model.delete(databaseWrapper);
        }

        public boolean isSuccess() {
            return success;
        }
    }
```

Then call in onSuccess() `transaction.transaction()`, cast it to your type and then retrieve if it was successful or not. Not very clean, but it works.
