### ISSUE TITLE
sqlcipher return null if row contain big string field

### ISSUE THREAD

**Issue by MR-omid** [Raizlabs/DBFlow#1016]
hi,
i encrypt plain text database and decrypt again and see all row exists, but problem is on my android application.
one row returned as null if one of field contain very big string.
in plain text database load all rows normally.
i think is bug on sqlcipher or maybe require config before decrypt database like set page size or any other load option.
sorry for my bad english and thanks for quick reply if possible.

**Comment by agrosner** [comment]
I am not sure but def does not sound like a DBFlow bug.
