### ISSUE TITLE
"Delete If Migration Needed" support

### ISSUE THREAD

**Issue by ssawchenko** [Raizlabs/DBFlow#1020]
DBFlow Version: 3.1.1
Issue Kind: Question

Description: 
Is there a way to have DBFLow automatically recreate the DB if a migration is needed? During beta testing it is not imperative that our data is kept, and I would like to avoid forcing users to uninstall and reinstall if possible. 

Is this already possible? I have gone over the docs and could not find reference to such a thing, and my google foo is coming up empty.

**Comment by agrosner** [comment]
create a custom migration that deletes the full db, and reopens it.

**Comment by agrosner** [comment]
This should help (https://github.com/Raizlabs/DBFlow/blob/master/usage2/Migrations.md)
