### ISSUE TITLE
How to execute sql "UPDATE Ant SET count = count + 1" use Wrapper Language?

### ISSUE THREAD

**Issue by yisizhu520** [Raizlabs/DBFlow#1021]
How to make a column auto increment  by using Wrapper Language? Should I query the column 'count' first and then set it +1? There is any easy way to implement this? Thanks a lot!

**Comment by agrosner** [comment]
autoincrementing should be done via `@Column(autoincrement = true)` so inserting will autoincrement it for you. Otherwise to what you're doing try this:
```
SQLite.update(Ant.class).set(Some_Table.count.eq(Some_Table.count).plus(1)
```
