### ISSUE TITLE
with Data binding not working

### ISSUE THREAD

**Issue by captain-miao** [Raizlabs/DBFlow#1024]
DBFlow Version:4.0.0-beta1
Issue Kind (Question):

Description: 

use Data binding in project

    dataBinding {
        enabled = true
    }

compile error:

error: package ***.databinding does not exist

**Comment by agrosner** [comment]
doesnt sound like a DBFlow issue. check to ensure that you dont have any intermediate compile issues in your project.

**Comment by captain-miao** [comment]
It's cause by Android-apt

**Comment by AugustoAleGon** [comment]
How did you solve it? @captain-miao

**Comment by captain-miao** [comment]
@AugustoAleGon I give it up

**Comment by AugustoAleGon** [comment]
I had the same problem. I solved stop using apt-android and migrate it.
