### ISSUE TITLE
Cannot create/insert in new table: android.database.sqlite.SQLiteException: no such table: "TableName" 

### ISSUE THREAD

**Issue by avinashs95** [Raizlabs/DBFlow#1025]
DBFlow Version: 4.0.0-beta1
Issue Kind  (Bug, Question, Feature): Question

Description: 
I was using DBflow for my models. After a long time I decided to add an extra model, But I am not able to do so. I am getting an exception saying "No such table". I tried cleaning the project, selecting "make project" and building again. Previously created models are working without any issue. 

> > 10-18 13:24:07.410 1547-1547/com.test.app E/SQLiteLog: (1) no such table: DummyTest
> 10-18 13:24:07.414 1547-1547/com.test.app D/AndroidRuntime: Shutting down VM
> 10-18 13:24:07.424 1547-1547/com.test.app E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                   Process: com.test.app, PID: 1547
>                                                                   java.lang.RuntimeException: Unable to start activity **ComponentInfo{com.test.app/com.test.app.HomeActivity}: android.database.sqlite.SQLiteException: no such table: DummyTest (code 1): , while compiling: INSERT INTO `DummyTest`(`name`) VALUES (?)**
>                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2452)
>                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535)
>                                                                       at android.app.ActivityThread.access$900(ActivityThread.java:154)
>                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
>                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                       at android.os.Looper.loop(Looper.java:152)
>                                                                       at android.app.ActivityThread.main(ActivityThread.java:5497)
>                                                                       at java.lang.reflect.Method.invoke(Native Method)
>                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>                                                                    **Caused by: android.database.sqlite.SQLiteException: no such table: DummyTest (code 1): , while compiling: INSERT INTO `DummyTest`(`name`) VALUES (?)**
>                                                                       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
>                                                                       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
>                                                                       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
>                                                                       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
>                                                                       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
>                                                                       at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
>                                                                       at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1006)
>                                                                       at com.raizlabs.android.dbflow.structure.database.AndroidDatabase.compileStatement(AndroidDatabase.java:59)
>                                                                       at com.raizlabs.android.dbflow.structure.ModelAdapter.getInsertStatement(ModelAdapter.java:64)
>                                                                       at com.raizlabs.android.dbflow.structure.ModelAdapter.getInsertStatement(ModelAdapter.java:51)
>                                                                       at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.insert(ModelSaver.java:83)
>                                                                       at com.raizlabs.android.dbflow.structure.ModelAdapter.insert(ModelAdapter.java:128)
>                                                                       at com.raizlabs.android.dbflow.structure.BaseModel.insert(BaseModel.java:95)
>                                                                       at com.test.app.HomeActivity.onCreate(HomeActivity.java:122)
>                                                                       at android.app.Activity.performCreate(Activity.java:6285)
>                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
>                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2405)
>                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535) 
>                                                                       at android.app.ActivityThread.access$900(ActivityThread.java:154) 
>                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380) 
>                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                       at android.os.Looper.loop(Looper.java:152) 
>                                                                       at android.app.ActivityThread.main(ActivityThread.java:5497) 
>                                                                       at java.lang.reflect.Method.invoke(Native Method) 
>                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
> 10-18 13:24:07.424 1547-1547/? D/AppTracker: App Event: crash

**Comment by fabiendem** [comment]
Hi,
Have you increased your database version number?

**Comment by avinashs95** [comment]
Sorry It just struck for me to uninstall and reinstall the app so that database gets deleted and created from the scratch (Guess this is same as increasing the database version number). I tried now and its working. Thank you

**Comment by andressalh** [comment]
Como eu eu faço isso?

**Comment by rileymanda** [comment]
Simply delete your app from the emulator/or mobile device,then run clean project,followed by build,then run(to reinstall the apk on your emulator or device).For aslong as SQLIte cannot find your table:Means two things could have possibly occured:1.Your localhosts activities changed,meaning what the device has stored in your SQLIte db is old,or has recently changed..2..This could be a change in your table name in your localhost,or a change in db name or ip address.

**Comment by junery115** [comment]
Well this might help someone in the future, i had a kinda similar problem but in my case the issue was that the table wasn't being created. After I modified the sql syntax and added a trailing "," at the end of the last column value, so after day of combing the internet, i finally realized it just had that trailing comma and took it out and the code ran like a breeze. Did have to change the db name too which just created a new db.

**Comment by loquitowen** [comment]
thanks for your message…
I have this strange problem,but the Arthur does not reply my issue..
I have some new situations, I can insert a response body which had been translated in json by gson,i insert it success and its string count is about 15000+, but I can insert this one….
By the wait,this cannot insert issue happend in a large table with about 40 properties..the one can insert only has 7 properties
Now I will have more test to find the problem,i always uninstall the app before a new version,so I think I needn’t to update the version of the database.
Thanks for your replay~
:D
