### ISSUE TITLE
OnModelStateChangedListener receives invalid SQLConditions

### ISSUE THREAD

**Issue by virusman** [Raizlabs/DBFlow#1027]
DBFlow Version: 3.1.1 (should be the same in 4.0.0)
Issue Kind (Bug, Question, Feature): Bug

Description: 
OnModelStateChangedListener receives SQLConditions without an operator that can't be used directly by calling SQLite.select().from(...).where(primaryKeyValues).
This can be fixed by changing value() to eq() here:
https://github.com/Raizlabs/DBFlow/blob/master/dbflow/src/main/java/com/raizlabs/android/dbflow/runtime/FlowContentObserver.java#L252

**Comment by agrosner** [comment]
in `develop`.
