### ISSUE TITLE
Get model that was deleted in FlowContentObserver

### ISSUE THREAD

**Issue by virusman** [Raizlabs/DBFlow#1028]
DBFlow Version: 3.1.1, 4.0.0
Issue Kind (Bug, Question, Feature): Feature

Description: 
FlowContentObserver notifies about delete actions after they've completed, so there is no way to get the original model's fields. It'd be nice if there was a way to get the model or have an event that fires before delete operation is complete.

**Comment by agrosner** [comment]
If you use the `OnModelStateChangedListener`, you will receive a `SQLCondition[]` of Primary keys of the objects that were deleted.
