### ISSUE TITLE
count() returns the row value instead of an actual count

### ISSUE THREAD

**Issue by virusman** [Raizlabs/DBFlow#1029]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Bug

Description: 
I have the following statement:
`SQLite.select().from(Fax.class).where(Fax_Table.documentKey.eq(fax.documentKey)).count()`
It returns an ID of the first object that matches instead of the actual count(*)

**Comment by agrosner** [comment]
```
SQLite.selectCountOf()...
```
