### ISSUE TITLE
Build fails adding ContentProvider.

### ISSUE THREAD

**Issue by wintersandroid** [Raizlabs/DBFlow#103]
I updated to 1.6.0, and attempted to add a content provider to the project, the compilation fails, I get 200 errors, but cant find any error directly related to the content provider. My app also uses androidannotations (3.2)

This is what I added.
```
package nz.org.winters.android.nzmobileaccountwidget.provider;

import com.raizlabs.android.dbflow.annotation.provider.ContentProvider;

import nz.org.winters.android.widgetscommon.BuildConfig;
import nz.org.winters.android.widgetscommon.database.AppDatabase;

/**
 * Created by mathew on 25/02/15.
 */
@ContentProvider(authority = AppContentProvider.AUTHORITY,
        databaseName = AppDatabase.NAME,
        baseContentUri = AppContentProvider.BASE_CONTENT_URI)
public class AppContentProvider {
  public static final String AUTHORITY = "nz.org.winters.android.nzmobileaccountwidget.provider";
  public static final String BASE_CONTENT_URI = "content://";
}
```
and in manifest..
```
 <provider
        android:authorities="nz.org.winters.android.nzmobileaccountwidget.provider"
        android:exported="false"
        android:name="nz.org.winters.android.nzmobileaccountwidget.provider.AppContentProvider$Provider"/>
```
The $Provider class never gets created.

I have tried compiling with --debug e.t.c., but it doesnt give me an answer, Just that none of the classes that are generated by the apt plugin are able to be found. The provider is not created, appears to be the problem.

**Comment by wintersandroid** [comment]
I just looked at the validator. I see I need to also create a end point, compiling before creating the end point will fail. The message didn't appear in the log.

**Comment by agrosner** [comment]
It appears in the log, it's just buried deep down in the other "error" messages that says it fails to find the generated classes. There must be a nicer or cleaner way of passing true valid error messages, but since the ```apt``` plugin is a little hacky as the Android plugin doesn't support that step in the compile, it may not be fixable or improvable.  

I guess the next step would be to make it clear in the usage docs that you must define at least one ```@TableEndpoint``` for the ```@ContentProvider``` to be valid.

**Comment by agrosner** [comment]
fixed in docs
