### ISSUE TITLE
Add support for custom type converters to override default implementations.

### ISSUE THREAD

**Issue by trevjonez** [Raizlabs/DBFlow#1030]
DBFlow Version: 4.+
Issue Kind (Bug, Question, Feature): Feature

Description: 
At current DBFlow 4 ships with default converters for types such as `java.util.Date`, `java.util.Calendar`, and `java.util.UUID`. 

In my work flow we have a case where there is a "magic number" for all of these types that specify that the value should be treated as null but it still needs to be sent to the server. Due to limitations with protocols outside of our control we must send any parameter being set as null as a string "_-NULL-_". 

So it would be great to be able to customize the UUID converter implementation so that the database entries read as "_-NULL-_". This sort of thing helps with debugging sessions since any direct monitoring of database values results in a human readable format.

As always I would be glad to implement, just want to spur a discussion about how to proceed. 

Ideally I think we should make the general structure of the configuration portions injectible to allow for more advanced configurations. Also there are quite a few other options exposed by the android DB system that are not exposed and you have to do some not so friendly things to hook into the underlying API's. Maybe a good time to revisit some of the config and holder structuring.

**Comment by agrosner** [comment]
try it now. in `develop`. sorry it took sooo long.
