### ISSUE TITLE
How to use sqlite date function to perfrom a query on epoch column

### ISSUE THREAD

**Issue by abeemukthees** [Raizlabs/DBFlow#1031]
DBFlow Version: 3.1.1
Issue Kind (Question):

Description: 

How to get the count of same day entries. I'm storing date as epoch.

I used the following query statement to perform the query in DBbrowser & I getting the expected result.

**SELECT COUNT(appointmentId) AS entries, DATE(appointmentOn, 'unixepoch') as date FROM  AppointmentModel GROUP BY DATE(appointmentOn, 'unixepoch')**

But how to perform the same in DBFlow ?

**Comment by agrosner** [comment]
try 
```java"
Method unixDateMethod = new Method("DATE", AppointmentModel_Table.appointmentOn,
     PropertyFactory.from("unixepoch");
SQLite.select(Method.count(Some_Table.appointmentId.as("entries")), unixDateMethod.as("date"))
     .from(AppointmentModel.class)
     .groupBy(unixDateMethod)
     .queryCustomList(AppointmentQueryModel.class);
 ```

You need to create `AppointmentQueryModel`:


```java
@QueryModel(database = ...)
public class AppointmentQueryModel extends BaseQueryModel {

  @Column
  int entries

  @Column
  long date; // no sure type here, might need custom converter to type?

}
```

**Comment by agrosner** [comment]
this is should answer it, might not be fully correct, but should give you the idea.

**Comment by abeemukthees** [comment]
I'll try it, thank you very much
