### ISSUE TITLE
Support Storing Database in other locations inside app-private storage

### ISSUE THREAD

**Issue by justjanne** [Raizlabs/DBFlow#1033]
Requested feature: Allow storing the database in a customizable location inside app-private storage.

Use Case: Storing it in the cache directory, so it can be treated differently (and easier deleted) from actual app data, in an app where a DBFlow database is only used to cache data from a remote relational database.

**Comment by agrosner** [comment]
since we're using `SQLiteOpenHelper` as the basis for opening database files, not currently supported. You can though, keep it in memory by specifying `@Database(inMemory=true)` if you wish instead.

**Comment by hannesa2** [comment]
In SQLiteOpenHelper I use the constructor for this approach

```

    public DatabaseHelper(final Context context) {
        super(context, getDBPath(context) + File.separator + DATABASE_NAME, null, DATABASE_VERSION);
    }

    private String getDBPath(Context context) {
        if (Environment.getExternalStorageState().equals(android.os.Environment.MEDIA_MOUNTED)) {
            return Environment.getExternalStorageDirectory().getAbsolutePath();
        } else {
            return context.getDatabasePath(DATABASE_NAME).getAbsolutePath();
        }
    }
```
