### ISSUE TITLE
ForeignKey | Define column name of referenced class

### ISSUE THREAD

**Issue by paraqles** [Raizlabs/DBFlow#1036]
## Setup:
- DBFlow Version: `4.0.0-beta1`
- Target Platform: `Android 23`
- Gradle/Maven: `Gradle v2.10` `Android Gradle Plugin v2.0.0`
- Build Tools: `24.0.3`
- Kotlin: `1.0.3` with `kapt`

_Issue Kind:_ Question
## Description:

I want to reference a Model from another Model (See below).
The problem with the version below is, I get 

```
Cannot find symbol method getFrom()
Cannot find symbol method getTo()
Cannot find symbol method getFrom()
Cannot find symbol method getTo()
```

``` Kotlin
@Table(database = MMHDatabase::class)
class Transaction(from: Account? = null, value: Float = 0.0f, to: Account? = null, id: Long = -1) : BaseModel() {
    companion object {
        fun get(id: Long) : Transaction? {
            return (select
                    from Transaction::class
                    where (Transaction_Table.id eq id)).result
        }
    }

    @PrimaryKey(autoincrement = true)
    var id: Long = -1

    @ForeignKey
    var from: Account? = null

    @Column
    var value: Float = 0.0f

    @ForeignKey
    var to: Account? = null
}
```

Corresponding generated code (Line 3 and 9):

``` Java
 1public final void bindToInsertValues(ContentValues values, Transaction model) {
 2    if (model.getFrom() != null) {
 3      values.put("from_id", model.getFrom().getFrom());
 4    } else {
 5      values.putNull("from_id");
 6    }
 7    values.put("value", model.getValue());
 8    if (model.getTo() != null) {
 9      values.put("to_id", model.getTo().getTo());
10    } else {
11      values.putNull("to_id");
12    }
13  }
```

and (Line 3 and 9)

``` Java
 1 public final void bindToInsertStatement(DatabaseStatement statement, Transaction model, int start) {
 2    if (model.getFrom() != null) {
 3      statement.bindLong(1 + start, model.getFrom().getFrom());
 4    } else {
 5      statement.bindNull(1 + start);
 6    }
 7    statement.bindDouble(2 + start, model.getValue());
 8    if (model.getTo() != null) {
 9      statement.bindLong(3 + start, model.getTo().getTo());
10    } else {
11      statement.bindNull(3 + start);
12    }
13  }
```

I expected it would use the get method of the primary key of the `Account` class which would be `getId()`.

**Comment by paraqles** [comment]
I got it nearly working with:

```Kotlin
@Table(database = MMHDatabase::class)
class Transaction(from: Account? = null, value: Float = 0.0f, to: Account? = null, id: Long = -1) : BaseModel() {
    companion object {
        fun get(id: Long) : Transaction? {
            return (select
                    from Transaction::class
                    where (Transaction_Table.id eq id)).result
        }
    }

    @PrimaryKey(autoincrement = true)
    var id: Long = -1

    @ForeignKey(
        references = arrayOf(
            ForeignKeyReference(
                columnName = "from_account_id",
                columnType = Long::class,
                foreignKeyColumnName = "id",
                referencedGetterName = "getId",
                referencedSetterName = "setId",
                referencedFieldIsPrivate = true
            )
        )
    )
    var from: Account? = null

    @Column
    var value: Float = 0.0f

    @ForeignKey (
        references = arrayOf(
            ForeignKeyReference(
                columnName = "to_account_id",
                columnType = Long::class,
                foreignKeyColumnName = "id",
                referencedGetterName = "getId",
                referencedSetterName = "setId",
                referencedFieldIsPrivate = true
            )
        )
    )
    var to: Account? = null
}
```

**Comment by xanscale** [comment]
same problem

`  @Override
  public final void bindToInsertStatement(DatabaseStatement statement, Voce model, int start) {
    statement.bindLong(1 + start, model.getAnno());
    statement.bindDouble(2 + start, model.getValore());
    String refvaloreString = model.getValoreString();
    if (refvaloreString != null)  {
      statement.bindString(3 + start, refvaloreString);
    } else {
      statement.bindNull(3 + start);
    }
    if (model.getBanca() != null) {
      statement.bindLong(4 + start, model.getBanca().getBanca());
    } else {
      statement.bindNull(4 + start);
    }
    if (model.getIndicatore() != null) {
      statement.bindLong(5 + start, model.getIndicatore().getIndicatore());
    } else {
      statement.bindNull(5 + start);
    }
  }`

but the correct code should be

`  @Override
  public final void bindToInsertStatement(DatabaseStatement statement, Voce model, int start) {
    statement.bindLong(1 + start, model.getAnno());
    statement.bindDouble(2 + start, model.getValore());
    String refvaloreString = model.getValoreString();
    if (refvaloreString != null)  {
      statement.bindString(3 + start, refvaloreString);
    } else {
      statement.bindNull(3 + start);
    }
    if (model.getBanca() != null) {
      statement.bindLong(4 + start, model.getBanca().getId());
    } else {
      statement.bindNull(4 + start);
    }
    if (model.getIndicatore() != null) {
      statement.bindLong(5 + start, model.getIndicatore().getId());
    } else {
      statement.bindNull(5 + start);
    }
  }`

**Comment by paraqles** [comment]
With the combination of
`referencedGetterName` and `referencedSetterName` in conjunction with `referencedFieldIsPrivate = true`

I get:

```Java
@Override
  public final void bindToInsertValues(ContentValues values, Transaction model) {
    if (model.getFrom() != null) {
      values.put("from_account_id", model.getFrom().getId());
    } else {
      values.putNull("from_account_id");
    }
    values.put("value", model.getValue());
    if (model.getTo() != null) {
      values.put("to_account_id", model.getTo().getId());
    } else {
      values.putNull("to_account_id");
    }
  }
```
and
```Java
  @Override
  public final void bindToInsertStatement(DatabaseStatement statement, Transaction model, int start) {
    if (model.getFrom() != null) {
      statement.bindLong(1 + start, model.getFrom().getId());
    } else {
      statement.bindNull(1 + start);
    }
    statement.bindDouble(2 + start, model.getValue());
    if (model.getTo() != null) {
      statement.bindLong(3 + start, model.getTo().getId());
    } else {
      statement.bindNull(3 + start);
    }
  }
```

So that kind of is solved, unfortunately I have now an `'infix' modifier is required on 'eq' in 'IntProperty'` problem (But seems like a different error)

**Comment by xanscale** [comment]
can you post your model?

**Comment by paraqles** [comment]
@xanscale: please have a look at my second post.

**Comment by xanscale** [comment]
@paraqles i have very simple model

```
@Table(database = AppDatabase.class)
public class Voce extends BaseModel {

	@PrimaryKey(autoincrement = true)
	private long id;

	@ForeignKey
	private Banca banca;

	@ForeignKey
	private Indicatore indicatore;
}
```

how can i resolve?

**Comment by paraqles** [comment]
```Java
@Table(database = AppDatabase.class)
public class Voce extends BaseModel {

    @PrimaryKey(autoincrement = true)
    private long id;

    @ForeignKey(
        references = @ForeignKeyReference(
                columnName = "banca",
                columnType = Long.class,
                foreignKeyColumnName = "id",
                referencedGetterName = "getId",
                referencedSetterName = "setId",
                referencedFieldIsPrivate = true
            )
        )
    )
    private Banca banca;

    @ForeignKey(
        references = @ForeignKeyReference(
                columnName = "indicatore",
                columnType = Long.class,
                foreignKeyColumnName = "id",
                referencedGetterName = "getId",
                referencedSetterName = "setId",
                referencedFieldIsPrivate = true
            )
        )
    )
    private Indicatore indicatore;
}
```

Assuming `Banca` and `Indicatore` are also derived from `BaseModel` and thier **ID** field is `id` and is of type `Long`. Also there must be getter and setter called `setId` and `getId`.

**Comment by paraqles** [comment]
It is kind of ugly and not like it is stated in the comment of the corresponding code, but seems solved.

**Comment by xanscale** [comment]
i confirm that works that workaround. I'm hoping for an official response

**Comment by xanscale** [comment]
@paraqles  i have found another workaround

```
public class Indicatore extends BaseModel {
   public Long getIndicatore() {return id;}
}
```

i don't know if is better or not :D

**Comment by paraqles** [comment]
Maybe, but in my example it would be:
```Kotlin
class Account : BaseModel() {
    fun getFrom() : Int = id
}
```

that is totally not clear what is happening.

**Comment by xanscale** [comment]
@paraqles i think more like this. each model class must have a method that return the primarykey that is called getMODEL, like this:

```
class From : BaseModel() {
    fun getFrom() : Int = id
}
```

**Comment by xanscale** [comment]
@agrosner any opinion?

**Comment by skoenen** [comment]
Maybe, but beside that, the method is named after the variable name for `@ForeignKey` and not after the referenced model name.

In my case the model name is `Account` and the `Transaction` model has a `from` (which is the source `Account`) and a `to` (target `Account`).

When you see the model needs a `get$Model` method it would be `getAccount` for the `Account` model, which is not the expected `getFrom` from the `Transaction` model `@ForeignKey` `from`.

That is the problem I see here and the only way to solve that is giving the parameters from above to the `@ForeignKey` annotation.
Which is not a big problem. The problem here is more the sentence in the code about the `references` property:

> This no longer required as the library will auto-generate references for you based on the other table's primary keys.
> [com.raizlabs.android.dbflow.annotation.ForeignKey](https://github.com/Raizlabs/DBFlow/blob/530cd6c6ccc4ef64c4a4638fd41e8bc0472c4fbf/dbflow-core/src/main/java/com/raizlabs/android/dbflow/annotation/ForeignKey.java#L16)

From this sentence I expected, that the processor recognises that this is a reference to another `Model` and tries to find the `@PrimaryKey` of that.
I didn't expect, that it just uses the `@ForeignKey` variable name as a getter method.

If this reflection should be avoided, it would be ok if it took the `getId` as the method name.

**Comment by paraqles** [comment]
@xanscale: you assume that the model I'm referencing is called `From` and not `Account`.

The misleading sentence here is more the one in `ForeignKey.java`
> This is no longer required as the library will auto-generate references for you based on the other table's primary keys.
```Java
ForeignKeyReference[] references() default {};
```
> [com.raizlabs.android.dbflow.annotation.ForeignKey.java](https://github.com/Raizlabs/DBFlow/blob/530cd6c6ccc4ef64c4a4638fd41e8bc0472c4fbf/dbflow-core/src/main/java/com/raizlabs/android/dbflow/annotation/ForeignKey.java#L16)

From this sentence I expect that the processor uses reflection to find the `@PrimaryKey` of the referenced model and then uses the appropriate getter and not the reference holding variable name as getter on the referenced model.
If the reflection should be avoided, it can be a convention, that a model has to implement the `getId` or `getPrimaryKey` method which is more obvious what is expected from the model.

**Comment by xanscale** [comment]
@paraqles so

```
class Account : BaseModel() {
    fun getAccount() : Int = id
}
```

i know that is a workaround and im waiting for an official response from @agrosner

**Comment by rogerhu** [comment]
I think this applies to private fields.  If you take away the private fields, this problem goes away?

**Comment by xanscale** [comment]
@rogerhu if i remove foreignKey and relative field problem goes away.

i think this is common and big problem. no one else has the same problem?

**Comment by rogerhu** [comment]
Change your primary key columns to be public...does this issue go away?

**Comment by mister11** [comment]
I had that problem few minutes ago and changing from private to public solved an issue

**Comment by xanscale** [comment]
@rogerhu package access solve issue perfectly.

**Comment by EdwardvanRaak** [comment]
Well I had the same problem and it was fixed with a public primary key. But this seems like a major bug introduced in the last version of this library right?

**Comment by xanscale** [comment]
PACKAGE LEVEL is enough

**Comment by mister11** [comment]
@xanscale As I've said above, Kotlin has that same problem and everything is public by default. Workaround is somewhere in this thread, but manually writing methods to support library bugs is not really nice solution

**Comment by agrosner** [comment]
since this is Kotlin, each property is treated private with associated getters and setters. I think it's getting confused because its calling :
```kotlin
 if (model.getFrom() != null) {
       statement.bindLong(1 + start, model.getFrom().getFrom());
```
Instead of :
```kotlin
 if (model.getFrom() != null) {
       statement.bindLong(1 + start, model.getFrom().getId());
```
I think that's the correct way you mention?

**Comment by agrosner** [comment]
found issue! fixed in `develop`. Sorry for no response (I was on vacation for a little while).

**Comment by paraqles** [comment]
Will this also work for an other `@PrimaryKey` than `id` (for example a string `name`)?

**Comment by xanscale** [comment]
@agrosner this bug affect java only projects too. your fix seams to solve only kotlin. i'm wrong?
