### ISSUE TITLE
Disable caching on certain queries

### ISSUE THREAD

**Issue by markfili** [Raizlabs/DBFlow#1037]
DBFlow Version: 4.0.0-beta1
Issue Kind (Bug, Question, Feature): Question

Description: 
Is it possible to disable caching on some queries?
For example when one query creates an object with some data while the other requires all of it, the first object is returned instead of the one with everything in it.

Thank you, great lib!

**Comment by agrosner** [comment]
no not currently able to disable caching, but it seems like an interesting idea. Ill keep it in mind.

**Comment by agrosner** [comment]
added a method:
```java

select(My_Table.column, My_Table.column2)
  .from(My.class)
  .disableCaching()
  .queryList();

```

**Comment by markfili** [comment]
woooo! you are most kind! thank you very much! have another great year!
