### ISSUE TITLE
DBFlow 3.1.1 version issue

### ISSUE THREAD

**Issue by DavidMont** [Raizlabs/DBFlow#1039]
```
Error:(48, 0) Could not find method apt() for arguments [com.github.Raizlabs.DBFlow:dbflow-processor:3.1.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
<a href="openFile:/home/android/Android/collaboration/FireWall/aFWall/build.gradle">Open File</a>
```

```
apt "com.github.Raizlabs.DBFlow:dbflow-processor:3.1.1"
compile "com.github.Raizlabs.DBFlow:dbflow-core:3.1.1"
compile "com.github.Raizlabs.DBFlow:dbflow:3.1.1"
compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:3.1.1@aar"
compile "net.zetetic:android-database-sqlcipher:3.5.1"
```

Please help me, I cant run a project because of this error I dont know.

**Comment by DavidMont** [comment]
This is the one I tried https://github.com/ukanth/afwall

**Comment by paraqles** [comment]
It seems that your gradle does not know about the Annotation Processor (apt).
Have a look at the [readme](https://github.com/Raizlabs/DBFlow#including-in-your-project) at the point **Including in your project**

> We need to include the apt plugin in our classpath to enable Annotation Processing

**Comment by agrosner** [comment]
please follow the easy [including in your project steps](https://github.com/Raizlabs/DBFlow#including-in-your-project)
