### ISSUE TITLE
Leaking TransactionQueue when no @Table is defined for @Database [low priority]

### ISSUE THREAD

**Issue by mickele** [Raizlabs/DBFlow#1041]
DBFlow Version: **3+** I believe (reproduced on HEAD)
Issue Kind (Bug, Question, Feature): **Bug**

Description: 
I consider this low priority since usually when you declare a `@Database` you want to declare at least one `@Table` for it, even when testing.

I'll try to explain the best way I can, but the tl;dr; is:
A `@Database` with no `@Table` will not be registered at the `DatabaseHolder` and its `TransactionQueue` will never be interrupted which results in 1 thread waiting.

**Detailed version:**
1. In the tests of DBFlow there's a `@Database` declared at `myDB.java`
2. There's no `@Table` declaration for this database
3. The constructor of the generated `myDBtest_Database.java` (extends DatabaseDefinition) will be inserted at the `GeneratedDatabaseHolder`
4. The constructor of the `DatabaseDefinition` will create a `TransactionManager` for its own, which will create a `DefaultTransactionQueue/Thread` and wait
5. `myDBtest_Database` will never call `DatabaseHolder#putDatabaseForTable` since there's no table declared for it and because of that, none of the `DatabaseHolder` maps will be populated with the myDB-related classes
6. When `FlowManager` is being reset/destroyed and the `globalDatabaseHolder.databaseClassLookupMap` is being scanned, it won't find any myDB-related classes and won't stop the TransactionQueue created at step 4.

I think a fix would be to DatabaseHolder also register a database without Tables, with a simple `putDatabase` that takes no `Table` param or not injecting this database definition at the `GeneratedDatabaseHolder` if no `@Table` was defined.

But to be honest I don't know if this is the best solution and/or viable. What do you think?

**Comment by agrosner** [comment]
fixed issue now in `develop`.
