### ISSUE TITLE
add types to callback signature

### ISSUE THREAD

**Issue by yoooyle** [Raizlabs/DBFlow#1043]
DBFlow Version: 4.0.0 beta1 and current master
Issue Kind (Bug, Question, Feature):
Bug

Description:

found raw type: com.raizlabs.android.dbflow.structure.database.transaction.QueryTransaction
  missing type arguments for generic class com.raizlabs.android.dbflow.structure.database.transaction.QueryTransaction<TResult>

https://github.com/Raizlabs/DBFlow/blob/4.0.0-beta1/dbflow/src/main/java/com/raizlabs/android/dbflow/structure/database/transaction/QueryTransaction.java#L31

**Comment by agrosner** [comment]
in `develop` for `4.0.0-beta2`
