### ISSUE TITLE
Update only specific column

### ISSUE THREAD

**Issue by nirwannursabda** [Raizlabs/DBFlow#1049]
I'm using DBFlow 4.0.0-beta1

I have model:

@Table(database = MyDatabase.class, name = "hero")
public class Hero extends [BaseModel{](url)

    @Column(name = "id")
    @PrimaryKey
    private int id;
    
    @SerializedName("code")
    @Column(name = "code")
    private String code;

    @SerializedName("name")
    @Column(name = "name")
    private String name;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

I'm insert value
Hero hero = new Hero();
hero.setId(390);
hero.setCode("823kjh12u3i1k2j3k1j2kj1h2jk32j3kj1h");
hero.setName("TARFIRE");
hero.save();

Im trying to update only name column

Hero hero = new Hero();
hero.setId(390);
hero.setName("TARFIRE");
hero.update();

but i had code column to be null in my row table

I'm i missing something?

**Comment by nirwannursabda** [comment]
closed with using SQLiteWrapper

https://github.com/Raizlabs/DBFlow/blob/master/usage2/SQLiteWrapperLanguage.md

But i hope there is simpler way than this

Thank You

**Comment by xxxifan** [comment]
yes, if it can only update non-null field would be nice, but I think it'll break API design and the purpose is not clear (what if we want to update a field to null?). So I'm gonna write a helper/util to do this :)

**Comment by yeduRaghav** [comment]
@nirwannursabda The link is broken, could you please provide the solution again ?

**Comment by nirwannursabda** [comment]
the idea behind this is upsert. But event native sqlite not support this. Just have replace function that set code column to be null when you dont operate 
1. select -> replace or
2. select -> update
to bring existing data

I get this example from this, I have not used dbflow for a long time. Hope it help
https://agrosner.gitbooks.io/dbflow/content/SQLiteWrapperLanguage.html

// Native SQL wrapper
SQLite.update(Ant.class)
  .set(Ant_Table.type.eq("other"))
  .where(Ant_Table.type.is("worker"))
    .and(Ant_Table.isMale.is(true))
    .async()
    .execute(); // non-UI blocking

**Comment by abiemann** [comment]
what I do is create a new table for each variable that is optional. Then use a ForeignKey to reference back to the main object.
