### ISSUE TITLE
One to Many where condition how to

### ISSUE THREAD

**Issue by andrewpros** [Raizlabs/DBFlow#1051]
DBFlow Version: 3.1.1
Issue Kind Question:

Well i have done one to many relation in my project, it works but the thing is i need a condition.

It is simple Title and TitleLang tables for localization, Title can have many TitleLang, so in Title i have added a function with OneToMany annotation.

I query the Title and i have a list of Titles and every one of them has a list of TitleLang items, but all of them.

How can i use DBflow OneToMany options to provide a where condition or some parameter that will allow me not only to get all related data but also limit them, in my project to specific language ID.

Yes i know i can just set it in the OneToMany method query call, but i need a way to set from outside.

Now i have:

List<TitleItem> titleItems = SQLite.select().from(TitleItem.class).queryList();

and i can't set it externally

Another issue is that OneToMany method is always called, how to use it only when i want?

Well the oblivious simple answer and question at the same time is - should i just ditch the OneToMany functionality and make plain'old joins?

**Comment by tux-world** [comment]
@andrewpros  could you help me on this topic? https://github.com/Raizlabs/DBFlow/issues/1097 Thanks

**Comment by agrosner** [comment]
yes you probably want to ditch the functionality if you want more control over it.
