### ISSUE TITLE
what's the meaning of foreignKeysSupported

### ISSUE THREAD

**Issue by xanscale** [Raizlabs/DBFlow#1052]
in my project i use @ForeignKey without specify foreignKeysSupported to true, and seams works.

foreignKeysSupported default value are FALSE. and i use 4beta1

what's the difference from foreignKeysSupported TRUE and FALSE?

thx for support, i know that is section is not for support but i don't know where to ask

**Comment by agrosner** [comment]
Enforced at `@Database` SQLite level. Otherwise DBFlow does not complain if you break foreign key constraints.
