### ISSUE TITLE
Bug using Enum inside Where condition

### ISSUE THREAD

**Issue by xanscale** [Raizlabs/DBFlow#1054]
DBFlow Version: develop-SNAPSHOT
Issue Kind (Bug, Question, Feature): Bug

Description: 
`SQLite.select().from(Bonus.class).where(Bonus_Table.market.eq(Market.CERT_X)).queryList();`

`android.database.sqlite.SQLiteException: no such column: CERT_X (code 1): , while compiling: SELECT * FROM `Bonus` WHERE `market`=CERT_X ORDER BY `underlyingName` ASC`

i think SELECT should be:

`SELECT * FROM `Bonus` WHERE `ask`!=0.0 AND `market`='CERT_X' ORDER BY `underlyingName` ASC`

with this converter works

```
public class CustomConverter extends TypeConverter<String, Market> {
	@Override
	public String getDBValue(Market model) {
		return model.name();
	}

	@Override
	public Market getModelValue(String data) {
		return Market.valueOf(data);
	}
}
```

this workaround works for "eq" but not for "in"

"in" seams not use converter

same converter produce this select that works

`SELECT * FROM `Bonus` WHERE `ask`!=0.0 AND (`typeBarrier`='CONTINUA' OR `typeBarrier`='DISCRETA') ORDER BY `underlyingName` ASC`

and this that not works

`SELECT * FROM `Bonus` WHERE `ask`!=0.0 AND `typeBarrier` IN (DISCRETA,CONTINUA) ORDER BY `underlyingName` ASC `

**Comment by trevjonez** [comment]
Do you have a type converter registered for that enum?

**Comment by xanscale** [comment]
```
public class MarketConverter extends TypeConverter<String, Market> {
	@Override
	public String getDBValue(Market model) {
		return model.name();
	}

	@Override
	public Market getModelValue(String data) {
		return Market.valueOf(data);
	}
}
```


```
public enum Market {
	SEDEX("Sedex"),
	CERT_X("Cert-X");
	private final String label;

	Market(String label) {
		this.label = label;
	}

	@Override
	public String toString() {
		return label;
	}
}
```

**Comment by trevjonez** [comment]
Can you debug through it and see if it is an issue of case sensitivity? You are storing `Sedex`, but the enum is named `SEDEX`. I would imagine `valueOf` is comparing against `SEDEX` which is not equal to `Sedex`.

**Comment by xanscale** [comment]
.name() return SEDEX
toString() return Sedex

inside SQLite Database i have SEDEX

the problem is formal, sqlite does not accept SELECT syntax. need this character : '

**Comment by trevjonez** [comment]
Ah I see, buggy indeed.

**Comment by obuiron** [comment]
TypeConverter not needed for Enum in your case cause based on `.name()` & `.valueOf(...)`
DBFlow support out of the box enum as type as you can see in this [test](https://github.com/Raizlabs/DBFlow/blob/develop/dbflow-tests/src/test/java/com/raizlabs/android/dbflow/test/sql/EnumModel.java).

**Comment by xanscale** [comment]
@obuiron in test i don't see where clausole using Enum

**Comment by obuiron** [comment]
Your query seem correct, try without your custom enum TypeConverter.

```
public class Author extends BaseModel{
..
  @Column 
  private Status status;
  
  public Author() {}

  public Status getStatus() {
    return status;
  }

  public void setStatus(Status status) {
      this.status = status;
  }

  public static enum Status {
      OK,
      KO
  }
..

```

Query : `SQLite.select().from(Author.class).where(Author_Table.status.eq(Author.Status.OK)).querySingle()`

Generated query : `SELECT * FROM `Author` WHERE `status`='OK'`

**Comment by trevjonez** [comment]
There are some big changes with how type converters work in V4. These issues are likely related.

**Comment by xanscale** [comment]
@obuiron in version develop-SNAPSHOT without converter does not works.

**Comment by trevjonez** [comment]
I opened a PR #1055 to reveal the issues noted here. I am unfamiliar with all the details surrounding that bit of the codebase and am strapped for time so hopefully @agrosner or anyone else familiar with the design can grab that PR and work through it without much ceremony.

**Comment by agrosner** [comment]
in `develop`.

**Comment by xanscale** [comment]
confirm that fix works perfectly.

PS i love DBFlow, i try much ORM for android and found DBFlow the best. thz for your works, i will help the dev :)
