### ISSUE TITLE
Worng access to private generated propery via @ForeignKey 

### ISSUE THREAD

**Issue by liorzam** [Raizlabs/DBFlow#1058]
DBFlow Version: 4.0.0-beta1
Issue Kind : Bug

class 1:
`@Table(name = BaseEntity.TABLE_NAME,
        database = Database.class,
        insertConflict = ConflictAction.REPLACE)
public class BaseEntity {

    public static final String TABLE_NAME = "entities";

    @PrimaryKey
    private String entityId;

    public String getEntityId() {
        return entityId;
    }

    public void setEntityId(String id) {
        entityId = id;
    }
}`

and the class2:

`@Table(name = User.TABLE_NAME, database = Database.class)
  public class User {
    public static final String TABLE_NAME = "users";

    @ForeignKey(references = {@ForeignKeyReference(columnType = String.class,
                    columnName = BaseEntity.Columns.USER_ID,
                    foreignKeyColumnName = BaseEntity.Columns.ENTITY_ID)})
    public BaseEntity baseEntity;
}`

'User_Table' which generated by DBFlow tried to accsess direct to the property 'entityId' even its declared as private instead of model.getEntityId()

**Comment by liorzam** [comment]
notice that when i use 'referencedFieldIsPrivate = true'
its generated worng : model.getBaseEntity().getBaseEntity()'

**Comment by agrosner** [comment]
already fixed in `develop`. when you specify manually references, you have to specify the visibility in the annotation thats why it failed the first try. Second issue is fixed. will be in beta2
