### ISSUE TITLE
Upgrade database in DBFlow Android

### ISSUE THREAD

**Issue by ssatiz** [Raizlabs/DBFlow#1059]
We released a version of the application in Play Store which implemented DBFlow, now we wants to update the app into next version, in that we should add two new tables to the existing database using DBFlow. Can anyone help me on this?

**Comment by trevjonez** [comment]
If it is only new tables you can just increment the version number on the database class annotation.

**Comment by trevjonez** [comment]
https://github.com/Raizlabs/DBFlow/blob/master/usage2/Migrations.md

**Comment by ssatiz** [comment]
Thank you for the answer. But I have new columns for the existing tables also, how to upgrade for this?

**Comment by trevjonez** [comment]
following the usage guide posted above create a migration for version two.

Keep in mind the new tables are created before the migration steps are run

**Comment by Mrxxy** [comment]
Hi, i have the same question,too. I need update the app into next version,and i modify some data in some tables,what should i do for this update,and let users use new data?Thank you.
