### ISSUE TITLE
implement a way to use load() without extends BaseModel

### ISSUE THREAD

**Issue by xanscale** [Raizlabs/DBFlow#1060]
DBFlow Version: current
Issue Kind (Bug, Question, Feature): Feature

Description: 
stubbedRelationship require to use load() to load full object but if BaseModel are not required by DBFlow there should be a way to do same without extends BaseModel

**Comment by trevjonez** [comment]
You can use the adapter to load the model. Ultimately the load method (and all other methods) on the `Model` is just a convenience wrapper to functionality on the adapter class.

Keeping in mind that the generated `adapter` class is being merged into the generated `table` class in DBFlow 4+

**Comment by xanscale** [comment]
"Model is just a convenience wrapper"
i agree with you but for load method is not so easy to replace

i need to create another instance of object and make a query single using primary key manually?

would be better if there is a load(Model)

**Comment by agrosner** [comment]
```java
ModelAdapter<MyTable> adapter = FlowManager.getModelAdapter(MyTable.class);
adapter.load(model);
```

its located in `RetrievalAdapter`. I think this is pretty simple. If not make your own method in your class to do the same thing.

**Comment by xanscale** [comment]
@agrosner perfect i didn't see anyware. i suggest to add in documentation
