### ISSUE TITLE
How to declare additional columns on the ManyToMany auto-generated connection table

### ISSUE THREAD

**Issue by liorzam** [Raizlabs/DBFlow#1061]
DBFlow Version: Question

Description: 
Take the example of the User_Follower which describe in the [Relationship explanation].(https://github.com/Raizlabs/DBFlow/blob/master/usage2/Relationships.md) 

how do you can add a column that specify when the user become a follower to the related user.

**Comment by liorzam** [comment]
i thought for solution : create table with 2 ForeignKey and additional column.

**Comment by agrosner** [comment]
yes you would need to create the table manually.
