### ISSUE TITLE
[Feature] Replace BaseModel methods with _Table methods

### ISSUE THREAD

**Issue by xanscale** [Raizlabs/DBFlow#1063]
extends BaseModel is usefull but sometimes has problem with integration (like Gson).

`class AAA extends BaseModel { save(); }`

cuold be moved inside _Table generated class like

`AAA_Table.save(AAA aaa)`

the usage is simple as actual, and seams has no negative points

**Comment by agrosner** [comment]
You dont have to extend `BaseModel`. Also always prefer non-static as to better support testing.

**Comment by agrosner** [comment]
just call:
```
ModelAdapter<AAA> adapter = FlowManager.getModelAdapter(AAA.class);
adapter.save(model);
```

**Comment by xanscale** [comment]
hi @agrosner, i want to explain my suggestion:

extends BaseModel is usefull but in sometimes have some problem (like Gson)

we can use annotationProcessor to generate same methods in _Table class.

this will give us the simplicity of basemodel without contraindications
