### ISSUE TITLE
Refresh FlowQueryList using a joined QueryModel

### ISSUE THREAD

**Issue by RigoRos** [Raizlabs/DBFlow#1064]
DBFlow Version: 4.0.0-beta1
Issue Kind: Question

Description: 
Do a join and use a QueryModel like here #864 for a FlowQueryList.
Now refresh this list. 
The result will be a NullPointerException because of missing the QueriableModel.

Is there any solution to fix this now? Or is it a bug?

**Comment by agrosner** [comment]
can you provide a stacktrace please, more info you give the easier it's to figure out what's wrong.

**Comment by agrosner** [comment]
sounds like a bug, ill look into it.

**Comment by agrosner** [comment]
as per #864 , if you specify a `Cursor` you cannot `refresh()` the list manually. It's a one-time use dataset. You will have to recreate and swap with new instance instead.

**Comment by agrosner** [comment]
throws `IllegalStateException` now, in `develop`.
