### ISSUE TITLE
Table classes generated with "package package" on first line - jack/java8/gradle2.2

### ISSUE THREAD

**Issue by richardleggett** [Raizlabs/DBFlow#1065]
**DBFlow Version:** 4.0.0-beta1
**Issue Kind (Bug, Question, Feature):** Bug

**Description:** 

Generated table code seems to be including the word package twice e.g.

`package package com.project.model;`

Forgive me if this is just a configuration error, but I wondered if it's something to do with the setup which is:

- gradle:2.2.2
- jack compiler enabled for Java 8 support

My build file looks like this:

```android {
    compileSdkVersion 25
    buildToolsVersion "24.0.2"
    defaultConfig {
        applicationId "com.project"
        minSdkVersion 19
        targetSdkVersion 24
        versionCode 1
        versionName "0.1"
        jackOptions {
            enabled true
        }
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

   ... 

  dependencies {
    ...
    annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:4.0.0-beta1"
    compile "com.github.Raizlabs.DBFlow:dbflow-core:4.0.0-beta1"
    compile "com.github.Raizlabs.DBFlow:dbflow:4.0.0-beta1"
  }
```

I'm also using Lombok. I've tried cleaning etc, but it always seems to include the word "package" twice.

**Comment by jilulu** [comment]
Having the same issue. Also on 4.0.0-beta1. 

> Screenshot: 
> <img width="437" alt="screen shot 2016-11-12 at 4 02 25 pm" src="https://cloud.githubusercontent.com/assets/8308217/20236485/8d50e1ae-a8f1-11e6-95c5-ee053168d3cf.png">

**Comment by agrosner** [comment]
Jack compiler is not tested/supported yet. I am going to look into it to see what the issue is. Most likely a JavaPoet issue.

**Comment by Glurt** [comment]
Do you have an update on this? I'm starting a new project and would like to use Jack + DBFlow.

**Comment by trevjonez** [comment]
@Glurt I would recommend you use the normal tool chain with retrolambda over jack. Still a good deal of unknowns not to mention it being a decent bit slower than the normal tool chain.

**Comment by crdornelles** [comment]
Guys, about this issue, we have news?

**Comment by agrosner** [comment]
fixed. in `develop` now.

**Comment by agrosner** [comment]
it was the difference of `manager.elements.getPackageOf(element)?.qualifiedName?.toString()?: ""` and `manager.elements.getPackageOf(element).toString()`. The second one prepended a "package" to the class file for some odd reason in Jack, while normal APT doesn't do that.
