### ISSUE TITLE
ForeignKeyAction.CASCADE does't work

### ISSUE THREAD

**Issue by sebastianmaz** [Raizlabs/DBFlow#1067]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Bug
Description: 

I have 2 tables: Installation and Device. Installation has field 'device' of type Device. 'device' is a foreign key with onDelete = ForeignKeyAction.CASCADE but when I delete Installation Device is still there:

`public class Installation extends BaseModel {
    @SerializedName("id")
    @Expose
    @PrimaryKey
    private long id;
    
    @SerializedName("device")
    @Expose
    @ForeignKey(onDelete = ForeignKeyAction.CASCADE, onUpdate = ForeignKeyAction.CASCADE, saveForeignKeyModel = true)
    private Device device;
}`

`public class Device extends BaseModel {
    @SerializedName("id") 
    @Expose
    @PrimaryKey
    private long id;
    @SerializedName("number")
    @Expose
    @Column
    private String number;
}`

**Comment by agrosner** [comment]
Did you enable `foreignKeyConstraintsEnforced()` in `@Database` (4.0.0-beta1, was `foreignKeysSupported()` ? Also when deleting the containing table, make sure to release reference to the `device`, otherwise it will still exist and might get resaved.

in 4.0.0-beta1 we have the option of `deleteForeignKeyModel()` which will call delete and remove its reference in the `Model` before the child referencing it is deleted. This is to prevent an issue like this from occurring potentially.

**Comment by sebastianmaz** [comment]
Hi, sorry for long time to reply.

Yes I enabled foreignKeysSupported. It is enabled from beginning. I am not sure what You mean by "when deleting the containing table, make sure to release reference to the device". Can You explain ?

**Comment by sebastianmaz** [comment]
I've checked it twice. I do Delete.table(Installation.class); then SQLite.select().from(Device.class).queryList(); and still have entries in Device table. 
I wonder if this is a bug or maybe I did something wrong

**Comment by sebastianmaz** [comment]
I switched to 4.0.0-beta1 and set foreignKeyConstraintsEnforced to true and used deleteForeignKeyModel on every ForeignKey but nothing changed. When I delete Installation table all entries in Device are still there. I am out of ideas.

**Comment by liorzam** [comment]
@sebastianmaz  , this feature works fine,
i think you just forgot add references column 

```
@ForeignKey(....
references = @ForeignKeyReference(columnName= ,
                    columnType = ,
                    foreignKeyColumnName = )
            ))
```

**Comment by tux-world** [comment]
@sebastianmaz Hi man could you help me for this topic on StackOverFlow? http://stackoverflow.com/q/41027698/6596724  Thanks

**Comment by sebastianmaz** [comment]
@liorzam thanks for answer but "references" is marked as no needed because it is done automatically, so I don't think that it will solve the problem, but I tried and it still doesn't work

**Comment by agrosner** [comment]
> Yes I enabled foreignKeysSupported. It is enabled from beginning. I am not sure what You mean by "when deleting the containing table, make sure to release reference to the device". Can You explain ?

set `installation.device = null` so you dont resave it or try to again later on.
