### ISSUE TITLE
Error ,automatic index on xxx for leftOuterJoin()

### ISSUE THREAD

**Issue by jeesezh** [Raizlabs/DBFlow#1069]
DBFlow Version:
Issue Kind (Bug, Question, Feature):question
Description: 
these my table:
![image](https://cloud.githubusercontent.com/assets/19542480/20297685/aeafaabc-ab4c-11e6-8523-66075646a295.png)
![image](https://cloud.githubusercontent.com/assets/19542480/20297601/458ef72c-ab4c-11e6-9f3c-d48ca43e16b5.png)
this is my query:
SQLite.select(Attends_Table.names).from(Attends.class).leftOuterJoin(CollectChild.class)
                .on(Attends_Table.barcodes.withTable().eq(CollectChild_Table.barcodes.withTable()))
                .where(CollectChild_Table.eventId.is(eventId))
                .and(CollectChild_Table.collectionId.is(54)).queryList();

**Comment by agrosner** [comment]
what is the question here? its not very clear what you're asking.
