### ISSUE TITLE
 java.lang.VerifyError: com/raizlabs/android/dbflow/config/FlowManager

### ISSUE THREAD

**Issue by avinashs95** [Raizlabs/DBFlow#1070]
DBFlow Version: 4.0.0-beta1
Issue Kind : Bug

Description: 
I installed my app on my Samsung GT-N8000 Tablet. The app could not start. It stopped with the following exception: 

> java.lang.VerifyError: com/raizlabs/android/dbflow/config/FlowManager
>                                                                         at com.kidobotikz.app.KDBApplication.onCreate(KDBApplication.java:41)
>                                                                         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
>                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
>                                                                         at android.app.ActivityThread.access$1600(ActivityThread.java:175)
>                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
>                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                         at android.os.Looper.loop(Looper.java:146)
>                                                                         at android.app.ActivityThread.main(ActivityThread.java:5603)
>                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
>                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
>                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
>                                                                         at dalvik.system.NativeStart.main(Native Method)

**Comment by michaellct** [comment]
do you solve the problem?  i also meet this issue.
