### ISSUE TITLE
Why StringQuery does not allow to provide selectionArgs?

### ISSUE THREAD

**Issue by maohieng** [Raizlabs/DBFlow#1073]
DBFlow Version: 4.0.0-beta2
Issue Kind (Bug, Question, Feature): Question and Feature

Description: 
`StringQuery` is nice for developer providing their custom (or complex) `sql` query. But turn out it does not provide the ability for developer to provide a `selectionArgs` for their `sql` query which is a natural providing by `android.database.sqlite.SQLiteDatabase#rawQuery(String, String[])` or DBFlow's `com.raizlabs.android.dbflow.structure.database.DatabaseWrapper#rawQuery(query, selectionArgs)`. Why `StringQuery` does not provide for selectionArgs?

Yeah, sometime in my case, I have a complex `sql` query with a placeholder (?) for flexible (like given `id`). To be useful, I have to duplicate this class and do my own :).  

Sorry for my English, and thanks for your awesome library.

**Comment by trevjonez** [comment]
What query are you doing that requires a string query? We recently migrated a large app to dbflow  and were able to not use it a single time.

Even for cursor loaders you can start with `ConditionGroup.clause(...)` use the normal query dsl then produce a string for the loader with `ConditionGroup.getQuery()`

**Comment by maohieng** [comment]
Here's an example of my custom query. I query to get Key Person Commune (KPC) list which are in a block area (given by `district IN (?)`) with the KPC's reports (sale activities, number of orders, commission...).

    -- {START totalCommission}
    SELECT * FROM (
        --{START totalKpv}
        SELECT *, COUNT(KPV.parent_id) AS totalKpv FROM (
            -- {START totalOrder}
            SELECT *, COUNT(Orders.user_id) AS totalOrder FROM (
                -- {START totalActivity}
                SELECT *, COUNT(Activity.user_id) AS totalActivity FROM (
                    SELECT * FROM users WHERE user_type='KPC' AND district IN (?)
                ) [KPC]
                LEFT OUTER JOIN (
                    SELECT user_id, held_on FROM activities WHERE date(held_on)>=date('now', 'start of month','localtime') and date(held_on)<=date('now','start of month','+1 month','-1 day','localtime')
                ) [Activity]
                ON KPC.id=Activity.user_id
                GROUP BY KPC.id
                -- {END totalActivity}
            ) [KPC_Activity]
            LEFT OUTER JOIN (
                SELECT user_id, status FROM orders WHERE status=0 OR status=1
            ) [Orders]
            ON KPC_Activity.id=Orders.user_id
            GROUP BY KPC_Activity.id
            --{END totalOrder}
        ) [KPC_A_O]
        LEFT OUTER JOIN (
            SELECT user_type, parent_id FROM users WHERE user_type='KPV'
        ) [KPV]
        ON KPC_A_O.id=KPV.parent_id
        GROUP BY KPC_A_O.id
        -- {END totalKpv}
    ) [KPC_A_O_V]
    LEFT OUTER JOIN (
        SELECT Orders.user_id AS user_id, Orders.sp_id AS sp_id
              , SUM( CASE WHEN Orders.commission_type=1 THEN Authorizes.commission_full ELSE Authorizes.commission_mfi END) AS totalCommission
         FROM (
              SELECT user_id, sp_id, commission_type FROM (
                   SELECT * FROM orders WHERE sp_id!=22222222222222 AND status=3 AND paid_status=0
              )
         ) [Orders]
         LEFT OUTER JOIN (
              SELECT * FROM authorizes
         ) [Authorizes]
         ON Orders.user_id=Authorizes.user_id AND Orders.sp_id=Authorizes.sp_id
         GROUP BY Orders.user_id
    ) [Commission]
    ON KPC_A_O_V.id=Commission.user_id
    GROUP BY KPC_A_O_V.id
    -- {END totalCommission}

With this case, I have this custom sql query followed by a `selectionArgs=[district1, district2]` or sometime `selectionArgs=[district3, district4, district5]`... etc. Should this case apply for `StringQuery`? Or do you have any recommend for this?

Thanks,

**Comment by trevjonez** [comment]
Yea out of scope of the built in DSL for sure. Looking at the string query class it would be very simple to add a few methods to pass in the arg array. You should open a PR.

**Comment by agrosner** [comment]
in `develop`.
