### ISSUE TITLE
FlowContentObserver.OnModelStateChangedListener doesn't receive changes done via SQLite wrapper

### ISSUE THREAD

**Issue by hindupuravinash** [Raizlabs/DBFlow#1074]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Question

Description: 
`FlowContentObserver.OnModelStateChangedListener` doesn't receive changes done to multiple models via SQLite Wrapper Language. For example:
```
SQLite.update(TableA.class) .set(TableA$Table.lastName.eq("Bar")
                            .where(TableA$Table.firstName.is("Foo"))
                            .async()
                            .execute();
```

But it receives changes done via Model Actions like `.save()` or `.update()`

Is there any way to listen to these changes?

**Comment by agrosner** [comment]
good question. Not currently.
