### ISSUE TITLE
Unable to do a query in ManyToMany relationship

### ISSUE THREAD

**Issue by mayuroks** [Raizlabs/DBFlow#1078]
DBFlow Version: 4.0.0-beta2
Issue Kind :Question :question:

Description: I have a many to many relationship in my app. But I am struggling to query it.
Here are my models

**Food.java**
```
@Table(database = DietTrackDB.class)
@ManyToMany(referencedTable = Meal.class)
public class Food extends BaseModel {

    @PrimaryKey(autoincrement = true)
    int id;
}
```

**Meal.java**
```
@Table(database = DietTrackDB.class)
public class Meal extends BaseModel {
    @Column
    @PrimaryKey(autoincrement = true)
    int id;
}
```

The @ManyToMany annotation created Food_Meal_Table. But while creating inner join I am having issue with this example

```
List<Food_Meal_Table> foods = new Select()   
  .from(Food.class).as("F")   
  .join(Meal.class, JoinType.INNER).as("M")    
  .on(Food_Table.id
      .withTable(NameAlias.builder("F").build())
    .eq(Meal_Table.id.withTable("R"))          <======= This withTable method
    .queryCustomList(Food_Meal_Table.class);
```

The issue is withTable highlighted above doesn't accept String param. It needs NameAlias.
So when I change withTable("R") to withTable(NameAlias.builder("R").build()), I get another error which says `Cannot resolve queryCustomList method`

**In my case I just want to find out which foods belong to a meal. How do I do that ?**

**Comment by mayuroks** [comment]
Is there any other place like gitter or stackoverflow where I can get some response ?

**Comment by trevjonez** [comment]
```java
List<Food_Meal_Table> foods = new Select()   
  .from(Food.class).as("F")   
  .join(Meal.class, JoinType.INNER).as("M")    
  .on(Food_Table.id.withTable(NameAlias.builder("F").build()).eq(Meal_Table.id.withTable(NameAlias.builder("R").build()))
  .where() <== try adding this?
  .queryCustomList(Food_Meal_Table.class);
```

**Comment by trevjonez** [comment]
and you can do `.innerJoin(Meal.class)` bit shorter.
