### ISSUE TITLE
Kotlin data classes and boolean getter/setter

### ISSUE THREAD

**Issue by Try4W** [Raizlabs/DBFlow#1080]
DBFlow Version:
Issue Kind (Bug, Question, Feature):
DBflow looking for `is*property_name*()` method but Kotlin generate something else.

It can be fixed with `@JvmName` annotations:
```
data class Product(
        ...
        @get:JvmName("isUseForCalculation") @set:JvmName("setUseForCalculation") @Column(name = "use_for_calculation") var useForCalculation: Boolean? = null
) : Model { ... }
```

But I think DBFlow can support such `getters/setters` generated by Kotlin.

**Comment by agrosner** [comment]
in `@Table`:
```
 /**
     * @return If true, all private boolean fields will use "is" instead of "get" for its getter and
     * "set" without the "is" if it starts with "is"
     */
    boolean useBooleanGetterSetters() default true;
```
If you wish not to use this, then set `@Table(useBooleanGetterSetters() = false)`

**Comment by peterchaula** [comment]
@agrosner, I would like to add that to the docs for the `useBooleanGetterSetters = false` parameter. Should this go under Kotlin support or Models?
