### ISSUE TITLE
Copy prepackaged database on App update

### ISSUE THREAD

**Issue by theaircrasher** [Raizlabs/DBFlow#1083]
DBFlow Version: 3.1.1
Issue Kind: Question

Description: 
My app comes with a prepackaged database. The data inside the DB changes frequently (not necessarily the DB Tables). My problem is that the DB only gets copied from the assets folder on initial creation. However i need to copy it on app update. I don't need to preserve any information of the previous DB.
Is there a way to exchange the DB on Db version change?

Thanks,
Chris

**Comment by trevjonez** [comment]
I would recommend persisting your app version each time your application launches (in shared preferences for example). Then for each time after check if the current version > persisted version. If it is you can assume that the app was just upgraded and proceed to delete the existing database file. This can be done by calling `getDatabasePath("yourdatabase.db")` which returns a `File` and you can call `.delete()`. If you do this before initializing dbflow it should trigger it to run whatever version 0, or pre-packaged file transfer logic.

**Comment by theaircrasher** [comment]
Thank you. I solved it using an BroadcastReceiver on MY_PACKAGE_REPLACED. However., after deleting the old DB I manually copied the new database. I will try if deleting only is also working.

**Comment by TWiStErRob** [comment]
@trevjonez Don't just delete the file, use `android.database.sqlite.SQLiteDatabase.deleteDatabase` to fully clean up the database.
