### ISSUE TITLE
Is DBFlow compatible with Lombok?

### ISSUE THREAD

**Issue by iroyo** [Raizlabs/DBFlow#1084]
I was wondering if it's possible to use Lombok alongside DBFlow. I have my private fields and use `@Getter` and `@Setter` annotations but then I get a bunch of errors. This is the Model I have:

```
@Getter @Setter
@Table(database = AppDatabase.class, allFields = true)
public class Doctor extends BaseModel {
    
   @PrimaryKey
    private int id;

    private int gender;
    private String name;

    @ForeignKey
    private Department department;

}
```

**Sorry it's not the right place to ask this**

**Comment by trevjonez** [comment]
without more specific information on the failure we can only guess. Would it be possible for you to setup a simple repo that is all setup so I can get in and play with it? there are many things we can try to do to make it work.

I would also ask if you have considered using kotlin over using lombok? If you were to use it for just your database models you can get a similar effect without much mental load and without including the kotlin std lib if you are tight on the method count limit.

**Comment by iroyo** [comment]
OK I've just created a very basic repo where you can reproduce the errors (when building project): [https://github.com/iroyo/dbflow-and-lombok](url)

On the other hand, if you could elaborate on how would it be possible to use Kotlin for models without the std lib... Thank for everything

**Comment by agrosner** [comment]
There def was a bug in 3.1.1 that didnt show the actual error message. Switching to 4.0.0-beta2 produced this error:
```
Error:*==========*class com.raizlabs.android.dbflow.processor.ColumnValidator (Kotlin reflection is not available) :Could not find getter for private element: "name" from table class: Person. Consider adding a getter with name getName or making it more accessible.*==========*
```

**Comment by agrosner** [comment]
I dont think its compatible with Lombok b/c Lombok is another annotation processor, so theres no guarantee when either one will run. Lombok modifies class files and changes them so it of course would work during compilation phase, since annotation processing happens prior to compilation.

**Comment by agrosner** [comment]
My suggestion which @trevjonez alluded to is to use Kotlin if you can, if not, you'll have to expose getters and setters.

**Comment by agrosner** [comment]
np. I recommend 4.0.0-beta2 because it is relatively stable and usable. For lower risk I'd go with 3.1.1, and since the upgrade path between these two versions on the surface are not super significant, it might be safer to stick with 3.1.1 until 4.0.0 stable.

**Comment by trevjonez** [comment]
You might try doing package scope fields so that the dbflow code doesn't depend on lombok code.

If you go with kotlin just don't add the compile dependency to avoid importing the std lib.

**Comment by IonutNegru87** [comment]
Is there a way to use lombok with DBFlow without relying on Kotlin?
