### ISSUE TITLE
executeUpdateDelete() causes InvalidDBConfiguration exception 

### ISSUE THREAD

**Issue by xinghui322** [Raizlabs/DBFlow#1087]
DBFlow Version:4.0.0-beta2
Issue Kind (Bug):

Description: 

Stacktrace :
```
com.raizlabs.android.dbflow.structure.InvalidDBConfiguration: Database: 
com.xxx.mobile.android.db.model.SysConfig is not a registered Database. Did you forget the @Database annotation?
	at com.raizlabs.android.dbflow.config.FlowManager.getDatabase(FlowManager.java:116)
	at com.raizlabs.android.dbflow.config.FlowManager.getWritableDatabase(FlowManager.java:146)
	at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.executeUpdateDelete(BaseModelQueriable.java:94)
```
I delete row as follow:
`SQLite.delete(SysConfig.class).where(SysConfig_Table.ConfigID.eq(1))
               .executeUpdateDelete()`
And I think should call statement.close() on executeUpdateDelete()

**Comment by agrosner** [comment]
```
com.xxx.mobile.android.db.model.SysConfig is not a registered Database. Did you forget the @Database annotation?

```
is the answer. Is the corresponding `DatabaseDefinition` for the database generated?

**Comment by xinghui322** [comment]
I saw the source code of `com.raizlabs.android.dbflow.sql.language.BaseModelQueriable#executeUpdateDelete()`, 
``` java
   @Override
    public long executeUpdateDelete() {
        return executeUpdateDelete(FlowManager.getWritableDatabase(getTable()));
    }
```
`FlowManager.getWritableDatabase(getTable())` needs a database class,but give it a table class?

**Comment by agrosner** [comment]
great catch!!

**Comment by agrosner** [comment]
in `develop`
