### ISSUE TITLE
FastStoreModelTransaction cannot save Relationships?

### ISSUE THREAD

**Issue by xxxifan** [Raizlabs/DBFlow#1088]
DBFlow Version: 3.1.1  
Issue Kind (Bug, Question, Feature): Bug  
Description:   
I need to save a set of data so I chose to use FastStoreModelTransaction to keep it safe and fast. But I found that all the relations cannot be saved so I got empty field when I query it. And when I changed the way to loop the list and save those model one by one then it' OK. Here's my code: 

          if (syncResult.orderInfo != null && syncResult.orderInfo.size() > 0) {
                for (int i = 0, s = syncResult.orderInfo.size(); i < s; i++) {
                    syncResult.orderInfo.get(i).associateForeignKeys();
                    // syncResult.orderInfo.get(i).save();
                }
                FastStoreModelTransaction transaction = FastStoreModelTransaction
                        .saveBuilder(FlowManager.getModelAdapter(OrderInfoTable.class))
                        .addAll(syncResult.orderInfo)
                        .build();
                database.executeTransaction(transaction); // relations broken
            }
  
and here's my model: [OrderInfo](https://gist.github.com/xxxifan/9c526578e6f7908a8f5c730a4e0b2529), [FormItemTable](https://gist.github.com/xxxifan/a532d84df9929be1be597292d6b28b63) (one of the sub-model, which is almost same with other models)  

Is this a bug or FastStoreModelTransaction designed for? Use the basic transaction is ok.  
  
Cheers

**Comment by agrosner** [comment]
upgrading to 4.0.0-beta2 has support for this already.

**Comment by agrosner** [comment]
let me know if that fixes your issue. upgrading shouldnt be any serious major breaking changes. Most of them are under the hood.

**Comment by xxxifan** [comment]
is 4.0 beta stable enough for production? I didn't upgrade for that reason.

**Comment by agrosner** [comment]
yeah it is, just in beta since I want to ensure theres no critical issues found before releasing as a full release. It seems like it is. Plus the migration (depending on how you implemented it) really should be seamless with very little changes so if something comes up you dont like, you can rollback and report it.

**Comment by xxxifan** [comment]
One thing confuse me on 4.0, how could I create one to many relation correctly? Since ModelContainer and ForeignkeyContainer is deprecated from 4.0, and doc is still telling me use @ModelContainer and the method annotated with @OneToMany select with condition ```.where(Ant_Table.queenForeignKeyContainer_id.eq(id))``` which looks like generated by ForeignKeyContainer

**Comment by agrosner** [comment]
check docs now. read on [stubbed relationships](https://github.com/Raizlabs/DBFlow/blob/master/usage2/Relationships.md#stubbed-relationships)

**Comment by akmad** [comment]
I think that I am still running into this issue with version 4.1.1. I've got some tests which show that when saving a model via `ModelAdapter<T>.save` the related models (`@OneToMany`) are properly saved to the db but they are **not** when using using `FastStoreModelTransaction.saveBuilder(table).addAll(models).build()`. Oddly, models related via`@ForeignKey` **are** saved properly and so are that related model's `@OneToMany` relations but if that same related model is attempted to be saved directly (via `FastStoreModelTransaction`) then the `@OneToMany` relations do not get saved.

Given that this was fixed I am wondering if I am just setting things up wrong or if there is actually a bug here. My tests are [here](https://github.com/akmad/openmrs-contrib-android-client/blob/feature/andr-241/openmrs-client/src/test/java/org/openmrs/mobile/data/db/RepositoryTest.java#L239) and some of the models in question are [Patient](https://github.com/akmad/openmrs-contrib-android-client/blob/feature/andr-241/openmrs-client/src/main/java/org/openmrs/mobile/models/Patient.java), [PatientIdentifier](https://github.com/akmad/openmrs-contrib-android-client/blob/feature/andr-241/openmrs-client/src/main/java/org/openmrs/mobile/models/PatientIdentifier.java), [Person](https://github.com/akmad/openmrs-contrib-android-client/blob/feature/andr-241/openmrs-client/src/main/java/org/openmrs/mobile/models/Person.java), and [PersonName](https://github.com/akmad/openmrs-contrib-android-client/blob/feature/andr-241/openmrs-client/src/main/java/org/openmrs/mobile/models/PersonName.java).

**Comment by elalfner** [comment]
Same issue as @Oknesif and @akmad on version 4.2.4
