### ISSUE TITLE
ModelContainer in 4.0.0-beta2

### ISSUE THREAD

**Issue by PingForward** [Raizlabs/DBFlow#1090]
What to use instead of ModelContainer in 4.0.0-beta2??

**Comment by trevjonez** [comment]
the use of `@ModelContainer` is no longer necessary.

See https://github.com/Raizlabs/DBFlow/blob/master/usage2/Relationships.md for information about how to do stubbed relationships if that is what is needed.

**Comment by PingForward** [comment]
Yep, it seems working now. Thanks
