### ISSUE TITLE
Execute strftime queries.

### ISSUE THREAD

**Issue by varundroid** [Raizlabs/DBFlow#1094]
DBFlow Version:3.1.1
Issue Kind (Bug, Question, Feature): Question

Description: 
How to execute the following raw query - SELECT strftime('%w', 'now')?
I need to use it in my conditional clause to fetch the data based on week day.

**Comment by agrosner** [comment]
in 4.0.0-beta4, it will be there. simply just:
```java

select(Method.strftime("%w", "now"))

```

As a workaround, you can copy paste the method (until the update):
```java
 /**
     * SQLite standard "strftime()" method. See SQLite documentation on this method.
     */
    public static Method strftime(String formatString, String timeString, String... modifiers) {
        List<IProperty> propertyList = new ArrayList<>();
        propertyList.add(PropertyFactory.from(formatString));
        propertyList.add(PropertyFactory.from(timeString));
        for (String modifier : modifiers) {
            propertyList.add(PropertyFactory.from(modifier));
        }
        return new Method("strftime", propertyList.toArray(new IProperty[propertyList.size()]));
    }
```

**Comment by colza** [comment]
Or you can use this method if you're directly using property as the time parameter. Friendly remind, don't use toString() to convert the property.

`    
public static Method strftime(String formatString, IProperty time, String... modifiers) {
        List<IProperty> propertyList = new ArrayList<>();
        propertyList.add(PropertyFactory.from(formatString));
        propertyList.add(time);
        for (String modifier : modifiers) {
            propertyList.add(PropertyFactory.from(modifier));
        }
        return new Method("strftime", propertyList.toArray(new IProperty[propertyList.size()]));
    }
`

**Comment by varundroid** [comment]
Hi, thanks for your replies.

I used the following and it worked like a charm -

Property STRFTIME_DAY_OF_WEEK = new Property(null, NameAlias.rawBuilder("strftime("%w", "now")").build()).as("today");
LongProperty TODAY_FIELD = new LongProperty(null, "today");

**Comment by luckerbai** [comment]
Why not add this method in DBFlow? Feel puzzled...
public static Method strftime(String formatString, IProperty time, String... modifiers) {
        List<IProperty> propertyList = new ArrayList<>();
        propertyList.add(PropertyFactory.from(formatString));
        propertyList.add(time);
        for (String modifier : modifiers) {
            propertyList.add(PropertyFactory.from(modifier));
        }
        return new Method("strftime", propertyList.toArray(new IProperty[propertyList.size()]));
    }
