### ISSUE TITLE
save jsonArray on database instead of loop cluase

### ISSUE THREAD

**Issue by tux-world** [Raizlabs/DBFlow#1096]
is any simple way to save json array to model instead of using ```loop``` cluase? for example this sample code is used with ```realm``` database solution:

`realm.createAllFromJson(Categories.class, result);`

My code:

```
@Table(database = AppDatabase.class)
public class Categories {
    @PrimaryKey
    private String categoryId;

    @Column
    private String categoryName;

    @Column
    private String categoryDescription;

    @Column
    private String categoryImageFileName;

    @Column
    private String fileServerUrl;

    @Column
    private String categoryCount;

    public Categories() {
    }


    public String getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getCategoryDescription() {
        return categoryDescription;
    }

    public void setCategoryDescription(String categoryDescription) {
        this.categoryDescription = categoryDescription;
    }

    public String getCategoryImageFileName() {
        return categoryImageFileName;
    }

    public void setCategoryImageFileName(String categoryImageFileName) {
        this.categoryImageFileName = categoryImageFileName;
    }

    public String getFileServerUrl() {
        return fileServerUrl;
    }

    public void setFileServerUrl(String fileServerUrl) {
        this.fileServerUrl = fileServerUrl;
    }

    public String getCategoryCount() {
        return categoryCount;
    }

    public void setCategoryCount(String categoryCount) {
        this.categoryCount = categoryCount;
    }
}

}
```

and this is save into database:

`
    final JSONArray result = data.getJSONArray("channelsCategories");
    JSONArrayModel<Categories> listArea = new JSONArrayModel<>(result, Categories.class); 
`

I get this error:

`Error:*==========*class com.raizlabs.android.dbflow.processor.ColumnValidator (Kotlin reflection is not available) :Could not find setter for private element: "channelStateId" from table class: Channels. Consider adding a setter with name setChannelStateId or making it more accessible.*==========*`

I dont use ```Kotlin``` on android

**Comment by agrosner** [comment]
Kotlin is used in the annotation processor. 
Looks like your missing:
```
Could not find setter for private element: "channelStateId" from table class: Channels.
```

And in 4.0.0+ there is no longer json parsing support so I would recommend using [LoganSquare](https://github.com/bluelinelabs/LoganSquare) or GSON for parsing.
