### ISSUE TITLE
Create simple oneToMany and i get an error

### ISSUE THREAD

**Issue by tux-world** [Raizlabs/DBFlow#1097]
i have simple two models and i'm trying to create simple OneToMany between them, as far as i'm newbie to use this library i can't use library documentation, my main model is:

Result with json format:

```
[
    {
        "id": 5,
        "channelId": 1,
        "createdAt": "2016-12-06T04:57:06.000Z",
        "updatedAt": "0000-00-00 00:00:00",
        "channel_video_containers": [
            {
                "id": 2,
                "videoName": "node js tutorial",
                "videoDescription": "node js video tutorial",
                "channelId": 1,
                "videoSize": "3123213",
                "videoFormat": "mp4",
                "videoLength": "13",
                "videoThumbnailImage": "nodejs_tutorial.png",
                "fileName": "nodejs.mp4",
                "postId": 5,
                "fileServerUrlId": 1,
                "createdAt": "2016-12-04T00:00:00.000Z",
                "updatedAt": "2016-12-04T00:00:00.000Z",
                "post_id": 5,
                "file_server_url_id": 1,
                "file_server_setting": {
                    "id": 1,
                    "fileServerUrl": "https://www.google.com/images/branding/googlelogo/1x/"
                }
            }
        ]
    }
]

```
    @Table(database = AppDatabase.class)
    public class ModelChannelPosts extends BaseModel {
        @PrimaryKey
        private int id;
    
        @Column
        private String channelId;
    
        @Column
        private List<ModelVideos> channel_video_containers;
    
        @Column
        private String createdAt;
    
        @Column
        private String updatedAt;
    
        ...

        public ModelChannelPosts() {
        }
    
        @OneToMany(methods = {OneToMany.Method.ALL}, variableName = "channel_video_containers")
        public List<ModelVideos> getVideos() {
            if (channel_video_containers == null || channel_video_containers.isEmpty()) {
                channel_video_containers = new Select()
                        .from(ModelVideos.class)
                        .where(ModelVideos_Table.channelId.eq(id))
                        .queryList();
            }
            return channel_video_containers;
        }
    
        ...
    }

and that has many `ModelVideos`, then `ModelVideos` belongs to `ModelChannelPosts`:

    @Table(database = AppDatabase.class)
    public class ModelVideos extends BaseModel {
        
        @PrimaryKey
        private int                    id;
    
        @Column
        private String                 fileName;
        
        @Column
        private String                 videoLength;

        @Column
        private int                    channelId;

        ...

        public ModelVideos() {
        }
    
        ...

    }

in `ModelChannelPosts_Table` file `model.channel_video_containers` is unknown and i get this error:

    Error:(168, 48) error: <identifier> expected

how can i implementing `OneToMany` for them?( make relation ship between `channel_video_containers` on `ModelChannelPosts` and `channelId` on `ModelVideos` ?

**Comment by DreierF** [comment]
As far as I know `channel_video_containers` should not be annotated with `@Column`.
Furthermore you have to add a reference to the parent `ModelChannelPosts` in `ModelVideos` like so:
```
@ForeignKey(stubbedRelationship = true)
ModelChannelPosts owner;
```

**Comment by agrosner** [comment]
@tux-world you muse specify in your `@OneToMany(isVariablePrivate = true)` and provide a setter for the field thats visible so that the processor can set values on it.

**Comment by tux-world** [comment]
@agrosner is this correct?

```
    @OneToMany(methods = {OneToMany.Method.ALL}, variableName = "channel_video_containers", isVariablePrivate = true)
```
