### ISSUE TITLE
Error when i try to use DBFlow, created in the last round will not be subject to annotation processing.

### ISSUE THREAD

**Issue by tux-world** [Raizlabs/DBFlow#1103]
define database:

```
@Database(name = AppDatabase.NAME, version = AppDatabase.VERSION)
public class AppDatabase {

    public static final String NAME = "Appdb";
    public static final int VERSION = 1;
}
```

My model:
```
@Table(database = AppDatabase.class)
public class UserInformation extends BaseModel {
    @PrimaryKey(autoincrement = true)
    private int id;

    @Column
    private String userId;

    @Column
    private int result;

    @Column
    private Info info;

    public UserInformation() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public int getResult() {
        return result;
    }

    public void setResult(int result) {
        this.result = result;
    }

    public Info getInfo() {
        return info;
    }

    public void setInfo(Info Info) {
        this.info = Info;
    }
}
```

Error:

> Warning:File for type 'com.raizlabs.android.dbflow.config.AppDatabaseAppdb_Database' created in the last round will not be subject to annotation processing.
> Warning:File for type 'com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder' created in the last round will not be subject to annotation processing.
> 

Application class:

`FlowManager.init(new FlowConfig.Builder(this).build());`

Manifest:

```
<application
        android:name=".myApp"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme">
```

Repositories:

```
def dbflow_version = "4.0.0-beta3"

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support:cardview-v7:+'
    compile 'com.jakewharton:butterknife:8.2.1'
    apt 'com.jakewharton:butterknife-compiler:8.2.1'
    compile 'com.google.code.gson:gson:2.6.2'

    ...

    apt "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
}
```

UserInformation_Table error:

```
if (index_info != -1 && !cursor.isNull(index_info)) {
      model.setInfo(cursor.????????????????????(index_info));
    } else {
      model.setInfo(null);
    }
```

**Comment by trevjonez** [comment]
These are just warning produced by the compiler. The code within `AppDatabaseAppdb` does not need to be processed by any other APT tools and **should be ignored.** 

A handful of classes generated by DBFlow are pushed to the last round of processing thus allowing other APT tools to generate dbflow table classes without being left out of the other config classes.

**Comment by agrosner** [comment]
this is a warning to be ignored. Its pushed off to last round of processing so we collect everything that gets generated.

**Comment by tux-world** [comment]
@trevjonez whats your meas about: does not need to be processed by any other APT tools. ? i dont have any other APT tools, 

@agrosner 
i'm using android studio and when i try to compile i get this error and it cause of broken compile process. how can i ignore that?

**Comment by tux-world** [comment]
@agrosner @trevjonez BTW did you try to read my full post??? my mean is my bottom of post


DBFlow create corrupted ```_Table```

UserInformation_Table error:

```
if (index_info != -1 && !cursor.isNull(index_info)) {
      model.setInfo(cursor.????????????????????(index_info));
    } else {
      model.setInfo(null);
    }
```

error is between ```cursor.``` and ```(index_info));```

**Comment by trevjonez** [comment]
@tux-world it would appear that you need to provide a type converter for the `Info` type. Can you provide the source for the info class?

**Comment by AyoPrez** [comment]
Could this warning cause problem with dagger2?

**Comment by trevjonez** [comment]
No. These classes do not have any annotations on them that requires dagger2
to process them.
