### ISSUE TITLE
Equivalent DROP TABLE

### ISSUE THREAD

**Issue by tux-world** [Raizlabs/DBFlow#1105]
in sql command we can use ```DROP TABLE IF EXISTS``` how can i use ```DBFlow``` to run this command without using ```StringQuery``` ?

**Comment by PingForward** [comment]
As I remember there is no such method just use simple code to drop it
```
 private void dropTables(DatabaseWrapper database, Class... models) {
            for (Class cl : models) {
                ModelAdapter myAdapter = FlowManager.getModelAdapter(cl);
                database.execSQL("DROP TABLE IF EXISTS " + myAdapter.getTableName());
                database.execSQL(myAdapter.getCreationQuery());
            }
        } 
```

**Comment by tux-world** [comment]
I found it, you can use ```Delete.table(s)```

**Comment by D330** [comment]
`Delete.table` clear all rows in the table but id ordering not reset.
