### ISSUE TITLE
Create some table with migration

### ISSUE THREAD

**Issue by tux-world** [Raizlabs/DBFlow#1107]
in my android application i would like to create some tables when i deploy current version of that, in documentation i cant find about any helper to handle this feature,

**Comment by xanscale** [comment]
if table does not exists will be created. manual migration need only for change table columns

**Comment by tux-world** [comment]
then this feature as create table has a bug. becauae dbflow dont create and
cause of crash my application with an error as

``` table does not exists ```

**Comment by tux-world** [comment]
then this feature as create table has a bug. because dbflow dont create and cause of crash my application with an error as 

```table does not exists```

**Comment by trevjonez** [comment]
Did you increment the DB version. A migration is required but it will be
done for you.

**Comment by tux-world** [comment]
incrementing version required for this feature?

**Comment by trevjonez** [comment]
`@Database(name = MyDB.NAME, version = 1)` -> `@Database(name = MyDB.NAME, version = 2)`

Just bumping the version of the database that contains the new table will trigger the creation.

You can look at the method `onUpgrade` in the `BaseDatabaseHelper` class to see the larger steps and how they work by diving in further.

Given that a bad database migration can absolutely destroy a release if done incorrectly I strongly urge anyone dealing with SQLite on android to fully understand their migration process and how it works at a fine grain level.
