### ISSUE TITLE
BUG _Table classes are not generated with 4.0.0-beta3 but works with 4.0.0-beta2

### ISSUE THREAD

**Issue by xanscale** [Raizlabs/DBFlow#1110]
WORKS:

```
dependencies {
	annotationProcessor 'com.github.Raizlabs.DBFlow:dbflow-processor:4.0.0-beta2'
	compile 'com.github.Raizlabs.DBFlow:dbflow:4.0.0-beta2'
}
```

ERROR:

```
dependencies {
	annotationProcessor 'com.github.Raizlabs.DBFlow:dbflow-processor:4.0.0-beta3'
	compile 'com.github.Raizlabs.DBFlow:dbflow:4.0.0-beta3'
}
```

i don't know how to see log of annotationProcessor

**Comment by xanscale** [comment]
anyone has this issue?

**Comment by agrosner** [comment]
do you have other annotation processor dependencies?

**Comment by xanscale** [comment]
no, this is the complete list:

```
dependencies {
	compile 'com.android.support:appcompat-v7:25.1.0'
	compile 'com.android.support:support-v13:25.1.0'
	compile 'com.android.support:cardview-v7:25.1.0'
	compile 'com.google.code.gson:gson:2.8.0'
	compile 'com.squareup.retrofit2:retrofit:2.1.0'
	compile 'com.squareup.retrofit2:converter-gson:2.1.0'
	compile 'com.github.xanscale:localhostToolkit:-SNAPSHOT'
	annotationProcessor 'com.github.Raizlabs.DBFlow:dbflow-processor:4.0.0-beta2'
	compile 'com.github.Raizlabs.DBFlow:dbflow:4.0.0-beta2'
}

```

**Comment by xanscale** [comment]
@agrosner this is the commit that breaks my build. i don't know why seams only test

https://github.com/Raizlabs/DBFlow/commit/d6381258908d36a1f00b3bc1ad3afe5b685b0879

**Comment by agrosner** [comment]
Maybe the 2.2.2 to 2.2.3 is the issue? 
Try adding this to your `build.gradle`:

```groovy
gradle.projectsEvaluated {
  tasks.withType(JavaCompile) {
    options.compilerArgs << "-Xmaxerrs" << "500" // or a larger number
  }
}
```

And see if more issues pop up that describe what happened.

**Comment by xanscale** [comment]
i found the problem but i don't know why.

Changing this line:
`public static Indicatore querySingle(@NotNull Long id) {.......}`
in this line
`public static Indicatore querySingle(Long id) {.......}`
works with both beta2 and beta3.

PS in my app i use
`classpath 'com.android.tools.build:gradle:2.2.3'`


why now i can't use NotNull Annotation in parameters?

**Comment by agrosner** [comment]
because the `NotNull` is either DBFlow not null and thats for fields only, or its the sun.istack.NotNull which doesnt actually exist in Android runtime...

**Comment by xanscale** [comment]
I Confused
`android.support.annotation.NonNull`
with
`com.raizlabs.android.dbflow.annotation.NotNull`

@agrosner why use own annotation for this?

**Comment by agrosner** [comment]
`@NotNull` is define a column via SQLite as not being null...

**Comment by xanscale** [comment]
@agrosner why not use "standard" annotation for that? now if i want to define column NOT null and relative variable i need to use 2 annotation.
