### ISSUE TITLE
remove single item as table row

### ISSUE THREAD

**Issue by tux-world** [Raizlabs/DBFlow#1113]
when i use this code:

```
DownloadProgressNotifier dlManager =
                        SQLite.select()
                                .from(DownloadProgressNotifier.class)
                                .where(DownloadProgressNotifier_Table.fileId.eq(channels.get(position).getId()))
                                .querySingle();
```
i want to remove that from database if its not NULL, how can i remove single row or mutiple rows from table?

**Comment by trevjonez** [comment]
the `BaseModel` class has a delete method on it so If you are extending it you can call do

```java
if (dlManager != null) {
    dlManager.delete();
}
```

Or if you didn't extend the `BaseModel` class you can use the adapter to perform the delete.

```java
if (dlManager != null) {
    FlowManager.getModelAdapter(DownloadProgressNotifier.class).delete(dlManager);
}
```

**Comment by danvwells** [comment]
you could also do this...

SQLite.delete()
              .from(DownloadProgressNotifier.class)
              .where(DownloadProgressNotifier_Table.fileId.eq(channels.get(position).getId()))

That way only one statement is used.

For multiple rows, you can do the same thing, just use different conditions in the where clause that matches multiple rows.

**Comment by tux-world** [comment]
@danvwells Thanks sir
