### ISSUE TITLE
Save list slowly 

### ISSUE THREAD

**Issue by Reginer** [Raizlabs/DBFlow#1114]
DBFlow Version:4.0.0-beta3
Issue Kind  Question 

I  use :
FlowManager.getDatabase(HideAppDB.class)
                .getTransactionManager()
                .getSaveQueue()
                .addAll2(mAppsList);

Why it takes a long time to see the results？Is there any way to do it right now？

**Comment by trevjonez** [comment]
There is a flush method you can call to trigger it.

**Comment by Reginer** [comment]
ok  ， thaks。
