### ISSUE TITLE
4.0.0-beta3 kotlin extensions on jitpack is a jar

### ISSUE THREAD

**Issue by kelsos** [Raizlabs/DBFlow#1117]
DBFlow Version: 4.0.0-beta3
Issue Kind (Bug, Question, Feature): Bug

Description: 
It seems that there is some issue with the kotlin-extensions artifact of 4.0.0-beta3 on jitpack.
This works fine with 4.0.0-beta2.

The error message when running gradle build is **Module 'com.github.Raizlabs.DBFlow:dbflow-kotlinextensions:4.0.0-beta3' depends on one or more Android Libraries but is a jar**

If I navigate to the gradle caches there is indeed a jar file in there and the pom file for kotlin extensions looks like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.github.Raizlabs.DBFlow</groupId>
  <artifactId>dbflow-kotlinextensions</artifactId>
  <version>4.0.0-beta3</version>
  <dependencies>
    <dependency>
      <groupId>com.github.Raizlabs.DBFlow.dbflow-kotlinextensions</groupId>
      <artifactId>dbflow</artifactId>
      <version>4.0.0-beta3</version>
      <type>aar</type>
    </dependency>
    <dependency>
      <groupId>com.github.Raizlabs.DBFlow.dbflow-kotlinextensions</groupId>
      <artifactId>dbflow-core</artifactId>
      <version>4.0.0-beta3</version>
    </dependency>
    <dependency>
      <groupId>com.github.Raizlabs.DBFlow.dbflow-kotlinextensions</groupId>
      <artifactId>dbflow-kotlinextensions</artifactId>
      <version>4.0.0-beta3</version>
      <type>aar</type>
    </dependency>
    <dependency>
      <groupId>com.github.Raizlabs.DBFlow.dbflow-kotlinextensions</groupId>
      <artifactId>dbflow-processor</artifactId>
      <version>4.0.0-beta3</version>
    </dependency>
    <dependency>
      <groupId>com.github.Raizlabs.DBFlow.dbflow-kotlinextensions</groupId>
      <artifactId>dbflow-sqlcipher</artifactId>
      <version>4.0.0-beta3</version>
      <type>aar</type>
    </dependency>
  </dependencies>
</project>
```

If I clear the gradle cache it will start downloading _com.github.Raizlabs.DBFlow.dbflow-kotlinextensions:dbflow-core_ , _com.github.Raizlabs.DBFlow.dbflow-kotlinextensions:dbflow-processor_ etc.

**Comment by agrosner** [comment]
hmmm looks like its an issue with either jitpack, the new kotlin version 1.0.5 I updated to, or something else. Have you tried this?
```
compile "com.github.Raizlabs.DBFlow:dbflow-kotlinextensions:${dbflow_version}@aar"
```

**Comment by kelsos** [comment]
To be honest I didn't think of trying it before, but I did now (since you mentioned it) and it seems to work properly. 

Thank you.

**Comment by agrosner** [comment]
cool. ill close it as the readme has been updated.
