### ISSUE TITLE
table() method in JSONModel still not reached. 

### ISSUE THREAD

**Issue by arturonaredo** [Raizlabs/DBFlow#112]
Sorry, I cannot reopen or change the state of the previous issue. 

I still cannot reach the table method
TransactionManager.getInstance().addTransaction(new ProcessModelTransaction<>(ProcessModelInfo.withModels(admissionEntitlementJSONModel).table(AdmissionEntitlement.class)));

And if I remove it, ProcessModelTransaction is abstract and wants to implement the process model methods. Could you please provide an example? Maybe adding it to the example app...

**Comment by agrosner** [comment]
there's logic inside of ```ProcessModelTransaction``` to handle it. Currently there's an issue where if the list is empty it will crash #106

**Comment by agrosner** [comment]
you don't need the method anymore. as of 1.6.2, you can simply call the method as normal and it _should_ work. Reopen if this is still an issue.
