### ISSUE TITLE
Increase/Decrease Method support

### ISSUE THREAD

**Issue by liorzam** [Raizlabs/DBFlow#1121]
DBFlow Version:4.0.0-beta2
Issue Kind : Feature
Description: 
Adding new SQLCondition for increase/decrease INTEGER column

like:
SQLite.update(User.class).set(User_Table.friendsCount.increase())

**Comment by agrosner** [comment]
not sure if such a method exists. Can you point me to the SQLite documentation for this method?

**Comment by agrosner** [comment]
you can use the `concatenate(1)` method on a `Property`. Also that query you want to use should be used this way:
```java
SQLite.update(User.class).set(User_Table.someColumn.concatenate(1)).executeUpdateDelete();
```
