### ISSUE TITLE
Run a very complex query like SQLite().setQuery("SELECT * FROM ....").execute()

### ISSUE THREAD

**Issue by Douvi** [Raizlabs/DBFlow#1122]
DBFlow Version: 4.0.0-beta3
Issue Kind (Question): Run a very complex query with using SQLite().setQuery("SELECT * FROM ....")

Description: 
My question is very simple, I have a very complex query to run and I do not want to speed time to translate it into `SQLite` object with `select`, `from`, `join`.... I would to run directly my query I get the result like `SQLite().setQuery("SELECT * FROM ....").execute()`.

The only example I saw is:
`FlowManager.getDatabase("MY_DB").getWritableDatabase().rawQuery("SELECT * FROM ....")`

Someone can told me if it's the right way or `DBFlow` do have other method to run a `SQL String` ?

Thanks

**Comment by agrosner** [comment]
Use StringQuery
