### ISSUE TITLE
Kotlin: val fields in data classes

### ISSUE THREAD

**Issue by wcarmon** [Raizlabs/DBFlow#1124]
DBFlow Version: 4.0.0-beta3
Issue Kind (Bug, Question, Feature): Question

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

Are there any plans to make DBFlow work with kotlin data classes that contain val (not var) fields?

When the annotation processor is running, I get this error message: 

Error:*==========*class com.raizlabs.android.dbflow.processor.ColumnValidator :Could not find setter for private element: "myField" from table class: MyEntity. Consider adding a setter with name setMyField or making it more accessible.*==========*

It looks like that validation happens here: 
https://github.com/Raizlabs/DBFlow/blob/4.0.0-beta3/dbflow-processor/src/main/java/com/raizlabs/android/dbflow/processor/Validators.kt#L51

I imagine this would require setting fields at construction time rather than using setters.

**Comment by agrosner** [comment]
No plans as of now. Without setters we cannot generate compilable code that reads data out of the db into the `Model`. May I suggest you trying `@QueryModel`. I believe though that this will still fail with a bug in DBFlow's `PrivateScopeColumnAccessor`. So ill leave it open to investigate.

**Comment by agrosner** [comment]
Scratch that last statement, that wouldnt work. So no not supported with `val`

**Comment by 2x2xplz** [comment]
To clarify: will `val` work for plain Kotlin classes? It appears they will not, based upon my experience, but the question above specifically asks about `data` classes. I was hoping you could confirm `val` is not supported for ALL Kotlin classes.  (using DBFlow 4.0.0-beta7, Kotlin 1.1)
