### ISSUE TITLE
beta-4 import problem

### ISSUE THREAD

**Issue by iagocanalejas** [Raizlabs/DBFlow#1129]
DBFlow Version:
Issue Kind (Bug, Question, Feature): Bug

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: I try updating from beta-3 to beta-4 and now i cant import all required annotations to build a model. This is my gradle dependencies for dbflow (using kotlin):

```ruby
dependencies {
    kapt "com.github.Raizlabs.DBFlow:dbflow-processor:4.0.0-beta4"
    compile "com.github.Raizlabs.DBFlow:dbflow:4.0.0-beta4@aar"
    compile "com.github.Raizlabs.DBFlow:dbflow-kotlinextensions:4.0.0-beta4@aar"
}
```

And the package i can't import is 
```java
    import com.raizlabs.android.dbflow.annotation.*
```

**Comment by agrosner** [comment]
yeah it looks like there was an issue with the generated pom files. I will have to figure out what happened tonight

**Comment by trevjonez** [comment]
@agrosner seems to be a fluke. by requesting a commit hash directly it worked out fine.
```groovy
annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:ad83cbacc0"
compile "com.github.Raizlabs.DBFlow:dbflow:ad83cbacc0"
compile "com.github.Raizlabs.DBFlow:dbflow-core:ad83cbacc0"
```

**Comment by agrosner** [comment]
try beta5 now

**Comment by iagocanalejas** [comment]
All seems working in a quick look. Thank you :)
