### ISSUE TITLE
Unable to compile against 4.0.0-beta4

### ISSUE THREAD

**Issue by ramib85** [Raizlabs/DBFlow#1130]
DBFlow Version: 4.0.0-beta4
Issue Kind (Bug): Unable to compile against 4.0.0-beta4

When adding the dependencies as specified in Readme, the gradle build fails.

Description: 
I'm unable to compile my project against 4.0.0-beta4 artifacts.
I'm using a gradle build on a new empty project.
I've copied the dependencies for java (no kotlin) to my dependencies, and I'm using apt to apply the processor.

The build output is:
Error:Module 'com.github.Raizlabs.DBFlow:dbflow-sqlcipher:4.0.0-beta4' depends on one or more Android Libraries but is a jar
Error:Module 'com.github.Raizlabs.DBFlow:dbflow:4.0.0-beta4' depends on one or more Android Libraries but is a jar
Error:Module 'com.github.Raizlabs.DBFlow:dbflow-core:4.0.0-beta4' depends on one or more Android Libraries but is a jar

I suspect that artifacts for 4.0.0-beta4 aren't created correctly, or their pom file needs to be fixed.
I was able to compile 4.0.0-beta3 successfully without issues.

**Comment by trevjonez** [comment]
have you tried specifying the `@aar` on the end of your dependency line? I think something either changed with the maven plugin config or with jitpack that may be causing these problems

**Comment by ramib85** [comment]
Yes, I have tried to add @aar to dbflow dependency,
It helped to remove just one of the error lines.

It seems for some reason that dbflow-core depends on the other dbflow
dependcies, which is weird.
 you can see this in ~/.gradle cache directory, under dbflow-core there are
subfolders for each of the other dependencies.

Can you also upload the artifacts to Jcenter/Maven central ?

**Comment by trevjonez** [comment]
give this a try, seems to be working just fine for me:
```groovy
annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:ad83cbacc0"
compile "com.github.Raizlabs.DBFlow:dbflow:ad83cbacc0"
compile "com.github.Raizlabs.DBFlow:dbflow-core:ad83cbacc0"
```

**Comment by agrosner** [comment]
try beta5 now

**Comment by ramib85** [comment]
Beta5 works for me,
Thank you.
