### ISSUE TITLE
For ver 3.0.0 beta5, pom file does not exist

### ISSUE THREAD

**Issue by hoshi005** [Raizlabs/DBFlow#1132]
DBFlow Version: 3.0.0 beta5
Issue Kind (Bug, Question, Feature): Question

Description: 

I am using Bitrise to build it.

https://www.bitrise.io/dashboard

However, we can not build from December 20, 2016.
I have confirmed that it was able to build on December 17, 2016.

The reason for the error seems to be that the following pom file can not be acquired.

https://jitpack.io/com/github/Raizlabs/DBFlow/dbflow-processor/3.0.0-beta5/dbflow-processor-3.0.0-beta5.pom

What should I do?

Thanks.

**Comment by trevjonez** [comment]
seems like it may be an issue with jitpack? https://jitpack.io/com/github/Raizlabs/DBFlow/3.0.0-beta5/build.log

The log looks fine but who knows, they really are a black box.

Why not upgrade to a newer version?

**Comment by agrosner** [comment]
I would try if you can upgrade to 3.1.1, but depending on implementation, you might be able to go all the way up to 4.0.0-beta5.

**Comment by hoshi005** [comment]
As java of "jitpack" became version 8, it seemed that the build of DBFlow Version: 3.0.0 - beta 5 failed.

com.raizlabs.android.dbflow.processor.definition.column.ColumnDefinition#appendPropertyComparisonAccessStatement

It seems to be caused by @return in the javadoc comment of this method.

So it is OK if you use ver 3.1.1 or later.

For the old version, if you modify the comment, the problem will be solved.
