### ISSUE TITLE
ModelClass_Table gives error

### ISSUE THREAD

**Issue by WanClem** [Raizlabs/DBFlow#1135]
Hey guys,nice job on DbFlow..Am new at this and wanted to try it out..After creating my Model as LastMessage and wanted to perform a query, Android studio marks `LastMessage_Table` as error..What could be wrong? Am using DBFlow `4.0.0-beta5` .

Here is my model.

` @Table(database = MessagesDatabase.class)
    public class LastMessage extends BaseModel {

    @Column
    @PrimaryKey
    int id;

    @Column
    String recipient;

    @Column
    String messageType;

    @Column
    String messageTextBody;

    @Column
    Date timeStamp;

    public void setRecipient(String recipient) {
        this.recipient = recipient;
    }

    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    public void setMessageTextBody(String messageTextBody) {
        this.messageTextBody = messageTextBody;
    }

} 

Here I tried getting a single lastmessage for a given recipient

` LastMessage lastMessage = SQLite.select().from(LastMessage.class).where(LastMessage_Table.recipient.is("u898981")).querySingle();
`

Android studio marks  `LastMessage_Table` as error. Any help would be greatly appreciated. All the same thanks for this awesome library.

**Comment by DreierF** [comment]
I assume the error says "Could not find reference LastMessage_Table" or similar, right?
Did you import the table class like `import my.package. LastMessage_Table;`?
Did you try to Invalidate the cache of Android Studio. Helped me already a few times. (File -> Invalidate caches -> Invalidate and Restart)

**Comment by agrosner** [comment]
yeah make sure you build project first and then try it. If not, ensure incremental compilation is off.
