### ISSUE TITLE
v

### ISSUE THREAD

**Issue by deltaeko** [Raizlabs/DBFlow#1136]
DBFlow Version:
Issue Kind (Bug, Question, Feature):

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description:

**Comment by agrosner** [comment]
Looks like a mistake. Im closing it.
