### ISSUE TITLE
is there bug?

### ISSUE THREAD

**Issue by mashazavolnyuk** [Raizlabs/DBFlow#1137]
### #
Description: 
Hello,Now I am using "4.0.0-beta5 and have problem with  UNIQUE constraint failed! I want to add new field with the samw data but can't. I try some variants but without result .
I have this in my DB:
 @Column
    @NotNull
    @Unique(unique = false,uniqueGroups = 1,onUniqueConflict = ConflictAction.REPLACE)
    private String name;

and this
 Person n=new Person();
        n.setName("sad");
        n.save(); //try to second and have promlem

I don't know how add second objects without failer(

**Comment by terry111zc** [comment]
I have the same problem,can you help me ?
