### ISSUE TITLE
[Feature Request] simplify the relationships (3 methods to 1)

### ISSUE THREAD

**Issue by xanscale** [Raizlabs/DBFlow#1141]
Actually there are 3 method to make a relationships: @ForeignKey, @OneToMany, @ManyToMany.
But they mean same things: a column value are a primary key of another table.

Actually can i create all of 3 type of relationships using only @ForeignKey

- 1to1: normal use of @ForeignKey
- OneToMany: put @ForeignKey in the "many" table that point to "one" table
- ManyToMany: create a new Table who have 2 @ForeignKey, 1 from each table

i think that this method is more SQL like and i don't see any advantage with current method

**Comment by agrosner** [comment]
They all serve different purposes. They don't all mean the same thing. 

> `1to1: normal use of @ForeignKey`
Yep
> `OneToMany: put @ForeignKey in the "many" table that point to "one" table`
No, it just a managed field that holds onto a `List` that gets inserted into the save, delete, insert, etc of the parent `Model`. 
> `ManyToMany: create a new Table who have 2 @ForeignKey, 1 from each table`
Yes, it generates the table for you. 

Combining them into one annotation is ripe for confusion.
