### ISSUE TITLE
create new Table on new version of application

### ISSUE THREAD

**Issue by tux-world** [Raizlabs/DBFlow#1142]
when i try to have some new table on application i increase app version and i expectation to create new table, but i get error such as:

no such table: UserChannelInformation (code 1): , while compiling: INSERT INTO `UserChannelInformation`(`channelId`) VALUES (?)

**Comment by agrosner** [comment]
increase the database version. app version has nothing to do with database version. 
https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html#onUpgrade(android.database.sqlite.SQLiteDatabase, int, int)
is where we do new tables, migrations,etc.

**Comment by tux-world** [comment]
ok so how can i create custom class to have migration file? dbflow has any helper to upgrade database?

i cant find any documentation about that on this library migration

**Comment by agrosner** [comment]
Just add your table and increment the database version. Restart the app.

**Comment by agrosner** [comment]
https://github.com/Raizlabs/DBFlow/blob/master/usage2/Migrations.md

**Comment by abiemann** [comment]
Mahdi, below is how I've done it. I assume a CREATE TABLE sqlite command is not needed - I haven' tried adding a completely new table yet.

```
@Migration(version = 3, database = AppDatabase.class)
public class MigrateTo03 extends BaseMigration {
    @Override
    public void migrate(@NonNull DatabaseWrapper database) {
        database.execSQL("ALTER TABLE `Person` ADD COLUMN `birthState` TEXT;");
        database.execSQL("ALTER TABLE `Person` ADD COLUMN `birthCountry` TEXT;");
        //database.execSQL("CREATE TABLE `HealthTopic` ... etc... ;"); not needed ?
        Timber.i("Upgraded Database to version 3");
    }
}
```
