### ISSUE TITLE
Change primary key column

### ISSUE THREAD

**Issue by gekitz** [Raizlabs/DBFlow#1143]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Question

Description: 
I want to update my primary key from one column to another column. What's the best way to do that?

**Comment by agrosner** [comment]
Best way is create a migration that takes existing table, reads it into a temporary another table, then renames the new table after dropping existing. More on that in this file: https://github.com/Raizlabs/DBFlow/blob/master/dbflow-tests/src/test/java/com/raizlabs/android/dbflow/test/sql/FixPrimaryKeyMigration.kt. Hope this helps.

**Comment by mohamadk** [comment]
link doesn't work anymore

**Comment by elsennov** [comment]
@agrosner could you please provide the updated link? thanks
