### ISSUE TITLE
Extends class from module

### ISSUE THREAD

**Issue by RimonGazi** [Raizlabs/DBFlow#1146]
DBFlow Version:Extends class from module
Issue Kind (Question):
Description: 
i have a model like "A.java" this model have many Column so i want to divide this 3 class like B.java,
C.java, D.java.  i want to use A.java model extend all there class and user their Column. how can i do this?

**Comment by agrosner** [comment]
If you mean merging three different base classes into a parent class, then that is not supported by Java so the lib does not support this. Not sure what you are trying to do, but unfortunately we don't support "flattening" other columns into the table. The only way we support that (as of now) is via `@ForeignKey`

**Comment by agrosner** [comment]
I could see if you specified something like:
```java
@Table(database = ...)
public class A {

  @PrimaryKey(autoincrement = true)
  int id;
  
  @Column
  B b;

  @Column
  C c;

  @Column
  D d;

}
```
then the lib would take each defined `@Column` and use that as part of the table?

**Comment by RimonGazi** [comment]
Actually number of column in my table is >100 so i want to divide the class and i did this way .

```
public class A extends BaseModel{
  @Column
  Integer a;
}

public class B extends A{
  @Column
  Integer b;
}

@Table(database = ...)
public class MyFinalTableModel extends B{

  @PrimaryKey(autoincrement = true)
  int id;

  @Column
  Integer v;
}
```
