### ISSUE TITLE
ManyToMany example

### ISSUE THREAD

**Issue by kurak38** [Raizlabs/DBFlow#1147]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Question

Description: 
Can someone provide a working example of ManyToMany relationship and usage of @ManyToMany annotation + how to properly set up all others foreign keys and methods. I've tried to use it, insert manually into auto-generated table but it crashes with SQLite exception about too many files opened or too large transaction.
Thanks

**Comment by agrosner** [comment]
Not sure if this is the place to post this question, but if you could provide more info into what is generated and your models look like, that might help.
