### ISSUE TITLE
How can I add a uri to uriMatcher then handle it?

### ISSUE THREAD

**Issue by sanegan199x** [Raizlabs/DBFlow#1148]
DBFlow Version: 3.1.1.
Issue Kind (Question):

I know in native method to create a Content Provider should have a uriMatcher to match uri that Content Resolver request. But with DBFlow, I don't know how can I add a new uri and where I can implement it. For example, I want to add a uri 'http://com.example.bk/movies/1' to set of matches. So what should I do?
P/S: Sorry for my english

**Comment by danvwells** [comment]
DBFlow can generate your content provider.  I haven't used this feature yet, but have you looked at this: https://github.com/Raizlabs/DBFlow/blob/master/usage2/ContentProviderGeneration.md?

You may have already seen this, but I thought I'd mention it just in case.

**Comment by agrosner** [comment]
this can go on stackoverflow
