### ISSUE TITLE
ForiegnKeyContainer takes too much time to load table

### ISSUE THREAD

**Issue by rspl17** [Raizlabs/DBFlow#1149]
DBFlow Version:
Issue Kind (Bug, Question, Feature):

Description: 
@agrosner : any help will be good
I have been using foriegnKeyContainer for relationship between tables but to load the relationships it takes more than 2-3 sec even to load a single record any help ?
I am using like this : tableA.foriegnKeyContainer.load();

**Comment by agrosner** [comment]
Not so sure here what your model looks like or what you are doing in the app. If you are writing to other parts of db while retrieving, it may be blocked until that happens.

**Comment by trevjonez** [comment]
If you can prove it is a read/write block that is slowing you down you might consider turning on write ahead logging. https://www.sqlite.org/wal.html

**Comment by rspl17** [comment]
@trevjonez @agrosner  thanks for your comments, Actually that model has 1 to many relationship with 2 other model, thats why for each model its fetching the many relationship each time.

Is there any good way to fetch these relationship faster or I can enable or disable this prefetch of relationship models whenever I required ?

**Comment by trevjonez** [comment]
Can you setup a demo project that exhibits this behavior so we can play with it and get a better understanding?

**Comment by sigfridod** [comment]
@agrosner  is there any way to make it enable easily

**Comment by agrosner** [comment]
You can use flowQueryList instead of queryList and then it'll be lazy loaded.

**Comment by agrosner** [comment]
Just don't forget to close when done, that's the only caveat
