### ISSUE TITLE
Field always zero

### ISSUE THREAD

**Issue by ted66** [Raizlabs/DBFlow#115]
My Model

@Table(databaseName = AppDatabase.NAME)
public class PinModel extends BaseModel {
    @Column(columnType = Column.PRIMARY_KEY)
    public String id;

    @Column
    public Long createTime;

    @Column
    public String gameDate;

    @Column
    public Integer position;
}

I will save data to table

PinModel pinModel = new PinModel();
pinModel.id = gsonAllGameObject.getId();
pinModel.createTime = System.currentTimeMillis();
pinModel.gameDate = mDate;
pinModel.position = i;
TransactionManager.getInstance().save(ProcessModelInfo.withModels(pinModel));

But only position field always 0

I have check i  isn't 0 but no insert to table

How to slove it? thx

**Comment by agrosner** [comment]
Placing the model on the ```TransactionManager``` puts it on a background thread to save. It happens asynchronously. If you wish to save it immediately, just use the ```.save(false)``` method.

**Comment by ted66** [comment]
Before only zero

http://i.imgur.com/0HfZgfY.png

@agrosner if i add pinModel.save(fale) the data is zero and auto add null row

http://i.imgur.com/dVBQgx4.png

but thx your help

**Comment by ted66** [comment]
for (int i = 0; i < mlist.size(); i++) {
            for (GsonAllGameObject object : mlist) {
                if (mlist.get(i).getId().equals(gameId)) {
                    GsonAllGameObject gsonAllGameObject =  mlist.get(i);
                    mlist.remove(i);
                    mlist.add(0, gsonAllGameObject);

                    PinModel pinModel = new PinModel();
                    pinModel.id = gsonAllGameObject.getId();
                    pinModel.createTime = System.currentTimeMillis();
                    pinModel.gameDate = mDate;
                    pinModel.position = i;
                    mDBHelper.saveData(pinModel);
                    break;
                }
            }
        }

This in baseAdapter

pinModel.position = i; 
the position is zero

but i try to assign number
pinModel.position = 3

the position is 3

how different?
