### ISSUE TITLE
Saving Model when app is closed

### ISSUE THREAD

**Issue by ptsiogas** [Raizlabs/DBFlow#1150]
DBFlow Version:
Issue Kind (Question):
Description: Hello i am trying to save a model into my DB when the app is killed (a notification triggers this event). So the onMessageReceived method is called but i had no luck in saving my model in db. Is something like this possible with DBFlow and how?

 ```java
@Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        NotificationModel model = new NotificationModel(false, true, remoteMessage.getSentTime(), null, remoteMessage.getNotification().getBody(), remoteMessage.getNotification().getClickAction());
        model.save();
}
```

**Comment by trevjonez** [comment]
This should work so long as DBFlow has been initialized before `onMessageReceived` is called. You can add some logging to your application class and service class to be able to observe how things are initialized and in what order. There may be other concerns if your service is being ran inside of a different process however I am not familiar with that type of use case.

**Comment by agrosner** [comment]
Yes you need to make sure DBFlow is initialized before doing that. it won't reinitialize the holders if they already exist, but it will replace the `FlowConfig` so ensure that you initialize dbflow the same way.
