### ISSUE TITLE
How can I get Access to DatabaseWrapper or SQLiteDatabase from code

### ISSUE THREAD

**Issue by Fornori** [Raizlabs/DBFlow#1152]
DBFlow Version: 4.0.0-beta5
Issue Kind (Bug, Question, Feature): Question

Hello. Inside my code I need to check is column exist in the table. So i have a qestion - how can I get access to DatabaseWrapper from my own code - not inside Migration?

**Comment by DreierF** [comment]
Not sure if this is the most elegant way to achieve the goal, but the following should work:
```FlowManager.getDatabase(AppDatabase.NAME).getHelper().getDatabase().execSQL("...");```

**Comment by agrosner** [comment]
You can do `FlowManager.getWritableDatabase(MyDatabaseClass.class)`

**Comment by AlyssonPHN** [comment]
Please release access to SQLiteDatabase

**Comment by AlyssonPHN** [comment]
Please release access to SQLiteDatabase
