### ISSUE TITLE
Make simple relationShip between 2 table

### ISSUE THREAD

**Issue by tux-world** [Raizlabs/DBFlow#1154]
I'm trying to make simple relationShiop between two table as `Sahmiye`and `FoodData` with `OneToMany`, in first time i get this error:

`Error:(69, 42) error: cannot find symbol variable queenForeignKeyContainer_id`

My `Sahmiye` class:

```
@Table(database = AppDatabase.class)
public class Sahmiye {
    @PrimaryKey(autoincrement = true)
    private int id;

    @Column
    private String title;

    @Column
    private String parentId;

    public List<FoodData> foodData;

    public Sahmiye() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public List<FoodData> getFoodData() {
        return foodData;
    }

    public void setFoodData(List<FoodData> foodData) {
        this.foodData = foodData;
    }

    @OneToMany(methods = {OneToMany.Method.ALL}, variableName = "foodData")
    public List<FoodData> getMyFoodDatas() {
        if (foodData == null || foodData.isEmpty()) {
            foodData = SQLite.select()
                    .from(FoodData.class)
                    .where(FoodData_Table.queenForeignKeyContainer_id.eq(id))
                    .queryList();
        }
        return foodData;
    }
}
```

and my `FoodData` Table:

```
@Table(database = AppDatabase.class)
public class FoodData {
    @PrimaryKey(autoincrement = true)
    private int     id;

    @Column
    private String  title;

    @Column
    private boolean rice;

    @Column
    private int     foodId;

    @Column
    private int     parentId;

    public FoodData() {
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public boolean isRice() {
        return rice;
    }

    public void setRice(boolean rice) {
        this.rice = rice;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
    public int getFoodId() {
        return foodId;
    }
    public void setFoodId(int foodId) {
        this.foodId = foodId;
    }
    public int getParentId() {
        return parentId;
    }
    public void setParentId(int parentId) {
        this.parentId = parentId;
    }
}
```

could you fix my relation ship? thanks in advance

**Comment by agrosner** [comment]
youre referencing a column in the that table which is not defined. `queenForeignKeyContainer_id` im assuming you pulled from the old example.

**Comment by tux-world** [comment]
maybe you have right, could you fix my code? i cant do that

**Comment by sigfridod** [comment]
@tux-world You have to create a "SahmiyeForiegnKeyContainer" in FoodData table. This will resolve your issue

**Comment by tux-world** [comment]
@sigfridod i'm so sorry sir. i'm newbie in using this library on android projects, is this correct?


```
@Table(database = AppDatabase.class)
public class FoodData {
    @ForeignKey(tableClass = Sahmiye.class)
    @PrimaryKey(autoincrement = true)
    private int     id;

    @Column
    private String  title;

    @Column
    private boolean rice;

    @Column
    private int     foodId;

    @Column
    private int     parentId;

```

**Comment by sigfridod** [comment]
@tux-world Just add below code in your FoodData model

@ForeignKey
ForeignKeyContainer<Sahmiye> data;

**Comment by tux-world** [comment]
@sigfridod in top of class instead of @Table ?

**Comment by sigfridod** [comment]
@tux-world No add below 
 @Column
    private int     parentId;

this one

**Comment by CapnSpellcheck** [comment]
@sigfridod Where is ForeignKeyContainer defined? I don't get such class to show up in Android Studio.

**Comment by CapnSpellcheck** [comment]
I feel the OneToMany doc example could be better. If it's not obvious how to make the code in getAnts() valid, it should be improved...

**Comment by tux-world** [comment]
@CapnSpellcheck Unfortunately the document is very very summarized and its not for more users. i cant use document, because its could be very very better with now. and this library developer expect to users must be know that

**Comment by CapnSpellcheck** [comment]
OK, I think I have it: (at least, this compiles!)

On the 'one' table I have a field for PK:
`    @NotNull @PrimaryKey lateinit var ID: String
`
Then in the 'many' table I have FK defined this way, attributes important:
`    @NotNull @ForeignKey(stubbedRelationship = true, tableClass = ProspectQuiz::class) lateinit var quizID: String
`

This produces a FK field in the generated table model which we can use in the @OneToMany loading function. It seems to be the name of the PK field in the main table with '_ID' added.
```
 /**
   * Foreign Key */
  public static final Property<String> quizID_ID = new Property<String>(ProspectQuizEntry.class, "quizID_ID");
```


@agrosner I really suggest a refresh of the example, very confusing

**Comment by agrosner** [comment]
The example has been removed. I dont include it anymore and just provide examples at certain sections.

**Comment by agrosner** [comment]
use this for reference https://github.com/Raizlabs/DBFlow/blob/master/usage2/Relationships.md

**Comment by driff** [comment]
hey im having problems with this, i'm not sure if the 1 to many example is updated since it looks exactly as @tux-world problem, anyway if you could help me out, here's my problem:

this is the list of orderDetails i'm calling from the parent class 'Order' 
`
@OneToMany(methods = {OneToMany.Method.ALL}, variableName = "orderDetailList")
    public List<OrderDetail> getOrderDetailList(){
        if(orderDetailList!= null&&orderDetailList.isEmpty()){
            orderDetailList = SQLite.select().from(OrderDetail.class).where(OrderDetail_Table.order_id.eq(id)).queryList();
        }
        return orderDetailList;
    }
`

and this is the fk i got in the child class
`@Column
    @ForeignKey(stubbedRelationship = true, tableClass = Order.class)
    Order order;`

and i'm getting this error 

> Error:(35, 94) error: package OrderDetail_Table does not exist
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

any help is appreciated

**Comment by MahdiPishguy** [comment]
@driff could you hep me for this issue:

https://github.com/Raizlabs/DBFlow/issues/1316
