### ISSUE TITLE
QueryModel for Select with an foreign key result Error

### ISSUE THREAD

**Issue by PrincessMelime** [Raizlabs/DBFlow#1155]
Hi!.

Here is my Base Model Object OrmActivity:

@Table(database = AdlavDatabase.class)

public class OrmActivity extends BaseModel{
    
    @Column
    @PrimaryKey
    private long activityId;
    @Column
    private String date;
    @Column
    private double locationLatitude;
    @Column
    private double locationLongitude;
    @Column
    private String posId;
    @Column
    private String posBusinessName;
    @Column
    private String posStreetName;
    @Column
    private int posStreetNum;
    @Column
    private String posAdressDetail;
    @Column
    private double posLocationLatitude;
    @Column
    private double posLocationLongitude;
    @Column
    private int posVisitDetail;
    @Column
    private int type;
    @Column
    @ForeignKey(saveForeignKeyModel = false)
    private OrmActivityDownloadState ormActivityDownloadState;

    public OrmActivity() {}

    public long getActivityId() {
        return activityId;
    }

    public String getDate() {
        return date;
    }

    public double getLocationLatitude() {
        return locationLatitude;
    }

    public double getLocationLongitude() {
        return locationLongitude;
    }

    public String getPosId() {
        return posId;
    }

    public String getPosBusinessName() {
        return posBusinessName;
    }

    public String getPosStreetName() {
        return posStreetName;
    }

    public int getPosStreetNum() {
        return posStreetNum;
    }

    public String getPosAdressDetail() {
        return posAdressDetail;
    }

    public double getPosLocationLatitude() {
        return posLocationLatitude;
    }

    public double getPosLocationLongitude() {
        return posLocationLongitude;
    }

    public int getPosVisitDetail() {
        return posVisitDetail;
    }

    public int getType() {
        return type;
    }

    public OrmActivityDownloadState getOrmActivityDownloadState() {
        return ormActivityDownloadState;
    }

    public void setActivityId(long id) {
        activityId = id;
    }

    public void setDate(String da) {
        date = da;
    }

    public void setLocationLatitude(double la) {
        locationLatitude = la;
    }

    public void setLocationLongitude(double lo) {
        locationLongitude = lo;
    }

    public void setPosId(String pId) {
        posId = pId;
    }

    public void setPosBusinessName(String pBn) {
        posBusinessName = pBn;
    }

    public void setPosStreetName(String psn) {
        posStreetName = psn;
    }

    public void setPosStreetNum(int psn) {
        posStreetNum = psn;
    }

    public void setPosAdressDetail(String pad) {
        posAdressDetail = pad;
    }

    public void setPosLocationLatitude(double pla) {
        posLocationLatitude = pla;
    }

    public void setPosLocationLongitude(double plo) {
        posLocationLongitude = plo;
    }

    public void setType(int ty) {
        type = ty;
    }

    public void setOrmActivityDownloadState(OrmActivityDownloadState ds) {
        ormActivityDownloadState = ds;
    }

    public void setPosVisitDetail(int pvd) {
        posVisitDetail = pvd;
    }
}

In this object I've got a Foreign Key to OrmActivityDownloadState.

When I execute this select:

Select().from(OrmActivity.class).queryList(); all work fine. Each OrmActivity cointain their own OrmActivityDownloadState object.

But...and THIS IS THE PROBLEM..when I want to use this table in a Select with a join that get for result an distinct Object (using a QueryModel) I got this error:
 
 No type converter for: ar.com.arconsultores.adlav_f1.helper.data.orm_dbflow.orm_entity.OrmActivityDownloadState -> ormActivityDownloadState from class: ar.com.arconsultores.adlav_f1.helper.data.orm_dbflow.orm_entity.OrmSummaryActivity. Pleaseregister with a TypeConverter.

This is my QueryModel:

@QueryModel(database = AdlavDatabase.class)

public class OrmSummaryActivity{

    @Column
    private long activityId;
    @Column
    private String date;
    @Column
    private double locationLatitude;
    @Column
    private double locationLongitude;
    @Column
    private String posId;
    @Column
    private String posBusinessName;
    @Column
    private String posStreetName;
    @Column
    private int posStreetNum;
    @Column
    private String posAdressDetail;
    @Column
    private double posLocationLatitude;
    @Column
    private double posLocationLongitude;
    @Column
    private int posVisitDetail;
    @Column
    private int type;
    @Column
    private OrmActivityDownloadState ormActivityDownloadState;
    @Column
    private int visitType;

    public OrmSummaryActivity() {}

    public int getVisitType() {
        return visitType;
    }

    public void setVisitType(int vType) {
        this.visitType = vType;
    }

    public long getActivityId() {
        return activityId;
    }

    public String getDate() {
        return date;
    }

    public double getLocationLatitude() {
        return locationLatitude;
    }

    public double getLocationLongitude() {
        return locationLongitude;
    }

    public String getPosId() {
        return posId;
    }

    public String getPosBusinessName() {
        return posBusinessName;
    }

    public String getPosStreetName() {
        return posStreetName;
    }

    public int getPosStreetNum() {
        return posStreetNum;
    }

    public String getPosAdressDetail() {
        return posAdressDetail;
    }

    public double getPosLocationLatitude() {
        return posLocationLatitude;
    }

    public double getPosLocationLongitude() {
        return posLocationLongitude;
    }

    public int getPosVisitDetail() {
        return posVisitDetail;
    }

    public int getType() {
        return type;
    }

    public OrmActivityDownloadState getOrmActivityDownloadState() {
        return ormActivityDownloadState;
    }

    public void setActivityId(long id) {
        activityId = id;
    }

    public void setDate(String da) {
        date = da;
    }

    public void setLocationLatitude(double la) {
        locationLatitude = la;
    }

    public void setLocationLongitude(double lo) {
        locationLongitude = lo;
    }

    public void setPosId(String pId) {
        posId = pId;
    }

    public void setPosBusinessName(String pBn) {
        posBusinessName = pBn;
    }

    public void setPosStreetName(String psn) {
        posStreetName = psn;
    }

    public void setPosStreetNum(int psn) {
        posStreetNum = psn;
    }

    public void setPosAdressDetail(String pad) {
        posAdressDetail = pad;
    }

    public void setPosLocationLatitude(double pla) {
        posLocationLatitude = pla;
    }

    public void setPosLocationLongitude(double plo) {
        posLocationLongitude = plo;
    }

    public void setType(int ty) {
        type = ty;
    }

    public void setOrmActivityDownloadState(OrmActivityDownloadState ds) {
        ormActivityDownloadState = ds;
    }

    public void setPosVisitDetail(int pvd) {
        posVisitDetail = pvd;
    }

}

What am I doing wrong?...I would appreciate your help.
Regards!

**Comment by agrosner** [comment]
@PrincessMelime since `@QueryModel` do not support `@ForeignKey` you would have to manually name out each of the foreign keys as separate fields that satisfy the query.

**Comment by PrincessMelime** [comment]
Thanks for your response!...

**Comment by sigfridod** [comment]
@agrosner  You mean to say if in table if I have one model as a @ForeignKey like

@ForeignKey
SomeModel someModel;

Than in my QueryModel it should be like 

public class MyQueryModel{

long id;

SomeModel someModel;

}
