### ISSUE TITLE
FlowQueryList will create FlowCursorList with model cache object even if model cache should be disabled

### ISSUE THREAD

**Issue by CapnSpellcheck** [Raizlabs/DBFlow#1157]
DBFlow Version: 4.0.0-beta3
Issue Kind (Bug, Question, Feature): Bug

Description: If I create a FlowQueryList like this
```
val flowBuilder = FlowQueryList.Builder<Prospect>(select)
        flowBuilder.cacheModels(false)
        flowBuilder.success(this)
        flowBuilder.error(this)
```

Then the internal cursor will create a `ModelCache` object and its `cacheModels` will be true, although the cache size will be 0, so it will burn some cycles for no purpose. 

Because FlowCursorList$Builder.cacheSize(int) sets cacheModels to true and `FlowQUeryList(Builder)` calls that _after_ call to cacheModels:

```
internalCursorList = new FlowCursorList.Builder<>(builder.table)
                .cursor(builder.cursor)
                .cacheModels(builder.cacheModels)
                .cacheSize(builder.cacheSize)
                .modelQueriable(builder.modelQueriable)
                .modelCache(builder.modelCache)
                .build();
```

**Comment by CapnSpellcheck** [comment]
Actually, a `ModelLruCache` is inside internalCursorList, with `maxSize`=25, so it seems it is using cache despite my request.

**Comment by agrosner** [comment]
in `develop`.
