### ISSUE TITLE
[Question] Additional columns in many to many join table

### ISSUE THREAD

**Issue by zubinmehta** [Raizlabs/DBFlow#1160]
DBFlow Version: 4.0.0-beta5
Issue Kind (Bug, Question, Feature): Question

Description: 
Hi,
I want to add more columns in the many to many join table. What is the recommended way to do it ?

I am guessing, I should not use @ManyToMany annotation and simple create that table by hand and have both foreignkeys inside that third table.

?

Thanks.

**Comment by xanscale** [comment]
i have table A and B. C is relation of A and B, also has other data.

i create C table manually and put on it 2 @foreignKey to point A and B.

i don't know if it's best wey

**Comment by agrosner** [comment]
yes if you need to add columns to the `@ManyToMany`, id copy the class file into your project and remove the annotation.

**Comment by agrosner** [comment]
that seems fine @xanscale to me.
