### ISSUE TITLE
Could not find com.android.support:support-annotations:25.1.0.

### ISSUE THREAD

**Issue by HappysWen** [Raizlabs/DBFlow#1161]
DBFlow Version:4.0.0-beta5
Issue Kind (Bug, Question, Feature):

Error:Could not find com.android.support:support-annotations:25.1.0.
Required by:
    community:app:unspecified
    community:app:unspecified > com.github.Raizlabs.DBFlow:dbflow:4.0.0-beta5

Please install the Android Support Repository from the Android SDK Manager.

**Comment by agrosner** [comment]
looks like you need to update your support repository. or you can force gradle onto an earlier version of the support lib dependency.
