### ISSUE TITLE
Cannot find symbol method. Has private access.

### ISSUE THREAD

**Issue by elsennov** [Raizlabs/DBFlow#1162]
DBFlow Version: 4.0.0-beta5
Issue Kind (Bug, Question, Feature): Bug
Instant run not used.

Description: 
Cannot use `set` as prefix for column name (like `setup`, `setting`). Error cannot find symbol method, `set[something]` has private access.

<img width="1280" alt="screen shot 2017-02-07 at 9 37 25 am" src="https://cloud.githubusercontent.com/assets/7565601/22675564/127539f0-ed19-11e6-80d9-73ff5842d712.png">

**Comment by agrosner** [comment]
its because it looks for `set` prefix dumbly and doesn't know difference between `setSetup` and `setUp`. So I would use `setterName="setSetup"`
