### ISSUE TITLE
Cannot find symbol class *_Table

### ISSUE THREAD

**Issue by taherhek** [Raizlabs/DBFlow#1166]
Thanks for great library.
Some times I get "Cannot find symbol class *_Table" for all my models. I know there is sth wrong with one of my models, however I don't know which one. So I have to comment all references for tables to find the model and debug it and this is really annoying.
I know it needs to build successfully first to create *_Tables but please do sth, to show the model that causes the error.
Thanks.

**Comment by agrosner** [comment]
The android plugin tends to hide those kind of errors especially if you have multiple annotation processors in your app.
