### ISSUE TITLE
Fields not picked up when @QueryModel with allFields = true

### ISSUE THREAD

**Issue by karltiirik** [Raizlabs/DBFlow#1167]
DBFlow Version: 4.0.0-beta5
Issue Kind (Bug, Question, Feature): Bug

Description: 
I have a class:
```
@QueryModel(database = AppDatabase.class, allFields = true)
public class AverageCar {
    String model;
}
```
I expect the generated code to be equivalent with generated code from: 
```
@QueryModel(database = AppDatabase.class)
public class AverageCar {
    @Column
    String model;
}
```

But the `model` field is not being picked up in the first example.

**Comment by agrosner** [comment]
good catch. let me look into it. sorry for long delay...

**Comment by agrosner** [comment]
this also affected `ModelView` so good find, thank you. in `develop`.
