### ISSUE TITLE
App doesnt work with 3.0.0-beta5. by changing release version to '3.0.0-beta6' or '3.0.0' Gradle sync works. But App fails as some of the classes doesnt exists.

### ISSUE THREAD

**Issue by pre2612** [Raizlabs/DBFlow#1168]
Error:A problem occurred configuring project ':app'.
> A problem occurred configuring project ':framework'.
   > Could not resolve all dependencies for configuration ':framework:_debugCompile'.
      > Could not find com.github.Raizlabs.DBFlow:dbflow-core:3.0.0-beta5.
        Searched in the following locations:
            file:/Volumes/Android Studio 2.2.3 1/Android Studio.app/Contents/gradle/m2repository/com/github/Raizlabs/DBFlow/dbflow-core/3.0.0-beta5/dbflow-core-3.0.0-beta5.pom
            file:/Volumes/Android Studio 2.2.3 1/Android Studio.app/Contents/gradle/m2repository/com/github/Raizlabs/DBFlow/dbflow-core/3.0.0-beta5/dbflow-core-3.0.0-beta5.jar
            https://jcenter.bintray.com/com/github/Raizlabs/DBFlow/dbflow-core/3.0.0-beta5/dbflow-core-3.0.0-beta5.pom
            https://jcenter.bintray.com/com/github/Raizlabs/DBFlow/dbflow-core/3.0.0-beta5/dbflow-core-3.0.0-beta5.jar
            https://repo1.maven.org/maven2/com/github/Raizlabs/DBFlow/dbflow-core/3.0.0-beta5/dbflow-core-3.0.0-beta5.pom
            https://repo1.maven.org/maven2/com/github/Raizlabs/DBFlow/dbflow-core/3.0.0-beta5/dbflow-core-3.0.0-beta5.jar
            https://jitpack.io/com/github/Raizlabs/DBFlow/dbflow-core/3.0.0-beta5/dbflow-core-3.0.0-beta5.pom
            https://jitpack.io/com/github/Raizlabs/DBFlow/dbflow-core/3.0.0-beta5/dbflow-core-3.0.0-beta5.jar
            https://urbanairship.bintray.com/android/com/github/Raizlabs/DBFlow/dbflow-core/3.0.0-beta5/dbflow-core-3.0.0-beta5.pom
            https://urbanairship.bintray.com/android/com/github/Raizlabs/DBFlow/dbflow-core/3.0.0-beta5/dbflow-core-3.0.0-beta5.jar
            file:/Users/borrawarp/AndroidStudioProjects/android/framework/libs/dbflow-core-3.0.0-beta5.jar
            file:/Users/borrawarp/AndroidStudioProjects/android/framework/libs/dbflow-core.jar
            file:/Users/borrawarp/Library/Android/sdk/extras/android/m2repository/com/github/Raizlabs/DBFlow/dbflow-core/3.0.0-beta5/dbflow-core-3.0.0-beta5.pom
            file:/Users/borrawarp/Library/Android/sdk/extras/android/m2repository/com/github/Raizlabs/DBFlow/dbflow-core/3.0.0-beta5/dbflow-core-3.0.0-beta5.jar
            file:/Users/borrawarp/Library/Android/sdk/extras/google/m2repository/com/github/Raizlabs/DBFlow/dbflow-core/3.0.0-beta5/dbflow-core-3.0.0-beta5.pom
            file:/Users/borrawarp/Library/Android/sdk/extras/google/m2repository/com/github/Raizlabs/DBFlow/dbflow-core/3.0.0-beta5/dbflow-core-3.0.0-beta5.jar
        Required by:
            android:framework:unspecified
      > Could not find com.github.Raizlabs.DBFlow:dbflow:3.0.0-beta5.
        Searched in the following locations:
            file:/Volumes/Android Studio 2.2.3 1/Android Studio.app/Contents/gradle/m2repository/com/github/Raizlabs/DBFlow/dbflow/3.0.0-beta5/dbflow-3.0.0-beta5.pom
            file:/Volumes/Android Studio 2.2.3 1/Android Studio.app/Contents/gradle/m2repository/com/github/Raizlabs/DBFlow/dbflow/3.0.0-beta5/dbflow-3.0.0-beta5.jar
            https://jcenter.bintray.com/com/github/Raizlabs/DBFlow/dbflow/3.0.0-beta5/dbflow-3.0.0-beta5.pom
            https://jcenter.bintray.com/com/github/Raizlabs/DBFlow/dbflow/3.0.0-beta5/dbflow-3.0.0-beta5.jar
            https://repo1.maven.org/maven2/com/github/Raizlabs/DBFlow/dbflow/3.0.0-beta5/dbflow-3.0.0-beta5.pom
            https://repo1.maven.org/maven2/com/github/Raizlabs/DBFlow/dbflow/3.0.0-beta5/dbflow-3.0.0-beta5.jar
            https://jitpack.io/com/github/Raizlabs/DBFlow/dbflow/3.0.0-beta5/dbflow-3.0.0-beta5.pom
            https://jitpack.io/com/github/Raizlabs/DBFlow/dbflow/3.0.0-beta5/dbflow-3.0.0-beta5.jar
            https://urbanairship.bintray.com/android/com/github/Raizlabs/DBFlow/dbflow/3.0.0-beta5/dbflow-3.0.0-beta5.pom
            https://urbanairship.bintray.com/android/com/github/Raizlabs/DBFlow/dbflow/3.0.0-beta5/dbflow-3.0.0-beta5.jar
            file:/Users/borrawarp/AndroidStudioProjects/android/framework/libs/dbflow-3.0.0-beta5.jar
            file:/Users/borrawarp/AndroidStudioProjects/android/framework/libs/dbflow.jar
            file:/Users/borrawarp/Library/Android/sdk/extras/android/m2repository/com/github/Raizlabs/DBFlow/dbflow/3.0.0-beta5/dbflow-3.0.0-beta5.pom
            file:/Users/borrawarp/Library/Android/sdk/extras/android/m2repository/com/github/Raizlabs/DBFlow/dbflow/3.0.0-beta5/dbflow-3.0.0-beta5.jar
            file:/Users/borrawarp/Library/Android/sdk/extras/google/m2repository/com/github/Raizlabs/DBFlow/dbflow/3.0.0-beta5/dbflow-3.0.0-beta5.pom
            file:/Users/borrawarp/Library/Android/sdk/extras/google/m2repository/com/github/Raizlabs/DBFlow/dbflow/3.0.0-beta5/dbflow-3.0.0-beta5.jar
        Required by:
            android:framework:unspecified

**Comment by agrosner** [comment]
might have been a temporary issue. please reference (https://github.com/Raizlabs/DBFlow#including-in-your-project) if you;re still having issues.
