### ISSUE TITLE
Bug: model is not registered with a Database

### ISSUE THREAD

**Issue by pavlea** [Raizlabs/DBFlow#1169]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question):
 
I get this error every time I tried to save data:
`com.raizlabs.android.dbflow.structure.InvalidDBConfiguration: Model object: com.app.bfriendly.user.database.User is not registered with a Database. Did you forget an annotation?
02-18 06:39:45.479 10462-10462/com.bfriendly.android.dev W/System.err:     at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseForTable(FlowManager.java:108)
02-18 06:39:45.479 10462-10462/com.bfriendly.android.dev W/System.err:     at com.raizlabs.android.dbflow.config.FlowManager.getModelAdapter(FlowManager.java:309)
02-18 06:39:45.479 10462-10462/com.bfriendly.android.dev W/System.err:     at com.raizlabs.android.dbflow.structure.BaseModel.getModelAdapter(BaseModel.java:117)
02-18 06:39:45.479 10462-10462/com.bfriendly.android.dev W/System.err:     at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:51)`

My Database class:
`
@Database(name = MyDatabase.NAME, version = MyDatabase.VERSION, foreignKeysSupported = true)
public class MyDatabase {

    public static final String NAME = "MyDb";

    public static final int VERSION = 1;
}`

and model:
`@Table(database = MyDatabase.class)
public class User extends BaseModel {

    @PrimaryKey(autoincrement = true)
    public int _id;

    @Unique(onUniqueConflict = ConflictAction.REPLACE)
    @Column
    public String userID;

    @Column
    public String createdAt;

    @Column
    public String updatedAt;

    @Column
    public String userName;
}`

I lost hours watching my code and I tried stupid thing like replace `annotationProcessor` with `apt` keyword in Gradle file and it started to work. So, your docs are wrong [https://github.com/Raizlabs/DBFlow#including-in-your-project](url)

**Comment by slambang** [comment]
+1

I've been trying to fix this myself for days and days. This simple trick fixed it all for me, so thank you!

**Comment by trevjonez** [comment]
what version of the android gradle plugin are you using?

**Comment by pavlea** [comment]
The latest, 2.2

**Comment by agrosner** [comment]
2.3 is the latest but should work with 2.2 nonethless. `apt` was a custom plugin that provided apt, while `annotationProcessor` is Android's name for it. The docs aren't wrong, something else in your project must be wrong.
