### ISSUE TITLE
UNIQUE constraint on multiple columns.

### ISSUE THREAD

**Issue by q1p** [Raizlabs/DBFlow#117]
Is it possible to implement with current version of DBFlow? Using Column annotation I can mark unique separate columns but not the group of columns. This constraint very useful but seems cannot be used with DBFlow.

**Comment by agrosner** [comment]
Let me understand your question. Why can't you just mark `@Column(unique = true)` to the columns you want?

**Comment by q1p** [comment]
This is not applicable when you need to make unique group of columns. For example two columns with `unique = true` property are not the same as constraint `UNIQUE(col1, col2)` where combination should be unique. In this case table can contain repeating values for `col1` and `col2`, but combination of this columns.

**Comment by agrosner** [comment]
ah! Interesting. Ok. I will add this as a feature request to a degree:
```@Table(uniqueColumns = {"col1", "col2"}``` 

or allow multiple may be better

```@Column(unique = true, uniqueGroup = 1)```

**Comment by q1p** [comment]
Thanks. Allowing multiple groups looks more flexible.

**Comment by agrosner** [comment]
now on master 1.7.0
