### ISSUE TITLE
Bug: Table properties will not be used correctly in generated code when using custom column names

### ISSUE THREAD

**Issue by TheWhiteLlama** [Raizlabs/DBFlow#1170]
DBFlow Version: 4.0.0-beta5

Description:
If I have the following classes:

Example1:
```
@Table(name = "example_table_1", database = Database.class)
public class Example1 extends BaseModel {

    @PrimaryKey
    public int id;

    @ForeignKey
    public Example2 relationTable;

}

```

Example2:
```
@Table(name = "example_table_2", database = Database.class)
public class Example2 extends BaseModel {

    @Column(name="custom_name")
    @PrimaryKey
    public int id;

}

```

The code generator will generate the Table classes wrongly when using a custom column name for a key. In the methods
`bindToInsertValues / bindToInsertStatement`
In the Example2_Table class it will generate:
```
if (model.relationTable != null) {
  values.put("`example2_id`", model.relationTable.custom_name);
} else {
  values.putNull("example2_id");
}
```
Important is to recognize that it should use `model.relationTable.id`  instead of `model.relationTable.custom_name` here since the code wants to reference a Java property of the model class itself.

**Comment by agrosner** [comment]
Good find. not sure how this got lost.

**Comment by agrosner** [comment]
in `develop`.
