### ISSUE TITLE
Cant define FK as deferred

### ISSUE THREAD

**Issue by liorzam** [Raizlabs/DBFlow#1171]
DBFlow Version: 4.0.0-beta2
Issue Kind: Feature

I need to change PK of row which has some related rows( FK )so i found this feature which is not available in DBFlow
http://www.sqlite.org/foreignkeys.html#fk_deferred

**Comment by liorzam** [comment]
For those who dealt with the kind of situation which they need to change a primary key with related rows with fk constraint , elegant way is to create trigger after update and make update operation on the dependency table


`   

final NameAlias oldParam = NameAlias.builder("OLD").build();
final NameAlias newParam = NameAlias.builder("NEW").build();

Trigger momentsComments = Trigger.create("TRG_UPDATE_STORIES_CHANGE_RELATED_MOMENTS");
                                    database.execSQL(momentsComments.after().update(Story.class)
                                            .begin(SQLite.update(Moment.class)
                                                    .set(Moment_Table.story.eq(Story_Table.storyId.withTable(newParam)))
                                                    .where(Moment_Table.story.withTable().eq(Story_Table.storyId.withTable(oldParam))))
                                            .getQuery());
`

**Comment by agrosner** [comment]
in `develop`. :)
