### ISSUE TITLE
4.0.0-Beta5 - migrating from 3.0.0-Beta5 causes app to hang and have lot of ANRs

### ISSUE THREAD

**Issue by PradMettu** [Raizlabs/DBFlow#1175]
Hi 

   First of all, thanks for dbflow has been nice and very helpful in developing my app which has lot of db transactions (Reads and Writes). 3.0.0-Beta5 served us well but we wanted to have SQLCipher and upgrade to latest dbflow version 4.0.0-Beta5. After upgrading we started seeing lot of ANRs and db reads are taking much longer than earlier. 

   We changed all of our writes to async writes or wrapped them in a transaction which improved the insert/update perf but reads are really slower. Is there known issue in 4.0.0-Beta5 or do we need to change something from 3.0.0 - Beta5 to reads to perform better?

**Comment by trevjonez** [comment]
have tried using WAL? https://www.sqlite.org/wal.html

```java
((FlowSQLiteOpenHelper) FlowManager.getDatabase(YourDatabase.class).getHelper()).setWriteAheadLoggingEnabled(true);
```

**Comment by PradMettu** [comment]
Thanks Trevor for answer. We are using SQLCipherOpenHelper, how can set the WAL flag with SQLCipher in dbflow?

**Comment by PradMettu** [comment]
The setWriteAheadLogging is in abstract SQLiteOpenHelper in package "**android.database.sqlite**", but when we are using SQLCipherOpenHelper then it is derived from SQLiteOpenHelper which is in package "**net.sqlcipher.database**" which doesn't have the setWriteAheadLogging() method.

**Comment by trevjonez** [comment]
Im not sure, may have to do some fishing around the packages to figure it out.

**Comment by agrosner** [comment]
if its SQLCipher, it doesn't have support for it directly, but see this thread: https://discuss.zetetic.net/t/enabling-write-ahead-logging-and-using-begin-immediate-with-sqlcipher-on-android/2124
so In DBFlow you'd call: `FlowManager.getDatabase(MyDatabase.class).execSQL("PRAGMA journal_mode=WAL;");`
