### ISSUE TITLE
Clear examples for IndexMigration

### ISSUE THREAD

**Issue by CapnSpellcheck** [Raizlabs/DBFlow#1176]
DBFlow Version: 4.0.0-beta3
Issue Kind (Bug, Question, Feature): Question, Documentation

Description: I would like clear instructions on how to enable indexes. With the IndexMigration documentation, it is clear that a migration needs to be done, but it does not explain how to provide the index name, which is apparently needed.

Case 1: Single column index. How to enable this in migration?
```
    @Index @Column(defaultValue = "1L") var modifiedDate: Date? = null
```

Case 2: Index group. I would guess that I use the name defined in the `IndexGroup`. But there's no example in the documentation. Again, I would like to see an `@Index` property/field, then the associated IndexMigration to enable this index group
```
@Table(database = Database::class,
       allFields = true,
       useBooleanGetterSetters = false,
       indexGroups = arrayOf(IndexGroup(number = 0, unique = true, name = "profileID_quizID_uniq")))
open internal class ProspectQuizEntry {
    @Index(indexGroups = intArrayOf(0)) @NotNull lateinit var profileID: String
    @Index(indexGroups = intArrayOf(0)) @NotNull @ForeignKey(stubbedRelationship = true, tableClass = ProspectQuiz::class)
        lateinit var quizID: String
```

**Comment by agrosner** [comment]
use `IndexPropertyMigration` which allows you to supply the generated index.
