### ISSUE TITLE
How to query next or before data?

### ISSUE THREAD

**Issue by qiujuer** [Raizlabs/DBFlow#1177]
Hello, I have a Model:
```
@Table(database = AppDatabase.class)
public class Message extends BaseModel {
    @PrimaryKey
    private String id;
    @Column
    private String content;
}
```
The PrimaryKey type is String, I can‘t query the next or before data. 
Help~~

Thanks!

**Comment by agrosner** [comment]
What do you mean by next or before data? you can do an orderby with Ascending on the id and then use that `List` or `Cursor` to iterate through them

**Comment by agrosner** [comment]
`SQLite.select().from(Message.class).orderBy(Message_Table.id, true).queryList()`
