### ISSUE TITLE
DBFlow get nested JsonArray and parse it

### ISSUE THREAD

**Issue by tux-world** [Raizlabs/DBFlow#1179]
this is simple json format which i want to parse it to save in database, but when i try to create field as other class as Info i get an error

    {
        "result": 1,
        "info":
        {
            "name": "ppppp",
            "family": "ooooooo"
        }
    }

UserInformation class contain Info class

    @Table(database = AppDatabase.class)
    public class UserInformation extends BaseModel {
        @PrimaryKey(autoincrement = true)
        private int id;
    
        @Column
        private String userId;
    
        @ForeignKey(references =
                {
                        @ForeignKeyReference
                                (
                                        columnName = "info",
                                        columnType = Integer.class,
                                        foreignKeyColumnName = "parentId"
                                )
                }
        )
        private Info info;
    
        public UserInformation() {
        }
    
         /*SETTERS and GETTERS*/
    }

and Info class contains :

    @Table(database = AppDatabase.class)
    public class Info extends BaseModel {
        @PrimaryKey(autoincrement = true)
        public int id;
    
        @Column
        public int parentId;
    
        @Column
        public String name;
    
        @Column
        public String family;
    
        public Info() {
        }
    
        /*SETTERS and GETTERS*/
    }

I get this error and i cant resolve that:

    java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 518 path $.info

**Comment by agrosner** [comment]
this is not a DBFlow issue but looks like a JSON issue.

**Comment by tux-world** [comment]
@agrosner unfortunately this is DBFlow issue. because i dont have any problem with other class like with dbflow structure, for example:

UserInformation class contain Info class

```
public class UserInformation {
    private int id;
    private String userId;
    private Info info;

    public UserInformation() {
    }

     /*SETTERS and GETTERS*/
}
```

and Info class contains :

```
public class Info {
    public int id;
    public int parentId;
    public String name;
    public String family;

    public Info() {
    }

    /*SETTERS and GETTERS*/
}
```
i removed dbflow annotations and work fine
