### ISSUE TITLE
Compound queries like *((A or B) and C)*.

### ISSUE THREAD

**Issue by amrsilva** [Raizlabs/DBFlow#118]
Hi!

I want do one Condition query like this *((A or B) and C)*.
For example I want the results of Some model that can have the values A or B, but always need have the value C.

For now, I'm trying does something like this:

ConditionQueryBuilder<Model> or_query = new ConditionQueryBuilder<>(
                Model.class, Condition.column(A).is(true))
                .or(Condition.column(B).is(0));
ConditionQueryBuilder<Model> queryBuilder = or_query
                .and(Condition.column(C).isNotNull());
return new Select().from(Model.class).where(queryBuilder).queryList();

But Query returned is select * from model where A = true OR B = true AND C IS NOT NULL, And query that I need is: select * from model where (A = true OR B = true) AND C IS NOT NULL.

Is that possible??

**Comment by tsuharesu** [comment]
It was already asked on #88

**Comment by agrosner** [comment]
at some point it will come. for now you can pass a string `where(string)` to provide similar (without wrapping).

**Comment by amrsilva** [comment]
ok thank you :)

**Comment by leovanhaaren** [comment]
Is the where(string) gone? Can't find it nor can I find support for compounds.

**Comment by trevjonez** [comment]
@leovanhaaren Take a look at the `ConditionGroup.clause(...)` method

**Comment by leovanhaaren** [comment]
@trevjonez Thanks!
