### ISSUE TITLE
whitch column searched when i use save() method

### ISSUE THREAD

**Issue by tux-world** [Raizlabs/DBFlow#1180]
in this library document i read this note:

> model.save(); // checks if exists, if true update, else insert. 

whitch column searched when i use save() method?

**Comment by trevjonez** [comment]
I would strongly recommend you dig into the code to see how the save method works.

There should be a method on the generated `_Adapter` or `_Table` class(depending on db flow version) that is called save. From there you should see the query that it uses to check if it exists. I believe it does this by doing a select based on the primary key of the table.

**Comment by agrosner** [comment]
all primary keys of object.

**Comment by tux-world** [comment]
and what about new records? this mean is, i must to get last inserted object from database and use save to update records, ok?
