### ISSUE TITLE
generated classes uses keyword "package" twice

### ISSUE THREAD

**Issue by hannesa2** [Raizlabs/DBFlow#1182]
DBFlow Version: 4.0.0-beta5
Issue Kind (Bug, Question, Feature): Bug

I do not use apt or kapt, I use annotationProcessor with Jack

Description: 
DBFlow is unuseabel, because generated class uses keyword **package** twice !

build.gradle
```
    annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"

    compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"

    // sql-cipher database encryption (optional)
    compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:${dbflow_version}"
    compile "net.zetetic:android-database-sqlcipher:${sqlcipher_version}@aar"
```
Table
```
package info.hannes.picam.dbflow;

import com.raizlabs.android.dbflow.annotation.Column;
import com.raizlabs.android.dbflow.annotation.PrimaryKey;
import com.raizlabs.android.dbflow.annotation.Table;

@Table(database = AppDatabase.class)
public class Test {
    @PrimaryKey(autoincrement = true)
    public long id; 
    @Column
    public Long timestamp;
}

```
Result:
<img width="521" alt="image" src="https://cloud.githubusercontent.com/assets/3314607/23400691/1d82c794-fda5-11e6-88cb-82a1584c6981.png">

**Comment by hannesa2** [comment]
I found the same issue #1065

**Comment by funnygerman** [comment]
@hannesa2 I could indeed solve this problem by using retrolambda as suggested in the comment https://github.com/Raizlabs/DBFlow/issues/1065#issuecomment-265789463

**Comment by hannesa2** [comment]
In my point of view Jack is the future and I want to reduce dependencies of other libraries. 
@agrosner I think it is in your interests, to let DBFlow not depend on a other library and support the most recent tool chain supported by Google

**Comment by agrosner** [comment]
closing as dupe to #1065

**Comment by agrosner** [comment]
in `develop`.
