### ISSUE TITLE
Possible to have auto-inherited columns from a base class?

### ISSUE THREAD

**Issue by lukewaggoner** [Raizlabs/DBFlow#1183]
Wondering if you could add (or is there already) a way to have columns declared in a class that automatically become columns in any classes that extend it?

For example:

    @Table(database = AppDatabase.class)
    public class BaseClass extends com.raizlabs.android.dbflow.structure.BaseModel {

        @Column
        private int id;

        @Column
        private Date inserted;

        @Column
        private Date updated;

        public int getId() {
            return id;
        }

        public void setId(int id) {
            this.id = id;
        }

        public Date getInserted() {
            return inserted;
        }

        public void setInserted(Date inserted) {
            this.inserted = inserted;
        }

        public Date getUpdated() {
            return updated;
        }

        public void setUpdated(Date updated) {
            this.updated = updated;
        }
    }

And then if any other tables that extend this class, they would automatically have these columns added to the table.

Is that doable?

**Comment by agrosner** [comment]
it already collects all visible fields of baseclasses.

**Comment by lukewaggoner** [comment]
I'm confused then. What's the point of the @InheritedColumn annotation inside the @Table annotation?

**Comment by agrosner** [comment]
Extending non dbflow classes

**Comment by lukewaggoner** [comment]
Ahhh...That makes sense. Thanks! And thanks for the quick response. Really appreciate it!

**Comment by agrosner** [comment]
No problem dude!
