### ISSUE TITLE
You can not create a table while the program is running

### ISSUE THREAD

**Issue by eric-zhang-gl** [Raizlabs/DBFlow#1188]
DBFlow Version:
Issue Kind (Bug, Question, Feature):

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description:

**Comment by eric-zhang-gl** [comment]
You can not create a table while the program is running

**Comment by agrosner** [comment]
Tables are not dynamic. Tables are pregenerated, thus you cannot create a table when program is running since you had to generate code to use it.

**Comment by eric-zhang-gl** [comment]
ok  thx,It's solved

**Comment by eric-zhang-dev** [comment]
Can dynamically create a table that is created after the program has run according to demand, I now think so, but for DBFlow, I do not know how to use it, so I intend to abandon the use of DBFlow
