### ISSUE TITLE
error not self explanatory when OneToMany and List<? extends SomeEntity>

### ISSUE THREAD

**Issue by manmaor** [Raizlabs/DBFlow#1191]
DBFlow Version: 4.0.0-beta5
Issue Kind (Bug, Question, Feature): bug

Description: 
``` java
@OneToMany(
            methods = {OneToMany.Method.ALL},
            variableName = "entities",
            isVariablePrivate = false)
    public List<? extends SomeEntity> getPayments() {
        if (entities== null || entities.isEmpty()) {
            entities= SQLite.select()
                    .from(SomeEntity.class)
                    .where(SomeEntity_Table.expense_id.eq(super.id))
                    .queryList();
        }
        return entities;
    }
```

When I did the code above I could not build the project, and it always faild with undetailed error:
Error:Execution failed for task ':app:compileDebugJavaWithJavac'. > java.lang.NullPointerException: element == null

And when i change the __List<? extends SomeEntity>__  To __List< SomeEntity>__ every thing was fine.

**Comment by agrosner** [comment]
in `develop`.

**Comment by sigfridod** [comment]
@agrosner  any way if I want to change the query of below oneToMany method runtime ?

public List<? extends SomeEntity> getPayments() {
        if (entities== null || entities.isEmpty()) {
            entities= SQLite.select()
                    .from(SomeEntity.class)
                    .where(SomeEntity_Table.expense_id.eq(super.id))
                    .queryList();
        }
        return entities;
    }
