### ISSUE TITLE
FastStoreModelTransaction.saveBuilder saving wrong values in null relationships

### ISSUE THREAD

**Issue by tmoura10** [Raizlabs/DBFlow#1192]
DBFlow Version: 4.0.0-beta5
Issue Kind: Bug

Description: 

I have this class:

    @Table(name = "order_items", database = FlowDataBase::class)
    class OrderItem : BaseModel {

        @PrimaryKey
        @Column(name = "id")
        var id: Int = 0

        @ForeignKey(saveForeignKeyModel = false)
        var product: Product? = null
    }

When I try to use FastStoreModelTransaction.saveBuilder and some of these `product` objects are null, they are being updated with the last valid product entity.

    FlowManager.getDatabase(FlowDataBase::class.java).executeTransaction(
                FastStoreModelTransaction
                        .saveBuilder(FlowManager.getModelAdapter(OrderItem::class.java))
                        .addAll(list)
                        .build())

For example, a list with these items:

OrderItem(1, 1)
OrderItem(2, 2)
OrderItem(3, null)
OrderItem(4, null)
OrderItem(5, null)

Is saving in the database the values: [1,1], [2,2], [3,2], [4,2], [5,null]

When I changed to `list.forEach { it.save() }` everything worked fine

**Comment by agrosner** [comment]
1. Are you doing anything on different threads with this list?
2. Have you debugged the update statements here to ensure theyre solid.

Plus I recreated your class with a test and everything works as expected:
```kotlin
class OrderItemTest : FlowTestCase() {

    @Test
    fun ensureCanSave() {
        delete<OrderItem>().execute()
        val testModel = TestModel1().apply { name = "Name1"; insert() }
        val testModel2 = TestModel1().apply { name = "Name2"; insert() }
        val list = arrayListOf(
                OrderItem(1, testModel),
                OrderItem(2, testModel2),
                OrderItem(3, null),
                OrderItem(4, null),
                OrderItem(5, null))
        FlowManager.getDatabase(TestDatabase::class.java).executeTransaction(
                FastStoreModelTransaction
                        .saveBuilder(FlowManager.getModelAdapter(OrderItem::class.java))
                        .addAll(list)
                        .build())

        val loaded = (select from OrderItem::class).list
        assertEquals(1, loaded[0].id)
        assertEquals(testModel.name, loaded[0].product?.name)
        assertEquals(2, loaded[1].id)
        assertEquals(testModel2.name, loaded[1].product?.name)
        (2..4).forEach { assertNull(loaded[it].product) }
    }
}
```

class:
```kotlin
@Table(name = "order_items", database = TestDatabase::class)
data class OrderItem(@PrimaryKey
                     @Column(name = "id")
                     var id: Int = 0,

                     @ForeignKey(saveForeignKeyModel = false)
                     var product: TestModel1? = null) : BaseModel()
```
