### ISSUE TITLE
Add getFileName database annotation

### ISSUE THREAD

**Issue by carmas123** [Raizlabs/DBFlow#1193]
DBFlow Version: 4.0.0-beta5
Issue Kind (Bug, Question, Feature): Feature

Description: 
Please can you add a new Database annotation that can invoke a static method to get the database file name. This can be usefull to have a multiple database on same device/app.
With this I can have db-1.db db-2.db...close DBFlow and reopen with another database file with same structure.

**Comment by agrosner** [comment]
Since code is generated ahead of time, it needs to be constant, so we cannot do dynamic dbs unfortunately.
