### ISSUE TITLE
Migrating to DBFlow

### ISSUE THREAD

**Issue by nicolabeghin** [Raizlabs/DBFlow#1194]
DBFlow Version: 4.0.0-beta5
Issue Kind: Bug/Question
Instant run: disabled

Hi everyone, I'm attempting a migration to DBFlow of a previosly SugarDB-based Android application.

I got all the models refactored and extending a 
```
public class DBFlowModel extends BaseModel {

    @PrimaryKey
    @Column
    protected Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}

```

Problem is, I don't get past compilation as a list of
```
  symbol:   class DBFlowModel_Helper
  location: package com.nbeghin.MyApp.utils.db
/Users/ark0n3/AndroidstudioProjects/MyApp/app/build/generated/source/apt/debug/com/nbeghin/MyApp/models/ReportTemplate_Table.java:5: error: cannot find symbol
import com.nbeghin.MyApp.utils.db.DBFlowModel_Helper;
```

pops up, to end with
```
 symbol:   class DBFlowModel_Helper
  location: package com.nbeghin.MyApp.utils.db
warning: File for type 'com.raizlabs.android.dbflow.config.MyAppDatabaseMyApp_Database' created in the last round will not be subject to annotation processing.
warning: File for type 'com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder' created in the last round will not be subject to annotation processing.
55 errors
2 warnings
```

Being that no further indication is given, and no other compilation errors are thrown, I'm ready to give up DBFlow. 

Thanks to anyone who could shade a light on this. DBFlow seems very promising but errors like the above make the entry barrier unpredictable.

**Comment by agrosner** [comment]
1. Can you try making the `id` field private or public and seeing if that fixes issue.
2. can you send what your model classes + generated code looks like if that does not fix issue.
