### ISSUE TITLE
Generating wrong code for migration

### ISSUE THREAD

**Issue by tomislavhoman** [Raizlabs/DBFlow#120]
I am using latest (in this moment) version - 1.6.2. When I add migration class into project it generates code that won't compile. Generated code tries to instantiate migration class with empty constructor, but actually it should take table class as parameter. I tried with AlterTableMigration

**Comment by agrosner** [comment]
you need to subclass `AlterTableMigration` and provide a default constructor that calls the super constructor with the appropriate table.

**Comment by tomislavhoman** [comment]
That's exactly what I did, but generated code tries to call empty constructor for migration that doesn't exist and I get compile error because of that...

**Comment by agrosner** [comment]
can you send me your migration class? thanks.
