### ISSUE TITLE
How to ensure minifyEnabled work with a project including DBFlow?

### ISSUE THREAD

**Issue by kenneth2008** [Raizlabs/DBFlow#1203]
DBFlow Version: 4.0.0-beta5
Issue Kind (Bug, Question, Feature): Question

Description: 
I have the following crash report:
> Exception java.lang.NoSuchFieldError:
> libcore.reflect.AnnotationAccess.decodeValue (AnnotationAccess.java:688)
> libcore.reflect.AnnotationAccess.toAnnotationInstance (AnnotationAccess.java:663)
> libcore.reflect.AnnotationAccess.toAnnotationInstance (AnnotationAccess.java:641)
> libcore.reflect.AnnotationAccess.getDeclaredAnnotation (AnnotationAccess.java:171)
> libcore.reflect.AnnotationAccess.getAnnotation (AnnotationAccess.java:72)
> java.lang.Class.getAnnotation (Class.java:359)
> com.b.a.c.e.y$a.<clinit> ()
> com.b.a.c.e.y$a.a ()
> com.b.a.c.u.<clinit> ()

I have included those line in my build.grade
annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    apt "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    // use kapt for kotlin apt
    compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"

I saw on other issues which is related to minifyEnabled, it say: it is a database cipher problem.
I wonder if my case is the same. 
The error message above is related to DBFlow?
How can I prevent the above error message?
How to ensure minifyEnabled work with a project including DBFlow?

**Comment by agrosner** [comment]
https://github.com/Raizlabs/DBFlow/blob/master/usage2/Intro.md#proguard

youre using SQLCipher, youll need to reference their docs for proguard.

**Comment by agrosner** [comment]
also you dont want to use both `apt` and `annotationProcessor`, the latter is the one you should use.
