### ISSUE TITLE
Decrypt database on migration

### ISSUE THREAD

**Issue by candalo** [Raizlabs/DBFlow#1205]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Question

Description: 
I encrypted my database following the documentation, and I would like to know if it is possible decrypt this database on migration. From now on I want to use the database without cryptography.

Thanks!

**Comment by agrosner** [comment]
From SQLCipher you mean?

**Comment by candalo** [comment]
Yes

**Comment by agrosner** [comment]
I am not sure if you can actually do so. A simple google search has gotten me nowhere. You might need to do something like open your existing DB, read all tables out of that db into the new, unencrypted db.
