### ISSUE TITLE
Execution failed for task ':app:compileDebugJavaWithJavac'. > java.lang.NullPointerException: element == null 

### ISSUE THREAD

**Issue by p4535992** [Raizlabs/DBFlow#1207]
Sorry to reopen this issue another time, i found answer to this similar issue on this other threads of the project:

- [':app:compileDebugJavaWithJavac'. > java.lang.NullPointerException](https://github.com/Raizlabs/DBFlow/issues/526)
- [[SOLVED] Execution failed for task ':app:compileDebugJavaWithJavac' java.lang.IllegalArgumentException: expected type but was null [UpperCamelCase not documented]](https://github.com/Raizlabs/DBFlow/issues/972)

but it's seems not the case, i put a link to a simple project android where i have success to replicate the error [my sample project](https://github.com/p4535992/TestDbFlowBug),  try to find out by myself but i have failed.

NOTE: I use the develop-SNAPSHOT version

Maybe some conflict during the developing of the version 4 with some library android support?
Any help is more than appreciate .
Greetings

**Comment by agrosner** [comment]
can you try it on latest `develop`? I believe its fixed.

**Comment by p4535992** [comment]
ty very much, now it's work.
Greetings.
