### ISSUE TITLE
ForeignKey to Model with UUID Primary Key causes build failure

### ISSUE THREAD

**Issue by buntagonalprism** [Raizlabs/DBFlow#1208]
DBFlow Version: 4.0.0-beta5
Issue Kind: Bug

Description: 
It seems having a foreign key relationship to another model which has a UUID data type as its primary key causes errors in the built java file for the model. 

Encountered in a situation with 'item' and 'category' model classes, where each item can belong to a single category. Both item and category models use UUIDs as their primary key. 

**Item.java**
```
import com.raizlabs.android.dbflow.annotation.Column;
import com.raizlabs.android.dbflow.annotation.ForeignKey;
import com.raizlabs.android.dbflow.annotation.PrimaryKey;
import com.raizlabs.android.dbflow.annotation.Table;
import com.raizlabs.android.dbflow.structure.BaseModel;

import java.util.UUID;

@Table(database =  QSDatabase.class)
public class Item extends BaseModel {

    @PrimaryKey
    @Column
    public UUID _id;

    @Column
    public String name;

    @ForeignKey
    public Category category;
}
```
**Category.java**
```
import com.raizlabs.android.dbflow.annotation.Column;
import com.raizlabs.android.dbflow.annotation.PrimaryKey;
import com.raizlabs.android.dbflow.annotation.Table;
import com.raizlabs.android.dbflow.structure.BaseModel;

import java.util.UUID;

@Table(database =  QSDatabase.class)
public class Category extends BaseModel {

    @PrimaryKey
    @Column
    public UUID _id;

    @Column
    public String name;

    @Column
    public int count;

    public Category() {
        _id = UUID.randomUUID();
        name = "";
    }
}
```
**Build Error**
On attempting to build the android studio project, the following gradle build errors are produced:

```
Error:(95, 14) error: variable ref_id is already defined in method bindToInsertValues(ContentValues,Item)
Error:(116, 14) error: variable ref_id is already defined in method bindToInsertStatement(DatabaseStatement,Item,int)
```

The errors refer to the generated code under **Item_Table.java** where the String "ref_id" is defined multiple times, causing an error. 

```
  @Override
  public final void bindToInsertValues(ContentValues values, Item2 model) {
    String ref_id = model._id != null ? global_typeConverterUUIDConverter.getDBValue(model._id) : null;
    values.put("`_id`", ref_id != null ? ref_id : null);
    values.put("`name`", model.name != null ? model.name : null);
    if (model.category != null) {
      String ref_id = model.category._id != null ? global_typeConverterUUIDConverter.getDBValue(model.category._id) : null;
      values.put("`category__id`", ref_id);
    } else {
      values.putNull("category__id");
    }
  }

  @Override
  public final void bindToInsertStatement(DatabaseStatement statement, Item2 model, int start) {
    String ref_id = model._id != null ? global_typeConverterUUIDConverter.getDBValue(model._id) : null;
    if (ref_id != null)  {
      statement.bindString(1 + start, ref_id);
    } else {
      statement.bindNull(1 + start);
    }
    if (model.name != null)  {
      statement.bindString(2 + start, model.name);
    } else {
      statement.bindNull(2 + start);
    }
    if (model.category != null) {
      String ref_id = model.category._id != null ? global_typeConverterUUIDConverter.getDBValue(model.category._id) : null;
      statement.bindString(3 + start, ref_id);
    } else {
      statement.bindNull(3 + start);
    }
  }
```
Changing the PrimaryKey of Category to be a non-UUID field allows the project to build without any errors.

**Comment by agrosner** [comment]
this seems to be an issue with naming of fields. I will have to adjust inner `@ForeignKey` local variables to have a unique prefix. This will work if you change the name of your `UUID` to something other than `_id` such as `uid`.

**Comment by buntagonalprism** [comment]
Thanks, changing the field name of the UUID PrimaryKey field in Category.java to anything different to the name of the primary key field in Item.java allows the project to build successfully. 

Sorry I'm new to github and issue tracking; should this be marked as closed now as there is a workaround or should this stay open until the fix you described is implemented? Thanks for your help!

**Comment by FMinus** [comment]
having the same issue but in my case i want to have the primary key in a base class with other additional fields
if `ref_id` that's in the category were to be generated as something like `category_ref_id` this would dodge part of the issue

**Comment by agrosner** [comment]
in `develop`. we append a unique `SomeTable_Table` postfix to foreign key loads and have more concise code, so this should never happen now.
