### ISSUE TITLE
Restore db from cloud

### ISSUE THREAD

**Issue by demirhand** [Raizlabs/DBFlow#1210]
DBFlow Version: 4.0.0-beta2
Question

Hi,
I am trying to restore db with downloaded db file from cloud. I am getting db file using 
`activity.getDatabasePath(MyDatabase.NAME+".db")`
When I do that I come up with empty db. I dont understand that why. What is the proper way to do that.
Thatnks.

**Comment by agrosner** [comment]
if you are instantiating or using DBFlow somewhere before that occurs, check to see if the db is already created. On first execution of anything db-related, we open a fresh db if theres no existing db.

**Comment by demirhand** [comment]
Db already created and I am trying to change current db downloaded from cloud to restore back state.  
I am replacing it with that code.

```
InputStream mInput = new FileInputStream(backupDB);

OutputStream mOutput = new FileOutputStream(db);
mBuffer = new byte[1024];
mLength;
mLength = mInput.read(mBuffer))>0)
{
        write(mBuffer, 0, mLength);
}
mOutput.flush();
mOutput.close();
mInput.close();
```

Is it correct way?
Thanks.

**Comment by agrosner** [comment]
not sure if its relevant here. please ask on Stackoverflow.
