### ISSUE TITLE
Prevent foreign key column names from appending _id

### ISSUE THREAD

**Issue by kirtan403** [Raizlabs/DBFlow#1211]
DBFlow Version: 4.0.0-beta5
Issue Kind (Bug, Question, Feature): Question

Description: 
For foreign key references How can I prevent foreign id names from appending `_id` at the end?

For example, I have 2 classes like this: 
**organization class:** 
```
@Table(database = MyDatabase.class)
public class organization extends BaseModel {
    @Column
    @PrimaryKey
    int id;

    @Column
    String name;

   // getters and setters

}
```

**college class:**
```
@Table(database = MyDatabase.class)
public class college extends BaseModel {
    @Column
    @PrimaryKey
    int id;

    @Column
    String name;

    @Column
    @ForeignKey(tableClass = organization.class)
    int foo;

   // getters and setters

}
```

But, when I compile, the name `foo` becomes `foo_id` in the database as well as college_Table class. 

Setting @Column(name="foo") also doesn't work. It failes at the compile time only. And gives the following error:

```
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.util.MissingFormatArgumentException: Format specifier '%1s'
```

Is there any way I can prevent this behavior and keep the same name `foo`?

**Comment by agrosner** [comment]
Hmm looks like its not in the docs. attach `@ForeignKey(references = {@ForeignKeyReference(columnName = "foo", foreignKeyColumnName = "id')})` and for each `@PrimaryKey` you must attach a `@ForeignKeyReference`.

**Comment by kirtan403** [comment]
Thanks! It compiled successfully. 
But I think I am missing this point:

> for each @PrimaryKey you must attach a @ForeignKeyReference.

Can you just provide an example?

**Comment by agrosner** [comment]
```java
    @Column
    @ForeignKey(tableClass = organization.class)
    int foo;
```
to:
```java
    @Column
    @ForeignKey(references = {@ForeignKeyReference(columnName = "foo", foreignKeyColumnName = "id')})
    int foo;
```

**Comment by agrosner** [comment]
if you have multiple primary keys:
```
@ForeignKey(references = {
    @ForeignKeyReference(columnName = "foo", foreignKeyColumnName = "id'),
    @ForeignKeyReferece(columnName="otherfoo", foreignKeyColumnName="id2"})
organization org;
```
where:
```
@Table(database = MyDatabase.class)
public class organization extends BaseModel {
    @PrimaryKey
    int id;

    @PrimaryKey
    int id2;

    @Column
    String name;
}
```

**Comment by kirtan403** [comment]
Yes. Got your point. Thank you 😄 

Please do add this to documentation for others.

**Comment by agrosner** [comment]
Ill keep this open as a reminder :)

**Comment by agrosner** [comment]
in `develop`.
