### ISSUE TITLE
Change foreignKeyConstraintsEnforced configuration at runtime

### ISSUE THREAD

**Issue by kirtan403** [Raizlabs/DBFlow#1212]
DBFlow Version: 4.0.0-beta5
Issue Kind (Bug, Question, Feature): Question

Description: 

My database class is something like this:

```
@Database(name = MyDatabase.NAME, version = MyDatabase.VERSION, foreignKeyConstraintsEnforced = true)
public class MyDatabase {
    public static final String NAME = "MyDatabase";

    public static final int VERSION = 1;
}
```

But, at runtime I want to remove foreign Key constraints for some time and then re-enable it. Is there any way to change the defined behavior at runtime?

**Comment by agrosner** [comment]
` FlowManager.getDatabase(MyDatabase.class).execSQL("PRAGMA foreign_keys=ON;");`
You can do `ON` or `OFF`. its simply a flag. But if you do enforced=true, whenever db is opened or created, it will turn it on. So if you leave off flag and manually turn it on and off youll be good.
