### ISSUE TITLE
Kotlin extensions or query is actually and

### ISSUE THREAD

**Issue by erwinknoop** [Raizlabs/DBFlow#1213]
DBFlow Version: 4.0.0-beta5
Issue Kind (Bug, Question, Feature): Bug

Description: 
I was trying to write a where query containing an OR in Kotlin using DBFlow and this wouldn't work as expected. So I tried logging the query and there I saw the problem, instead of an OR there was an AND in the where query.

The code I was using is:
`(select
                from Model::class
                where (dateColumn.isNull)
                or (dateColumn lessThan Date()))`

The resulting query was:
``SELECT * FROM `Model` WHERE `dateColumn` IS NULL  AND `dateColumn`<1490285193654 ``

After some inspection of the source code I found out that this was indeed a bug because I found the following code in https://github.com/Raizlabs/DBFlow/blob/master/dbflow-kotlinextensions/src/main/java/com/raizlabs/android/dbflow/kotlinextensions/QueryExtensions.kt

`infix fun <T : Any> Where<T>.or(sqlCondition: SQLCondition): Where<T> = and(sqlCondition)`

So it seems that the Kotlin extension for an or query is actually calling the code for an and query. When creating the query without the Kotlin extension it works as expected.

**Comment by agrosner** [comment]
this is a bug thatll be fixed in the next release. Sorry for the confusion. :)

**Comment by agrosner** [comment]
in 4.0.0-beta6
