### ISSUE TITLE
Releasing DBFlow4

### ISSUE THREAD

**Issue by rogerhu** [Raizlabs/DBFlow#1214]
DBFlow Version:4.0.0-beta
Issue Kind (Bug, Question, Feature):

Any reason why DBFlow 4.0 is still beta?  Can it be pushed to jCenter?

Description:

**Comment by xxxifan** [comment]
I believe this can be an answer [is 4.0 beta stable enough for production? I didn't upgrade for that reason.](https://github.com/Raizlabs/DBFlow/issues/1088#issuecomment-264708195)
