### ISSUE TITLE
Join query doesnt return right result

### ISSUE THREAD

**Issue by sigfridod** [Raizlabs/DBFlow#1215]
DBFlow Version:
Issue Kind (Bug, Question, Feature):

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

I have 2 tables like below
Account
Group

Account and Group table contains one to many relationship, I want to fetch all accounts & associated groups where group's one column should have value like if column is enable = true/false

than when I fire join or sub query it should return all accounts with groups where groups with enable true should return

but using DBFlow it returns right account but it returns all groups not a single group which was enabled

@agrosner  any solution or help will be appreciated as as of now I can't change the database ?

**Comment by agrosner** [comment]
sorry for late reply, but Im going to need to see code to be able to help you. if it's still valid, please reopen.
