### ISSUE TITLE
Does Char column work?

### ISSUE THREAD

**Issue by CapnSpellcheck** [Raizlabs/DBFlow#1217]
DBFlow Version: 4.0.0

I try to create a character column using kotlin's Char: (table has allFields)
`    var lastNameInitial: Char? = null`

Then the generated table has the code
`    values.put("`lastNameInitial`", reflastNameInitial != null ? reflastNameInitial : null);`

but there is no such put method signature in ContentValue.

But the docs say that Java char and Character are supported. Is there a type converter necessary?

**Comment by CapnSpellcheck** [comment]
I have made a character based TypeConverter for now.

**Comment by agrosner** [comment]
ah nullable chars will not work since they arent actually `char` but `Char` in java. This is a bug on my side which I will work on fixing. thank you.

**Comment by agrosner** [comment]
in `develop`.

**Comment by CapnSpellcheck** [comment]
Ok cool!
