### ISSUE TITLE
Question about annotation proccessing implementation

### ISSUE THREAD

**Issue by geralt-encore** [Raizlabs/DBFlow#1220]
Hey, sorry if it is not the right place to ask, but I have a question regarding your implementation of annotation processing. I've noticed that it is written in Kotlin except `DBFlowProcessor` itself. Is there any reason for that? Did you have any issues with it if it is written in Kotlin? Thanks in advance!

**Comment by agrosner** [comment]
If its in Kotlin, at least when I first converted from java to Kotlin, the annotation processor couldn't be found, so I left it in Java.
