### ISSUE TITLE
Add execSQL(sql, bindArgs) in DatabaseWrapper

### ISSUE THREAD

**Issue by xinghui322** [Raizlabs/DBFlow#1223]
DBFlow Version:4.0.0-beta5
Issue Kind :Feature

Could you add method `void execSQL(String sql, Object[] bindArgs)` in DatabaseWrapper?

**Comment by agrosner** [comment]
Just call `((AndroidDatabase)FlowManager.getWritableDatabase().getDatabase()).execSql(...)` as necessary.
