### ISSUE TITLE
Migration On Enum

### ISSUE THREAD

**Issue by Debarshi-Banerjee** [Raizlabs/DBFlow#1224]
DBFlow Version: 3.1.1
Issue Kind: Question

Description: 
Hello Good People of DBFlow I am A Big fan of your work. Love and recommend It basically.

So Here is a Question 
Can any one explain How to do Migration On enum will work i want to add onther type actually
`@Table(database = ClinicDatabase.class)
public class Ticket extends BaseModel implements Parcelable {

    @PrimaryKey String id;
    @Column TicketStatus status;
    
    public enum TicketStatus {
        visited,
        visiting,
        waiting,
        pending_checkin,
        no_show,
        cancelled
    }
}
`
so I want to add missing to TicketStatus 
`
   public enum TicketStatus {
        visited,
        visiting,
        waiting,
        pending_checkin,
        no_show,
        cancelled,
missing
    }
`

**Comment by agrosner** [comment]
Enums just convert to `SQLiteType.TEXT`. So you can add as necessary. If you remove one, itll convert to `null`.
