### ISSUE TITLE
Warning:File for type ... created in the last round will not be subject to annotation processing.

### ISSUE THREAD

**Issue by MahdiPishguy** [Raizlabs/DBFlow#1225]
why i get this warning on Logcat:

`Warning:File for type 'com.raizlabs.android.dbflow.config.AppDatabaseMyDatabase_Database' created in the last round will not be subject to annotation processing.`

for this file:

```
@Database(name = AppDatabase.NAME, version = AppDatabase.VERSION)
public class AppDatabase {

    public static final String NAME = "MyDB";
    public static final int VERSION = 1;
}
```

**Comment by trevjonez** [comment]
A few of the files generated by dbflow are not output until the final round of processing. This allows other APT tools generate table classes as input for dbflow to process in subsequent rounds.

The files deferred to last round of processing generally need to list all tables in them. This includes things like the database holder, content provider, as well as the file you are pointing out.

It is a warning not an error and can be safely ignored.

**Comment by agrosner** [comment]
Yes the database holder needs to get generated in the last round to gather everything. because we cannot recreate source files once theyve been generated.
