### ISSUE TITLE
Add @Generated annotation to generated classes

### ISSUE THREAD

**Issue by cmoreno** [Raizlabs/DBFlow#1227]
DBFlow Version: 3.1.1
Bug
Description: The generated classes by DBFlow should be annotated with `@Generated`. I am using Google's Error Prone gradle plugin and every class generated by DBFlow produces warnings, mostly missing `@Override` annotations. If the classes are generated and have the `@Generated` annotation, I can add a compiler flag to bypass them. 
Let me know if you'd like me to be more specific about the warnings.

**Comment by trevjonez** [comment]
It would probably be best to add the missing annotations. can you provide a list of the warnings?

**Comment by agrosner** [comment]
Yes there are missing `@Override`, in 4.0.0 when it goes live, it should have all annotation overrides.
