### ISSUE TITLE
Migration DBFlow 3.0.0-beta 5 to 3.1.1

### ISSUE THREAD

**Issue by AugustoAleGon** [Raizlabs/DBFlow#1229]
DBFlow Version:
Question:

Hello I am doing a migration process with the DBFlow 3.0.0-beta5 to 3.1.1

TransactionManager has been replaced with a new per-database BaseTransactionManager. Each DB has its own DBTransactionQueue and you can replace the default with your own system. Also, no longer is this priority-based, but rather order-based. See more here?

I was reading the previous text and I don't know exactly how the new BaseTransactionManager works in comparison with TransactionManager. The methods are totally different. Do you have a snippet of how to replace the method? The documentation is incompleted.

In advanced thanks you very much for helping me.

**Comment by agrosner** [comment]
I would suggest reading the [docs](https://github.com/Raizlabs/DBFlow/blob/74bb93cb19c3af3203be6e350276e179730887a9/usage2/StoringData.md) on how async transactions now work. If you need priority based, read [here](https://github.com/Raizlabs/DBFlow/blob/74bb93cb19c3af3203be6e350276e179730887a9/usage2/StoringData.md#priority-queue). The methods are totally different, yes. They are more streamlined and straightforward.

**Comment by agrosner** [comment]
What kinds of things were you doing before with transactions, did you use any part of the transactions that no longer exist? can you paste some code of what you need to convert and I can try to help.

**Comment by AugustoAleGon** [comment]
I was doing a migration. I finished completely and successfully. Thanks for your help @agrosner

**Comment by agrosner** [comment]
np @AugustoAleGon ! good to hear.

**Comment by AugustoAleGon** [comment]
Yes. At first I saw it hard to do it, but when you read the documentation you got easy and straight forward.
