### ISSUE TITLE
Polymorphism and Inheritance Possible? 

### ISSUE THREAD

**Issue by boxlady** [Raizlabs/DBFlow#123]
I was wonder how or if it’s possible to polymorphism with this.
For example, I have base shape class, and rectangle and circle inherit from this class. When I put it in the database it goes in for example as rectangle but there is nothing in the shape table. I would like to be able to say, look for all the shapes. Is this possible? Special way to go about it?

**Comment by agrosner** [comment]
inheritance is fully supported (https://github.com/Raizlabs/DBFlow/blob/master/usage/DBStructure.md)

**Comment by agrosner** [comment]
Not sure what you're asking exactly.

**Comment by boxlady** [comment]
Im asking this...

For example:

Class Shape
Class Rectangle extends Shape
Class Circle extends Shape

If I create 2 Rectangle's, and then 2 Circles
I expect 4 entries in Shapes table.
I expect ids in Shapes to be 1, 2, 3, 4
I expect the ids in Rectangle to be 1, 2
I expect the ids in Circle to be 4, 5

I;m getting something like this
0 in Pets
3 in Dogs -> ids: 1, 2
2 in Cats -> ids: 1, 2

But Shape table has No data in it what so ever. The Rectangle  does inherit the some variables from  shape but I want to be able to later look for all shapes with out having to build a long complicated query,

**Comment by agrosner** [comment]
All that inheritance does is include all super classes' ```@Column``` to your current table. It does not insert rows into those super classes, and I don't know why you would want to.

**Comment by boxlady** [comment]
It would be useful, at-least for me. Otherwise I have to do complicated query in order to get all shapes for that specific page but not all the other ones (I'm using polymorphism with a genetic shape class and an array that holds them). Hell maybe they can be linked though a key and I can use that to get them all back together. I Know other people were looking for the same thing on ActiveAndroid. Its where I found a link to this library.

**Comment by agrosner** [comment]
yeah you can use a ```Column.FOREIGN_KEY``` which references the `Shape` table and your local column references are the primary keys of the `Shape` table so they're connected. 

so something like this:

```java

public class Rectangle extends Shape {

  @Column(columnType = Column.FOREIGN_KEY, 
      references = {references go here})
  ForeignKeyContainer<Shape> shape;

}

```

so now everytime you save ```Rectangle```, ```Shape``` reference is saved too. You will need to manage how the relationship is connected through the keys but it won't be that difficult based on what I understand. Also you can override any method for ```Model``` to ensure when a `Rectangle` is deleted, the corresponding `Shape` is too.

**Comment by boxlady** [comment]
I'll try it out. Thank you :)
