### ISSUE TITLE
Is it possible to create a single-row table?

### ISSUE THREAD

**Issue by jorgecoca** [Raizlabs/DBFlow#1230]
DBFlow Version:
Issue Kind (Bug, Question, Feature): Question

Description: 
Hi, and thanks in advance. I'm using v3.1.1, and I'd like to know if it is possible to create a table that only has one row every single time. I just need it to store the last occurrence of a certain event, so the next time that same event happens, I can compare them to check that they are not the same.

Thank you!

**Comment by trevjonez** [comment]
This can't be enforced however you could easily create a table that has a string primary key column and a string column and use it like a key value store. Then by having a few string constants in your code you would be able access them consistently.

Unless you need to do some sort of query where this is being joined against as some type of filter this sounds like a better fit for android's shared preferences api.

**Comment by jorgecoca** [comment]
Thanks a lot! Your response has been very helpful!
