### ISSUE TITLE
ltrim and rtrim functions

### ISSUE THREAD

**Issue by rashmi-tondare** [Raizlabs/DBFlow#1231]
DBFlow Version: 4.0.0-beta5
Issue Kind (Question):

Description: 
Are there any specific methods to perform the SQLite functions or ltrim or rtrim?
I'm trying to achieve something like this - 
update table_name set column_name = lTrim(rTrim(column_name))

**Comment by agrosner** [comment]
Create custom `Method` to do what you want. 
```java
new Method("ltrim", new Method("rtrim", SomeTable_Table.column))
```
