### ISSUE TITLE
when setting a ForeignKey with a custom column will go error

### ISSUE THREAD

**Issue by woailuo1218** [Raizlabs/DBFlow#1232]
DBFlow Version:
Issue Kind (Bug, Question, Feature):

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
class B {
@PrimaryKey(autoincrement = true)
    @Column(name = "c_id")
    long id;
}
class A {
@PrimaryKey(autoincrement = true)
    @Column(name = "c_id")
    long id;
@ForeignKey(stubbedRelationship = true)
    B b;
}
when build will go wrong

**Comment by agrosner** [comment]
what version of DBFlow are you using.

**Comment by DreierF** [comment]
I have the same problem using 4.0.0-beta7.

In the A_Table class everytime the `model.b.id` should be accessed `model.b.c_id` is generated.
For example:
```
public final class A_Table extends ModelAdapter<A> {
  ...
 @Override
  public final void bindToInsertValues(ContentValues values, A model) {
    ...
    if (model.b != null) {
      values.put("`b_c_id`", model.b.c_id);
    } else {
      values.putNull("b_c_id");
    }
    ...
  }
}
```

**Comment by agrosner** [comment]
fixed in `develop`.
