### ISSUE TITLE
update only specific columns

### ISSUE THREAD

**Issue by AndreiStanciu89** [Raizlabs/DBFlow#1236]
DBFlow Version: 4.0.0-beta6
Issue Kind (Question):

Description: 
Hi, is there any way to update just specific columns, and ignore the rest?
To be more precise, I have a list of objects I fetch from the backend, and add some fields that I only use locally. When syncing with the backend, those fields will have some default values, and I therefore want to ignore then, when updating the table.
Right now, I do a local query, manually update the models with that I get from the backend, and then save them. I'd like to avoid doing that local query.

**Comment by agrosner** [comment]
No, there really isn't an easy way to update only specific columns. You could theoretically do a `SQLite.set().columnValues(SomeTable.column.eq(someValue), SomeTable.anotherColumn.eq(someValue))` so if you don't have models in memory but in the DB, you can do a regular `Set` on the data with the values you like.

**Comment by AndreiStanciu89** [comment]
Got it, thank you
