### ISSUE TITLE
inMemory support

### ISSUE THREAD

**Issue by sigfridod** [Raizlabs/DBFlow#1237]
DBFlow Version:
Issue Kind (Bug, Question, Feature):

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

Will it support if I use database with InMemory option and than keep backup and restore this database in and from a directory ?

**Comment by agrosner** [comment]
a backup will get stored, but it does not restore DB in memory. It will simply attempt to overwrite (in this case nonexistent) DB file.

**Comment by sigfridod** [comment]
@agrosner  what if I will provide a back up and restore implementation like backup on disc from current inmemory database and than restore back when I start application from disc to inmemory database

A common back up and restore feature but here my database will be in "InMemory"

will it work ?

**Comment by agrosner** [comment]
Sorry for late response. I am not so sure. Since it is in memory, it doesn't have a file associated it with it, so copying I am not sure would work.
