### ISSUE TITLE
nested OneToMany models not saved if not extending from BaseModel

### ISSUE THREAD

**Issue by AndreiStanciu89** [Raizlabs/DBFlow#1238]
DBFlow Version: 4.0.0-beta6
Issue Kind (Bug):

Description:
Hi, I have a nested OneToMany data structure, let's say: ClassA contains a list of ClassB which contains a list of ClassC. When calling FlowManager.getModelAdapter(ClassA.class).save(classAObj), the main model is saved correctly, its list of ClassB objects get saved correctly, but it stops there. None of the nested ClassC objects get saved.
Everything works as expected if the models extend from BaseModel though.

**Comment by agrosner** [comment]
thats because we use efficient code gen on `@OneToMany` that don't extend base model. Im going to switch it back to normal and then provide an option for `efficientOperations` that you can turn on that will do what you don't want it to do, but be much faster.

**Comment by agrosner** [comment]
ok so now we have a flag called `efficientMethods` on `OneToMany` which should give you what you need. set it to `false` to generate code that uses the `ModelAdapter` method (or `Model` methods if implements) that implement the nested many to many relationship.
