### ISSUE TITLE
Failed to resolve rx2 in 4.0.0-beta6

### ISSUE THREAD

**Issue by mnawrott** [Raizlabs/DBFlow#1239]
DBFlow Version: 4.0.0-beta6
Issue Kind (Bug, Question, Feature): Bug

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

Hi,
I wanted to add DBFlow to my app, but everytime i compile project i got

`Failed to resolve: com.github.Raizlabs.DBFlow:dbflow-rx2:4.0.0-beta6`
and
`Failed to resolve: com.github.Raizlabs.DBFlow:dbflow-rx2-kotlinextensions:4.0.0-beta6`

I don't have problems with dbflow, dbflow-core, dbflow-kotlinextensions, but rx2 is just not working for me. I added jitpack.io to allprojects repositories.

**Comment by flavioschneider** [comment]
+1

**Comment by ultraon** [comment]
+1

**Comment by trevjonez** [comment]
If you run into problems you can go view the build logs on jitpack to figure out what is going on as well. 

https://jitpack.io/com/github/raizlabs/dbflow/4.0.0-beta6/build.log

ultraon is correct the rx modules have not been configured for maven publishing yet.

**Comment by ultraon** [comment]
I've created temporary solution for all rx/rx2 extensions (included kotlin), use the following:
```
compile('com.github.ultraon.DBFlow:dbflow-rx2:3ecd1171aa') {
        exclude group: "com.github.ultraon.DBFlow"
    }
```

Also i've added PR with fixes above: https://github.com/Raizlabs/DBFlow/pull/1240

**Comment by agrosner** [comment]
sorry!!! its fixed. no need but thank cyou @ultraon

**Comment by agrosner** [comment]
beta7
