### ISSUE TITLE
FOREIGN_KEY also as PRIMARY_KEY

### ISSUE THREAD

**Issue by jan-pintr** [Raizlabs/DBFlow#124]
Hello, I would need to specify FOREIGN_KEY also as PRIMARY_KEY. Something like 

```java
@Column(columnType = ColumnType.FOREIGN_PRIMARY_KEY)
```

There is example use case which would ensure items cannot be repeated in same group, but item can exist in more groups.

There is example use case. (http://sqlfiddle.com/#!7/eb95d/1)

```
CREATE TABLE group (
  id integer primary key,
  name varchar(30)
);

CREATE TABLE item (
  name varchar(30),
  group_id integer references group(id),
  
  primary key(name, group_id)
);
```
As I know this is now not possible. Is it possible to add this functionality?

**Comment by agrosner** [comment]
I see what you mean. I don't see this making it in, because in general you would want to avoid using a primary key that is a foreign key.

**Comment by rjam** [comment]
@agrosner I don't think this is really something that should be avoided for all situations, I mean, isn't this a pretty standard (and correct) thing to do when creating a [junction table](http://en.wikipedia.org/wiki/Junction_table) for example? The foreign keys are usually the only columns of such tables, and together they make the primary key of the table. Currently, I need to have an auto incrementing - pointless - id on my junction tables, and I'm also missing the uniqueness constraint of having my foreign keys also set as primary keys.
