### ISSUE TITLE
[question] combined migration files with migration classes

### ISSUE THREAD

**Issue by santa010** [Raizlabs/DBFlow#1241]
DBFlow Version: 3.1.1

Issue Kind Question

Description: 
I'd like use both Migration Files (.sql) and Migration Classes. Is this possible, let's say we have
* 2.sql
* Migration3.java
* 4.sql 

Will the migrations execute in the correct order?

**Comment by trevjonez** [comment]
if you reference the code here https://github.com/Raizlabs/DBFlow/blob/master/dbflow/src/main/java/com/raizlabs/android/dbflow/structure/database/BaseDatabaseHelper.java#L106

you can see that it will run files first then classes at each level. 

so you had both a 2.sql and M2.java with a 3.sql and M3.java followed up by a  4.sql it would run 2 .sql -> M2 -> 3.sql -> M3 -> 4.sql

**Comment by santa010** [comment]
It works, thank you for your help.
