### ISSUE TITLE
Possible to inject a call higher in the queue than a long-running insert?

### ISSUE THREAD

**Issue by lukewaggoner** [Raizlabs/DBFlow#1246]
DBFlow Version: 4.0.0-beta5
Issue Kind (Bug, Question, Feature): Question

Description: 
I looked through the docs, and I couldn't find anything regarding priority of calls. I'm running a `ProcessModelTransaction` with over 27K items, and during the insertion process, I need to access a different table in the same database. Right now it's waiting until those 27K rows are added before it allows my other call to go through. I'm wondering if there is a way to "cut in line" and make the separate call have a higher priority than the insertion process so that I don't have to wait. Is that possible?

**Comment by agrosner** [comment]
Its kind of buried. but [here](usage2/StoringData.md#priority-queue
