### ISSUE TITLE
How to write bitmap to uri?

### ISSUE THREAD

**Issue by wangsuicheng** [Raizlabs/DBFlow#1247]
I use dbflow to generate content provider, and I want to write the bitmap to uri ,how to do ?

I look up the android ContentProvider source code, found the method that:
`openFileHelper(@NonNull Uri uri,@NonNull String mode) throws FileNotFoundException`
It's description:
```
Convenience for subclasses that wish to implement {@link #openFile}
     * by looking up a column named "_data" at the given URI.
```
yes, it support: context.getContentResolver().openOutputStream(resultUri), and then I can write bitmap or read bitmap from ContentProvider, but but the ContentProvider generated by
dbflow does't support the openStream...

**Comment by wangsuicheng** [comment]
In order to write file to uri, we must re-load the method like that:
`@Override
    public ParcelFileDescriptor openFile(Uri uri, String mode)
            throws FileNotFoundException
    {
        int matcher_result = sUriMatcher.match(uri);
        if (matcher_result == MatcherResult.THUMBNAIL_ID) {
            ParcelFileDescriptor d = this.openFileHelper(uri, mode);
            return d;
        }
        else {
            assert(false);
            return null;
        }
    }`

**Comment by agrosner** [comment]
not supported.
