### ISSUE TITLE
Integrating RX extension

### ISSUE THREAD

**Issue by yFotouh** [Raizlabs/DBFlow#1248]
DBFlow Version: 3.1.1
Issue Kind ( Question,):
Description: 
I'm trying to integrate the Rx extension ,however , i get this when syncing gradle :
Error:Could not find com.raizlabs.android:dbflow-rx:3.1.1.
Required by:
    project :app
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by agrosner** [comment]
its only on versions 4.0.0-beta7 and higher..

**Comment by yFotouh** [comment]
Thanks for the note.
Please state this in the documentation here.
https://github.com/Raizlabs/DBFlow/blob/master/usage2/RXSupport.md
