### ISSUE TITLE
Inserted data is ordered by primarykey column?

### ISSUE THREAD

**Issue by szitguy** [Raizlabs/DBFlow#1250]
DBFlow Version: 4.0.0-beta7
Issue Kind (Bug, Question, Feature): Question

Description: 
i have a Animal Class, id(primarykey column), name(common column) 
then i get animal data list from net, like this:
id name
3  dog
2  cat
1  fish

then i save them to db for cache.
but next time i query data from db, the list is like this:
id name
1  fish
2  cat
3  dog

it seems like dbflow inserts data order by the primarykey column?
can i insert data list and keep the list original order?

**Comment by agrosner** [comment]
if you want original order youll need to create a column that specifies insert time and then sort them by that. SQLite by default I believe has no exact order in the data.

**Comment by szitguy** [comment]
data list from net is already ordered by some logic, and maybe the order is not ordered by id, i just want to save them, and next time i query them out, they are the same order, but dbflow save them ordered by the primarykey column.

now i add a extra "_id" column as the primarykey, and the data's "id" column is specified as a common column, so when i save the data list, dbflow save them ordered by "_id" column, this way i can keep the original order.

**Comment by agrosner** [comment]
sounds good.

**Comment by pyus-13** [comment]
I have my custom primary key and I don't want to change that and create a new key, is there any way that I can persist the order of items and get in the order they were inserted ? 

Another workaround, I have a field which holds a unique number in string format like "34", "32". Is there any way I can fetch the data in desending order of it. I tried the orderBy() seems like doesn't work.
