### ISSUE TITLE
fastSave() and others

### ISSUE THREAD

**Issue by 2x2xplz** [Raizlabs/DBFlow#1252]
DBFlow Version: 4.0.0.-beta7
Issue Kind (Bug, Question, Feature): Question

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
I don't see the fast() functions mentioned in the docs or issue tracker. I followed the code so I think this is right...

Is writing this in Kotlin:

    modelList.fastInsert()

the same as this code in the [documentation](https://github.com/Raizlabs/DBFlow/blob/530cd6c6ccc4ef64c4a4638fd41e8bc0472c4fbf/usage2/StoringData.md#faststoremodeltransaction)

    FastStoreModelTransaction
      .insertBuilder(FlowManager.getModelAdapter(TestModel2.class))
        .addAll(modelList)
        .build()

and executing it one time?

I'd like to confirm that the .fastInsert(), .fastSave(), .fastUpdate() functions perform transactions without needing to be wrapped in a `database<myDB>().executeTransaction{ }` block. Pretty awesome if so. Thank you.

**Comment by agrosner** [comment]
not quite. it actually just simplifies the transaction builder for you. you will still need to write 
```kotlin
database<myDB>().executeTransaction{
  modelList.fastInsert()
    .build().execute()
} 
```

**Comment by agrosner** [comment]
you could always create an extension like:
```kotlin
inline fun <reified T : Any> ITransaction.executeAsync() = database<T>().beginTransactionAsync(this).execute()
```
then you can just:
```kotlin
modelList.fastInsert().build().executeAsync<myDB>()
```

**Comment by AlyssonPHN** [comment]
I got a faster insertion like this:

`val sqlInsert = SQLite.insert(Product::class.java).columns("_id", "descricao", ...)

            for (product in arrayList) {
                sqlInsert.values(product!!.idPro, produto.xdesc, ...)
            }
            sqlInsert.execute(databaseWrapper)`
