### ISSUE TITLE
Generated insertion code contains duplicate variable declaration when referring to converted type

### ISSUE THREAD

**Issue by FMinus** [Raizlabs/DBFlow#1254]
DBFlow Version: 4.0.0-beta7
Issue Kind: Bug

Description:
generated code does not take advantage of the type converter to set values back from the cursor

```
public class BaseEntity extends BaseModel implements Serializable{

    @PrimaryKey
    ObjectId id; //from 'org.mongodb:bson:3.0.4'

    //getters and setters 
}
```

```
@Table(database = DatabaseConfig.class,inheritedPrimaryKeys = {@InheritedPrimaryKey(column = @Column,primaryKey = @PrimaryKey,fieldName = "id")})
public class User extends BaseEntity implements Model {

    //other fields
}

```
ObjectId has a typeconverter class 

```
@Table(database = DatabaseConfig.class,inheritedPrimaryKeys = {@InheritedPrimaryKey(column = @Column,primaryKey = @PrimaryKey,fieldName = "id")})
public class Collaborator extends BaseEntity implements Model {

    @ForeignKey(saveForeignKeyModel = false,stubbedRelationship = true)
    private User user;

    //getters and setters

}
```

the generated code in Collaborator_Table tries to set the **id** of the **user** on a **collaborator** from a string rather than converting it to an ObjectId on the `loadFromCursor`

```
private final void loadFromCursor(Cursor cursor, Collaborator model){
//...
if (index_user_id != -1 && !cursor.isNull(index_user_id)) {
      model.setUser(new User());
      model.getUser().setId(cursor.getString(index_user_id));
    } else {
      model.setUser(null);
    }
//..
}
```

i bypassed this issue by creating a second setter of the id on the BaseEntity class that accepts a string 

also if the BaseEntity class is declared abstract the methods **bindToInsertValues** and **loadFromCursor** the generated variable ref id will be declared twice in the same scope making the code not compile

**Comment by agrosner** [comment]
yes this is a bug. for now you can specify a column name manually while keeping variable name unique:
```java
@Column(name = "id")
int _id;
```
something like this on your `Collaborator` class.

**Comment by agrosner** [comment]
now foreign keys have a special postfix based on `_Table` which will eliminate this issue. Also new generated code would prevent this issue you see here now. in `develop`.
