### ISSUE TITLE
how to get maximum value of Auto Incremented value

### ISSUE THREAD

**Issue by surindersinghbindra** [Raizlabs/DBFlow#1255]
DBFlow Version: 4.0.0-beta7
Issue Kind (Question):

i want to get last value or maximum value from Int type Property 
**@Table(database = AppDatabase.class)
public class RawData extends BaseObservable {

    @Unique
    @Column
    @PrimaryKey(autoincrement = true)
    public int id;
}**

Like here id here.

**Comment by agrosner** [comment]
this is more of a SQLite question...you can do it simply by reading from a query `Cursor`:

```java
Cursor cursor = SQLite.select(Method.max(RawData_Table.id).as("max")).from(RawData.class)
  .query()
int max = cursor.getInt("max");

cursor.close(); // when done
```

or using a `QueryModel`:
```java
@QueryModel
class MaxResult {

  @Column
  int max;
}

MaxResult result = SQLite.select(Method.max(RawData_Table.id).as("max")).from(RawData.class)
  .queryCustomSingle(MaxResult.class);
```

Something like that would work too if you don't like using `Cursor` directly.
