### ISSUE TITLE
 How to operate outside of the database

### ISSUE THREAD

**Issue by ozy20** [Raizlabs/DBFlow#1258]

**Comment by agrosner** [comment]
need more information here. this ticket makes no sense.

**Comment by ozy20** [comment]
My assets folder has a DB,how to operate it

**Comment by agrosner** [comment]
I'd suggest you look at the [documentation for prepackaged dbs](https://github.com/Raizlabs/DBFlow/blob/master/usage2/Databases.md#prepackaged-databases)

**Comment by ozy20** [comment]
Ok, thank you
