### ISSUE TITLE
Non-primary key auto increment index

### ISSUE THREAD

**Issue by simernes** [Raizlabs/DBFlow#126]
Could you please implement support for having columns as indexes that are not primary keys, but still auto increment? I tried looking at the Index documentation part you have, but I guess that's something else.

If I've missed it I'm sorry, but please point me in the right direction

**Comment by agrosner** [comment]
If you mean ```Column.AUTO_INCREMENT``` I actually don't have support for that yet. There are primary keys that autoincrement. So it may be that there is no support for a non-primary key autoincrement field. Yes?

**Comment by simernes** [comment]
Yes exactly. Problem is that you apparently cannot mix and match AUTO_INCREMENT primary keys and regular primary keys, or else I wouldve tried that.

**Comment by agrosner** [comment]
Ill make it a feature request for 1.7.0

**Comment by simernes** [comment]
great thanks

**Comment by agrosner** [comment]
actually this is not possible in Android. Only primary keys can autoincrement. http://stackoverflow.com/questions/7594541/android-table-creation-failure-near-autoincrement-syntax-error. I was getting:

```
android.database.sqlite.SQLiteException: near "AUTOINCREMENT": syntax error (code 1): , 
```
