### ISSUE TITLE
Impossible to use @NotNull with InheritedColumn

### ISSUE THREAD

**Issue by CapnSpellcheck** [Raizlabs/DBFlow#1265]
DBFlow Version: 4.0
Issue Kind (Bug, Question, Feature): Feature/Bug

Description: Seems like I can't use NotNull on an InheritedColumn because is separate annotation. Seems like NotNull should be an attribute of Column.

**Comment by agrosner** [comment]
Not null is not supported by `InheritedColumn` yet. it its certainly possible to add it to the annotation without breaking existing code. So I will add this as a feature request.

**Comment by agrosner** [comment]
in `develop`. use `@InheritedColumn(notNullConflict = )` if you specify anything other than `NONE` we assume its `@NotNull`

**Comment by CapnSpellcheck** [comment]
Thanks, do you have any suggestions for how to leverage `develop` into my build?

**Comment by trevjonez** [comment]
@CapnSpellcheck you can use the commit hash as the version and jitpack should create the artifact for you.
