### ISSUE TITLE
Annotations conflict

### ISSUE THREAD

**Issue by shiguangxiang** [Raizlabs/DBFlow#1267]
DBFlow Version:
4.0.0-beta7

Description: 
@ table annotation in conflict, could you tell me how to solve?

**Comment by agrosner** [comment]
Im sorry I do not understand the issue. I need more info.

**Comment by shiguangxiang** [comment]
I use the entity class @Database (name = DBFlowDatabase.NAME, version = DBFlowDatabase.VERSION), the compiler wrong, suggesting that the error message is a conflict, and I should use the Notes of the DataBinding conflict! Now did not find a solution, please help you ok?

**Comment by agrosner** [comment]
im sorry I don't understand.
First, "entity" should use `@Table` annotation, not `@Database`
Second, you should paste a screenshot of the compiler error here.
Third, "I should use the Notes of the DataBinding conflict!" If it's a DatabindingIssue, this is not a DBFlow issue.

**Comment by shiguangxiang** [comment]
Ok! thank you for your help! I am from China's Andrews developers, poor English ability to express!

**Comment by agrosner** [comment]
No worries. Screenshots and error messages can help a lot.

**Comment by shiguangxiang** [comment]
Listen to your tips using @Table annotations have been resolved. Thank you！
