### ISSUE TITLE
Is it possible to use DBFlow outside of android?

### ISSUE THREAD

**Issue by rerzer** [Raizlabs/DBFlow#1269]
DBFlow Version: Any
Issue Kind (Bug, Question, Feature): Question

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

So far I've only seen examples of DBFlow being used for android development (which seems to be the main focus of the project) but is it possible to use it for standard JVM Applications? If so, can someone direct me to any examples?

**Comment by agrosner** [comment]
no. unfortunately doing so would require a great deal of work on the lib. It is built around Android-specific cases and doing requires a 5.0 rewrite with support for the java libraries.

**Comment by trevjonez** [comment]
An alternative for jvm is requery which IMO has a similar feel to dbflow.

https://github.com/requery/requery
