### ISSUE TITLE
Question: Does anyone uses DBFlow with RxJava/RxAndroid?

### ISSUE THREAD

**Issue by Rainer-Lang** [Raizlabs/DBFlow#127]
Any experiences with DBFlow and RxJava?
Something which shouldn't be used?
Any comments?

**Comment by mrkma** [comment]
I use the combo and they work pretty well together. Are there any particular queries about them?

**Comment by Rainer-Lang** [comment]
In the near future - definitely. :-)
Can I ask you if I have some trouble?

**Comment by Rainer-Lang** [comment]
a) How do you use RxJava and DBFlow? Do you load models for a list or "only" single model loading?
b) Do you also use RxJava for saving models?

My workflow:
1) I get a lot of objects/models from a server (JSON) and I want to store them.
2) Then want to load and show them in a RecyclerView - if there is a new model in the database I want to load and show it in the list immediately.

**Comment by mrkma** [comment]
a - both
b - yes
I'm doing the same thing as you, I'm not sure if this is the best way of doing so but my code is like this for getting messages from a server

```
 public Observable<List<Message>> getConversation(String userId) {
        return Observable.create(subscriber -> {
            subscriber.onNext(messageListQuery(userId));
            webService.getMessages(userId).subscribe(res -> {
                for (ApiMessage m : res.results) {
                    Message message = m.toDbModel();
                    message.save(false);
                }
                subscriber.onNext(messageListQuery(userId));
            });
        });
    }

    private List<Message> messageListQuery(String userId) {
        return new Select().from(Message.class).where(Condition.column(Message$Table.USERFK_USERID).is(userId)).queryList();
    }


```

where `webService.getMessages()` returns an Observable (using Retrofit)

**Comment by Rainer-Lang** [comment]
just short answer before looking deeper in your answer. :-)
I also use Retrofit.
