### ISSUE TITLE
Export/Import or backup/restore Database in DBFlow

### ISSUE THREAD

**Issue by Mahdiazadbar** [Raizlabs/DBFlow#1270]
i use DBFlow for my sql lite jobs in android program. i need export or backup my data base and import or restore from special location in memory of phone. how can i do this?

**Comment by Mahdiazadbar** [comment]
any one?

**Comment by agrosner** [comment]
you can either use the `@Database(backupEnabled = true)` and call `backupDatabase()` on the `DatabaseDefinition` or simple file copy.
