### ISSUE TITLE
cannot access content provider in separate process

### ISSUE THREAD

**Issue by shenm233** [Raizlabs/DBFlow#1275]
DBFlow Version: 4.0.0-beta7
Issue Kind (Bug, Question, Feature): Bug

Description:
I defined a content provider which runs in separate process, such as in manifest.xml
`<provider
            android:name=".core.ContentProvider_Provider"
            android:authorities="com.test.provider"
            android:enabled="true"
            android:exported="false"
            android:process=":core"/>`

However, the other process queries an item, the content provider throws such an exception:

> java.lang.IllegalStateException: The global database holder is not initialized. Ensure you call FlowManager.init() before accessing the database.

I read the generated ContentProvider source code, I found that ContentProvider_Provider.onCreate() doesn't really call FlowManager.init() to initialize databases.
And I have added initializing FlowManager codes at onCreate() in custom Application class, but it doesn't work, because ContentProvider.onCreate() is called before Application.onCreate() .

I think it's necessary to add database initialization codes into the generated ContentProvider source code.

**Comment by ultraon** [comment]
Try to extend the generated ContentProvider and before calling super.onCreate() method call FlowManager.init(). In Manifest use your extended ContentProvider.

**Comment by agrosner** [comment]
Bad idea. Don't extend generated code. I will add an `init()` method in the `onCreate()` of `BaseContentProvider`.

**Comment by agrosner** [comment]
in `develop`. use commit `e294c00ab0` instead of `4.0.0-beta7` and should work.
