### ISSUE TITLE
Android Studio not find DBFlow

### ISSUE THREAD

**Issue by inromualdo** [Raizlabs/DBFlow#1278]
DBFlow Version: 4.0.0
Issue Kind (Bug, Question, Feature): Bug

Error:Failed to resolve: com.github.Raizlabs.DBFlow:dbflow-core:4.0.0
Error:Failed to resolve: annotationProcessor
Error:Failed to resolve: com.github.Raizlabs.DBFlow:dbflow:4.0.0

**Comment by agrosner** [comment]
try 4.0.1 and ensure your android studio tooling is up to date.

**Comment by sshutl** [comment]
![dbflow401](https://cloud.githubusercontent.com/assets/5792962/26004732/82cad7c6-373f-11e7-9ee2-d715e71dee04.jpg)

**Comment by trevjonez** [comment]
yea looks like jitpack choked on its self. @agrosner Pretty sure you should have a delete artifact option then it will retry the build. Since there hasn't been any artifacts produced for people to cache there shouldn't be an worries about going that route.

**Comment by agrosner** [comment]
4.0.1 worked for me. It choked because the new gitbooks site was pointing directly to the account, which I only have access too. So I created a public repo that people can contribute to and pointed the new submodule there.

**Comment by inromualdo** [comment]
Hi. finally 4.0.1 worked for me

**Comment by venkat4453** [comment]
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
} 


add above lines in your file
