### ISSUE TITLE
How to get status / result of FastStoreModelTransaction

### ISSUE THREAD

**Issue by jnischler** [Raizlabs/DBFlow#1283]
Hey,

we need to insert many thousand rows and therefore we would like to use the
FastStoreModelTransaction.

Some parts of our application need to wait for the transaction to complete, but as there is no result we are unable to wait.

Is there a way to get the status or result of this transaction?

Or is there a way to bulk insert rows synchronously.

Thanks for this great library!
😊

**Comment by agrosner** [comment]
By using the `Success` callback block on the `Transaction` executed from the DB.
`database.beginTransationAsync(FastStoreModelTransaction....).success(...).execute()`.

**Comment by agrosner** [comment]
to do it synchronous, use `executeSync()` method. but if its synchronous, then youll know it completed in line.

**Comment by jnischler** [comment]
perfect this was to easy ;)
Thanks!
