### ISSUE TITLE
DBFlow 3.0.0-beta5 not found on maven 

### ISSUE THREAD

**Issue by alex-vega-accedo** [Raizlabs/DBFlow#1289]
DBFlow Version: 3.0.0-beta5

The application we have uses DBFlow 3.0.0-beta5 but is not found anymore on the maven 
repository, so we cannot longer compile the source code. I found an issue that mentions
that other users have the same problem.

We cannot just upgrade from 3.0.0-beta5 to 3.0.0-beta6 because with newer library, source code 
simply does not compile without modifying the code, since 3.0.0-beta6 changed almost all the transaction implementation, and our code cannot be modified any longer.

Is there any possibility that you can fix the 3.0.0-beta5 so it can be compiled in
jitpack.io?  this specific version is the only one missing, it seems it is a problem in the javadoc
not in the functional code.

there is a reference to the same issue here for more info about the same error:
https://github.com/Raizlabs/DBFlow/issues/1132

I will really appreciate if can take a look to this issue.

Thanks in advance!

Alex

**Comment by agrosner** [comment]
it never built successfully. you can reference a specific 10-digit commit hash to grab the version you need or youll have to update.
