### ISSUE TITLE
DataClass should not nullable in TypeConverter.getModelValue(DataClass data).

### ISSUE THREAD

**Issue by NightlyNexus** [Raizlabs/DBFlow#1290]
https://github.com/Raizlabs/DBFlow/blob/4.0.2/dbflow-core/src/main/java/com/raizlabs/android/dbflow/converter/TypeConverter.java#L25

There is no value in trying to convert a null value here.

**Comment by agrosner** [comment]
null is useful when you need to return something like a default value in stead of `null`. in 5.0 the code gen is fixed and null is passed to the typeconverter.
