### ISSUE TITLE
Mark nullable types.

### ISSUE THREAD

**Issue by NightlyNexus** [Raizlabs/DBFlow#1291]
Use the support library annotations and mark nullable types in the public API.

**Comment by agrosner** [comment]
done. most of the lib. there might be a couple missing classes.

**Comment by NightlyNexus** [comment]
Thanks! Super great, especially for Kotlin users.

**Comment by agrosner** [comment]
oh yes. i am one of those, but havent used DBFlow in a real project using Kotlin as of yet.
