### ISSUE TITLE
Multidatabase?

### ISSUE THREAD

**Issue by myhcqgithub** [Raizlabs/DBFlow#1292]
Hi ,My database name is dynamic. Do you have any suggestions?

**Comment by carmas123** [comment]
Vote for my pull  #1206

**Comment by kistitan** [comment]
👍 for this issue.
It is actually duplicated, there is a closed one about the same, mentioning it is not planned to be supported, but it would be a great win for scenarios when the App is used by different users.

**Comment by myhcqgithub** [comment]
I database name not in application get,
need user login  just get.

**Comment by myhcqgithub** [comment]
@carmas123 
My The database name is not available in the application
need a user login to get it

**Comment by carmas123** [comment]
Yes I know

**Comment by carmas123** [comment]
@myhcqgithub 
I understand...so now I make an updated fork from lastest version and share on it my changes for you

**Comment by myhcqgithub** [comment]
@carmas123  Thanks,  I Expect Your Reply

**Comment by agrosner** [comment]
I will add it as a configuration parameter, still have to decide best way to do it.

**Comment by myhcqgithub** [comment]
@agrosner   FlowConfig Which parameter can clearly point out?

**Comment by baranowskinet** [comment]
For me this is also a big issue. I have system which has one main db and separate dbs per logged users. All databases are encrypted especially users based on user password. To make it work in dbFlow I had to prepare custom DatabaseHelper and under App class define specific 
```
public SQLiteDatabase openOrCreateDatabase(String name, int mode, SQLiteDatabase.CursorFactory factory)
public SQLiteDatabase openOrCreateDatabase(String name, int mode, SQLiteDatabase.CursorFactory factory, DatabaseErrorHandler errorHandler)
public File getDatabasePath(String name)
public boolean deleteDatabase(String name)
```
With that I can have two separate database files based on separate databases classes. First initialisation works ok and problems started when I want to move to another instance of User Database (the same class but different file - file name the same but separate folder). I forced call just closeDb() but FlowManager remember first instance and after changing database and init again databse I hade errors about that my old db is already closed. So I decide to call FlowManager.destroy() with small trick to prevent delete exsting database. That generally works ok but causes integrity issues as it close all databases which are linked to FlowManager. After testing I got few times db corruptions and t is really hard to find safety place to close all db. Generally I think any db shouldn't be closed to prevent multithreading issues. So the best solution for me will be not real close db but ability to remove db configuration from FlowManager and any configuration keep per database file path not based on database class.

**Comment by myhcqgithub** [comment]
@baranowskinet  How do you use dbflow to open different database files?

**Comment by baranowskinet** [comment]
I am creating encrypted databases on sd card based on:

**Comment by actionbar** [comment]
🙂Hello there! My database name is also dynamic in the project

**Comment by baranowskinet** [comment]
I really need to ability close individual database (release specific loadedModules which is now prvate in FlowManager). On the end I could make a fork but I prefer no do that and use original source.

**Comment by agrosner** [comment]
in 4.1.0 will replace static `@Database(name = "name")` with `DatabaseConfig.builder().databaseName("name")` dynamically. This will ensure that you can pass in a dynamic db name. You can also call `DatabaseDefinition.reset(DatabaseConfig)` to pass in a new configuration upon opening if you want to change DB name dynamically at runtime.

**Comment by agrosner** [comment]
in `develop`. use 10-digit commit hash `63158448c2` as version to check it out.
