### ISSUE TITLE
Best way to insert data at first launch

### ISSUE THREAD

**Issue by StephenAndroid** [Raizlabs/DBFlow#1294]
Hi,

I want to insert multiple data in database at first launch.
I don't find the way to do this in documentation.

What is the best way ? There is one way to do this with DBFlow ?
I think the best way is to execute db file with inserts queries, but i don't know when execute this.

Thanks a lot for your help.

**Comment by agrosner** [comment]
You can do it wherever you want. Depending on your implementation, but has to be after DBFlow is initialized. Depends on the data, can you create a prepackaged db file? You can prepackage existing file to get copied over on app launch so you don't have to insert reams worth of data. https://agrosner.gitbooks.io/dbflow/content/Usage.html
