### ISSUE TITLE
Issue with performance  in multi module project

### ISSUE THREAD

**Issue by zezekalo** [Raizlabs/DBFlow#1295]
DBFlow Version: '4.0.0-beta7'
Issue Kind (Bug, Question, Feature): Question

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
I used DbFlow lib in my application and it worked Ok.
Then I decided to refactor it, created several modules('app', 'infrastructure' and so on) and passed code to these new modules. 
When I moved code with DbFlow to 'infrastrucure' I've got an issue:

`Warning:File for type 'com.raizlabs.android.dbflow.config.MinFinDatabaseMinFinDb_Database' created in the last round will not be subject to annotation processing.
Warning:File for type 'com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder' created in the last round will not be subject to annotation processing.
.../infrastructure/repository/settings/db/DbSettingStorage.java
Error:(60, 59) error: package DbSettings_Table does not exist
Error:Execution failed for task ':infrastructure:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED`

As I see the issue happened because of moving all the files associated to DbFlow to another modules, there are some warnings with Database itself and particular table wasn't found.
Is there any fix to it?

**Comment by zezekalo** [comment]
Is there any problems with using dbFlow in multi-modules application?

**Comment by trevjonez** [comment]
All tables must be defined in the same module as the database they belong
to.

**Comment by zezekalo** [comment]
Yes, I followed this rule, my Database-description file and Table-description files are in the same module named 'infrastructure'.
Build. gradle of this module:
`apply plugin: 'com.android.library'

android {
	compileSdkVersion rootProject.ext.versions.android.compileSdk
	buildToolsVersion rootProject.ext.versions.android.buildTools

	defaultConfig {
		minSdkVersion rootProject.ext.versions.android.minSdk
		targetSdkVersion rootProject.ext.versions.androidtargerSdk

		testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
	}

	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
		}
	}
}

dependencies {
	compile "com.android.support:appcompat-v7:$rootProject.ext.versions.android.support"

	annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:$rootProject.ext.versions.db.dbFlow"
	compile "com.github.Raizlabs.DBFlow:dbflow-core:$rootProject.ext.versions.db.dbFlow"
	compile "com.github.Raizlabs.DBFlow:dbflow:$rootProject.ext.versions.db.dbFlow"

	compile project(path: ':domain')
}
`
The problem is then after compiling I didn't find link to new generated table class.
All these happened when I moved database initialization code from main module to lib-module and I asked if this is a bug of dbFlow or mine?

**Comment by trevjonez** [comment]
It sounds like it is an issue with something in your code not compiling which given the cyclic nature of APT baed libraries can make this hard to track down. I would urge you to verify all imports of generated code are correct first.

The db in a module can work as it was the primary method I typically use with my db related content. 

this just seems like residue from your refactor.

**Comment by trevjonez** [comment]
also if you are using kotlin you should use `kapt` not `annotationProcessor`
