### ISSUE TITLE
@ForeignKey(stubbedRelationship = true)  annotated field is 'null'

### ISSUE THREAD

**Issue by facundobringas** [Raizlabs/DBFlow#1296]
DBFlow Version: 4.0.2
Issue Kind: Bug
Description: 

I 've just upgraded from 4.0.0-beta7 and having the following class , ForeignKey annotated property is initialized "null".

```
/**
 * Created by facundo on 26/01/17.
 */
@Table(database = AppDatabase.class, name = "magazines")
public class Magazine extends BaseModel {

    @Column
    @PrimaryKey
    public long id;

    **@ForeignKey(stubbedRelationship = true)
    public Catalog catalog;**


    @Override
    public boolean equals(Object obj) {
        if(obj instanceof Magazine){
            Magazine other = (Magazine) obj;
            return this.id == other.id;
        }
        else {
            return super.equals(obj);
        }

    }

    @Override
    public int hashCode() {
        return (int)id;
    }

}
```

**Comment by agrosner** [comment]
field will be null if not present in the cursor.

**Comment by facundobringas** [comment]
Thanks for your answer. I've just noticed that my description was incomplete. I was talking about the ForeignKey(StubbedRelationship)  property. I've just edited to the correct way. Field is present. I'm using a populated database. Downgrading to 4.0.0-beta7 allows me to continue using DBFlow in my app that is already in production. I was intended to upgrade to 4.0.2 but unfortunately if I do app will crash in thousands of users. Is this the intended behaviour? No longer initializing a StubbedRelationship?

**Comment by agrosner** [comment]
yes no longer if the whole object not in cursor for efficiency purposes. because if the cursor does not contain the column or a primary key is null, it will be ignored.

**Comment by agrosner** [comment]
have your model implement `LoadFromCursorListener` and keep it non null by checking and initializing it to a default value.

**Comment by agrosner** [comment]
or in 4.0.4 if you annotate with `android.support.annotations.NonNull` or jetbrain's `NotNull`, it will not assign a null value to it if you provide a default nonnull value.
