### ISSUE TITLE
Add javax.annotation.Generated annotation to generated classes.

### ISSUE THREAD

**Issue by NightlyNexus** [Raizlabs/DBFlow#1297]
This helps with tooling. For example, static analysis tools can skip checking these classes.
In a project I work on, Error Prone yells a lot about the generated code from this library. (Also, those warnings might might be worth fixing. I may file separate issues for them later if that would be welcome.)

**Comment by agrosner** [comment]
if its on classpath, we will generate it. in `develop` for 4.1.0.
