### ISSUE TITLE
IndexGroup doesn't work property

### ISSUE THREAD

**Issue by olbb** [Raizlabs/DBFlow#1298]
DBFlow Version:4.0.2
Issue Kind (Bug, Question, Feature):Bug
Description: 
Hello, I used IndexGroup and Index with 4.0.2, but I found it's not precise in generated code. 
The columns is empty , then throw a "There should be at least one column in this index" exception.
Here is my code.
![image](https://cloud.githubusercontent.com/assets/5554102/26301678/7ea182ee-3f14-11e7-906f-084e53f6cdb6.png)

![image](https://cloud.githubusercontent.com/assets/5554102/26301732/9e62c2aa-3f14-11e7-9391-b3bc05d6d32d.png)

**Comment by iveyalkin** [comment]
We have the same issue when were trying to migrate to `4.0.2` from `3.0.1`. The exception is being thrown in the initial migration script, that is `version = 0`, hence, when the DB is being initialized. I can confirm, that `IndexProperty<>` initialization call lacks of indexed columns list.
Migration script:
```
@Migration(version = 0, database = MyDatabase.class)
public class InitialIndexMigration extends BaseMigration {

    @Override
    public void migrate(DatabaseWrapper database) {
        PendingMessage_Table.index_pending_message_chat_id.createIfNotExists(database);
    }
}
```
Model:
```
@Table(database = MyDatabase.class,
        indexGroups = {
                @IndexGroup(name = PendingMessage.INDEX_CHAT_ID)
        })
public class PendingMessage extends BaseModel {
    static final String INDEX_CHAT_ID = "pending_message_chat_id";

    @Nullable
    @Index
    @ForeignKey(
            references = {
                    @ForeignKeyReference(
                            columnName = "chat_id",
                            foreignKeyColumnName = "id"
                    )
            },
            onDelete = ForeignKeyAction.CASCADE)
    Chat chat;
}
```
Generated code:
```
public final class PendingMessage_Table extends ModelAdapter<PendingMessage> {
    public static final IndexProperty<PendingMessage> index_pending_message_chat_id = new IndexProperty<>("pending_message_chat_id", false, PendingMessage.class);
}
```

**Comment by agrosner** [comment]
fixed in `develop`. for 4.0.3
