### ISSUE TITLE
Consider making the library easier to use

### ISSUE THREAD

**Issue by tsuharesu** [Raizlabs/DBFlow#130]
Right now DBFlow do a hell lot of things, and is incredible good. I liked a lot about what I saw, and I am an avid supporter. But...

This idea of "you can do things on different ways, the way you like" is not a good thing on long term. I mean, it is really good to have options and do things more automatic or by doing more queries. But this is giving the library a confusion problem. "Do I need to create a Select or can I use the static method? Why when I create I have some options and when I use the static method no?" This can hurt the library. This day I was looking for a way to simply use a Callback when I finished saving objects on a transaction and lost some time until I find something... looking at the code. And I don't event know if I'm doing this right... I can see that a lot of issues is because people are lost trying to use it.

This is not a rant, it's more of a tip. This is one of the best libraries I used for Android, it's fast, it's stable and have a lot of good ideas. But consider making breaking changes that can really help library users out there in version 2. 

I'm open to help with documentation, Wiki or even coding if it's needed.

**Comment by Rainer-Lang** [comment]
@tsuharesu You are right. I'm relatively new with DBFlow... I read and read and read - and I don't know when I write the code if this is good or not.
The docu should also be adjusted to the good features of DBFlow.
I would appreciate if someone helps with the docu - so Andrew could concentrate to develop the great lib.

**Comment by panzerfahrer** [comment]
I'd like to +1 this.

Even though I'm not really using every aspect of the lib yet, I feel like the things I used so far all have 1-3 ways of doing them. As tsuharesu pointed out, it really might be better to make the way how to use the exposed API more consistent and maybe even more strict.

Also, I'd say it is counterproductive to try to please everybody's liking. It was one reason why chose this library over others, because it seems it's concentrating on the one problem: getting ORM right.

Feel free to trigger me for coding/docu as well.

**Comment by Rainer-Lang** [comment]
@tsuharesu and @panzerfahrer Please look at this issue #154 
Maybe you could write something, maybe save is also to handle like load with annotations.
I think an example would be great.
I also think it would be good if more users help Andrew to extend the wiki, so he could concentrate on DBFlow.
@agrosner You are doing a really really great job and your support is very fine! My words above aren't a criticism, I hope you understand me. English is not my mother tongue. :-)

**Comment by agrosner** [comment]
right I agree with everyone here. I added in too many ways to do certain things--I wanted to try to achieve balance with flexibility and usability. I don't want to limit what developers could do because who wants to have to fork/clone the project, when it should be ready to go out of the box for 99% of cases?

**Comment by Rainer-Lang** [comment]
@agrosner I "only" want some more examples and a bit of more docu. ;-)

I also love flexibility, but this should be written down:
to do X:
1) In this way: with pros and cons
2) alternative 1: with pros and cons
3) alternative 2: with pros and cons

But I know, that's a big thing to do it in this way. :-)
I think this can be achieved if 1 to 3 persons are contributing some time.

**Comment by tsuharesu** [comment]
@agrosner I agree with you last sentence. It's just faster to put the dependency on Maven that set up you library, put as a dependency and blablabla. But sometimes this wave of information make us confuse.

What I could help is with more documentation, knowing that on next versions this should get better, ie, less ways to achieve the same thing. There should be an easy way to do something and a advanced way. Like in `Select`: if DBFlow can't do something "easy", I'm making my own `selectClause` and using `where(String)`. It's not really a OO way of doing things, but it is how I can do advanced things.

**Comment by agrosner** [comment]
@tsuharesu Yeah. for 2.0.0 for example, I am removing some of the extraneous ways of writing queries. I removed the static methods and simplified some things. If you wish to check it out, its on the 2.0.0 branch. That won't be released for a few weeks as it will be a major update to the lib.

**Comment by tsuharesu** [comment]
Nice! I'll try to take a look later :+1:
