### ISSUE TITLE
DBFlow ignoring generic classes

### ISSUE THREAD

**Issue by teamagam3** [Raizlabs/DBFlow#1305]
DBFlow Version: 4.0.2
Issue Kind (Bug, Question, Feature): Bug

Description: 

Hi,
I'm trying to create a table from a generic class. For example, I have this class:

```
@Table(database = AppDatabase.class)
public class Test extends BaseModel {
  @PrimaryKey
  @Column
  private String name;

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }
}
```

This code works fine. 
If I add a generic type to the class `public class Test<T> extends BaseModel`,
DBFlow won't create a table class (Test_Table), and it seems that the class Test is being ignored by DBFlow.

I haven't found any documentation about or similar questions about this issue.

If that's not possible, is there any way to do something similar to make it work?

Thanks!

**Comment by agrosner** [comment]
Generic classes are not supported. You could, however, make the class abstract and extend it to each subclass you need as separate tables. We don't support generic columns though so you would need to make abstract getter/setter or something that you implement in subclass with variable.
