### ISSUE TITLE
Generated ModelAdapter handles Nulls incorrectly in bindToInsertValues()

### ISSUE THREAD

**Issue by jdabrowski1337** [Raizlabs/DBFlow#1306]
DBFlow Version: 4.0.2
Issue Kind (Bug, Question, Feature): Bug

Description: 

The generated ModelAdapter handles nulls incorrectly. It creates two keys in the ContentValues for the same column: ex. "parent_id" and "\`parent_id\`". 

Here is a snippet from the generated code:
`
    if (model.getDeviceType() != null) {
           values.put("``deviceType_id``", model.getDeviceType().getId());
        } else {
          values.putNull("deviceType_id");
        }
`
_[the double back ticks should be single, I can't get around githubs back tick being used for code formatting]_

This results in a bug when using FastStoreModelTransaction, which reuses the ContentValues instance for multiple updates. The problem is that when there are two instances of the model saved in such a transaction and first model has deviceType_id set and the second model has a null in this field then both models will be saved with the same deviceType_id of the first model, because second run of bindToInsertValues will not clear the correct ContentValues key.

The result of running the bindToInsertValues two times on the same ContentValues instance (on above example) is something like this:

ContentValues {deviceType_id=3,`deviceType_id=null}

but the SQLite will only use the deviceType_id key, not the escaped one.

**Comment by agrosner** [comment]
fantastic catch. luckily 4.0.2 doesnt use `ContentValues` when inserting anymore. but anyways it will be fixed in 4.0.3.
