### ISSUE TITLE
Using dbflow in an aar library

### ISSUE THREAD

**Issue by luisreja76** [Raizlabs/DBFlow#1308]
DBFlow Version:
Issue Kind (Question):

Description: 
I'm trying to use dbflow inside an aar library. All appears to going well, in my module library the tables are generated, but when I include this aar generated in a sample app and try to init dbflow, the following error appears:

> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/raizlabs/android/dbflow/config/FlowConfig$Builder;
>                                                                        at com.trecone.treconesdk.TreconeSDK.<init>(TreconeSDK.java:46)
>                                                                        at com.trecone.treconesdk.TreconeSDK.getInstance(TreconeSDK.java:112)
>                                                                        at com.trecone.sdktest.MyApp.onCreate(MyApp.java:19)
>                                                                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
>                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
>                                                                        at android.app.ActivityThread.-wrap1(ActivityThread.java)
>                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
>                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                        at android.os.Looper.loop(Looper.java:148)
>                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417)
>                                                                        at java.lang.reflect.Method.invoke(Native Method)
>                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.raizlabs.android.dbflow.config.FlowConfig$Builder" on path: DexPathList[[zip file "/data/app/com.trecone.sdktest-1/base.apk"],nativeLibraryDirectories=[/data/app/com.trecone.sdktest-1/lib/x86_64, /vendor/lib64, /system/lib64]]
>                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
>                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
>                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
>                                                                        at com.trecone.treconesdk.TreconeSDK.<init>(TreconeSDK.java:46) 
>                                                                        at com.trecone.treconesdk.TreconeSDK.getInstance(TreconeSDK.java:112) 
>                                                                        at com.trecone.sdktest.MyApp.onCreate(MyApp.java:19) 

**//////build.gradle in my library/////////////////////////////////////**
.
.
def dbflow_version = "3.1.1"

apt {
    arguments {
        targetModuleName 'sdk'
    }
}
.
.
//DBFLOW
    apt "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"

////Init dbflow in my library//////////////////////////////////////////////

FlowManager.init(new FlowConfig.Builder(context).build());
            DatabaseHolder sdkGeneratedDatabaseHolder = (DatabaseHolder) Class.forName(
                    "com.raizlabs.android.dbflow.config.sdkGeneratedDatabaseHolder").newInstance();
            FlowManager.initModule(sdkGeneratedDatabaseHolder.getClass());

//////build.gradle from my sample app////////////////////////////////////////////////////////
.
.
repositories {
    flatDir {
        dirs 'aars'
    }
}
.
.
compile (name: 'sdk-debug', ext: 'aar')
.
.
/////////Calling init from my sample app//////////////////////////////
I Call from a Multidex aplication called MyApp to pass the application context.

public class MyApp extends MultiDexApplication {

    public static TreconeSDK treconeSDK;

    @Override
    public void onCreate() {
        super.onCreate();
        treconeSDK =TreconeSDK.getInstance(this);
    }
}

Any tips or ideas? Thank you in advance

**Comment by trevjonez** [comment]
Are you producing a pom file for your library? If not than you are
certainly missing all of the required transitive dependencies. Based on the
way you are including your aar in the build I am thinking the issue is in
how you publish the aar.

This is probably not a dbflow issue just the first place it shows up is
when initializing dbflow.

**Comment by luisreja76** [comment]
No, I'm not including POM file, this is my very first aar. I think you are right, it is something with the transitive dependencies. Im going to go in this line.

I'll post the solution when I find.

Thank you very much for your quick response @trevjonez .

**Comment by trevjonez** [comment]
give this plugin a look: https://github.com/dcendents/android-maven-gradle-plugin

it is the easiest way to get going. once configured you can run `./gradlew lib:install` to use it locally.

**Comment by luisreja76** [comment]
Ok, I'll take a look... Thank you again @trevjonez

**Comment by mkashifkamb** [comment]
@luisreja76 , have you able to find the solution? I am facing the same problem. I have used Transitive property but still same exception

**Comment by luisreja76** [comment]
Hi @mkashifkamb ,

I do not resolve it yet, because Im working in another project now. But I discover what happens:

As @trevjonez pointed, you need to put your aar in a maven repository (local or remote) with a POM file, so gradle can resolve the interdependencies.

Another way is to include locally dbflow jars and aars in the libs folder.

Check this:

https://github.com/dcendents/android-maven-gradle-plugin

You can check this too:

https://support.sonatype.com/hc/en-us/articles/218637467-Download-Nexus-Repository-Manager-3

Hope it helps!!

Please report your solution I you find it!!!

**Comment by luisreja76** [comment]
Hi @mkashifkamb and @trevjonez , I managed to resolve the issue and I'll try to explain the process. 
(Feel free to comment if I'm doing or saying something wrong)

The problem: Trying to generate an aar who depends on third party librarys (in this case dbFlow), when you include your aar in a new app, gradle was not able to resolve this dependency.

How I managed to resolve:
- Since dbflow has no repository on mavenCentral I have to configure my own mavenLocal (you can find useful info here: https://spring.io/guides/gs/maven-android/) and deploy the jars and aars needed for dbflow to run.
- In the gradle of my library y put the following code:
publishing {
    publications {
        maven(MavenPublication) {
            version '0.0.1'
            artifact bundleRelease
            pom.withXml {

                    def dependenciesNode = asNode().appendNode('dependencies')

                    configurations.compile.allDependencies.each { dependency ->
                        def dependencyNode = dependenciesNode.appendNode('dependency')
                        dependencyNode.appendNode('groupId', dependency.group)
                        dependencyNode.appendNode('artifactId', dependency.name)
                        dependencyNode.appendNode('version', dependency.version)

                    }

            }

        }
    }
}

This code may be invoked via Android studio terminal typing:
gradlew clean build publishToMavenLocal

This comand generates the aar and pom file with all the dependencies needed and deploy the generated aar in our mavenLocal. (Note that if you have another dependency which is stored in mavenCentral, you don't need to deploy it in your local maven.)

- In the app you want to use the aar, edit gradle and put:
compile  group: 'GroupName', name: 'sdk', version:"0.0.1"
Now gradle seeks in our mavenLocal, reads pom file and is able to resolve the dependencies.

And that's all, it took me days to resolve, but it is working now.

Thank you @trevjonez for the support .
