### ISSUE TITLE
Publish sources jar.

### ISSUE THREAD

**Issue by NightlyNexus** [Raizlabs/DBFlow#1310]
https://github.com/Raizlabs/DBFlow/blob/baa52700a21e49981cdf81bcc4d8f0626c2e3905/android-artifacts.gradle#L25
I see the task for it, but I don't see the sources jar on jitpack. The sources jar is helpful for modern IDEs like IntelliJ IDEA that will jump to these sources rather than decompiling the class files.

**Comment by agrosner** [comment]
it should be there for all pure java artifacts. what is missing?

**Comment by NightlyNexus** [comment]
Oops, yes, I missed it. Apologies and thank you!
