### ISSUE TITLE
How to get the data from a queryList?

### ISSUE THREAD

**Issue by JunjieCheng** [Raizlabs/DBFlow#1312]
Hi,

If I use something like this
`List<C> cList = SQLite.select(sum(amount).as("total")).from(C.class)
                            .where(C_Table.id.eq(id)).queryList();`

How can I get the "total"? Do I have to define a new table?

BTW, I try to implement the following command, but I don't know if this is correct?

// "SELECT COUNT(DISTINCT(S_I_ID)) AS LOW_STOCK FROM ORDERLINE, STOCK WHERE OL_W_ID = ? AND OL_D_ID = ? AND OL_O_ID < ? AND OL_O_ID >= ? AND S_W_ID = ? AND S_I_ID = OL_I_ID AND S_QUANTITY < ?"
        
`iLowStock = SQLite.select(Stock_Table.iId).from(OrderLine.class)
                .innerJoin(Stack.class)
                .on(Stock_Table.iId.eq(OrderLine_Table.iId))
                .where(OrderLine_Table.wId.eq(w), OrderLine_Table.dId.eq(d), OrderLine_Table.oId.lessThan(nextOrder),
                        OrderLine_Table.oId.greaterThanOrEq(nextOrder - 20), Stock_Table.wId.eq(w), Stock_Table.quantity.lessThan(threshold))
                .count();`

**Comment by agrosner** [comment]
if you have a query that maps to non-standard tables, yes you need to create a `@QueryModel`. https://agrosner.gitbooks.io/dbflow/content/QueryModels.html
