### ISSUE TITLE
DBflow make simple relation ship between 2 table (one to many)

### ISSUE THREAD

**Issue by MahdiPishguy** [Raizlabs/DBFlow#1316]
how can i make simple relation ship between to table i can't do that,

i have 2 table as

`MainCategories` and `SubCategories`

in `SubCategories` i have `channelId` which its stored on `MainCategories`, `MainCategories` has more data on `SubCategories` table, (one to many)

now i'm trying to implementing this relation ship:

my code is not correct and its like with the library documentation 

`MainCategories`:

    @Table(database = AppDatabase.class)
    public class ChannelContentCategories extends BaseModel {
        @PrimaryKey(autoincrement = true)
        private int id;
    
        @Column
        private int channelId;
    
        @Column
        private String title;
    
        List<ChannelSubContentCategories> subContentCategories;
    
        @OneToMany(methods = {OneToMany.Method.ALL})
        public List<ChannelSubContentCategories> getMyChannelSubContentCategoriess() {
            if (subContentCategories == null || subContentCategories.isEmpty()) {
                subContentCategories = SQLite.select()
                        .from(ChannelSubContentCategories.class)
                        .where(ChannelSubContentCategories_Table.queenForeignKeyContainer_id.eq(id))
                        .queryList();
            }
            return subContentCategories;
        }

        ...
    }

`SubCategories`:

    @Table(database = AppDatabase.class)
    public class ChannelSubContentCategories extends BaseModel {
        @PrimaryKey(autoincrement = true)
        private int id;
    
        @Column
        private int categoryId;
    
        @Column
        private int parentId;
    
        @Column
        private String title;
       
        ...
    }

how can i make simple relation ship between `channelId` on `ChannelContentCategories` table with `parentId` on `ChannelSubContentCategories` table?

**thanks in advance**

**Comment by agrosner** [comment]
probably better suited for stackoverflow here. 
but it looks like:
```
.where(ChannelSubContentCategories_Table.queenForeignKeyContainer_id.eq(id))
```
you are not referencing the proper field here. it should be:
```
.where(ChannelSubContentCategories_Table.id.eq(id))
```
