### ISSUE TITLE
Issue in update

### ISSUE THREAD

**Issue by JunjieCheng** [Raizlabs/DBFlow#1317]
Hi,

I'm trying to update a column in the table. It works when I do this:

```
Category category = SQLite.select().from(Category.class)
                    .where(Category_Table.id.eq((long)c))
                    .querySingle();

category.setTitle(this.random.randomAString26_50());
category.save();
```

But when I do this, it doesn't work:

`SQLite.update(Category.class)
                    .set(Category_Table.title.eq(this.random.randomAString26_50()),
                            Category_Table.pages.eq(this.random.randomInt(1, 10000)),
                            Category_Table.subcats.eq(this.random.randomInt(1, 5000)),
                            Category_Table.files.eq(this.random.randomInt(1, 20000)))
                    .where(Category_Table.id.eq((long)c));`

I hope to use the second one because I want to update multiple columns at the same time. Is there anything wrong with this?

Thank you.

**Comment by agrosner** [comment]
you didn't add `executeUpdateDelete()` at end of update query....
