### ISSUE TITLE
no such column when inner join

### ISSUE THREAD

**Issue by JunjieCheng** [Raizlabs/DBFlow#1318]
Hi,

I'm trying to use the following statement:

`long count = SQLite.select(count(OrderLine_Table.oLIId)).from(OrderLine.class)
                .innerJoin(Stock.class)
                .on(OrderLine_Table.oLIId.eq(Stock_Table.sIId))
                .count();`

But I got the error:

E/SQLiteLog: (1) no such column: oLIId
android.database.sqlite.SQLiteException: no such column: oLIId (code 1): , while compiling: SELECT COUNT(`oLIId`) FROM `OrderLine` INNER JOIN `Stock` ON `oLIId`=`sIId`

Tried many times but still have no idea. I also tried #1085.

Thank you for your help.

**Comment by agrosner** [comment]
use `OrderLine_Table.oLIId.withTable().eq(...)`
