### ISSUE TITLE
ColumnValidator error when extending BaseRXModel

### ISSUE THREAD

**Issue by iamareebjamal** [Raizlabs/DBFlow#1320]
DBFlow Version: 4.0.3
Issue Kind (Bug, Question, Feature): Bug

Description: 
When extending from BaseRXModel and using `allFields = true`, ColumnValidator throws error saying that 

```
Error:*==========*class com.raizlabs.android.dbflow.processor.ColumnValidator (Kotlin reflection is not available) :Could not find getter for private element: "modelAdapter" from table class: SimpleModel. Consider adding a getter with name getModelAdapter or making it more accessible.*==========*
```

I saw in code that `modelAdapter` has `@ColumnIgnore` annotation set on it, which makes this error more weird. My model class is very simple test class.

````Java
@Table(database = OrgaDatabase.class, allFields = true)
public class SimpleModel extends BaseRXModel {

    @PrimaryKey
    public long id;

    public String name;
    public String description;

    SimpleModel() {}

    public SimpleModel(long id, String name, String description) {
        this.id = id;
        this.name = name;
        this.description = description;
    }

}
````

**Comment by agrosner** [comment]
thats weird. let me try it. might be `allFields`

**Comment by agrosner** [comment]
yes that was it. so making the `@ColumnIgnore` annotation retained in the `CLASS` instead of `SOURCE` it works. probably something to do with it referencing the annotation from another module. in `develop`.

**Comment by kamilski81** [comment]
Was there a solution to this?
