### ISSUE TITLE
Failed to resolve: com.github.Raizlabs.DBFlow:dbflow:4.0.3

### ISSUE THREAD

**Issue by hcw2175** [Raizlabs/DBFlow#1321]
DBFlow Version: 4.0.3
Issue Kind: Question
Description: 

Hi，I want to upgrade the version 4.0.3 of DBFlow，but i got some error:

![image](https://user-images.githubusercontent.com/8132286/26910589-60ba7cee-4c3a-11e7-8b83-14f66f2a7517.png)

I'm not use the `android-apt` but use `android-build-tools`，and i think it`s not the reason with this.

how can i resolve it ? please!!

----- 

My configs:

**root build.gradle:**

```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.2'
        classpath 'com.tencent.bugly:symtabfileuploader:2.1.0'
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
}
```

**module build.gradle：**

```
annotationProcessor 'com.github.Raizlabs.DBFlow:dbflow-processor:4.0.3'
compile 'com.github.Raizlabs.DBFlow:dbflow-core:4.0.3'
compile 'com.github.Raizlabs.DBFlow:dbflow:4.0.3'
```

**Comment by hcw2175** [comment]
e, when i use the old version `4.0.0-beta7` it's no problem

**Comment by dreamcatcha** [comment]
I'm get this with 4.0.4 version

**Comment by GerritDeMeulder** [comment]
Hi All, 
solution to this for me was to change the "... Raizlabs.DBFlow ..." part to lowercase "... raizlabs.dbflow ..."
I think this might be android studio 2.3.3 related, 
because I just recently got this in 4.0.4, and not in 4.0.3 before I upgraded AS.

**Comment by baranowskinet** [comment]
Yes, convert to lower case solves problem.  Please update main page on Github with proper example of installation.

**Comment by agrosner** [comment]
oddly enough jitpack is case sensitive. I use 4.0.4:
```
kapt "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
```
no problem.

**Comment by shobhik** [comment]
This is happening again on 4.2.4. I tried to introduce it to two new projects and ran into this issue. 

I have 
`maven { url "https://www.jitpack.io" }` in project Gradle, and 
```
    compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
```
in app build.gradle file as indicated in readme. Going to lowercase didn't solve my problem.

**Comment by KeitelDOG** [comment]
I had the same problem with Gradle 3.0.1, I tried almost everything, with no success. Finally I place the maven repo path in All Projects section and it worked:

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()

        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by ivan8m8** [comment]
@shobhik Ensure you placed `maven { url 'https://www.jitpack.io' }` within 
```
allprojects {
    repositories {
        ...
        maven { url 'https://www.jitpack.io' }
```

Not within 
```
buildscript {
    repositories {
        ...
```
at the top of the file.

So, your file should look something like the following:
```
buildscript {
    
    repositories {
        google()
        jcenter()
        // THIS IS NOT A PLACE TO PUT MAVE DEPENDENCY
    }
    dependencies {
        ...
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://www.jitpack.io" } // THAT'S THE PLACE
    }
}
```

**Comment by venkat4453** [comment]
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}




place the above code in your gradile file

**Comment by ArtanBerisha1** [comment]
For me going to lowercase worked, but do we know why is this working ?
