### ISSUE TITLE
Counted read when I insert data into database

### ISSUE THREAD

**Issue by JunjieCheng** [Raizlabs/DBFlow#1322]
Hi,

I'm doing a test on the performance of  DBFlow. When I insert something like this:

```
Item item = new Item();
item.setId(i);
item.save();
```

My tool detects that there are always a little bit more read than write while inserting. Do you know what may cause it?

Thank you.

**Comment by agrosner** [comment]
1. check if exists by select query
2. if exists update
3. if not, insert.

**Comment by agrosner** [comment]
if you know it doesnt exist you should call insert() or conversely if you know it exists you call update instead.

**Comment by agrosner** [comment]
if you need a performance test, check out this one: https://github.com/agrosner/AndroidDatabaseLibraryComparison2
