### ISSUE TITLE
Add parenthesis in Property arithmetic operations

### ISSUE THREAD

**Issue by jurmeneta** [Raizlabs/DBFlow#1323]
DBFlow Version: 3.1.1.
Issue Kind (Bug, Question, Feature): Question/Feature

Description: 
I'm using the arithmetic operations in the properties.
Concretely I'm trying to achieve this query: 
```SQLite
select *, (
	(pLatitude - latitude) * (pLatitude - latitude) + (pLongitude - longitude) * (pLongitude - longitude)
	) as distance 
from shops order by distance
```
Which returns a list of shops sorted by distance.
I tried to translate this sql query into dbflow in this way:

```java
SQLite.select(Property.ALL_PROPERTY, ShopDataStore_Table.latitude.minus(pLatitude).multipliedBy(ShopDataStore_Table.latitude.minus(pLatitude)).
                plus(ShopDataStore_Table.longitude.minus(pLongitude).multipliedBy(ShopDataStore_Table.longitude.minus(pLongitude)).as("distance")))
                .from(ShopDataStore.class)
                .orderBy(ShopDataStore_Table.distance,true)
                .queryList();
```

But the query generated has no parenthesis, and the results obtained are wrong:

`SELECT *,`latitude` - 41.3895635 * `latitude` - 41.3895635 + `longitude` - 2.1129822 * `longitude` - 2.1129822 AS `distance` FROM `ShopDataStore` ORDER BY `distance` ASC `

Then, how can I add parenthesis in order to do first the minus operations?

Thank you!

Note: pLongitude=2.1129822 and pLatitude=41.3895635

**Comment by agrosner** [comment]
to wrap them in parenthesis, you need to use a `ConditionGroup.clause()` and wrap the operations within that clause instead of chaining them between each other as youve done here.

**Comment by jurmeneta** [comment]
Thanks for your fast answer agrosner!
But, there are not conditions, there are properties!
Then, how can you wrap them in a ConditionGroup.clause()

Thank you!

**Comment by agrosner** [comment]
select *, ( (pLatitude - latitude) * (pLatitude - latitude) + (pLongitude - longitude) * (pLongitude - longitude) ) as distance from shops order by distance

```java

SQLite.select(Property.ALL_PROPERTY, 
ConditionGroup.clause(
ConditionGroup.clause(pLatitude.minus(latitude)).times(ConditionGroup.clause(pLatitude.minus(latitude))).plus(...)..... etc.
)

```
This complex query though might better be represented by a `StringQuery` if you wish:
```java

StringQuery<QueryModelReturnType> query = new StringQuery("SELECT *, ( (pLatitude - ?) * (pLatitude - ?) + (pLongitude - ?) * (pLongitude - ?) ) as distance from shops ORDER BY distance");
query.setSelectionArgs(new String[]{latitude, latitude, longitude, longitude}); // this might be only in 4.0+
List<QueryModelReturnType> list = query.queryCustomList(QueryModelReturnType.class); 
// since you return different columns in query add a query model. 
```

**Comment by jurmeneta** [comment]
Thanks for your answer agrosner!

I implemented successfully your explanation, but the point is that I'm naming the arithmetic operation as "distance" and the resulted model has a field also named "distance" and when I sort the rows according to this field the rows are not sorted.

It seems that the sort doesn't take in account the arithmetic results, because if I change the operation name to, for instance, "dist" and I sort the rows by "dist" it works properly.

Any idea about what's happening?

Thanks!

**Comment by agrosner** [comment]
not sure. A stackoverflow question wouldnt hurt on that.
