### ISSUE TITLE
Generated class can't be compiled with model which has "@Nullable Float" field

### ISSUE THREAD

**Issue by ultraon** [Raizlabs/DBFlow#1324]
DBFlow Version: 4.0.3
Issue Kind: Bug

Description: 

With version 4.0.3 models with "@ Nullable Float field" (not primitive "float") can't be compiled in generated class <MODEL_NAME>_Table, because
DatabaseStatement.bindDoubleOrNull(...) method uses "Double" (not primitive "double" as with bindDouble(...) method) and "Float" can't be casted to "Double" (but "float" to "double" can). I think to resolve this issue it needs an additional method as "DatabaseStatement.bindFloatOrNull(...)"

**Comment by agrosner** [comment]
good catch. will fix for 4.0.4

**Comment by agrosner** [comment]
fixed in `develop`.
