### ISSUE TITLE
Better way to upgrade to 4.0.4 from 3.X.X

### ISSUE THREAD

**Issue by sigfridod** [Raizlabs/DBFlow#1327]
DBFlow Version:
Issue Kind (Bug, Question, Feature):

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

I have been using DBFlow from last 6 months for one of my project since it was version 3.x.x when I integrated pls suggest the best way to migrate it to latest version

as I have used foreignkeycontainer a lot

**Comment by agrosner** [comment]
look at https://agrosner.gitbooks.io/dbflow/content/Relationships.html under "Stubbed Relationships". They are more convenient than using `ForeignKeyContainer` objects.
