### ISSUE TITLE
Boxed primitives columns breaking change

### ISSUE THREAD

**Issue by baranowskinet** [Raizlabs/DBFlow#1329]
DBFlow Version: 4.0.3
Issue Kind Bug/Question

After update from 4.0.0 beta I had massive problem with Double, Integer defaults. Before update i had nulls as I expected as I am using boxing primitive. I didn't use annotation for that columns to notify that columns allow null as boxing type should be enough. Now that columns return zeros which cause a lot of issue in existing code. In generated class I see in loadFromCursor method:
model.setLatitude(cursor.getDoubleOrDefault("Latitude"));
which set double not Double which means it convert null to 0.

Should I back to older version? Annotation should solve issue (@Nullable doesn't help for now), also property set assignDefaultValuesFromCursor to false not solviing issue.

Could someone help me how to get nullable Double, Integer etc, or should I come back to older version?

**Comment by ultraon** [comment]
Use https://github.com/Raizlabs/DBFlow/releases/tag/4.0.4 (4.0.4) version with fix

**Comment by baranowskinet** [comment]
I tried version 4.0.4 but it doesn't fix issue, I am back to ver 4.0.0-beta5 and then generate code is ok:

int index_Latitude = cursor.getColumnIndex("Latitude");
    if (index_Latitude != -1 && !cursor.isNull(index_Latitude)) {
      model.setLatitude(cursor.getDouble(index_Latitude));
    }

or I did something wrong in 4.0.4. Could you confirm that 4.0.4 can return null for Doulbe column type in generated loadFromCursor method?

**Comment by baranowskinet** [comment]
Thank you very much for help, I didn't noticed fix on first time as I had set property assignDefaultValuesFromCursor for table. Once I removed it code looks now ok:

model.setLatitude(cursor.getDoubleOrDefault("Latitude", null));
