### ISSUE TITLE
How to add tableendpoint to @table?

### ISSUE THREAD

**Issue by jiqimaogou** [Raizlabs/DBFlow#133]
the document say:
Or Add the annotation to a @Table and specify the content provider class name (ex. TestContentProvider)

it means add @tableEndpoint at a model class which is annotated with @table?

can you give me some example code?

if I just add @TableEndPoint in a model class, the compiler say you must has at least one TableEndPoint.

If I just specify @TableEndPoint contentProviderName, it say missing value for @TableEndPoint, the value is the table name, but I have specify the table name in @table, it would know the table name in the model class.

**Comment by jiqimaogou** [comment]
Ollie generate contentprovider is easy, not need to give the model content uri.

**Comment by agrosner** [comment]
addedd example in `2.0.0`.

**Comment by agrosner** [comment]
added example in `2.0.0`
