### ISSUE TITLE
Need to recompile 4.0.4 version on JitPack

### ISSUE THREAD

**Issue by ultraon** [Raizlabs/DBFlow#1330]
There was known compilation bug on the JitPack 09.06.17 (Friday) with Android project, so the build with tag 4.0.4 was not compiled successfully (https://jitpack.io/com/github/Raizlabs/DBFlow/4.0.4/build.log ). Could you please re-tag version for re-compilation on JitPack.
To resolve this issue temporary we can use version (hash of the commit) instead version number: 43dd2f67eb.
Example:
`compile "com.github.Raizlabs.DBFlow:dbflow:43dd2f67eb"`

**Comment by baranowskinet** [comment]
I am not sure if it is related but I had problem with compile 4.0.4 also and make url lower case solved problem: 
compile "com.github.raizlabs.dbflow:dbflow-core:${dbflow_version}"

**Comment by wang9090980** [comment]
Make url lower case solved problem:
  annotationProcessor "com.github.raizlabs.dbflow:dbflow-processor:${dbflow_version}"
  compile "com.github.raizlabs.dbflow:dbflow-core:${dbflow_version}"
  compile "com.github.raizlabs.dbflow:dbflow:${dbflow_version}"
  compile "com.github.raizlabs.dbflow:dbflow-rx2:${dbflow_version}"
