### ISSUE TITLE
ID from stubbed relationship

### ISSUE THREAD

**Issue by arvola** [Raizlabs/DBFlow#1331]
DBFlow Version: 4.0.4
Issue Kind: Question
Description: 
I have a one-to-many relationship similar to the queen and ants example, with the ant having `@ForeignKey(stubbedRelationship = true) var queen: Queen? = null`.

I want to get a two-dimensional list (ie. a list of queens, and each of them having their list of ants). If I just query for the Queens and have them load all ants, that can be quite a few queries. The best approach in my mind is to do two queries, one for the queens, and another for the ants, and then map them. I'm OK with 2 queries, which is always going to be less than N queries. A join would also work, but to my knowledge that would mean using a Query Model and mapping it out from there, which seems like a worse solution.

My question: is there a way to get the queen_id from the stubbed relationship without loading the Queen?

**Comment by agrosner** [comment]
when it's stubbed we don't load the full object. It instantiates the object and fills it only with referenced fields. if its a single `@ForeignKey` you can replace the object with the type of the field it references such as an `int`. If there was an abstraction (aka `ForeignKeyContainer`), it would be just as efficient as this way, since we would create a new object anyways for every ant.

**Comment by agrosner** [comment]
or! have your ant model implement `LoadFromCursorListener`, and load the field from the `Cursor` manually.
```java
public interface LoadFromCursorListener {

    /**
     * Called when the {@link Model} is loaded from the DB.
     *
     * @param cursor The cursor that is loaded.
     */
    void onLoadFromCursor(@NonNull Cursor cursor);
}
```

**Comment by arvola** [comment]
@agrosner Appreciate the responses. Do you think it'd be safe to just use the `ant.queen.rowid` that gets set when the ants are loaded from the cursor? I realize it might change if the primary keys change. I'm not concerned about the created objects at this point, just the number of queries.

Otherwise, I think the `LoadFromCursorListener` approach would work too, a little more boilerplate, but not excessive.

Thanks again!

**Comment by agrosner** [comment]
yes you can safely reference any of the primary keys on a stubbed object no problem. Just be careful as the reference may be null if the cursor or reference doesnt exist.

**Comment by agrosner** [comment]
if you need the full object, you can call `load()`.

**Comment by sigfridod** [comment]
@agrosner  saw that the issue get resolved, But it would be good if load() return the object of table like foreignkeycontainer was doing well, it will help to migrate 3.3+ version code to newer version easier
