### ISSUE TITLE
Deleting stubbed foreign key only works through model.delete()

### ISSUE THREAD

**Issue by iamareebjamal** [Raizlabs/DBFlow#1332]
DBFlow Version: 4.0.4
Issue Kind (Bug, Question, Feature): Bug

Description: Currently, after setting up everything correctly, 
1. Enabling foreign key constraints
```Java
@Database(
    name = OrgaDatabase.NAME,
    version = OrgaDatabase.VERSION,
    insertConflict = ConflictAction.IGNORE,
    updateConflict= ConflictAction.REPLACE,
    foreignKeyConstraintsEnforced = true
)
```
2. Defining all correct annotations to the foreign key in model
```Java
@ForeignKey(
    stubbedRelationship = true,
    saveForeignKeyModel = true,
    deleteForeignKeyModel = true,
    onDelete = ForeignKeyAction.CASCADE)
@SerializedName("user_detail")
private UserDetail userDetail;
```
3. Defining a primary key in foreign model
```Java
@Table(database = OrgaDatabase.class, allFields = true)
public class UserDetail extends BaseModel {

    @PrimaryKey(autoincrement = true)
    private int id;

    private String contact;
    private String twitter;
    @SerializedName("firstname")
    private String firstName;
    private String avatar;
    private String facebook;
    @SerializedName("lastname")
    private String lastName;
    private String details;
}
```

I'm only able to delete the foreign key model from database by calling `user.delete()`

Both of these methods don't work ->
1. `Delete.table(User.class);`
2. `SQLite.delete().from(User.class).execute()`

I have to resort to this to actually delete the user and userdetails

<details><summary>Click to see code</summary><p>

```
User user = new User();
UserDetail userDetail = new UserDetail();
user.setUserDetail(userDetail);
user.setId(2);
user.setEmail("jamal.areeb@gmail.com");
user.setLastAccessTime("lol");
user.setSignupTime("bawa");
userDetail.setFirstName("Areeb");
userDetail.setLastName("Jamal");
userDetail.setDetails("A B  C D");

user.save();

databaseRepository.getAllItems(UserDetail.class).subscribe(user1 -> {
    System.out.println("Detail : " + user1);
});

List<User> users =  SQLite.select().from(User.class).queryList();

for (User user1 : users) {
    user.delete();
}

databaseRepository.getAllItems(UserDetail.class).subscribe(user1 -> {
    System.out.println("Detail : " + user1);
});
```
</p>
</details>

**Comment by agrosner** [comment]
the `user.delete()` works because you specify the `deleteForeignKeyModel = true,` on the `UserDetail`. If you call delete from a wrapper query, you need to clear out your `UserDetail` object fields from the current objects loaded in memory. And by "Both of these methods don't work ->" can you be more specific.

**Comment by iamareebjamal** [comment]
Both of these methods don't work ->

Delete.table(User.class);
SQLite.delete().from(User.class).execute()


By this, I meant that none of these methods delete the UserDetail table on deleting of the user. And I have no reference to it in the memory too
I have checked this using several unit tests

We need to clear all user referencing models when we delete the user and right now it is only possible to so by either calling user.delete() or manually clearing out tables

We are not using BaseModel as parent class to our model, so it is not possible for us to use delete method on model

**Comment by agrosner** [comment]
you can use `FlowManager.getModelAdapter(User.class).deleteAll(models)`

**Comment by agrosner** [comment]
and I believe the `@ForeignKey` parent needs to get deleted for it to cascade to the `User` table. So defining a foreign key on the `User` table is reverse of what you're thinking. If you delete `UserDetail` itll cascade to the `User` table.

**Comment by iamareebjamal** [comment]
OK :+1:
