### ISSUE TITLE
DirectModelNotifier.OnModelStateChangedListener  callback twice

### ISSUE THREAD

**Issue by wang9090980** [Raizlabs/DBFlow#1335]
DBFlow Version:4.0.4
Issue Kind (Bug, Question, Feature):

When I execute save() method,  OnModelStateChangedListener CallBack  twice

Description: 

> I found   NotifyDistributor.get().notifyModelChanged(model, modelAdapter, BaseModel.Action.SAVE);
> method call twice.

![image](https://user-images.githubusercontent.com/6111077/27178484-f9d150d4-51fc-11e7-9884-b6571c0f8420.png)

```
  DirectModelNotifier.OnModelStateChangedListener<Colony> modelChangedListener = new DirectModelNotifier
            .OnModelStateChangedListener<Colony>() {
        @Override
        public void onModelChanged(
                @NonNull Colony model, @NonNull BaseModel.Action action) {
            Log.d("TAG", "-------Colony changed-----" + model.toString());

        }

    };
```

**Comment by agrosner** [comment]
`INSERT` and `SAVE` get called both at once because they technically are the same. You might want to listen for a `SAVE` vs. an `INSERT`. a `SAVE` is a catch all for both insert and update. In certain situations you might only be listening for `INSERT` and not `UPDATE`.

**Comment by wang9090980** [comment]
Thank you !
