### ISSUE TITLE
Prefetch at runtime and backlinks feature

### ISSUE THREAD

**Issue by sigfridod** [Raizlabs/DBFlow#1337]
DBFlow Version:
Issue Kind (Bug, Question, Feature):

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description:

**Comment by agrosner** [comment]
please provide more infomation.

**Comment by sigfridod** [comment]
@agrosner  meaning if I have person and address table with one to many relationship
than I should be able to get addresses from person table and from address i can get person without firing any database query

**Comment by agrosner** [comment]
not supported. going "back" from one to many still queries DB for the same model if its a `@ForeignKey` object. We dont do any efficient operations on that.
