### ISSUE TITLE
Best way to clear table?

### ISSUE THREAD

**Issue by henorek** [Raizlabs/DBFlow#1338]
DBFlow Version: 4.0.4
Issue Kind (Bug, Question, Feature): Question

Description: 
Hi there! I wonder about the best way to clean the table. Currently I iterate over all objects in table and delete them, like this
`(select from Model::class).queryList().forEach { it.delete() }`
but this solution seems to be a little bit hacky.

**Comment by AllanWang** [comment]
I have the following
```

**Comment by agrosner** [comment]
you can do `Delete.table(MyTable.class)`
