### ISSUE TITLE
Generated ViewTable classes have duplicated property fields.

### ISSUE THREAD

**Issue by brwskitime** [Raizlabs/DBFlow#1340]
DBFlow Version: 4.0.4
Issue Kind (Bug, Question, Feature): Bug

Description: 

I have 3 views. At v 3.1.1 they generate fine. But now each generated class has every property field duplicated, so they don't compile. 
 
I created a bare-bones project that reproduces the issue. 
[TestViews.zip](https://github.com/Raizlabs/DBFlow/files/1091873/TestViews.zip)

**Comment by brwskitime** [comment]
I'm not  using kotlin or any of the other bells/whistles. 

Just:

    // dbflow
    annotationProcessor 'com.github.Raizlabs.DBFlow:dbflow-processor:4.0.4'
    compile 'com.github.Raizlabs.DBFlow:dbflow-core:4.0.4'
    compile 'com.github.Raizlabs.DBFlow:dbflow:4.0.4'

**Comment by julienmeyer** [comment]
We have the same problem (since 4.0 beta7 to 4.0.4).

**Comment by agrosner** [comment]
fixed for 4.0.5
