### ISSUE TITLE
Fatal JRE crash when upgrading to 4.0.4

### ISSUE THREAD

**Issue by danvwells** [Raizlabs/DBFlow#1342]
DBFlow Version: 4.0.4
Issue Kind: Question I guess...
Description: 

Our app was still on 4.0.0-beta7, so I attempted to update to 4.0.4.  While running the unit tests on our headless build (or on command line myself using "./gradlew test"), we get a JRE fatal error (see below).  Rolling back to 4.0.0-beta7 it works fine.  Many of our tests exercise our use of DbFlow - basically integration tests of our logic and data access code.  I tried 4.0.0, but couldn't download from jitpack per known issue, tried 4.0.1, which broke cuz of enums per known issue, and then both 4.0.2 and 4.0.3 resulted in the same fatal error.  The fatal error occurs at least when using jdk 1.8.0_122 and 1.8.0_131, but NOT in jdk 1.8.0_25 (older).  Our tests run fine in Android Studio, unless using the gradle tasks to run them.  I can run the tests in dbflow-tests using the same approach without getting that error, although 102 of the tests fail (master branch as of yesterday).

I'm not yet sure where the issue really lies - probably a JDK bug (I am reporting it to Oracle as well), but it seems to be triggered by something in DBFlow.  

Anyone run into this?  Anyone have any ideas?  Anyone know how to further trace this fatal error (see below)?

<pre>
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010286f6b6, pid=46936, tid=0x0000000000004d03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x46f6b6]  Node::uncast() const+0x4
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/<me>/<path to my project>/app/hs_err_pid46936.log
#
# Compiler replay data is saved as:
# /Users/<me>/<path to my project>/app/replay_pid46936.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
</pre>

**Comment by simon-the-canadian** [comment]
I'm in the exact same situation. For me the JVM takes a dump after about 600 tests (each test initialize and tear down DBFlow). I've tried allocating more memory to the JVM as suggested by https://groups.google.com/forum/#!topic/robolectric/u6mxcSmSOW8. That didn't work though. I'm not sure what would have changed in 4.0.4 that would cause this. 4.0.3 doesn't cause that problem.

**Comment by simon-the-canadian** [comment]
@danvwells Have you had any issues with random ANRs in production when saving models using 4.0.0 beta 7?

**Comment by danvwells** [comment]
@simon-the-canadian No, I haven't.  We actually haven't released this app I'm working on just yet.  The app we have in production that uses DBFlow is still on 3.1.1.  Sorry I'm no help there.

**Comment by danvwells** [comment]
btw, here is the Oracle bug report: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8183200

**Comment by agrosner** [comment]
```
Without reproducer it is difficult to find the root cause.
But it looks similar issue has already fixed in JDK9 (http://jdk.java.net/9/ ) as part of https://bugs.openjdk.java.net/browse/JDK-8134321. 
You can verify the issue on 9 and share your feedback with us.
````
lol if only we can verify with Java9 on Android..

**Comment by agrosner** [comment]
looks like a JDK issue, not a dbflow issue.

**Comment by danvwells** [comment]
@agrosner yep, but dbflow 4.0.4+ exposes the issue, so I had wondered if anyone else using dbflow had discovered this and found a work-around.

**Comment by danvwells** [comment]
@agrosner I'm revisiting this and trying to build the dbflow artifacts myself to see if different versions of javac impact this.  I'm having some troubles and wondered if you could explain what you do to build?  Running "gradle install" fails with "Execution failed for task ':dbflow-kotlinextensions:transformResourcesWithMergeJavaResForRelease'.
> More than one file was found with OS independent path 'META-INF/dbflow-kotlinextensions_release.kotlin_module'"

Thanks for any help

**Comment by danvwells** [comment]
uh... ok, whoops, "gradle clean install" works fine.  my bad.

**Comment by danvwells** [comment]
We've come back to this as it is preventing us from upgrading, and we know much more about the cause.

1) The commit that introduced the issue for us is c7004e435444cfba6109cc2ba05a8a21d91a59f7 - the introduction of FlowCursor.

2) I noticed in the hs_err_pid...log file that was created the "Current CompileTask" was FlowCursor::getStringOrDefault(), so I tried changing all overloads of that method to implement their logic themselves, no forwarding to other methods (a hunch based on the next data point).  Then I built locally and tried that build with my app, and the crash does not happen.

3) The latest hs_err_pid log file generated from the crash had a bit of a lower level stack trace this time from the JVM that showed the crash happened while trying to inline the function (hmmm, JIT compiler?)

4) Then we tried again, with a legit version of DBFlow (not a local build), but added the test options below to our build.gradle, and it worked consistently without crashing.  However, the build runs about 3 times slower of course.
```
    testOptions {
        unitTests.all {
            jvmArgs '-Djava.compiler=NONE'
        }
    }
``` 

So we can work around the issue this way, but hopefully Oracle will fix their JIT soon.  Also, hopefully the Dalvik/ART JIT stuff doesn't have a similar issue.

**Comment by danvwells** [comment]
This actually works around it without impacting the build performance as much.  Our build time is just about the same, plus doesn't crash with this.

```
    testOptions {
        unitTests.all {
            jvmArgs '-XX:MaxInlineSize=0'
        }
    }
```

**Comment by simon-the-canadian** [comment]
@danvwells what version of Java are you using for running your unit tests? I tried both options: `jvmArgs '-XX:MaxInlineSize=0'` and `jvmArgs '-Djava.compiler=NONE'`. None of those worked for me. I'm also using open JDK that comes built in with Android Studio 2.3.3.

**Comment by danvwells** [comment]
@simon-the-canadian I believe our version is 1.8_131 now (don't currently have access to it, but I could check tomorrow).  If you are running your tests within Android Studio, the testOptions in your build.gradle file don't apply (I know, right?).  Instead, create a JUnit runtime configuration and put ```-XX:MaxInlineSize=0``` in the VM Options field.

**Comment by simon-the-canadian** [comment]
Crazy, I would have thought it would run the test options in the build.gradle file. I put that in my test configuration and now all my tests run. Thank you.
