### ISSUE TITLE
@NotNull on ForeignKeyContainer

### ISSUE THREAD

**Issue by santa010** [Raizlabs/DBFlow#1344]
DBFlow Version: 3.1.1
Issue Kind: Question

I am trying to have a @NotNull constraint on a ForeignKeyContainer like so:
```
@Table(database = Database.class)
public class TestClassB extends BaseModel {

    @PrimaryKey
    @NotNull
    String cid;

    @NotNull
    @Column
    String displayName;

    @NotNull
    @ForeignKey
    ForeignKeyContainer<TestClassA> testClassA;
}
```
but the generated TestClassB creation query (from the TestClassB_Adapter) seems to be missing the NOT NULL constraint for the foreign key:

> "CREATE TABLE IF NOT EXISTS `TestClassB`(`cid` TEXT NOT NULL,`displayName` TEXT NOT NULL,`testClassA_uid` TEXT, PRIMARY KEY(`cid`)"+ ", FOREIGN KEY(`testClassA_uid`) REFERENCES " + FlowManager.getTableName(TestClassA.class) + "(`uid`) ON UPDATE NO ACTION ON DELETE NO ACTION" + ");"

Am I doing something wrong or is this a bug?

**Comment by agrosner** [comment]
no its not a bug, but an enhancement. Currently foreign key fields don't support `NOT NULL` on individual references.

**Comment by agrosner** [comment]
will be 4.1.0. in `develop`.
