### ISSUE TITLE
Best way to migrate from 3.1.1 to 4.0.4

### ISSUE THREAD

**Issue by rspl17** [Raizlabs/DBFlow#1346]
DBFlow Version:
Issue Kind (Bug, Question, Feature):

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

I have been using 3.1.1 version and having too many foriegnkeycontainer
current version doesn't support foriegnkeycontianer any best for this kind of migration ?

**Comment by agrosner** [comment]
ForeignKeyContainer is replaced with `@ForeignKey(stubbedRelationship = true)`. Use Model.load() to get same functionality as before, without the confusion. Meaning that you can remove the `ForeignKeyContainer` objects and reference the actual object. Just ensure if you need all of its data, call `load()` before using.
