### ISSUE TITLE
Add AND & OR functions from OperatorGroup to Kotlin OperatorExtensions

### ISSUE THREAD

**Issue by epetrenko** [Raizlabs/DBFlow#1351]
DBFlow Version: 4.0.4
Issue Kind (Bug, Question, Feature): Feature

Description: Is it possible to add a couple of infix functions to Kotlin OperatorExtensions? 

I mean AND / OR functions from OperatorGroup:
```
@NonNull
public OperatorGroup or(SQLOperator sqlOperator) {
   return operator(Operation.OR, sqlOperator);
}

@NonNull
public OperatorGroup and(SQLOperator sqlOperator) {
    return operator(Operation.AND, sqlOperator);
}
```

Something like that:
```
infix fun OperatorGroup.and(sqlOperator: SQLOperator) = OperatorGroup.clause(this).and(sqlOperator)
infix fun OperatorGroup.or(sqlOperator: SQLOperator) = OperatorGroup.clause(this).or(sqlOperator)
```

It could help to combine several conditions into a single OperatorGroup (second part of WHERE expression in the following example):
```
(select from Task::class innerJoin Task_Employee::class
    on (Task_Table.id eq Task_Employee_Table.task_id)
    where (Task_Employee_Table.employee_id eq employeeId.property)
    and (Task_Table.dateComplete.isNull and
        Task_Table.appointmentDate.isNull or
        (Task_Table.dateComplete between startDate and endDate) or
        (Task_Table.appointmentDate between startDate and endDate))).list
```

**Comment by agrosner** [comment]
don't you want the `OperatorGroup` to just add to itself, instead of defining another `OperatorGroup` for each new added one?
```kotlin

infix fun OperatorGroup.and(sqlOperator: SQLOperator) = and(sqlOperator)
infix fun OperatorGroup.or(sqlOperator: SQLOperator) = or(sqlOperator)

```

**Comment by agrosner** [comment]
currently the problem I think with Kotlin (a bug) is you cannot define a more "refined extension" overload:
```kotlin
infix fun OperatorGroup.and(sqlOperator: SQLOperator) = and(sqlOperator)
infix fun OperatorGroup.or(sqlOperator: SQLOperator) = or(sqlOperator)

infix fun OperatorGroup.and(sqlOperator: OperatorGroup) = clause(this).and(sqlOperator)
infix fun OperatorGroup.or(sqlOperator: OperatorGroup) = clause(this).or(sqlOperator)
```
in this case the `SQLOperator` (top-level instance) is still chosen over the `OperatorGroup`. I want the behavior to be that if you use infix on a group, it creates a new clause with current group and new group. If you infix to a single `SQLOperator` it should append to existing `OperatorGroup`.

**Comment by agrosner** [comment]
so for now I will keep this out of the lib since its just two lines of code and will revisit by filing a kotlin issue about this.

**Comment by agrosner** [comment]
so i am adding an extension, called `SQLOperator.clause()` that turns the object into a clause via:
```kotlin
(select from Task::class innerJoin Task_Employee::class
            on (Task_Table.id eq Task_Employee_Table.task_id)
            where (Task_Employee_Table.employee_id eq employeeId.property)
            and (Task_Table.dateComplete.isNull and
            Task_Table.appointmentDate.isNull or
            (Task_Table.dateComplete between startDate and endDate).clause() or
            (Task_Table.appointmentDate between startDate and endDate).clause())
```
which will give you what you want.

**Comment by agrosner** [comment]
in `develop`.

**Comment by epetrenko** [comment]
Thanks for your response. 

> don't you want the OperatorGroup to just add to itself, instead of defining another OperatorGroup for each new added one?

```kotlin
infix fun OperatorGroup.and(sqlOperator: SQLOperator) = and(sqlOperator)
infix fun OperatorGroup.or(sqlOperator: SQLOperator) = or(sqlOperator)
```

I think that it's exactly what I asked about. Actually I don't need separate `clause()` here - `(Task_Table.dateComplete between startDate and endDate)` and here -
 `(Task_Table.appointmentDate between startDate and endDate)` in my above example.

Btw, current implementation (from [OperatorExtensions.kt](https://github.com/Raizlabs/DBFlow/blob/master/dbflow-kotlinextensions/src/main/java/com/raizlabs/android/dbflow/kotlinextensions/OperatorExtensions.kt)) gives us possibility to call infix `add()` / `or()` only for single operator, which means that we can combine only two single operators using infix syntax:
```kotlin
infix fun <T : Any> Operator<T>.and(sqlOperator: SQLOperator) = clause(this).and(sqlOperator)
infix fun <T : Any> Operator<T>.or(sqlOperator: SQLOperator) = clause(this).or(sqlOperator)
```
For example:
```kotlin
(Task_Table.dateComplete.isNull and Task_Table.appointmentDate.isNull)
```

But if we want to combine more than two operators into `OperatorGroup` via infix functions, compiler won't let us to do this (because second `and()` call related to `OperatorGroup`, not to `Operator`):
```kotlin
(Task_Table.dateComplete.isNull and Task_Table.appointmentDate.isNull and Task_Table.dateUpdate.isNull)
```
