### ISSUE TITLE
Mutliple FastStoreModelTransaction in Transaction

### ISSUE THREAD

**Issue by baranowskinet** [Raizlabs/DBFlow#1352]
DBFlow Version: 4.0.4
Issue Kind (Bug, Question, Feature): Bug, Question

In my application I need to update many different models in one time. To do that I'm using suggested transaction method
```       
DatabaseDefinition appDatabase = FlowManager.getDatabase(SystemDatabase.class);
appDatabase.beginTransactionAsync(new ITransaction() {...}).build().execute();
```
and pass databaseWrapper to  multiple FastStoreModelTransactions:
```                
FastStoreModelTransaction
                        .insertBuilder(FlowManager.getModelAdapter(table))
                        .addAll(list)
                        .build()
                        .execute(databaseWrapper);
```
I am using insertBuilder, deleteBuilder and saveBuilder depend if I need just insert, delete or update. On the end I also prepare standard model.save(databaseWrapper). All of that is in one transaction and based on my tests I can say it works but I still got many warning related to not close cursor. So, now I am not sure if all of that is right or should I do it in different way. I noticed many issues like #1156, #1050, #706 which are either closed or not solved. I have the same warning `Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor` which worries me and I can't find solution for it. 

I tried using standard lookup to save each instance of model but it is really slow when I compare it to FastStoreModelTransaction. This warning happen not all the time but always when I have to update many different records (1000+ in 25 different models) in one transaction. I need use transaction to keep data integrity but none of my models has relations.

**Comment by agrosner** [comment]
quick question, what version of Android are you using?

**Comment by agrosner** [comment]
that error doesn't exist on Android higher than 4.0.1 it seems and only in SQLCipher. I believe that the `update` method was the issue as the used updateStatement was not closed after use.

**Comment by agrosner** [comment]
try using `6799aa375d` as your dependency.

**Comment by baranowskinet** [comment]
Quick check your changes and it seems to work without warnings! I am working on Android Lolipop and sqlCipher 3.5.4.
Of course I will test it more but so far so good and no issues. For me it is great news ;) and only one problem left - close database file to able open different database file with the same structure (class). 

Anyway thank you very much for responding and fixing!

**Comment by agrosner** [comment]
in `develop` then. for 4.0.5
