### ISSUE TITLE
BaseSyncableProviderModel.insert() is inserting two records

### ISSUE THREAD

**Issue by samuelkister** [Raizlabs/DBFlow#1353]
DBFlow Version: 4.0.4
Issue Kind (Bug, Question, Feature): Bug ?

Description: 
when running `myModel.insert()` where myModel extends BaseSyncableProviderModel, two identical records (except the autoincrement key) are created in the DB.

in `BaseSyncableProviderModel.insert()`, two different inserts are called :
`public long insert() {`
`    long rowId = super.insert();`
`    ContentUtils.insert(getInsertUri(), this);`
`    return rowId;`
`}`

**Comment by agrosner** [comment]
`BaseSyncableProviderModel` is best used in scenarios where you are going out to a remote content provider (another app's process) and need to keep track of information. You can switch to using `BaseProviderModel` instead for this case if your `ContentProvider` is acting as your storage.
