### ISSUE TITLE
FlowContentObserver Crash on Android O

### ISSUE THREAD

**Issue by simon-the-canadian** [Raizlabs/DBFlow#1356]
DBFlow Version: 4.0.3
Issue Kind (Bug, Question, Feature): Bug/Question

Description: 
Calling registerForContentChanges() on FlowContentObserver causes 
`java.lang.SecurityException: Failed to find provider `TimeEntry_Model` for user 0; expected to find a valid ContentProvider for this authority`

This link explains the change in Android O
https://developer.android.com/preview/behavior-changes.html#ccn

In debugging I found that the Uri DBFlow uses for my model is dbflow://%60TimeEntry_Model%60  I've tried adding that to the authorities property for my content provider in the android manifest file. I also tried adding `TimeEntry_Model`. However, I always get the same crash. 
My question is does this change in Android require something to change in DBFlow, or am I just not  specifying the correct authority for my database model?

**Comment by CapnSpellcheck** [comment]
It says "if you are targeting Android O"
...So you could keep your target *below* O, for now.

**Comment by SjoerdvGestel** [comment]
is this still an issue?

**Comment by SjoerdvGestel** [comment]
This is a real issue now, here's the change described > https://developer.android.com/about/versions/oreo/android-8.0-changes.html#ccn

**Comment by SjoerdvGestel** [comment]
@agrosner are u aware of this issue on android oreo?

**Comment by SjoerdvGestel** [comment]
I've managed to work around the issue on Oreo by not using the FlowContentObserver any more, the uri's it generate throw the SecurityExceptions on compileSdkVersion 26. Using DirectModelNotifier did give me the needed callbacks on data changes.

**Comment by CapnSpellcheck** [comment]
So it's not possible to keep your targetSdk below the compileSdk? I was
curious about this.

On Wed, Sep 20, 2017 at 9:59 AM, Sjoerd van Gestel <notifications@github.com

**Comment by SjoerdvGestel** [comment]
@CapnSpellcheck No, thats not possible for us.

**Comment by SjoerdvGestel** [comment]
observeOnTableChanges in the RX implementation also don't seem to work anymore on Oreo

**Comment by surajm097** [comment]
This is kinda a breaking issue, since Android 8.0 has been out for a while. Is there any indication when this issue will be fixed?

**Comment by CapnSpellcheck** [comment]
@surajm097 @simon-the-canadian According to the docs you will only have a problem if you target 26. Do either of you confirm this? If this is true, that would significantly reduce the severity, as most apps don't need to target 26.
(Note, I do not work on this project)

**Comment by simon-the-canadian** [comment]
@CapnSpellcheck You're right that its only an issue if you target api 26. I'm not targeting that api yet mainly because of this crash. I'm not in a huge hurry to target 26 either, but it would be nice to have this addressed some time in the near future.

**Comment by SjoerdvGestel** [comment]
This bug is preventing usage of the lifecycle logic added as default in support v26 witch can't be used without targetSdkVersion 26, this now became blocking for us.

**Comment by agrosner** [comment]
```
These APIs now require that a valid ContentProvider is defined for the authority in all Uris. Defining a valid ContentProvider with relevant permissions will help defend your app against content changes from malicious apps, and prevent you from leaking potentially private data to malicious apps.


```
meaning if you do not provide a `ContentProvider` that has the authority you're targeting then you cannot use the default `ContentResolverNotifier` anymore. I will have to introduce a breaking change in DBFlow in order to switch over default to `DirectModelNotifier`. For now your best option to switch to the direct option. I may have to deprecate `ContentResolverNotifier` in a near-future release in order to have people switch over as some may not be aware they're using it.

**Comment by WonderCsabo** [comment]
@agrosner `DirectModelNotifier` lacks a feature of `FlowContentObserver`: batched notifications (including `notifyAllUris = false`). It should be added to it if you deprecate  `FlowContentObserver`.

**Comment by sirekanyan** [comment]
@agrosner, are there any workarounds for this issue? When this issue is planned to be fixed?

I've added generation of [external content provider](https://github.com/teocci/AndroidGuidenotes/wiki/DBFlow-Guide#exposing-content-providers) and added a provider to my manifest (with grantUriPermissions="true"). Now my data is available with content://com.sample/MyEntity uri. But FlowContentObserver still needs dbflow://\`MyEntity\` to be accessed. Is it possible in this case to write my own ModelNotifier which will work with uris like content://? Have you any other ideas for workaround?

Guys, @WonderCsabo, @simon-the-canadian, how do you deal with it?

Thank you, I'll appreciate any help with this issue.

**Comment by volser** [comment]
Any progress?

need to change this method
```
public static Uri getNotificationUri(@NonNull Class<?> modelClass,
                                         @NonNull Action action,
                                         @Nullable SQLOperator[] conditions) {
        Uri.Builder uriBuilder = new Uri.Builder().scheme("dbflow")
            .authority(FlowManager.getTableName(modelClass));
        if (action != null) {
            uriBuilder.fragment(action.name());
        }
        if (conditions != null && conditions.length > 0) {
            for (SQLOperator condition : conditions) {
                if (condition != null) {
                    uriBuilder.appendQueryParameter(Uri.encode(condition.columnName()), Uri.encode(String.valueOf(condition.value())));
                }
            }
        }
        return uriBuilder.build();
    }```

**Comment by agrosner** [comment]
fixed. https://github.com/Raizlabs/DBFlow/releases/tag/4.2.0

**Comment by WonderCsabo** [comment]
@agrosner you could add the content provider to the `dbflow` project manifest, so client could automatically get it via manifest merging.

**Comment by agrosner** [comment]
Yes. I do not want to force consumers on it. If it's exported there could be collisions in Android os that will prevent installing. If I included it in the library, most devs might not be aware it was there and get bug reports later about it.
