### ISSUE TITLE
Prepacked database

### ISSUE THREAD

**Issue by rhespanhol** [Raizlabs/DBFlow#136]
I have a small question.
 Im using a prepacked database and when the app starts i need to insert new content to the database but sometimes the database has not finished copying. Is there any listener so that the app could know when the database has finished copying or if something went wrong?

**Comment by agrosner** [comment]
try placing what you need in a ```Migration``` for version 1 of the database. I would add logic to ensure this doesn't get called twice as migrations occur on both ```onCreate()``` and ```onUpgrade()``` of the ```FlowSQLiteOpenOpenHelper```.  Or you can call ```FlowManager.getDatabase(databaseName).getWriteableDatabase()``` to jump start the process of copying over the prepackaged database before you insert new content.

**Comment by rhespanhol** [comment]
Im keep getting this error

<code>
java.lang.RuntimeException: android.database.sqlite.SQLiteConstraintException: columns latitude, longitude, mId are not unique (code 19)
            at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:77)
</code>

when i try to do:

<code>
TransactionManager.getInstance().update(ProcessModelInfo.withModels(spot.getmSpotCordinates()));
</code>

I think that im inserting data before the prepacked is fully copied so if a repeated line is copied after, this error occurs

**Comment by agrosner** [comment]
that appears you are updating or inserting data that does already exists. Are those columns primary keys or unique? You can define either global defaults for your ```@Database``` or specific ```@Table``` using ```insertConflict()``` and ```updateConflict()```. In this case you may want to use ```ConflictAction.REPLACE```. Anyways check it out here: https://github.com/Raizlabs/DBFlow/blob/master/usage/DBStructure.md

**Comment by rhespanhol** [comment]
Yes, those are primary keys. here is my table

<code>
@Table(insertConflict = ConflictAction.REPLACE)
public class Coordinate extends BaseModel implements Parcelable{

    public Coordinate() {
        super();
    }

    @Column(columnType = Column.PRIMARY_KEY)
    @Expose
    @SerializedName("geo_lat")
    public double latitude;

    @Column(columnType = Column.PRIMARY_KEY)
    @Expose
    @SerializedName("geo_lng")
    public double longitude;

    @Column(columnType = Column.PRIMARY_KEY)
    @Expose
    @SerializedName("id")
    public int mId;

    @Column
    @Expose
    @SerializedName("geo_zoom")
    public double zoom;

</code>

I've added what you suggested and i think it works, but now i have this and sometimes the error that database is locked:

<code>
/SQLiteLog﹕ (11) database corruption at line 51791 of [00bb9c9ce4]
/SQLiteLog﹕ (11) database disk image is malformed
/DefaultDatabaseErrorHandler﹕ Corruption reported by sqlite on database: /data/data/package/databases/database
/DefaultDatabaseErrorHandler﹕ deleting the database file: /data/data/package/databases/database
</code

**Comment by agrosner** [comment]
A corrupt database? Not sure if this is due to DBFlow necessarily. It quite possibly is due to the copy not copying correctly at times. Can you open the prepackaged database you provide in the terminal, and run through sqlite3 ```pragma quick_check(1)```. This can help diagnose if there are issues.

**Comment by rhespanhol** [comment]
Sometimes i have the corrupt database errors, other times it is:

<code>
SQLiteDatabase﹕ Failed to open database '/data/data/package/databases/database.db'.
    android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/databases/database.db' to 'pt_BR'.

Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)

</code>

**Comment by agrosner** [comment]
Are you changing the locale somehow? I haven't seen this one before.

**Comment by rhespanhol** [comment]
Yes, in my Application i change the locale

**Comment by surfer190** [comment]
@rhespanhol How did you solve this issue?

**Comment by rhespanhol** [comment]
@surfer190  I haven't solved it yet. do you have any insight of how to do this?
