### ISSUE TITLE
"Long monitor contention" warning during reactive save operation.

### ISSUE THREAD

**Issue by bartoszwilk** [Raizlabs/DBFlow#1360]
DBFlow Version: 4.0.4 RX, Kotlin
Issue Kind (Bug, Question, Feature): Question

Hi,

I noticed a following logcat warning during reactive save operation. 
```ruby
W/art: Long monitor contention with owner RxComputationThreadPool-1 (3474) at boolean com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(java.lang.Object)(ModelSaver.java:29) waiters=2 in boolean com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(java.lang.Object) for 109ms
```
As I have mentioned, it occurs only during save operation and happens pretty randomly.
Do you have any informations about it?

**Comment by agrosner** [comment]
Not sure what that means, but the operation requires an existence check which is a `SELECT` then either an `INSERT` or `UPDATE` on every object used. So its possible its locked by another operation and has to wait.
