### ISSUE TITLE
Sqlite-Exception handling

### ISSUE THREAD

**Issue by sigfridod** [Raizlabs/DBFlow#1362]
DBFlow Version:
Issue Kind (Bug, Question, Feature):

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

Please provide exception handling support because there are cases where queries or any sqlite operation gets failed and at client end we need to handle that. Right now it is not possible to do it because the framework doesn't throw any exception.

**Comment by agrosner** [comment]
If it doesnt throw an exception, then you're doing it correctly. We don't catch any thrown exceptions, except for `.count()` method on a query and return a 0 because a `SQLiteDoneException` does not make much sense.

**Comment by agrosner** [comment]
Providing "exception handling support" is a little too general for me to make sense of it. If you wrap your db ops in a database `Transaction` we provide an `Error` handler that catches all `Exception` thrown in a query and lets you handle those. https://agrosner.gitbooks.io/dbflow/content/StoringData.html under `Async Transaction`.

**Comment by sigfridod** [comment]
@agrosner got it need to use asynctransaction.
