### ISSUE TITLE
getInsertStatement() to string?

### ISSUE THREAD

**Issue by josueespinosa** [Raizlabs/DBFlow#1367]
DBFlow Version:
Issue Kind (Bug, Question, Feature): Question

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

Is there any way to go from the `DatabaseStatement` returned by `model.getModelAdapter().getInsertStatement()` to an actual string containing the sql text with the insert command??

**Comment by agrosner** [comment]
If you need the real insert, you can use
```java
ContentValues values = new ContentValues();
FlowManager.getModelAdapter(MyTable.class).bindToInsertValues(values, model)
String query = SQLite.insert(...).columnValues(values).getQuery()
```
If you just need the query ModelAdapter has a protected method that returns it. Just extend the  class with a delegate wrapper that exposes the `getInsertStatementQuery()`.  I think that would work.

**Comment by josueespinosa** [comment]
Thank you very much, that works perfectly! I appreciate the help, here's what I ended up doing:

for (ParentModel tableModel : updatedRows) {
            // each table model can be a different subclass of ParentModel, so we'll cast as ParentModel for accessibility
            ContentValues values = new ContentValues();
            tableModel.getModelAdapter().bindToInsertValues(values, tableModel);
            String query = SQLite.insert(((Model)tableModel).getClass()).columnValues(values).getQuery();
            updateStatements.append(query);
}
