### ISSUE TITLE
@OneToMany is invalid

### ISSUE THREAD

**Issue by AllynYonge** [Raizlabs/DBFlow#1368]
When there are three layers nested one-to-many, the last layer of nested methods = OneToMany.Method.ALL is invalid

ProvinceEntity_Table
![image](https://user-images.githubusercontent.com/8694648/28148457-644be538-67b9-11e7-9622-ee7f4dba72d1.png)

CityEntity_Table
![image](https://user-images.githubusercontent.com/8694648/28148501-a27d7330-67b9-11e7-8c47-0e0bf4960e74.png)

DistrictEntity_Table
this is model not auto save

**Comment by agrosner** [comment]
whats invalid here?

**Comment by agrosner** [comment]
use `efficientMethods=false` for the ProvinceEntity and CityEntity. however such nested relationships are strongly discouraged here as it can lead to serious performance issues.
