### ISSUE TITLE
Link to documentation is broken

### ISSUE THREAD

**Issue by ubaierbhat** [Raizlabs/DBFlow#1369]
Issue Kind: Question
Description: 
I am not sure if it is a github issue but looks like the link to documentation in most of the answers to the issue are broken eg. https://github.com/Raizlabs/DBFlow/blob/master/usage2/TypeConverters.md

Can we do something about this?

**Comment by agrosner** [comment]
its moved to https://agrosner.gitbooks.io/dbflow/content/TypeConverters.html

**Comment by agrosner** [comment]
separate site, better format.
