### ISSUE TITLE
Adding name to to column with PRIMARY_KEY_AUTOINCREMENT generates Table$Adapter with error

### ISSUE THREAD

**Issue by hipczor** [Raizlabs/DBFlow#137]
My field with annotation  @Column(name = "bank_id", columnType = Column.PRIMARY_KEY_AUTO_INCREMENT) generates adapter with error in method exists().

@Override
  public boolean exists(Bank model) {
    return ((long)model.bank_id) > 0;
  }

Looks like it takes the column name into method instead of field name.
Without name property it works fine.

**Comment by agrosner** [comment]
@hipczor good find. for now keep it the same, this is a bug fix.

**Comment by hipczor** [comment]
The problem is probably in ExistenceWriter.java on line 34. Used columnName instead of columnFieldName (my inside Sherlock forced me to find this bug :))

**Comment by agrosner** [comment]
thanks @hipczor Ill ensure its not being used anywhere else that can cause other issues!

**Comment by nithdi** [comment]
I am not sure if this is the same bug, but I also can't compile my project when I set the column name for a foreign object or id field in 1.7.2 and with columnType = Column.PRIMARY_KEY.

Sample:
```java
public class ModelA extends BaseModel {
    @Column(name = "my_model_b", columnType = Column.FOREIGN_KEY,
            references = {@ForeignKeyReference(columnName = "modelB", foreignColumnName = "id", columnType = Integer.class)},
            saveForeignKeyModel = true)
    ModelB modelB;
}

public class ModelB extends BaseModel {

    @Column(columnType = Column.PRIMARY_KEY)
    int id;
}
```

This leads to compiler error in the ModelA$Adapter class: Error:(40, 36) error: cannot find symbol variable my_model_b

Test project here: https://github.com/nithdi/dbflowtest
