### ISSUE TITLE
Save Model not working like before when updating from 4.0.0-beta7 to 4.0.5 

### ISSUE THREAD

**Issue by lumueller** [Raizlabs/DBFlow#1371]
DBFlow Version: 4.0.5

I would like to update from 4.0.0-beta7 to 4.0.5, but when I do, my models are not saved as they have been before.

My Model/Classes: There is an issue, it has n subIssues which holds a list with n pages... I am saving the model with ProcessModelTransaction. It works in 4.0.0-beta7 but not in any of the newer versions. The issue and the subissue are saved into the database as the should but not any pages. so the page-table remains empty.

Here are the relevant snippets which show the relationship... has there anything changed from beta to release-version concerning the models?

```
@Table(database = MyDatabase.class)
public class Issue extends BaseModel {

    @PrimaryKey
    String id;

    List<SubIssue> subIssueList;

    @OneToMany(methods = {OneToMany.Method.SAVE, OneToMany.Method.DELETE}, variableName = "subIssueList")
    public List<SubIssue> getDbSubIssueList() {
        if (subIssueList == null || subIssueList.isEmpty()) {
            subIssueList = SQLite.select()
                    .from(SubIssue.class)
                    .where(SubIssue_Table.owningIssueId.eq(id))
                    .queryList();
        }
        return subIssueList;
    }
```

```
@Table(database = MyDatabase.class)
public class SubIssue extends BaseModel {

    @PrimaryKey
    String id;

    @PrimaryKey
    String owningIssueId;

    List<Page> pageList;

 @OneToMany(methods = {OneToMany.Method.SAVE, OneToMany.Method.DELETE}, variableName = "pageList")
    public List<Page> getDbPageList() {
        if (pageList == null) {
            pageList = new ArrayList<>();
        }
        if (pageList.isEmpty()) {
            pageList = SQLite.select()
                    .from(Page.class)
                    .where(Page_Table.owningIssueId.eq(owningIssueId), Page_Table.subIssue_id.eq(id))
                    .queryList();
        }
        return pageList;
    }
```

```
@Table(database = MyDatabase.class)
public class Page extends BaseModel {

    @PrimaryKey
    @Column
    String id;

    @PrimaryKey
    String owningIssueId;

  @ForeignKey(stubbedRelationship = true)
    SubIssue subIssue;
```

thanks for your help!

**Comment by agrosner** [comment]
using stubbedRelationship you need unpack the foreign key objects when retrieving, otherwise you might be saving objects without any fields.

**Comment by agrosner** [comment]
try turning off `@OneToMany(efficientMethods = false)`. If its efficient, it will skip looping through the models to handle their nested relationships.

**Comment by lumueller** [comment]
Thanks, perfect, that worked!
So that would be necessary e.g. if you have nested OneToMany relationships... Maybe you could update the documentation about this? I think there will be more people with that use-case.

btw great lib! appreciate your work!

**Comment by agrosner** [comment]
documentation updated.
