### ISSUE TITLE
[Question] Are enums stored by their name?

### ISSUE THREAD

**Issue by AllanWang** [Raizlabs/DBFlow#1372]
DBFlow Version: 4.0.4
Issue Kind (Bug, Question, Feature): Question

Just to clarify in case I modify my enums in the future. Are enums stored based solely on their naming and class defined in the model? Does it matter if we change the ordering of the enums or refractor it into another class?

**Comment by agrosner** [comment]
yes theyre stored by name. if they no longer exist we fail silently and return null.

**Comment by agrosner** [comment]
order doesnt matter. and you can always define your own `TypeConverter` if you need custom handling.
