### ISSUE TITLE
one to many can not be used on kotlin

### ISSUE THREAD

**Issue by william198824** [Raizlabs/DBFlow#1374]
version = 4.0.5

I make project, IDE create a file like this:

@Override
  public final boolean delete(DataPojo model) {
    boolean successful = super.delete(model);
    if (model.getProjList() != null) {
      ModelAdapter<Proj> adapter = FlowManager.getModelAdapter(Proj.class);
      adapter.deleteAll(model.getProjList());
    }
    model.projList = null;// why not model.setProjList(null); ????
}

why "model.projList = null" ? I think it should be "model.setProjList(null)".
this throw an error is 「error: projList could call private in MainPojo」

**Comment by agrosner** [comment]
use `@OneToMany(isVariablePrivate = true)`

**Comment by agrosner** [comment]
in 4.1.0 lib will detect visibility.

**Comment by agrosner** [comment]
in `develop`.

**Comment by william198824** [comment]
I will try this ,thanks!

**Comment by william198824** [comment]
in 4.1.0 lib, one to many can support  data classes ?
