### ISSUE TITLE
How to sum decimal value?

### ISSUE THREAD

**Issue by dariyanto** [Raizlabs/DBFlow#1376]
DBFlow Version: 4.0.4
Question:
i'm using this query
double income = SQLite.select(sum(Finance_Table.amount))
                .from(Finance.class)
                .where(Finance_Table.type.eq(Constants.TYPE_INCOME))
                .count();
it's return 31000.0 but the correct value is 31000.60, how to correct it?

**Comment by agrosner** [comment]
`count()` calls `simpleQueryForLong()` from `SQLiteStatement`. The only way to get an actual `Double` value from the cursor is to either call `cursor()` and then retrieve the single row from it manually, or define a `@QueryModel` with a single field, AKA `AmountSum(@Column var sum: Double)` and adjust query as:
```
AmountSum sum = SQLite.select(sum(Finance_Table.amount).as("sum"))
.from(Finance.class)
.where(Finance_Table.type.eq(Constants.TYPE_INCOME))
.queryCustomSingle(AmountSum.class);
double income = sum != null ? sum.sum : 0
```
