### ISSUE TITLE
MultiDex: VM has multidex support, MultiDex support library is disabled

### ISSUE THREAD

**Issue by muhammadzadeh** [Raizlabs/DBFlow#1377]
`public class iApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();

            FlowManager.init(new FlowConfig.Builder(this)
                    .addDatabaseConfig(
                            new DatabaseConfig.Builder(iDataBase.class)
                                    .openHelper(new DatabaseConfig.OpenHelperCreator() {
                                        @Override
                                        public OpenHelper createHelper(DatabaseDefinition databaseDefinition, DatabaseHelperListener helperListener) {
                                            return new SQLCipherHelperImpl(databaseDefinition, helperListener);
                                        }
                                    })
                                    .build())
                    .build());
        
    }

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
            MultiDex.install(this);
    }
}`

`public class SQLCipherHelperImpl  extends SQLCipherOpenHelper
{

    public SQLCipherHelperImpl(DatabaseDefinition databaseDefinition, DatabaseHelperListener listener)
    {
        super(databaseDefinition, listener);
    }

   
}`

`
    <application
        android:name=".iApplication"
...`

When i use dbflow sql cipher the following is occurred and app is closed

`07-23 11:48:23.356 8412-8412/? I/art: Late-enabling -Xcheck:jni
07-23 11:48:23.710 8412-8412/ir.hanaabonyan.plasscoapp I/MultiDex: VM with version 2.1.0 has multidex support
07-23 11:48:23.710 8412-8412/ir.hanaabonyan.plasscoapp I/MultiDex: install
07-23 11:48:23.710 8412-8412/ir.hanaabonyan.plasscoapp I/MultiDex: VM has multidex support, MultiDex support library is disabled.`

**Comment by agrosner** [comment]
this does not look like a DBFlow issue. This is a log output that has nothing to do with DBFlow.

**Comment by hzandi** [comment]
I think this is not an error , The vm has already have the support of multidex that is why they are disabling , try to check the log in below 5.0. I guess the the ART vm have already have the multidex support
