### ISSUE TITLE
Enums as composite primary key

### ISSUE THREAD

**Issue by ubaierbhat** [Raizlabs/DBFlow#1379]
DBFlow Version: 4.0.4, 4.0.5
Issue Kind : Question

Description: 

I get a `<identifier> expected` error if I have use enum as primary key. Looks like there is a problem with Enums as primary keys or should we handle them differently? 

```
public class Contact {
    @NotNull
    @PrimaryKey
    Long userId;

    @NotNull
    @PrimaryKey
    ContactType type; // Enum
   
    @Column
    String name;
    ...
}

public class User {
    @PrimaryKey
    Long id;
    @ForeignKey(saveForeignKeyModel = true,
            deleteForeignKeyModel = true,
            tableClass = TaskAddress.class,
            onDelete = ForeignKeyAction.SET_NULL,
            onUpdate = ForeignKeyAction.CASCADE)
   Contact contact;
   ...
}
```

**Comment by agrosner** [comment]
I guess its a botched error message on the fact that enums are not supported as primary keys because they are limiting and you could end up with a null primary key, which is not always what you want. Because if you change the `name()` property on an `Enum` it will not be able to parse it from DB, causing issues hard to detect.

**Comment by agrosner** [comment]
I will ensure that the error message appears.

**Comment by agrosner** [comment]
it seems that I either fixed it or decided to support enums as primary keys. can you check with latest `32dd5e19c` to see if issue is still happening?

**Comment by ubaierbhat** [comment]
Enums are supported in `32dd5e19c` as primary keys. I didn't get that error anymore and was able to save/load. Thank you 😄 

btw. When is the next release ?

**Comment by agrosner** [comment]
soon. just trying to include more bugs and things.
