### ISSUE TITLE
Return null even if data is there in table

### ISSUE THREAD

**Issue by sigfridod** [Raizlabs/DBFlow#1382]
DBFlow Version: 3.3.+
Issue Kind : Bug

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

@agrosner 
I have checked using setho that the data is inserted in table but when I tried to fetch it some time it returns null weird. Any Idea ?? 

Example : from one screen I have inserted one location and started new screen to fill up form after filling up form finding the same location returns null in some cases. not all time

**Comment by agrosner** [comment]
with very little information, I cannot help you on this. It could be threading issues where you are modifying objects on different threads and saving them in some strange state. I would ensure every op is on the same thread.

**Comment by ubaierbhat** [comment]
@sigfridod It would be nice if you could fill the the issue template correctly (DBFlow Version: , Issue Kind:  ) 🙂

**Comment by sigfridod** [comment]
@agrosner and @ubaierbhat  updated description

**Comment by agrosner** [comment]
still, with more information like some sample code. Im guessing you're async storing the data and attempting to retrieve it before the save completes. that's just a guess.
