### ISSUE TITLE
simple adding column by migration

### ISSUE THREAD

**Issue by MahdiPishguy** [Raizlabs/DBFlow#1383]
this is my database schema and i would like to add one column to `ContentDownloadingStatus` table as `filename`

Schema:

```
@Database(name = AppDatabase.NAME, version = AppDatabase.VERSION)
public class AppDatabase {

    public static final String NAME    = "myDB";
    public static final int    VERSION = 4;

    @Migration(version = 4, database = AppDatabase.class)
    public static class Migration2 extends AlterTableMigration<ContentDownloadingStatus> {

        public Migration2(Class<ContentDownloadingStatus> table) {
            super(table);
        }

        @Override
        public void onPreMigrate() {
            addColumn(SQLiteType.TEXT, "filename");
        }
    }
}
```

now after install application on device i dont have this column as `filename` and i get `no column named filename` error

**Comment by agrosner** [comment]
Make sure you increment database version and assign migration to that version. if you previously had version 4 on device, you need to make DB and migration a 5
