### ISSUE TITLE
Cannot remove a table and still access *_Table generated classes

### ISSUE THREAD

**Issue by pinpointdev** [Raizlabs/DBFlow#1386]
DBFlow Version: 4.0.0-beta3
Issue Kind (Bug, Question, Feature): Question

Description: 

I want to remove a table in the new version of an app. Even if I cannot actually drop the table when the app upgrades, I definitely do not want it to be created for new app installs. Therefore I have removed the @Table annotation from the model class for the table that I no longer want created. However, with this annotation removed the _Table class for it is no longer generated. This breaks my migration code, both for the newest version of the database and older migrations that I do not want to delete0.

I believe this could be resolved by adding an element to the @Table annotation called something like "dontCreateTable". If a model class is from a legacy version of the database and is no longer needed, users could use this flag to prevent the table from being created in the database while still having access to the generated _Table class needed for migrations.

Example:

@Table(database = AppDatabase.class, dontCreateTable = true)
public class User {

  @PrimaryKey // at least one primary key required
  UUID id; 

  @Column
  String name;

  @Column
  int age;
}

So, now the User_Table class is still generated and useable in migration code but the User table will not longer be created in new databases.

**Comment by MahdiPishguy** [comment]
@pinpointdev did you cleanUp project and rebuild again?

**Comment by pinpointdev** [comment]
Yes. The problem is that I actually need the generated *_Table classes for old migrations even though I don't want to tables themselves to be created in new installs.

**Comment by agrosner** [comment]
Ill add a flag to turn off automatic creation of the tables.

**Comment by agrosner** [comment]
in `develop` now.  to start using, replace version with `32dd5e19c`
