### ISSUE TITLE
calculate SUM for single column

### ISSUE THREAD

**Issue by MahdiPishguy** [Raizlabs/DBFlow#1390]
I'm using latest version of this library and i'm trying to calculate sum single column as `countOfNewPosts` 

this is my table:

```
public class CafeWebNewPostInformation extends BaseModel {
    @PrimaryKey
    @Column
    public int id;

    @Column
    public int cafeWebServerId;

    @Column
    public int countOfNewPosts;

    @Column
    @ForeignKey(tableClass = AlachiqCafeWebs.class,
            references = @ForeignKeyReference(columnName = "parentId", foreignKeyColumnName = "id"))
    private int parentId;

    @Column
    public int lastSavedId;

    @Column
    public int lastRequestedId;

    @Column
    public int lastRetrievedId;
}
```

and this is my code to get that from this table:

    CafeWebNewPostInformation countOfNewPost =
            SQLite.select(
                    Method.sum(CafeWebNewPostInformation_Table.countOfNewPosts).as("count")
            )
                    .from(CafeWebNewPostInformation.class).querySingle();

i dont get any error and this is result of that:

ScreenShot:
http://www.rupload.ir/upload/zswq6ehmkmpzbqa2telr.png

what happen and where is  `count` on this result?

**Comment by agrosner** [comment]
think about it. you are calling ```SELECT SUM(`countOfNewPosts`) as 'count' FROM CafeWebNewPostInformation```. Meaning the results you get back only contain a single row of `count` from that query. You wont get any error since we don't implement strict column matching on a `Cursor`. You need to define a `@QueryModel` https://agrosner.gitbooks.io/dbflow/content/QueryModels.html that has a single field called `count`:
```java
@QueryModel
public class CountOfPost {

  @Column
  public int count;
}
```
then
```java
CountOfPost count = select(SQLite.select(
                Method.sum(CafeWebNewPostInformation_Table.countOfNewPosts).as("count"))
  .from(CafeWebNewPostInformation.class)
  .queryCustomSingle(CountOfPost.class);  
```

or you can instead of calling `querySingle()` call `count()`.

**Comment by MahdiPishguy** [comment]
I get error:

screen shot:

http://rupload.ir/upload/orufzgmqgkpjy7sl6x1b.png

**Comment by agrosner** [comment]
you're doubling calls to `SQLite.select()` I had a typo by putting it in twice...

**Comment by MahdiPishguy** [comment]
Iam sorry. I don't understand me. Could you fix my code please?

**Comment by MahdiPishguy** [comment]
Iam sorry. I don't understand me. Could you fix my code please?

i created this table:

```
@QueryModel(database = AppDatabase.class)
public class CountOfPost {

    @Column
    public int count;
}
```

but my problem is run query
