### ISSUE TITLE
Question about PropertyMethodExtensions.kt

### ISSUE THREAD

**Issue by epetrenko** [Raizlabs/DBFlow#1391]
DBFlow Version: 4.0.5
Issue Kind (Bug, Question, Feature): Question

Description: There are few infix property methods extensions implemented in [PropertyMethodExtensions.kt](https://github.com/Raizlabs/DBFlow/blob/master/dbflow-kotlinextensions/src/main/java/com/raizlabs/android/dbflow/kotlinextensions/PropertyMethodExtensions.kt) such as `eq`, `isNot`, `notEq ` and etc. have non-null parameter. But the same functions in [Property.java](https://github.com/Raizlabs/DBFlow/blob/master/dbflow/src/main/java/com/raizlabs/android/dbflow/sql/language/property/Property.java) have `@Nullable` annotation for parameter.

For example `eq` function. Infix representation:
```kotlin
infix fun <T : Any> Property<T>.eq(value: T) = this.eq(value)
```
and source function:
```java
@NonNull
@Override
public Operator<T> eq(@Nullable T value) {
    return getCondition().eq(value);
}
```
Question is why not to set nullability for infix function parameter too? Because currently compiler won't let us to do something like this:
```kotlin
var employee = (select from Employee::class where (Employee_Table.id eq employeeId)).result
```
cause `employeeId` is defined like `var employeeId: Int? = null` and can be `null`. Compiler shows the following error - 
`'infix' modifier is required on 'eq' in 'com.raizlabs.android.dbflow.sql.language.property.Property'`.

But if we call `eq` without infix, all is working just fine:
```kotlin
var employee = (select from Employee::class where (Employee_Table.id.eq(employeeId))).result
```

**Comment by agrosner** [comment]
good catch.

**Comment by agrosner** [comment]
use `d624e8f4` for version to see it in action.

**Comment by epetrenko** [comment]
Thanks!
