### ISSUE TITLE
issue with _table generation

### ISSUE THREAD

**Issue by rspl17** [Raizlabs/DBFlow#1393]
DBFlow Version: 4.0.5
Issue Kind (Bug): Bug

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
@agrosner 
in _table generated file reloadRelationship method has this below check
!cursor.isNull(-1)
where "-1" is column index not sure if it generates _table correct or not

**Comment by agrosner** [comment]
need more information please. include generated class `_Table` and the model classes where it happens. Thank you.
