### ISSUE TITLE
Is 4.1.0 DBFlow version Live

### ISSUE THREAD

**Issue by ankursamarya** [Raizlabs/DBFlow#1396]
DBFlow Version:4.0.5
Issue Kind (Question): Question

Description: I have found documentation of vsersion 4.1.0 but i could not get it via gradle. Is it released now or you guys have just updated the doc for future version ie.4.1.0 and current version is 4.0.5

**Comment by trevjonez** [comment]
it is not. releases are always done via github since publishing happens via jitpack, it must.

https://github.com/Raizlabs/DBFlow/releases

**Comment by ArdenDev** [comment]
Any ETA on 4.1.0 ?

**Comment by agrosner** [comment]
probably this weekend. you can start using current code in "38fe8f0cd6"

**Comment by agrosner** [comment]
released.
