### ISSUE TITLE
Should the foreign key be the primary key of another table

### ISSUE THREAD

**Issue by wangp8895** [Raizlabs/DBFlow#1397]
DBFlow Version: 4.0.5
I want the foreign key to be the unique of another table , and the problem:
class com.raizlabs.android.dbflow.processor.definition.column.ForeignKeyColumnDefinition (Kotlin reflection is not available) :Could not find referenced column id from reference named parent

not support?

**Comment by agrosner** [comment]
foreign keys are primary keys of another table. the error means it cannot find column `id` from the referenced table. reopen if you still have issue on later versions of dbflow (4.2.3) and provide more information please.
