### ISSUE TITLE
Type adapters for generic types

### ISSUE THREAD

**Issue by dron247** [Raizlabs/DBFlow#1399]
DBFlow Version: 4.0.4
Issue Kind (Bug, Question, Feature): Question

Description: 
Today i faced an error in generated code while trying to specify my custom converter for `Map<K,V>` faced syntax errors in generated code.
Found solution:
```java
public final class MyAliasType extends HashMap<String, MyPojo> {
    public MyAliasType() { super(); }
    public MyAliasType(Map<String, MyPojo> toCopy) { super(toCopy); }
    // keep empty
}
```
Is there any way to register generic type converters except this one?

Is it possible for you guys to generate a bytecode directly for adapters registration? Or register them with less straightforward code than `converterMap.put(Type, Converter.class)`?  Because this code is the source of current error, on generic types we have `converterMap.put(Map<T1, T2>.class, Converter.class)` - syntax error, may be it is possible to use TypeToken's in generated code?

**Comment by sbatururimi** [comment]
Any update on this?

**Comment by dron247** [comment]
May be you need some help with that, this feature, as I see can be implemented with `TypeToken` for generic types, not just direct call `SomeType<Type1,Type2>.class`
example(whiteboard code):
```java
private Type genericType = new TypeToken<Map<String, Type2>>() {
}.getType();
...
converterMap.put(genericType, Converter.class);
```
If, you have no resources to implement that i can try

**Comment by dron247** [comment]
@agrosner ?

**Comment by agrosner** [comment]
generic type converters are not supported as types are erased at compile time. DBFlow relies on them being unique class objects. It will not perform reflection of any kind to get type information.
