### ISSUE TITLE
Update Listner is Available?

### ISSUE THREAD

**Issue by fakefacebook** [Raizlabs/DBFlow#1400]
DBFlow Version: **4.0.2**
Issue Kind (Bug, Question, Feature): **Question** + if not available then its **Feature**

Description: 

I want to Update Lack of data using loop like this.

``` java
                 for (int k = 0; k < employees.size(); k++){
                     SQLite.update(Overlaymodel.class)
                    .set(Overlaymodel_Table.imagePath.eq(k + 2 + ""))
                    .where(Overlaymodel_Table.imageId.is(employees.get(k).getImageId()))
                    .async()
                    .execute();
                  } 
 ```

after this loop will be finished then i want to get the data from their updated column's list then the list is getting null.  it seems like data isn't Update. 

after some seconds , it will gives me perfect Updated Data ..

so my question is **any listner for that Asynctask to notify when data is inserted successfully or Not.. ?**

**Comment by agrosner** [comment]
just batch them in an `ITransaction` via `FlowManager.getDatabase(MyDatabase.class).beginTransactionAsync(...)` and have a success listener.
