### ISSUE TITLE
Unique Groups not working properly

### ISSUE THREAD

**Issue by mrkma** [Raizlabs/DBFlow#141]
I've copied the UniqueGroups code from DBStructure and after building, the unique groups do not appear in the `UniqueModel$Adapter.getCreationQuery()` generated code. 

If I set each column as `unique = true` in the `@Column` annotation it does append the groups at the end however it also puts `UNIQUE` by the column definition - which wouldn't be what we want.

**Comment by agrosner** [comment]
can you send me your model class here to see what the issue is. Thank you.

**Comment by agrosner** [comment]
did you assign the same ```uniqueGroups``` value for both?

**Comment by mrkma** [comment]
I copied the code from here https://github.com/Raizlabs/DBFlow/blob/master/usage/DBStructure.md#unique-groups
(fixing the closing brackets at the end of the `@Table` annotation)

**Comment by agrosner** [comment]
ok Ill check it out within next couple days and see what's wrong.
