### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by guowang1102** [Raizlabs/DBFlow#1410]
String sql = "select a.ecode, a.birth_time as birthday, a.sex, a.fk_zcode, a.fk_g_zcode, a.p_id, a.ls_id, a.l_id, d.z_type,"
                + "(select name from PARAMETER p where p.ptype='z_type' and p.code=d.z_type) as z_type_name, "
                + "(select fk_l_id from lanshe_no l where l.id=a.ls_id) as she, "
                + "round(julianday('now')-julianday(a.birth_time)) as riling from BASEINFO_SOW_PORKET a "
                + "join BASEINFO_SOW_DELIVER d on d.id=a.fk_deliver_id or d.aid= a.fk_deliver_aid "
                + "or (d.ddid=a.ddid and d.fk_zcode=a.fk_zcode and d.parity_num=a.parity_num) "
                + "where a.serverStatus=" + SERVER_STATUS_VALID + " and a.ablactation_type=2 and a.ecode='" + ecode + "'";

how to use ?

**Comment by agrosner** [comment]
questions like these dont belong in issues. please ask on stackoverflow.
