### ISSUE TITLE
FlowCursor cur = FlowManager.getDatabase(PigDataBase.class).getWritableDatabase().rawQuery(sql, null);

### ISSUE THREAD

**Issue by guowang1102** [Raizlabs/DBFlow#1412]
don't work .

**Comment by agrosner** [comment]
please provide more information. "don't work" doesn't describe what is happening.

**Comment by guowang1102** [comment]
want to get the SQLiteDatabase object of the database directly to execute SQL, like this:
FlowCursor cur = FlowManager.getDatabase(PigDataBase.class).getWritableDatabase().rawQuery(sql, null)
but I don't query success

**Comment by guowang1102** [comment]
this is success
List<parameter> parameterList = SQLite.select().from(parameter.class).queryList();
        for (parameter p : parameterList) {
            Log.v("--", "parameter value is--->" + p.getName() + p.getPtype() + "\n");
        }

**Comment by danvwells** [comment]
Is it that you want to execute some raw sql without the wrapper language?  If so, and you would like it to map to your model object, you could try doing

`new StringQuery<>(parameter.class, sql).queryList();` as long as your selection columns match the parameter.class property names.

If you want the cursor, you say

`new StringQuery<>(parameter.class, sql).query()`

That's kind of short hand for what you were initially trying to do.
