### ISSUE TITLE
how to use Migration0 

### ISSUE THREAD

**Issue by guowang1102** [Raizlabs/DBFlow#1414]
I want to initialize some data，The assets directory has delegated the SQL file, but it cannot be called. How do you use it?

@Database(name = AppDataBase.DB_NAME, version = AppDataBase.VERSION)
public class AppDataBase{

    public static final String DB_NAME = "AppDataBase";

    public static final int VERSION = 1;

    @Migration(version = 0, database = AppDataBase.class)
    public static class Migration_0 extends BaseMigration {

        @Override
        public void migrate(DatabaseWrapper database)
        {

        }
    }
}

sql:
INSERT INTO "parameter" VALUES (1, '2017-08-24 16:35:50');

application
FlowManager.init(this);

**Comment by agrosner** [comment]
just call it on the `DatabaseWrapper` object. `database.execSQL("INSERT INTO "parameter" VALUES (1, '2017-08-24 16:35:50');")`
