### ISSUE TITLE
UI thread is overloaded during large insert transactions

### ISSUE THREAD

**Issue by justincamp** [Raizlabs/DBFlow#1419]
DBFlow Version: 4.0.5
Issue Kind (Bug, Question, Feature): Question

Description: 
During the initial launch of our app, we synchronize data from our server. I'm saving the data with save() calls so that existing records will be updated. The queries are being run from a background service on a separate thread.

I've tried using FastStoreModelTransaction as well as a regular Transaction and I've also tried setting the Transaction to runCallbacksOnSameThread=true, however, no matter what I do, the UI thread is incredibly choppy. I have an infinite spinner displaying on the UI and it basically doesn't spin. The cpu is at roughly 25% during this, so it's not CPU overload.

I have put logging messages in the service, in the query code and in the callback code and verified that none of them are running on the UI thread. The only thing I can think of is perhaps the select queries running to see if the records exist (during the save() calls) are perhaps running callbacks on the UI thread?

Any insight would be appreciated.

Thanks!
Justin

**Comment by danvwells** [comment]
Have you seen this [video](https://www.youtube.com/watch?v=McAvq5SkeTk)?  I wonder if you are experiencing something like the issue he describes.  There are many more like it from Google - the Android Performance Patterns series - they could be helpful to you if you haven't seen them.

**Comment by justincamp** [comment]
@danvwells I'm a little embarrassed to say that memory churn was indeed the problem. I was creating new objects that map json objects to database objects in a loop instead of using a single object. Not only did it clear up the UI staggering issues, but it's saving a lot faster now too.

Thanks so much!

**Comment by justincamp** [comment]
It appears I spoke too soon. The churn made smaller sets of data more responsive, but large sets of data are still really breaking the UI thread.

**Comment by trevjonez** [comment]
can you profile it and determine if the issue is indeed dbflow logic or if you are just having GC pressure causing issues?

**Comment by justincamp** [comment]
I figured it out. I was being stupid. I had a table change observer resetting the cursor and invalidating the recyclerview dataset with every record during the massive import. Thanks for the video, without it I wouldn't have been in the right mindset to find the issue.

Cheers!
