### ISSUE TITLE
dbflow should have dbflow-core as dependency

### ISSUE THREAD

**Issue by xanscale** [Raizlabs/DBFlow#1426]
in version 4.0.5 we can use dbflow with just

```
annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:4.0.5"
compile "com.github.Raizlabs.DBFlow:dbflow:4.0.5"
```

in 4.1.1 require dbflow-core to compile

```
annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:4.1.1"
compile "com.github.Raizlabs.DBFlow:dbflow-core:4.1.1"
compile "com.github.Raizlabs.DBFlow:dbflow:4.1.1"
```

if `com.github.Raizlabs.DBFlow:dbflow` require `com.github.Raizlabs.DBFlow:dbflow-core` it should be specified in maven dependency

**Comment by agrosner** [comment]
it does. in its build.gradle. also in the getting started docs we still ask you to include it as a dependency. it might be something with the new gradle plugin.
