### ISSUE TITLE
cannot find symbol class *_Table

### ISSUE THREAD

**Issue by fakefacebook** [Raizlabs/DBFlow#1427]
DBFlow Version:4.1.1
Issue Kind (Bug, Question, Feature): Overlaymodel_Table class not found

    annotationProcessor 'com.github.Raizlabs.DBFlow:dbflow-processor:4.1.1'
    compile 'com.github.Raizlabs.DBFlow:dbflow-core:4.1.1'
    compile 'com.github.Raizlabs.DBFlow:dbflow:4.1.1'

**i am no more use other annotationProcessor .**

![capture](https://user-images.githubusercontent.com/20983834/29995513-7fec869a-9008-11e7-8559-83d51c513f9c.PNG)

**Comment by agrosner** [comment]
did you import the generated class?

**Comment by fakefacebook** [comment]
ya same error 
![](https://user-images.githubusercontent.com/20983834/30011890-096052de-9159-11e7-847c-7b5099ba287c.PNG)

**Comment by Harti** [comment]
@fakefacebook what did you do to resolve the issue?

**Comment by hardikm9850** [comment]
A remote team is facing the same issue that apt files are generated but are not linked via imports, they would like to know if your solution works for them, can you please post the solution?

**Comment by ankur99999** [comment]
We are also getting same issue. 
Can you please tell how we can solve this issue?

**Comment by fakefacebook** [comment]
When you are Using various annotation with anoting error then it will b arrise this Error. Check your code and find annotation error . I hope it should be solve
