### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Number.longValue()' on a null object reference

### ISSUE THREAD

**Issue by adigyran** [Raizlabs/DBFlow#1428]
DBFlow Version: 4.1.1
Issue Kind (Bug, Question, Feature): Bug
Description: after update from 4.0.5 to 4.1.1 i have this error
`java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Number.longValue()' on a null object reference
09-05 14:50:01.977 3481-3481/* W/System.err:     at com.raizlabs.android.dbflow.structure.ModelAdapter.hasAutoIncrement(ModelAdapter.java:316)
09-05 14:50:01.978 3481-3481/* W/System.err:     at com.raizlabs.android.dbflow.sql.saveable.AutoIncrementModelSaver.insert(AutoIncrementModelSaver.java:49)
09-05 14:50:01.978 3481-3481/*  W/System.err:     at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:51)
09-05 14:50:01.978 3481-3481/*  W/System.err:     at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:35)
09-05 14:50:01.978 3481-3481/*  W/System.err:     at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:190)
09-05 14:50:01.978 3481-3481/*  W/System.err:     at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:68)`
and field with @ForeignKey(saveForeignKeyModel = true)
and autoincrement primary key. In 4.0.5 all working fine. In patch-notes i can`t find any changes about it behavior

**Comment by danvwells** [comment]
I noticed this recently too.  If you initialize your auto incrementing primary key to some value, say 0, I think that works around this.  Something like this

```
@PrimaryKey
private Long id = 0;
```

**Comment by xanscale** [comment]
or simply...

```
@PrimaryKey
private long id = 0;
```

**Comment by agrosner** [comment]
yeah. nullable autoincrement columns will be disallowed. in java there is no way to enforce this other than a runtime exception (or compile time with nullability annotations).

**Comment by agrosner** [comment]
in `develop` for `4.1.2`

**Comment by agrosner** [comment]
we will display a warning like:
```
w: warning: *==========*
w: 

w:   Attempting to use nullable field type on an autoincrementing column. To suppress or remove this warning switch to java primitive, add @android.support.annotation.NonNull,@org.jetbrains.annotation.NotNull, or in Kotlin don't make it nullable. Check the column id on AutoIncrementingModel
w:   *==========*
```
in 5.0 it might become an error, but also it will throw an `IllegalStateException` if the field value is null when it checks for it during insert.

**Comment by yzp531** [comment]
don't use
 @Column
    @PrimaryKey(autoincrement = true)
    public Long id;
please user
 @PrimaryKey(autoincrement = true)
    public Long id;

Long is not OK
long is ok

**Comment by danvwells** [comment]
correct, must not be nullable type in more recent versions.
