### ISSUE TITLE
Index with InheritedColumn 

### ISSUE THREAD

**Issue by gnuhel** [Raizlabs/DBFlow#1429]
DBFlow Version:4.1.1
Issue Kind (Bug, Question, Feature): Feature 

Description: 
I tried to use InheritedColumn but I couldn't find a way to set the Index for specific columns. With fields within the table I can set @Index. Is there a way to set it in @InheritedColumn? Thanks

**Comment by agrosner** [comment]
not supported currently. it would just continue to further increase complexity of inherited columns.
