### ISSUE TITLE
Documentation for using distinct

### ISSUE THREAD

**Issue by simernes** [Raizlabs/DBFlow#143]
Maybe I've missed it but I can't find how to use the distinct call in select queries. Can you please add it to https://github.com/Raizlabs/DBFlow/blob/master/usage/SQLQuery.md ? Thanks

**Comment by agrosner** [comment]
```new Select().distinct()```

**Comment by simernes** [comment]
can you specify selecting by a distinct column if for example a table has two primary keys, but you only want one of them in a specific query?

**Comment by yeduRaghav** [comment]
Same question as @simernes. I had to write raw sql, to specify distinct column.
