### ISSUE TITLE
Custom Cache key for model class using modelcache

### ISSUE THREAD

**Issue by rspl17** [Raizlabs/DBFlow#1432]
DBFlow Version:
Issue Kind : Question

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
How can I use custom key for caching using modelcache I guess it takes primary key as default key

**Comment by agrosner** [comment]
it uses primary key values only to ensure uniqueness with the DB. https://agrosner.gitbooks.io/dbflow/content/Caching.html under Advanced.
