### ISSUE TITLE
Select.from(IProperty... properties) does not work if you not specify primary key in properties when "cachingEnabled=true"

### ISSUE THREAD

**Issue by Rexee** [Raizlabs/DBFlow#1433]
DBFlow Version: 4.1.1
Issue Kind (Bug, Question, Feature): Bug

**Description:** 
If you have class with flag `cachingEnabled = true` and try to load data from it with ` Select` while not specify column with PrimaryKey in ` Select.from(IProperty... properties)` properties list, DBFlow will throw exception. If you not enable cache - everything works well.

**Expected behaviour:**
`Select.from` with cache enabled should work as SQLite queries.

**Code to reproduce:**
```java
@Table(database = AppDatabase.class, cachingEnabled = true)
public class TestModel extends BaseModel {
    @PrimaryKey
    public long id;

    @Column
    public String name;
}

public class MainApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();

        FlowManager.init(FlowConfig.builder(this)
                .addDatabaseConfig(DatabaseConfig.builder(AppDatabase.class).build())
                .build());

        Delete.tables(TestModel.class);

        TestModel model = new TestModel();
        model.id = 1;
        model.name = "Test model";
        model.save();

        TestModel result = new Select(TestModel_Table.id, TestModel_Table.name)//<-works normal
                .from(TestModel.class)
                .querySingle();

        result = new Select(TestModel_Table.name)//<-throw exeption if "cachingEnabled=true". If cachingEnabled=false, all works correctly
                .from(TestModel.class)
                .querySingle();
    }
}
```

**Comment by danvwells** [comment]
The primary key is how dbflow identifies the cached object within the cache, so it really needs it.  Note also from the [docs](https://agrosner.gitbooks.io/dbflow/content/Caching.html) that you should avoid doing selection beyond ```select *```, which is accomplished with ```select().from(...```, when using caching.  

Perhaps a more descriptive error could have helped though.

**Comment by Rexee** [comment]
` Select(TestModel_Table.name).from(TestModel.class)` is absolutely correct. Cache should works **exactly** same way as if you requested data from db. If cache require to work PrimaryKey column, then it should be checked internally and, if column missed, it should be added automatically at the query building stage. Or it should works as SQLite works with queries without primary keys - it just returns first matching value.

**Comment by agrosner** [comment]
caching is great for keeping things around based on primary key. you need to have them present in the query (or no columns specified for it to work properly). You can call `disableCaching()` on any query to retrieve fresh results from the DB. I would avoid caching if possible in general as its only a bit more faster and you can end up with stale data. I would use RX or DB transactions to load the query on a bg thread and return results to your consumer asynchronously.

**Comment by agrosner** [comment]
DBFlow wont do much "magic" under the hood. If a column is missed, it will crash or throw exception. The consumer of the query should always expect its query to match what it's requesting. by adding missing columns, it changes that correspondence and just leads to more confusion and more issues.
