### ISSUE TITLE
Custom newInstance method

### ISSUE THREAD

**Issue by OmidID** [Raizlabs/DBFlow#1434]
DBFlow Version: 4.1.1
Issue Kind (Bug, Question, Feature): Question
Description: 
Hello, I want to know is there anyway to have custom instance with arguments.
For example i have a class:

```
@Table(database = MyDatabase.class, name = "Contacts")
public class ContactModel {
   public ContactModel(int arg1, int arg2) {
      /* */
   }
}
```

I understand DBFlow using `_Table` classes for do something and there is a method `newInstance`
and there i can see the code like this: `return new ContactModel();`
 
Now the question is here. How can I have a custom `newInstance` method here?
Possible?
If I edit this method what's will be happen for next generate code?

Thanks.

**Comment by danvwells** [comment]
If arg1 and arg2 correspond to required columns in the table, you could have your constructor in your example to use for your convenience, and then also have a no-argument constructor that DBFlow will use, and then annotate your columns with ```@NotNull``` so it will throw an exception if anyone ever tries to save without populating those fields.

**Comment by agrosner** [comment]
not currently. I am considering adding ability for immutable objects with passing constructor args, but that would require some heavy refactoring to get working.

**Comment by agrosner** [comment]
you are required to have an empty, default constructor for now.

**Comment by OmidID** [comment]
@agrosner Custom cache controller? this also can help somehow
