### ISSUE TITLE
how to connect dbflow to existed content provider?

### ISSUE THREAD

**Issue by mchenani** [Raizlabs/DBFlow#1439]
Hey there and thanks for great dbflow
I have a big android project with hundreds of connections from UI to DB ( a content provider ).
now planned to setup dbflow in our code. but we need a great plan to how start, and how to connect dbflow to existed CP, or ....
Thank you.

**Comment by agrosner** [comment]
this is a question for stackoverflow. DBFlow can be used to generate content providers or you can roll your own which calls the DBFlow wrapper methods.
