### ISSUE TITLE
primary key Long not valid?

### ISSUE THREAD

**Issue by Rainer-Lang** [Raizlabs/DBFlow#144]
```java
@Column(columnType = Column.PRIMARY_KEY_AUTO_INCREMENT)
public Long id;
```
If I save a new object I get this:
```java
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
```

Is this a bug or a feature? ;-)

**Comment by agrosner** [comment]
It appears to be a bug, can you send me the full stacktrace.

**Comment by Rainer-Lang** [comment]
Hi,
is it possible to send you my classes via mail? 3 small files and some test-lines.
There is also one other issue #28 .

**Comment by petroski77** [comment]
@Rainer-Lang 
You've defined the primary key as a Long which can have a null value. 
If you define the key as long then it probably will work. ;)

**Comment by Rainer-Lang** [comment]
I know that I can use "long" instead of "Long" (this works definitely). But this is not the same.
As I think - Long should also work.

**Comment by agrosner** [comment]
@Rainer-Lang is correct, long should work too. Let me file this under 1.7.1
