### ISSUE TITLE
How to initialize database with SQLCipher

### ISSUE THREAD

**Issue by shobhik** [Raizlabs/DBFlow#1445]
DBFlow Version: 4.1.1
Issue Kind: Question

Description: So I noticed the way we configure and initialize databases has changed. Our app uses SQLCipher with the following init steps in our application class:

```
FlowManager.init(new FlowConfig.Builder(this)
    .addDatabaseConfig(
        new DatabaseConfig.Builder(SBNDatabase.class)
            .openHelper(new DatabaseConfig.OpenHelperCreator() {
                @Override
                public OpenHelper createHelper(DatabaseDefinition databaseDefinition,                     
                 DatabaseHelperListener helperListener) {
                    return new SQLCipherHelperImpl(databaseDefinition, helperListener, mContext);
           }
    })
    .build())
    .openDatabasesOnInit(true).build());

```

I was wondering what should change per 4.1.0/4.1.1 in those initialization steps. Should we be adding a 

```
.addDatabaseConfig(DatabaseConfig.builder(SBNDatabase.class)
.databaseName("AppDatabase")
```
inside the `DatabaseConfigBuilder`?

**Comment by shobhik** [comment]
Also, if I remove the @database(name = ?, version ?) annotation in my database class, my model classes cannot find the database and therefore building fails. Any ideas on this?

**Comment by baranowskinet** [comment]
My db class has just version annotation rest is in init method:

**Comment by agrosner** [comment]
yes version in the annotation, the name in the config builder.

**Comment by divyanshingle** [comment]
In my project i was using v4.0.5 and i upgrade the library with v4.2.4, also i am using 4 database in my project along with i have one module which also have 3 database.

But when i remove the name from annotation from each database file and put it config then no database creating and throw exception "The specified database databaseName was not found. Did you forget the @Database annotation?"

*Note i have 4 database in main project and other module having 3 more database.

**Comment by shobhik** [comment]
@divyanshingle I now have 4.2.4 working. Can you share a code sample of the relevant build.gradle files so I (or we) can help you out?

**Comment by divyanshingle** [comment]
I am adding snap of build.gradle for releavant code

![screen shot 2018-11-29 at 2 26 15 pm](https://user-images.githubusercontent.com/34330817/49210544-5e4c8900-f3e3-11e8-9a5b-06356011e33c.png)
![screen shot 2018-11-29 at 2 29 15 pm](https://user-images.githubusercontent.com/34330817/49210557-65739700-f3e3-11e8-974c-9a227a37f4f7.png)

Project having two points for initialisation of DB, one is main project and second is module but i am not sure how to add all database name in both place.

Note : I am using 4.2.4 version and project having multiple database.

**Comment by divyanshingle** [comment]
Here is my main project code
```
private void initDbFlow() {
        FlowManager.init(FlowConfig.builder(context)
                .addDatabaseConfig(DatabaseConfig.builder(AppDatabaseHelper.class)
                        .databaseName(AppDatabaseHelper.getDatabaseName())
                        .build())
                .addDatabaseHolder(AppDatabaseHelperGeneratedDatabaseHolder.class)
                .build());
    }

```

Similarly i used this code in my module also but i am only passing one database file and the same database couldn't found by app.

**Comment by divyanshingle** [comment]
Anyluck?
