### ISSUE TITLE
Ensuring a custom TypeConverter is used.

### ISSUE THREAD

**Issue by ubaierbhat** [Raizlabs/DBFlow#1448]
DBFlow Version:4.0.0-beta5
Issue Kind : Bug
Description: 
We have a custom DateConverter to convert Date into string using Gson so that we can persist the date as `yyyy-MM-dd'T'HH:mm:ssZZ` into the db. 

```@com.raizlabs.android.dbflow.annotation.TypeConverter
public class DateConverter extends TypeConverter<String, Date> {
    private final Gson gson = GsonInstance.getInstance();

    @Override
    public String getDBValue(Date model) {
        return gson.toJson(model);
    }

    @Override
    public Date getModelValue(String data) {
        return gson.fromJson(data, Date.class);
    }
}
````

This works as expected however occasionally the date is stored in Long format which might come from dbflows own implementation of [DateConverter.java](https://github.com/Raizlabs/DBFlow/blob/master/dbflow-core/src/main/java/com/raizlabs/android/dbflow/converter/DateConverter.java)

I have looked into the generated code and it seems like there is no guarantee on which TypeConverter will be used.

**Comment by agrosner** [comment]
does this still happen on 4.2.2?

**Comment by agrosner** [comment]
dont see it happening just by globally overridding it, closing it.
