### ISSUE TITLE
Fatal exception in select

### ISSUE THREAD

**Issue by relevante** [Raizlabs/DBFlow#1450]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Bug

In production I'm seeing a few crash reports in Crashlytics of the following:

android.database.sqlite.SQLiteException: no such column: __ChadronAlwaysEqualString (code 1): , while compiling: SELECT * FROM `MyTable` WHERE `myColumn`=__ChadronAlwaysEqualString LIMIT 1

I've never seen this before. It's always on Nexus 4 devices running 6.0.1 (it appears to have happened on 4 different devices though).

Any ideas? Thanks!

**Comment by agrosner** [comment]
if you have migrations then probably a race condition. Not sure here but this doesnt seem like a DBFlow question. please ask on stackoverflow.

**Comment by petitJAM** [comment]
I'm seeing `__ChadronAlwaysEqualString` come up in some server logs. I think it's just a bot running your app. The user agent in our logs was `Dalvik/2.1.0 (Linux; U; Android 6.0.1; Nexus 4 Build/MMB29U)`, which lines up with what you see.
