### ISSUE TITLE
select case

### ISSUE THREAD

**Issue by Alexinzaz** [Raizlabs/DBFlow#1452]
DBFlow Version:
Issue Kind:  Question

Description: 

Hello.
How to create next with Dbflow:
`SELECT CASE WHEN exclusive=1 THEN product.name WHEN exclusive=0 THEN product.name + "*" END name FROM product`

I want concatenate filed value with some text

**Comment by agrosner** [comment]
this might work:
```java
SQLite.select(
  SQLite.casewhen(Some_Table.exclusive.eq(1)
  .then(name.withTable())
  .when(exclusive.eq(0))
  .then(name.withTable().concatenate("*"))
  .end("name"))
.from(Product.class)
```
