### ISSUE TITLE
Enum<E> generic TypeConverter

### ISSUE THREAD

**Issue by thornley-touchstar** [Raizlabs/DBFlow#1453]
DBFlow Version: 4.1.1
Issue Kind (Bug, Question, Feature): Question

Description: 

Is it possible with the Kotlin extensions to provide a generic enum TypeConvertor? For example `TypeConverter<String,Enum<E>>` as opposed to specifying convertors for every enum class that would be used in the database. Enum types are typically either stored (generically) in the database as the element's string value or its associated integer ordinal/position.

**Comment by agrosner** [comment]
unfortunately not right now. you will need to define a custom type converter for each one. just create a common base class and register all the TypeConverters you need. Its because on reverse from DB you would need to do a `EnumClass.valueOF()` to figure out the enum you want it to be.
