### ISSUE TITLE
AutoIncrementModelSaver does not call ModelAdapter.saveForeignKeys()

### ISSUE THREAD

**Issue by optisamit** [Raizlabs/DBFlow#1454]
DBFlow Version: 4.1.1
Issue Kind Bug

Description: 

`AutoIncrementModelSaver` does not call `ModelAdapter.saveForeignKeys()`.
As a result, `@ForeignKey(saveForeignKeyModel = true)` is not working on a table with `@PrimaryKey(autoincrement = true)`

**Comment by agrosner** [comment]
fixed in `develop`. try `a8cb9dfa30` as your DBFlow version.
