### ISSUE TITLE
Cant see columns After Android DBFLOW migration

### ISSUE THREAD

**Issue by BbosaH** [Raizlabs/DBFlow#1456]
I made a DbFlow migration for my SQLite Db. I added two columns and the build was successful The problem is I cant see those columns anywhere in the User table and i cant insert or read data from them. Infact everytime i try to insert data i still get the error that User  has no column phoneNumber .What could be the problem ?

```
package com.omnitech.elunda.mobile.database;

import com.raizlabs.android.dbflow.annotation.Database;
import com.raizlabs.android.dbflow.annotation.Migration;
import com.raizlabs.android.dbflow.sql.SQLiteType;
import com.raizlabs.android.dbflow.sql.migration.AlterTableMigration;

/**
 * Created by magicwand on 9/28/2017.
 * Database class to manage datastore
 */

@Database(name=ELundaDatabase.name , version=ELundaDatabase.VERSION)
public class ELundaDatabase {

    public static final String name ="ElundaDatabase";
    public static final int VERSION =1;

    @Migration(version = ELundaDatabase.VERSION +1, database=ELundaDatabase.class)
    public static class Migration1 extends AlterTableMigration<User> {


        public Migration1(Class<User> table) {
            super(table);
        }

        @Override
        public void onPreMigrate() {
            super.onPreMigrate();
            addColumn(SQLiteType.TEXT, "phoneNumber");
            addColumn(SQLiteType.TEXT, "password");
        }
    }



}

```

**Comment by agrosner** [comment]
did you add them to your model objects?

**Comment by BbosaH** [comment]
Oh thanks for the Answer but i finally fixed it 11 days ago.
I had not updated the version while doing a migration. I also learnt that as soon as i unistalled my app onthe phone . dint need to do a migration

**Comment by raphaelbgr** [comment]
i'm facing the same problem, and I have the right properties (tried also as public fields) and on the migration, it only shows the columns I added when I reset and destroy the database and do init again.
