### ISSUE TITLE
Bug: Transaction queue must me cleared as part of DB reset process.

### ISSUE THREAD

**Issue by liorzam** [Raizlabs/DBFlow#1457]
**DBFlow Version**:4.1.1
**Issue Kind**: Bug

**Description**:
As i describe in the title transaction queue must me cleared as part of DB reset process,
otherwise db reset can lead to serious issues.

Transactions queue have no sense if the relevant database for which it was created doesn't exist anymore.

**Solution**:
call this line in reset method:
openHelper.getDelegate().getDatabaseDefinition().getTransactionManager().stopQueue();

**Comment by agrosner** [comment]
`DatabaseDefinition.close()` stops the queue. `destroy()` is called in `reset()` which calls close() inside of it.

**Comment by agrosner** [comment]
try latest 4.2.2
