### ISSUE TITLE
can I add a list of string in a model?

### ISSUE THREAD

**Issue by jiqimaogou** [Raizlabs/DBFlow#146]

**Comment by Rainer-Lang** [comment]
Can you be a bit more precise?
Maybe some code snippet.

**Comment by jiqimaogou** [comment]
@column
List<String> attachmenets.

can I do this?

**Comment by agrosner** [comment]
That's not possible and will break one of the relational database constraints . Cannot have more than one value for a column. You need to have a new table that references the id of the first table and a row for each value of the list.

**Comment by jiqimaogou** [comment]
ok, thank you, I use a string column which join string with ",", and split theme then.
