### ISSUE TITLE
Unable to Import Condition clause 

### ISSUE THREAD

**Issue by DroidDeveloper28** [Raizlabs/DBFlow#1460]
DBFlow Version:4.1.1
Issue Kind (Bug, Question, Feature):Bug, Question

 
 SQLite.update(P2PMsg.class)
                .set(**Condition.Column**(XXXXXXX))
                .where(P2PMsg_Table.Message.eq(message.getTextBody()))
                .execute();

Description: 
Unable to Import the **Condition** or **ConditionGroup** .

**Comment by agrosner** [comment]
`Condition` class does not exist. please read the [4.0 migration](https://agrosner.gitbooks.io/dbflow/content/Migration4Guide.html)
