### ISSUE TITLE
math operators (plus, minus, times, etc)

### ISSUE THREAD

**Issue by 2x2xplz** [Raizlabs/DBFlow#1462]
DBFlow Version: 4.1.1.
Issue Kind (Bug, Question, Feature): question

Description: Probably a stupid syntax issue on my end, but I cannot get the math operators to work.

Simplest example (WidgetID is a Long):
`SQLite.select().from(Widget::class.java).where(Widget_Table.WidgetID.times(0).eq(0)).queryList()`  
anything times 0 should == 0, but this returns an empty list

`SQLite.select().from(Widget::class.java).where(Widget_Table.WidgetID.greaterThan(10000))).queryList()`  
returns list of size == 6
`SQLite.select().from(Widget::class.java).where(Widget_Table.WidgetID.times(2).greaterThan(20000))).queryList()` 
everything is doubled, but returns empty list

`SQLite.select().from(Widget::class.java).where(Widget_Table.WidgetID.plus(50000).greaterThan(20000))).queryList()`
adding 50000 should make every row valid, but also returns empty list

Also, is there any way to use these inside the SELECT? Like
`SQLite.select(Widget_Table.WidgetID.times(3)).from(Widget::class.java).queryList()`
instead, this gives a TypeMismatch error

Thank you.

**Comment by agrosner** [comment]
```
SQLite.select().from(Widget::class.java).where(Widget_Table.WidgetID.times(0).eq(0)).queryList()

```
Query list never returns a null list. I would debug the query that is run. We run:
```java
        FlowLog.log(FlowLog.Level.V, "Executing query: " + query);

```
So to see the logs of queries:
```kotlin
FlowLog.setMinimumLoggingLevel(Level.V)
```

**Comment by agrosner** [comment]
for custom queries that return projections from `select` you need a `@QueryModel`. when you specify `where(...)` its not going to return all rows. its only returning rows that match that query, so really its working as intended. If you want all rows to perform operation on them, you need to specify a custom projection on the column.
