### ISSUE TITLE
Standart column types, foreign keys, default constructor in Kotlin

### ISSUE THREAD

**Issue by Aqluse** [Raizlabs/DBFlow#1463]
DBFlow Version: 4.1.1
Issue Kind (Bug, Question, Feature): Bug, Question

Description: 
I'm using Kotlin to create database
I've got 3 issues (don't know if I should separate them).

**1. Standart column types.**
I use ByteArray type in a table. I got:

> Error:error: Columns cannot be of array type.

But 3rd item allows it:
![16-10-2017 001357](https://user-images.githubusercontent.com/13728921/31588131-ecfbd5b8-b206-11e7-890a-fb43199f8549.png)
https://agrosner.gitbooks.io/dbflow/content/TypeConverters.html

**2. Non-nullable Foreign Key**
> Error:error: *==========* :Foreign Keys must be nullable. Please remove the non-null annotation if using Java, or add ? to the type for Kotlin.*==========*

Is it really such a problem to have non-nullable foreign key?

**UPD:** As I took a point, after reading some of the same issues had been asked here before, I should put @NonNull annotation instead of non-nullable Kotlin type to see right behavior of this.

**3. Default constructor for data class***

> Error:error: *==========*class com.raizlabs.android.dbflow.processor.TableValidator :Table XXXX must provide a visible, default constructor.*==========

I have data classes for all tables in database with column as parameters. Looks like one's in example
https://agrosner.gitbooks.io/dbflow/content/KotlinSupport.html
Got errors for all of tables.

**Comment by agrosner** [comment]
please file 3 separate issues.
1. that's a bug. 
2. see #1459 
3. Make sure you provide default values for all fields.

**Comment by agrosner** [comment]
1. is in `develop` now.
