### ISSUE TITLE
Private properties

### ISSUE THREAD

**Issue by Aqluse** [Raizlabs/DBFlow#1465]
DBFlow Version: 4.1.2
Issue Kind (Bug, Question, Feature): Question

Description: 
I created this block of code inside of Kotlin data class, but got exception told me it shouldn't be private. Is there a way to do same behavior somehow?
```
@get:OneToMany(methods = arrayOf(OneToMany.Method.ALL))
private var collections by oneToMany { select from Collection::class where (Collection_Table.musician_id eq id ) }
    
var collectionsNonNull = collections ?: emptyList()
```

**Comment by agrosner** [comment]
dont make `OneToMany` private.

**Comment by agrosner** [comment]
the annotation processor needs it visible so it can call it.
