### ISSUE TITLE
Could I have a class with an List<Long> or List<String>?

### ISSUE THREAD

**Issue by confuste** [Raizlabs/DBFlow#1466]
Hello.

I want to have a class with a Column which has a list of numbers. Are there any way to do it and save it automatically when I save my parent class?

```
@Table(database = MyDatabase.class)
public MyClass extends BaseModel {

   @PrimaryKey
   private long id;

   @Column
   private List<Long> listofOrderedNumbers;

}
```

Thank you.

**Comment by agrosner** [comment]
Not recommended. Use a custom class with a `TypeConverter` to handle it for you.
