### ISSUE TITLE
  kapt "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}" 

### ISSUE THREAD

**Issue by zhangruiyu** [Raizlabs/DBFlow#1469]
Error in studio3.0

**Comment by Harti** [comment]
* What does the error say?
* Are you using Kotlin? If so, do _not_ add the `kapt` line.

**Comment by agrosner** [comment]
yes more information is required. @Harti you need to add the kapt line for Kotlin.

**Comment by zhangruiyu** [comment]
sorry. because of the anko10.0.0 problem

**Comment by Harti** [comment]
Oops sorry, I meant to write "if not". Edited.
