### ISSUE TITLE
save a list of mode with observer

### ISSUE THREAD

**Issue by jiqimaogou** [Raizlabs/DBFlow#147]
if i have an observer and save a list of models, it will notify many times, does it have a way notify change when a list of data saving is complete.

notify dbflow://modelclass

**Comment by agrosner** [comment]
Not currently. You could use a ```@ContentProvider``` class and do a bulk insert, which would do pretty close to what you may want to do.

**Comment by agrosner** [comment]
This is going to be fixed in `2.0.0`

**Comment by agrosner** [comment]
use the `FlowContentObserver.beginTransaction()` and then call `endTransactionAndModify()`

**Comment by brucexia0** [comment]
@agrosner so this code will still fire two notifcations for item saved? And if we use beginTransaction and endTransactionAndNotify then we cannot use the existing ProcessModelInfo?
````
FlowContentObserver.setShouldForceNotify(false);
                ProcessModelInfo<Currency> processModelInfo = ProcessModelInfo.withModels(response.body())
                        .result(new TransactionListenerAdapter<List<Currency>>() {
                            @Override
                            public void onResultReceived(List<Currency> result) {
                                Timber.d("GetCurrenciesJob Currencies saved %d", result.size());
                            }
                        });
                TransactionManager.getInstance().addTransaction(new SaveModelTransaction<>(processModelInfo));
````

**Comment by brucexia0** [comment]
@agrosner any chance this solution can be reconsidered? even with an option to specify whether to do quell in transaction notification? This issue has been a show stopper for using the flow observer.
