### ISSUE TITLE
Clarify "Including in Project" Documentation

### ISSUE THREAD

**Issue by Harti** [Raizlabs/DBFlow#1470]
DBFlow Version: any
Issue Kind (Bug, Question, Feature): Enhancement (Documentation)

Description: 
Documentation around [including DBFlow in a project](
https://agrosner.gitbooks.io/dbflow/content/including-in-project.html) should be made more clear. I've spent a few hours trying to figure out where I was doing something wrong.

Suggestion: 
Add the following statements:

* Use the "Build > Rebuild Project" command in Android Studio to make DBFlow automatically generate `*_Table` classes for you. In order for this to work, your code should not reference any of these classes yet (e.g. comment out the lines in question).
* Depending on your project configuration, you may need to use `apt "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"` instead of  `annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"` in your Gradle dependencies.

Thanks for creating this awesome library!

**Comment by agrosner** [comment]
1. shouldnt need to comment out the lines if you import them properly.
2.`apt` is deprecated and shouldn't be used anymore.
