### ISSUE TITLE
defaultValue of Date is not generated correctly

### ISSUE THREAD

**Issue by mikinw** [Raizlabs/DBFlow#1472]
DBFlow Version: 4.1.2
Issue Kind (Bug):

Description: 
The documentation says the way to define default value for a Date is this:
```
@Column(defaultValue = "1000L")
public Date date;
```

However when I build the project, I get compile errors:
`Error:(268, 31) error: incompatible types: long cannot be converted to String`

In bindToUpdateStatment() and bindToInsertStatement() medthods of the corresponding *_Table.java class I get this:
```
    if (refdate != null) {
      statement.bindNumber(8, refdate);
    } else {
      statement.bindString(8, 1000L);
    }
```
Which is wrong.

**Comment by agrosner** [comment]
try out `4.2.2`. there is a bug fix for types of typeconverters that may fix it for you.
