### ISSUE TITLE
I have more data in database after uninstalling application 

### ISSUE THREAD

**Issue by MahdiPishguy** [Raizlabs/DBFlow#1474]
DBFlow Version:
after uninstalling application from android settings and install fresh version from android studio my old database have all data and don't deleted after uninstalling application. why?

**Comment by agrosner** [comment]
backup https://developer.android.com/guide/topics/data/autobackup.html
```
Files in the directory returned by getDatabasePath(String), which also includes files created with the SQLiteOpenHelper class.

```
disable autobackup and youre good.
