### ISSUE TITLE
How to define a case insensitive column?  (COLLATE NOCASE)

### ISSUE THREAD

**Issue by tuckercr** [Raizlabs/DBFlow#1476]
DBFlow Version: 4.0.5
Issue Kind: Question
Description: 

I would like to define a column that ignores case.  Consider the follow table definition:
```
CREATE TABLE table_name (
   email TEXT PRIMARY KEY COLLATE NOCASE,
   ...
)
```

How would I tell DBFlow to apply COLLATE NOCASE to the email column?  So far I have:

```java
@PrimaryKey
@Column
public String email;
```

Thanks in advance.

**Comment by nvolpini** [comment]
there is a "collate" attribute for the @Column annotation
@Column(collate = Collate.NOCASE)
