### ISSUE TITLE
Ignore Null fields when updating

### ISSUE THREAD

**Issue by brucexia** [Raizlabs/DBFlow#1477]
DBFlow Version:4.1.2
**Issue Kind (Bug, Question, Feature):**

Feature

**Description**:
is it possible to annotate fields that should only be updated if it's not null? This is useful in that we have different APIs same object, but one with simplifed data and one full, e.g. for a User a simplified version will be: id, name, avatar. A full version will be id, name, avatar, address, birthday, etc.

**Comment by agrosner** [comment]
Since we pregenerate the `Update` compiled `DatabaseStatement` on objects, we cannot do this. The best bet would be to create an `UpdateStatement` method that you do yourself, and even with Kotlin this is better:
```kotlin
model.updateIfNotNull()

fun MyModel.updateIfNotNull() {
 val set =  update<MyModel>() set 
 if (this.field != null) {
   set.conditions(MyModel.field.eq(this.field))   
 }
}
``` 
etc.
