### ISSUE TITLE
[Feature] ColumnMap with TypeConverter

### ISSUE THREAD

**Issue by DreierF** [Raizlabs/DBFlow#1480]
DBFlow Version: 4.1.2
Issue Kind (Bug, Question, Feature): Feature
Description: 
I would like to use the new `@ColumnMap` annotation. Unfortunately one of the fields in my embedded object is an enum and therfore currently uses a TypeConverter.
I would love to use `@ColumnMap` in combination with TypeConverter 🙂 

## Current implementation
```
@Table(...)
public class Training extends BaseModel {

    @Column(typeConverter = EWeatherConverter.class)
    public EWeather weather;

    @Column
    public int windDirection;

    public Environment getEnvironment() {
        return new Environment(weather, windDirection);
    }

    public void setEnvironment(Environment env) {
        weather = env.weather;
        windDirection = env.windDirection;
    }
}
```

```
public class Environment {
    public EWeather weather;
    public int windDirection;
    // ...
}
```

## Suggestion 1
```
@Table(...)
public class Training extends BaseModel {
    @ColumnMap
    public Environment environment;
}
```

```
public class Environment {
    @Column(typeConverter = EWeatherConverter.class)
    public EWeather weather;
    @Column
    public int windDirection;
}
```

## Suggestion 2
```
@Table(...)
public class Training extends BaseModel {
    @ColumnMap(references = {@ColumnMapReference(columnName = "weather", typeConverter = EWeatherConverter.class)})
    public Environment environment;
}
```

```
public class Environment {
    public EWeather weather;
    public int windDirection;
}
```

**Comment by agrosner** [comment]
It appears to be a bug that even specifying type convertible fields without annotation fails to compile. 
I think that suggestion 2 what we want because:  the fields do not even respect the annotations on the object. they behave just like a `@ForeignKeyReference` object without sqlite baggage. so adding it to the `@ColumnMap` annotation is more desirable.

**Comment by agrosner** [comment]
Added in 5.0
