### ISSUE TITLE
[Bug] Columns using TypeConverter are always stored with TEXT

### ISSUE THREAD

**Issue by DreierF** [Raizlabs/DBFlow#1481]
DBFlow Version: 4.1.2
Issue Kind (Bug, Question, Feature): Bug

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
Previous versions of dbFlow (I'm migrating from 3.1.1) did respect the return type of the custom type converter. For the example below a column of type `BLOB` was created in sqlite for `thumbnail`: 
```
@Column(typeConverter = ThumbnailConverter.class)
public Thumbnail thumbnail;
```
```
public final class ThumbnailConverter extends TypeConverter<Blob, Thumbnail> {
    ...
}
```

In 4.1.2 I get a column of type `TEXT` regardless of the type I convert my object to (Blob above, but also happens for all other types). Is this new behavior expected?

**Comment by anastasia-zaitsewa** [comment]
Wanna join since I have the same issue migrating from 3.1.1.

We use `LocalDate` as a primary key for one of our models and using a `TypeConverter` to make the `long` out of it.

What 3.1.1 was generating in `ModelWithLocalDate_Adapter`:
```
"CREATE TABLE IF NOT EXISTS `ModelWithLocalDate`(`day` INTEGER,`someField` TEXT, PRIMARY KEY(`day`) ON CONFLICT REPLACE" + ");"
```
And here is what I am getting with 4.1.2 in `ModelWithLocalDate_Table`:
```
"CREATE TABLE IF NOT EXISTS `ModelWithLocalDate`(`day` TEXT, `assignments` TEXT, PRIMARY KEY(`day`) ON CONFLICT REPLACE)"
```
Is there are a chance to get a workaround for that?

**Comment by agrosner** [comment]
Sounds like a bug.

**Comment by agrosner** [comment]
released. 4.2.2
