### ISSUE TITLE
how to update database by sqlite file downloaded from internet at runtime ?

### ISSUE THREAD

**Issue by omar-adel** [Raizlabs/DBFlow#1483]
Description: 

I have sqlite file in assets and dbflow read it correctly but at runtime I sometimes  need to download 
a new updated sqlite file from internet and place it in certain folder in sdcard
so how to update dbflow database by this  sqlite file in sdcard 
 to remove  data of all tables 
and add the new data to them ?

**Comment by yangtuhua** [comment]
Hello ,can you give me hand?I put the db file in assert ,but dbflow didn't read it when the app is first installed.

**Comment by agrosner** [comment]
close db, copy file over and then reopen.
