### ISSUE TITLE
@Column(defaultValue = X) with @ForeignKey cause $Table to not get generated

### ISSUE THREAD

**Issue by zmorris** [Raizlabs/DBFlow#1484]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Bug

Instant Run is off (as always) until they get around to fixing it to actually work.

Not sure about incremental compilation, likely off because build.gradle doesn't contain the word "incremental".

Description: 

The following compiles:

	@Table(name = MyTable.TABLE_NAME, database = MyDatabase.class)
	public class MyClass extends MyModel implements IUpdateOthersOnDelete {
		public static final String TABLE_NAME = "table";
		
		@Column//(defaultValue = "0")
		//@NotNull
		@ForeignKey(
			references = @ForeignKeyReference(
				columnName = "foreign_table_id",
				columnType = String.class,
				foreignKeyColumnName = "id"//,
				//referencedGetterName = "getID",
				//referencedSetterName = "setID",
				//referencedFieldIsPrivate = true
			)
		)
		ForeignClass foreign;
	}

But if I change it to `@Column(defaultValue = "0")` then I get:

	Error:(24, 44) error: cannot find symbol class SomeOtherClass$Table

I've tried every combination of `@Column`, `@NotNull` and `@ForeignKey`, as well as commenting out the lines in `@ForeignKeyReference` so I think this may be a conceptual problem in DBFlow where it disallows having a foreign key reference and a default value at the same time.

Nullable foreign keys work, just not foreign keys where the default value is something like 0 instead of null.

**Comment by zmorris** [comment]
As another data point, as of 3.1.1, setting a default value in the class for primitive types like TEXT and INTEGER works:

	public class MyClass extends MyModel implements IUpdateOthersOnDelete {
		public static final String TABLE_NAME = "table";

		public MyClass() {
			this.value = "";
		}
		
		@Column(name = "val")
		@NotNull
		String value;
		
		// ...

Results in:

	CREATE TABLE `table` (`val` TEXT NOT NULL DEFAULT '')

This also works:

	public class MyClass extends MyModel implements IUpdateOthersOnDelete {
		public static final String TABLE_NAME = "table";

		@Column(name = "val")
		@NotNull
		String value = "";
		
		// ...

But the annotation is ignored:

	public class MyClass extends MyModel implements IUpdateOthersOnDelete {
		public static final String TABLE_NAME = "table";

		@Column(name = "val", defaultValue = "")
		@NotNull
		String value;
		
		// ...

So that results in:

	CREATE TABLE `table` (`val` TEXT NOT NULL)

I haven't figured out a way to do this with model foreign keys:

	ForeignClass foreign = "";	// won't compile

So as far as I can tell, there's no way to use defaults with model foreign keys.  The documentation at https://agrosner.gitbooks.io/dbflow/content/Models.html is out of date unless annotations have been fixed in DBFlow 4+.

Note that non-null foreign keys with a default of "" or 0 are kind of weird, and assume that a default row with id "" or 0 exists in the foreign table.  This is admittedly a code smell.

But it would be great if the documentation had examples for setting defaults right in the constructor or member variable declaration.  Hope this helps someone.

P.S. I have not tested these with migrations.  My guess is that any change in default values will be ignored since SQLite lacks modify column.  Which is why it's so important to get it right when the model is first created.

**Comment by agrosner** [comment]
Default values on foreign key objects are not supported. I probably need to add an error in the logs. If you need that support you will have to manually specify the foreign key references as primitive columns. Later versions of DBFlow (probably 4.0+) ignore default values for `@ForeignKey` objects.

**Comment by agrosner** [comment]
added warning in 5.0 branch for use in primitive columns. 4.0+ must have fixed the issue with specifying the default value in the `@Column` annotation. 
Now in 5.0 you can attach default values to both `@ColumnMapReference` and `@ForeignKeyReference`
