### ISSUE TITLE
SQLiteConstraintException: FOREIGN KEY constraint failed (code 787) on model.delete()

### ISSUE THREAD

**Issue by kriggus** [Raizlabs/DBFlow#1486]
DBFlow Version: 4.1.2
Issue Kind (Bug, Question, Feature): Question

Description: 
How do i set up my foreign key relation below such that all DbMedicineTime entries with a relation to DbMedicine x are deleted when `x.delete()` is called?

Right now I get `SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)` error if  `foreignKeyConstraintsEnforced = true`.

Doing something along the line of `x.times?.forEach { it.delete() }` before `x.delete()` does help. But I don't trust myself to remember that every time, is it possible to set it up so DBFlow handle this for me?

```kotlin
@Table(database = MyDailyMedDatabase::class)
private data class DbMedicine(

        @PrimaryKey(autoincrement = true)
        var id: Int = 0,

        @Column
        var name: String = "",

        @Column
        var dosageMode: Int = 0

) : BaseModel() {

    @get:OneToMany(methods = arrayOf(OneToMany.Method.ALL))
    var times by oneToMany {
        select from DbMedicineTime::class where (DbMedicineTime_Table.medicine_id.eq(id))
    }
}

@Table(database = MyDailyMedDatabase::class)
private data class DbMedicineTime(

        @PrimaryKey(autoincrement = true)
        var id: Int = 0,

        @ForeignKey(
                stubbedRelationship = true,
                references = arrayOf(ForeignKeyReference(
                        notNull = NotNull(),
                        columnName = "medicine_id",
                        foreignKeyColumnName = "id")))
        var medicine: DbMedicine? = null,

        @Column
        var hourOfDay: Int = 0,

        @Column
        var minute: Int = 0

) : BaseModel()
```

**Comment by agrosner** [comment]
Since you extend `BaseModel` just call `delete()` on the `DbMedicine` table. I would strongly avoid using `oneToMany` on a class that has a reverse `@ForeignKey` relationship on the table. Can cause serious performance issues.
