### ISSUE TITLE
Dependencies missing in .pom files

### ISSUE THREAD

**Issue by MarcoLied** [Raizlabs/DBFlow#1487]
DBFlow Version: 4.1.0, 4.1.1, 4.1.2
Issue Kind (Bug, Question, Feature): Bug

Description: 
Your dependencies are missing in the provided .pom files on jitpack, since you changed to the new gradle 3.0.0 api / implementation dependency syntax with 4.1.0.

Can you please check it and provide those information?

Invalid:
https://www.jitpack.io/com/github/Raizlabs/DBFlow/dbflow/4.1.2/dbflow-4.1.2.pom

Correct:
https://www.jitpack.io/com/github/Raizlabs/DBFlow/dbflow/4.0.5/dbflow-4.0.5.pom

Thank you in advance.

Best regards
Marco

**Comment by agrosner** [comment]
use lowercase naming: https://www.jitpack.io/com/github/raizlabs/dbflow/dbflow/4.0.5/dbflow-4.0.5.pom
this comes out just fine. Must have been a jitpack.io bug.

**Comment by MarcoLied** [comment]
@agrosner: It makes no difference, if I use the lowercase, for all version since 4.1.0, the dependencies are missing in the .pom files:
https://www.jitpack.io/com/github/raizlabs/dbflow/dbflow/4.1.0/dbflow-4.1.0.pom
https://www.jitpack.io/com/github/raizlabs/dbflow/dbflow/4.1.1/dbflow-4.1.1.pom
https://www.jitpack.io/com/github/raizlabs/dbflow/dbflow/4.1.2/dbflow-4.1.2.pom

You posted the .pom of 4.0.5 and that one is an example, where the dependencies where there.

**Comment by agrosner** [comment]
looking at this: https://github.com/dcendents/android-maven-gradle-plugin/issues/61
just need to update plugin to 2.0+ which im doing for 4.2.3 :)
