### ISSUE TITLE
Misleading warning in FlowLog while generating Operators using TypeConverters 

### ISSUE THREAD

**Issue by dave-mellors** [Raizlabs/DBFlow#1488]
DBFlow Version: 4.1.2
Issue Kind : Question

Description: 

When generating SQL involving an Operator with a TypeConverter, for example:

`SQLite.select().from(Log.class).where(Log_table.insertTime.greaterThan(yesterday))`

a warning message is generated in the FlowLog which details a ClassCastException with full stack trace, via 
`Operator.convertObjectToString(Object object, boolean appendInnerParenthesis)`

The appearance of the stack trace caused me to spend some time believing that some error had occurred, whereas the final output of the method is actually correct in this case.

Would it be possible to change the log record to not include the stack trace in this instance?

**Comment by agrosner** [comment]
Its just giving you an idea of a possible problem. 
```
                // if object type is not valid converted type, just use type as is here.
```
the comment should have helped you or at least seeing through debugging why it happened should explain it.
For reference, what is the type of `insertTime` and what is the value/type of `yesterday`

**Comment by dave-mellors** [comment]
I am not suggesting that  the warning is removed (although this is reporting the internal default behaviour, which in this case is the desired outcome), which is perfectly valid, but that the log need not contain a stack trace as it is only a warning and not an error as such. The warning could still show relevant details at that point.

The example above is just an example, not a real case, but would have been a String representation of a LocalDateTime.  The resulting SQL was exactly as it should have been.

**Comment by agrosner** [comment]
ill move it up to `Level.I` info and put it as not a stack trace, but as the actual purpose of what is happening.

**Comment by agrosner** [comment]
in `develop`.
