### ISSUE TITLE
Help needed for asynchronous example

### ISSUE THREAD

**Issue by marvinmosa** [Raizlabs/DBFlow#1489]
I would like to ask for an example using asynchronous instead of synchronous.
I am currently using the format below

User user = new User();
user.setId(0);
Business business = new Business();
business.setId(1);
Location location = new Location();
location.setId(3);
location.save();
business.setLocation(location);
business.save();
Job job = new Job();
job.setId(8);
job.save();
user.setBusiness(business);
user.setJob(job);
user.save();

it is working perfectly but if i have many data then the best solution was to do it in asynchronous.
I looked at the Async Transactions but that doesnt show how to do a something similar thing above.
Hope somebody could show me an example for it. Thanks alot.

**Comment by agrosner** [comment]
if you need help I would ask on stackoverflow, not in github issues. Its on the docs here:
https://agrosner.gitbooks.io/dbflow/content/StoringData.html

Just use a regular `Transaction`:
```

DatabaseDefinition database = FlowManager.getDatabase(AppDatabase.class);
Transaction transaction = database.beginTransactionAsync(new ITransaction() {
            @Override

            public void execute(DatabaseWrapper databaseWrapper) {
               User user = new User();
user.setId(0);
Business business = new Business();
business.setId(1);
Location location = new Location();
location.setId(3);
location.save();
business.setLocation(location);
business.save();
Job job = new Job();
job.setId(8);
job.save();
user.setBusiness(business);
user.setJob(job);
user.save();
            }
        }).build();
transaction.execute();
```
