### ISSUE TITLE
[Question] Exporting provider

### ISSUE THREAD

**Issue by AllanWang** [Raizlabs/DBFlow#1501]
In light of [v4.2.0](https://github.com/Raizlabs/DBFlow/releases/tag/4.2.0)

I'm wondering if it's okay if we use `exported=false` for the provider.
I'm not on Android O and I don't use observables, so I'm not sure of the entire context of the provider, but if it's purely for the current app, it won't need to be exported and this will resolve a lint warning.

If that's expected, it would be nice to include it in the changelog.

**Comment by agrosner** [comment]
yeah you should only have exported content provider if you need to share data between apps. its up to you to decide if you wish to expose it to other apps (which in most cases dont need to)
