### ISSUE TITLE
columnName of ForeignKeyReference is not used for PrimaryKey

### ISSUE THREAD

**Issue by Devenias** [Raizlabs/DBFlow#1504]
DBFlow Version: **4.2.3**

Hi, I just upgraded from an older version to v4.2.3 and have an issue with the code generation. I could reproduce it in a sample project as well.

Here are some classes which are referenced by a `ForeignKey` (which is also a `PrimaryKey`) and the column is renamed in `ForeigKeyReference`

```
@Table(database = AppDatabase.class)
public class AntHill extends BaseModel {
    @PrimaryKey
    public String hillId;
}

@Table(database = AppDatabase.class)
public class Ants extends BaseModel {
    @PrimaryKey
    public String antId;

    @PrimaryKey
    @ForeignKey(tableClass = AntHill.class, references = {
            @ForeignKeyReference(columnName = "hillIdRef", foreignKeyColumnName = "hillId")
    })
    public String hillId;
}
```

The Project won't compile as it is because there is an error in the `Ants_Table.java`.
`error: cannot find symbol variable hillId`
Caused by that generated method in the `Ants_Table.java`:
```
@Override
public final OperatorGroup getPrimaryConditionClause(Ants model) {
  OperatorGroup clause = OperatorGroup.clause();
  clause.and(antId.eq(model.antId));
  clause.and(hillId.eq(model.hillId));
  return clause;
}
```
It should be `clause.and(hillIdRef.eq(model.hillId));` if I'm not wrong.

**Comment by agrosner** [comment]
ill look into it. thanks for report!

**Comment by agrosner** [comment]
in `develop` for `4.2.4`. you can try it via `904a66738e`
