### ISSUE TITLE
 Confused about @Index

### ISSUE THREAD

**Issue by wangsuicheng** [Raizlabs/DBFlow#1506]
DBFlow Version:4.x

Bug or Feature Request: Annotation @Index will genearate INDEX sql schema?

Description:
If i annotate @Index to filed , and install app, I sqlite3 the db throught adb, there is no schema:
sql CREATE INDEX xxx on tableName(column....)

**Comment by agrosner** [comment]
use `IndexMigration` to add it. I will make it clearer in 5.0 to add the index into the schema.

**Comment by wangsuicheng** [comment]
@agrosner 
for example, my db version is 10, if i never installed this app on my phone, I install it first time, It is impossible to go through the migration process, so it can't generate the schema.
