### ISSUE TITLE
[Error] The global database holder is not initialized.

### ISSUE THREAD

**Issue by Eranot** [Raizlabs/DBFlow#1507]
DBFlow Version: 4.2.4

Bug or Feature Request: I cant use the library without the error "The global database holder is not initialized. Ensure you call FlowManager.init() before accessing the database."

Description: Whenever I try to use .save() function with a entity the error "The global database holder is not initialized. Ensure you call FlowManager.init() before accessing the database." will show up. I have started a brand new project with no others libraries to be sure they are no affecting it.
I'm using Kotlin.

Entire backtrace:

> 12-29 17:52:15.894 20084-20084/com.example.eranot.testdflow E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                                Process: com.example.eranot.testdflow, PID: 20084
>                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.eranot.testdflow/com.example.eranot.testdflow.MainActivity}: java.lang.IllegalStateException: The global database holder is not initialized. Ensure you call FlowManager.init() before accessing the database.
>                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
>                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
>                                                                                    at android.app.ActivityThread.-wrap12(ActivityThread.java)
>                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
>                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                    at android.os.Looper.loop(Looper.java:154)
>                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6123)
>                                                                                    at java.lang.reflect.Method.invoke(Native Method)
>                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
>                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
>                                                                                 Caused by: java.lang.IllegalStateException: The global database holder is not initialized. Ensure you call FlowManager.init() before accessing the database.
>                                                                                    at com.raizlabs.android.dbflow.config.FlowManager.checkDatabaseHolder(FlowManager.java:507)
>                                                                                    at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseForTable(FlowManager.java:138)
>                                                                                    at com.raizlabs.android.dbflow.config.FlowManager.getModelAdapterOrNull(FlowManager.java:469)
>                                                                                    at com.raizlabs.android.dbflow.config.FlowManager.getModelAdapter(FlowManager.java:414)
>                                                                                    at com.example.eranot.testdflow.MainActivity.onCreate(MainActivity.kt:22)
>                                                                                    at android.app.Activity.performCreate(Activity.java:6672)
>                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
>                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
>                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
>                                                                                    at android.app.ActivityThread.-wrap12(ActivityThread.java) 
>                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
>                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                                    at android.os.Looper.loop(Looper.java:154) 
>                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6123) 
>                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
>                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
>                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

Database class:
```
 @Database(name = AppDatabase.NAME, version = AppDatabase.VERSION)
 object AppDatabase {

    const val NAME = "AppDatabase"

    const val VERSION = 1
 }
```

My only table:
```
@Table(database = AppDatabase::class)
class User : BaseModel(){

    @PrimaryKey // at least one primary key required
    internal var id: UUID? = null

    @Column
    internal var name: String? = null

    @Column
    internal var age: Int = 0
}
```

Application class:
```
class MyApp : Application() {

    override fun onCreate() {
        super.onCreate()
        FlowManager.init(this)
    }
}
```

In my MainActivity I call:
```
var user = User()
user.name = "dsf"
user.age = 12
user.id = UUID.randomUUID()

user.save()
```

build.gradle:
```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'


android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.example.eranot.fuckdbflow"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

def dbflow_version = "4.2.4"

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    // Use if Kotlin user.
    kapt "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"

    compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
}
```

Other considerations:

- I have tryed with both Kotlin 1.1.51 and 1.2.0
- I have registered the custom Application in my Manifest and "FlowManager.init(this)" is running.

**Comment by agrosner** [comment]
Use `kotlin-kapt` plugin it's required for kotlin.
