### ISSUE TITLE
Upgrade db with app version upgrade

### ISSUE THREAD

**Issue by d-rahul** [Raizlabs/DBFlow#1511]
DBFlow Version: 4.0.0-beta5

Bug or Feature Request: Feature Request

Description: How can I upgrade my app database on the upgrade of the app to a new database?

 See, I have an app with existing database "User" table with column "id","firstname","lastname" and now I updated my app with some specific requirements with app database. So new database, same "User" table with column "id", "name", "address". One more table "Statics" with column "id" and "static". 

Right now what is happening app is crashing because it is checking for "name" column in "User" table which is I think not upgraded auto on app database version upgrade.
So, how I can upgrade the database with old data?

**Comment by agrosner** [comment]
DB are not updated automatically, you need to perform a `Migration`. https://agrosner.gitbooks.io/dbflow/content/Migrations.html

There aren't real automatic migrations in SQLite. 

This seems not like a bug or feature request. May I ask you ask it on Stackoverflow, or if there's missing documentation related to this, you report it as bug for clarification.
