### ISSUE TITLE
Duplicated content provider authorities

### ISSUE THREAD

**Issue by mnovosvetsky** [Raizlabs/DBFlow#1525]
DBFlow Version: 4.2.4

Bug or Feature Request:
Different content provider authorities for subprojects using the same module lib with DBFlow.

Description:
I'm migrating ActiveAndroid project to DBFlow and now having a problem with the content provider. I use DBFlow in lib module which is used in more projects. I somehow need to change and set different provider authorities for each application using this project. 

In lib manifest I can probably use this:

```
<provider
 android:name=".database.AppDatabase_Provider"
 android:authorities="${applicationId}.provider"
 android:exported="false" />
```

But I have no Idea how to put dynamic authorities in AppDatabase and generated classes.

Thank you!

**Comment by agrosner** [comment]
please take a look at the end here:
```
https://github.com/Raizlabs/DBFlow/releases/tag/4.2.0
```

**Comment by agrosner** [comment]
using applicationId is from the `BuildConfig` class.
