### ISSUE TITLE
Warning:Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior.

### ISSUE THREAD

**Issue by MPLB-litvine** [Raizlabs/DBFlow#1526]
DBFlow Version: 3.0.0-beta3

Bug or Feature Request: Warning:Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior.

Description: After installing DBFlow and syncing, android studio (android version 26) throws the above warning.

**Comment by MPLB-litvine** [comment]
I found the solution to this error on http://www.voidcn.com/article/p-swgglggz-bqp.html. 
Apparently annotationProcessor is deprecated in Butterknife and therefore "apt" should be used.

**Comment by agrosner** [comment]
You've definitely got it backwards

**Comment by agrosner** [comment]
You should not be using apt at all anymore whatsoever
