### ISSUE TITLE
Access to SQLiteDatabase

### ISSUE THREAD

**Issue by AlyssonPHN** [Raizlabs/DBFlow#1528]
DBFlow Version:
4.2.4
Bug or Feature Request:
access to SQLiteDatabase
Description:
Please release access to SQLiteDatabase.

**Comment by agrosner** [comment]
you can grab it via `((AndroidDatabase)FlowManager.getWriteableDatabase()).getDatabase())` depending on your sqlite implementation.

**Comment by AlyssonPHN** [comment]
Error again
I'm using Kotlin.

Classifier 'AndroidDatabase' does not have a companion object, and thus must be initialized here.
And "FlowManager." Expecting an element

**Comment by agrosner** [comment]
thats a kotlin question then, not a dbflow question,. cast the `DatabaseWrapper` object to `AndroidDatabase`

**Comment by AlyssonPHN** [comment]
So I will not be able to access SQLiteDabase by Kotlin?

**Comment by AlyssonPHN** [comment]
I got it like this:
`var sqliteDatabase = (FlowManager.getWritableDatabase(AppDatabase::class.java) as AndroidDatabase).database`
