### ISSUE TITLE
Load times?

### ISSUE THREAD

**Issue by SpanKMee** [Raizlabs/DBFlow#153]
Hey. I'm testing the library out and what i found is a bit strange so i thought i'd ask here.
So right now im creating 25000 very simple objects and saving them to the db. This on average takes 80-90 ms which is fast (nice!). But then when i try to load them the time it takes is 600-800 ms. This seems way to much. Am i doing something wrong?

    // Here is my class
    public class Book extends BaseModel {
       @Column(name = BookScheme.ID, columnType = Column.PRIMARY_KEY_AUTO_INCREMENT)
       long _id;

       @Column(name = BookScheme.TITLE)
       String title;

       @Column(name = BookScheme.EDITION)
       String edition;
    }

and here is how i load them

    long start = System.currentTimeMillis();
    List<Book> books = Select.all(Book.class);
    Log.d("asd", "Time to load 25000 items: " + (System.currentTimeMillis() - start) + "ms");

or 

    TransactionManager.getInstance().fetchFromTable(Book.class, new TransactionListenerAdapter<List<Book>>() {
                @Override
                public void onResultReceived(List<Book> books) {
                    Log.d("asd", "Time to load 25000 items (transaction): " + (System.currentTimeMillis() - start) + "ms");
                }
            });

**Comment by Rainer-Lang** [comment]
Did you test other orm-libs?

**Comment by SpanKMee** [comment]
Yes.
OrmLite 
Average time to save 25000 items: 888ms
Average time to load 25000 items: 351ms

SugarOrm
Average time to save 25000 items: 3605ms
Average time to load 25000 items: 954ms

ActiveAndroid
Average time to save 25000 items: 5035ms
Average time to load 25000 items: 473ms

Sprinkles
Average time to save 25000 items: 9617ms
Average time to load 25000 items: 295ms

GreenDao
Average time to save 25000 items: 511ms
Average time to load 25000 items: 129 ms

As you can see all of them (except SugarOrm) are faster at reading.

And then there is this project 
https://github.com/Raizlabs/AndroidDatabaseLibraryComparison
which basically does the same test but there DBFlow is faster than GreenDao. I looked at the source code and it just makes a simple Select.all query like i do, but it takes way less time to do it. So this is why i'm asking am i doing something wrong. Extending my class to BaseCacheableModel didn't help either.

**Comment by Rainer-Lang** [comment]
Thanks. 
Did you try ollie?

**Comment by SpanKMee** [comment]
No

**Comment by Rainer-Lang** [comment]
For my project I have to load many more items than I have to save. So it is important that load is really fast.

**Comment by agrosner** [comment]
That seems pretty strange. Can you paste the generate `$Adapter` class?

**Comment by SpanKMee** [comment]
Sure thing.
  package com.mentormate.myapplication;

import android.content.ContentValues;
import android.database.Cursor;
import com.raizlabs.android.dbflow.config.FlowManager;
import com.raizlabs.android.dbflow.sql.SqlUtils;
import com.raizlabs.android.dbflow.sql.builder.Condition;
import com.raizlabs.android.dbflow.sql.builder.ConditionQueryBuilder;
import com.raizlabs.android.dbflow.sql.language.Select;
import com.raizlabs.android.dbflow.structure.ModelAdapter;
// This table belongs to the App database
public final class Book$Adapter extends ModelAdapter<Book> {

  @Override
  public Class<Book> getModelClass() {
    return Book.class;
  }

  @Override
  public String getTableName() {
    return com.mentormate.myapplication.Book$Table.TABLE_NAME;
  }

  @Override
  protected final String getInsertStatementQuery() {
    return "INSERT INTO `book` (`TITLE`, `EDITION`) VALUES (?, ?)";
  }

  @Override
  public void bindToStatement(android.database.sqlite.SQLiteStatement statement, Book model) {
    if (((java.lang.String)model.title) != null)  {
      statement.bindString(1,((java.lang.String)model.title));
    } else {
      statement.bindNull(1);
    }
    if (((java.lang.String)model.edition) != null)  {
      statement.bindString(2,((java.lang.String)model.edition));
    } else {
      statement.bindNull(2);
    }

  }

  @Override
  public void bindToContentValues(ContentValues contentValues, Book model) {
    contentValues.put("_id",((long)model._id));
    contentValues.put("title",((java.lang.String)model.title));
    contentValues.put("edition",((java.lang.String)model.edition));

  }

  @Override
  public boolean exists(Book model) {
    return  ((long)model._id) > 0;
  }

  @Override
  public void loadFromCursor(Cursor cursor, Book model) {
    int index_id = cursor.getColumnIndex("_id");
    if (index_id != -1)  {
      model._id = cursor.getLong(index_id);
    }
    int indextitle = cursor.getColumnIndex("title");
    if (indextitle != -1)  {
      if (cursor.isNull(indextitle))  {
        model.title = null;
      }  else  {
        model.title = cursor.getString(indextitle);
      }
    }
    int indexedition = cursor.getColumnIndex("edition");
    if (indexedition != -1)  {
      if (cursor.isNull(indexedition))  {
        model.edition = null;
      }  else  {
        model.edition = cursor.getString(indexedition);
      }
    }
    model.onLoadFromCursor(cursor);
  }

  @Override
  public void updateAutoIncrement(Book model, long id) {
    model._id = ((long)id);
  }

  @Override
  public long getAutoIncrementingId(Book model) {
    return ((long)model._id);
  }

  @Override
  public String getAutoIncrementingColumnName() {
    return Book$Table._ID;
  }

  @Override
  public ConditionQueryBuilder<Book> getPrimaryModelWhere(Book model) {
    return new ConditionQueryBuilder<Book>(Book.class, Condition.column(Book$Table._ID).is(((long)model._id)));
  }

  @Override
  public ConditionQueryBuilder<Book> createPrimaryModelWhere() {
    return new ConditionQueryBuilder<Book>(Book.class, Condition.column(Book$Table._ID).is("?"));
  }

  @Override
  public String getCreationQuery() {
    return "CREATE TABLE IF NOT EXISTS `book`(`_id` INTEGER PRIMARY KEY AUTOINCREMENT, `title` TEXT, `edition` TEXT);";
  }

  @Override
  public final Book newInstance() {
    return new com.mentormate.myapplication.Book();
  }
}

**Comment by agrosner** [comment]
@SpanKMee Ill check it out when I get time. thank you

**Comment by Rainer-Lang** [comment]
Any news?
