### ISSUE TITLE
Update of table triggers update of all OneToMany rows, even when efficientMethods = true

### ISSUE THREAD

**Issue by lukewaggoner** [Raizlabs/DBFlow#1541]
4.1.2

Bug

Even with efficientMethods set to true inside the OneToMany annotation, when I save or update a record in a table, it performs a `saveAll` or `updateAll` of all of the related rows in my oneToMany table. Am I mistaken about what effect efficientMethods should have, or does this appear to be a bug?

**Comment by agrosner** [comment]
Efficient methods affect is using fastest possible operation. so this is accurate. if not efficient, it calls the associated `save()` or `insert()`, etc. on each model it retrieves from the query.
