### ISSUE TITLE
Kotlin override .save() in .async()

### ISSUE THREAD

**Issue by lukewaggoner** [Raizlabs/DBFlow#1544]
DBFlow Version: 4.1.2

I would like to use the standard `.save()` function I've overridden in my model class, however when using `.async()` in Kotlin, it doesn't use this function.

I'm saving a class like so: `model.async().save()` and since it's going through `.async()` it does not use the `.save()` function I've overridden in my model class.

**Comment by agrosner** [comment]
`AsyncModel` is being removed in 5.0. I would move this to a `ProcessModelTransaction`.

**Comment by lukewaggoner** [comment]
Good to know, thanks!
