### ISSUE TITLE
Ensuring uniqueness of primary key

### ISSUE THREAD

**Issue by david-perez** [Raizlabs/DBFlow#155]
Is there an option to set a column as an auto-incremented primary key? I have a model in which an int or long is used as a primary key. In order to ensure uniqueness when inserting a new record I find myself querying the table and ordering by this column to find the next value to add. Is there a way so that when I insert new records I don't have to specify the value of this primary key and DBFlow autogenerates it? I've been unable to sort by int because int columns are sorted lexicographically... how can I enforce numeric sorting?

**Comment by agrosner** [comment]
```@Column(columntype = Column.PRIMARY_KEY_AUTOINCREMENT) ```
