### ISSUE TITLE
Class SQLiteCompatibilityUtils is declared in a file named "SqliteCompatibilityUtils.java"

### ISSUE THREAD

**Issue by markzhai** [Raizlabs/DBFlow#156]
Class SQLiteCompatibilityUtils is declared in a file named "SqliteCompatibilityUtils.java", which makes the build failed.

**Comment by Rainer-Lang** [comment]
Same here

**Comment by agrosner** [comment]
Is this in `master`? @markzhai @Rainer-Lang ? thank you. It's a git issue as I'm not seeing it here.I may need to just force add the file changes.

**Comment by Rainer-Lang** [comment]
Sorry for answering so late...
It's the master.
"Error:(13, 8) error: class SQLiteCompatibilityUtils is public, should be declared in a file named SQLiteCompatibilityUtils.java"
