### ISSUE TITLE
Migration doubt

### ISSUE THREAD

**Issue by amrsilva** [Raizlabs/DBFlow#157]
Hi!

I will start use migrations one My Project and before start I like to know if I can create an upgrade and downgrade like alembic. (https://alembic.readthedocs.org/en/latest/tutorial.html#create-a-migration-script)

Thank you, 
  Andreia Silva

**Comment by agrosner** [comment]
all `Migration` classes allow you to do upgrades. They will run against the version of the database specified in the class. For downgrading, that is not supported because SQLite does not provide that many migration options. [here](https://www.sqlite.org/lang_altertable.html)

**Comment by amrsilva** [comment]
Ok :) thank you :)

**Comment by amrsilva** [comment]
In case of migration going wrong what happens to data base?  A roolback is done or we need to catch this exception and force a roolback?

**Comment by agrosner** [comment]
You can wrap a transaction in `TransactionManager.transact()` and that will rollback a transaction if the operation was not successful. Be warned to use the `SQLiteDatabase` parameter referencing the passed in DB, otherwise you may get a recursive call exception:

```
TransactionManager.transact(database, new Runnable(){...});
```

**Comment by agrosner** [comment]
so call that in `migrate()`

**Comment by amrsilva** [comment]
ok. Thank you :)

**Comment by agrosner** [comment]
you're welcome. Reopen if this doesn't answer your question.
