### ISSUE TITLE
Can I put Database Definition class, model classes and CRUD classes in different module?

### ISSUE THREAD

**Issue by laycui** [Raizlabs/DBFlow#1576]
DBFlow Version:
4.2.4

Feature Request:
Define Database.class in module 1, but tables in module 2

Description:
Currently we want to split code into different modules, and for now we want to put database definition into a separate module but table in another. However, It gives the error:
"Database not found for Table Thread".
So we'd like to know if it is feasible?

**Comment by agrosner** [comment]
Tables across module from DB is not supported. you need to keep DB and related tables in same module.

**Comment by agrosner** [comment]
you can specify custom name for db when creating it, but its currently not possible to only include some tables in a db vs others.

**Comment by laycui** [comment]
Thank you Andrew! Your answer helps me save a lot of meaningless trying!
