### ISSUE TITLE
Creating migration doesn't work

### ISSUE THREAD

**Issue by hipczor** [Raizlabs/DBFlow#158]
My simple migration

@Migration(version = 2, databaseName = AppDatabase.NAME)
public class MigrationV2 extends AlterTableMigration<Bank> {

    public MigrationV2(Class<Bank> table) {
        super(table);
    }

    @Override
    public void onPreMigrate() {
        super.onPreMigrate();
        addColumn(Integer.class, "preferred");
    }

}

results in sqlite$Database.java with 

// Begin Migrations
    List<com.raizlabs.android.dbflow.sql.migration.Migration> migrations2 = new ArrayList<>();
    mMigrationMap.put(2,migrations2);
    migrations2.add(new packageNames.MigrationV2());
    // End Migrations

instead of migrations2.add(new packageNames.MigrationV2(Bank.class));

I'm using my external database placed in assets folder

**Comment by agrosner** [comment]
You must have a default constructor. pass the `Bank.class` to the `super(table)` call.

**Comment by simernes** [comment]
can you please add this to the doc? I had the same issue and I think it will save people from confusion if the default constructor is included in the example template
