### ISSUE TITLE
How to make this 'SELECT COUNT(DISTINC(column)) FROM table'

### ISSUE THREAD

**Issue by ricardoantunesmaia** [Raizlabs/DBFlow#1600]
DBFlow Version:
4.0.2
Description:
I need to make a select using COUNT and DISTINCT

**Comment by liorzam** [comment]
SQLite.selectCountOf(YOUR_ENTITY_Table.YOUR_DISTINCT_PROPERTY.distinct()).from(YOUR_ENTITY.class)
