### ISSUE TITLE
Initial content

### ISSUE THREAD

**Issue by marianperca** [Raizlabs/DBFlow#161]
How to add content in tables after the database is created for the first time (version 1).
I tried to add a migration for version 1 but it's now working.

**Comment by gnuhel** [comment]
I also would like to have the feature to create initial content when table is created.

**Comment by Rainer-Lang** [comment]
Me too.

**Comment by petroski77** [comment]
Take a look at https://github.com/Raizlabs/DBFlow/issues/160
prehaps you can seed the database in a migration.

//Christian

**Comment by agrosner** [comment]
use version 0
