### ISSUE TITLE
JSONModel  inserts same data

### ISSUE THREAD

**Issue by imosmanyilmaz** [Raizlabs/DBFlow#165]
I want to insert my json model  without  checking pk  and i don't want to insert same data.
 Is there a simple way?

JSONModel<Records> jsonModel = new JSONModel<Records>(mValue, Records.class);
 if(!jsonModel.exists()) //always return false and insert all data
 jsonModel.save(false);

**Comment by agrosner** [comment]
can you send me the `Model` blueprint you're using? It would give me a good idea.

**Comment by imosmanyilmaz** [comment]
@Column(columnType = Column.PRIMARY_KEY_AUTO_INCREMENT)
    int ID;
    @Column
    String formType;
    @Column
    String formID;
    @Column
    String recordID;
    @Column
    String updateDate;
    @Column
    String recordStatus;
    @Column
    String filteredFields;
    @Column
    boolean needSync;
    @Column
    String title;
    @Column
    String recordData;

I dont want to check PK

**Comment by agrosner** [comment]
outdated, but use `insert()` method instead of `save()`
