### ISSUE TITLE
application using dbflow

### ISSUE THREAD

**Issue by simernes** [Raizlabs/DBFlow#167]
At the University of Oslo we've been developing the health information system DHIS 2 for several years (www.dhis2.org) . We are now developing an Android SDK to allow the users of the systems to easily create apps to connect to their DHIS 2 servers. To develop the Android SDK we're using DbFlow, so please add it to the "Applications That Use DBFlow" section if you'd like.

https://github.com/dhis2/dhis2-android-sdk

**Comment by agrosner** [comment]
awesome! thank you!!

**Comment by agrosner** [comment]
added in README on master
