### ISSUE TITLE
UpdateTableMigration com.raizlabs.android.dbflow.sql.builder.ConditionQueryBuilder.getTableClass()' on a null object reference error

### ISSUE THREAD

**Issue by amrsilva** [Raizlabs/DBFlow#168]
Hi! :)

I'm trying do on migration like this:

@Migration(version = 4, databaseName = GAUDIDatabase.DB_NAME)
public class MigrationGAU251TestUpdateValues extends UpdateTableMigration<SupplierProblem> {

    public MigrationGAU251TestUpdateValues() {
        super(SupplierProblem.class);
    }

    /**
     * Migration of GAU 239
     * - Change corrective comment value to "test migration" on OK supplier problems
     */

    @Override
    public void onPreMigrate() {
        super.onPreMigrate();
        // UPDATE SupplierProblem SET corrective_comment = "test migration" WHERE problem_status = STATUS_OK;
        set(Condition.column(SupplierProblem.Columns.CORRECTIVE_COMMENT).is("test migration"))
                .where(
                        Condition.column(SupplierProblem.Columns.PROBLEM_STATUS)
                                .is(Constants.AuditProblemStatus.STATUS_OK));
        Timber.e("Migration 4 run with success.");
    }
}

But when I run this migration I have this error:
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development E/GeneralUtils﹕ An error occured while executing doInBackground()
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ java.lang.RuntimeException: An error occured while executing doInBackground()
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at android.os.AsyncTask$3.done(AsyncTask.java:300)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:242)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class com.raizlabs.android.dbflow.sql.builder.ConditionQueryBuilder.getTableClass()' on a null object reference
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at com.raizlabs.android.dbflow.sql.language.Set.getTable(Set.java:134)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at com.raizlabs.android.dbflow.sql.language.Where.<init>(Where.java:72)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at com.raizlabs.android.dbflow.sql.language.Set.where(Set.java:101)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at com.raizlabs.android.dbflow.sql.language.Set.where(Set.java:111)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at com.raizlabs.android.dbflow.sql.migration.UpdateTableMigration.onPreMigrate(UpdateTableMigration.java:74)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at consipere.pt.gaudi.model.migrations.MigrationGAU251TestUpdateValues.onPreMigrate(MigrationGAU251TestUpdateValues.java:28)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at com.raizlabs.android.dbflow.config.FlowSQLiteOpenHelper$4.run(FlowSQLiteOpenHelper.java:417)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at com.raizlabs.android.dbflow.runtime.TransactionManager.transact(TransactionManager.java:120)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at com.raizlabs.android.dbflow.config.FlowSQLiteOpenHelper.executeMigrations(FlowSQLiteOpenHelper.java:397)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at com.raizlabs.android.dbflow.config.FlowSQLiteOpenHelper.onUpgrade(FlowSQLiteOpenHelper.java:313)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:140)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at com.raizlabs.android.dbflow.sql.SqlUtils.querySingle(SqlUtils.java:223)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at com.raizlabs.android.dbflow.sql.language.Where.querySingle(Where.java:339)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at com.raizlabs.android.dbflow.sql.language.From.querySingle(From.java:144)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at consipere.pt.gaudi.model.GAUDIDatabase.initSyncControlTable(GAUDIDatabase.java:296)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at consipere.pt.gaudi.sync.GAUDISyncAlgorithm.syncDataWithServer(GAUDISyncAlgorithm.java:56)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at consipere.pt.gaudi.sync.task.SyncRequestTask.doInBackground(SyncRequestTask.java:24)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at consipere.pt.gaudi.sync.task.SyncRequestTask.doInBackground(SyncRequestTask.java:14)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:288)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-24 18:26:35.387    2722-2722/consipere.pt.gaudi.development W/System.err﹕ ... 4 more

What am I doing wrong?

**Comment by agrosner** [comment]
call `super()` after calling `set()`. This is a bug so I can fix it in next few days. thank you
