### ISSUE TITLE
Select Max, Min, Avg function?

### ISSUE THREAD

**Issue by gnuhel** [Raizlabs/DBFlow#169]
How can I select something like this
`SELECT max(salary) FROM COMPANY;`

**Comment by wintersandroid** [comment]
currently i have used

Cursor cursor = new Select().method("MAX","salary").from(company.class).query();

**Comment by agrosner** [comment]
Yeah I mean I could have added more functions, just at some point it may be a lot. so I added the `method()` method to easily enable other functions.

**Comment by gnuhel** [comment]
@agrosner 
Sorry to ask you again. how do I get the Max value?

`
   public static int foo() {
        Cursor cursor = new Select().method("MAX", Ticket$Table.TICKETID).from(Ticket.class).query();
        if (cursor != null && cursor.getCount() > 0) {
            int ticketId = cursor.getInt(0);
            return ticketId + 1;
        }
        return 10000;
    }
`

this is my code but how do I get Max column?
`int ticketId = cursor.getInt(0);` is wrong

**Comment by GNima** [comment]
was this feature removed? can't find `method` function anymore.

**Comment by raphaelbgr** [comment]
Same, can't find that method funcion too
