### ISSUE TITLE
How can I add custom query to where clause

### ISSUE THREAD

**Issue by hipczor** [Raizlabs/DBFlow#170]
I want to achieve condition which looks kinda like this:

... AND 51.2 > (latitude - 0.5) AND ... 

Is there any way to create custom string queries inside and() method? e.g.

new Select().from(MyClass.class).where(Condition.column(MyClass$Table.ACTIVE).eq(1)).and("here my string query").and()....

**Comment by agrosner** [comment]
Oooh interesting. I see this is a different kind of `Condition`. I may consider doing a `StringCondition` or something for `2.0.0`. That release is a major update to the lib I'm working on. For now, you'll need to just specify a `String` `where()` for now.
