### ISSUE TITLE
Error in Table$Adapter class when setting column name

### ISSUE THREAD

**Issue by nithdi** [Raizlabs/DBFlow#173]
Hi, I am using the latest version (1.7.2) of this library. When I set the name for a column on a foreign object or id field, my project won't compile.

Sample:
```java
public class ModelA extends BaseModel {
...

    @Column(name = "my_model_b", columnType = Column.FOREIGN_KEY,
            references = {@ForeignKeyReference(columnName = "modelB", foreignColumnName = "id", columnType = Integer.class)},
            saveForeignKeyModel = true)
    ModelB modelB;
}

public class ModelB extends BaseModel {

    @Column(columnType = Column.PRIMARY_KEY)
    int id;
}
```

This leads to compiler error in the ModelA$Adapter class: Error:(40, 36) error: cannot find symbol variable my_model_b

I've uploaded a test project: https://github.com/nithdi/dbflowtest
Maybe there is just something wrong in the model setup?!

**Comment by agrosner** [comment]
For a `ForeignKeyReference` model, the `name()` field should remain empty. I will add a validation step in `1.8.0`, but treat `columnName()` from the `@ForeignKeyReference` as the column name that goes into the `ModelA` table. The point of those classes are to enable complex keys as foreign key references.

**Comment by nithdi** [comment]
Ok, thanks for your answer.
