### ISSUE TITLE
Problems with initial setup

### ISSUE THREAD

**Issue by radzio** [Raizlabs/DBFlow#174]
Hi,

I've added these lines in proper places in my gradle files:

    apt 'com.raizlabs.android:DBFlow-Compiler:1.7.2'
    compile 'com.raizlabs.android:DBFlow-Core:1.7.2'
    compile 'com.raizlabs.android:DBFlow:1.7.2'

    maven { url "https://raw.github.com/Raizlabs/maven-releases/master/releases" }

But unfortunately DBFlow is not added as a dependency so I don't have FlowManager etc. classes available. DBFlow-Core is ok.

Do you have any idea why it is happening? Other libs are working like a charm :(

**Comment by radzio** [comment]
When I've run 
![image](https://cloud.githubusercontent.com/assets/469111/6894616/ab0703c4-d6d7-11e4-91de-cf33d4028288.png) from gradle window in my AS it started working.

**Comment by agrosner** [comment]
usually in studio I just would run the normal clean, and assemble tasks.
