### ISSUE TITLE
TransactionManager SaveOnSaveQueue 

### ISSUE THREAD

**Issue by arturonaredo** [Raizlabs/DBFlow#175]
Hi, 

I'm recording all my exceptions and crashes and I've experienced this crash. Should I do something to avoid send the Model to the saveOnSaveQueue thread while is running? 

Sorry I have no more data to reproduce it. Yep, it's pain to have bug reports like this. 
The OS version is 4.4.2 and the library version used is 1.7.2

Cheers,
Arturo.

java.lang.IllegalThreadStateException: Thread already started
	at java.lang.Thread.checkNotStarted(Thread.java:871)
	at java.lang.Thread.start(Thread.java:1025)
	at com.raizlabs.android.dbflow.runtime.TransactionManager.saveOnSaveQueue(TransactionManager.java:294)

**Comment by agrosner** [comment]
No worries, that is strange. 

```java

 // Only start save queue if we are going to use it
 if (!getSaveQueue().isAlive()) {
     getSaveQueue().start();
 }

```

Is there some issue with this code you notice?

**Comment by arturonaredo** [comment]
Not really. I'm calling saveOnSaveQueue from different threads asap the data is received. Could be a race condition? Thinking aloud. 

Just happened once so I'm not really worried about... Feel free to close it as long I just posted it for tracking purposes or easy/fast support, If I'm able to reproduce it... I'll be back :)

**Comment by agrosner** [comment]
@arturonaredo that's certainly possible. Let me know if you find it again, or find a way to repro it. thanks!
