### ISSUE TITLE
Unable to run UnitTests inside android Studio.

### ISSUE THREAD

**Issue by MoranM** [Raizlabs/DBFlow#179]
Hi
im trying to run unit test in android studio version 1.1.0 as suggested here:
http://nenick-android.blogspot.de/2015/03/android-studio-110-and-robolectric-30.html
and hrere:
http://tools.android.com/tech-docs/unit-testing-support

and i keep getting this error :
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$MethodSymbol cannot be cast to javax.lang.model.element.TypeElement
at com.raizlabs.android.dbflow.processor.handler.MigrationHandler.onProcessElement(MigrationHandler.java:23)
which seams realated to the DBFlow annotation processor.

The project is working and compiles well when im under the the standard Android Instrumentation Tests artifact, but not under the new experimental artifact.
Any suggestion on that?
Thanks,
MM

**Comment by agrosner** [comment]
@MoranM Not sure exactly what's going on here and haven't tested using the new Unit tests. I know for 1 that you shouldn't use any logic dependant on behavior of the Android platform ([here](http://tools.android.com/tech-docs/unit-testing-support)). Not sure whats going on. Maybe someone else knows how to fix it.

**Comment by MoranM** [comment]
Never mind the new AS (1.2) version seems to fix it.
