### ISSUE TITLE
varargs warning on generated provider..

### ISSUE THREAD

**Issue by wintersandroid** [Raizlabs/DBFlow#180]
```
AppContentProvider$Provider.java:164: warning: non-varargs call of varargs method with inexact argument type for last parameter;
            .where(selection, selectionArgs)
                              ^
  cast to Object for a varargs call
  cast to Object[] for a non-varargs call and to suppress this warning
```

from the generated code.. methods update, and delete..

my provider - basic..
```
@ContentProvider(authority = AppContentProvider.AUTHORITY,
        databaseName = AppDatabase.NAME,
        baseContentUri = AppContentProvider.BASE_CONTENT_URI)
public class AppContentProvider {
  public static final String AUTHORITY = "nz.org.winters.android.nzmobileaccountwidget.provider";
  public static final String BASE_CONTENT_URI = "content://";

}


```
I have two tables, annotated as such..

```
@TableEndpoint(value = TwoDegreesExtrasTable.NAME, contentProviderName = "AppContentProvider")
@Table(value=TwoDegreesExtrasTable.NAME)
public class TwoDegreesExtrasTable extends BaseModel {
  public static final String NAME="TD_VALUEPACKS2";
  @ContentUri(path = NAME, type = ContentUri.ContentType.VND_MULTIPLE + NAME)
  public static final Uri CONTENT_URI = ContentUtils.buildUri(AppContentProvider.AUTHORITY,new String[]{NAME});
}
```

Everything works, but it would be nice to not have the warnings!

**Comment by amrsilva** [comment]
I Have the same problem! :)
But isn't frequently. Sometimes I haven't warnings and I don't understand why this happens.

**Comment by wintersandroid** [comment]
​I notice it on a complete clean assemble - for a "release" build..
Possibly its coming from lint being run over the code.​

On 7 April 2015 at 00:17, amrsilva <notifications@github.com> wrote:

> I Have the same problem! :)
> But isn't frequently. Sometimes I haven't warnings and I don't understand
> why this happens.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Raizlabs/DBFlow/issues/180#issuecomment-90033754>.
>



-- 
*Mathew Winters*
*See my other apps*
*https://play.google.com/store/apps/developer?id=Mathew+Winters
<https://play.google.com/store/apps/developer?id=Mathew+Winters>*

**Comment by agrosner** [comment]
Ill find a way to remove the warning.

**Comment by agrosner** [comment]
is this a lint warning?

**Comment by wintersandroid** [comment]
I am thinking it is.. I thought I had lint turned off in the gradle.build
but It seems I didnt for this project..

On 9 April 2015 at 01:26, Andrew G <notifications@github.com> wrote:

> is this a lint warning?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Raizlabs/DBFlow/issues/180#issuecomment-90914961>.
>



-- 
*Mathew Winters*
*See my other apps*
*https://play.google.com/store/apps/developer?id=Mathew+Winters
<https://play.google.com/store/apps/developer?id=Mathew+Winters>*
