### ISSUE TITLE
JSONModel ForeignKey not null

### ISSUE THREAD

**Issue by OptimistNot** [Raizlabs/DBFlow#184]
I got an issue, when i try to save model with foreign key that has notNull condition equals true, ex:
     @Column(columnType = Column.FOREIGN_KEY,
            references = {@ForeignKeyReference(columnType = String.class, columnName = Columns.USERNAME_FK, foreignColumnName = User.Columns.USERNAME)}, notNull = true, saveForeignKeyModel = true)
    ForeignKeyContainer<User> user_foreign;
it gives me "Caused by: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: User.user_full_name (code 1299)".
The model that has foreign key and i try to save is this:
        JSONObject json = new JSONObject();
        JSONModel<FinalProductAudit> JSON_FPA = new JSONModel<>(json, FinalProductAudit.class);
        JSON_FPA.save(false);

any hALP please?

**Comment by agrosner** [comment]
@OptimistNot it appears the `user_full_name` was null. By setting `nonNull() = true` you cannot pass the field as `null`. So either before saving the object check for null or specify a `onNullConflict()`

**Comment by OptimistNot** [comment]
I doesn't seems to be the case, as before i try to save my model i set user_full_name and check that it is not null. But if i use ForeignKeyContainer<User> user_foreign; how should i set value? and when exactly i should use user_foreign. toModel()?
Thank you for the response!
