### ISSUE TITLE
Build never end

### ISSUE THREAD

**Issue by ppamorim** [Raizlabs/DBFlow#186]
I've tried 3 times and the build never ends.

    buildscript {
      repositories {
        jcenter()
        maven { url "https://raw.github.com/Raizlabs/maven-releases/master/releases" }
      }
      dependencies {
        classpath 'com.android.tools.build:gradle:1.1.0'
        classpath 'com.raizlabs:Griddle:1.0.3'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
      }
    }

    allprojects {
      repositories {
        jcenter()
        maven { url "https://raw.github.com/Raizlabs/maven-releases/master/releases" }
     }
    }

**Comment by agrosner** [comment]
are you sure its a `DBFlow` issue and not a gradle issue?

**Comment by agrosner** [comment]
Github had experienced DDOS attacks and its possible that its hanging because github wasn't responding.
