### ISSUE TITLE
ForeignKeyContainer not serializable

### ISSUE THREAD

**Issue by OptimistNot** [Raizlabs/DBFlow#187]
it seems like ForeignKeyContainer is not serializable as when i try to start activity with model that has foreign key container it gives me  "java.io.NotSerializableException: com.raizlabs.android.dbflow.structure.container.ForeignKeyContainer", any solution?
Thank you!

**Comment by agrosner** [comment]
I wouldn't serialize it. Rather pass the primary key through and requery to
model.

On Wed, Apr 8, 2015 at 11:06 AM, OptimistNot <notifications@github.com>
wrote:

> it seems like ForeignKeyContainer is not serializable as when i try to
> start activity with model that has foreign key container it gives me
> "java.io.NotSerializableException:
> com.raizlabs.android.dbflow.structure.container.ForeignKeyContainer", any
> solution?
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Raizlabs/DBFlow/issues/187>.
>



-- 
--

*Andrew Grosner, Android Developer*

Mobile Strategy, Design & Development

www.raizlabs.com | Check my calendar
<https://www.google.com/calendar/embed?src=andrew.grosner@raizlabs.com&ctz=America/New_York&mode=WEEK>
 | @agrosner <http://www.twitter.com/agrosner> | 716-472-5075
[image: Raizlabs]
