### ISSUE TITLE
Byte[] Error:Columns cannot be of array type. 

### ISSUE THREAD

**Issue by faustor21** [Raizlabs/DBFlow#189]
Compile error it won't  convert from byte[] or Byte[]  to Blob.

**Comment by EGeorgiev** [comment]
Yeap ... I want to know the same.

**Comment by agrosner** [comment]
@faustor21 Not supported as of yet. I would create a custom class that contains the `byte[]` and define a `TypeConverter` to convert it into its proper data.

**Comment by faustor21** [comment]
Excellent, thank you.

**Comment by Den-Rimus** [comment]
Do I understand correctly that as of current implementation if we need to store, say, this:
`@Column public String[] bookFilesList;` - we need to create TypeConverter for that and use it? And the same for all primitive-typed arrays? (actually String is not so primitive, but you know what I mean)
If so - doesn't this lib happen to have some predefined TypeConverters ready to use out-of-the-box for int[], String[], long[] etc ?

Is that something one can add as participant?

**Comment by agrosner** [comment]
You would be breaking relational database constraints. For array types it's
recommended to create a separate table and use a one to many relationship.
There are no converters for those types and probably never will be. You can
create a wrapper class to define as a field  that has a type converter that
handles conversion for the array of data.

**Comment by mori-honest** [comment]
It is very hard to make all the arrays to tables. There is lots of boilerplate code. is there any other solution to handle arrays? it makes me hate all the work i do with models :(
