### ISSUE TITLE
Missing null check for non primitive number properties

### ISSUE THREAD

**Issue by davidschreiber** [Raizlabs/DBFlow#19]
`com.raizlabs.android.dbflow.processor.utils.ModelUtils#writeContentValueStatement` does not create null value checks for types (e.g. non-primitive values) like Integer, Long, etc.

The compiler would need to check if the model property is a primitive (not nullable) or a type (nullable) variable and handle those two cases differently.

If a column is set to allow null values, the expected behavior would be to insert the null value to the database. Currently the generated adapter class throws a NPE inside the `Model$Adapter#bindToStatement` method.

**Comment by davidschreiber** [comment]
Here you go. The property that can contain a null value is the `rblNumber`.

	@Table
	public class WienerLinienStop extends AbstractPlace {

	    @Column(columnType = Column.PRIMARY_KEY)
	    public Long id;

	    @Column
	    public Long lineId;

	    @Column
	    public Long stationId;

	    @Column
	    public Direction direction;

	    @Column
	    public int sort;

	    @Column(notNull = false)
	    public Integer rblNumber;

	    // Bereich
	    @Column
	    public int area;

	    // Steig
	    @Column
	    public String station;

	    @Column
	    public String stand;

	}

**Comment by agrosner** [comment]
@davidschreiber taking a look at this now. One thing is that the default for ```@Column``` is ```notNull=false``` so ```rblNumber``` would not have any effect. If you want the other columns to be such, you will need to set ```notNull=true``` and then inserting/saving in the DB should handle the rest.

**Comment by agrosner** [comment]
@davidschreiber so I found it. it will be in the next release, 1.1.6. I will be pushing that out ASAP as this is high priority.
