### ISSUE TITLE
Add a trigger on update of model

### ISSUE THREAD

**Issue by amrsilva** [Raizlabs/DBFlow#190]
Hi!

I want do on trigger after update of some model that will insert some content in another table. And this table need register the values present on model that was updated. How can I do this?

**Comment by amrsilva** [comment]
I'm trying doing this:

CompletedTrigger<MillsAudit> mill_audit_trigger = new Trigger<MillsAudit>("update_mill_audit_decision_trigger")
                .after()
                .update(MillsAudit.class, MillsAudit$Table.MILLS_AUDIT_DECISION)
                .when(Condition.column(MillsAudit$Table.MILLS_AUDIT_DECISION).isNot("'" + Constants.Decision.DECISION_DEFAULT + "'"))
                .begin(
                        new Insert<>(AuditReportsToSend.class)
                                .columns(AuditReportsToSend.Columns.AUDIT_ID_FK,
                                        AuditReportsToSend.Columns.AUDIT_TIPE,
                                        AuditReportsToSend.Columns.CREATE_DATE)
                                .values(
                                        MillsAudit$Table.MILLS_AUDIT_ID,
                                        Constants.AuditType.MILLS_AUDIT,
                                        GeneralUtils.formatDateTime(DateTime.now())
                                )
                );

But it raises this exception:
- no such column: mills_audit_decision (code 1): , while compiling: UPDATE  OR ABORT MillsAudit SET mills_audit_username_fk=?,mills_audit_server_id=?,mills_audit_contract_order_id_fk=?,mills_audit_timestamp=?,mills_audit_date=?,mills_audit_decision=?,mills_audit_contract=?,mills_audit_subcontract_id_fk=?,mills_audit_id=?,mills_audit_supplier_id_fk=?,mills_audit_is_dirty=?,mills_audit_to_delete=?,mills_audit_observation=?,mills_audit_undefined_subcontract_name=? WHERE `mills_audit_id`=1

**Comment by agrosner** [comment]
should be fixed in 3.0.0
