### ISSUE TITLE
Question: Subselect

### ISSUE THREAD

**Issue by gervaisb** [Raizlabs/DBFlow#192]
Hi,

I have a domain object _Environment_ who is backed by one `BaseModel` and two `count()`. At this time, for each _Environment_ I have to execute 3 queries :
  1. `Select.byId(EnvironmentRecord.class, envId)`
  2. `Select.count(ApplicationRecord.class, /*where app.envId=envId*/)`
  3. `Select.count(ConfigurationRecord.class, /*where config.envId=envId*/)`

While I can do it in one query in plain SQL : 

    SELECT 
        env.*,
        applications.nbr AS nbr_of_applications,
        configurations.nbr AS nbr_of_configurations 
    FROM 
        environments  env,
        (SELECT count(id) nbr FROM applications WHERE env_id=1) applications,
        (SELECT count(id) nbr FROM configurations WHERE env_id=1) configurations;
    WHERE
        env.id=1

Is it something inside DBFlow that can be used to optimise my 3 queries ?

**Comment by agrosner** [comment]
This kind of nested queries is not supported by the wrapper classes in DBFlow. May be in a future update, but right now it's not supported. You can use a `StringQuery` if you wish and query from it.

**Comment by Rainer-Lang** [comment]
Would be nice to use this...

**Comment by mathieudebrito** [comment]
+1
