### ISSUE TITLE
improperly generated backticks in select query

### ISSUE THREAD

**Issue by mayur-mi** [Raizlabs/DBFlow#193]
recently, i have been playing with dbflow and i realized that when querying data from multiple tables, using the query like 

new Select("t1.col1, t1.col2, t2.col1")
.from(Table1.class).as("t1")
.join(Table2.class,Join.JoinType.INNER).as("t2")
.on(Condition.column("t1." + TestModel1$Table.ID).eq("t2." + TestModel1$Table.ID))
.querySingle();

The generated query was having problems in backticks in the select statement's column lists.

May be you need to fix the function generating these backticks in the sql.

**Comment by agrosner** [comment]
@mayur-mi you're saying a column is `"t1.col1, t1.col2, t2.col1"`. I would separate those out into separate strings.

**Comment by agrosner** [comment]
Also what is the generated query. thanks

**Comment by mayur-mi** [comment]
what i do in the query is that i select column named "col1" from Table1, "col2" from Table1 and "col1" from Table2. I have same column names in both the tables and so i do such select statement. May be you should add the functionality to use the models that dont extend the BaseModel class, as i do not want the data for the select queries to be persisted and as i have columns from multiple tables, this is like a view. But i see that DBFlow currently does not support other models.

The generated query is as follows:
SELECT `t1.col1`, `t1`.col2, t2.`col1` FROM Table1 as t1 INNER JOIN Table2 as t2 ON t1.id = t2.id

The only problem in generated query is that the back ticks (SQL escape for column names) are not placed where they should be.

The query should be like 
SELECT `t1.col1`, `t1.col2`, `t2.col1` FROM Table1 as t1 INNER JOIN Table2 as t2 ON t1.id = t2.id

Note the positions of back ticks (`) here

**Comment by agrosner** [comment]
```java
new Select(ColumnAlias.columnWithTable("t1", col1), 
    ColumnAlias.columnWithTable("t1",  col2),
    ColumnAlias.columnWithTable("t2", col1))
.from(Table1.class).as("t1")
.join(Table2.class,Join.JoinType.INNER).as("t2")
.on(Condition.columnRaw(ColumnAlias.columnWithTable("t1.", TestModel1$Table.ID).eq(ColumnAlias.columnWithTable("t2.", TestModel1$Table.ID))
.querySingle();
```
with `2.0.0` out sometime next week.

**Comment by mayur-mi** [comment]
Hope to see this release soon, keep up the great work.

**Comment by agrosner** [comment]
keeping it open until `2.0.0` is released.
