### ISSUE TITLE
How DBFlow affects project compile times?

### ISSUE THREAD

**Issue by nithdi** [Raizlabs/DBFlow#194]
Hi,
I am using DBFlow for a few months now and it's great so far! However, I noticed that my projects take quite longer to compile when using it.
Is there anything I can do to gain some performance? Can you explain what affects the performance the most?

Thank you.

**Comment by Rainer-Lang** [comment]
Same here: Compile time increased from about 20/25 seconds with Ollie to about 2 minutes with DBFlow.
A friend of mine had the same problem and then changed to another orm-lib. Here: DBFlow about 90 seconds and for the other lib 8 seconds.

**Comment by fhur** [comment]
Same problem here. @agrosner If you could point to some parts of the code where you think the bottle necks might occur that would be great

**Comment by agrosner** [comment]
Its most likely the gradle fetching system for project sync is the issue here. If you try running/making the app with `--offline` it builds significantly faster.

**Comment by Rainer-Lang** [comment]
with "offline":
- normal build: 3 sec
- rebuild project: 19 sec
- start debug: mostly 5 sec

**Comment by agrosner** [comment]
You're welcome @Rainer-Lang Ill add that to the set-up steps to deviate confusion.
