### ISSUE TITLE
onTerminate()

### ISSUE THREAD

**Issue by Den-Rimus** [Raizlabs/DBFlow#195]
Hey there!

Surprisingly didn't find this in the issues.

Your docs say about putting `FlowManager.destroy()` method in `onTerminate()` callback of `Application` class.
But [android docs](http://developer.android.com/reference/android/app/Application.html#onTerminate()) say this:
> This method is for use in emulated process environments. It will never be called on a production Android device, where processes are removed by simply killing them; no user code (including this callback) is executed when doing so.

So - should we run `FlowManager.destroy()` anywhere at all and, if so - where?

**Comment by agrosner** [comment]
good point. This is something I forgot about. No, not really needed. It only releases its hold on the application Context.
