### ISSUE TITLE
"Writing Insert Statement Failed" when defining foreign key

### ISSUE THREAD

**Issue by mikescamell** [Raizlabs/DBFlow#197]
I'm following the doc examples for setting a foreign key but i persistently keep getting this error:

"java.io.IOException: Writing insert statement failed for: com.example.example.data.db.model.Accommodation. A type converter must be defined for this type, or if this field is a Model, must be a foreign key definition"

My code is:

```
@Column(columnType = Column.FOREIGN_KEY, 
    references = {@ForeignKeyReference(columnName = "accommodation", columnType = Accommodation.class, foreignColumnName = "id")}, 
    saveForeignKeyModel = false)
public ForeignKeyContainer<Accommodation> accommodation;
```

Accommodation is another Model class. 

If i override the default column name then the tables get generated but i get an error based on the changelog of version 1.8.0 where column names can't be specified for foreign keys.

Any help would be appreciated.

**Comment by agrosner** [comment]
@mikescamell the `columnType` cannot be a model class. It must be a class that can convert into a column. In this case it would be the type of the primary key of `Accommodation`

**Comment by mikescamell** [comment]
Ahhh thank you @agrosner and thank you for the library.

**Comment by mindInv** [comment]
This is Base class

@Table(tableName = Questionnaries_questionnaries_Data.TABLE_NAME, databaseName = AppDatabase.NAME)
@JsonObject
public class Questionnaries_questionnaries_Data extends BaseModel {

    public static final String TABLE_NAME = "Questionnaries_questionnaries_Data";

    @Column
    @PrimaryKey(autoincrement = true)
    public long unique_id;

    @Column
    @JsonField
    private String name;

    @Column
    @JsonField
    private String sub_name;


    @JsonField
    private List<Questionnaries_questionnaries_Sub_Child_Data> questionnaires;

    public long getUnique_id() {
        return unique_id;
    }

    public void setUnique_id(long unique_id) {
        this.unique_id = unique_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSub_name() {
        return sub_name;
    }

    public void setSub_name(String sub_name) {
        this.sub_name = sub_name;
    }

    public List<Questionnaries_questionnaries_Sub_Child_Data> getQuestionnaires() {
        return questionnaires;
    }

    public void setQuestionnaires(List<Questionnaries_questionnaries_Sub_Child_Data> questionnaires) {
        this.questionnaires = questionnaires;
    }
}



This is child class




@Table(tableName = Questionnaries_questionnaries_Sub_Child_Data.TABLE_NAME, databaseName = AppDatabase.NAME)
@JsonObject
public class Questionnaries_questionnaries_Sub_Child_Data extends BaseModel {

    public static final String TABLE_NAME = "Questionnaries_questionnaries_Sub_Child_Data";

    @Column
    @PrimaryKey(autoincrement = true)
    long unique_id;

    @Column
    @JsonField
    private String store_jewellery_id;


    @Column
    @ForeignKey(
            references = {@ForeignKeyReference(columnName = "questionnaries_questionnaries_sub_child_data_new_column_id",
                    columnType = Long.class,
                    foreignColumnName = "unique_id")},
            saveForeignKeyModel = false)
    Questionnaries_questionnaries_Data questionnaries_questionnaries_data;

    @Column
    @JsonField
    private String jewellery_name;


    @Column
    private int wholeseller;

    @Column
    private int retailer;

    @Column
    private int houseseller;

    @Column
    private int traveller;


    public String getStore_jewellery_id() {
        return store_jewellery_id;
    }

    public void setStore_jewellery_id(String store_jewellery_id) {
        this.store_jewellery_id = store_jewellery_id;
    }

    public int getWholeseller() {
        return wholeseller;
    }

    public void setWholeseller(int wholeseller) {
        this.wholeseller = wholeseller;
    }

    public int getRetailer() {
        return retailer;
    }

    public void setRetailer(int retailer) {
        this.retailer = retailer;
    }

    public int getHouseseller() {
        return houseseller;
    }

    public void setHouseseller(int houseseller) {
        this.houseseller = houseseller;
    }

    public int getTraveller() {
        return traveller;
    }

    public void setTraveller(int traveller) {
        this.traveller = traveller;
    }


    public String getJewellery_name() {
        return jewellery_name;
    }

    public void setJewellery_name(String jewellery_name) {
        this.jewellery_name = jewellery_name;
    }

    public long getUnique_id() {
        return unique_id;
    }

    public void setUnique_id(long unique_id) {
        this.unique_id = unique_id;
    }
}


I am getting foreign key null.Please get rid out of it.Thanks in advance.
