### ISSUE TITLE
save() can insert two objects

### ISSUE THREAD

**Issue by FredJul** [Raizlabs/DBFlow#198]
First of all, thank you for this awesome lib!

Unfortunately, I've encountered an issue. Let's say you have a class defined like this:

      public class Task extends BaseModel implements Parcelable {
          @Column(columnType = Column.PRIMARY_KEY_AUTO_INCREMENT)
          public int id;
     }

If you create yourself an object with an specific id, it is inserted twice:

      Log.e("Test", "first count=" + new Select().from(Task.class).queryList().size()); // display 0
      Task test = new Task();
      test.id=23;
      test.save(false);
      Log.e("Test", "second count=" + new Select().from(Task.class).queryList().size()); // display 2 !!

In my project, I need to specify the id to restore the data from the server and keep the relations between this object and the others.

**Comment by agrosner** [comment]
@FredJul what version of the app are you using? also, what is it doing underneath, is it updating or inserting in `SqlUtils.save()`? Just curious.

**Comment by FredJul** [comment]
Hi!

I'm using the 1.8.0 version of your lib. And when I do this test, I've an empty database, so the save is inserting two items.

Do you think that's a possible thing or did I missed something?

**Comment by agrosner** [comment]
@FredJul I would not try to keep autoincrementing column ids for previously stored data. I'd rather just make it a general primary key. No matter what happens, if you call `save()` on that object where `id=23` does not exist, its going to insert that item into the database and get a new `id` value.
