### ISSUE TITLE
Select with custom columns (and problems with inner join)

### ISSUE THREAD

**Issue by pboos** [Raizlabs/DBFlow#199]
I am doing a more complex query using dbflow. Which is like this:

    From<ModelN> from = new Select().from(ModelN.class).as("N")
            .join(ModelS.class, Join.JoinType.INNER).as("S")
            .on(Condition.column("N." + ModelN$Table.ID).is(
                   "S." + ModelS$Table.NID))
            .groupBy(new QueryBuilder()
                   .appendQuotedArray(groupBy, ModelS$Table.NID))
            .orderBy(groupBy + ", " + ModelN$Table.DATE + " DESC");

This basically gets all ModelNs that have one or multiple ModelS linked to it.

Now the first problem is, that both models have a ID. And sadly the id returned is the one from the joined table (which logically is wrong).

Next problem is:
In the same query I would like to have a count over the number of items linked to it. In SQL that works fine. I just set the columns to:

    N.*, count(DISTINCT S.NID)

Now trying to do this with ```new Select("N.*, count(DISTINCT S.NID)")``` doesn't work. Because it expects single columns and quotes them. Giving a list of columns like the following, doesn't work either.

    new Select(new String[]{"N.*","count(DISTINCT S.NID)"})

Reason is, that it adds grave accents around each column. So it becomes ``` `N`.`*`, `count(DISTINCT S.NID) as count` ```.  Which then will result in column not found errors. This is done [here in Select.java:218](https://github.com/Raizlabs/DBFlow/blob/master/library/src/main/java/com/raizlabs/android/dbflow/sql/language/Select.java#L218).

I have an idea of a workaround that uses the created WHERE and creates a new ModelQueriable that removes all from between SELECT and FROM and replaces it with the correct form and pass it to FlowCursorList which I use and iterate over to get the item + the additional column through the cursor. Will post my "workaround" when it is working.

This bug is related to #67 (but goes further than just simple joins).

**Comment by pboos** [comment]
Here is the class I set up to use. Now I do not get the error and I can do everything I want. Would be nice to have support for that though. Basically a new Select(columns) one that does not add the grave accents.

Usage:
```
String[] columns = new Select(new String[]{"N.*" , "count(DISTINCT S.NID)"});
new CustomColumnsModelQueriable<>(where, columns).queryCursorList()
```

CustomColumnsModelQueriable.java
```
import com.raizlabs.android.dbflow.config.FlowManager;
import com.raizlabs.android.dbflow.list.FlowCursorList;
import com.raizlabs.android.dbflow.list.FlowTableList;
import com.raizlabs.android.dbflow.sql.ModelQueriable;
import com.raizlabs.android.dbflow.sql.language.Where;
import com.raizlabs.android.dbflow.structure.Model;

import org.apache.commons.lang3.StringUtils;

import android.database.Cursor;

import java.util.List;

public class CustomColumnsModelQueriable<ModelClass extends Model>
        implements ModelQueriable<ModelClass> {

    private final Where<ModelClass> mWhere;

    private final String mQuery;

    public CustomColumnsModelQueriable(Where<ModelClass> where, String... columns) {
        mWhere = where;
        mQuery = where.getQuery().replaceFirst("SELECT .* FROM",
                "SELECT " + StringUtils.join(columns, ", ") + " FROM");
    }

    @Override
    public Cursor query() {
        Cursor cursor = null;
        cursor = FlowManager.getDatabaseForTable(mWhere.getTable()).getWritableDatabase()
                .rawQuery(mQuery, (String[]) null);
        return cursor;
    }

    @Override
    public Class<ModelClass> getTable() {
        return mWhere.getTable();
    }

    @Override
    public FlowCursorList<ModelClass> queryCursorList() {
        return new FlowCursorList<>(false, this);
    }

    // ones below are all unused in FlowCursorList

    @Override
    public List<ModelClass> queryList() {
        // not used in FlowCursorList
        throw new UnsupportedOperationException("Not implemented");
    }

    @Override
    public ModelClass querySingle() {
        // not used in FlowCursorList
        throw new UnsupportedOperationException("Not implemented");
    }

    @Override
    public FlowTableList<ModelClass> queryTableList() {
        // not used in FlowCursorList
        throw new UnsupportedOperationException("Not implemented");
    }

    @Override
    public void queryClose() {
        // not used in FlowCursorList
        throw new UnsupportedOperationException("Not implemented");
    }
}
```

**Comment by agrosner** [comment]
@pboos this is in the works in #47 . It's slated for `2.0.0`, but that will also mark some breaking changes to the lib. Its not going to be released for at least a few weeks.

**Comment by pboos** [comment]
Glad to hear that! thx for the great work!

**Comment by darkovski88** [comment]
@agrosner maybe im silly but im not fully clear with this issue... is milestone 2.0 done? Im having this issue now.. When i do join and getting a object id they are 1,2,3.. how can I solve this? Thanks
