### ISSUE TITLE
Join#as() does not return correct type for chaining

### ISSUE THREAD

**Issue by davidschreiber** [Raizlabs/DBFlow#20]
`com.raizlabs.android.dbflow.sql.language.Join#as` returns the generic type `Join` (without the *type variables* `ModelClass` and `FromClass`) which leads to IDE warnings.

In order to fix this problem the signature of the method needs to be changed from this

	public Join as(String alias)
	    
to this

	public Join<ModelClass, FromClass> as(String alias)

**Comment by agrosner** [comment]
@davidschreiber I really appreciate these kind of issues. If you notice any kind of these issues in the future, please send a pull request my way and I can reference you in a change log! Thus it will also make you a contributor.

Anyways this is a simple fix I will include in 1.1.6
