### ISSUE TITLE
Want to add a new TypeConverter, but "import android.net.Uri" fails

### ISSUE THREAD

**Issue by Rainer-Lang** [Raizlabs/DBFlow#200]
I forked the project and added a new file to TypeConverter - to make a pr.
But the import android.net.Uri cannot be resolved...

**Comment by agrosner** [comment]
This sounds like an issue on your end. If the import fails, its for another reason.

**Comment by Rainer-Lang** [comment]
@agrosner I'm using "android.net.Uri" within my projects - all is fine.
If I want to import this to a TypeConverter within DBFlow - it fails.

Maybe it's possible to send you the TypeConverter file and you could integrate it in DBFlow - the import doesn't also fail for you?

**Comment by agrosner** [comment]
AH! Its a java project where the default `TypeConverter` live. You'll need to just include it in the project you're using and add the `@TypeConverter` annotation.

**Comment by Rainer-Lang** [comment]
Is it possible to include the new converter in DBFlow?
Makes more sense to me...
