### ISSUE TITLE
Exclude a field from being updated with save(async) or update(async)

### ISSUE THREAD

**Issue by simernes** [Raizlabs/DBFlow#201]
Is it possible to exclude a field while using these functions, rather than writing a manual query? I ask this because of a reference column that may change asynchronously and I'd like to not have to maintain a manual query if more columns are added to my data model.

If the reference column changes while the data model is loaded in memory, a simple call to save or update would overwrite the changed column to what it was when it was loaded to memory I presume, correct?

**Comment by agrosner** [comment]
@simernes No. It generates an update and insert statements for all fields. Yes, if you save the object and it contains a different value than somewhere else, its potentially will change. The best bet it to use an `Update()` query with the fields you want to use. The risk is leaving out fields in update query, for example a primary key, is that it can touch other rows. In this case if its a simple field, no harm no foul.

**Comment by agrosner** [comment]
Actually May I ask for your `Model` and what field is changing?

**Comment by simernes** [comment]
Here's an example. I have a server and client system (communicate over http) where the clients can create DataValues like the class provided and upload to the server. The server then generates a random string for serverId and returns it to the client. 
The client generates a dummy serverId while it is yet to be synced with server, because the clients can go offline for longer periods of time. 

The problem is that if a DataValue object is loaded in memory and edited while it is simultaneously being synced with the server, there is a potential for the client to overwrite the reference received from the server.

I understand it's a very specific problem and I guess if there's no support for it then a manual update query will work.

    @Table
    public class DataValue extends BaseModel {
        @Column(columnType = Column.PRIMARY_KEY_AUTO_INCREMENT)
        public long localId;

        @Column(unique = true)
        public String serverId;

        @Column
        public String value;
    }

**Comment by agrosner** [comment]
I guess I am going to work on a feature to enable custom `Model` classes that aren't treated as tables, but rather as simple "query" models that can interact with the database as if they were.
