### ISSUE TITLE
Concurrent access with async=false results in deadlock

### ISSUE THREAD

**Issue by simernes** [Raizlabs/DBFlow#202]
When accessing the database concurrently I get a deadlock with exceptions looking like this:

    SQLiteConnectionPool﹕ The connection pool for database '/data/data/org.me.myapp/databases/database.db' has been unable to grant a connection to thread 1 (main) with flags 0x6 for 30.001001 seconds.
    Connections: 0 active, 1 idle, 0 available.
    SQLiteConnectionPool﹕ The connection pool for database '/data/data/org.me.myapp/databases/database.db' has been unable to grant a connection to thread 781 (Thread-781) with flags 0x1 for 30.002 seconds.
    Connections: 0 active, 1 idle, 0 available.

And it keeps waiting until the app crashes.

It's a little hard to debug but so far I've narrowed it down to this:
- Deadlock occurs when trying to save(async=false) with two concurrent threads.
- Deadlock occurs when trying to query from the db in one thread while saving with async=false in another.

I haven't tried with more than two concurrent threads. I don't think I would get the same deadlock if I was adding the queries to the TransactionManager, but unfortunately I can't do that in this case.

This is a critical problem for our project so I hope there can be some kind of resolution.

**Comment by agrosner** [comment]
@simernes This may be related to #183 . So it's possible theres a `synchronized` deadlock occuring. the fix is on `develop` if you need to get this fixed today/tomorrow. I can't guarantee 1.8.1 will be out tonight, but I'll try.

**Comment by simernes** [comment]
@agrosner Ok, you don't have to rush for it to be implemented today. If it's a known issue and already being worked on that's fine, but obviously the sooner it's fixed the better.

**Comment by agrosner** [comment]
@simernes actually if you had time to see if it works on `develop` I will know that the issue is truly fixed.

**Comment by simernes** [comment]
@agrosner I can't today unfortunately maybe tomorrow. Can I do that easily with gradle somehow?

**Comment by agrosner** [comment]
@simernes not easily, you would have to clone project as submodule and import using local gradle syntax. and ensure its on `develop` branch.

**Comment by simernes** [comment]
@agrosner if 1.8.1 will be released this week anyways I think I'll just wait thanks

**Comment by simernes** [comment]
Ok so I've been trying to test with the develop branch locally but I get errors for incompatible java versions (major.minor version 52 error) when I try to open the gradle project, and I also get this when I try to include the project locally into my project.

    Error:Could not GET 'https://raw.github.com/Raizlabs/maven-releases/master/releases/null/compiler/'. Received status code 400 from server: Bad Request
    Enable Gradle 'offline mode' and sync project

@agrosner any chance 1.8.1 will be out this week?

**Comment by agrosner** [comment]
What's your build.gradle look like? Not sure yet about `1.8.1` I can try tonight to finish what I need for it. The release will bump up to `1.9.0` since I am adding a new feature.

**Comment by simernes** [comment]
Ok I see.

I have 

    compile project(':..:DBFlow:app') 
replacing 

    apt 'com.raizlabs.android:DBFlow-Compiler:1.8.0'
    mod "com.raizlabs.android:{DBFlow-Core, DBFlow}:1.8.0"

in build.gradle

**Comment by agrosner** [comment]
1. You should not be compiling the test application.
2. you need to compile all artifacts: 

```groovy
apt project(':..:compiler')
compile project(':...:library')
compile project(':...:flowcore')
```

**Comment by agrosner** [comment]
Also you need to specify the `dbflow_project_prefix=` in your `gradle.properties` so the inner projects can reference each other properly.

**Comment by simernes** [comment]
Ok great thanks. If I have time tomorrow I'll try it out
