### ISSUE TITLE
How to dynamic generate database using DBFlow?

### ISSUE THREAD

**Issue by ExtremeWill** [Raizlabs/DBFlow#203]
My app need to offer each login user a different db. For example, generate user001.db for user1,user002.db for user2 and so on.
How to achieve this goal with DBFlow?

**Comment by agrosner** [comment]
Not sure if thats possible with DBFlow. It relies on you knowing the name of the database ahead of compile time. Dynamic DBs are not supported. I can see how this is potentially useful, but not supported as of now.
