### ISSUE TITLE
DBFlow with private fields solution

### ISSUE THREAD

**Issue by Noah-Huppert** [Raizlabs/DBFlow#205]
So I was reading the docs and it said something about how all model fields must be public for DBFlow to work. I think I may of come up with a solution to this by using java reflection.

Private Test Class
```java
package com.noahhuppert.reflect;

public class TestPrivateClass {
    private String f1;
    private int f2;

    public TestPrivateClass(){
        f1 = "f1value";
        f2 = 2;
    }
}
``` 

Accessing the private fields
```java
TestPrivateClass testPrivateClass = new TestPrivateClass();

Field[] fields = testPrivateClass.getClass().getDeclaredFields();

for(Field f : fields){
    boolean pastAccess = f.isAccessible();

    if(!pastAccess){
        f.setAccessible(true);
    }

    try {
        Object fValue = f.get(testPrivateClass);
        System.out.println(f.getType() + " " + f.getName() + " = " + fValue);
    } catch(IllegalAccessException e){
        System.out.println("FAILED TO ACCESS: " + f.getName());
    }

    if(!pastAccess){
        f.setAccessible(false);
    }
}
```

The output ends up being 
```
04-18 15:53:37.611  29590-29590/com.noahhuppert.reflect I/System.out﹕ class java.lang.String f1 = f1value
04-18 15:53:37.611  29590-29590/com.noahhuppert.reflect I/System.out﹕ int f2 = 2
```

Would this work as a solution? Or am I missing something?

**Comment by agrosner** [comment]
We definitely do not want to use reflection in this library. The main reason this library was created is to not use it for performance and readability reasons. You should either declare them `public` or package private so the generated adapters have direct access to the fields. I may add a feature that enables you to define methods that are "column accessors" but thats not a priority right now.

**Comment by Rainer-Lang** [comment]
" I may add a feature that enables you to define methods that are "column accessors" but thats not a priority right now."
Would be nice.
