### ISSUE TITLE
How do we get MAX function in DBFlow ?

### ISSUE THREAD

**Issue by javajack** [Raizlabs/DBFlow#209]
I am new to DBFlow.

I am not able to find a MAX equivalent in DBFLow. I can see that there is an avg and sum functions.

Am I missing something ?

One more question, How to we ignore errors in case of duplicate inserts ( same primary key ) while performing BATCH save operation on a model collection ?

**Comment by agrosner** [comment]
@javajack 
1. `new Select().method("MAX", columnName)...`
2. You can do either two things: (https://github.com/Raizlabs/DBFlow/blob/master/usage/DBStructure.md#global-insertconflict-and-updateconflict) or provide it on a `@Table` by table basis.

**Comment by javajack** [comment]
hanks for both the answers, it was quick :)

I don't understand the statement though..
"You can apply global values to each table (when not explicitly specified) by defining the insertConflict() and updateConflict()"

Are these supposed to be attributes in table definition ? Any example in documentation ?
Or may be a rough example of that table annotation/attribute here in comments section would be great !

I am intending to update values upon conflict in insert based on primary key.
