### ISSUE TITLE
on save() foreign key can't be null

### ISSUE THREAD

**Issue by OptimistNot** [Raizlabs/DBFlow#213]
Hi!
Im trying to save jsonmodel and passing some foreign keys that has null values as a relation is not defined yet. I got NullPointerException in bindToStatement in $Container. How do i allow it to save null values in foreign keys? (i tried these: notNull = false, saveForeignKeyModel = false, still no results)

Thanks

**Comment by agrosner** [comment]
Hey can you send me what your model looks like? thank you.

**Comment by OptimistNot** [comment]
http://pastebin.com/KZ6rbw8A
where AQL and Supplier foreign keys can have null values

**Comment by agrosner** [comment]
It's a bug. I will add a check to ensure that the getValue is not null for the `ModelContainer` as foreign key. Also adding unit test here.

**Comment by agrosner** [comment]
Nice find!

**Comment by OptimistNot** [comment]
Meanwhile is there any quick fix? Thanks in advance.

**Comment by agrosner** [comment]
@OptimistNot not for such an error. Can you send me the `$Container` generated class as well and line number its failing on? thanks

**Comment by OptimistNot** [comment]
http://pastebin.com/sLV4UxLw on lines 145-148

**Comment by agrosner** [comment]
Also can you ensure all inner classes have `@ContainerAdapter` annotatons?

**Comment by agrosner** [comment]
NVM. It may be a conversion from a null `Long` to a `long`

**Comment by OptimistNot** [comment]
Maybe, but there is nothing i can do about it. If i have null value there is no long foreign key to look for. I tried today to fork dbflow and include in my project to change columndefinition class to add if null condition for container but i really stuck with it...
I cant get Android studio to include the module, and i need a fast solution.

Andrew G <notifications@github.com> escreveu:

NVM. It may be a conversion from a null `Long` to a `long`

---

**Comment by agrosner** [comment]
@OptimistNot its going to be fully fixed in `2.0.0` now. I had to rewrite the underlying code generator and consequently does some breaking changes (but for consitency and the better) so 2.0.0 should be released soon instead of `1.9.0`

**Comment by agrosner** [comment]
hopefully EOD tomorrow or Monday

**Comment by OptimistNot** [comment]
Thank you for your quick response! Sorry hurry u up... Waiting for 2.0.0 to be released as soon as possible :)
Thanks!
