### ISSUE TITLE
[Question] Executing transactions in current Thread.

### ISSUE THREAD

**Issue by Araz-Abishov** [Raizlabs/DBFlow#214]
First of all, many-many thanks for developing such awesome library!. 

Is there any way to execute transactions by means of TransactionManager in current thread (in thread where call to TransactionManager.getInstance().save(ProcessModelInfo.withModels(models)) is made) ?

**Comment by agrosner** [comment]
`new SaveModelTransaction<>(ProcessModelInfo.withModels(models)).onExecute();` 
for `2.0.0` I will force you to use the classes vs. static methods on the `TransactionManager`, such that the statement you mentioned above becomes:

```java

TransactionManager.getInstance().addTransaction(new SaveModelTransaction<>(ProcessModelInfo.withModels(models)));
```

**Comment by Araz-Abishov** [comment]
Alright, thanks very much!
