### ISSUE TITLE
"onDelete = ForeignKeyAction.CASCADE" with no effects

### ISSUE THREAD

**Issue by YSDC** [Raizlabs/DBFlow#216]
I try to use the "onDelete" with ForeignKeyAction.CASCADE but without success. I have the following annotation in a class that we will call MyClass:

```
    @Column(columnType = Column.FOREIGN_KEY, references = {@ForeignKeyReference(columnName = FIELD_MEDIA, columnType = Long.class, foreignColumnName = "id")}, onDelete = ForeignKeyAction.CASCADE, saveForeignKeyModel = false, uniqueGroups = 1)
    protected Media media;
```

But when i do this

```
        new Delete().from(MyClass.class).query();
```

The Media is not deleted. Any idea why?

**Comment by agrosner** [comment]
@YSDC do you have foreign key constraints turned on? `@Database(foreignKeysSupported = true)` ?

**Comment by YSDC** [comment]
Yes sure:
```
@Database(name = DatabaseHelper.DBNAME, version = BuildConfig.DATABASE_VERSION, foreignKeysSupported = true)
public class DatabaseHelper {
```

**Comment by YSDC** [comment]
Let me know if you need any more information to help me, it's a bit blocking this cascade, and I don't want to do an ugly loop to remove manually all items :(

I tried also to remove the 'uniqueGroups' but it changed nothing.

**Comment by YSDC** [comment]
Should the 'ModelAdapter' generated contains anything special related to the onDelete annotation? something i could check if present?

**Comment by agrosner** [comment]
What version of Android is this running on?

**Comment by YSDC** [comment]
Thanks for your answer. I tried on different phones that were 4.x
I will give you a more precise version in the next 24 hours.
I have created a sample project with the minimum of classes, I can send it to you if you want

**Comment by dudadayan** [comment]
Hey, 
can you please update if you solved this issue?

**Comment by ydanneg** [comment]
This should work in other way, if you do
    new Delete().from(Media.class).query();
then related MyClass records will be deleted.

**Comment by ydanneg** [comment]
After several failed attempts using foreign keys I found the way to implement One-To-One relationship using OneToMany annotation.

User.java
```
@Table(tableName = "Users", databaseName = "mydb")
@ModelContainer
public class User extends BaseModel {

    @Column(name = "id")
    @PrimaryKey(autoincrement = true)
    private long id;

    @Expose
    // should be non-private due to the DBFlow compiler limitation
    /*private*/ UserProfile userProfile;

    @OneToMany(methods = {OneToMany.Method.ALL})
    public UserProfile getUserProfile() {
        if (userProfile == null) {
            userProfile = new Select().from(UserProfile.class)
                    .where("userId=?", id).querySingle();
        }
        return userProfile;
    }

    @Override
    public void save() {
        if (userProfile != null) {
            userProfile.setUserId(id);
        }
        super.save();
    }
}
```
UserProfile.java
```
@Table(tableName = "UserProfiles", databaseName = "mydb")
public class UserProfile extends BaseModel {
    @Column(name = "id")
    @PrimaryKey(autoincrement = true)
    private long id;

    @Expose
    @Column(name = "firstName")
    private String firstName;

    @Column(name = "userId")
    @NotNull
    @Unique(onUniqueConflict = ConflictAction.REPLACE)
    private long userId;
}
```

OneToManyValidator does not validate the filed type have to be a List.
So that became possibly to user this annotation for non List variable :)

Example use:
 ```
    // create
    UserProfile profile = new UserProfile();
    User user = new User();
    user.setUserProfile(profile);
    user.save(); // saves also a userProfile

    // load
    User user = new Select().from(User.class).querySingle();
    user.getUserProfile(); // not null, loaded from DB

    // modify
    user.getUserProfile().setFirstName("john");
    user.save(); // saves also a userProfile

    // delete
    user.delete(); // deletes user and associated userProfile
 ```

@agrosner Is it possible by default to use gettters and setters to get access to private memebrs in generated code?
@agrosner The provided "OneToOne" solution still uses *ModelListTransaction to modify sub-models. Maybe there is a reason to add OnToOne annotation?

**Comment by flywheelms** [comment]
+1
OneToOne annotation

**Comment by faken** [comment]
I was wondering what's currently the preferred way of making a OneToOne-Relation work. I'm struggling with getting it to work when I'm following the current Document of DBFlow 4.0.4.
