### ISSUE TITLE
`new Select().from(Table.class).count();` returning incorrect value

### ISSUE THREAD

**Issue by spierce7** [Raizlabs/DBFlow#221]
If I create 5 objects to the database, and then call `.delete(false)` on them, `new Select().from(Table.class).count();` will still return 5, even after the app been killed. It's an always incrementing number for some reason.

At the same time if I call `new Select().from(ReaderTab.class).where().queryList().size();` it will return 0.

if I add another object to the database, the first call would return 6, and the second call would return 1. I would expect these values to be in sync. The documentation seems to indicate this as well.

Any idea what could be going on?

**Comment by agrosner** [comment]
did you try `new Select().count().from(Table.class).count()`

**Comment by spierce7** [comment]
No I did not. I'll try that and get back to you.

**Comment by spierce7** [comment]
That seems to work. My misunderstanding. Thanks :-)

**Comment by tuckercr** [comment]
The above didn't work for me in v4.0.4.  What did was:
```
new Select(Method.count()).from(Contact.class).count()
```
