### ISSUE TITLE
can you push the repo jar to the maven?

### ISSUE THREAD

**Issue by jiqimaogou** [Raizlabs/DBFlow#224]
If I do like this:
```
  allprojects {
    repositories {
        maven { url "https://raw.github.com/Raizlabs/maven-releases/master/releases" }
    }
  }
```
all project will search other dependencies again in the github, it make compile so slow.

**Comment by pboos** [comment]
I totally agree. What is the reason for not publishing it to maven?

**Comment by agrosner** [comment]
If you turn on `offline mode` there is no difference. We may move it to maven central/bintray eventually, but not yet.

**Comment by agrosner** [comment]
Related to #277 , we will in the next release, so keep your fingers crossed ;)
