### ISSUE TITLE
How can i cast String to int

### ISSUE THREAD

**Issue by imosmanyilmaz** [Raizlabs/DBFlow#228]
Hello this is my query
List<Fields> someObjectList = new Select().from(Fields.class).where(queryBuilder).orderBy(true, Fields$Table.ORDERINDEX).queryList();

i want to get list order by ORDERINDEX . However ORDERINDEX type is string and data is not ordered correctly. How can i simply cast it "integer".

edt: 

like this...
select * from fields where formID='170' order by cast(orderIndex as int)

**Comment by agrosner** [comment]
http://stackoverflow.com/a/11489098/3911006

**Comment by agrosner** [comment]
```java
List someObjectList = new Select()
  .from(Fields.class)
  .where(queryBuilder)
  .orderBy("CAST(" + Fields$Table.ORDERINDEX + " AS INTEGER)")
  .queryList();
```

**Comment by imosmanyilmaz** [comment]
Thanks !
