### ISSUE TITLE
ModelView troubles

### ISSUE THREAD

**Issue by wongcain** [Raizlabs/DBFlow#23]
I having a problem using a ModelView.  I have traced the problem to these lines in the convertToModel method in SqlUtils:

```
                    Class persistentClass = (Class) ((ParameterizedType) table.getGenericSuperclass()).getActualTypeArguments()[0];
                    if (persistentClass.isAssignableFrom(BaseModelView.class)) {
                        model = (ModelClass) FlowManager.getModelViewAdapter((Class<? extends BaseModelView<? extends Model>>) table).loadFromCursor(cursor);
                    }
```

The problem is that `persistentClass` gets assigned to the class of the *real* table rather than the class of the *view*, but then is checked to see if it extends BaseModelView.  As a result, `model` always returns as null. Shouldn't you instead be checking if `table` extends this class?

**Comment by agrosner** [comment]
Is there a specific exception or error? I need more info on whats going wrong

**Comment by wongcain** [comment]
I am trying to use the FlowCursorList with my ViewModel.   I instantiate it like this:
```
cursorList = new FlowCursorList<MyView>(true, MyViewModel.class);
```
This creates the cursorList without error.  And doing a `cursorList.getCount()` returns the number I would expect.  The problem comes when I try `MyViewModel item = cursorList.getItem(i);`   This always returns a `null`.

I stepped through the code here, and as I said, the problem seems to be in the `SqlUtils.convertToModel` method.  On line 120, the `persistentClass` always gets set as the class of the actual `Model` and not the `ModelView`, and therefore always fails the check on line 121.

**Comment by wongcain** [comment]
I just submitted a pull request with the fix for this.  I didn't update your test coverage, but I did testing on my end.

**Comment by agrosner** [comment]
Interesting issue, I had never thought of using the ```FlowCursorList``` with a ```ModelView```. I will write a test for this and merge in your pull request once I see that it works as expected. Thank you!
