### ISSUE TITLE
[Question] Proper way to use FlowContentObserver?

### ISSUE THREAD

**Issue by rdzha** [Raizlabs/DBFlow#231]
We have FlowContentObserver which can send finegraned notifications about CRUD operations on model, which is great. But I cannot figure out the way to use it, because these notifications do not have any identifier of what actually was changed. It would be great if notifications included model id, or, even better, row number. That would allow us to map model notifications to RecyclerView.Adapter.

**Comment by agrosner** [comment]
Not a bad idea. It does beg the question when we have complex/composite primary keys...do we then require the `Model` used in this instance to have one primary key only? Its quite possible.

**Comment by glureau** [comment]
I have the same problem, I would have the changed object (since I think we have the id in the uri, it looks pretty obvious to return the targeted element instead of the entire table).
Is there some news in this direction?

**Comment by mayur-mi** [comment]
Hi there.. Can you suggest a way to use the library to observe for the changes in a batch save operation?

**Comment by agrosner** [comment]
@mayur-mi added in `2.0` I think the ability to batch `Transactions`:

```java

flowContentObserver.beginTransaction();

// do the 1000 objects

flowContentObserver.endTransactionAndNotify();

```

Also more precise Uris are coming in `2.2`, however your table must only contain one Primary key. :)
