### ISSUE TITLE
Define inherited properties as columns

### ISSUE THREAD

**Issue by simernes** [Raizlabs/DBFlow#232]
Would it be possible to implement functionality so that it's possible to define columns at the top of the class definition rather than having the annotations above the individual columns? I ask this because it would be great to be able to define tables without having to intrude on lets say a data model that may or may not be shared between different projects. 

So for example define a table like this:

    @Table
    @Column(property = name, columnType = Column.PrimaryKey)
    @Column(property = age)
    public class TablePerson extends Person {
    }

    public class Person {
    private String name;
    private int age;
    }

I guess it would be a problem with extending the BaseModel though..

**Comment by agrosner** [comment]
Interesting idea. The only thing I have to say is that the annotation processor needs access to private fields...Either through the `getter/setter` of field names or package private/public access.

**Comment by simernes** [comment]
I'm sure it's gonna be a bit of work to implement but at least the way I see it, it would be very useful. For example, we're working on a project where we're passing objects between apps where one app acts as a persistence data store, and other apps would just use the same data models, but share the persistence.

**Comment by agrosner** [comment]
@simernes will add this in 2.1.0

**Comment by simernes** [comment]
Are classes still required to extend the BaseModel class to be able to work as a table?
