### ISSUE TITLE
Support to use dbflow in multiple processes

### ISSUE THREAD

**Issue by pboos** [Raizlabs/DBFlow#237]
I am using dbflow in the application and in a separate process which is responsible for syncing data with a server. In both I need database access.
The problem is that when both processes are trying to use the database at the same time it results in a SQLiteDatabaseLockedException. Is there a way to wait until the database is not locked anymore? Or any other support to avoid this problem?

**Comment by agrosner** [comment]
Interprocess access of the database becomes complicated as they require communication to be synchronized. I would say 
A. use `@ContentProvider` classes to manage the interprocess access or
B. Create a `Service` that acts as the connection between the two processes' access to the database. There also might be more ways to solve this.
