### ISSUE TITLE
[1.8.1] After resetting a DB the new DB instance is read only

### ISSUE THREAD

**Issue by rjam** [Raizlabs/DBFlow#238]
After a database is reset using ```FlowManager.getDatabase(Db.NAME).reset(context);```, following attempts to write to the DB will throw the following exception:
```java.lang.RuntimeException: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)```.

I've been getting this on a Nexus 5 running 5.1. I've found this [issue](https://code.google.com/p/android-developer-preview/issues/detail?id=1189) reported for the L-preview, but couldn't find any follow up so I'm not sure if this is still the case.

**Comment by rjam** [comment]
According to some posts on SO (see comments [here](http://stackoverflow.com/a/4420083/641018)), I believe this may be fixed by closing the DB connection before deleting the database, through [SQLiteOpenHelper.close()](http://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html#close). I've tried completely closing the app after using the current reset method and indeed the problem no longer occured. 

Unfortunately the ```getHelper()``` method on BaseDatabaseDefinition isn't public, so I wasn't able to test it myself.

**Comment by andrecrispim** [comment]
This still occurs in version 2.0

**Comment by andrecrispim** [comment]
A little workaround for version 2.0, just to hold the helper and close the database using it:

	/**
	 * Sql open helper
	 *
	 * @author andre.moreira
	 */
	public class SqlOpenHelper extends FlowSQLiteOpenHelper{

		private volatile static SqlOpenHelper helper;

		/**
		 * @return The current helper created by FlowManager
		 */
		public static SqlOpenHelper getCurrent() {
			return helper;
		}

		public SqlOpenHelper(BaseDatabaseDefinition flowManager, DatabaseHelperListener listener) {
			super(flowManager, listener);
			helper = this;
		}
	}

**Comment by agrosner** [comment]
this may be outdated. If its still broken on 3.0.0-beta3 or higher, reopen new issue. Thank you
