### ISSUE TITLE
can I have a column with auto increment but not primary key?

### ISSUE THREAD

**Issue by jiqimaogou** [Raizlabs/DBFlow#239]

**Comment by jiqimaogou** [comment]
I want it record the insert order.

**Comment by agrosner** [comment]
No its not possible in SQLite: `ny attempt to use AUTOINCREMENT on a WITHOUT ROWID table or on a column other than the INTEGER PRIMARY KEY column results in an error.`
 (https://www.sqlite.org/autoinc.html). You could do an `Insert` query or by using a `Trigger` [here] (http://stackoverflow.com/questions/6982173/sqlite-auto-increment-non-primary-key-field)
