### ISSUE TITLE
Best approach when working with existing SQLite database

### ISSUE THREAD

**Issue by PiXeL16** [Raizlabs/DBFlow#242]
Hi, 
Was just wondering if there is a suggested approach when working with a existing data with DBFlow?
I will like to ship my app with a lot of existing data. Should I copy my .db from assets to db folder in first launch or is there anything better I can do? 
Thanks!

**Comment by agrosner** [comment]
yeah 

We assume your database file is named "Example.db"

1. you should prepackage the database by placing it in the `src/assets/Example.db` 

2. create a database placeholder class:

```
@Database(name = MyDatabase.NAME, version = MyDatabase.VERSION)
public class MyDatabase {

  public static final String NAME = "myPrepackagedDatabaseName";

  public static final int VERSION = 3; // this should refer to the version of the existing db

}

```

3. Create all the `@Table` classes that refer to the prepackaged db, otherwise modifications may not match up, leading to SQLiteExceptions everywhere.

**Comment by agrosner** [comment]
I hope this helps!

**Comment by mehere** [comment]
@agrosner 
seems this is not working. Still requires to **Initialize FlowManager**
However, if we initialize the FlowManager, the database file under _assets_ is not copied to _data/data/\<app\>/databases_ but an empty DB is created there

**Comment by Motoharujap** [comment]
same thing here as @mehere mentioned. database copied to assets folder is not used, empty DB is created instead

**Comment by julianfalcionelli** [comment]
Same, the Prepackaged Database feature is not working.
Copying manually the db file will not work on none-root devices, right ?

**Comment by julianfalcionelli** [comment]
Apologies, I was with the version 3.0, in the version 3.1.1 that worked perfectly. Thanks!
