### ISSUE TITLE
How to write function in where clause..

### ISSUE THREAD

**Issue by wintersandroid** [Raizlabs/DBFlow#249]
I am attempting to write the query, the problem being the date function..
while compiling: SELECT SUM(`TOTAL`)  FROM `WALLET_ORDERS` WHERE `ACCOUNT_ID`=15 AND `STATUS`='charged' AND date(PAYMENT_DATE)='2015-05-24',

Currently trying
```
 Cursor cursor = new Select().method("SUM",WalletOrdersTable$Table.TOTAL)
        .from(WalletOrdersTable.class)
        .where(Condition.column(WalletOrdersTable$Table.ACCOUNT_ID).eq(accountId))
        .and(Condition.column(WalletOrdersTable$Table.STATUS).eq(WalletOrdersTable.statuses.charged.name()))
        .and("date(" + WalletOrdersTable$Table.PAYMENT_DATE + ")", SharedFunctions.dateToDBString(date) )

        .query();
```

Have tried other iterations, but I cant seem to figure out how to use the date function on the column condition without ending up with extra single quotes around 'date(payment_date)'

payment_date is a timestamp (database formatted)..

Seem to get the following or some vairation of..

no such column: date(PAYMENT_DATE) (code 1): , while compiling: SELECT SUM(`TOTAL`)  FROM `WALLET_ORDERS` WHERE `ACCOUNT_ID`=15 AND `STATUS`='charged' AND `date(PAYMENT_DATE)`='2015-05-24',

:)

**Comment by agrosner** [comment]
I guess I can make a more clear `function` method or something to make it easier to queries like that. You can do `Condition.column(ColumnAlias.columnRaw("date(PAYMENT_DATE)"))` to achieve what you want but its not ideal...

**Comment by agrosner** [comment]
In 2.1.0, it will be as simple as:
```
date(`myColumn`)=1433872730 -> Condition.columnsWithFunction("date", "myColumn").eq(1433872730)
```
