### ISSUE TITLE
Inner join

### ISSUE THREAD

**Issue by rhespanhol** [Raizlabs/DBFlow#250]
When im doing an inner join between two tables that has some equal column names the object that is returned has values from the second column instead of the first. is this the expected behaviour?

example:

```java
Where<Category> query = new Select().from(Category.class).as("C")
  .join(Spot.class, Join.JoinType.INNER).as("S")
  .on(Condition.column("S." + Spot$Table.MCATEGORYID).eq("C." + Category$Table.MID),
        Condition.column("S." + Spot$Table.MSTATE).eq(ConstantsApi.STATE_ACTIVE) )
                .where()
                .groupBy("C." + Category$Table.MID)
                .orderBy(true, "C." + Category$Table.MORDER);
```

the category.id has the value of spot.id

**Comment by Nams29** [comment]
I have the same problem. My solution is to build and array of ColumnAlias using `ColumnAlias.columnWithTable()` (in your case with Category columns) and use the `Select(ColumnAlias... columns)` constructor.
