### ISSUE TITLE
Got java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer when parse json use JSONArrayModel

### ISSUE THREAD

**Issue by ducna01598** [Raizlabs/DBFlow#252]
I got java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer when try to parse this json : 
{"mst_areas":[{"id":"1","p_id":null,"name":"\u30d0\u30ea\u5cf6\u5168\u4f53","thumbnail":null,"created_at":"2015","updated_at":"2015","is_deleted":"0"},{"id":"2","p_id":null,"name":"\u30a2\u30e1\u30c3\u30c9","thumbnail":null,"created_at":"2015","updated_at":"2015","is_deleted":"0"},{"id":"3","p_id":null,"name":"\u30a6\u30d6\u30c9","thumbnail":null,"created_at":"2015","updated_at":"2015","is_deleted":"0"},{"id":"4","p_id":null,"name":"\u30ad\u30f3\u30bf\u30de\u30fc\u4e8c","thumbnail":null,"created_at":"2015","updated_at":"2015","is_deleted":"0"},{"id":"5","p_id":null,"name":"\u30b8\u30f3\u30d0\u30e9\u30f3","thumbnail":null,"created_at":"2015","updated_at":"2015","is_deleted":"0"}]}

Here is my code:
JSONArrayModel<Area> listArea = new JSONArrayModel<>(json.getJSONArray("mst_areas"), Area.class);
listArea.update(false);

My Model :
@Table(value = "mst_areas", databaseName = DB.NAME)
@ContainerAdapter
public class Area extends BaseCacheableModel {
    @Column(name = "id", columnType = Column.PRIMARY_KEY_AUTO_INCREMENT)
    int id;

    @Column(name = "p_id")
    int pId;

    @Column(name = "name")
    String name;

    @Column(name = "thumbnail")
    String thumbnail;

    @Column(name = "created_at")
    int createdAt;

    @Column(name = "updated_at")
    int updatedAt;

    @Column(name = "is_deleted")
    int isDeleted;
}

It seem that JSONArrayModel parser can't recognize json : {"id" : "1"...} as Int
Please help me

**Comment by agrosner** [comment]
@ducna01598 its using underneath the `JSONObject.get()` method which does not try or attempt coerce values to what you expect them to be. I'd suggest extending the existing `JSONModel` class and adding in type checking, and then creating a "copy" of `JSONArrayModel` with the same functionality. Possibly the model containers are slightly too simple and need better support. That wouldn't happen in the near future, though.

**Comment by ducna01598** [comment]
thanks i solved the issue by changing my json data. But i got a new issue that it's adding some redundant  rows after a save to a table which have relations with "mst_area" for example this table:

@Table(tableName = "spots", databaseName = BaliGuideDB.NAME)
@ModelContainer
public class Spot extends BaseCacheableModel {
...
    @Column
    @ForeignKey(references = {@ForeignKeyReference(columnType = Integer.class, columnName = "area", foreignColumnName = "id")}, onDelete = ForeignKeyAction.NO_ACTION, onUpdate = ForeignKeyAction.NO_ACTION)
    Area areaFK;
...
}

In my HomeActivity i call:
JSONArrayModel<Area> listArea = new JSONArrayModel<>(json.getJSONArray("mst_areas"), Area.class);
listArea.save(); ----> size of list area is 5 now

JSONArrayModel<Spot> listSpot = new JSONArrayModel<>(json.getJSONArray("spots"), Spot.class);
listSpot.update();------------> size of listSpot is 4, and now size of listArea is 9

what is happened ?

**Comment by agrosner** [comment]
@ducna01598 ensure that the `Area` object inside each `Spot` inside the `JSONArrayModel` is correctly populated. The JSON data must contain the proper fields. Also if the `Area` class has autoincrementing keys, that may be the case.

**Comment by ducna01598** [comment]
@agrosner I removed autoincrementing keys from all table but its not worked . Here is my JSON of Spot , don't think that it has problems:

"spots":[{"id":1,"title":"ABC\u30ab\u30d5\u30a7","area":1,"location":"139.6967912,35.6883178","description":"ABC\u30ab\u30d5\u30a7\u8aac\u660e\u6587","address":"\u795e\u5948\u5ddd\u770c\u6a2a\u6d5c\u5e02\u6e2f\u5317\u533a\u65b0\u6a2a\u6d5c 3-7-18 \u7b2c2\u4e0a\u91ce\u30d3\u30eb","publish":1,"show_at_top":1,"display_order":1,"created_at":2015,"updated_at":1432791945,"is_deleted":0},{"id":2,"title":"DEF\u30db\u30c6\u30eb","area":4,"location":"139.6967912,35.6883178","description":"DEF\u30db\u30c6\u30eb\u8aac\u660e\u6587","address":"\u795e\u5948\u5ddd\u770c\u6a2a\u6d5c\u5e02\u6e2f\u5317\u533a\u65b0\u6a2a\u6d5c 3-7-18 \u7b2c2\u4e0a\u91ce\u30d3\u30eb","publish":0,"show_at_top":1,"display_order":1,"created_at":2015,"updated_at":1432698560,"is_deleted":0},{"id":3,"title":"\u30c6\u30b9\u30c8","area":1,"location":"139.6967912,35.6883178","description":"\u30c6\u30b9\u30c8","address":"\u795e\u5948\u5ddd\u770c\u6a2a\u6d5c\u5e02\u6e2f\u5317\u533a\u65b0\u6a2a\u6d5c 3-7","publish":1,"show_at_top":1,"display_order":1,"created_at":2015,"updated_at":1432698560,"is_deleted":0},{"id":4,"title":"Test preview","area":1,"location":"139.6967912,35.6883178","description":"test preview","address":"\u795e\u5948\u5ddd\u770c\u6a2a\u6d5c\u5e02\u6e2f\u5317\u533a\u65b0\u6a2a\u6d5c 3-7-18 \u7b2c2\u4e0a\u91ce","publish":1,"show_at_top":0,"display_order":1,"created_at":2015,"updated_at":1432698560,"is_deleted":0}]

**Comment by agrosner** [comment]
massive updates in `ModelContainer` land. try in 3.0, your issues should go away since I implemented stronger type retrieval in the `ModelContainer` via `getStringValue()`, `getIntegerValue()`, etc... when loading and saving to DB.
