### ISSUE TITLE
Basic question

### ISSUE THREAD

**Issue by mesterj** [Raizlabs/DBFlow#254]
Hello

I am a beginner with DBFlow. I can't find any tutorial about save objects related onetomany. 
I tried with colony/queen/ant example. I can't save ant in relation with queen or colony.

I trie:
Colony c = new Colony();
c.setName("First");
c.save();

Queen q = new Queen();
q.setColony(c);
q.save();

Ant a = new Ant();
a.setMale(true);
//a.setColony(// I don't know how to save!
a.save();
It saves ant but without colony or queen;

How can I do?

Sorry for writing here but I can't find any DBFlow related community or forum. 

DBFlow is a good ORM but without good tutorial and community it is almost unusable...

**Comment by agrosner** [comment]
1. The `Ant` table has a `ForeignKeyContainer` for a `Queen` object. What you'll need to do is create the container and `put(columnName, value)` for each primary key of the `ForeignKeyContainer` before you save it. I will put that in the README in 2.0.1 so it's clear.

**Comment by agrosner** [comment]
or you can call `setModel()` on the `ForeignKeyContainer` so you don't need to worry about putting in each primary key

**Comment by mesterj** [comment]
|Hello Thank you for your answers, but can't save ant yet.

I tried
Ant a = new Ant();
a.getQueen().put(Ant$Table.QUEEN_QUEEN_ID,queen_object);
a.save();
This is don't work.
I tried with setModel(queen_object) also, and don't save ant.

I have to setModel(Queen) in Ant class?

I see my real question is : What is ForeignKeyContainer, and how is it 
working? I working with databases since 2004 and I really know what 
Foreign key and I can imagine a Collection with Foreign Keys but your 
implementation is a bit hard for me. Please explain.

Joe.

|

**Comment by fabiendem** [comment]
Hey joe,

Not sure it's the way to do it, but add a setter in your Ant model:

```
public void setQueen(Queen queen) {
        this.queen = new ForeignKeyContainer<>(Queen.class);
        this.queen.put(Queen$Table._ID, queen.getId());
    }
```
Next time you ant.getQueen().load(), it should grab it from the DB.

Fabien

**Comment by mesterj** [comment]
2015.06.03. 10:07 keltezéssel, Fabien Demangeat írta:
>
> Hey joe,
>
> Not sure it's the way to do it, but add a setter in your Ant model:
>
> |public void setQueen(Queen queen) {
>          this.queen = new ForeignKeyContainer<>(Queen.class);
>          this.queen.put(Queen$Table._ID, queen.getId());
>      }
> |
>
> Next time you ant.getQueen().load(), it should grab it from the DB.
>
> Fabien
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Raizlabs/DBFlow/issues/254#issuecomment-108237845>.
>
I do it. It is saves the id, not a reference to queen object. It is not 
good as saving reference for queen object.
I tried put(Queen$Table.QUEEN_ID, queen) not queen.getId().
You right and your solution is working.
Thank you.

**Comment by ganeshs** [comment]
>> What you'll need to do is create the container and put(columnName, value) for each primary key of the ForeignKeyContainer before you save it. I will put that in the README in 2.0.1 so it's clear.

I spent handsome of time before figuring out this. Can you please update the README. I'm sure there are others who are new to this awesome library stumbling upon the same issue.
