### ISSUE TITLE
can you public SqlUtils.convertToCacheableList?

### ISSUE THREAD

**Issue by jiqimaogou** [Raizlabs/DBFlow#255]
convertToCacheable is public.

**Comment by agrosner** [comment]
good find!  `private` was done with purpose before but doesn't make sense when you want to evaluate a cursor.

**Comment by jiqimaogou** [comment]
convertToCacheableList is still private in 2.1

**Comment by agrosner** [comment]
@jiqimaogou in `2.2` its fully public and you can use custom `ModelCache` in the method too if you need to.
