### ISSUE TITLE
Which versionName in migration?

### ISSUE THREAD

**Issue by equinoxel** [Raizlabs/DBFlow#256]
Hi,

I've got a DB with version 1 and I want to upgrade it to version 2. Easiest for me would be to add the sql file to cover the changes. Which number should I put in so the migration is run if the old db is version 1?

IMHO, in `Migrations.md` you should provide a concrete example via SQL file in assets, with the effective number in (e.g.: to migrate from version 1 to version 2, you need a file named `assets/migrations/{DatabaseName}/1.sql`).

Thank you,

Laur

**Comment by agrosner** [comment]
`assets/migrations/{DatabaseName}/2.sql`

**Comment by agrosner** [comment]
For each version specified, is when the database reaches that version the migration for that version is run. so it does it sequentially

**Comment by equinoxel** [comment]
Super! Thank you :)
