### ISSUE TITLE
Join Query 

### ISSUE THREAD

**Issue by amrsilva** [Raizlabs/DBFlow#263]
Hi!

I'm trying do this JOIN:

new Select()
        .from(StandardControlItem.class)
        .join(ProblemPhotos.class, Join.JoinType.INNER)
        .on(Condition.column(StandardControlItem.Columns.STANDARD_CONTROL_ITEM_ID)
                .eq(Condition.column(ProblemPhotos.Columns.PROBLEM_ID_FK))).queryList();

But I have a sqlexception:
android.database.sqlite.SQLiteException: near ".": syntax error (code 1): , while compiling: SELECT * FROM `StandardControlItem` INNER JOIN `ProblemPhotos` ON `standard_control_item_id`=com.raizlabs.android.dbflow.sql.builder.Condition@2cea512

When I print the query returned of this join I have this:
SELECT * FROM `StandardControlItem` INNER JOIN `ProblemPhotos` ON `standard_control_item_id`=com.raizlabs.android.dbflow.sql.builder.Condition@2e068332

I'm doing something wrong???

**Comment by agrosner** [comment]
Yes, You're doing an `eq()` on a `Condition` object. rather you should use the `ColumnAlias` class and specify the column name there instead.

**Comment by amrsilva** [comment]
Oooh. Thank you. Now runs correctly :)
