### ISSUE TITLE
Using DBFlow in more than one module

### ISSUE THREAD

**Issue by strigare** [Raizlabs/DBFlow#266]
When I try to use DBFlow in more than one module I get an error. I figured out it was because it creates two DataBaseHolder classes in the same package. Is there a way to avoid this and use only one class for the whole project?

**Comment by agrosner** [comment]
Not currently possible with annotation processing. Not sure if there are techniques or ways around this, but my understanding of annotation processing is that they run in isolation from each other. Meaning, the annotation processor in one module has no knowledge of other annotations from another project.

**Comment by eboissonneault** [comment]
Could you simply add a prefix for GeneratedDatabaseHolder in order to avoid duplicates or would this cause other issues?

**Comment by strigare** [comment]
@eboissonneault I was thinking something along the same line. I'm probably going to try and give it a go this week.

@agrosner the problem is not that I need the annotation processing to know of the existence of all the modules in order for them to interact, the problem is that when the code gets compiled into the dex files it throws an error because it finds two classes that share the same fully qualified name (DataBaseGenerator in the same package). This is not really a problem until I want to develop a library and the project that includes it is also trying to use DBFlow. Of course I could be mistaken, I'm just now starting to use both gradle and this library. If you could give me instructions on how to build it (in order to include it as a maven repo and test changes) I would really appreciate it.

**Comment by wfxphoebus** [comment]
i have the same problem，use DBFlow in more than one module

**Comment by agrosner** [comment]
alright. Ill add the ability to do so in `3.0.0`, which lets you change the generated class file name. But youll have to do something like this: `FlowManager.init(context, "_MyModule");` which will append it to the end of the file name and in your Database:
```@Database(...holderClassSuffix="_MyModule")```.

**Comment by strigare** [comment]
Great! Thank you very much.

**Comment by adrianq** [comment]
Hi @agrosner! Finally did you manage to get this into 3.0.0? I was having a look at the code and it doesn't look like. I have tried to implement it in a fork. I have been able to generate the classes using the suffix but I am stuck in something probably quite stupid. When I executed ```FlowManager.init(context, "_MyModule");``` the second time (I have to execute it twice: the first one for the module, the second one for the main app), mDatabaseHolder is not null. Therefore ```getDatabaseHolder()``` returns the first holder and never instantiate the second GeneratedDatabaseHolder (I am talking about [this method](https://github.com/Raizlabs/DBFlow/blob/3.0/dbflow/src/main/java/com/raizlabs/android/dbflow/config/FlowManager.java#L112-L123)). Can you shed some light on this? What am I missing?

**Comment by agrosner** [comment]
hey @adrianq not quite yet, I will need to add it at some point. But if you get it working, make the PR against the `3.0` branch, that would be great. So what's missing is the ability for you to define the `GeneratedPlaceHolder` class that DBFlow looks for. The generated class is always in same package and may get overwritten (as you mention here). What's missing is the ability to define _where_ this placeholder class lives, so we could essentially operate with two different ones for each module. What we would need is to add a simple `FlowManager.init(context, "_MyModule");` method to that class and have it look for a class with that postfix in the `FlowManager` instead of always checking for :"
```
 protected static DatabaseHolder getDatabaseHolder() {
        if (mDatabaseHolder == null) {
            try {
                mDatabaseHolder = (DatabaseHolder) Class.forName(
                        "com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder").newInstance();
            } catch (Throwable e) {
                throw new RuntimeException(e);
            }
        }

        return mDatabaseHolder;
    }
```
It would append or change that class that was created. The only downside is that you'd need to specify which holder to put the `@Database` into.

**Comment by adrianq** [comment]
@agrosner and we kind of merge GeneratedDatabaseHolder and GeneratedDatabaseHolder_suffix into the same mDatabaseHolder? or are we using two different mDatabaseHolder? I am not sure if I understood you right. I already generate the two GeneratedDatabaseHolder but the two apps (module and main app) are sharing the same FlowManager. So mDatabaseHolder != null by the time the second ```FlowManager.init(context, "_MyModule");``` is called.

**Comment by adrianq** [comment]
@agrosner I've made it work merging the two GeneratedDatabaseHolder into a single mDatabaseHolder. It is looking good so far although I will have to test it a little bit more. If you are happy with this approach, I can clean up the code and create a PR.

**Comment by hilljh82** [comment]
@agrosner, @adrianq This was a feature that I really need for a project I am working on. As you can see above, I just closed the duplicate issue. I also went ahead and implemented this feature in a forked version of the repo. Here is a [link to comparison between my repo and master for DBFlow](https://github.com/Raizlabs/DBFlow/compare/master...onehilltech:master).

I used the approach discussed on this thread, but made a few changes. In essence, I wanted to be able to specify the module where the databases reside, and use Java-like naming conventions for the DatabaseHolder class. 

The way the approach work is you define a module in the ```@Database``` annotation. For example:

```java
@Database(name=ColonyDatabase.NAME, version=ColonyDatabase.VERSION, module=Example)
public class ColonyDatabase {
  public static final String NAME = "Colonies";
  public static final int VERSION = 1;
  public static final String MODULE = "Example";  
}
```

The default module is an empty string. In the code generation, each module is used to generate a DatabaseHolder class. For example, the code above will result in the ```ExampleGeneratedDatabaseHolder``` class. Also, this implies that if every database has a module definition, then ```GeneratedDatabaseHolder``` class is not generated (i.e., the problem we are currently experiencing should go away).

To load a module that contains a database, you use the new ```initModule``` method on ```FlowManager```. Using the example above, one would first initialize ```FlowManager``` as we currently do:

```java
FlowManager.init (context);
```

This will behave as it currently does by attempting to load ```GeneratedDatabaseHolder```. If the holder is not found, then no exception occurs. The module is then be initialized:

```java
FlowManager.initModule ("Example")
```

This will search for the ```ExampleGeneratedDatabaseHolder``` class. 

The main update with to the ```FlowManager``` and ```DatabaseHolder``` classes. In the ```FlowManager``` class, we have a ```GlobalDatabaseHolder``` class that contains a merge of all loaded ```DatabaseHolder``` classes. This includes ```GeneratedDatabaseHolder``` and the one for each corresponding loaded module. The ```FlowManager``` class also contains a map <ModuleName, DatabaseHolder>. I was thinking of making the ```GlobalDatabaseHolder``` class contain the mapping, as the merge, but that would require iterating over the maps values to query into each ```DatabaseHolder``` object for each operation. That would see to expensive and decided that space is more valuable than time given DBFlow's performance concerns. This, however, can also make it hard use DBFlow if your application+modules have LOTS of databases!

Right now, all unit tests pass!

Please give me your thoughts! I would like to make a pull-request if the design/approach is OK!

**Comment by agrosner** [comment]
@hilljh82 a very interesting idea and Ill have to check it out. one thing is that 3.0 is very close to being ready for merging into `develop` and then released on `master` and bintray or maven central. I would see if there would be any conflicts with this solution on the `3.0` branch. (3.0 is a huge change to library). Or if you would like, I can go ahead, look at your branch and implement it in the same way. If you want credit for it, I would submit a PR against `3.0` and see if your solution works with the code there as is. 
Thanks for the help, ill have to check this out soon.

**Comment by hilljh82** [comment]
@agrosner I will do some more checks against my target project, then make a PR against 3.0.

**Comment by hilljh82** [comment]
@agrosner I tested my approach in my target project, and it worked. I just had to figure out how to use DBFlow (and its libraries) by inserting them into a ```lib``` folder. While testing the approach, I came up with another approach after learning more about ```android-apt```.

What I learned is you can pass arguments to the processor. For example, the following addition to your ```build.gradle``` file will pass the target module name to ```DBFlow-Compiler```:

```groovy
apt {
    arguments {
        targetModuleName 'DBFlow'
    }
}
```

This will result in the database holder being named ```DBFlowGeneratedDatabaseHolder```. It will be initialized as discussed in previous comments.

I think that this approach would be better than the annotation approach proposed above and currently implemented. Using this new approach, you can really now say that all databases in a project are part of the same module. Using the previous approach, you have to annotate every database. That is somewhat tedious and error prone, and add more complexity to using DBFlow. I have this new approach working, but I have not pushed the changes to my forked version of DBFlow.

Please let me know your thoughts.

**Comment by agrosner** [comment]
That approach is awesome. yes that would be great. What I want to know is how the `FlowManager` changes. Maybe you can answer this for me. Do you break the `GeneratedDatabaseHolder` into multiple ones that the `FlowManager` references? how does it retrieve the `BaseDatabaseDefinition` for `getDatabaseForTable()`? Im sure these questions will get answered in a PR.

**Comment by hilljh82** [comment]
@agrosner. The simple answer is the ```FlowManager``` contains its own implementation of a ```DatabaseHolder``` (i.e., ```GlobalDatabaseHolder```) that is used to merge the ```DatabaseHolder``` implementations for each loaded module, and the ```GeneratedDatabaseHolder``` class, if present. The other approach was to do something similar to what you ask above. Have the ```GlobalDatabaseHolder```  have a reference to each loaded ```DatabaseHolder``` implementation. This approach would require searching through each loaded ```DatabaseHolder``` until we found what we were looking for. Although the runtime complexity is the same in both approaches, the latter would require extra calls. The former is use a batch processing design approach since it only require a single call to get the ```BaseDatabaseDefinition```.

I would like to see how either approach performs. How do you run performance tests?

**Comment by AlexCrookes** [comment]
After several hours futzing around with DBFlow, I've found this thread that discusses my problem - will this make it into 3.0? Last update was 19 days ago and I'm hoping it will...

**Comment by hilljh82** [comment]
@AlexCrookes. Yes, it should. I have been using the patched version in my projects, and it is working great! I should have time this week to check the patch against the 3.0 branch.

**Comment by agrosner** [comment]
@hilljh82 that would be great to see a PR on that feature ASAP, so I can finalize the preparations for 3.0.  It's shaping up to being a great release!

**Comment by hilljh82** [comment]
@agrosner I have updated the develop branch with the new functionality, and there are no problems right now.

**Comment by agrosner** [comment]
@hilljh82 do you have a PR open for it I can look at and merge in?

**Comment by hilljh82** [comment]
See #484

**Comment by agrosner** [comment]
now works via (https://github.com/Raizlabs/DBFlow/blob/develop/usage/DatabaseModules.md)

**Comment by prempalsingh** [comment]
@agrosner The link (https://github.com/Raizlabs/DBFlow/blob/develop/usage/DatabaseModules.md) doesn't work anymore.

**Comment by hilljh82** [comment]
See https://github.com/Raizlabs/DBFlow/blob/master/usage2/MultipleModules.md

**Comment by FarhanAhmad** [comment]
Can we have a small example? its not very clear at the moment.

**Comment by skhanzada** [comment]
how does it work when one module is dependent on another module?

I have a shared module that defines some model classes lets say ClassA. I have another module that has ClassB which uses ClassA in a foreignKeyContainer.  Now since both modules have their own Database classes i am getting the following error:

@Table(database = ModuleADB.class)
public class ClassA extends BaseModel implements Serializable {
@PrimaryKey
String code;
}

@Table(database = ModuleBDB.class)
public class ClassB extends BaseModel implements Serializable {

    @ForeignKey
    ForeignKeyContainer<ClassA> incidentCategory;

}


Error:error: *==========*
  class com.raizlabs.android.dbflow.processor.definition.column.ForeignKeyColumnDefinition: Could not find the referenced table definition my.package.ClassA from ClassB Ensure it exists in the samedatabase my.package.ClassBDB
  *==========*


I have two database holder added in my flow manager but the error i am getting is on compile time.

        FlowManager.init(new FlowConfig.Builder(this).
                addDatabaseHolder(ModuleAGeneratedDatabaseHolder.class).
                addDatabaseHolder(ModuleBGeneratedDatabaseHolder.class).
                build());

I don't want to create the two databases because i want to link tables from ModuleA in ModuleB.

Thanks,

**Comment by trevjonez** [comment]
As is, the database tables need to be in the same module because the
database class is generated at the compile time of that module. This would
ultimately need to be a feature request to make the generated database
classes runtime configurable thus allowing adding external table specs to
pre generated config. But it would require some big changes in the apt
processor and output product design as well as things such as overriding
content providers, migrations etc.

The question I then pose to you, if the models are so closely related that
they directly reference one or the other why are you placing them in
separate modules? Without a better understanding of your needs and goals
this just sounds like poor package design.

**Comment by skhanzada** [comment]
I have many projects and they share some common functionality that is defined in shared library, this include some common model classes as well. I don't want to rewrite those classes in each project.

**Comment by ubaierbhat** [comment]
I have two modules core and app each has its own database. For some reason only one of the databases gets initialised (core). 

```
FlowManager.init(new FlowConfig.Builder(this)
                .addDatabaseConfig(new DatabaseConfig.Builder(CoreDatabase.class).build())
                .addDatabaseConfig(new DatabaseConfig.Builder(AppDatabase.class).build())
                .build());
```


I get the following error. 

` java.lang.RuntimeException: Unable to create application com.omniva.omnigo.App: com.raizlabs.android.dbflow.structure.InvalidDBConfiguration: The specified databaseOmnigo_app was not found. Did you forget the @Database annotation?
`
```
@Database(name = AppDatabase.NAME, version = AppDatabase.VERSION )
public class AppDatabase {
    public static final String NAME = "Db_app";
    public static final int VERSION = 1;

}
```
```
@Database(name = CoreDatabase.NAME, version = CoreDatabase.VERSION )
public class CoreDatabase {
    public static final String NAME = "Db_core";
    public static final int VERSION = 1;

}
```

What am I doing wrong?

**Comment by mohamadk** [comment]
I use 

`apt {
    arguments {
        targetModuleName 'DBFlow'
    }
}`
this solution in android studio 2.3.3
and that solves my problem but today I update my android studio to version 3.0 and we don't have apt or we cannot use it so any solution for this version of the android studio

**Comment by nirwannursabda** [comment]
cant use apt anymore. its deprecated now. please help how to use multiple module without apt

**Comment by fakefacebook** [comment]
@agrosner have you any solution about it i have latest dbflow vesrion dependancy in java. please reply me asap.
Thanks
