### ISSUE TITLE
Encrypted Database

### ISSUE THREAD

**Issue by gautamshrm3** [Raizlabs/DBFlow#270]
Can we create encrypted database using dbflow? and How?
Like sqlcipher

**Comment by agrosner** [comment]
you can define a custom `sqlHelperClass()` in `@Database` which requires the same signature as `FlowOpenSQLiteHelper` [here](https://github.com/Raizlabs/DBFlow/blob/master/usage/Migration2Guide.md#custom-flowsqliteopenhelper)

**Comment by Rainer-Lang** [comment]
@gautamshrm3 I'm also interested. Did you anything?

**Comment by aldrinjoemathew** [comment]
@agrosner  The above mentioned link is not working!

**Comment by agrosner** [comment]
its moved. https://agrosner.gitbooks.io/dbflow/content/. Migration 2 guide is removed as its severely out of date now.
