### ISSUE TITLE
@Unique annotation doesn't get ForeignKey columnName attribute.

### ISSUE THREAD

**Issue by caio-yassoyama-movile** [Raizlabs/DBFlow#273]
I had to use a @ForeignKey an @Unique annotations on a single column, and the creation query throws an error.

```java
@Column
@PrimaryKey(autoincrement = true)
Long id;

@Column
@Unique(unique = false, uniqueGroups = 1)
String userId;

@Column
@ForeignKey(references = {
        @ForeignKeyReference(columnName = "stageId", columnType = String.class, foreignColumnName = "id")},
        onDelete = ForeignKeyAction.CASCADE)
@Unique(unique = false, uniqueGroups = 1)
StageEntity stage;
```

And the creation query is:
```sql
CREATE TABLE IF NOT EXISTS `UserEntity`(`id` INTEGER PRIMARY KEY AUTOINCREMENT, `userId` TEXT,  `stageId` TEXT, UNIQUE (`userId`, `stage`) ON CONFLICT IGNORE, FOREIGN KEY(`stagId`) REFERENCES `StageEntity` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE );
```

The column and foreign key sql statements gets the "stageId" as column name, but the UNIQUE statement gets the "stage" as column name.

**Comment by agrosner** [comment]
I guess its kind of weird. You need to _also_ specify the column name for `@Column` in order to match it up appropriately.

**Comment by msal** [comment]
I had the same bug like @caio-yassoyama-movile in _version 2.2.1_ and tried to follow your advice to also specify the column name in `@Column`, @agrosner :
```Java
@Column(name = "ShipmentId")
@ForeignKey(saveForeignKeyModel = false,
            references          = {
                 @ForeignKeyReference(columnName        = "ShipmentId",
                                      columnType        = Long.class,
                                      foreignColumnName = "_id")})
@Unique(unique       = false,
        uniqueGroups = 1)
ForeignKeyContainer<Shipment> shipment;
```

However this gives me following error message:
> Error: Foreign Key shipment cannot specify the column() field. Use a @ForeignKeyReference(columnName = {NAME} instead. Column: ShipmentId and type: de.msal.app.model.db.Shipment

**Comment by fernanda-moya-movile** [comment]
I am having the same bug... when i include @unique its says i dont have the column
