### ISSUE TITLE
Working with Enum

### ISSUE THREAD

**Issue by xero88** [Raizlabs/DBFlow#274]
Hi,

Is there a way to work with enums ?

Thank you !

EDIT :

I found a way, using TypeConverter. Implementing a easier way in the API would be an enhancement ?

Sorry for my poor english =)

**Comment by agrosner** [comment]
Adding it in 2.1.0!

**Comment by zeroarst** [comment]
Hi just wondering if this is mentioned in document because I thought Enum is not supported so i made a lot of changes, until I saw this.....

**Comment by CapnSpellcheck** [comment]
Still implemented in 4.0? I don't know where it is in the docs...
