### ISSUE TITLE
Select ById

### ISSUE THREAD

**Issue by carmelo-ruota** [Raizlabs/DBFlow#275]
Is there, in new version, equivalent of byId method?

**Comment by agrosner** [comment]
Bringing it back in `2.1.0` as `new Select().from(table).byId(ids).querySingle()`

**Comment by carmelo-ruota** [comment]
I tried but it contains a bug.
The result query obtained by "ByIds" method is:
 SELECT * FROM \`TABLE\` WHERE  __\`\`ID\`\`__ =12 LIMIT 1

**Comment by Rainer-Lang** [comment]
Any news?

**Comment by agrosner** [comment]
@Rainer-Lang , I apologize. It will be fixed in `2.2.0`. A current fix is on the `develop` branch, otherwise I would suggest specifying the columns manually.

**Comment by Rainer-Lang** [comment]
Great work. Thanks for answer.
