### ISSUE TITLE
maven repository error

### ISSUE THREAD

**Issue by morder** [Raizlabs/DBFlow#276]
https://raw.github.com/Raizlabs/maven-releases/master/releases
Not Found

**Comment by agrosner** [comment]
What's your `build.gradle` look like?

**Comment by agrosner** [comment]
and are you running in offline mode? If so, you need to turn it off once to download the artifacts.

**Comment by fabiendem** [comment]
I think the confusion is that if you click on the link https://raw.github.com/Raizlabs/maven-releases/master/releases you get a Not found message.

**Comment by morder** [comment]
project build.gradle 
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.1.1'
        classpath 'com.google.gms:google-services:1.3.0-beta1'
    }
}
allprojects {
    repositories {
        jcenter()
        maven { url "https://raw.github.com/Raizlabs/maven-releases/master/releases" }
    }
}
```
app build.gradle 

```
...
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.neenbedankt.android-apt'
...
dependencies {
...
    apt 'com.raizlabs.android:DBFlow-Compiler:2.0.0'
    compile "com.raizlabs.android:DBFlow-Core:2.0.0"
    compile "com.raizlabs.android:DBFlow:2.0.0"
}
```

my gradle takes me error
> Error:(11, 0) Plugin with id 'com.neenbedankt.android-apt' not found.

**Comment by morder** [comment]
I solved my problem

project build.gradle

```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.1.1'
        classpath 'com.google.gms:google-services:1.3.0-beta1'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
    }
}
```

app build.gradle
```
repositories {
    jcenter {
        url "http://jcenter.bintray.com/"
    }
}
```

**Comment by agrosner** [comment]
@morder You don't need `mavenCentral()` anymore. `jcenter()` is a superset of `mavenCentral()` and version `2.1.0` of the library is up on `jcenter()` now :)

**Comment by agrosner** [comment]
ah I see the issue now, I need to add the plugin to the classpath in my getting started guide.

**Comment by voghDev** [comment]
I ran into the same error for a few minutes and solved it as it's explained here. Had to replace:

    dependencies {
        'com.neenbedankt.gradle.plugins:android-apt:1.4'
    }

with

    dependencies {
        classpath 'another.previous.classpath'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
    }

Maybe the README is a bit confusing in that aspect. Thanks!
