### ISSUE TITLE
Could not find com.raizlabs.android:DBFlow-Compiler:2.1.0

### ISSUE THREAD

**Issue by rey5137** [Raizlabs/DBFlow#278]
Although the changelog said that 2.1.0 version is available on jCenter, when I add it to my project, the Gradle sync return this error:
```
Error:Could not find com.raizlabs.android:DBFlow-Compiler:2.1.0.
Searched in the following locations:
    https://jcenter.bintray.com/com/raizlabs/android/DBFlow-Compiler/2.1.0/DBFlow-Compiler-2.1.0.pom
    https://jcenter.bintray.com/com/raizlabs/android/DBFlow-Compiler/2.1.0/DBFlow-Compiler-2.1.0.jar
    https://repo1.maven.org/maven2/com/raizlabs/android/DBFlow-Compiler/2.1.0/DBFlow-Compiler-2.1.0.pom
    https://repo1.maven.org/maven2/com/raizlabs/android/DBFlow-Compiler/2.1.0/DBFlow-Compiler-2.1.0.jar
    https://raw.github.com/Raizlabs/maven-releases/master/releases/com/raizlabs/android/DBFlow-Compiler/2.1.0/DBFlow-Compiler-2.1.0.pom
    https://raw.github.com/Raizlabs/maven-releases/master/releases/com/raizlabs/android/DBFlow-Compiler/2.1.0/DBFlow-Compiler-2.1.0.jar
    ...
```

You can see that I even added the custom maven repo, but still no success.

**Comment by jan-pintr** [comment]
For now you can add repo:
```maven { url 'https://dl.bintray.com/raizlabs/Libraries' }```

**Comment by pboos** [comment]
That won't work either because they didn't push it to https://github.com/Raizlabs/maven-releases/tree/master/releases/com/raizlabs/android/DBFlow either.

My guess is that they thought they pushed it to maven, but didn't. Actually pushing to maven is not that easy ;-). They probably forgot that they have to manually release it in https://oss.sonatype.org/. But just guessing.

**Comment by rey5137** [comment]
@pboos I have tried adding the custom maven repo above and it's working now.

**Comment by cedricfortin** [comment]
@rey5137 I can't get it working...
Could you explain which changes did you make?

**Comment by cedricfortin** [comment]
Just get it working:
<code>
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.3'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url 'https://dl.bintray.com/raizlabs/Libraries' }
    }
}
</code>
Thanks!

**Comment by agrosner** [comment]
hey its finally up on jCenter(). Just took some time. Ensure you reference `jCenter()` in your libraries and not `mavenCentral()`
