### ISSUE TITLE
Error:TypeConverter: ImagesConverter uses an unsupported Model Element parameter

### ISSUE THREAD

**Issue by rey5137** [Raizlabs/DBFlow#279]
I tried to create a custom TypeConverter:
```java
@com.raizlabs.android.dbflow.annotation.TypeConverter
public class ImagesConverter extends TypeConverter<String, Image[]>{
...
}
```
But the build process give me this error:
```
Error:TypeConverter: ImagesConverter uses an unsupported Model Element parameter. If it has type parameters, you must remove them or subclass itfor proper usage.
```
Why array class is unsupported?

**Comment by agrosner** [comment]
You cannot have columns as arrays or lists since it breaks relational database constraints. The way to go is to use _composition_ of the element and create a custom type, and then the associated type converter. So if you define class:

```java
public class ImageHolder {

  private Image[] images;

  // associated setter/getter

}

```

And then the `TypeConverter`:

```java
@com.raizlabs.android.dbflow.annotation.TypeConverter
public class ImagesConverter extends TypeConverter<String, ImageHolder>{
...
}
```

**Comment by rey5137** [comment]
I want to convert array to Json string and store in a column . It's only static data and doesn't link with any table. Is there anyway to make it work other than wrap it in a class, because the Json returned to me from REST API contain many array fields, and creating 2 different class is too much of work.

**Comment by agrosner** [comment]
@rey5137 you can create another table that `Image` belongs in with a format like this:

```
public class Image extends BaseModel {

  @PrimaryKey(autoincrement = true)
  @Column
  long id;

  @Column
  String url; // not sure what kind of data image contains?

  @Column
  long other_table_id; // represent's the other tables id that we reference here.

}
```

then override `save()` in the parent object and save the `Images[]` field into the new table you created. and implement `OnLoadFromCursorListener`.

Or option 2, use a `List<Image>` and a `OneToMany` relationship that aids in loading and saving these fields.

**Comment by agrosner** [comment]
closing
