### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by matteinn** [Raizlabs/DBFlow#280]
Hi there!
What about SQL Injection? Is there any way to protect the Conditions?

`String value = "invalidEmail OR 1=1";`
`User firstUser = new Select().from(User.class).where(Condition.column(User$Table.EMAIL).eq(value)).querySingle();`

**Comment by agrosner** [comment]
@matteinn not currently. its up to you to validate that the email passed is a valid email via regex. I guess I could add support for something like `ColumnValueValidator` to prevent against such injections.

**Comment by agrosner** [comment]
major changes will come in 3.0 that will be for the better.

**Comment by agrosner** [comment]
3.0 strongly types the conditional `Property` object.s this is in develop now.
