### ISSUE TITLE
Protocol Buffers  support.

### ISSUE THREAD

**Issue by clertonleal** [Raizlabs/DBFlow#281]

**Comment by agrosner** [comment]
can you elaborate?

**Comment by clertonleal** [comment]
Sorry for the lack of detail.
I love Protocol Buffers, and I love the ability to generate entities in different languages using a simple .proto file.
How can I generate and evolve my entities with .proto files and continue using Squidb annotations? It is possible?
It will be necessary to implement a specific Protocol Buffers compiler for Squidb or there is another simple solution?

**Comment by kaeawc** [comment]
@clertonleal How are you trying to use Squidb annotations with DBFlow? Can you give an example?
