### ISSUE TITLE
Delete query doesn't dispatch onModelStateChanged event.

### ISSUE THREAD

**Issue by rey5137** [Raizlabs/DBFlow#282]
I already created a `FlowContentObserver` and added `OnModelStateChangedListener`. But when I use Delete query to clear the table, no `onModelStateChanged` event is dispatched. 
I also tried to delete a model object (ex: model.delete()) and an `onModelStateChanged` event with `Action.DELETE` is successfully dispatched.

**Comment by agrosner** [comment]
@rey5137 good point. Raw sql-wrapping queries do not dispatch an event to the `FlowContentObserver`. I believe that can be considered a bug, however it gets tricky when we get into more complicated queries. I will think of an improvement that may make this work in a good way.

**Comment by rey5137** [comment]
For now, I call `SqlUtils.notifyModelChanged()` to notify it manually. May be you should make it clear in Wiki.
