### ISSUE TITLE
Create a mock to test with junit

### ISSUE THREAD

**Issue by arturonaredo** [Raizlabs/DBFlow#283]
Is there a way to test DBFlow without passing a context or a mockcontext (right now is giving us a NPE) to test it with mock data? Maybe passing a db file or something? 

We want to create junit tests and and unit tests should not know nothing about context nor other android stuff...

**Comment by fcostaa** [comment]
+1

**Comment by jesdiart** [comment]
Great idea, that would be really helpful :)

**Comment by agrosner** [comment]
with the better support from studio/gradle, this becomes much easier. Ill try it out

**Comment by agrosner** [comment]
Not currently, you need to get a handle on the database to use it, since it operates using the `FlowSQLiteOpenHelper`

**Comment by agrosner** [comment]
you can use roboelectric to do that, http://robolectric.org/

**Comment by kaeawc** [comment]
@arturonaredo I've successfully mocked both Context and SqlUtils in [this example](https://github.com/kaeawc/android-test-playground/blob/master/app/src/test/java/io/kaeawc/testplayground/data/repositories/WidgetRepositorySpec.java). Will update the sample to 2.2.1 when I get the chance.

**Comment by kaeawc** [comment]
Here's the short helper class that makes it possible: [SqlUtilsMock](https://github.com/kaeawc/android-test-playground/blob/master/app/src/test/java/io/kaeawc/testplayground/data/SqlUtilsMock.java)

This lets you mock a table for the duration of a test.

Let me know if that works for you or if you have any problems.

**Comment by mathroule** [comment]
@kaeawc do you still have your example ? unfortunately both links you've given are deads.

**Comment by arctouch-luizsantana** [comment]
+1

**Comment by rosmons** [comment]
Does anybody have a backup of this code (SqlUtilsMock)?
