### ISSUE TITLE
Query wildcards

### ISSUE THREAD

**Issue by olpie101** [Raizlabs/DBFlow#29]
Firstly amazing work. I would like to know if with the where method and using Condition if it possible to use wildcards? I looked around but couldn't seem to find anything on it.

An example of the query I am looking to resolve is:

    SELECT * FROM myTable WHERE Name LIKE '%Doe%';

**Comment by agrosner** [comment]
Yep,

```java

new Select().from(myTable.class).where(Condition.column(myTable$Table.NAME).like("%Doe%");

```

I will be adding in the near future a more comprehensive usage documentation so it can answer question like these. Enjoy!

**Comment by olpie101** [comment]
Thank you. Hadn't realised that the gradle build files had changed. Finally working.
