### ISSUE TITLE
Possible: ORDER BY column COLLATE NOCASE?

### ISSUE THREAD

**Issue by Rainer-Lang** [Raizlabs/DBFlow#293]
I only found:
```java
public Where<ModelClass> orderBy(boolean ascending, String... columns)
public Where<ModelClass> orderBy(String orderby)
```
I need this to get a list back with "queryList()".

**Comment by thinkfeed** [comment]
you can try this
ConditionQueryBuilder<FriendList> queryBuilder = new ConditionQueryBuilder<>(FriendList.class);
List<FriendList> friendLists = new Select().from(FriendList.class).where(queryBuilder).orderBy(true,FriendList$Table.STATE).queryList();

**Comment by Rainer-Lang** [comment]
@agrosner Is it possible to integrate "COLLATE NOCASE" in orderBy(...)?

**Comment by agrosner** [comment]
@Rainer-Lang for right now, you can use the `String` method for it. Ill think of some way to improve this in 2.2 or later.

**Comment by Rainer-Lang** [comment]
Thanks!

**Comment by agrosner** [comment]
in `2.2` you can:
```java

new Select().from(myTable).orderBy(OrderBy.columns(...).collate(Collate.NOCASE)); //etc..

```

**Comment by Rainer-Lang** [comment]
Thank you very much!

**Comment by Rainer-Lang** [comment]
@agrosner Something is wrong...
SELECT `name` FROM `categories`  ORDER BY `name` DESC  NOCASE
android.database.sqlite.SQLiteException: near "NOCASE": syntax error (code 1): , while compiling: SELECT `name` FROM `categories`  ORDER BY `name` DESC  NOCASE

**Comment by agrosner** [comment]
@Rainer-Lang appears that I left out "COLLATE". It'll be fixed in `2.2.1`

**Comment by Rainer-Lang** [comment]
ok

**Comment by Rainer-Lang** [comment]
Still wrong.

wrong:
```java
SELECT name FROM categories  ORDER BY name ASC COLLATE NOCASE
```
good:
```java
SELECT name FROM categories  ORDER BY name COLLATE NOCASE asc
```

**Comment by Rainer-Lang** [comment]
@agrosner Is it possible to open this issue again? 
After correction I will test it and give you feedback.

**Comment by Rainer-Lang** [comment]
@agrosner Would it possible to correct this in the next version?

**Comment by austenlux** [comment]
@agrosner 
Can we please get a response to this?
The issue is not resolved, and this is a major feature needed in any SQL library.

**Comment by Rainer-Lang** [comment]
Agrosner is on holiday.

**Comment by Rainer-Lang** [comment]
@agrosner Please include this in next release.

**Comment by agrosner** [comment]
thanks for reminder @Rainer-Lang .

**Comment by agrosner** [comment]
its in `develop` now. I reversed the order.

**Comment by Rainer-Lang** [comment]
Fantastic. Thanks.

**Comment by agrosner** [comment]
in 3.0, develop too. can access `OrderBy` via `...orderBy(OrderBy.fromProperty(someproperty).collate(Collate.NOCASE))...`
