### ISSUE TITLE
Transaction Listener

### ISSUE THREAD

**Issue by OptimistNot** [Raizlabs/DBFlow#295]
Hey!
can you please provide me some help, or give an opinion..
im using UpdateMiodelListTransaction and SaveModelTransaction with TransactionListener. At the moment TransactionsListener only notify when all transactions completed, but i need some listener that shows me progress of transaction one by one..is there any listener for it? or any other way?
Thanks!

**Comment by agrosner** [comment]
@OptimistNot no, but I can add a `ProgressCallBack` to the `ProcessModelTransaction` base class.
