### ISSUE TITLE
I can't find or import @PrimaryKey

### ISSUE THREAD

**Issue by abdellahCode** [Raizlabs/DBFlow#296]
I have added this:     
    compile 'com.github.agrosner:DBFlow:1.0.3'
    compile 'com.github.agrosner:DBFlow-Core:1.0.3'
    compile 'com.github.agrosner:DBFlow-Compiler:1.0.3' to my module gradle and I could import @Database, @Table, and @Column,  but I can't find @PrimaryKey, any thoughts ? Thank you.

**Comment by agrosner** [comment]
you're using an outdated version of the library on maven. Use the package `com.raizlabs.android` instead and version `2.1.0` to compile the library.

**Comment by agrosner** [comment]
@abdellahCode closing this one as invalid.
