### ISSUE TITLE
Ordering a FlowCursorList

### ISSUE THREAD

**Issue by surfer190** [Raizlabs/DBFlow#297]
I believe that currently there is no Ordering for the `FlowCursorList`. I believe this would be a good enhancement.

**Comment by agrosner** [comment]
@surfer190  what you mean? you can pass in any `ModelQueriable` such as a `From`, `Where`, etc and can use the `orderBy()` method in `Where` to do that.

**Comment by surfer190** [comment]
@agrosner I'm just trying to get an example of this in the Docs, is there an available guide?

This is what I have currently:

```
mFlowCursorList = new FlowCursorList<TreeDetails>(true,
        TreeDetails.class, Condition.column(TreeDetails$Table.KRUGER).eq(true));
```

I would like to order this query

**Comment by agrosner** [comment]
```
new FlowCursorList<TreeDetails>(true, new Select().from(TreeDetails.class)
  .where(Condition.column(TreeDetails$Table.KRUGER).eq(true))
  .orderBy(orderByString));
```

Ill add something in docs for it if its not there already.

**Comment by surfer190** [comment]
@agrosner Thank you. It worked. I was confused about `ModelQueriable`. I don't really know what it is. I thought I would have to do something like:

```
ModelQueriable<TreeDetails> mq = new ModelQueriable<TreeDetails>() {
      ...
    }
```

It seems as though `new Select()` returns a `ModelQueriable`.

**On a side note** , and I know this is not the place: How should subqueries be handled? The usecase is list the data include an image and a selection of languages. I haven't used `Relationships`/`ForeignKeys` and wanted to do SQL like this:

```
SELECT *, (SELECT CommonName FROM CommonNames WHERE LanguageId = '1' AND TreeId = TreeDetails.TreeGuid AND Primary = '1') AS afrikaans,
  (SELECT CommonName FROM CommonNames WHERE LanguageId = '2' AND TreeId = TreeDetails.TreeGuid AND Primary = '1') AS english
  FROM TreeDetails LEFT JOIN (SELECT * FROM TreeImages WHERE Icon = 1) ti ON TreeDetails.TreeId = ti.TreeId WHERE Kruger = 1
  ORDER BY english;
```

Would I be able to do something like the above when using `Relationships`?
