### ISSUE TITLE
Executing JOINs inside generated Content Provider

### ISSUE THREAD

**Issue by R4md4c** [Raizlabs/DBFlow#299]
I have many Malls that can include many stores, and the same store can be found in many malls, obviously it is a many to many relationship.

I already made an auxiliary table that resembles this relationship.

```
@Table(databaseName = AppDatabase.NAME)
public class MallStoreMany extends BaseModel {
    @Column
    @PrimaryKey(autoincrement = true)
    protected long id;

    @Column
    @ForeignKey(references = {@ForeignKeyReference(columnName = "store", columnType = long.class, foreignColumnName = "id")},
    onDelete = ForeignKeyAction.CASCADE)
    protected ForeignKeyContainer<Store> store;

    @Column
    @ForeignKey(references = {@ForeignKeyReference(columnName = "mall", columnType = long.class, foreignColumnName = "id")},
    onDelete = ForeignKeyAction.CASCADE)
    protected ForeignKeyContainer<Mall> mall;

    public MallStoreMany() {
    }

    public MallStoreMany(Store store, Mall mall) {
        this.store.setModel(store);
        this.mall.setModel(mall);
    }
}
```

My problem is, now that I need to add a uri to the generated content provider that gets the stores under a specific mall "mall/#/store", so IMO to achieve that I need to make a JOIN with MallStoreMany table to extract the stores under that # mall. 

Is that possible with DBFlow generated of ContentProvider ? If yes how can I achieve that ?

**Comment by agrosner** [comment]
not possible, and probably not supported for this basic, yet powerful feature.
