### ISSUE TITLE
Load Model with ForeignKey doesn't work

### ISSUE THREAD

**Issue by Informaticore** [Raizlabs/DBFlow#300]
I have a Model with 3 ForeignKeys. I did everything like the guide but when I try to load a list of this model the app ends in an endless loop of loading.
The only thing I see is the garbage collector outputs:

*Background sticky concurrent mark sweep GC freed 923969(16MB) AllocSpace objects, 0(0B) LOS objects, 18% free, 35MB/43MB, paused 4.915ms total 125.013ms*

This is my Model:

```javascript
@Table(databaseName = DatabaseAdapter.NAME)
public class Car extends BaseModel {
    public static final String COLUMN_ID                = "id";
    public static final String COLUMN_ERA               = "era";
    public static final String COLUMN_MANUFACTURER      = "manufacturer";
    public static final String COLUMN_CATEGORY          = "category";
    public static final String COLUMN_UPDATED_AT        = "updated_at";
    public static final String COLUMN_MANUFACTURE_ID    = "manufacture_id";

    @SerializedName("id")
    @Column(name = COLUMN_ID)
    @PrimaryKey
    public int id;

    @SerializedName("era")
    @Column
    @ForeignKey(references = {@ForeignKeyReference(
            columnName = COLUMN_ERA,
            columnType = Integer.class,
            foreignColumnName = Era.COLUMN_ID)},
            saveForeignKeyModel = false)
    public Era mEra;

    @SerializedName("manufacturer_id")
    @Column(name = COLUMN_MANUFACTURE_ID)
    public int mManufactureId;

    @Column
    @ForeignKey(references = {@ForeignKeyReference(
            columnName = COLUMN_MANUFACTURER,
            columnType = Integer.class,
            foreignColumnName = Manufacture.COLUMN_ID)},
            saveForeignKeyModel = false)
    public Manufacture mManufacture;

    @SerializedName("category")
    @Column
    @ForeignKey(references = {@ForeignKeyReference(
            columnName = COLUMN_CATEGORY,
            columnType = Integer.class,
            foreignColumnName = Category.COLUMN_ID)},
            saveForeignKeyModel = false)
    public Category mCategory;

    @SerializedName("updated_at")
    @Column(name = COLUMN_UPDATED_AT)
    public int mUpdatedAt;
}
```

**Comment by agrosner** [comment]
@Informaticore is there any possibility you have a recursive, two way relationship here? like one of the foreign keys references this table as a foreign key?

**Comment by Informaticore** [comment]
I tripple checked it. The three foreign objects have just primitive types inside. But all 3 extend a *MyBaseModel* which extend the *BaseModel* of DBFlow.

**Comment by Informaticore** [comment]
@agrosner  does the *columnName* should be the same as the variable name? Here I have mEra as variable and *era" as column name. But maybe I forgot to set foreignKeysSupported = true in the DatabaseAdapter, because no ForeignKEy is working correctly.

**Comment by Informaticore** [comment]
@agrosner I forgot to add foreignKeysSupported = true BUT now I added it, invalidated caches, re-installed the app and everything but it changed just nothing. ForeignKeys are not working and for this Car object it still ends up in a endless loading loop.

This is my query:
```java
    new Select().from(Car.class).where(Condition.column(Car.COLUMN_MANUFACTURE_ID).eq(manufactureId)).async().queryList(listener);
```

Car.COLUMN_MANUFACTURE_ID is not the ForeignKey - its just the ID.
I also changed the variable names but it didn't changed anything.

**Comment by Informaticore** [comment]
Gson was the problem! I tried the app on a different phone and it crashed because this phone was much slower, so I could figure out that it was gson which couldn't handle the BaseModel mModelAdapter.

**Comment by agrosner** [comment]
@Informaticore have a fix in `2.2` to lazy-load the model adapter so superclasses that extend `BaseModel` don't crash when created if they aren't used for DB operations.

**Comment by gustahrodrigues** [comment]
Hi @agrosner 

Do you have some news about the version 2.2? I am asking because i have a problem with foreign key too:

I have a model with four foreign keys (one to one). 
```
public class Match extends BaseModel implements Serializable {

    @SerializedName("id")
    @Column
    @PrimaryKey(autoincrement = false)
    long _id;

    @Column
    private Date date;

    @Column
    @ForeignKey(
            references = {@ForeignKeyReference(columnName = "team1_id",
                    columnType = Long.class,
                    foreignColumnName = "_id")},
            saveForeignKeyModel = true)

    Team team1;

    @SerializedName("team1_score")
    @Column
    private int team1Score;

    @Column
    @ForeignKey(
            references = {@ForeignKeyReference(columnName = "team2_id",
                    columnType = Long.class,
                    foreignColumnName = "_id")},
            saveForeignKeyModel = true)
    Team team2;

    @SerializedName("team2_score")
    @Column
    private int team2Score;

    @Column
    @ForeignKey(
            references = {@ForeignKeyReference(columnName = "competition_id",
                    columnType = Long.class,
                    foreignColumnName = "_id")},
            saveForeignKeyModel = true)

    Competition competition;

    @Column
    @ForeignKey(
            references = {@ForeignKeyReference(columnName = "match_id",
                    columnType = Long.class,
                    foreignColumnName = "_id")},
            saveForeignKeyModel = true)

    MatchLocation location;

    //getter and setters
}
```

I am using GSon to deserialze a Json into this Model. After gson deserialization, I print/check the model's primary key objects (team1, team2, competition and matchlocation) and everything is fine. But, when I get the Match model from DB, some primary key objects is null.

Follow is my code:

```
// I use this same code piece for all matches
Match match = getMatchFromJson(json); //using Gson library
CustomLog.debug( m.toString() ); //All primary keys filled
m.save()

List<Match> listMatch = new Select().from(Match.class).queryList();
for (Match m : listMatch) {
       CustomLog.debug(m.toString()); //Some match does not have the primary keys objects filled
 }
```

Thanks!
Great job et all!

**Comment by gustahrodrigues** [comment]
@agrosner I made another test: i created all the models objects by myself (without gson deserialize) and everything worked fine!

So, the problem is something in GSON model deserialized + Dbflow.

Do you have any idea about what can be wrong?

It's so weird because when i print the model instance from gson deserialization, all the fields were filled ok.

Thanks!

**Comment by Informaticore** [comment]
@gustahrodrigues This helped me with Gson:

```java
mGson = new GsonBuilder()
                .setExclusionStrategies(new ExclusionStrategy() {
                    @Override
                    public boolean shouldSkipField(FieldAttributes f) {
                        return f.getDeclaredClass().equals(ModelAdapter.class);
                    }

                    @Override
                    public boolean shouldSkipClass(Class<?> clazz) {
                        return false;
                    }
                })
                .create();
```

This will skip the ModelAdapter which is in the BaseModel.

**Comment by Informaticore** [comment]
@agrosner now I have the problem that my One-to-Many relation is not loading. I added @ModelContainer to this class and did this like the doc:

```java
@SerializedName("store_items")
public List<ShopItem> shopItems;

@OneToMany(methods = {OneToMany.Method.ALL})
public List<ShopItem> getShopItems() {
    if(shopItems == null) {
        shopItems = new Select()
                .from(ShopItem.class)
                .where(Condition.column(ShopItem.COLUMN_SHOP_CATEGORY).is(id))
                .queryList();
    }
    return shopItems;
}
```

This is inside the ShopItem class:

```java
@Column
@ForeignKey(references = {
@ForeignKeyReference(columnName = COLUMN_SHOP_CATEGORY, columnType = Integer.class, foreignColumnName = ShopCategory.COLUMN_ID)}, saveForeignKeyModel = false)
public ForeignKeyContainer<ShopCategory> mShopCategory;
```

From the docs it says I do not have to save the items myself. So if I save the ShopCategory it also saves all ShopItems.
The mShopCategory variable in ShopItem is always null, so the Select would never work. When I get the data from the network the ShopItems are set, but the variable is null. Do I have to set them?

**Comment by gustahrodrigues** [comment]
@Informaticore thanks for your reply.

I am already used this code piece. So, with this code piece, i am getting model instance from json. After thath, i get the model instance generated from GSON and try to save. All foreign key model is save right, (team, competition and matchlocation) but when i try to get the match instance using select, some foreign key model from match is null.

For select matches, i am using:
```
List<Match> listMatch = new Select().from(Match.class).queryList();
```

**Comment by gustahrodrigues** [comment]
After several intestigations, i found the problem, but i don't know how to solve it:

In ```Match$Adapter```, method ```loadFromCursor(Cursor cursor, Match model)```, when it perform ```cursor.getLong(indexteam1_id)``` always returned -1, but the team model was saved. Variable ```indexteam1_id``` is ```2``` and I debug the code and the cursor variable at position ```2``` has the correct team id.

It's happening with all my foreign key.

@agrosner do you know what happening ?

Thanks!!

**Comment by Informaticore** [comment]
@gustahrodrigues where is the -1 coming from? Do you have this value in the json or something? 
And I saw that you used autoincrement = false, maybe this is incorrect?

**Comment by gustahrodrigues** [comment]
@Informaticore I was getting -1 from ```cursor.getString(index);``` when index corresponds to my foreign key. Autoincrement is false because i am getting the id from server.

I finally found the problem and the solution!!

In my models ```Team, Competition and MatchLocation ```, i had a Unique field ``` @Unique(unique = true, onUniqueConflict = ConflictAction.IGNORE) ```.

So when i was trying to save a model with unique conflict, the Ignore constraint just ignore the save and didn't get the reference to Match (foreign key). I think the right behavior would be: "on ignore unique conflict, not save, just get the reference model instance(id)".

What do you think about ir @agrosner  ?
