### ISSUE TITLE
How to get affected models from a FlowContentObserver.OnModelStateChangedListener

### ISSUE THREAD

**Issue by easyspeak** [Raizlabs/DBFlow#301]
Hi I am new to DBFlow and so far I really like it. I had a question about ObservableModel's.  I have set up a FlowContentObserver.OnModelStateChangedListener and it is working well, however, I would like to know which models were affected by the change.

```java
mObserver = new FlowContentObserver();

// registers for callbacks from the specified table
mObserver.registerForContentChanges(this, Ant.class);
mObserver.addModelChangeListener(new FlowContentObserver.OnModelStateChangedListener() {
        @Override
        public void onModelStateChanged(Class<? extends Model> table, BaseModel.Action action) {
            // Here I want to know which Ant Model's were affected in this change
        }
});
```

Is there a way to get the get the affected models or possible just their primary keys? This would be a great help for my use case.

**Comment by agrosner** [comment]
hey @easyspeak, Not currently in this release. I will have to formulate some kind of way to handle cases where there are complex primary keys (maybe enforce a `row_id`/single primary key instead).

**Comment by easyspeak** [comment]
Hi @agrosner thanks for the quick reply and adding this enhancement to the next milestone. This feature would allow for some very simple yet powerful data-binding, I can't wait to see it in action.
