### ISSUE TITLE
Plugin with id 'com.neenbedankt.android-apt' not found.

### ISSUE THREAD

**Issue by khafan** [Raizlabs/DBFlow#303]
Hi, I just intended to use this library but after adding dependencies to module build.gradle file, (my project consists of a few modules and mentioned module is library one) and on sync project with gradle files, it gives me this error:
Error:(2, 0) Plugin with id 'com.neenbedankt.android-apt' not found.
My build.gradle file if it helps:
    apply plugin: 'com.android.library'
    apply plugin: 'com.neenbedankt.android-apt'
    android {
   ...
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
        productFlavors {
        }
    }

    dependencies {
     ...
        apt 'com.raizlabs.android:DBFlow-Compiler:2.1.0'
        compile "com.raizlabs.android:DBFlow-Core:2.1.0"
        compile "com.raizlabs.android:DBFlow:2.1.0"
    }

**Comment by agrosner** [comment]
You need to add the plugin to your classpath via:
```
buildscript {
    repositories {
      jcenter()
    }
    dependencies {
        // the latest version of the android-apt plugin
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
    }
}

apply plugin: 'com.neenbedankt.android-apt'
```

**Comment by khafan** [comment]
Thanks for the answer. I don't get the error anymore and can access to library files but still Android Studio doesn't know the library classes. (I can't use FlowManager in custom Application class)
Is there a slight chance I've forgotten sth? Or it's completely a Android Studio Issue?

**Comment by kbighorse** [comment]
The ```README``` is missing the ```classpath``` command in the ```dependencies``` block: https://github.com/Raizlabs/DBFlow#including-in-your-project

**Comment by ramanAug** [comment]
I am using Android Studio : 3.0.1,

 dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
Error is coming while cleaning the project
android-apt plugin is incompatible with the Android Gradle plugin.  Please use 'annotationProcessor' configuration instead.

**Comment by fabiendem** [comment]
@ramanAug you must be running a very old version of DBFlow.
Try the version 2.2.1 if you are stuck back to the version 2.x.x.

This should work:
```
    annotationProcessor 'com.raizlabs.android:DBFlow-Compiler:2.2.1'
    implementation 'com.raizlabs.android:DBFlow-Core:2.2.1'
    implementation 'com.raizlabs.android:DBFlow:2.2.1'
```
