### ISSUE TITLE
endTransactionAndNotify() seems to have incorrect implementation

### ISSUE THREAD

**Issue by tikimcfee** [Raizlabs/DBFlow#306]
Hello there!

My team and I have been using DBFlow for our project recently and things seem to be going alright so far. However, we have hit a snag in the implementation of table/model change listeners that is of great importance to us.

Specifically, we need to be able to view *individual* model changes with an arbitrary listener (e.g., an object that calls for a UI refresh when a particular model has received a new set of properties), as well as *table* level changes (e.g., everything that is a Model in this particular table has changed, so update a RecyclerView's backing adapter). On the former, #301 seems to mention that this functionality has been added to the 2.2.0 milestone (which is awesome!), so we really look forward to that.

On the other end, it seems as if:
```java
public void endTransactionAndNotify() {
        if(this.isInTransaction) {
            this.isInTransaction = false;
            if(VERSION.SDK_INT >= 16) {    // <------ the issue is here
                this.onChange(true);
            } else {
                List var1 = this.notificationUris;
                synchronized(this.notificationUris) {
                    Iterator var2 = this.notificationUris.iterator();

                    while(var2.hasNext()) {
                        Uri uri = (Uri)var2.next();
                        this.onChange(true, uri);
                    }

                    this.notificationUris.clear();
                }
            }
        }

    }
```
...is not quite right; the docs here:
```
http://developer.android.com/reference/android/database/ContentObserver.html#onChange(boolean, android.net.Uri)
```

... show that Android API level 16 actually *supports* the onChange(boolean, Uri) method, while level 15 and below only support the onChange(boolean). That logic above seems to be flip-flopped! If I am wrong, I would really appreciate an example of why this is done this way.

```java
public void endTransactionAndNotify() {
        if(this.isInTransaction) {
            this.isInTransaction = false;
            if(VERSION.SDK_INT < 16) {    // <------ this should be the fix needed
                this.onChange(true);
            } else {
               ...
                }
            }
        }

    }
```

Definitely a small tweak, but it is a big change for us. If this is accepted, any chance this could be pushed as a hotfix?

Many thanks for your time!
EDIT: formatting changes

**Comment by agrosner** [comment]
@tikimcfee great catch! wow. Ok will fix this in `2.2`. Thanks :) Devs like you reporting issues like this make the library much better.

**Comment by tikimcfee** [comment]
Thanks very much for the fast response! =D

You guys seems to be quite quick on the turnaround for your milestones and issue resolution. My teammate and I are really excited to work with your team and this library because of that.

Side note: might there be any update on when we might see that 2.2.0? Totally OK if it's a little ways out from now - even a ballpark is useful for us, as we're making a big transition in core database work, and knowing when some of those big features are coming is always a load off the minds!

**Comment by agrosner** [comment]
@tikimcfee im thinking tonight :) I just need to run a few tests on the code. PS Im the primary dev on this library and pretty much coded 98% of the library :)

**Comment by tikimcfee** [comment]
That sounds great! I'd love to get my hands on that code. And wow, great to have a *lead* dev so responsive. Seriously, can't overstate the appreciation of your speed-to-action. The team is always under the gun here, so having another mind to bounce ideas off of is great.
