### ISSUE TITLE
Example of Inserting relationship with the Queen and Ant

### ISSUE THREAD

**Issue by surfer190** [Raizlabs/DBFlow#313]
I am having difficulty finding documentation relating to the creation and inserting of records.

```
Queen q = new Queen();
q.name = "Best Queen";
q.save();

Ant a = new Ant();
a.type = "worker";
a.isMale = false;
a.associateQueen(q);
a.save();
```

Returns an error: `Cannot call save() on a foreign key container. Call load() instead`

What is the correct way of inserting records with relationships?

**Comment by vincekennedy** [comment]
I created a test project around this to play with ForeignKeyContainer's and this is what I got sort of working.

```        Colony c = new Colony();
        c.name = "New Colony";
        c.save();

        Queen q = new Queen();
        q.name = "Queeny";
        q.colony = c;

        for (int i = 0; i < 10; i++) {
            Ant a = new Ant();
            a.isMale = i % 2 == 0;
            a.type = String.format("Type%d", i);
            a.save();
            a.associateQueen(q);
            q.getAnts().add(a);
        }
        q.save();```

However I've not been able to get the queen object to populate when loading my ants.

**Comment by surfer190** [comment]
@vincekennedy I tried the above suggested. I am getting a `NullPointerException` with the folowing line:

```
q.getAnts().add(a);
```

**Comment by Informaticore** [comment]
I also play with ForeignKeyContainer and 1-to-many relations, but I never get the list of entries.

```java
@ModelContainer
@Table(databaseName = DatabaseAdapter.NAME)
public class ShopCategory extends BaseModel {
    public static final String COLUMN_ID            = "id";
    public static final String COLUMN_SHOP_ITEMS    = "shop_items";

    @SerializedName("id")
    @Column(name = COLUMN_ID)
    @PrimaryKey
    public int id;

    @SerializedName("store_items")
    public List<ShopItem> shopItems;

    @OneToMany(methods = {OneToMany.Method.ALL})
    public List<ShopItem> getShopItems() {
        if(shopItems == null) {
            shopItems = new Select()
                    .from(ShopItem.class)
                    .where(Condition.column(ShopItem.COLUMN_SHOP_CATEGORY).is(id))
                    .queryList();
        }
        return shopItems;
    }
}

@ModelContainer
@Table(databaseName = DatabaseAdapter.NAME)
public class ShopItem extends BaseModel {

    public static final String COLUMN_ID           = "id";
    public static final String COLUMN_SHOP_CATEGORY = "shop_category";

    @SerializedName("id")
    @Column(name = COLUMN_ID)
    @PrimaryKey
    public int id;

    @Column
    @ForeignKey(references = {
    @ForeignKeyReference(columnName = COLUMN_SHOP_CATEGORY, columnType = Integer.class, foreignColumnName = ShopCategory.COLUMN_ID)}, saveForeignKeyModel = false)
    public ForeignKeyContainer<ShopCategory> mShopCategory;
}
```

When I try to run the Select via the debugger I am getting a NullPointerException but the App is not crashing in normal use. I really don't get this error:

Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
0 = {java.lang.StackTraceElement@4247} "com.raizlabs.android.dbflow.sql.QueryBuilder.appendQuoted(QueryBuilder.java:178)"
1 = {java.lang.StackTraceElement@4248} "com.raizlabs.android.dbflow.sql.language.ColumnAlias.getQuery(ColumnAlias.java:102)"
2 = {java.lang.StackTraceElement@4249} "com.raizlabs.android.dbflow.sql.builder.BaseCondition.columnName(BaseCondition.java:72)"
3 = {java.lang.StackTraceElement@4250} "com.raizlabs.android.dbflow.sql.builder.Condition.columnName(Condition.java:19)"
4 = {java.lang.StackTraceElement@4251} "com.raizlabs.android.dbflow.sql.builder.Condition.appendConditionToQuery(Condition.java:84)"
5 = {java.lang.StackTraceElement@4252} "com.raizlabs.android.dbflow.sql.builder.ConditionQueryBuilder.appendConditionToQuery(ConditionQueryBuilder.java:495)"
6 = {java.lang.StackTraceElement@4253} "com.raizlabs.android.dbflow.sql.builder.ConditionQueryBuilder.getQuery(ConditionQueryBuilder.java:136)"
7 = {java.lang.StackTraceElement@4254} "com.raizlabs.android.dbflow.sql.language.Where.getQuery(Where.java:296)"
8 = {java.lang.StackTraceElement@4255} "com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryList(BaseModelQueriable.java:35)"
9 = {java.lang.StackTraceElement@4256} "com.raizlabs.android.dbflow.sql.language.Where.queryList(Where.java:347)"
10 = {java.lang.StackTraceElement@4257} "com.homami.cars.models.ShopCategory.getShopItems(ShopCategory.java:51)"
11 = {java.lang.StackTraceElement@4258} "com.homami.cars.models.ShopCategory$Adapter.loadFromCursor(ShopCategory$Adapter.java:118)"
12 = {java.lang.StackTraceElement@4259} "com.homami.cars.models.ShopCategory$Adapter.loadFromCursor(ShopCategory$Adapter.java:12)"
13 = {java.lang.StackTraceElement@4260} "com.raizlabs.android.dbflow.sql.SqlUtils.convertToModel(SqlUtils.java:166)"
14 = {java.lang.StackTraceElement@4261} "com.raizlabs.android.dbflow.sql.SqlUtils.querySingle(SqlUtils.java:224)"
15 = {java.lang.StackTraceElement@4262} "com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.querySingle(BaseModelQueriable.java:40)"
16 = {java.lang.StackTraceElement@4263} "com.raizlabs.android.dbflow.sql.language.Where.querySingle(Where.java:366)"
17 = {java.lang.StackTraceElement@4264} "com.raizlabs.android.dbflow.sql.language.From.querySingle(From.java:173)"
18 = {java.lang.StackTraceElement@4265} "com.homami.cars.database.DatabaseHelper.getChangeSetFromShop(DatabaseHelper.java:231)"
19 = {java.lang.StackTraceElement@4266} "com.homami.cars.tasks.SyncDynamicDataTask.requestShopCategories(SyncDynamicDataTask.java:97)"
20 = {java.lang.StackTraceElement@4267} "com.homami.cars.tasks.SyncDynamicDataTask.requestShop(SyncDynamicDataTask.java:79)"
21 = {java.lang.StackTraceElement@4268} "com.homami.cars.tasks.SyncDynamicDataTask.doInBackground(SyncDynamicDataTask.java:49)"
22 = {java.lang.StackTraceElement@4269} "com.homami.cars.tasks.SyncDynamicDataTask.doInBackground(SyncDynamicDataTask.java:23)"
23 = {java.lang.StackTraceElement@4270} "android.os.AsyncTask$2.call(AsyncTask.java:292)"
24 = {java.lang.StackTraceElement@4271} "java.util.concurrent.FutureTask.run(FutureTask.java:237)"
25 = {java.lang.StackTraceElement@4272} "android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)"
26 = {java.lang.StackTraceElement@4273} "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)"
27 = {java.lang.StackTraceElement@4274} "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)"
28 = {java.lang.StackTraceElement@4275} "java.lang.Thread.run(Thread.java:818)"

@surfer190 @vincekennedy did you guys get this relations to work? The List in my objekt is always null, also the ForeignKeyContainer in ShopItem. I am doing everything like in the doc.

**Comment by Informaticore** [comment]
@surfer190 @vincekennedy 

```java
            for (ShopCategory category : shopCategories) {
                category.save();
                for (ShopItem item : category.getShopItems()) {
                    item.setShopCategory(category);
                    item.save();
                }
            }
```

So ShopCategory = Queen and I guess ShopItem = Ant.

**Comment by surfer190** [comment]
@Informaticore I think the library can do all that work for you.

```
public void setShopCategory(ShopCategory shopCategory) {
        this.mShopCategory = new ForeignKeyContainer<>(ShopCategory.class);
        this.mShopCategory.setModel(shopCategory);
    }
```

My problem is that when I use `save()` after calling `associate()` I get an error:

```
Cannot call save() on a foreign key container. Call load() instead
```

**Comment by Informaticore** [comment]
@surfer190 I tried this as well but it was not working. The main differnce was, that I save the ShopCategory BEFORE I save the ShopItem. 

You can try to put q.save() before the for-loop

**Comment by surfer190** [comment]
The main thing is you have to call `save()` after `associate()` or `setShopCategory`.

Otherwise it won't save.

Problem is if you do:

```
com.raizlabs.android.dbflow.structure.container.ForeignKeyContainer$InvalidMethodCallException: Cannot call save() on a foreign key container. Call load() instead
```

Do you know why is this? Maybe @agrosner can help

**Comment by snezdoliy** [comment]
I have currently same issue as @surfer190 
If calling `save()` before `associate()` then foreign key value is not saved.
If calling `save()` after `associate()` then I am getting same exception.
I tried adding `queenModelContainer.put("queen_id", queen.id);` in `associateQueen(Queen queen)` method, but it seems for me as well that `ForeignKeyContainer` should take care of this itself when we `setModel` to it. 

Waiting for possible solution or workaround

**Comment by kendrikat** [comment]
Workaround for me is to set keys manually, since ``` setModel() ``` seems not to work... like:
````
a.setQueen(q);
a.save();
```
and 
```
public void setQueen(Queen q) {
  queenModelContainer = new ForeignKeyContainer<>(Queen.class);       
  queenModelContainer.setModel(q); // <-- ignored?
  queenModelContainer.put(Queen$Table.ID, q.id);
}

```
found here https://github.com/Raizlabs/DBFlow/issues/254#issuecomment-108237845

**Comment by snezdoliy** [comment]
@kendrikat I've done same within `setQueen` method but using `queen_id` instead of `Queen$Table.ID` (as `queen_id` is column name for foreign key in my `Ant` table), but when are you calling `setQueen` method? 
I am getting ants within Queen object as JSON and then if I am overriding `save` for `Queen` like this: 

```
    @Override
    public void save() {
        super.save();
        for (Ant ant : ants) {
            ant.setQueen(this);
        }
    }
``` 

My foreign key in `Ant` table is empty. 

If I do it like this: 

```
    @Override
    public void save() {
        for (Ant ant : ants) {
            ant.setQueen(this);
        }
        super.save();
    }
```

I am getting crash: 

```
    java.lang.RuntimeException: com.raizlabs.android.dbflow.structure.container.ForeignKeyContainer$InvalidMethodCallException: Cannot call save() on a foreign key container. Call load() instead
            at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:75)
     Caused by: com.raizlabs.android.dbflow.structure.container.ForeignKeyContainer$InvalidMethodCallException: Cannot call save() on a foreign key container. Call load() instead
```

**Comment by kendrikat** [comment]
I set ``` saveForeignKeyModel = false ``` and am saving (only the ants) like: 
```
// Queen q exists in DB at this point
a.setQueen(q);
a.save();
```
I think you can just omit "saving the queen" :)

**Comment by surfer190** [comment]
@kendrikat Mine still doesn't work:

```
public void associateTree(MyTree tree){
    myTreesModelContainer = new ForeignKeyContainer<>(MyTree.class);
    myTreesModelContainer.setModel(tree);
    //mytreeid
    Log.e("TAG", "tree id is: " + tree.id);
    myTreesModelContainer.put("mytreeid", tree.id);
  }
```

Calling the method I use:

```
            Log.e("TAG", "id is: " + mytree.id);
            mytreedetails.associateTree(mytree);
            mytreedetails.save();
```

It doesn't save the foreign key in the db. What am I doing wrong? 

This is `MyTreeDetails`:

```
@Table(databaseName = TreeDatabase.NAME)
public class MyTreeDetails extends BaseModel {
  @Column @PrimaryKey(autoincrement = true) long ID;
  @Column private String location;
  @Column private String note;
  @Column private String date;
  @Column
  @ForeignKey(references = {@ForeignKeyReference(columnName = "mytreeid",
                    columnType = Long.class,
                    foreignColumnName = "treeId")},
  saveForeignKeyModel = false)
  ForeignKeyContainer<MyTree> myTreesModelContainer;
```

Maybe @agrosner can help us clear this up?

**Comment by kendrikat** [comment]
I think ``` myTreesModelContainer.put("mytreeid", tree.id); ``` needs to be ``` myTreesModelContainer.put(MyTree$Table.ID, tree.id); ``` So the PK not the FK. (Just "id")

**Comment by surfer190** [comment]
@kendrikat Hmmm still not.

This is how `MyTree` looks:

```
@ModelContainer
@Table(databaseName = TreeDatabase.NAME)
public class MyTree extends BaseModel{
  @Column @PrimaryKey(autoincrement = true) public long id;
  @Column int treeId;
  @Column String treeGuid;
```

**Comment by iXnaL** [comment]
I got the same exception, and I've had to trace into the source code. 
Finally, I found that the __setModel()__ method just set the model class to model container but did not set the properties of model to the member "data" which __getData()__ method work with.

The two method in __BaseModelContainer__,  and not been overrided by __ForeignKeyContainer__
__BaseModelContainer line:42__
```javascript
    public void setModel(ModelClass model) {
        this.model = model;
    }
```
__BaseModelContainer line:68__
```javascript
    public void setData(DataClass data) {
        this.data = data;
        this.model = null;
    }
```

This is how the __getValue(String columnName)__ worked.
__ForeignKeyContainer line:31__
```javascript
    public Object getValue(String columnName) {
        return ((Map)this.getData()).get(columnName);
    }
```
__BaseModelContainer line:64__
```javascript
    public DataClass getData() {
        return this.data;
    }
```
__So the question is, is this a bug or the usage documentation need to be modified?__

**Comment by surfer190** [comment]
@all The example given in the guides actually works, provided the details supplied for the `ForeignKey Column` is correct. Double check to make sure this data is correct.

**Comment by iXnaL** [comment]
@surfer190 So how is your problem solved? By changing some annotation?

**Comment by surfer190** [comment]
@iXnaL 

@ForeignKey(references = {@ForeignKeyReference(columnName = "mytreeid",
                    columnType = Long.class,
                    foreignColumnName = "id")},
  saveForeignKeyModel = false)
  ForeignKeyContainer<MyTree> myTreesModelContainer;

**The foreign key column string was incorrect**: changed from `treeId` to `id`

**Comment by iXnaL** [comment]
@surfer190 Do you use DBFlow for android development?

**Comment by ShagunParikh** [comment]
I am facing the same issue.. Forreign key is blank in the table.. please help @agrosner .

**Comment by btquanto** [comment]
I'm having the same issue. @agrosner this is pretty serious!

**Comment by grandvortex** [comment]
So has anyone solved this issue or perhaps has some pointers?  This is my 1-many code.  
I have a ListModel that has multiple SectionModels.  I'd really appreciate the help!  Thanks!

//Inside ListModel
public List<SectionModel> sections;
   @OneToMany(methods = {OneToMany.Method.ALL}, variableName = "sections")
    public List<SectionModel> getSections() {
        if (sections == null) {
            sections = new Select()
                    .from(SectionModel.class)
                    .where(Condition.column(SectionModel$Table.LISTMODELCONTAINER_LIST_ID).is(id))
                    .queryList();
        }
        return sections;
    }
------------------------------------------------------------------------------------------------------------------------------
//Inside SectionModel

@Column
@ForeignKey(references = {@ForeignKeyReference(columnName = "list_id", columnType = String.class, foreignColumnName = "id")}, saveForeignKeyModel = false)
ForeignKeyContainer<ListModel> listModelContainer;

public void associateListWithSection(ListModel list) {
        listModelContainer = new ForeignKeyContainer<>(ListModel.class);
        listModelContainer.setModel(list);
}

------------------------------------------------------------------------------------------------------------------------------
//Inside View Presenter
This is how I save them: 
metropolitanModel.cardList.save();

for (SectionModel section : metropolitanModel.cardSections) {
      section.associateListWithSection(metropolitanModel.cardList);
       section.save();
 }

**Comment by KChernenko** [comment]
As I understood, Foreign Keys doesn't work?

**Comment by micHar** [comment]
It's the most basic functionality of a relational database, so I assume it has to work.
But I can't find any docs about saving the data to the db and for me the example doesn't work either.

**Comment by KChernenko** [comment]
@micHar 
I've tried to use his solution, but it didn't help.

**Comment by micHar** [comment]
@KChernenko 
I have different models, so I won't post the code not to confuse anyone, but for me it was:

1. Manually put the foreign key in the foreign container, as in @kendrikat's solution.
2. Use a specific flow (which makes sense if you think how sql works under the hood. So
   1. Make a Queen and save it
   2. Make an Ant
   3. Associate the Ant with the Queen
   4. Save the Ant.

**Comment by ShagunParikh** [comment]
@KChernenko I did the same. But it creates an issue while deleting the Queen. An Ant associated with the Queen does not get deleted on deleting that Queen. Do you have any solution for that?

**Comment by kihaki** [comment]
Yeah, I cannot get this to work either. Trying to store comments for a post, but the 1-many relationship always fails, even though I basically copied and pasted the Queen/Ant code. Something is missing here.

**Comment by deviant-studio** [comment]
same issue. can anybody provide simple working example?

**Comment by romulof** [comment]
Just make this way:

``

**Comment by agrosner** [comment]
It's fixed in develop with working example test code in the test folder
