### ISSUE TITLE
warning - Attempt to recreate a file for type config.data$Database

### ISSUE THREAD

**Issue by battlmonstr** [Raizlabs/DBFlow#314]
With version 2.2.1 I'm getting 2 warnings when building the project:

Warning:Attempt to recreate a file for type com.raizlabs.android.dbflow.config.data$Database
Warning:File for type 'com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder' created in the last round will not be subject to annotation processing.

After fixing https://github.com/Raizlabs/DBFlow/issues/285 I was expecting that those warnings will be gone.

Why wasn't it made silent as a part of issue 285?
What is the purpose of those warnings? What are they telling? Is it something I can fix?

**Comment by agrosner** [comment]
Its incase something went wrong in the writing process. I can just remove it or something.

**Comment by woodcockjosh** [comment]
I think it's not necessary. If something went wrong the compile should fail. The warning isn't helpful. If there's any issue the developer can clean and rebuild.

**Comment by teddis** [comment]
This is uglifying our build. How can we suppress this?

> warning: Attempt to recreate a file for type com.raizlabs.android.dbflow.config.gameon$Database
warning: Attempt to recreate a file for type com.raizlabs.android.dbflow.config.gameon$Database
> warning: File for type 'com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder' created in the last round will not be subject to annotation processing.
> 3 warnings

**Comment by woodcockjosh** [comment]
Yes super ugly.

**Comment by agrosner** [comment]
fixed in `develop`
