### ISSUE TITLE
In-Memory SQLite DB

### ISSUE THREAD

**Issue by johntvolk** [Raizlabs/DBFlow#315]
Hi,

In the documentation for SQLiteOpenHelper it mentions that you can send `null` as the value for name parameter in its constructor to create an in-memory DB. It seems like the design of FlowSQLiteOpenHelper prevents one from doing this. Is there another way to accomplish this in DBFlow? If not, could one accomplish this by forking the project and simply adding a constructor to FlowSQLiteOpenHelper, or does the general design of DBFlow preclude this sort of thing? Thanks!

John

**Comment by agrosner** [comment]
@johntvolk its meant not to be in memory, rather on disk since all code is precompiled and analyzed pre-runtime. Never even knew you could create an in-memory DB. If you forked the project, would it work?

**Comment by johntvolk** [comment]
@agrosner We haven't ended up needing this yet, but we may take a look in the next few months again. Would you be interested in looking at a PR for this if we figured it out?

**Comment by agrosner** [comment]
fixed in 3.0.0+
