### ISSUE TITLE
Simple notification test with Robolectric

### ISSUE THREAD

**Issue by glureau** [Raizlabs/DBFlow#317]
I've tried to make very simple test to check automatically ContentProvider notifications on my project, but finally I'm stuck to run a test with RobolectricGradleTestRunner from AndroidStudio or directly with gradle.

build.gradle

    apply plugin: 'com.neenbedankt.android-apt'

    android {
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_7
            targetCompatibility JavaVersion.VERSION_1_7
        }
        ....
    }
    dependencies {
        apt 'com.raizlabs.android:DBFlow-Compiler:2.2.1'
        compile 'com.raizlabs.android:DBFlow-Core:2.2.1'
        compile 'com.raizlabs.android:DBFlow:2.2.1'
        ....
    }

DBFlowNotificationTest.java

    @RunWith(RobolectricGradleTestRunner.class)
    @Config(constants = BuildConfig.class)
    public class DBFlowNotificationTest {
        @Test
        public void test() {
            final TestModel1 foo = new TestModel1();
            System.out.println("foo: " + foo);
            FlowManager.init(RuntimeEnvironment.application);
        }
    }

TestDatabase.java

    @Database(name = TestDatabase.NAME, version = 3, foreignKeysSupported = true)
    public class TestDatabase {
        public static final String NAME = "Test";
    }

TestModel1.java

    @Table(databaseName = TestDatabase.NAME)
    @ModelContainer
    public class TestModel1 extends BaseModel {
        @Column
        @PrimaryKey
        public String name;

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            TestModel1 that = (TestModel1) o;
            return !(name != null ? !name.equals(that.name) : that.name != null);
        }
        @Override
        public int hashCode() {
            return name != null ? name.hashCode() : 0;
        }
    }

output

    java.lang.RuntimeException: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder
        at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:119)
        at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:158)
        at com.***.dbflow.DBFlowNotificationTest.test(DBFlowNotificationTest.java:36)

------------------------------------------------------
EDIT:
My problem was the apt doesn't generate sources for the test directory. My workaround is to use directly Model in src, not very beautiful, still hoping a better solution.

**Comment by glureau** [comment]
In the meantime, I have cloned the repository and updated it on master.
Once loaded in AndroidStudio, every write to TestContentProvider$Provider is in error, seems logic because it's dynamically generated, but not cool to use as is.
How do you manage this? Just removing the warning in AS?

**Comment by agrosner** [comment]
@glureau maybe try it now? in newest version `1.7` now supports the `test` directory (https://bitbucket.org/hvisser/android-apt)

**Comment by agrosner** [comment]
PS How did you get Roboelectric working with DBFlow? I might consider switching to it for quicker tests.
