### ISSUE TITLE
Transactions fire multiple onModelStateChange

### ISSUE THREAD

**Issue by easyspeak** [Raizlabs/DBFlow#319]
I am using FlowContentObserver.OnModelStateChangedListener() and noticed that I get change event for each model contained in a SaveModelTransaction. My hope was by grouping the models in a transaction only a single model change event would be fired. Is there some way to only receive a single onModelStateChanged() call at the end of the transaction instead of per model?

```java
mFlowObserver = new FlowContentObserver();
mFlowObserver.registerForContentChanges(getContext(), tableClass);
mFlowObserver.addModelChangeListener(new FlowContentObserver.OnModelStateChangedListener() {
            @Override
            public void onModelStateChanged(Class<? extends Model> table, BaseModel.Action action) {
               //this is being called for every model in the transaction
            }
};);

ProcessModelInfo<SomeModel> processModelInfo = ProcessModelInfo.withModels(models);
TransactionManager.getInstance().addTransaction(new SaveModelTransaction<>(processModelInfo));
```

**Comment by agrosner** [comment]
@easyspeak you need to pass the `FlowContentObserver` into the `SaveModelTransaction` and will batch them all up.
