### ISSUE TITLE
Save relationship with TransactionManager

### ISSUE THREAD

**Issue by tsuharesu** [Raizlabs/DBFlow#32]
I have 2 models with a One-to-Many relationship, like below:

``` java
@Table
public class Dashboard extends BaseModel {
...
List<Chart> charts;
}
```

``` java
@Table
public class Chart extends BaseModel {
    ...
    @Column(columnType = Column.FOREIGN_KEY, references = {@ForeignKeyReference(columnName = "dashboard_id", columnType = int.class, foreignColumnName = "id")})
    Dashboard dashboard;
}
```

After creating a list of dashboards with Charts, I'm saving them on a transaction with `TransactionManager.getInstance().save(ProcessModelInfo.withModels(dashboards))` my dashboards are saved but the charts inside are not. Am I missing something? Do I need to iterate through all dashboards and save charts in a similiar transaction?

**Comment by damson** [comment]
If you save the dashboards, their charts won't be saved automatically because there are no DBFlow link from Dashboard to Chart.

> The reason why there is no support for 1-many in the annotation side is to encourage lazy-loading of the many field relationships. This ensures much faster performance on a large scale when loading many objects of a table, and by only using them when you need them.



So you need save them by yourself. And instead of iterate through all of them, you should consider using these method .

 ```
/**
     * Saves all of the passed in models to the DBBatchSaveQueue
     * This method is recommended for saving large amounts of continuous data as to batch up as much data as possible in a save.
     *
     * @param models       The list of models to save
     * @param <ModelClass> The class that implements Model
     */
    public <ModelClass extends Model> void saveOnSaveQueue(Collection<ModelClass> models)

```

**Comment by tsuharesu** [comment]
Oh, I see. But I did not get the "instead of iterate..." part, because I will need to get the charts from each dashboard and save them using a TransactionManager anyway, right? 

I'm doing like this:
```java
for (Dashboard dashboard : dashboards) {
    TransactionManager.getInstance().saveOnSaveQueue(dashboard.getCharts());
}
TransactionManager.getInstance().saveOnSaveQueue(dashboards)
```

**Comment by agrosner** [comment]
@tsuharesu @damson depends on how much data that gets processed but I would shy away from using the ```DBBatchSaveQueue```because it batches the saves when the queue is full, however when the queue remains not completely full, it defaults to a "check" time of 30 seconds. If you are saving a very large amount of data that does not need to be shown right away, then this would make sense. If not, I would stick with ```TransactionManager.getInstance().save(ProcessModelInfo.withModels(dashboards))```. You can also override the ```save()``` method for your ```Dashboard``` class and save the contained data manually. 

For a real performance gain, if you know this is existing data you can do ```TransactionManager.getInstance().update(ProcessModelInfo.withModels(dashboards))```, or ```TransactionManager.getInstance().insert(ProcessModelInfo.withModels(dashboards))``` if new data.

**Comment by agrosner** [comment]
This is how I would do it:

```java

public void save(boolean async) {
  super.save(async);
  new SaveModelTransaction(ProcessModelInfo.withModels(charts)).execute();
}

```

If you use the ```TransactionManager``` for the call, it will for each inner set of ```Model``` save as a ````BEGIN TRANSACTION...END TRANSACTION``` piece. This is very inefficient when you call this many different times vs. batching them up into a larger transaction. So I suggest using this (above) to run the save in the same transaction as its parent object, as this will be a very noticeable difference when saving multiple items at a time.

**Comment by agrosner** [comment]
if this answers your question, @tsuharesu would you mind closing it?

**Comment by damson** [comment]
@agrosner I can find the `onExecute()` method but not the `execute()` method.
I didn't know this way of using transactions, I thought they could only be used like that: `TransactionManager.getInstance().addTransaction(myTransaction);`

And saving a basic model `with save(true)` will actually create a new `SaveModelTransaction` added to the `DBTransactionQueue`
So how can we add a new `SaveModelTransaction` for saving associations (like `charts` above) and incorporate it to the save transaction of its parent model like you said ?

**Comment by damson** [comment]
I think we could avoid the `BEGIN TRANSACTION...END TRANSACTION` behavior using a custom transaction. Saving all models in the `onExecute` method of a `BaseTransaction`

**Comment by agrosner** [comment]
sorry I meant ``onExecute()```. The ```TransactionManager``` simply adds the object to the ````DBTransactionQueue``` and that's how the transactions are processed. The base class, ```ProcessModelTransaction```, will wrap the ```onExecute()``` call within a single Transaction.

Yes, there are a few ways to do something in this library, and usually it comes down to personal preference. 

The simplest solution without using begin and end transaction is simply (in Dashboard.java):

```java
public void save(boolean async) {
  super.save(async);
  for(Chart chart: charts) {
    chart.save(false);
  }
}

```

**Comment by tsuharesu** [comment]
@agrosner thanks for all the tips, I think this answers my question and give a lot of options for people with the same 'problem'.
