### ISSUE TITLE
How to do this?

### ISSUE THREAD

**Issue by darkovski88** [Raizlabs/DBFlow#322]
Hello,
I have a model class, that cotains a list of other model classes inside. So when I setup the DBFlow make the model class like this:
<code>
 @Table(databaseName = AppDatabase.NAME) 
public class Response extends BaseModel{
 @SerializedName("existing_plan_generation")
@Expose
@Column
private String existingPlanGeneration;
@Expose
@Column
private List<Bill> bills = new ArrayList<Bill>();
@Expose
@Column
private List<Final> finals = new ArrayList<Final>();
@Expose
@Column

private List<Filter> filters = new ArrayList<Filter>();

/**
 *
 * @return
 * The existingPlanGeneration
 */
public String getExistingPlanGeneration() {
    return existingPlanGeneration;
}

/**
 *
 * @param existingPlanGeneration
 * The existing_plan_generation
 */
public void setExistingPlanGeneration(String existingPlanGeneration) {
    this.existingPlanGeneration = existingPlanGeneration;
}

/**
 *
 * @return
 * The bills
 */
public List<Bill> getBills() {
    return bills;
}

/**
 *
 * @param bills
 * The bills
 */
public void setBills(List<Bill> bills) {
    this.bills = bills;
}

/**
 *
 * @return
 * The finals
 */
public List<Final> getFinals() {
    return finals;
}

/**
 *
 * @param finals
 * The finals
 */
public void setFinals(List<Final> finals) {
    this.finals = finals;
}

/**
 *
 * @return
 * The filters
 */
public List<Filter> getFilters() {
    return filters;
}

/**
 *
 * @param filters
 * The filters
 */
public void setFilters(List<Filter> filters) {
    this.filters = filters;
}
}
</code>
I get this error that I don't know how to solve?
<code>
 Error:Execution failed for task ':app:compileDebugJava'.
java.lang.RuntimeException: Writing insert statement failed for: null. A type convertermust be defined for this type, or if this field is a Model, must be a foreign key definition. 
</code>

**Comment by ydanneg** [comment]
There are at least two ways how to do this:
1. Provide TypeCoverter for each typed List. But you have to subtype every list like that:

YourModelList.java
```
public class YourModelList extends ArrayList<Integer> {
}
```

YourModelListConverter.java
```
@com.raizlabs.android.dbflow.annotation.TypeConverter
public class YourModelListConverter extends TypeConverter<String, YourModelList> {

    @Override
    public String getDBValue(YourModelList model) {
        return new Gson().toJson(model);
    }

    @Override
    public IntegerList getModelValue(String data) {
        return new Gson().fromJson(data, YourModelList.class);
    }
}
```
IMHO this solution is not good due to code aamoutn and serialize/deserialize perfomance.
@agrosner I hope some time DBFlow will support default List and Map converters, where user only needs to provide real type converter.

2. Use OneToMany method [https://www.youtube.com/watch?v=1uBNhiwE9Tw] (https://www.youtube.com/watch?v=1uBNhiwE9Tw)

**Comment by agrosner** [comment]
yeah, but the whole concept breaks relational database design which _explicitly_ state that you have only one value per column per row. 

If you wish to properly support this
1.  you don't make the `List<Type>` a column but rather make a separate table for the items that go in that list. 
2. Use a `@OneToMany` relationship to associate that list with the current table.
3. When you save the list of items, you will need a column that is a `@ForeignKey` or `@Column to the current table so it can be referenced properly.

**Comment by ydanneg** [comment]
@agrosner The method you described here causes circular queries.
OneToMany loads sub-models and submodel loads model referenced by ForeignKey...

**Comment by agrosner** [comment]
@ydanneg then you will need to remove the `Model` field as the `ForeignKey` and use the non-model version. Its unfortunate, but its nearly impossible to fix unless you do it that way.

**Comment by agrosner** [comment]
closing this
