### ISSUE TITLE
OrderBy collate LOCALIZED is there any way?

### ISSUE THREAD

**Issue by hipczor** [Raizlabs/DBFlow#325]
Is there any way to use collate localized in orderBy method? I see that after update to 2.2.0 you have changed completely orderBy logic and simple 

.orderBy(true, Province$Table.NAME + " COLLATE LOCALIZED")

doesn't work anymore.

**Comment by agrosner** [comment]
@hipczor just use `orderBy(Province$Table.NAME + " COLLATE LOCALIZED ASC")`
