### ISSUE TITLE
How to use ForeignKeyContainer

### ISSUE THREAD

**Issue by DenisGL** [Raizlabs/DBFlow#328]
With the Getting Started example model, I tried the following:

        Colony colony = new Colony();
        colony.name = "DBFlow Colony";
        colony.save();

        System.out.println("Colony: " + new Select().from(Colony.class).querySingle().toString());
        // => Colony:Colony{id=1, name='DBFlow Colony'} : OK

        Queen queen = new Queen();
        queen.name = "The Queen";
        queen.colony = colony;
        queen.save();

        System.out.println("Queen: " + new Select().from(Queen.class).querySingle().toString());
        // => Queen: Queen{id=1, name='The Queen', colony=Colony{id=1, name='DBFlow Colony'}, ants=null} : OK

        Ant ant1 = new Ant();
        ant1.type = "mater";
        ant1.isMale = true;
        ant1.associateQueen(queen);
        ant1.save();

        System.out.println("Ant1: " + new Select().from(Ant.class).querySingle().toString());
        // => Ant1: Ant{id=1, type='warrior', isMale=true, queenModelContainer=null}

At this point `queenModelContainer` is null. Is this normal ?

**Comment by romulof** [comment]
Same problem here.

It seems `ForeignKeyContainer` has a `ModelClass` object on it, but it does not save. It's used only for reading from database, not saving. To save data it is using `DataClass` object, but I don't know the relationship between a model and this dataclass.

**Comment by romulof** [comment]
This issue is duplicated:

https://github.com/Raizlabs/DBFlow/issues/313

**Comment by DenisGL** [comment]
I close it, because it’s a duplicate of #313 .
