### ISSUE TITLE
Where is created DB stored?

### ISSUE THREAD

**Issue by TiagoMota** [Raizlabs/DBFlow#33]
Usually the DB file is stored under /data/data/com.yourpackage.yourapp/databases/yourdb

I'm using DBFlow and I need to debug the contents of my Database and I don't find it anywhere. Someone can help?

Cheers, and sorry for opening an issue just for this.

**Comment by agrosner** [comment]
and that is where it goes. Did you create the ```@Database``` definition class and call either any database operation or ```FlowManager.getDatabase(databaseName).getWriteableDatabase()```?

**Comment by TiagoMota** [comment]
You're right, I wasn't using the DB anywhere, just added the models and compiled everything. I just assumed that the FlowManager.init() would do this for me.

Anyways, thanks for the help. You can close the issue know.
