### ISSUE TITLE
Variables naming in generated $Adapters

### ISSUE THREAD

**Issue by syndarin** [Raizlabs/DBFlow#333]
Hello!
I've created some models some time before and succeeded with compilation. After that I decided to rename some of variables to improve code readability, but for some reason generated $Adapter file uses old class variable name, so compilation fails.
Clean/Rebuild project doesn't help.

**Comment by agrosner** [comment]
you need to add `name = {oldName}` to your `@Column` that you changed. If you leave out the name, it defaults to the variable name.
