### ISSUE TITLE
Is there the ability to compress the database?

### ISSUE THREAD

**Issue by surfer190** [Raizlabs/DBFlow#334]
I noticed that with the [Android SQLite Asset Helper](https://github.com/jgilfelt/android-sqlite-asset-helper) you can `zip` or `gzip` the database.

Can we add this functionality to `DBFlow` to decrease total app size?

**Comment by agrosner** [comment]
Not officially supported as of right now. That said this could make it for a prepackaged database file instead. On first launch it would unload the database onto the device. Possible, will keep it in mind for `3.0` but not sure if its high priority right now.
