### ISSUE TITLE
Migrations - Unable to add new column and define an index on it using same migration version.

### ISSUE THREAD

**Issue by petroski77** [Raizlabs/DBFlow#338]
Hi!

I'm trying to do the following:
1. Define an AlterTableMigration which adds a new column to an existing table.
2. Define an indexMigration which adds an index to the new column.

It seems to go wrong because DBFlow runs the IndexMigration first and secondly the AlterTableMigration.

I can make it work if I add the column in version x and the index in version x+1, but I would really like do it in the same version.

Best regards
Christian

**Comment by agrosner** [comment]
good idea. I think what I can do is add a priority for migrations, such that one gets executed before another?

**Comment by petroski77** [comment]
Thank you for your fast response!

Yes, that would be a perfect solution :)

**Comment by agrosner** [comment]
its in `develop` @petroski77  so def in `2.3.0`
