### ISSUE TITLE
Join returns row number instead of object ID

### ISSUE THREAD

**Issue by darkovski88** [Raizlabs/DBFlow#342]
Hello,
I'm using DBflow in my app but when I do a join I get the row number instead of the object id.
Here is my code:
```java
topContracts = new Select().from(Plan.class).as("p")
   .join(MobileOperator.class, Join.JoinType.INNER).as("m").
   on(Condition.column("p." + Plan$Table.OPERATOR_ID)
    .eq("m." + MobileOperator$Table.ID_)).
   orderBy(false, "p." + Plan$Table.SAVINGS_AMOUNT)
    .limit(3).groupBy("m." + MobileOperator$Table.ID_).queryList();
```

Also is there a way to get the top 3 rows to have a maximum `Plan$Table.SAVINGS_AMOUNT` value?

**Comment by agrosner** [comment]
@darkovski88 for Joins on other classes you need to create a `@QueryModel` and then call `queryCustomList(MyCustomModel.class)`
