### ISSUE TITLE
How can I build a Condition with two column

### ISSUE THREAD

**Issue by markzhai** [Raizlabs/DBFlow#343]
How can I build a Condition with two column? 
say like 'column1 + column2 < 10000'

**Comment by markzhai** [comment]
In detail, I want to do 
delete * from Table1 where expiration_time + timestamp >= currentTimeMillis

It seems we have
                    new Delete().table(CacheObject.class, Condition
                            .column(CacheObject$Table.EXPIRATION_TIME)
                            .operation(Condition.Operation.PLUS)
                             // how to append another column here?
                            .lessThanOrEq(System.currentTimeMillis()));

**Comment by agrosner** [comment]
for now you can do 
```java
new Delete().table(CacheObject.class, Condition
  columnRaw(CacheObject$Table.EXPIRATION_TIME + " " + Condition.Operation.PLUS )
     lessThanOrEq(System.currentTimeMillis()));
```

In `3.0.0` conditions will  be _vastly_ improved.

**Comment by agrosner** [comment]
in 3.0.0, you simply:
```
'column1 + column2 < 10000'
```
to
```java
MyTable_Table.column1.plus(MyTable_Table.column2).lessThan(10000);
```
woo!

**Comment by agrosner** [comment]
note each column must be of same type
