### ISSUE TITLE
Can't restore DB from backup

### ISSUE THREAD

**Issue by mkovalyk** [Raizlabs/DBFlow#347]
FlowManager.getDatabaseForTable(table).backupDB() doesn't work in version 2.2.1.
I see only method backupDatabase(), but no restore methods in BaseDatabaseDefinition.

**Comment by agrosner** [comment]
@mkovalyk restore will happen automatically when the DB  is reopened. The backup mechanism is meant to only work for cases when the database integrity check fails, and the backup DB is not corrupt.
