### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by iainconnor** [Raizlabs/DBFlow#35]
Let me begin by saying thank you for the effort that has clearly gone into this library. I think it shows great promise! Just a few questions;

1. Have you considered replacing [mModelCache](https://github.com/Raizlabs/DBFlow/blob/a0a5ee6a935005a857e976f5d3ba58d141b570ba/library/src/main/java/com/raizlabs/android/dbflow/list/FlowCursorList.java#L30) with an [LRU Cache](http://developer.android.com/reference/android/util/LruCache.html)? It might better support using an adapter in a ListView/RecyclerView as only the most recently accessed items would be fully inflated (be in the cache) whereas the items "far" outside the window of the list the user is currently looking at could be safely evicted (and recreated if and when they are brought back into focus). I'd be happy to help with a pull-request if this sounds like something interesting.

2. Does [FlowCursorList](https://github.com/Raizlabs/DBFlow/blob/a0a5ee6a935005a857e976f5d3ba58d141b570ba/library/src/main/java/com/raizlabs/android/dbflow/list/FlowCursorList.java#L45) perform its query on the UI thread by default? It seems like the [provided example](https://github.com/Raizlabs/DBFlow/blob/master/usage/TableList.md#cursor-list) would perform the query on the UI thread at the time of the adapter's creation. Any thoughts on how to work around that?

3. Any suggestions on observing changes to a table from a [FlowCursorList](https://github.com/Raizlabs/DBFlow/blob/master/usage/TableList.md#cursor-list)? I see the [CursorObserver](https://github.com/Raizlabs/DBFlow/blob/a0a5ee6a935005a857e976f5d3ba58d141b570ba/library/src/main/java/com/raizlabs/android/dbflow/list/FlowCursorList.java#L175) being registered, but doesn't [setNotificationUri](http://developer.android.com/reference/android/database/Cursor.html#setNotificationUri(android.content.ContentResolver, android.net.Uri)) have to be called with the same uri as generated in [FlowContentObserver](https://github.com/Raizlabs/DBFlow/blob/294cf1f0fcf6e7a50842d1436e44b1fb70014473/library/src/main/java/com/raizlabs/android/dbflow/runtime/FlowContentObserver.java#L58) to actually wire this up?

4. Related to the previous two points, was there a reason you opted to not generate/wrap a [ContentProvider](http://developer.android.com/guide/topics/providers/content-provider-basics.html) so that [CursorLoader](http://developer.android.com/reference/android/content/CursorLoader.html) could be used with a [LoaderManager](http://developer.android.com/reference/android/app/LoaderManager.html)?

5. How are one-to-one relationships currently handled? Are they fetched via another query at the time a Cursor is loaded into the parent Model? Any thoughts on the performance of running this operation -- particularly if models with one-to-one relationships need to be satisfied in a ListView/RecyclerView as the list is being scrolled? As far as I can tell, this would result in queries being executed on the UI thread as the list is attempting to render.

Apologies for the dump of questions. Again, if you're looking for a hand on implementing any of this, please let me know and keep up the great work!

**Comment by agrosner** [comment]
Thanks for writing this!

1. That would require me to add the v4-support library as a dependency. That is not really what I would like to do as this could cause potential transitive dependency issues. It's really not a bad idea, I just don't want to pull the dependency in if this is the only one using it. However, if you put a pull request with adding just the class or an impressive caching solution, I will take a look!

2. FlowCursorList is a non-modifiable, read-only cursor backed list. It does conversions into Model on the main thread when converting them. 

3. This is based on the ```CursorAdapter``` from the android SDK. It will call ```refresh()``` and rerun the query underneath it. If you wish to notify your `Adapter` of those changes, override ```refresh()``` and call `notifyDataSetChanged()` on your adapter that contains this ```FlowCursorList```

4. Did not think of it. Why would this be necessary for this class? The `FlowCursorAdapter` is meant for use in a `BaseAdapter`, and I thought Loaders were meant for actions within an `Activity`. 

5. Fields that are specified as ```ColumnType.FOREIGN_KEY``` and are models will have their SELECT statement to retrieve the Model done on load of the model. Only if the cursor returns a non-NULL column. I guess this is a possible option to lazy-load the one-to-one as one-to-many will work this way. 

And yes any pull request with code you write that makes sense I will give it a thorough review. Also here are some rules:
1. Match coding style (braces, spacing, etc.) This is best achieved using CMD+Option+L (Reformat code) on Mac (not sure for Windows) with Android Studio defaults.
2. If its a feature, bugfix, or anything please only change code to what you specify. Ex: "Fixes Crash Related to Bug" includes other files that were changed without explanation or doesn't relate to the bug you fixed.
3. Have fun!

**Comment by agrosner** [comment]
@iainconnor if this answers your question, could you close this? thanks

**Comment by iainconnor** [comment]
Yes, thanks for getting back to me so quickly. Will close. :+1:

**Comment by gustahrodrigues** [comment]
Hi Guys,

I am very interesting in ContentProvider to use with CursorLoader. Is there any news about that?

**Comment by iainconnor** [comment]
Seems like this might have [already been implemented](https://github.com/Raizlabs/DBFlow/blob/master/usage/ContentProviderGenerators.md), @gustahrodrigues
