### ISSUE TITLE
Model caching with String

### ISSUE THREAD

**Issue by ndmt** [Raizlabs/DBFlow#350]
Hello,

I would like to know if it is possible to implement a custom String based model caching class like that :

    public class StringModelCaching<ModelClass extends Model> extends ModelCache<ModelClass,         LruCache<String, ModelClass>> {

        public StringModelCaching(int size) {
            super(new LruCache<String, ModelClass>(size));
        }

        @Override
        public void addModel(Object id, ModelClass model) {
            if(id instanceof String) {
                synchronized (getCache()) {
                    getCache().put(id.toString(), model);
                }
            } else {
                throw new IllegalArgumentException("A ModelLruCache uses an String");
            }
        }
        ....
    }

But I have some problems, for example : 

    new Select().from(Model.class).queryList();

at com.raizlabs.android.dbflow.sql.SqlUtils.convertToCacheableList(SqlUtils.java:90)
because of : 
    BaseCacheableModel cacheable = (BaseCacheableModel)modelCache.get(Long.valueOf(id));

With FlowQueryList there is no problem, but I don't know if I doing it well..

**Comment by agrosner** [comment]
@ndmt good find. Its actually a _bug_. so let me fix it.

**Comment by agrosner** [comment]
resolved in 3.0+
