### ISSUE TITLE
How to run batch insert in synchronous transaction

### ISSUE THREAD

**Issue by mkorszun** [Raizlabs/DBFlow#353]
I am struggling to make it happen and can not find anything in documentation. Please help!

**Comment by ydanneg** [comment]
TransactionManger.getInstance().transact(MyDatabase.NAME, runnable);

**Comment by mkorszun** [comment]
@ydanneg `transact(MyDatabase.NAME, runnable)` i do not see such a method in version `2.2.1`

**Comment by ydanneg** [comment]
It there and it's static.

https://github.com/Raizlabs/DBFlow/blob/master/DBFlow/src/main/java/com/raizlabs/android/dbflow/runtime/TransactionManager.java

**Comment by ydanneg** [comment]
This is how I save collection of models synchronously:

```
public static <T extends BaseModel> void saveModelList(final Collection<T> models) {
    if (!LangUtils.isCollectionEmpty(models)) {
        TransactionManager.transact(Database.NAME, new Runnable() {
            @Override
            public void run() {
                for (T model : models) {
                    model.save();
                }
            }
        });
    }
}
```
Hope it helps.

**Comment by agrosner** [comment]
@mkorszun you can also do: `new InsertModelTransaction<>(processModelInfo).onExecute()`
