### ISSUE TITLE
Many-to-One relationship failing at compile time

### ISSUE THREAD

**Issue by vIiRuS** [Raizlabs/DBFlow#354]
Hi,

So I tried to build a One-to-Many relationship between two of my models. I used the [Getting Started](https://github.com/Raizlabs/DBFlow/blob/master/usage/GettingStarted.md) page as a guideline on how to do so. But for some reason I am getting an error during compilation:

    Error:Gradle: A Model or ModelContainer field must be a @ForeignKeyReference. Found Column: tags and type: com.example.MyModel

Googling this problem only got me the source code portion in the validator, where this error appears. If I understand the code right, it checks every column on the model for issues. But the *tags* field does not have the *Column* annotation. So I don't understand why DBFlow apparently tries to validate it as such.

This (partially) is the parent model (

    @ModelContainer
    @Table(databaseName = MyDatabase)
    public class MyModel extends BaseModel {
    
        List<Tag> tags;

        @Column
        @PrimaryKey
        String id;

        @Column
        public String text;
        /**
         * @return the id
         */
        public String getId() {
            return id;
        }
        /**
         * @param id the id to set
         */
        public void setId(String id) {
            this.id = id;
        }
        /**
         * @return the text
         */
        public String getText() {
            return text;
        }
        /**
         * @param text the text to set
         */
        public void setText(String text) {
            this.text = text;
        }

        @OneToMany(methods = {OneToMany.Method.ALL}, variableName = "tags")
        public List<TaskTag> getRewards() {
            if(tags == null) {
                tags = new Select()
                        .from(Tag)
                        .queryList();
            }
            return tags;
        }

    }

and the "to-many" model

    @Table(databaseName = HabitDatabase.NAME)
    public class TaskTag extends BaseModel {
    
        @Column
        @PrimaryKey(autoincrement = true)
        long id;

        @Column
        @ForeignKey(references = {@ForeignKeyReference(columnName = "task_id",
                columnType = String.class,
                foreignColumnName = "id")})
        private ForeignKeyContainer<MyModel> model;

    
        public MyModel getModel() {
            return model.toModel();
        }
    
        public void setTask(MyModel model) {
            this.model = new ForeignKeyContainer<>(MyModelclass);
            this.model.setModel(model);
        }
    }

I hope somebody can point me in the right direction, as I have no idea how to solve this problem.
Thanks

**Comment by grandvortex** [comment]
Hey, 

Did you ever get your question answered?  Also, when/where do you actually call the setTask method, or does the system call it?

**Comment by vIiRuS** [comment]
The solution seems to be that I was subclassing the model. (so MyModel had a MySubModel) After refactoring that to have two seperate classes I could get it to work. So I guess the question is: did I do something wrong or do DBFlows foreign keys not work when subclassing is involved?
fwiw I also tried it the other way around and added the List<Tag> tags to the subclass with the same error.

**Comment by grandvortex** [comment]
Hey vliRus, 

I managed to get the app compiled with all the annotations, but when I look for it on my emulator data/data/***/ there is not database.  Does DBFlow automatically create the db as soon as the Model object is created?  Or do I have to call save() method like ActiveAndroid?  I really hope you can help me out buddy.

**Comment by agrosner** [comment]
this is fixed in 3.0.0. as for that last question, you need to run a query or call `FlowManager.getDatabase(..).getWritableDatabase()`
