### ISSUE TITLE
upgrade DB with the new version Number and remove the one with old version.

### ISSUE THREAD

**Issue by saurabhghewari** [Raizlabs/DBFlow#355]
Hi,
I am new to android and DBflow but have experience using ORMs for web Databases. I want to remove the old version of database when user updates the application from the play store. how can this be achieved using DBFlow DatabaseHelperListener interface or FlowSQLiteOpenHelper class? I have followed the database creation method from the Documentation its working fine. But now i want to create new database removing the old one?

**Comment by saurabhghewari** [comment]
I followed the SugarORM documentation to get it done.

**Comment by KeitelDOG** [comment]
Any link on the SugarORM upgrade db?

**Comment by saurabhghewari** [comment]
http://satyan.github.io/sugar/migration.html
