### ISSUE TITLE
Another AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY (code 1)

### ISSUE THREAD

**Issue by dmilicic** [Raizlabs/DBFlow#356]
I get the issue using this code:

```java
@Table(databaseName = Database.NAME, allFields = true)
public class Activity extends BaseModel {

    @PrimaryKey(autoincrement = true)
    int id;

    Date date;

    int steps;

    double calories;
}
```

This is the exception:

```
android.database.sqlite.SQLiteException: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY (code 1): , while compiling: CREATE TABLE IF NOT EXISTS `Activity`(`id` INTEGER(0) PRIMARY KEY AUTOINCREMENT, `date` INTEGER(0), `steps` INTEGER(0), `calories` REAL(0));
```

I believe this is very similar to this issue: https://github.com/Raizlabs/DBFlow/issues/288

The `id` should probably be `INTEGER` instead of `INTEGER(0)` as in the issue above.

This code works **correctly** so I think it should be an issue with an `allFields` variable:

```java
@Table(databaseName = Database.NAME)
public class Activity extends BaseModel {

    @Column
    @PrimaryKey(autoincrement = true)
    int id;

    @Column
    Date date;

    @Column
    int steps;

    @Column
    double calories;
}
```

**Comment by mesterj** [comment]
I think this is not good idea to name your class Activity. And why don't use long id? This is the suggested way.

**Comment by dmilicic** [comment]
This was a demo app and I did use `id` as `long` but the same issue appeared, as in the issue I linked to. I forgot to point that out :)

**Comment by agrosner** [comment]
Been fixed in develop branch
