### ISSUE TITLE
Is this library discontinued? 

### ISSUE THREAD

**Issue by arturonaredo** [Raizlabs/DBFlow#360]
Hi,

Last commit was made for change the copyright. No more changes, no more pull request accepted, no more responses to issues... is the support to this library discontinued? 

I'd be sorry to hear that... 

Thank you @agrosner for your great work!

**Comment by mlebarron** [comment]
Please see https://github.com/Raizlabs/DBFlow/issues/351#issuecomment-130010110 and https://groups.google.com/forum/#!forum/dbflow

It's not being discontinued, we're in the process of determining how to move forward.
