### ISSUE TITLE
String like in Select

### ISSUE THREAD

**Issue by mesterj** [Raizlabs/DBFlow#362]
Hello

I have a problem.

I have two String in database:
ű and Ű
When I do a search with .like("%ű%") program can't find Ű
If i have p and P in the database 
like("%p%") found p and P correctly. 

Can you recommend a solution?

Joe

**Comment by kaeawc** [comment]
@mesterj As stated in [SQLite's documentation](http://www.sqlite.org/lang_expr.html#like): 
```
The LIKE operator does a pattern matching comparison. The operand to the right of the LIKE operator contains the pattern and the left hand operand contains the string to match against the pattern. A percent symbol ("%") in the LIKE pattern matches any sequence of zero or more characters in the string. An underscore ("_") in the LIKE pattern matches any single character in the string. Any other character matches itself or its lower/upper case equivalent (i.e. case-insensitive matching). (A bug: SQLite only understands upper/lower case for ASCII characters by default. The LIKE operator is case sensitive by default for unicode characters that are beyond the ASCII range. For example, the expression 'a' LIKE 'A' is TRUE but 'æ' LIKE 'Æ' is FALSE.)
```

You need to use ICU collation to write your SQL queries or add them to your tables. [Sqlite in Android is built with the ICU extension](http://developer.android.com/reference/java/util/Locale.html), however from reading the documentation around it and this [bug report for AOSP](https://code.google.com/p/android/issues/detail?id=9199) it seems unlikely to be working correctly on most devices.

**Comment by agrosner** [comment]
thanks for your help @kaeawc, closing this.
