### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by HectorFGarcia** [Raizlabs/DBFlow#363]
I´m having this exception when I launch my project and I don't know why.

java.lang.RuntimeException: Unable to create application com.xx.App: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder

I'm testing my project on two devices; one of them is running Android 5.1.1 and the other is running Android 4.0.3. Initially I started with the 4.0.3 device and all was ok, DBFlow worked. Same with the 5.1.1. But now, when I went back to the 4.0.3 I found this problem and I don't know what's going on because the code still works on 5.1.1

Why is working in one device but not in the other? What could have changed?

**Comment by HectorFGarcia** [comment]
Ok, I discovered the reason. It's caused by "multiDexEnabled true" in the build.gradle. Dalvik cache can't load the class if multiDex is on, but you don't have that problem on Lillipop because Lollipop doesn't use Davilk, uses ART.

I did this

http://developer.android.com/intl/es/tools/building/multidex.html

 to made multiDex compatible with Android ICS and now it's working again. You can close this.

**Comment by mlebarron** [comment]
Glad you figured it out @HectorFGarcia!
