### ISSUE TITLE
use Foreignkeys as Primarykeys

### ISSUE THREAD

**Issue by vIiRuS** [Raizlabs/DBFlow#364]
Hi,

I wanted to use two foreign keys as a composite primary key. The problem is, that during compile time I get the error that it can't find TASK and TAG (task and tag are the names of the fields). Looking at where the error happens, it tries to get the column names from TaskTag$Table.TASK and TaskTag$Table.TAG.

Does this not work or do I need to set anything additionally? I simply added the `@PimaryKey` annotation to the fields.

**Comment by agrosner** [comment]
Currently primary keys as foreign keys are not supported. It's more better design to leave them as foreign keys and use an Autoincrementing primary key instead. You can make them part of a `@UniqueGroup` I believe to enforce uniqueness.

**Comment by micHar** [comment]
@agrosner actually, you can't make them unique, it doesn't work. See this for reference: https://github.com/Raizlabs/DBFlow/issues/142

**Comment by agrosner** [comment]
fixed in develop, now primary key as foreign key works.
