### ISSUE TITLE
Inherited column as PrimaryKey

### ISSUE THREAD

**Issue by simernes** [Raizlabs/DBFlow#365]
To me it doesn't seem like it's possible to define inherited columns as PrimaryKey, since you no longer define it in the @Column annotation, but rather as a separate @PrimaryKey annotation, and the @InheritedColumn only takes two paramters (@Column, String) . Can you please correct me if I'm wrong, or implement.

**Comment by agrosner** [comment]
This could be added as a future feature in the next release. It wasn't implemented, since the complications around validation and column access.

**Comment by simernes** [comment]
Ok cool. I see you're not with RaizLabs anymore though, so I guess you won't be able to support the library as before? Hopefully it's not the end of DbFlow I mean since you pretty much were the only contributor.

**Comment by agrosner** [comment]
No, I am still going to be a maintainer going forward..now have full access again :). Won't be able to contribute meaningfully until this weekend however. I plan to fix most of the outstanding issues that need most attention, and then plan to release a major update in the near future. I will keep this going on the google groups chat here (https://groups.google.com/forum/?hl=en#!forum/dbflow)

**Comment by simernes** [comment]
All right man that's cool. You're a legend

**Comment by agrosner** [comment]
fixed in develop now. use the `@InheritedPrimaryKey` annotation!
