### ISSUE TITLE
Add documentation for save/insert

### ISSUE THREAD

**Issue by dantman** [Raizlabs/DBFlow#366]
I don't see any documentation on how to save and insert new model instances. Or any basic API documentation.

I ended up using `model.save()` and `model.insert()` but found that for some reason auto-increment on my primary key wasn't being handled (even though I never set the id) and models always shared the same id. So `.save()` replaced the one instance and `.insert()` threw and crashed the app.

**Comment by agrosner** [comment]
can you send me an example of your model class @dantman . Need more info. As for documentation, its slated for improvements in `3.0` by end of next month hopefully.

**Comment by dantman** [comment]
Adding `(autoincrement = true)` explicitly to the `@PrimaryKey` fixed that problem for me.

However because some other complications – primarily the fact that when I incremented VERSION and made some adjustments to my model DBFlow implicitly erased (or at least made completely inaccessible and not easily recoverable) the app data for that model – I've already dropped DBFlow and switched to a different storage library.
