### ISSUE TITLE
Primary Key inheritance

### ISSUE THREAD

**Issue by danPixel** [Raizlabs/DBFlow#367]
It appears to me that if you have a primary key column on a parent class, it doesn't show up to the validator. 

I have a base class I'm using for our models becausse they all need some basefields and logic. One of these is the primary key:

    public class TrellisModel extends BaseModel {

        @Column
        @PrimaryKey
        String id;

        @Column(name = "add_date")
        Date added;

        @Column(name = "modify_date")
        Date modified;

        @Column(name = "delete_date")
        Date deleted;
 
    .........

    }

however if a model derives from this it will complain that it has no primary key.

**Comment by agrosner** [comment]
@danPixel does the base class exist in same package?

**Comment by danPixel** [comment]
It didn't - it works when that is the case - I was separating them for organizational purposes considering I have about 70 tables.

**Comment by agrosner** [comment]
is it from another package? in develop, I added ability to access package private fields from other packages when you inherit from the class.
