### ISSUE TITLE
How to catch exceptions of 'TransactionManager'?

### ISSUE THREAD

**Issue by superyfwy** [Raizlabs/DBFlow#370]
@Table(databaseName = AppDatabase.NAME)
@ModelContainer
public class BModel extends BaseModel {

    @Column
    @PrimaryKey(autoincrement = true)
    Long id;

    @Column
    @NotNull
    String name;

    @Column
    String sex;

    @Column
    int age;

}

               List<BModel> modelList = new ArrayList<BModel>();
                for (int i = 0; i < 100; i++) {
                    BModel bModel = new BModel();
                    bModel.setName("name" + i);
                    if (i == 90) {
                        bModel.setName(null);
                    }
                    bModel.setAge(i + 1);
                    modelList.add(bModel);
                }
                try {
                    ProcessModelInfo<BModel> processModelInfo =
                            ProcessModelInfo.withModels(modelList)
                                    .result(new TransactionListener<List<BModel>>() {
                                        @Override
                                        public void onResultReceived(List<BModel> bModels) {
                                        }

                                        @Override
                                        public boolean onReady(BaseTransaction<List<BModel>> baseTransaction) {
                                            return false;
                                        }

                                        @Override
                                        public boolean hasResult(BaseTransaction<List<BModel>> baseTransaction, List<BModel> bModels) {
                                            return bModels != null && bModels.size() != 0;
                                        }
                                    }).info(DBTransactionInfo.create());

                    TransactionManager.getInstance()
                            .addTransaction(new SaveModelTransaction<>(processModelInfo));
                } catch (Exception ex){
                    Log.e("ERROR" , ex.getMessage());
                }

            }
        });

**Comment by agrosner** [comment]
@superyfwy you can extend `SaveModelTransaction` and do a try-catch in the `processModel()` method or whatever method you need to override.
