### ISSUE TITLE
Cannot resolve symbol RecordStub$Table

### ISSUE THREAD

**Issue by ratan12** [Raizlabs/DBFlow#372]
Hi,

Recently I found this library and tried to add this in my app but for some reason I got RecordStub$Table. I have implemented all the gradle things and the annotations are working fine.

I tried also implementing the ant and queen models to see if it still continue-ed and yes it did.

Any idea what could cause this?

**Comment by agrosner** [comment]
Do you have a `RecordStub` class with the `@Table` annotation? I'm not sure what the issue is here.

**Comment by ratan12** [comment]
@Table(databaseName = DatabaseTest.NAME, allFields = true)
Yes.

I tried a clean build with no success, if you would like it I could create a separate branch with my latest changes with the error that you could inspect.

**Comment by ratan12** [comment]
Okay I updated my JDK version and it was working fine then.
