### ISSUE TITLE
Column order with primary key

### ISSUE THREAD

**Issue by glureau** [Raizlabs/DBFlow#373]
I've just saw this code, I think there could be an issue here :

        // single primary key checking for a long or int valued column
        if (getPrimaryColumnDefinitions().size() == 1) {
            ColumnDefinition columnDefinition = getColumnDefinitions().get(0);
            if (columnDefinition.isPrimaryKey) {
                hasCachingId = !columnDefinition.hasTypeConverter;
            }
        }

I think it must be ColumnDefinition columnDefinition = getPrimaryColumnDefinitions().get(0); (and probably no need of the second "if")
Without this, it must fail if the primary key is not the first one in the file, isn't it ?

**Comment by agrosner** [comment]
fixed i ndevelop, 3.0
