### ISSUE TITLE
Is it possible to use OnSpecificModelStateChangedListener with a @PrimaryKey(autoincrement=true)? [Question]

### ISSUE THREAD

**Issue by glureau** [Raizlabs/DBFlow#378]
I have looked into the code, when the primary key has autoincrement=true it doesn't manage it as a cachingId, so the OnSpecificModelStateChangedListener is never called (due to the URI without id).
I'm asking why because I think it's pretty classic to have
> @PrimaryKey(autoincrement=true) long id;

Is there a good reason for blocking this? Some edge case that I don't see?

(In the meantime, I'm trying to update the processor on a fork to manage this.)

**Comment by glureau** [comment]
Please @agrosner I would have a simple go/no-go just to be sure I'm working on the good direction.

**Comment by agrosner** [comment]
sorry for long response. This should be fixed in 3.0/develop. Reopen if not.
