### ISSUE TITLE
How to delete all related documents in one-to-many relation

### ISSUE THREAD

**Issue by mkorszun** [Raizlabs/DBFlow#379]
I have followed this guide to setup `one-to-many` relation - https://github.com/Raizlabs/DBFlow/blob/master/usage/GettingStarted.md. I have only made small change in (since `setModel` did not work for me):

```
public void associateQueen(Queen queen) {
    queenModelContainer = new ForeignKeyContainer<>(Queen.class);
    Map<String, Object> keys = new LinkedHashMap<>();
    keys.put(Queen$Table.ID, queen.id);
    queenModelContainer.setData(keys);
}
```

It seems to be ok but whenever deleting "Queen" objects via:

`Delete().from(Queen.class).query();`

all related `Ants` remain in DB. How to delete them as well?

**Comment by Mervyn-Raizlabs** [comment]
@agrosner Could you please respond to this? Even I'm having this issue. I tried overriding delete() in Queen and manually deleting all associated Ants but they still seem to be present in the DB. I tried both `ant.delete()` and `TransactionManager.getInstance().addTransaction(new DeleteModelListTransaction<>(ProcessModelInfo.<Ant>withModels().models(getAnts())));` before and after Queen's super.delete() method. Any idea?

**Comment by agrosner** [comment]
try in 3.0/develop. it should be fixed.
