### ISSUE TITLE
Saving ForeignKeys by (long) ID instead of reference to model object

### ISSUE THREAD

**Issue by romulof** [Raizlabs/DBFlow#382]
Hi,

I'm receiving a large dump from server and I need to save lots of models in a transaction.
In your Colony example you make foreign key relations by passing the model object to `associateQueen` method.

Let's say I'm receiving in this dump lots of Queens and Ants. By the time I'm instancing an Ant model, I don't have the related Queen model object in hand, just the ID.

Is there a way to save a model with a ForeignKey giving only it's ID ?

**Comment by agrosner** [comment]
Yep it should be ```@ForeignKey(tableClass=Your table.class```

**Comment by romulof** [comment]
Like this?

```java
@Table(databaseName = ColonyDatabase.NAME)
public class Ant extends BaseModel {

  @Column
  @PrimaryKey(autoincrement = true)
  long id;

  @Column
  @ForeignKey(tableClass=Queen.class)
  long queenId;
}
```

**Comment by agrosner** [comment]
Yes, but you still need to add a @ForeignKeyReference. For 3.0 I hope to
have much better documentation on everything. It's just a work in progress

**Comment by romulof** [comment]
I just edited the snippet.

In my example above, the foreign key column name will the be one declared by `columnName` parameter or it'll be determined by `@Column` default (field name, in this case `queenId`) ?

**Comment by OptimistNot** [comment]
Thank u! Helped alot in my project. If u add @Column it'll use default, ur variable name. Remove it and it'll use columnName.
