### ISSUE TITLE
ForeignKeyAction.CASCADE vs OneToMany.Method.DELETE

### ISSUE THREAD

**Issue by romulof** [Raizlabs/DBFlow#383]
From your documentation enabling `OneToMany.Method.DELETE` will generate code to delete each element of the associated list when deleting the model, while `ForeignKeyAction.CASCADE` is an option to enforce SQLite to do this job.

If the OneToMany list isn't special (just get everything related), I assume they both do the same thing, right? In this case, should the later (CASCADE) be more efficient?

**Comment by agrosner** [comment]
yeah `CASCADE` is more efficient. apologies for super-late reply! ha.
