### ISSUE TITLE
How to get Queen of Ant? 

### ISSUE THREAD

**Issue by mesterj** [Raizlabs/DBFlow#384]
Hello

I can save ant with relation of Queen (the solution what is in readme is not works).
The correct answer is :

 public void associateQueen(Queen queen) {
    queenModelContainer = new ForeignKeyContainer<>(Queen.class);
    queenModelContainer.put(Queen$Table.ID,queen.getId());
  }

Now I would like to get back the Queen of ant.

I tried in Ant class:
public Queen getMyQueen() {
this.queenModelContainer = new ForeignKeyContainer<>(Queen.class);
return this.queenModelContainer.toModel();
}

But I got null. 
I tried many other things and I can't understand. Why it is so painfull? I just want get an Object!!

I really thinking of leave the whole DBFlow and start using SugarORM or something other ...

I found a solution which is not use ForeignKeyContainer, this is really simple . 
https://www.youtube.com/watch?v=1uBNhiwE9Tw

If you say it is correct way to create onetomany, than I will use this. 

Or need use ForeignKey PLEASE PLEASE create CORRECT associate and getForeignObject methods in Model class. I just want to use not hack this library...

You can see the whole ant and queen example: 
https://github.com/mesterj/DbFlowMain

Did you ever tried the demo ? I don't think so...

**Comment by agrosner** [comment]
fixed in 3.0.
