### ISSUE TITLE
Consider exposing list of Model classes publicly

### ISSUE THREAD

**Issue by danPixel** [Raizlabs/DBFlow#385]
I'm in a situation it would be great if I could access all the modelclasses associated with a given database. I see that this property exists on BaseDatabaseDefinition but I don't think theres any easy way to us to access it. Thanks!

**Comment by agrosner** [comment]
you can create a file  in the same package as `com.raizlabs.android.dbflow.config;`
```java

public class DatabaseExtensions {

  public static List<Class<? extends Model>> getModelClasses(BaseDatabaseDefinition bd) {
     return bd.getModelClasses();
  }

}
