### ISSUE TITLE
Adding @Column to @ForeignKey field stops $Table from being built

### ISSUE THREAD

**Issue by escproxy** [Raizlabs/DBFlow#387]
I'm working with foreign keys. When I follow the Queen-Colony-Ant example, I found that adding `@Column` to a `@ForeignKey` field breaks the generator for the `$Table` class. Removing the `@Column` means I get a null value when I run a query. But adding it means that `/app/build/generated/source/apt/debug/com/.../Ant$Table.java` becomes an empty file and I can no longer reference column names. Here's some example code:

    @Table(databaseName = Database.NAME)
    public class Ant
    extends BaseModel
    {
        @Column
        @PrimaryKey(autoincrement = true)
        public Long ANT_ID;

        @Column // Adding this
        @ForeignKey
        (
            references = {
                @ForeignKeyReference
                (
                    columnName = Job$Table.JOB_ID
                ,   columnType = Long.class
                ,   foreignColumnName = Job$Table.JOB_ID
                )
            }
        ,   saveForeignKeyModel = false
        )
        public Job JOB;

        // ... etc ...

        public Job getJob()
        {
            return JOB;
        }
    }

Additionally, I want to be able to call data from Job after querying the Ant table, like so:

    Ant ant = new Select().from(Ant.class).where(
        // I can no longer do this after adding @Column
        Condition.column(Ant$Table.ANT_ID).is(antId)
    ).querySingle();

    // How do I accomplish a task like this?
    Job job = ant.getJob();
    job.doSomethng()

I'm using DBFlow 2.2.1.

**Comment by kaeawc** [comment]
@escproxy What is the string value for `Job$Table.JOB_ID` ? I'm trying to reproduce your issue

**Comment by escproxy** [comment]
`Job$Table.JOB_ID` should return "`JOB_ID`" as defined by:

    @Table(databaseName = Database.NAME)
    public class Job
    extends BaseModel
    {
        @Column
        @PrimaryKey(autoincrement = true)
        public Long JOB_ID;

        // ... etc ...
    }

**Comment by kaeawc** [comment]
K, will try to reproduce

**Comment by agrosner** [comment]
try now in 3.0. Issues should be fixed. let me know.
