### ISSUE TITLE
Suggestion: `findById` static method on Model or ModelAdapter

### ISSUE THREAD

**Issue by romulof** [Raizlabs/DBFlow#388]
I tried to make on my BaseModel derived abstract class, but Java falls short here. I think the only way to make this helper is on those generated classes.

**Comment by kaeawc** [comment]
@romulof Couldn't you just create a static method on your model's class?

**Comment by romulof** [comment]
I leveled up my skill in Java and made it work without casting the result.

```java
public static <M extends BaseModel> M findById(Class<M> modelClass, Long id) {
    if (id == null)
        return null;

    return new Select().from(modelClass).byIds(id).querySingle();
}
```

But I still have to pass the target model class as parameter. Example:

```java
Bla x = Bla.findById(Bla.class, 10);
```

The ideal way would be like this:
```java
Bla x = Bla.findById(10);
```

As far as I know it's not possible to make a static method in the base class aware of derived class type, so the only way to make the desired way would be using generated code.

I'm really liking the way DBFlow works. I might later stop a while to study how APT works and make some contribution to the project.

**Comment by agrosner** [comment]
not going to be supported anymore. just call each column manually. thank you

**Comment by ssnake** [comment]
Hey,
I'd like to have such method as well. My implemntation:

```java
 public static <T extends BasicRecord> T findById(Class<T> T, final long id) {
        return  SQLite.select().from(T).where(new SQLCondition() {
            @Override
            public void appendConditionToQuery(QueryBuilder queryBuilder) {
                queryBuilder.append(columnName()).append(operation()).append(value());
            }

            @Override
            public String columnName() {
                return "id";
            }

            @Override
            public String separator() {
                return "";
            }

            @Override
            public SQLCondition separator(String separator) {
                return this;
            }

            @Override
            public boolean hasSeparator() {
                return false;
            }

            @Override
            public String operation() {
                return "=";
            }

            @Override
            public Object value() {
                return new Long(id);
            }
        }).querySingle();
    }
```
Then I use

```java
WordPair wp = WordPair.findById(WordPair.class, 1); //Method threw 'java.lang.NullPointerException' exception
```
However, in wp variable I have a record from db.
Why It throws exception and how to overcome this. Thanks
