### ISSUE TITLE
Select().from().count() always return 1

### ISSUE THREAD

**Issue by deltaguita** [Raizlabs/DBFlow#389]
Hi:

I went to count all instance in db,but this statement always return 1 
> new Select().from(Baby.class).count();
Is any Idea?

**Comment by agrosner** [comment]
Yes it's not well documented but you need to do:
```new Select().count().from(Baby.class).count()```. I will make this more clear in 3.0

**Comment by deltaguita** [comment]
@agrosner 
Thank you!
