### ISSUE TITLE
Default column name for FKs

### ISSUE THREAD

**Issue by OptimistNot** [Raizlabs/DBFlow#398]
Here's the deal, i have my fk with columnName defined in references, and also i have @Column definition that put name default as i can't define name in it...  so on update im getting SQLexception that default name (my variable name) does not exists in db as a field, and it make sense. But i want that field associated to db name...i can't even...any solution?
P.S. I update with update transaction using gson to convert data i receive.

**Comment by agrosner** [comment]
need more information. be helpful with sample code. This is a couple months old so close this if you had your question answered.

**Comment by OptimistNot** [comment]
i found solution using @SerializedName and some name tricks. But still you should add support for private foreign keys. At this moment i can't use private.
