### ISSUE TITLE
new Select().from().byIds() retuns always null

### ISSUE THREAD

**Issue by Informaticore** [Raizlabs/DBFlow#403]
Hey,

I try to get a List of entries by using the select where byIds() methode but it always returns null.
I tried it with the where eq id field and was getting an entry. I guess this is a bug.

This is the query:
````java
new Select().from(Some.class).byIds(ids).queryList()
````

If I call getQuery I get this: ````java SELECT * FROM `Car` WHERE `id`='[7245, 6039, 7027]' ````

I used a StringQuery like
````java
new StringQuery<>(Car.class, "SELECT * FROM 'Car' WHERE id IN (7245, 6039, 7027)").queryList()
````

and was getting all items. I guess this is a bug in 2.1.1

**Comment by agrosner** [comment]
method is removed in 3.0. Preferred method going forward is specifying keys such that:
```java
SQLite.select().from(Some.class).where(Car_Table.id.eq("[7245, 6039, 7027]").queryList();
``
