### ISSUE TITLE
Package private model classes are not visible to DbFlow.

### ISSUE THREAD

**Issue by ArazAbishov** [Raizlabs/DBFlow#406]
Documentation states that it is possible to create package private models:

"All model class definitions must be top-level (in their own file) and public or package private."

Here: https://github.com/Raizlabs/DBFlow/blob/master/usage/DBStructure.md

But the problem is that DbFlow does not recognise them stating that they have to be public.  Is it a documentation or library issue?

**Comment by agrosner** [comment]
Documentation issue. Should be all `public`. will adjust accordingly.
