### ISSUE TITLE
Support "isName()" getters instead of "getName()" for private booleans 

### ISSUE THREAD

**Issue by ajpolt** [Raizlabs/DBFlow#407]
Currently for private fields, the guide says to "specify a getName() and setName(columnType) for the field named name."

I'm sure I'm not the only one who uses the convention "isName()" instead of "getName()" in the case of accessors for booleans. IntelliJ/Android Studio uses it by default when using "Create Getter" or "Encapsulate Fields" for example.

I've recently found myself doing quite a bit of refactoring to accommodate DBFlow using getName() for booleans, and it would be really great if DBFlow supported isName() as well.

Thanks, and keep up the great work!

**Comment by kaeawc** [comment]
I've run into this as well, would enjoy being able to name things a bit better. `is_awesome` is different from `getAwesome` and leads to confusion. I would not want to think just because something is awesome that they could also get it.

**Comment by agrosner** [comment]
will be added in 3.0 as `useIsForPrivateBooleans()` in `@Table`

**Comment by kaeawc** [comment]
Awesome, thanks!

**Comment by ajpolt** [comment]
Thanks!

**Comment by agrosner** [comment]
in `develop`
