### ISSUE TITLE
Migrate new table

### ISSUE THREAD

**Issue by nambv** [Raizlabs/DBFlow#410]
Hi @graiz ,
I want to add new table in migration, how can I do it ?
Thank you so much!

**Comment by fabiendem** [comment]
Hey,
You just have to define your new table:
```
@Table(databaseName = MyDatabase.NAME)
public class MyTable {...}
```
and increase the database version number in the database definition
```
@Database(name = MyDatabase.NAME, version = MyDatabase.VERSION)
public class MyDatabase {
    public static final String NAME = "your_database_name";
    public static final int VERSION = 6; // Here increase the number (for me it's 6...)
}
```

DBFlow should handle the creation for you the next time your run a request.

**Comment by nambv** [comment]
@fabiendem It's work! thanks a lot!!!

**Comment by ervinsae** [comment]
it is worked

**Comment by ervinsae** [comment]
what about this:https://github.com/Raizlabs/DBFlow/issues/324

**Comment by voghDev** [comment]
Important to remark the "increase database version" thing. I spent some minutes wondering why my table wasn't being created, and it was that.
