### ISSUE TITLE
Problem setting up dbflow as module dependency

### ISSUE THREAD

**Issue by gauravsapiens** [Raizlabs/DBFlow#413]
I'm trying to use DbFlow with SqlCipher. For that I need to make modifications in DbFlow, substituting instances of SqliteDatabase with the one in SqlCipher. 

Therefore, I'm including DBFlow, DBFlow-Compiler, DBFlow-Core as 3 separate modules in my project and wrapping them up in the same way as the sample. However, I'm getting this error: 

```Cause: org/gradle/api/publication/maven/internal/DefaultMavenFactory```

I've tried a lot but I can't get through this. Any help would be appreciated.
Also, is there a better approach to solving my problem apart from the one I'm trying.

PS: I suck at gradle !

**Comment by agrosner** [comment]
can you send the full stacktrace please? I do not understand the error message.

**Comment by agrosner** [comment]
closed as no response and 3.0.0 came out after this.
