### ISSUE TITLE
Recursive relationship

### ISSUE THREAD

**Issue by darkwizz** [Raizlabs/DBFlow#414]
Good day,
can I implement recursive 1-M relationship?
thanks

**Comment by agrosner** [comment]
Recursive relationship is not really supported. Can you send a example of what you're trying to achieve? Thank you.

**Comment by darkwizz** [comment]
oh, thanks, I've already fixed it, I've added reference as a simple field and marked it as a foreign key

**Comment by darkwizz** [comment]
there is another problem. I have a class that references on two another, both those classes reference on other class, which has a reference to first. When I try to load some object, then it'll be StackOverflowError. How can I keep such relationships in another way?

**Comment by agrosner** [comment]
@darkwizz try using a `ForeignKeyContainer` instead for the relationships.
