### ISSUE TITLE
Bug with statement Update cause of argument Class

### ISSUE THREAD

**Issue by machei** [Raizlabs/DBFlow#416]
Java:
```
import com.raizlabs.android.dbflow.sql.language.Update;

[...]

Where update = new Update().table(UserAccount.class)
	.set(Condition.column(UserAccount$Table.MODE_SYNC).eq(user.mode_sync))
	.where(Condition.column(UserAccount$Table._ID).is(user.getUserID()));
update.queryClose();
```
Error:
```
Error:(314, 28) error: constructor Update in class Update<ModelClass> cannot be applied to given types;
required: Class
found: no arguments
reason: actual and formal argument lists differ in length
where ModelClass is a type-variable:
ModelClass extends Model declared in class Update
```

![screenshot_4](https://cloud.githubusercontent.com/assets/7736131/10296931/a4a9c5a8-6bcd-11e5-900d-c765aa2e5d9f.png)

DBFlow - version: 2.2.1

**Comment by machei** [comment]
Worked after replacing java version from 1.6 to 1.7

Correctly here, but documentation seems a bit older than before...
```
Where update = new Update<>(UserAccount.class).set().where();
```

Gradle:
```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
```

**Comment by agrosner** [comment]
@machei , correct. the `Update` class changed to enforce the constructor _or_ the `Update.table()`  static method.

**Comment by diickens** [comment]
Took this from the official Documentation
´´´Java
TransactionManager.getInstance().addTransaction(new UpdateTransaction<>(DBTransactionInfo.create(BaseTransaction.PRIORITY_UI), update);
´´´
and got this error:

Error:(100, 57) Gradle: error: cannot infer type arguments for UpdateTransaction<>

**Comment by mathieudebrito** [comment]
+1
