### ISSUE TITLE
What is the right way to handle a " Logout " in app?

### ISSUE THREAD

**Issue by mori-honest** [Raizlabs/DBFlow#417]
This is my code that does the logout:

    
    public void clearApplicationData() {
        // Delete shared prefs
        UserProvider.getInstance(this).deleteAllUserData();

        File cache = getCacheDir();
        File appDir = new File(cache.getParent());
        if (appDir.exists()) {
            String[] children = appDir.list();
            for (String s : children) {
                if (!s.equals("lib")) {
                    deleteDir(new File(appDir, s));
                }
            }
        }
    }

    public void logout() {
        deleteDatabase(Database.NAME);
        FlowManager.getDatabase(Database.NAME).reset(this);

        clearApplicationData();
        FlowManager.init(this);
        restartApp();
    }

    public void restartApp() {
        Intent i = getBaseContext().getPackageManager()
                .getLaunchIntentForPackage(getBaseContext().getPackageName());
        i.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
        i.putExtra("restart", true);
        startActivity(i);
    }

But no transaction is done after login and no item is saved in database so no item is loaded **UNTIL** user closes the app and opens again.
How can i fix this?

**Comment by andrecrispim** [comment]
For me calling FlowManager.reset database and FlowManager,init don't worked, 
I used that (not so pretty) **workaround**:

* Create a helper to Keep the database instance
* Close the database before deleting it
* Don't call the FlowManager.init in that case

	public class SqlOpenHelper extends FlowSQLiteOpenHelper {
	
	    private volatile static SqlOpenHelper helper;
	    private static SQLiteDatabase database;
	
	    /**
	     * Closes the database
	     */
	    public static void closeDatabase() {
	        if (helper != null) {
	            helper.close();
	        }
	    }
	
	    /**
	     * Constructor
	     *
	     * @param flowManager FlowManager
	     * @param listener Listener
	     */
	    public SqlOpenHelper(BaseDatabaseDefinition flowManager, DatabaseHelperListener listener) {
	        super(flowManager, listener);
	        helper = this;
	    }
		
	    @Override
	    public void onOpen(SQLiteDatabase db) {
	        database = db;
	        super.onOpen(db);
	    }
	
	    @Override
	    public SQLiteDatabase getWritableDatabase() {
	        if (database == null || !database.isOpen()) {
	            database = super.getWritableDatabase();
	        }
	
	        return database;
	    }
	}

**Comment by mstedler** [comment]
look at #253

**Comment by mori-honest** [comment]
Any Update in this bug? I need this for my app release :(

**Comment by agrosner** [comment]
have you upgraded to at least 3.0.0-beta1?

**Comment by mori-honest** [comment]
No, 
we have tested our app and the only major bug is this one. I am in the rush of release and i don't want any unexpected behaviour.
what do you suggest?

**Comment by agrosner** [comment]
If this isn't fixed in 3.0.0-beta5+ please reopen.

**Comment by MahdiPishguy** [comment]
i have this problem in current  version of this library

**Comment by felipezf** [comment]
@agrosner This is not working on version 4.1.2. The behavior is inconsistent.

**Comment by ka05** [comment]
@agrosner This still appears to be an issue in 4.2.4
