### ISSUE TITLE
API to reset the autoincrement counter for a table?

### ISSUE THREAD

**Issue by clo-dan** [Raizlabs/DBFlow#418]
Occasionally we need to empty a table and reset its autoincrement counter to 0. Does DBFlow provide an API to do this or will we need to turn to a raw query?

**Comment by agrosner** [comment]
You do this..http://stackoverflow.com/a/1601854

**Comment by agrosner** [comment]
You will need to provide a raw query for this after deleting the table:
```sqlite
delete from sqlite_sequence where name='your_table';
```
