### ISSUE TITLE
Migration AlterTable Add new column not work?

### ISSUE THREAD

**Issue by nambv** [Raizlabs/DBFlow#419]
Hi @graiz , I have a table

```
@Table(databaseName = MyDatabase.NAME)
@ModelContainer
public class Lead extends BaseModel {

    @Column
    @PrimaryKey
    @Expose
    String objectId;

    @Column
    @Expose
    String name;
}
```

Now I want to add new column into this table, I do following step:
1. Add new column into Lead.class

```
@Table(databaseName = MyDatabase.NAME)
@ModelContainer
public class Lead extends BaseModel {

    @Column
    @PrimaryKey
    @Expose
    String objectId;

    @Column
    @Expose
    String name;

    @Column
    @Expose
    String otherInfos;
}
```
2. Create Migration:

```
@Migration(version = 4, databaseName = MyDatabase.NAME)
public class Migration1 extends AlterTableMigration<Lead> {

    public Migration1() {
        super(Lead.class);
    }

    public Migration1(Class<Lead> table) {
        super(table);
    }

    @Override
    public void onPreMigrate() {
        super.onPreMigrate();
        addColumn(String,class, Lead$Table.OTHERINFOS);
    }
}
```

but It returns error:

```
android.database.sqlite.SQLiteException: no such column: otherInfos (code 1):
```

Can you help me to solve this?

Thanks a lot!!

**Comment by fabiendem** [comment]
Have you increased the DB version number also?

And try:
```
 @Override
    public void onPreMigrate() {
        super.onPreMigrate();
        addColumn(String,class, "otherInfos");
    }
```

**Comment by nambv** [comment]
@fabiendem OK I will test it right now :D thanks for your comment!

**Comment by nambv** [comment]
Wow, @fabiendem It worked! thanks a lot @fabiendem !!!

**Comment by voghDev** [comment]
I was having a stupid mistake that made me waste hours. I just want you guys to know, to avoid someone from doing the same. The error I was getting is:

Process: com.company.app.flavor, PID: 6381
    java.lang.RuntimeException: java.lang.NullPointerException
            at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:75)
     Caused by: java.lang.NullPointerException

The reason: I was passing an unassigned String to addColumn. Imagine this:

    public static final String STR;

    @Override
    public void onPreMigrate() {
        super.onPreMigrate();

        addColumn(String,class, STR);
    }

I know it's a dumb issue, but I wasted several hours finding it. Maybe it helps someone else.

**Comment by narimetisaigopi** [comment]
remove 

public Migration1() {
        super(Lead.class);
    }
one constructor is  enough if not it gives an error

2.
incremnet your database version number and 
use version = Mydatabase.VERSION;
