### ISSUE TITLE
Load overriding

### ISSUE THREAD

**Issue by darkwizz** [Raizlabs/DBFlow#420]
hello, in simple BaseModel child class I can override save, update, delete and insert. How can I override load method?

**Comment by darkwizz** [comment]
I have a parent with two children and another class that stores reference on one from children. But when I try to add a non-null value for foreign key in another class I always receive foreign key constraint error (code 19)

**Comment by agrosner** [comment]
if you're receiving foreign key constraint errors, then you need to ensure that the parent objects exist and you're following proper foreign key procedure. There is no `load()` method in the `Model` class.
