### ISSUE TITLE
How to log SQL statements?

### ISSUE THREAD

**Issue by Tyderion** [Raizlabs/DBFlow#422]
Hi there,

Is it possible to log all executed SQL Statements?

My queries do not do what I expect them to do but I do not get how to debug the statements.

Thanks for helping me,
Tyd

**Comment by agrosner** [comment]
Ensure that the `FlowLog` is set to minimum of `FlowLog.Level.V` via `FlowLog.setMinimumLoggingLevel(FlowLog.Level.V);`

**Comment by agrosner** [comment]
The line of code you're looking for is in `Where.java` at `getQuery()`

**Comment by Tyderion** [comment]
wow that was fast, thanks a lot :+1:

**Comment by zmorris** [comment]
If someone needs to also log `insert` and `update`, please see my attempts at https://github.com/Raizlabs/DBFlow/issues/607#issuecomment-360009079
