### ISSUE TITLE
Big problem with a new database and first structure creation

### ISSUE THREAD

**Issue by carmas123** [Raizlabs/DBFlow#427]
I've in my application an assets with migration/1.sql file that contain my first database sql script to create all table. So the problem is that this script is not run if the database does not exist!!
No script is executed if the database does not exist.

The
executeMigrations(db, -1, db.getVersion());
in 
OnCreate(SQLiteDatabase db) method

execute always a migration from 0 to 0.

What am I doing wrong?

**Comment by carmas123** [comment]
The method

                @Override
                public void onCreate(SQLiteDatabase db) {
                    checkForeignKeySupport(db);
                    executeCreations(db);
                    executeMigrations(db, -1, db.getVersion());
                }

need to be changed like this

                @Override
                public void onCreate(SQLiteDatabase db) {
                    checkForeignKeySupport(db);
                    executeCreations(db);
                    executeMigrations(db, -1, databaseDefinition.getDatabaseVersion());   <--- THIS IS THE CURRENT VERSION
                }

With this we can create and upgrade database from 0 to current also when it does not exist.

**Comment by grennis** [comment]
> I've in my application an assets with migration/1.sql file that contain my first database sql script to create all table

You should not write a script like that. DBFlow will automatically create all tables that do not exist for all your @Table classes. So, no migrations should run when the database is created, since it is already by definition in its current state.

**Comment by agrosner** [comment]
yes thats not the purpose of migrations @carmas123. Its to get existing databases up-to-date with newly created DB. It automatically creates all DB tables for you based on your schema. you should not use migrations for that

**Comment by relevante** [comment]
That makes sense, but for some reason indexes weren't getting created by the creation process unless I executed a migration to explicitly create them, which is why I searched for and found this issue/resolution. I'm using the reference in an indexedBy call so I think my annotations are set up correctly.

**Comment by zmorris** [comment]
I opened an issue https://github.com/Raizlabs/DBFlow/issues/1415 detailing how DBFlow's creation vs migration metaphor differs from [other migration strategies used by frameworks like Laravel](https://laravel.com/docs/migrations).
