### ISSUE TITLE
working example with SQLCipher

### ISSUE THREAD

**Issue by noinnion** [Raizlabs/DBFlow#432]
Hi,

does anyone have a working example of DBFlow + SqlCipher?
I tried to create a custom FlowSQLiteOpenHelper but I have not idea how to use it with SqlCipher.

Any help would be appreciated. 

Thanks

**Comment by noinnion** [comment]
It seems that you need to replace all android.database.sqlite.* with net.sqlcipher.database.*.
Could it be done with FlowSQLiteOpenHelper?

If not, could I just clone the project and replace all imports?

**Comment by agrosner** [comment]
@noinnion I haven't really looked at the implementation, but since many people are calling for it, it will be on my radar.

**Comment by sevar83** [comment]
@agrosner Please, please, please, add a DB abstraction similar to that in GreenDAO's "DbAbstraction" branch. Take a look:
https://github.com/greenrobot/greenDAO/blob/DbAbstraction/DaoCore/src/de/greenrobot/dao/database/Database.java
https://github.com/greenrobot/greenDAO/blob/DbAbstraction/DaoCore/src/de/greenrobot/dao/database/AndroidSQLiteDatabase.java

With this aproach, both SQLCipher and Spatialite can be used with DBFlow very easily.

**Comment by agrosner** [comment]
done. in `develop`

**Comment by gnuhel** [comment]
@agrosner Thanks for adding the example
Could you tell me how it exactly works?
