### ISSUE TITLE
duplicate class GeneratedDatabaseHolder error

### ISSUE THREAD

**Issue by notice501** [Raizlabs/DBFlow#433]
I have several modules which  every one want to create a database,but it can not be done, because every module will generate a GeneratedDatabaseHolder that cause duplicate entry error.

**Comment by elsennov** [comment]
Has it been solved? I face the same issue today. Thanks

**Comment by notice501** [comment]
https://github.com/Raizlabs/DBFlow/blob/master/usage/DatabaseModules.md

**Comment by elsennov** [comment]
@notice501 Thanks.
Where should i put the apt configuration? is it inside android {} ?
Also, i cannot find FlowManager.initModule.

**Comment by notice501** [comment]
@elsennov 
No, put apt in `dependencies`.
`FlowManager` is not in source code, but generated after the apt's annotation process.
Btw,I wrote an `orm` lib by myself, because DBFlow didn't support multiple Instances of modules that time.
So,I'm not  familiar with DBFlow neither. You can open a new  issue.

**Comment by elsennov** [comment]
i mean this apt:
```
apt {
    arguments {
        targetModuleName 'Test'
    }
}
```

**Comment by notice501** [comment]
```
android {
....
}


apt {
    arguments {
        targetModuleName 'your module name'
    }
}
```

[apt](https://bitbucket.org/hvisser/android-apt)

**Comment by elsennov** [comment]
Thanks
