### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by sevar83** [Raizlabs/DBFlow#434]
@agrosner @graiz 
Hey, is this project still alive? It passed 2 months since the last commit. It would be a shame such a beautiful library to die like this! I even had a plans to integrate it with SpatialiteDB making it a first class GIS ORM for Android!

**Comment by agrosner** [comment]
Hey,
Yes it is. It's alive and well. I'm just putting the finishing touches on
3.0,which is a massive update to the library. All that is left is
documentation and some more testing and it'll be released to the wild!
Thanks for the concern. If you want a preview, check out the 3.0 branch.

**Comment by sevar83** [comment]
Glad to hear that mate! Keep up the good work!

**Comment by agrosner** [comment]
thanks for the concern man. I have been a lot busier than I would have liked of late, so my time has been pressed, but that should change very soon and great things will come :)

**Comment by youdonotexist** [comment]
Is the 3.0 branch somewhere up on maven / a Gradle compatible repo? Or is the common approach to pull down the code and build locally?

**Comment by agrosner** [comment]
Its only on a separate branch for now. I also need to fix maven
configuration, since it's been broken. Best thing to do is pull it down as
a submodule and check it out. as always with unstable, non-final releases,
future commits may break or erase new features in this branch. so best bet
is to fork the branch and merge in changes until final release.

**Comment by sevar83** [comment]
Not 100% sure but I think it can be be imported without Maven but with the
new and cool JitPack.io which emulates maven artifact from a GitHub repo.
With it you can include any github tag or commit as a maven dependency.
Like this:

Add it in your build.gradle at the end of repositories:

 repositories {
        // ...
        maven { url "https://jitpack.io" }
    }

Step 2. Add the dependency in the form

	dependencies {
	        compile 'com.github.Raizlabs:DBFlow:319585975b'
	}

**Comment by jacktech24** [comment]
@agrosner  Do you have an ETA for the release?

**Comment by mikacl** [comment]
@agrosner The 3.0 version will be compatible with Gradle 2.8?. The 2.2.1 version only works with Gradle 2.4.
