### ISSUE TITLE
SQLiteDoneException when doing select().count() on empty table

### ISSUE THREAD

**Issue by kenkyee** [Raizlabs/DBFlow#436]
long numpoints = new Select().from(ResponsePointData.class).count();

I expected that to do
  SELECT COUNT(*) FROM ResponsePointData

should probably just return 0 instead of throwing an error...

**Comment by agrosner** [comment]
@kenkyee how did you get to that error?

**Comment by agrosner** [comment]
I'd prefer making it configurable to turn on and off errors, since hiding errors completely may hide the real problem there.

**Comment by kenkyee** [comment]
Sorry for the slow reply...I'm up in Toronto for a relative's wedding so not really at work :-)

Anyways, I got to the error doing a simple CRUD unit test on a table.
It's pretty simple...I replaced the line above w/ the count check at the end.
There should be no reason it should throw an error.  Doing SELECT COUNT(*) on a table should always return one value.

[quote]
    public void testCRUD()
    {
        // purge table
        new Delete().from(ResponsePointData.class).query();

        ResponsePointData point = new ResponsePointData();
        point.setId("1");
        point.setHits(5);
        point.setCapturedValueTotal(5.5f);
        point.save();

        List<ResponsePointData> points = new Select().from(ResponsePointData.class).queryList();
        assertThat(points).hasSize(1);

        ResponsePointData datapoint = new Select().from(ResponsePointData.class).querySingle();
        assertThat(datapoint.getId()).isEqualTo("1");
        assertThat(datapoint.getHits()).isEqualTo(5);
        assertThat(datapoint.getCapturedValueTotal()).isCloseTo(5.5d, within(0.0001d));
        assertThat(datapoint.getAvgCapturedValue()).isCloseTo(1.1d, within(0.0001d));

        point.setCapturedValueTotal(10.10f);
        point.setHits(2);
        point.save();
        ResponsePointData updatedDatapoint = new Select().from(ResponsePointData.class).querySingle();
        assertThat(updatedDatapoint.getId()).isEqualTo("1");
        assertThat(updatedDatapoint.getHits()).isEqualTo(2);
        assertThat(updatedDatapoint.getCapturedValueTotal()).isCloseTo(10.10d, within(0.0001d));
        assertThat(updatedDatapoint.getAvgCapturedValue()).isCloseTo(5.05d, within(0.0001d));

        new Delete().from(ResponsePointData.class).where(column(ResponsePointData$Table.ID).is("1")).query();
        List<ResponsePointData> remainingPoints = new Select().from(ResponsePointData.class).queryList();
        assertThat(remainingPoints).hasSize(0);
    }

**Comment by kenkyee** [comment]
Ahhh...I see the bug.
In dbflow/sql/language/Where.java::count(), it's handling this case totally wrong.
The query being used is:
  SELECT * FROM `ResponsePointData` 

This will return no rows if there's nothing there and is also horridly inefficient if there are lots of rows.
It should be using the COUNT(*) query I mentioned above.
I don't understand how the DBFlow pieces work together so I'm not sure how to fix this or I'd put in a PR...only thing I can suggest that's probably hackish is to replace the query string that starts with "SELECT *" with "SELECT COUNT(*)" in that count() method :-)

**Comment by agrosner** [comment]
oooo now I see it. 
```java
new Select().from(ResponsePointData.class).count()
```
should be:
```java
new Select().count().from(ResponsePointData.class).count()
```

In 3.0 this query is a little more straightforward:
```
new Select(Method.count()).from(ResponsePointData.class).count();
```

so `Method.count()` is an actual method of `COUNT(*)`

**Comment by kenkyee** [comment]
Ahhhh...that makes sense.
I was going through the docs and this wasn't obvious.  Almost like there should be a "common SQL queries and how to translate them to DBFlow" page.
But still...I don't think it should throw an exception in the case above...should return 0.
Thanks for looking into it this late :-)

**Comment by agrosner** [comment]
You're welcome. I'll look into the exception to see if its the fault of the library for the exception.

**Comment by agrosner** [comment]
Added a `SQLite.selectCountOf()` method to make it easier/more clear.
