### ISSUE TITLE
ContentProvider support for Sync-Adapter implementation

### ISSUE THREAD

**Issue by ivangag** [Raizlabs/DBFlow#44]
Hi,
i just found out this library and it promises to do many thing in a powerful way.
BUT I'm worry about whether the DBFlow enables easily the use of Sync-Adapter, as you know the Sync-Adpater requires a stub ContentProvider implementation, and in fact i nicely have been using another ORM (ActiveAndroid) and it makes that easily.
How would DBFlow aim to do that (if do)?
Thanks in advance.

**Comment by Rainer-Lang** [comment]
I'm also very interested.

**Comment by agrosner** [comment]
@ivangag I am not familiar with ```SyncAdapter```. I am familiar with AA so are you talking about the ```ContentProvider``` that it uses to notify that ```Model``` has been saved or changed? 

In [Model](https://github.com/pardom/ActiveAndroid/blob/master/src/com/activeandroid/Model.java) line 161:

```java
Cache.getContext().getContentResolver()
				.notifyChange(ContentProvider.createUri(mTableInfo.getType(), mId), null);
```

**Comment by ivangag** [comment]
Exactly. 
The SyncAdapter to work needs of a ContentProvider (stub) implementation and then declared in the Manifest and in the AA case is here https://github.com/pardom/ActiveAndroid/blob/master/src/com/activeandroid/content/ContentProvider.java
In the manifest i do something like this 
 <provider
            android:name="com.activeandroid.content.ContentProvider"
            android:authorities="org.example.myapp"
            android:exported="false" />
As you can see AA defines a CP a allows me to declare in the manifest.
Also see here http://developer.android.com/training/sync-adapters/creating-stub-provider.html fo SyncAdapter requirement.

Thanks.

**Comment by ivangag** [comment]
Just another thing...to be more complete.
A CP "concrete" implementation is not "strictly" necessary to SyncAdapter to work as SyncAdapter framework wants just a "stub" authority to validate it. 
The CP (in general) could be something like this..

```
public class DummyProvider extends ContentProvider {

    @Override
    public int delete(Uri uri, String selection, String[] selectionArgs) {
         return 0;
    }
    @Override
    public String getType(Uri uri) {
        return null;
    }
    @Override
    public Uri insert(Uri uri, ContentValues values) {
        return null;
    }
    @Override
    public boolean onCreate() {
        return false;
    }
    @Override
    public Cursor query(Uri uri, String[] projection, String selection,
                    String[] selectionArgs, String sortOrder) {
        return null;
    }
    @Override
    public int update(Uri uri, ContentValues values, String selection,
                    String[] selectionArgs) {
        return 0;
    }}

}
```

Howewer a CP concrete implementation in DBFlow (as AA does) can be very usefuel when you use Cursor and Loaders, in particular see the method [ContentProvider.createUri()] (https://github.com/pardom/ActiveAndroid/blob/master/src/com/activeandroid/content/ContentProvider.java), it helps your code when you would instantiate new CursorLoader, for instance you can do something like this:

```
    public Loader<Cursor> onCreateLoader(int id, Bundle args) {

        return new CursorLoader(getActivity(),
                ContentProvider.createUri(MyDummyClass.class, null),
                ActiveContract.CHECK_IN_TABLE_PROJECTION, mSelectionQuery, null,
                ActiveContract.CHECKIN_COLUMNS.ISSUE_TIME + " asc"
        );
    }
```

**Comment by agrosner** [comment]
@ivangag ok I will consider it at some point in the next couple weeks for it. I see it as part of a 1.5.x or 1.6.x release. It does not seem to bad, I will just need to figure out how to test it on my end to ensure it works as expected.

**Comment by ivangag** [comment]
@agrosner great.  
Thanks for considering..

**Comment by jiqimaogou** [comment]
wish you for release content provider suppor,t.

**Comment by agrosner** [comment]
check out the ```feature/agrosner/ContentProviderGenerator``` branch. Its similar to https://github.com/SimonVT/schematic. Not warranty here as its still in alpha phase, but should make it in the 1.6.0 release early next week or so.

**Comment by agrosner** [comment]
1.6.0 is now out

**Comment by ivangag** [comment]
Great! Thanks! I'll try for sure ASAP
