### ISSUE TITLE
Is there a way to do begin/end transactions?

### ISSUE THREAD

**Issue by andrewpmoore** [Raizlabs/DBFlow#442]
I've read the documents on transactions and we are currently migrating from ActiveAndroid over to dbflow.

The app  so far works well but currently I've not batched the saves into transactions to make them faster.
With ActiveAndroid when parsing some quite large json streams we'd begin a transaction, do a number of saves along the way into many model objects and then end a transaction when they were completed.

The layout being like this
```java
     controlling_block
         beginTransaction
                   parseJson 
                          parseJsonBlock1 (and save the model data e.g. Model1.save())
                          parseJsonBlock2 (and save the model data e.g. Model2.save())
                               parseJsonBlock2a (and save the model data  e.g. Model2a.save())
                          ....
                          parseJsonBlock10 (and save the model data  e.g. Model10.save())
         endTransaction
```

As the saves are spread across many objects beginning and ending the transaction at the top level was fairly simple.

If I was to use:

```java
    TransactionManager.getInstance().addTransaction(new SaveModelTransaction<>(ProcessModelInfo.withModels(models)));
```

would I need to build up a big collection of all the models to save to pass it through to the controlling_block or is there a simpler way to achieve this?

Just looking for suggestions which would also probably help out others too.

**Comment by agrosner** [comment]
yes. just call:
```java
    new SaveModelTransaction<>(ProcessModelInfo.withModels(models)).onExecute();

    // or
    ProcessModel.process(MyTable, models, new ProcessModel() {...});

   // or
   TransactionManager.transact(MyDatabase.NAME, new Runnable(){..});
```

**Comment by rhespanhol** [comment]
I think i have the same problem than you. I need to sync save several models in bulk but using transactions is faster. What i did was create an arraylist<BaseModel> with all models i need to save and added that transaction:
private ArrayList<BaseModel> mModels = new ArrayList<>();
mModels.addAll(mModel1);
mModels.addAll(mModel2);
TransactionManager.getInstance().addTransaction(new UpdateModelListTransaction<>(ProcessModelInfo.withModels(mModels).result(onModelsInserted)));

I dont know if this is the best way, but is better than have several listeners for all models that i need to insert and sync all that way.

**Comment by re3lex** [comment]
@rhespanhol you can do it in this way:


        SQLiteDatabase database = FlowManager.getDatabase(ColonyDatabase.NAME).getWritableDatabase();
        database.beginTransaction();
        Queen queen = new Queen();
        queen.setId(System.currentTimeMillis());
        queen.setName("should not be saved");
        queen.save();

        database.endTransaction();

        database.beginTransaction();
        queen = new Queen();
        queen.setId(System.currentTimeMillis());
        queen.setName("should be saved");
        queen.save();
        database.setTransactionSuccessful();
        database.endTransaction();

**Comment by thekalinga** [comment]
@re3lex 

Where does the save method on Queen comes from?
