### ISSUE TITLE
Model$Table doesn't generate the columns when allFields = true

### ISSUE THREAD

**Issue by yiyangest** [Raizlabs/DBFlow#443]
Hi, I'm using DBFlow 2.2.1, and I have a model like

    @Table(databaseName=DemoDB.NAME, allFields = true)
     public class UserModel extends BaseModel {
         @PrimaryKey
         private String userId

         private String userName;
         
         public void setUserId(String userId){this.userId = userId;}
         public void getUserId() {return this.userId};

         //....userName getter and setter

     }

and the DBFlow-Compiler generated userModel$Table class only contains userId

    public final class UserModel$Table {

        public static final String TABLE_NAME = "UserModel";

        public static final String USERID = "userId";

    }

I thought allFields should take all fields as column, so what happend? did I miss something?

**Comment by andrecrispim** [comment]
Looks like they don't changed allFields to use get/set:

		/**
		 * @return When true, all public, package-private , non-static, and non-final fields of the reference class are considered as {@link com.raizlabs.android.dbflow.annotation.Column} .
		 * The only required annotated field becomes The {@link com.raizlabs.android.dbflow.annotation.PrimaryKey}
		 * or {@link PrimaryKey#autoincrement()}.
		 */
		boolean allFields() default false;

Then, they can't be private, I think.

**Comment by agrosner** [comment]
try this on the develop branch please. 3.0 has many new updates and changes. Reopen if after updating to 3.0, it resolves itself.

**Comment by yiyangest** [comment]
Great! Thanks.
