### ISSUE TITLE
Inheritance conflicts with allFields

### ISSUE THREAD

**Issue by bryant1410** [Raizlabs/DBFlow#444]
For example, if we have this classes from the tests, but using `allFields`, it doesn't work:

```java
@Table(databaseName = TestDatabase.NAME)
@ModelContainer
public class TestModel2 extends TestModel1 {
    @Column(name = "model_order")
    int order;
}
```

```java
@Table(databaseName = TestDatabase.NAME, allFields = true)
@ModelContainer
public class TestModel1 extends BaseModel {
    @PrimaryKey
    String name;
}
```

It will say that `TestModel2` has no primary key.

This is because the annotator processor tool checks only for the presence of `allFields` in the subclass: https://github.com/Raizlabs/DBFlow/blob/master/DBFlow-Compiler/src/main/java/com/raizlabs/android/dbflow/processor/definition/TableDefinition.java#L192

**Comment by agrosner** [comment]
for 3.0 in `develop`, I cannot repro this issue. Its only checking current table's modifier. so if the subclass requires allFields, then this table will need to also specify that to keep the same behavior.

**Comment by bryant1410** [comment]
No, the thing is different. The `allFields` is in the superclass (`TestModel1`) and not in the subclass (`TestModel2`). So when trying to process the subclass, it will fail because it doesn't have the `allFields` and also `name` is not annotated with `@Column`: https://github.com/Raizlabs/DBFlow/blob/develop/dbflow-processor/src/main/java/com/raizlabs/android/dbflow/processor/definition/TableDefinition.java#L245
