### ISSUE TITLE
One to Many relatioship

### ISSUE THREAD

**Issue by marinovskiy** [Raizlabs/DBFlow#446]
Hi everybody. I don't understand how to use one to many relationship in DBFlow. Could anybody explain me, how? I have read this: https://github.com/Raizlabs/DBFlow/blob/master/usage/GettingStarted.md but have not understand what is ModelContainer and where from this variable QUEENFOREIGNKEYCONTAINER_QUEEN_ID

**Comment by andrecrispim** [comment]
The ForeignKeyContainer is used to lazy load a model: when you get a Ant you will only have the queen's identifier (queenModelContainer.getValue("id")), to really query the queen you can call the method queenModelContainer.getModel().

Explaning a little :

  @Column
  @ForeignKey(
    references = {@ForeignKeyReference(columnName = "queen_id", **// queen's identifier column of the table ant**
                    columnType = Long.class,
                    foreignColumnName = "id")}, **// queen's primary key column name**
    saveForeignKeyModel = false) // 
  ForeignKeyContainer<Queen> queenModelContainer;

**Comment by marinovskiy** [comment]
Okay, I have made database with 3 tables from example. But when I try to add new Ant, I take exception that this table does not exist. I do not know how now I can add new info into DB when I have One to Many relationship. Could you help me?

**Comment by agrosner** [comment]
Check out `develop` package `com.raizlabs.android.dbflow.example` in the `test` directory. By default it calls `getMyAnts()` when the model loads from the DB>

**Comment by agrosner** [comment]
https://github.com/Raizlabs/DBFlow/blob/develop/usage/GettingStarted.md
