### ISSUE TITLE
Support for table name and column name strategy

### ISSUE THREAD

**Issue by simplysoft** [Raizlabs/DBFlow#447]
It would be great to have a way to customize how columns are generated from field names as well as the table names from models. In our particular case we would like to convert from camel case (myEntity) to snake case (my_entity)

**Comment by andrewpmoore** [comment]
When defining a column just use the "name" attribute.

e.g.
@Column(name = "my_column")

I'm sure you can do the same on the table name too.

**Comment by simplysoft** [comment]
yes, it is possible with the name attribute (both on the table as well as the column), but is is bit tedious and adds a lot of noise to the code. 
I must admit it is just a nice to have feature

**Comment by PingForward** [comment]
@agrosner, @simplysoft  Any updates on this?

**Comment by agrosner** [comment]
probably wont make this happen, as its confusing and can lead to problems when mapping fields to columns globally. I.e. this decreases readability and introduces complexity. best bet is to specify name in `@Column` to achieve what you want.
