### ISSUE TITLE
Using keyword as field name compiler check

### ISSUE THREAD

**Issue by mariciv** [Raizlabs/DBFlow#45]
It would be great if you could add compiler check when using SQL keywords in table model.
I had issue with model defined like this: 

`@Table
public class MyModel extends BaseModel {

    @Column(columnType = Column.PRIMARY_KEY_AUTO_INCREMENT)
    public int primary;

    @Column
    public int id;

    //... other colums
}`

It took me awhile to realize what was my mistake. 
It would be great when compiler could detect this error and show descriptive message.

**Comment by mozarcik** [comment]
I encountered that a while ago and fix that in my fork. I think that generator should quote column and table names instead of triggering error. I need to update my fork with latest changes and create PR.

**Comment by agrosner** [comment]
@mozarcik if you have code to PR that would be great. I would like to add this in a release at some point this week if it makes sense.

**Comment by agrosner** [comment]
in 1.5.0 #70
