### ISSUE TITLE
Parceler support for model

### ISSUE THREAD

**Issue by bryant1410** [Raizlabs/DBFlow#451]
Subclassing `BaseModel` and using [Parceler](https://github.com/johncarl81/parceler) gives problems out of the box. It can be solved if the attribute [`modelAdapter`](https://github.com/Raizlabs/DBFlow/blob/master/DBFlow/src/main/java/com/raizlabs/android/dbflow/structure/BaseModel.java#L45) is `transient` (see https://github.com/johncarl81/parceler/issues/73).

**Comment by agrosner** [comment]
Will make the necessary fix, I've used that library before!!

**Comment by agrosner** [comment]
in develop.

**Comment by johncarl81** [comment]
:+1: Awesome @agrosner .  Would you mind if I added a reference to DBFlow in the Parceler docs here: http://parceler.org/#mixing_getters_setters_and_fields
