### ISSUE TITLE
Transaction  is complicated

### ISSUE THREAD

**Issue by wanglg** [Raizlabs/DBFlow#452]
Transaction  is complicated

**Comment by agrosner** [comment]
please elaborate. Thank you.

**Comment by wanglg** [comment]
I want to delete on table data and insert some data,In activeandroid,I add  ActiveAndroid.beginTransaction();
delete something...
insert something...
ActiveAndroid.setTransactionSuccessful();
ActiveAndroid.endTransaction();
I konw DBFlow  can be achieved,I suppose I need custom Transactions,but it is complicated,I suggest simplify the logic.
I'm sorry to my poor English

**Comment by carmas123** [comment]
What is complicated? I'm sorry :)

Il lunedì 16 novembre 2015, wanglg <notifications@github.com> ha scritto:

**Comment by wanglg** [comment]
I'm sorry,I mean it is complex, Do you understand ?

**Comment by romulof** [comment]
DBFlow offers an API allow a transaction to be processed in background, without hurting the MainThread or UIThread. This API is easy to use for operations of the same kind (inserts, deletes, etc), but custom transactions you have to follow whats written on the documentation: https://github.com/Raizlabs/DBFlow/blob/master/usage/Transactions.md

In my application I already had a background thread to process this kind of transaction, so I did it in old style:
```java
SQLiteDatabase database = FlowManager.getDatabase(MyDatabase.NAME).getWritableDatabase();
database.beginTransaction();

try {
    // do your stuff here
    database.setTransactionSuccessful();
} finally {
    database.endTransaction();
}
```

**Comment by wanglg** [comment]
Thanks,It can solve my problem,I also find a way.
TransactionManager.transact(MobileDatabase.NAME,  new Runnable() {
                    @Override
                    public void run() {
                        // do your stuff here
                    }
                });

**Comment by agrosner** [comment]
out of date now.
