### ISSUE TITLE
Custom Enum Type Converter ignored

### ISSUE THREAD

**Issue by simplysoft** [Raizlabs/DBFlow#455]
We have a customized enum like

```
  public enum Style {
    VALUE1(0),
    VALUE2(1);

    private final short code;

    Style(int i) {
      code = (short) i;
    }

    public short getCode() {
      return code;
    }

    public static Style valueOf(short code) {
      for(Style s : values()) {
        if (code == s.getCode()) {
          return s;
        }
      }
      return null;
    }
  }
```

and correpsonding value converter

```
@com.raizlabs.android.dbflow.annotation.TypeConverter public class StyleConverter
    extends TypeConverter<Short, Style> {

  @Override public Short getDBValue(Pass.Style style) {
    return style.getCode();
  }

  @Override public Pass.Style getModelValue(Short code) {
    return Pass.Style.valueOf(code);
  }
}
```

however, the converter is not used in the generated code. The code uses the builtin support for enum by using the enum's name as representation in the database

**Comment by simplysoft** [comment]
In the 3.0 branch at least it is possible to specify a custom converter in the column definition, which will take precedence over other (default) access methods:

```
@Column(typeConverter = StyleConverter.class)
Style style;
```

Not sure if a `@com.raizlabs.android.dbflow.annotation.TypeConverter` annotated converter always should take precedence over the builtin access methods.

**Comment by agrosner** [comment]
thanks for help @simplysoft .  Yes it always takes precedence over built-in access methods, except if the variable is private. That retains the private column access and takes advantage of the fact that `TypeConverterAccess` "wraps" any existing column access.

**Comment by agrosner** [comment]
3.0 allows you to specify on a per-column basis its own `TypeConverter`.

**Comment by simplysoft** [comment]
It is a pleasure :)
From what I can tell, for Blob and Enum they don't take precendence, see [ColumnDefinition.java:178](https://github.com/Raizlabs/DBFlow/blob/develop/dbflow-processor/src/main/java/com/raizlabs/android/dbflow/processor/definition/column/ColumnDefinition.java#L178-L181), the code for finding the type converters follows later in a different conditional branch in 
[ColumnDefinition.java:194](https://github.com/Raizlabs/DBFlow/blob/develop/dbflow-processor/src/main/java/com/raizlabs/android/dbflow/processor/definition/column/ColumnDefinition.java#L194)

**Comment by agrosner** [comment]
Closing this with a note in the usage docs that special conversion for enums is only available on a per-column basis.

**Comment by marcusedu** [comment]
After I implement pattern TypeConverster in my enum class, the ModelAdapter can't save more my class.
Before that works but after change no more works.
I changed db version and cleared my installation.

Any tip?

**Comment by marcusedu** [comment]
My TypeConverter Class
```java
package br.powerappsdev.gas2.model;

import com.raizlabs.android.dbflow.converter.TypeConverter;

public class TipoVeiculoConverter extends TypeConverter<Short, TipoVeiculo> {
    private short moto = 1;
    private short carro = 2;
    private short caminhao = 3;

    @Override
    public Short getDBValue(TipoVeiculo tipoVeiculo) {
        switch (tipoVeiculo) {
            case MOTO:
                return moto;
            case CARRO:
                return carro;
            default:
                return caminhao;
        }
    }

    @Override
    public TipoVeiculo getModelValue(Short aShort) {
        if (aShort.equals(moto)) {
            return TipoVeiculo.MOTO;
        } else if (aShort.equals(carro)) {
            return TipoVeiculo.CARRO;
        } else {
            return TipoVeiculo.CAMINHAO;
        }
    }
}
```

And this is my enum class
```java
package br.powerappsdev.gas2.model;

public enum TipoVeiculo {
    MOTO ("Moto"), CARRO ("Carro"), CAMINHAO ("Caminhão");

    public String descricao;

    TipoVeiculo(String descricao){
        this.descricao = descricao;
    }
}
```

And this is my class with relatoinship with enum class
```java
@Table(database = AppDBClass.class)
public class Veiculo {
    @PrimaryKey
    private UUID id;
    @Column(typeConverter = TipoVeiculoConverter.class)
    private TipoVeiculo tipoVeiculo;
//getters and setters here
}
```

**Comment by trevjonez** [comment]
try adding the `@TypeConverter` annotation to your type converter implementation and just remove the typeConverter label from the column declaration site?

**Comment by marcusedu** [comment]
@trevjonez Thank you so much, works. 👍
