### ISSUE TITLE
Cannot reset database

### ISSUE THREAD

**Issue by bafitor** [Raizlabs/DBFlow#46]
Hi,

I'm invoking this method:

**FlowManager.getDatabase(DATABASE_NAME).reset(context);**

But nothing happens to my database.

I think the problem is in the method that deletes the database:

	public void reset(Context context) {
	    if (!isResetting) {
	        isResetting = true;
	        context.deleteDatabase(getDatabaseName());
	        mHelper = new FlowSQLiteOpenHelper(this, mInternalHelperListener);
	        isResetting = false;
	    }
	}

**getDatabaseName()** only returns the database name without the ".db" extension. If we append the ".db" extension to the name the database is deleted.

Can you look at this issue?

Thanks

**Comment by agrosner** [comment]
hey @bafitor nice find. If you make the change on ```develop``` branch and submit a pull request for my ```develop``` branch you can become a contributor! otherwise I can do it myself for a bugfix release
