### ISSUE TITLE
Providing Snapshot Artefacts

### ISSUE THREAD

**Issue by simplysoft** [Raizlabs/DBFlow#460]
It would be convenient to have snapshot artefacts of the development branch. 
One way to achieve this is using [jitpack.io](http://jitpack.io), we have integrated support for it in our fork (https://github.com/simplysoft/DBFlow/commit/2ecfbc733e7e83b71be66a40a5225244803acd84) and it works nicely

**Comment by agrosner** [comment]
https://github.com/Raizlabs/DBFlow#including-in-your-project
