### ISSUE TITLE
Doc isn't complete: JsonModel and ModelContainer

### ISSUE THREAD

**Issue by u007** [Raizlabs/DBFlow#462]
The doc mentioning about jsonmodel does not mention any example of adding 
@ ModelContainer at class level.

took my some time to figure this out.

and is there a way for me to skip certain field from being parsed from json to jsonmodel?
and will this apply when converting model to jsonmodel?

And migration class did not mention where to place the custom migration classes like:

public class Migration1 extends BaseMigration

Does anyone know how do i run this file? will this be automatic from 
FlowManager.init ?

thanks

**Comment by agrosner** [comment]
1. Skipping fields, not currently. I can add this if its trivial. Let me try.
2. Add the `@Migration` to the class to specify what DB it runs on and version

**Comment by u007** [comment]
Hi Andrew, the field exclusion for modelcontainer will be awesome!
My current work around is to add the field manually before turning it into
jsonmodel.

Okay migration noted, but can someone help to add it the doc with example?

Thanks for the quick response :)

**Comment by agrosner** [comment]
its already there. https://github.com/Raizlabs/DBFlow/blob/develop/usage/Migrations.md#migration-classes

**Comment by u007** [comment]
thank you :)

btw, where do i place the migration class?
i can place it anywhere?
how do i call it in application file?

thanks

**Comment by agrosner** [comment]
https://github.com/Raizlabs/DBFlow/blob/develop/usage2/Migrations.md#migration-classes :)
