### ISSUE TITLE
Save Image as Blob

### ISSUE THREAD

**Issue by coniocharles** [Raizlabs/DBFlow#464]
Having a problem saving image in DBFlow.  
I'm converting the image to byte.  

      try {
            FileInputStream fileInputStream = new FileInputStream(imageURL);
            byte[] image = new byte[fileInputStream.available()];
            fileInputStream.read(image);
            

        } catch (IOException e) {
            e.printStackTrace();
        }

But it cannot be saved as Blob using DBFlow. Is there any way to save the blob image into dbFlow?  
I just used this dbflow 2hours ago. so I'm pretty new here. thanks

**Comment by agrosner** [comment]
if you use the develop branch (3.0) which will be released very soon, you can use the `Blob` column type to save and retrieve blob information from the DB.

**Comment by agrosner** [comment]
closing as 3.0 works with image blobs.
