### ISSUE TITLE
One to many relations

### ISSUE THREAD

**Issue by ArcaneWater** [Raizlabs/DBFlow#465]
Even that tutorial is great i got lost when i tryed to implement 1:n to my example,

So i have User which can have multiple businesses (i alread have defined models, so i use it with retrofit) Here is my class:
```Java
    @Expose
    @Column
    private Boolean allow_offline;
    @Expose
    @Column
    private Integer user_level;
    @Expose
    @Column
    private Integer account_validity;
    @Expose
    @Column
    private Integer selected_business;
    @Expose
    @Column
    @PrimaryKey
    private String user_id;
    @Expose
    @Column
    private Boolean allow_print;
    @Expose
    @Column
    private String email;
    @Expose
    private List<Business> businesses;
```

and my business variables:
```Java
    @Expose
    @Column
    @PrimaryKey
    private Integer id;
    @Expose
    @Column
    private String name;
    @Expose
    @Column
    private Boolean is_zero_tax;
    @Expose
    @Column
    private String header;
    @Expose
    @Column
    private String footer;
    @Expose
    private List<Pos> poses = new ArrayList<Pos>();
```

So if i understand correcty, i should now add a new variable at Business class called user_id(type string) and method associateUserToBusiness()...?

**Comment by agrosner** [comment]
You  can follow the tutorial and use a `ForeignKeyContainer` to keep the relation efficient. and yes, you can create the method for that, since a `ForeignKeyContainer` is a stub for the full relation. It's lazy loaded so its super efficient, but that also means you cannot easily set the data in it.

**Comment by agrosner** [comment]
hope this helps.
