### ISSUE TITLE
Byte[] DataType

### ISSUE THREAD

**Issue by coniocharles** [Raizlabs/DBFlow#466]
I have an Images and I converted it to Bytes. 
But i'm having a problem setting byte[] datatype using dbflow.
is there a way to implement Byte[] datatype on this? thanks.

**Comment by agrosner** [comment]
try the 3.0 branch. youll need to migrate the app to that. Use a `Blob` object as the column instead.

**Comment by agrosner** [comment]
closing as 3.0, develop branch now works
