### ISSUE TITLE
Drop a column on migration

### ISSUE THREAD

**Issue by eyal-fairfly** [Raizlabs/DBFlow#467]
Hello,

I am migrating the DB to a newer version (kudos for making the migration process easy) and I wish to drop a few columns which are no longer necessary. I've looked around but couldn't find any reference, is this possible?

Thank you!

**Comment by agrosner** [comment]
This is a SQLite question, and short answer is...not easily. You have to (this is with SQLite too):
1. Create new table without column with temporary name
2. Copy over data to it
3. Drop old table
4. Recreate new table with column left out

As I said, not easy.

**Comment by eyal-fairfly** [comment]
Thank you for the prompt reply :+1:
