### ISSUE TITLE
select alias

### ISSUE THREAD

**Issue by u007** [Raizlabs/DBFlow#469]
hi,

is it possible to have alias support for select?

thanks

**Comment by u007** [comment]
can we have Select().addSelect(name), and addSelect(name, alias)

**Comment by agrosner** [comment]
Not sure the question. in `3.0` you can do `MyTable_Table.column.as("Some Alias")` and use that in your queries

**Comment by u007** [comment]
Hi,

im not sure how to get version 3.0 to work with my android,
how about adding @Alias for column declaration?
do you think that will be good?

thanks

**Comment by agrosner** [comment]
no. 3.0 lets you use `Property`, which have an `as()` method, giving you the Alias functionality you desire.

**Comment by u007** [comment]
my current work around, but its manual and ive to output every column.
ColumnAlias[] alias = new ColumnAlias[3];
alias[0] = ColumnAlias.columnRaw("localid as _id");
alias[1] = ColumnAlias.column("id");
alias[2] = ColumnAlias.column("name");
// a bug on cursoradapter that ive to force select * for listview
new Select(alias).from(Product.class).where(where, args).orderBy("name asc").query();
