### ISSUE TITLE
Join Statements should allow different, new kind of Model return classes.

### ISSUE THREAD

**Issue by agrosner** [Raizlabs/DBFlow#47]
1. Currently JOIN only allow you to join on a specific ```Model``` class and return a list of those. I
2. It should   have you create a special ```Model``` class defined as ```@Join``` to represent the JOIN statement.
3. This leads to missing data when running ```JOIN``` statements

**Comment by iainconnor** [comment]
:+1: Terrific idea, could really save some performance of fetching relationships on the fly

**Comment by nambv** [comment]
Hi @agrosner  Have you done this issue :D?
I want to inner join 2 tables and get all properties of 2 model.
Is there any way I can do it?
Thank you very much! ^^

**Comment by Rainer-Lang** [comment]
This is a feature that would be pretty nice but also helpful.

**Comment by agrosner** [comment]
Hey, Not yet. It is on my roadmap for a 2.0 release since it requires some breaking changes in the API. If I am going to do a 2.0 release I also want to make some changes to help simplify or provide less confusion in the API.

**Comment by nambv** [comment]
Thanks for your answer @agrosner ! I'll be waiting for this. ^^

**Comment by Rainer-Lang** [comment]
Wow that are really great news. 
Thanks for your hard work.
