### ISSUE TITLE
Has no COLUMN error even after updating DB version

### ISSUE THREAD

**Issue by vivekkartha** [Raizlabs/DBFlow#470]
I keep getting no column exits error even after I updated DB flow DB version. Uninstall and installing will help, but this is not always possible if the app in the playstore. User's need not necessarily uninstall the app.

**Comment by agrosner** [comment]
Can let me know the version of DBFlow. And have you done a migration? I need more info here...

**Comment by vivekkartha** [comment]
Seems I didn't do migration.  I am closing this isse

**Comment by vivekkartha** [comment]
Seems I didn't do migration.  I am closing this isse
