### ISSUE TITLE
Error when saving the Ant object

### ISSUE THREAD

**Issue by harry-itp** [Raizlabs/DBFlow#474]
I have been following the [Getting Started](https://github.com/Raizlabs/DBFlow/blob/master/usage/GettingStarted.md) guide, and was trying to implement below code:

    Queen queen = new Queen();
    queen.save();

    Ant ant = new Ant();
    ant.addQueen(queen);
    ant.save();

There is nothing wrong so far. I can see the `Ant` object is now connected to its `Queen`. HOWEVER, when I try to change the `Ant` properties then call `ant.save()` again, an error occurs. The same error happened when I call `ant.save()` twice. It is something like:
`E/SQLiteLog﹕ (1) near "something": syntax error`

then an exception is raised:
`android.database.sqlite.SQLiteException: near "something": syntax error (code 1): , while compiling: UPDATE  OR ABORT Ant SET`

If I DELETE the Ant table before calling `ant.save()` for the second time, it works. No error, but this is not what I expected. I want to UPDATE, instead of DELETE then INSERT.

**Comment by agrosner** [comment]
have you tried it in the `develop` 3.0 branch? I understand its a significant update, but the issue should be fixed there.

**Comment by harry-itp** [comment]
Oh, I haven't. I'm currently using `2.2.1`.
Okay, I will try it. Thanks for the reply!

**Comment by agrosner** [comment]
youre welcome. closing. reopen if it happens again
