### ISSUE TITLE
Truncate/Delete all rows of all tables in database

### ISSUE THREAD

**Issue by setiawanp** [Raizlabs/DBFlow#476]
I would like to know. Can DbFlow truncate all tables in database? Or at least getting all the tables name in database in `List<String>` or `List<Class<? extends Model>>`. Thank you.

**Comment by agrosner** [comment]
`SELECT name FROM sqlite_master WHERE type = "table"` http://stackoverflow.com/questions/82875/how-to-list-the-tables-in-an-sqlite-database-file-that-was-opened-with-attach

And you can define a `QueryModel` to retrieve that information.
