### ISSUE TITLE
Exclude column from ModelContainer

### ISSUE THREAD

**Issue by romulof** [Raizlabs/DBFlow#477]
Is there a way to exclude a `@Column` from `ModelContainer`?

I found `@ContainerKey` annotation, but it only allows to change the name.

The real problem here is that my model has a few columns with local data, and the remaining ones have to be updated by JSON, so I'm trying to use ModelContainer to update values without destroying these local ones.

**Comment by agrosner** [comment]
how would you say you're using it? `ModelContainer` is meant to bypass the conversion into `Model` before saving/loading from db from a key/value source. That was not necessarily its intended purpose, but I could have an "excludeFromToModel()` flag on the `@Column` if that's what you mean by excluding them from parse.

**Comment by agrosner** [comment]
that's in 3.0, you can now add `@ContainerKey` to any field to have it included in the `toModel()` method parse, and vice versa where a `@Column` can get excluded from the parse as well.

**Comment by romulof** [comment]
> how would you say you're using it?

In my case, data from JSON never have those fields. For example:

```java
@Table(databaseName = NoteDatabase.NAME)
@ModelContainer
public class Note extends BaseModel {

  @Column
  @PrimaryKey
  long id;

  @Column
  @ContainerKey("titulo") // My JSON comes in portuguese (not my fault)
  String title;

  @Column
  @ContainerKey("conteudo")
  String content;

  /**
      This field stores local information only, it never comes from JSON.
      It's only manipulated using model object.
   */
  @Column
  @ContainerKey(false) // Suggestion 1
  @ContainerExcluded // Suggestion 2
  boolean read;
}
```
