### ISSUE TITLE
Select Query (AVG)

### ISSUE THREAD

**Issue by coniocharles** [Raizlabs/DBFlow#480]
I'm having a problem with Select Query using AVG.  
I have set the ListModel like this.  

  private List<ModelComments> commentDatas;
  commentDatas= new Select().avg(ModelComments$Table.RATING).from(ModelComments.class).queryList();

But when I get the values from the selected, i got nothing but null values,  
           ModelComments modelComments =(ModelComments)getItem(i);
            Log.e(""," LAT: "RATING: "+modelComments.rating);

In that code resulting to null. what seems to be the problem?

**Comment by agrosner** [comment]
use 3.0/develop branch
