### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by LouisCAD** [Raizlabs/DBFlow#481]
Hi!
I'm reading the documentation, and there's something I don't get on [this page](https://github.com/Raizlabs/DBFlow/blob/master/usage/DBStructure.md#model--creation):
> **Models Support:**
…
2. A non-default object with a TypeConverter is also save-able (**leave out parameterized classes such as List, Map and use List and Map**.).
…

Does it means we should use List, Map and so on, but without declaring any type parameter? It could be clearer IMHO.
Thanks and have a nice day :)

**Comment by romulof** [comment]
You can't use classes that require parameters without declaring them.

And they cannot be used with TypeConverter.

**Comment by LouisCAD** [comment]
Thanks for your clarification @romulof ! I hope it will be integrated in the doc :)
