### ISSUE TITLE
[3.0] ForeignKeyContainer#exists() can populate partial model and subsequent load() will not load

### ISSUE THREAD

**Issue by simplysoft** [Raizlabs/DBFlow#485]
When saving an entity, the ForeignKeyContainer is populated with the primary key of the foreign entity (and only that data)

When calling exists() on the foreign key container, the model is created based on the partial data
```
  public boolean exists() {
    Model model = this.toModel();
    return model != null && this.modelAdapter.exists(model);
  }
```

subsequent load() calls won't load the full data as the model already is set:
```
public ModelClass load() {
    if(this.model == null && this.data != null) {
      this.model = (new Select(new IProperty[0])).from(this.modelAdapter.getModelClass()).where(new SQLCondition[]{this.modelContainerAdapter.getPrimaryConditionClause(this)}).querySingle();
    }

    return this.model;
  }
```

When not calling `exists()` but directly `load()`, then everything works as expected. The code should distinguish between partially loaded (only primary key) model and fully loaded models, and in case of apartially loaded model, not set the model in the container, or allow `load()` to fetch the data if the set model is only partial

**Comment by agrosner** [comment]
added a `reload()` method of `ForeignKeyContainer` in `develop`
