### ISSUE TITLE
Boolean values not being loaded into model from prepackaged databse

### ISSUE THREAD

**Issue by ivanquirino** [Raizlabs/DBFlow#487]
I have a prepackaged db and a correctly mapped Model, all other fields work (string, ints), but boolean values are not loaded. I worked around by using integers anyway, but I think this is an issue to be checked.

Link to db file and model Code: https://dl.dropboxusercontent.com/u/6964311/yupitime.zip

**Comment by agrosner** [comment]
how are booleans represented in the prepackaged DB?

**Comment by ivanquirino** [comment]
as boolean type. Using integers solved the problem. I wrote a get method to get as boolean.

**Comment by filipemanuelofs** [comment]
@ivanquirino can you show the solution?

**Comment by ivanquirino** [comment]
@filipemanuelofs I do not use booleans. Use integers as booleans.

**Comment by agrosner** [comment]
Not sure what version this is, but this is out of date.
