### ISSUE TITLE
@Unique not working [Resolved]

### ISSUE THREAD

**Issue by DanChaltiel** [Raizlabs/DBFlow#489]
I'm trying to set a column unique, but it's not working : 
```java
@Table(databaseName = FlowDatabase.NAME)
public class LifeEventType extends BaseModel {
    public static final String NAME = "LIFE_EVENT_TYPE";

    @Column
    @PrimaryKey(autoincrement = true)
    public long id;

    @Unique(onUniqueConflict = ConflictAction.ABORT)
    @Column
    public String nom;

    public LifeEventType(String nom) {
        this.nom = nom;
    }
```

Now I can write
```java
LifeEventType type1 = new LifeEventType("blabla")
LifeEventType type2 = new LifeEventType("blabla")
type1.save();
type2.save();
```
And it return no error and insert the new object in the database (List<LifeEventType> returned on select by name "blabla" is size 2).
The same occurs if I use insert() in place of save();

I cant find any clue about constraints in tutorial so I don't really know if I'm doing it right...

**Comment by agrosner** [comment]
have you tried 3.0 / develop branch of the library?

**Comment by DanChaltiel** [comment]
I didn't find anything about it, what should I write in my build.gradle file ?

**Comment by DanChaltiel** [comment]
Actually, I'm affraid 
``` 
List<LifeEvent> events;
@OneToMany(methods = {OneToMany.Method.SAVE, OneToMany.Method.DELETE}, variableName = "events")
public List<LifeEvent> getMyEvents() {
    if(events == null) {
        events = new Select()
                .from(LifeEvent.class)
                .where(Condition.column(LifeEvent$Table.LIFEEVENTTYPEFOREIGNKEYCONTAINER_TYPE_ID).is(id))
                .queryList();
    }
    return events;
}
 ```
won't work either : if I delete a LifeEventType , all its LifeEvent are not deleted along.

Could I have made something wrong ?
