### ISSUE TITLE
getHelper of BaseDatabaseDefinition no thread safe?

### ISSUE THREAD

**Issue by bood** [Raizlabs/DBFlow#492]
Looks like no thread protection is done there.
In multi-thread environment, looks like it's possible to have more than one FlowSQLiteOpenHelper created.
Wouldn't that be a problem?

**Comment by mathieudebrito** [comment]
+1

**Comment by bood** [comment]
@agrosner Could you shed some light on this? or help me understand why this is not a problem?

**Comment by agrosner** [comment]
it's possible, but not recommended. If you need thread-safe operations, or wait for stuff to happen async, use the `DBTransactionQueue` via `BaseTransaction` subclasses.

**Comment by BernhardReu** [comment]
Hi,
I just commented on an related issue (https://github.com/Raizlabs/DBFlow/issues/357) and would like to reopen the discussion about thread safety without using the <code>DBTransactionQueue</code>.
Tank you!

**Comment by agrosner** [comment]
np @BernhardReu Will put this in next beta.

**Comment by agrosner** [comment]
fixed in beta6
