### ISSUE TITLE
UPDATE with internal reference (incrementing)

### ISSUE THREAD

**Issue by DanChaltiel** [Raizlabs/DBFlow#494]
Is it possible to update a model with incrementing a field ?
Just like this [StackOverflow question](http://stackoverflow.com/questions/744289/sqlite-increase-value-by-a-certain-number).

I tried with 
```
Update.table(LifeEventType.class).set(Condition.column(LifeEventType$Table.PLACE).eq(LifeEventType$Table.PLACE+"-1")).where(
        Condition.column(LifeEventType$Table.PLACE).greaterThan(previousPlace),
        Condition.column(LifeEventType$Table.PLACE).lessThanOrEq(newPlace)
).queryClose();
```
But the query ended like this : 
```
UPDATE `LifeEventType` SET `place`='place-1' WHERE `place`>1 AND `place`<=2  
```

The problem is the simple quotes around place-1, is there a way to achieve this without using a Select query ?

**Comment by agrosner** [comment]
this is out of date. please use `develop` branch. thank you.

**Comment by DanChaltiel** [comment]
I'm migrating to version 3beta, and I don't find a clue about my old question in the doc. Could you please help me ?
