### ISSUE TITLE
Could not find dependency

### ISSUE THREAD

**Issue by AamirAbro** [Raizlabs/DBFlow#496]
Gradle sync failed: Could not find com.raizlabs.android:dbflow-processor:3.0.0-beta1.

I have added jitpack to my repositories but but does not appears to download it from there.

**Comment by jitpack-io** [comment]
Hi
In the meantime it's available as `com.github.Raizlabs.DBFlow:dbflow-processor:3.0.0-beta1`. It appears the custom domain is not yet set up.

**Comment by epool** [comment]
+1

**Comment by elsennov** [comment]
```
Error:Could not find com.raizlabs.android:dbflow-core:3.0.0-beta1.
Required by:
    :skyfish:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>
```

**Comment by Fshamri** [comment]
got the same issue ............. any solution yet??

**Comment by jitpack-io** [comment]
@elsennov @Fshamri  Use the dependencies as:
`compile 'com.github.Raizlabs.DBFlow:dbflow-processor:3.0.0-beta1'`
`compile 'com.github.Raizlabs.DBFlow:dbflow-core:3.0.0-beta1'`

**Comment by agrosner** [comment]
https://github.com/Raizlabs/DBFlow#including-in-your-project

**Comment by agrosner** [comment]
you need to specify the JitPack.io repo `maven { url "https://jitpack.io" }` in your build.gradle file

**Comment by epool** [comment]
@agrosner Maybe you could update the README file to avoid this kind of issues, because there is:

    dependencies {
        apt 'com.raizlabs.android:dbflow-processor:3.0.0-beta1'
        compile 'com.raizlabs.android:dbflow-core:3.0.0-beta1'
        compile 'com.raizlabs.android:dbflow:3.0.0-beta1'
    }

instead of:

    dependencies {
        apt 'com.github.Raizlabs.DBFlow:dbflow-processor:3.0.0-beta1'
        compile 'com.github.Raizlabs.DBFlow:dbflow-core:3.0.0-beta1'
        compile 'com.github.Raizlabs.DBFlow:dbflow:3.0.0-beta1'
    }

**Comment by agrosner** [comment]
thanks @epool for pointing it out. fixed
