### ISSUE TITLE
Insert tutorial

### ISSUE THREAD

**Issue by elsennov** [Raizlabs/DBFlow#498]
Hi is there any INSERT tutorial? I can't find one. Thanks

**Comment by Jackoder** [comment]
I think so, it would be useful if the demo can provide more infomation :)

**Comment by agrosner** [comment]
you mean like `SQLite.insert().into(MyTable.class).columns(..).values(...).queryClose()`? for SQLite raw insert or `model.insert()`?

**Comment by filipemanuelofs** [comment]
I think he means on [SQL Statements](https://github.com/Raizlabs/DBFlow/blob/master/usage/SQLQuery.md) doesn't have **insert** step-by-step, but has **select**, **delete**, **update**.

**Comment by elsennov** [comment]
Yes @filipemanuelofs is right. Thanks @agrosner for the answer :)
