### ISSUE TITLE
[3.0.0-beta1] generatedClassSeparator not used in Adapter

### ISSUE THREAD

**Issue by noinnion** [Raizlabs/DBFlow#501]
generated Adapters don't use generatedClassSeparator defined in @Database

**Comment by agrosner** [comment]
are you sure? I don't see it happening here.

**Comment by gnuhel** [comment]
yeah I am still seeing it

````
    //// Only load model if references match, for efficiency
    int indexuser_id = cursor.getColumnIndex("user_id");
    if (indexuser_id != -1 && !cursor.isNull(indexuser_id)) {
      model.user = new com.raizlabs.android.dbflow.sql.language.Select().from(de.dynaweb.dynapos.database.model.User.class).where()
          .and(de.dynaweb.dynapos.database.model.User_Table.id.eq(cursor.getInt(indexuser_id))).querySingle();
    }
    //// Only load model if references match, for efficiency
    int indexcustomer_id = cursor.getColumnIndex("customer_id");
    if (indexcustomer_id != -1 && !cursor.isNull(indexcustomer_id)) {
      model.customer = new com.raizlabs.android.dbflow.sql.language.Select().from(de.dynaweb.dynapos.database.model.Customer.class).where()
          .and(de.dynaweb.dynapos.database.model.Customer_Table.id.eq(cursor.getInt(indexcustomer_id))).querySingle();
    }
````

it should be  ```User$Table.id``` and  ```Customer$Table.id``` instead of ```User_Table.id``` and  ```Customer_Table.id```

**Comment by gnuhel** [comment]
I think it is here:

https://github.com/Raizlabs/DBFlow/blob/56f83f4abb0c1d082b8457c4af2d9c66a49a2594/dbflow-processor/src/main/java/com/raizlabs/android/dbflow/processor/definition/column/ForeignKeyColumnDefinition.java#L274

I don't know how to get database to get the classSeperator :(

**Comment by lzanita09** [comment]
I'm seeing it too, it only happens if I use ForeignKey. I think @gnuhel pointed to the right place.
