### ISSUE TITLE
[3.0.0-beta1] Could not create table if @UniqueGroup defined but not use

### ISSUE THREAD

**Issue by noinnion** [Raizlabs/DBFlow#502]
if you define 
uniqueColumnGroups = {
				@UniqueGroup(groupNumber = 1, uniqueConflict = ConflictAction.FAIL),
				@UniqueGroup(groupNumber = 2, uniqueConflict = ConflictAction.ROLLBACK)}

in @Table but and don't use it in any column then it produce a query with 
UNIQUE() ON CONFLICT ROLLBACK

sqlite will raise the error near ")": syntax error (code 1)

**Comment by agrosner** [comment]
won't generate the UNIQUE if no columns reference it.
