### ISSUE TITLE
Update foreign key without requery

### ISSUE THREAD

**Issue by krzysiek-zgondek** [Raizlabs/DBFlow#506]
Hi,
here is the situation:
ModelA{
@ForeignKey
ModelB linked_model
}

now i have a huge list of ModelA loaded objects and want only to refresh few linked ModelB (inside loaded ModelA objects). Is this possible without requerying whole ModelA list ? Sth like ModelAList[2].linked_model.refresh() etc?

**Comment by agrosner** [comment]
its just an object. you can just loop through and set the field with the updated object. You still need to save the whole object `ModelA` to get the change. Or you can run the raw `Update.set()` method using wrapper classes to do a bulk change without having to pull the information out of the DB and then resaving it.
