### ISSUE TITLE
Duplicates in db when insert record with already defined primary key

### ISSUE THREAD

**Issue by zoopolitic** [Raizlabs/DBFlow#507]
Maybe I misunderstood smth, but if I try to save records with already defined id > 0, it inserts every record twice.

```
@SuppressWarnings("unchecked")
   public static <ModelClass extends Model, TableClass extends Model, AdapterClass extends RetrievalAdapter & InternalAdapter>
   void save(TableClass model, AdapterClass adapter, ModelAdapter<ModelClass> modelAdapter) {
       if (model == null) {
           throw new IllegalArgumentException("Model from " + modelAdapter.getModelClass() + " was null");
       }

       boolean exists = adapter.exists(model);

       if (exists) {
           exists = update(model, adapter, modelAdapter);
       }

       if (!exists) {
           insert(model, adapter, modelAdapter);
       }

       notifyModelChanged(model, adapter, modelAdapter, Action.SAVE);
   }
```

First exists returns true since id > 0, then update returns false because this record is not actually in DB, but also update performs insertion, after this exists == false and here:

       if (!exists) {
           insert(model, adapter, modelAdapter);
       }

insertion performing second time.

**Comment by agrosner** [comment]
have you tried `3.0`? By default if checks > 0 and runs a `SELECT` query on the object to see if it exists in DB. The behavior is controlled by in `PrimaryKey`:
```
/**
     * @return When true, we simple do {columnName} &gt; 0 when checking for it's existence if {@link #autoincrement()}
     * is true. If not, we do a full database SELECT exists.
     */
    boolean quickCheckAutoIncrement() default false;
```

**Comment by agrosner** [comment]
Pre 3.0 it only did the quick check on an autoincrement `PrimaryKey`

**Comment by zoopolitic** [comment]
No, I didn't use 3.0 yet, and yes, I saw that quick check as described above, so question can be closed I think.
