### ISSUE TITLE
Could not find com.raizlabs.android.DBFlow:dbflow-processor:3.0.0-beta1

### ISSUE THREAD

**Issue by joginder89** [Raizlabs/DBFlow#509]
I have included

    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

in top level gradle and 

    apply plugin: 'com.neenbedankt.android-apt'

in app level and 

     apt 'com.raizlabs.android.DBFlow:dbflow-processor:3.0.0-beta1'
    compile "com.raizlabs.android.DBFlow:dbflow-core:3.0.0-beta1"
    compile "com.raizlabs.android.DBFlow:dbflow:3.0.0-beta1"

in dependencies.

**Comment by mirecalu** [comment]
Fixed in this PR : https://github.com/Raizlabs/DBFlow/pull/508

**Comment by joginder89** [comment]
@mirecalu I have try this but not work.

**Comment by agrosner** [comment]
merged in #508
