### ISSUE TITLE
[3.0.0-beta1] Multiples modules

### ISSUE THREAD

**Issue by mirecalu** [Raizlabs/DBFlow#510]
I've tried to use DBFlow in 2 modules in my project. I've followed the Readme ( https://github.com/Raizlabs/DBFlow/blob/master/usage/DatabaseModules.md ) by putting : 

```
apt {
    arguments {
        targetModuleName 'Gsnews'
    }
}
```
and 

```
apt {
    arguments {
        targetModuleName 'Gstests'
    }
}
```

in my build.gradle(s)

Unfortunately, "GeneratedDatabaseHolderMyModel" is not generate so I can't initialize my modules with 
```FlowManager.initModule(GeneratedDatabaseHolderMyModel.class); ```

Any idea ?

**Comment by agrosner** [comment]
`GeneratedDatabaseHolderGsNews` + `GeneratedDatabaseHolderGsTests` should be the names.

**Comment by mirecalu** [comment]
No files named GeneratedDatabaseHolder* are generated.

**Comment by agrosner** [comment]
did you try building/running the app first?

**Comment by mirecalu** [comment]
yes I did

**Comment by agrosner** [comment]
sorry I had the order reversed. (https://github.com/Raizlabs/DBFlow/blob/master/usage2/MultipleModules.md)
