### ISSUE TITLE
[3.0.0-beta1] Duplication of table alias in query

### ISSUE THREAD

**Issue by jacktech24** [Raizlabs/DBFlow#512]
Hi,
I found a bug in NameAlias class where you are adding prefixName twice. As far as I understand, you are generating the query string by calling toString on NameAlias, which is then calling getDefinition(). In there you are checking whether there is prefixName and if so, then adding it, but then also calling getName() method which does exactly the same, hence the prefixName is added twice.
Example to try:
```
Timber.i("NA: "+YourTable.yourTableProperty.withTable(new NameAlias("ALIAS")).getNameAlias().toString());
```
Temporary fix (setting tickName to false)
```
Timber.i("NA: "+YourTable.yourTableProperty.getNameAlias().withTable("ALIAS").tickName(false).toString());
```

I understand why you have done this, as when tickName is false, the prefixName won't be added because instead of getName(), getNamePropertyRaw() is called thus not adding the prefixName. At least I suggest this fix (can send PR if you want)
```
@NonNull
    public String getDefinition() {
        StringBuilder definition = new StringBuilder();
        if (prefixName != null && !tickName) {
            definition.append(prefixName).append(".");
        }
        definition.append(tickName ? getName() : getNamePropertyRaw());
        if (hasAlias()) {
            definition.append(" AS ").append(getAliasName());
        }
        return definition.toString();
    }
```

**Comment by kelsos** [comment]
Is there any update on the issue?

**Comment by agrosner** [comment]
fixed in `develop`
