### ISSUE TITLE
Update-Migration calculations

### ISSUE THREAD

**Issue by TheWhiteLlama** [Raizlabs/DBFlow#516]
Hey there!

I wanted to upgrade my app to use the new DBFlow beta version. Before I had an update-migration that would set the value of a column to the product of two other existing columns.

Therefor I could simply do this:
```
        set(Condition.column(Project$Table.PROGRESS).is("currentIndex * 100 / (requiredS * requiredR)"));
```

Now I am not sure how to make this migration, since with the properties I cannot do this anymore. Since this here also won't work:
```
this.set(Project$Table.progress.is(Project$Table.currentIndex * 100f / (Project$Table.requiredS * Project$Table.requiredR)));
```

I'm a bit confused. Thank you!

**Comment by agrosner** [comment]
in `3.0.0beta-6` (not released yet)
```
this.set(Project$Table.progress.is(Project$Table.currentIndex.multiplyBy(100f).divideBy( (Project$Table.requiredS).multiplyBy(Project$Table.requiredR)))); 
```
potentially would work (untested).

**Comment by agrosner** [comment]
reopen if issue is still relevant
