### ISSUE TITLE
[3.0.0-beta1] Specifying multiple columns in the .orderBy

### ISSUE THREAD

**Issue by andrewpmoore** [Raizlabs/DBFlow#518]
Previously I'd do something like this:

.orderBy("first_name, last_name")

but now with 3.0.0-beta1 I can't seem to find a way to handle multiple columns (or maybe the documentation needs adding to)

**Comment by andrewpmoore** [comment]
would  I do

.orderBy(Model_Table.first_name)
.orderBy(Model_Table.last_name)

instead?

**Comment by andrewpmoore** [comment]
Another issue potentially, is how do you cast an item in the order by. I'm wanting to cast a value into an integer and used to be able to use the "cast" function in sqlite but I'm not sure how to do that now.

**Comment by eboissonneault** [comment]
There is a new function that has been added: 

orderByAll(List<OrderBy> orderBies)

I didn't have the chance to test it yet but looking at its definition, it seems pretty clear that it's the new way of handling multiple columns.

**Comment by andrewpmoore** [comment]
Thanks, that sound good, but I can't think how to call it.
The Class OrderBy is private when trying to create a new OrderBy object

**Comment by andrewpmoore** [comment]
Mutli orderbies also seems to work

.orderBy(1)
.orderBy(2)

looking at the generated query

**Comment by eboissonneault** [comment]
@andrewpmoore I had problems trying that in previous versions. The order of the order Bies was randomly changing. I don't think it was intended to respect the order of function calls.

**Comment by eboissonneault** [comment]
@andrewpmoore You can instantiate a new OrderBy object using these static functions: OrderBy.fromProperty or OrderBy.fromNameAlias.

**Comment by andrewpmoore** [comment]
Thanks Eric
