### ISSUE TITLE
[3.0.0-beta1] README.md unclear

### ISSUE THREAD

**Issue by Ekt0s** [Raizlabs/DBFlow#519]
Hi! 

I've been trying to migrate from DBFlow 2.*.* to 3.0.0 for the last hours and I've found an error on the README on the include example.

Here:
```
dependencies {
     apt 'com.raizlabs.android:dbflow-processor:3.0.0-beta1'
     compile "com.raizlabs.android:dbflow-core:3.0.0-beta1"
     compile "com.raizlabs.android:dbflow:3.0.0-beta1"
  }
```

But shouldn't the dependencies be like that ? 
```
    apt 'com.github.Raizlabs.DBFlow:dbflow-processor:develop-SNAPSHOT'
    compile "com.github.Raizlabs.DBFlow:dbflow-core:develop-SNAPSHOT"
    compile "com.github.Raizlabs.DBFlow:dbflow:develop-SNAPSHOT"
```

I've also a conflict error due to 'com.android.support:support-annotations' dependency *DBFlow* use the 23.1.1 but Square's AssertJ-Android library (v1.1.1) uses the 22.2.1. I will appreciate the help :wink: 

Ps: a gitter would be really cool :+1: 

Thanks for the great work

**Comment by agrosner** [comment]
First part is already fixed. Second part is not fixable. This lib is compiled against API 23. Not sure how there's conflicts as gradle takes the newer one. You can fix this by forcing a specific version, or changing the `resolutionStrategy`
