### ISSUE TITLE
BaseMigration migration database is empty

### ISSUE THREAD

**Issue by TheWhiteLlama** [Raizlabs/DBFlow#521]
Another issue I currently have with migrations is, that the database passed to the migrate method (BaseMigration) while migrating to a new data base version seems to be empty except for the locale meta data.

Is this a bug in beta 3.0 or how can I write a migration that will select data from the existing tables, do some complex computations and update/insert the data?

**Comment by agrosner** [comment]
https://github.com/Raizlabs/DBFlow/blob/develop/usage2/Migrations.md :)
