### ISSUE TITLE
Does DBFlow support FTS3/4?

### ISSUE THREAD

**Issue by epool** [Raizlabs/DBFlow#522]
I want to implement an android search view, in the [documentation](http://developer.android.com/intl/es/guide/topics/search/search-dialog.html) they mentioned `FTS3 (full text search)` rather than a `LIKE` query. In the [sqlite documentation](http://www.sqlite.org/fts3.html) I see that is necessary to create `virtual tables` for this and now I am not sure how to do this with `DBFlow` or if it is possible.

Thanks!

**Comment by agrosner** [comment]
Not currently. Virtual tables are not supported yet.

**Comment by agrosner** [comment]
Answer will be no, for now.
