### ISSUE TITLE
JodaTime with DBFlow?

### ISSUE THREAD

**Issue by ZkHaider** [Raizlabs/DBFlow#527]
I want to setup a column with type `DateTime`. Correct me if I'm wrong but from my understanding DBFlow does not support Joda Time's `DateTime`? therefore would I have to create a `TypeConverter` in order for this to work?

Something like:

    @Table(database = SampleDB.class)
    public class SampleTable {

        //.....
        
        @Column(typeConverter = DateTimeConverter.class)
        private DateTime mDateTime;

        //.....
    }

    public final class DateTimeConverter extends TypeConverter<String, DateTime> {

        @Override
        public String getDBValue(DateTime model) {
            if (model != null) {
                return model.toString();
            }

            return null;
        }

        @Override
        public DateTime getModelValue(String data) {
            if (data != null) {
                return DateTime.parse(data);
            }

            return null;
        }

    }

This would save the `DateTime` as a `String` though, does DBFlow automatically convert String's that match dates into SQL DATETIME?

**Comment by agrosner** [comment]
Yes you need to create A custom `TypeConverter` which is very simple. To the second question, no you have to do it a manually and in this case it translates the type of the `Column` from `DateTime` to `String`, meaning it will be of type `TEXT`.
