### ISSUE TITLE
Migration code from docs doesn't compile

### ISSUE THREAD

**Issue by mlatu** [Raizlabs/DBFlow#529]
Hi
I'm trying to add a column. My migration file looks like this:

```java
	@Migration(version = 1030, databaseName = Db.NAME)
	public class Migration1030 extends AlterTableMigration<OrderData> {


	    public Migration1030(Class<OrderData> table) {
		   super(table);
	    }

	    @Override
	    public void onPreMigrate() {
		   addColumn(String.class, "shipping_info_holder");
	    }

	}
```

And I get this error in generated class:

	Error:(19, 24) error: constructor Migration1030 in class Migration1030 cannot be applied to given types;
	required: Class<OrderData>
	found: no arguments
	reason: actual and formal argument lists differ in length

**Comment by nithdi** [comment]
Changing the constructor should fix the problem:

```Java
public Migration1030() {
    super(OrderData.class);
}
```

**Comment by agrosner** [comment]
thank you @nithdi , was going to say the same thing.

**Comment by agrosner** [comment]
added a note in `master` docs.
