### ISSUE TITLE
Allow Model classes Private fields if getters and setters are specified

### ISSUE THREAD

**Issue by agrosner** [Raizlabs/DBFlow#53]
To remove limitation of public/package private fields, we can add this feature to look for a getter and setter for a Model field if its private. 

Target Release: 1.5.0 or later

**Comment by bboyfeiyu** [comment]
that means DBFlow just access the public/protected fields right now ? It generate some Adapter under the model's package, and then access the model field directly, is it that right ?

**Comment by agrosner** [comment]
Correct.  If you know how to manipulate byte code or have any better ideas that would be awesome.

**Comment by bboyfeiyu** [comment]
I have no idea better then yours, your work is awesome, thanks for sharing!

**Comment by damson** [comment]
How would you use bytecode in this case ?

DAGNET Damien

**Comment by agrosner** [comment]
@damson not sure. Isn't that what Project Lombok does? It hacks the generated class system somehow. that would be nice if something like this could be done.

**Comment by bboyfeiyu** [comment]
hi,agroaner, when DBFlow load the generated ModelAdapter  class ?  Can you share with me ? thanks

**Comment by agrosner** [comment]
going to close this one. rather be consistent
