### ISSUE TITLE
Docs migration adding table

### ISSUE THREAD

**Issue by surajm097** [Raizlabs/DBFlow#532]
I need to add a new table to the database. I am using version 2.2.1. The only changes i could find in the docs are about adding a column or updating columns. Can somebody help me with this? Thanks!

**Comment by agrosner** [comment]
There isn't one really. You need to run the SQL code manually pretty much.

**Comment by agrosner** [comment]
To add a new table, you need to increment the database version to get it to show up. It will run the creation on upgrade of DB

**Comment by raymondlukanta** [comment]
So, if I want to add a new table, I don't need to write the migration script? Am I correct?

**Comment by agrosner** [comment]
no script needed to add table. You just increment database version and the creation of the table will get run.
