### ISSUE TITLE
Error on code generated for @ModelContainer for boolean fields.

### ISSUE THREAD

**Issue by epool** [Raizlabs/DBFlow#536]
I am getting an `Error:(93, 61) error: incompatible types: int cannot be converted to boolean` error. My `Book` model has a `private boolean isAvailable` column with `public boolean getIsAvailable() {...}` as getter method.

And the generated code with error is:

    @Override
    public final void bindToInsertStatement(SQLiteStatement statement, ModelContainer<Book, ?> modelContainer, int start) {
      String modelContainerid = modelContainer.getStringValue("id");
      if (modelContainerid != null) {
        statement.bindString(1 + start, modelContainerid);
      } else {
        statement.bindNull(1 + start);
      }
      String modelContainertitle = modelContainer.getStringValue("title");
      if (modelContainertitle != null) {
        statement.bindString(2 + start, modelContainertitle);
      } else {
        statement.bindNull(2 + start);
      }
      String modelContainerauthor = modelContainer.getStringValue("author");
      if (modelContainerauthor != null) {
        statement.bindString(3 + start, modelContainerauthor);
      } else {
        statement.bindNull(3 + start);
      }
      statement.bindLong(4 + start, modelContainer.getIntValue("releaseYear"));
      statement.bindLong(5 + start, modelContainer.getIntValue("numberOfCopies"));
      statement.bindLong(6 + start, modelContainer.getIntValue("numberOfDaysAllowedForBorrowing"));
      statement.bindLong(7 + start, modelContainer.getIntValue("isAvailable") ? 1 : 0); // <==== Here is the error
    }

Maybe a solution could be change `modelContainer.getIntValue("isAvailable")` by `modelContainer.getBoolValue("isAvailable")`. I wish I could fix this issue, but I have no experience with code generation libraries like this.

**Comment by agrosner** [comment]
as a stopgap if you cannot update to a newer commit before beta2, change it from `private` to package private.

**Comment by agrosner** [comment]
fixed in `develop`
