### ISSUE TITLE
Prepackaged databases not loading in 3.0

### ISSUE THREAD

**Issue by marwfair** [Raizlabs/DBFlow#537]
Prepackaged databases worked fine before I updated. Now my prepackaged database isn't being loaded. I have the .db file in /src/main/assets and have verified that the data is in there correctly. I just pulled the db from the app, then prepackaged it in. If I copy the db to the databases directory myself on app launch, it works fine. Thanks!

**Comment by agrosner** [comment]
is this still happening?

**Comment by agrosner** [comment]
reopen if its still happening.
