### ISSUE TITLE
NullPointer when the variable name of the `ForeignKeyContainer` differs from the assigned column name in the database.

### ISSUE THREAD

**Issue by ArashJavan** [Raizlabs/DBFlow#539]
I have the following models:

Project:
https://github.com/ArashJavan/Vitalife/tree/dbflow

``` java
@Database(name = VitalifeDB.NAME, version = VitalifeDB.VERSION, foreignKeysSupported = true)
public class VitalifeDB {
    public static final String NAME = "usda";
    public static final int VERSION = 1;
}
```
``` java
@ModelContainer
@Table(database = VitalifeDB.class, name = "food")
public class Food extends BaseModel {

    @Column(name = "id")
    @PrimaryKey(autoincrement = false)
    int mId;

    @Column(name = "food_group_id")
    @ForeignKey(saveForeignKeyModel = false)
    ForeignKeyContainer<FoodGroup> mFoodGrp;

    @Column(name = "long_desc")
    String mLongDesc;

    public FoodGroup getFoodGrp() {
        return mFoodGrp.load();
    }
}
```

``` java
@ModelContainer
@Table(database = VitalifeDB.class, name = "food_group")
public class FoodGroup extends BaseModel {
    @Column(name = "id")
    @PrimaryKey(autoincrement = false)
    int mId;

    @Column(name = "name")
    String mName;

    List<Food> mFoods;

    @OneToMany(methods = {OneToMany.Method.SAVE, OneToMany.Method.DELETE}, variableName = "mFoods")
    public List<Food> getFoods() {
        if (mFoods == null || mFoods.isEmpty()) {
            mFoods = SQLite.select()
                    .from(Food.class)
                    .where(Food_Table.mFoodGrp_id.eq(mId))
                    .queryList();
        }
        return mFoods;
    }
}
```
#### Fragment Code 
``` java
         List<Food> foods = SQLite.select().from(Food.class).queryList();
         Food food = foods.get(0);
         FoodGroup fg = food.getFoodGrp();
```
###### Food-Table:

| id | foo_group_id | long_desc |
| ----------------- | ------------- | -----------| 
| 1000 | 100 | Cheese |

CREATE TABLE `food` (
  id int PRIMARY KEY NOT NULL,
  food_group_id int REFERENCES food_group(id) NOT NULL,
  long_desc text NOT NULL DEFAULT '',
)

###### Food-Group-Table:
| id | name |
| ----------------- | ------------- | 
| 100 | Dairy and Egg |

CREATE TABLE `food_group` (
  id int PRIMARY KEY NOT NULL,
  name text NOT NULL
)

### Problem:
After Loading all Foods from the Food-Table as follow:
``` java
         List<Food> foods = SQLite.select().from(Food.class).queryList();
```
Food-Group is not loaded and is NULL.
``` java
         Food food = foods.get(0);  
         FoodGroup fg = food.getFoodGrp();  // NULLPointer, cause mFoodGrp is NULL-Pointer
 ```

#### assumption:
after looking inside the DBFlow genrated Files:

###### 1. __Food_Table.java__

Here is **_mFoodGrp_id_** listed as Column-Name, which should be actually food_group_id,  as
it is so in the Database.

``` java
  public static BaseProperty getProperty(String columnName) {
    columnName = QueryBuilder.quoteIfNeeded(columnName);
    switch (columnName)  {
      case "`id`":  {
        return id;
      }
      case "mFoodGrp_id":  {   // Should be actually food_group_id
        return mFoodGrp_id;
      }
      case "`long_desc`":  {
        return long_desc;
      } 
....
```

###### 2. __Food_Adapter.java__

In this file you see a lot of usage of **_mFoodGrp_id_** in SQL-Statments, which IMHO should be actually **_food_group_id_** 
``` java

  @Override
  public final String getCompiledStatementQuery() {
    return "INSERT INTO `food`(`id`,`mFoodGrp_id`,`long_desc`,`short_desc`,`common_name`,`manufac_name`,`nitrogen_factor`,`protein_factor`,`fat_factor`,`calorie_factor`) VALUES (?,?,?,?,?,?,?,?,?,?)";
  }
```

#### Conclusion

I think naming a foreign key column has no effect (respectively has just limited effects ) in the generated files.

``` java
    @Column(name = "food_group_id")
    @ForeignKey(saveForeignKeyModel = false)
    ForeignKeyContainer<FoodGroup> mFoodGrp;
```
__--> Will not search for food_group_id-Column but rather for _mFoodGrp_id_ !__

**Comment by agrosner** [comment]
yeah, so `ForeignKey` objects should not reference a `name` for it's `Column`. Instead you will need to manually specify `@ForeignKeyReference` and then you can specify it's specific, local column name in that reference. It's more of a bug that it doesn't cause an error.

**Comment by agrosner** [comment]
The column name by default of a `ForeignKey` is `{variableName}_{foreignKeyColumnName}`
