### ISSUE TITLE
Explain project setup better

### ISSUE THREAD

**Issue by gmilette** [Raizlabs/DBFlow#54]
It is not clear how to edit my gradle build files to include this project.

This statement needs clarification I think:
"Add the library to the project-level build.gradle, using the apt plugin and the AARLinkSources plugin::"

Please provide a sample project level and module level gradle.build files that use the library

**Comment by agrosner** [comment]
@gmilette makes sense...I will add this ASAP! thank you.

**Comment by gnuhel** [comment]
@agrosner I also wanted to use DBFlow in my project but failed to integrate DBFlow with the description. It seems like https://raw.github.com/Raizlabs/maven-releases/master/releases is NOT FOUND

Would be great to have a working example. Thank you for your effort.

**Comment by agrosner** [comment]
Add this line to your app's build.gradle: 

```groovy

repositories {
        maven { url "https://raw.github.com/Raizlabs/maven-releases/master/releases" }
  }

```

**Comment by gnuhel** [comment]
@agrosner It works, thank you.
