### ISSUE TITLE
Deleting Tables from database.

### ISSUE THREAD

**Issue by saurabhghewari** [Raizlabs/DBFlow#541]
Hi I am working on the Social Education app in which i have used DBflow version 1.8.0. I am facing the issue in deleting all tables when user switches the stream or user is changed. Some times tables get deleted and some time not. I have followed the delete query statement as per the documentation. 
This is the query I fire to delete all the tables from the database 
Delete.tables(MyTable1.class, MyTable2.class); but this does not work properly. Some how tables are persisted in db with previous stream data and new stream data which leads to confusion of streams.

Help will be greatly appreciated.

**Comment by agrosner** [comment]
I would recommend updating to DBFlow 3.0.0-beta1. Not sure how they are persisted, or what you mean but deleting only clears the row from the tables, if you have something else adding rows to the table on another thread, it'll add rows to the table. If you dive into the source, all it's doing is calling `SQLiteDatabase.execSQL("DELETE FROM `Table`")`

**Comment by saurabhghewari** [comment]
ok, Thank you for precious reply. Will update to 3.0.0-beta1 and test.
