### ISSUE TITLE
Adapter does not follow boolean setter convention

### ISSUE THREAD

**Issue by andhie** [Raizlabs/DBFlow#543]
For a boolean value, the Java convention would be `isEnabled()` and `setEnabled()`.  The generated `*_Adapter` uses `setIsEnabled` when `useIsForPrivateBooleans = true`
e.g. `model.setIsEnabled(cursor.getInt(indexisEnabled) == 1 ? true : false);`

using the below libs
```gradle
compile 'com.github.Raizlabs.DBFlow:dbflow-core:3.0.0-beta1'
compile 'com.github.Raizlabs.DBFlow:dbflow:3.0.0-beta1'
```

**Comment by agrosner** [comment]
fixed in `develop`. look out for it in 3.0.0

**Comment by agrosner** [comment]
`useBooleanGetterSetters()`
