### ISSUE TITLE
Many to many, is it possible?

### ISSUE THREAD

**Issue by dbruce1990** [Raizlabs/DBFlow#549]
Hi, I'm messing around with DBFlow for the first time, trying to create a super simple chat app. In the app a `UserModel` belongs to many `ConversationModels`. In order for users to communicate, `ConversationModel` would have many `Users` therefor creating a many-to-many relationship no? Apologies if I'm mistaken and wasting somebodies time asking, but is there a way to implement...I can't seem to find anything with a google search. Or, maybe it isn't possible and it's a bad practice, or what's going on here?

**Comment by YSDC** [comment]
I'm able to do it, yes, you simply need to create a join table yourself (UserConversationModels) that contains ForeignKeyContainer to your two classes.
Then with a single query (two join) you can get the list of the conversationsModels for your users or the opposite

**Comment by YSDC** [comment]
If you are still blocked I can give you an example

**Comment by dbruce1990** [comment]
An example would be cool.

**Comment by marwfair** [comment]
@dbruce1990, I would do something like @YSDC suggested. Create a UserConversationModel that contains the ids of your UserModel and ids from your ConversationsModels.

UserModel
-----------------
id:
1
2
3

ConversationModel
-----------------------------
id:
1
2
3

UserConversationModel
----------------------------------
UserId:        ConversationId:
1                  1
1                  2
2                  1
2                  3
3                  1
3                  2
3                  3

Then to see what all Users belong to a particular Conversation, just do a query on your UserConversationModel to get your User ids.

**Comment by agrosner** [comment]
its in `develop`. add the annotation `@ManyToMany` and it will generate the join/association table for you! :)

**Comment by agrosner** [comment]
its in the readme docs (https://github.com/Raizlabs/DBFlow/blob/develop/usage/DBStructure.md#many-to-many-source-gen)

**Comment by abiemann** [comment]
https://github.com/agrosner/DBFlowDocs/blob/master/Relationships.md
