### ISSUE TITLE
Allow TypeConverters to be registered manually

### ISSUE THREAD

**Issue by NightlyNexus** [Raizlabs/DBFlow#562]
I have a `TypeConverter` that has a dependency on another object, but there seems to be no way to handle this case, as TypeAdapters are created by generated code.
For example, I'd like to be able to register this kind of converter:
```
final class GsonFooConverter extends TypeConverter<String, Foo> {
  private final Gson gson;

  GsonFooConverter(Gson gson) {
    this.gson = gson;
  }

  @Override public String getDBValue(Foo model) {
    return gson.toJson(model);
  }

  @Override public Foo getModelValue(String data) {
    return gson.fromJson(data, Foo.class);
  }
}
```

**Comment by agrosner** [comment]
I would suggest having a singleton with the `Gson` object that you access via static calls within the converter. or if you need to change something just add a setter method that you call when you call `FlowManager.getTypeConverterForClass()`
