### ISSUE TITLE
Invalid sql generated if primary autoincrement key is not first column in class 

### ISSUE THREAD

**Issue by grennis** [Raizlabs/DBFlow#563]
Invalid SQL (extra comma) generated like this:

    INSERT INTO `Test`(`value1`,,`value2`) VALUES (?,,?)

For a class like this

    @Table(database = TestDatabase.class)
    public static class Test extends BaseModel {
        @Column
        String value1;

        @Column
        @PrimaryKey(autoincrement =  true)
        int id;

        @Column
        String value2;
    }

Which is not a big deal except that it also is triggered by this more subtle and more common case:

    public static class Base extends BaseModel {
        @Column
        String value1;
    }

    @Table(database = TestDatabase.class)
    public static class Derived extends Base {
        @Column
        @PrimaryKey(autoincrement =  true)
        int id;

        @Column
        String value2;
    }

**Comment by agrosner** [comment]
fixed in `develop`
