### ISSUE TITLE
Example unit test with robolectric

### ISSUE THREAD

**Issue by nambv** [Raizlabs/DBFlow#569]
Hi @agrosner , can you show an example how to write unit test for DBFlow?
Thanks so much!

**Comment by GrahamRogers** [comment]
I created a `TestRule` that looks like this:

    public class DBFlow implements TestRule {
    
      public static DBFlow create() {
        return new DBFlow();
      }

      private DBFlow() {}

      @Override
      public Statement apply(final Statement base, Description description) {
      return new Statement() {
        @Override
        public void evaluate() throws Throwable {
          FlowManager.init(RuntimeEnvironment.application);
          try {
            base.evaluate();
          } finally {
            FlowManager.destroy();
          }
        }
      }
    }

Then in your test class:

    @RunWith(RobolectricTestRunner)
    @Config(manifest = "path to manifest")
    public class MyTest {

      @Rule public final DBFlow dbflow = DBFlow.create();
    }

I found that you have to specify a manifest otherwise you get errors about an assets directory not being found.

**Comment by agrosner** [comment]
@GrahamRogers that is a pretty cool solution. I guess I have not delved too far into robolectric to realize you can do rules

**Comment by agrosner** [comment]
unless thats from another library?

**Comment by GrahamRogers** [comment]
It's a standard part of JUnit 4 https://github.com/junit-team/junit/wiki/Rules.

**Comment by agrosner** [comment]
all tests are now robolectric unit tests. :)

**Comment by PingForward** [comment]
@nambv @agrosner @GrahamRogers can anyone provide a full samples?
I try to implement tests like in dbflow-tests but in one app module no luck... Getting ConcurrentModificationException on Delete.tables

**Comment by farkerhaiku** [comment]
seconded, the sample app should provide an example of a robolectric test imo.
