### ISSUE TITLE
something wrong when use query in statement

### ISSUE THREAD

**Issue by answer1989** [Raizlabs/DBFlow#570]
I want to query from a table where some integer field not in some range, but it doesn't work.
When the statement is below, the field ROWNUM is integer field.
```java
ArrayList<Integer> rows = new ArrayList<>(entity.size());
rows.add(1);
rows.add(2);
rows.add(4);
new Select().from(News.class).where(Condition.column(News$Table.ROWNUM).notIn(rows));
```
it dosen't work, but the statement below is work.

```java
new Select().from(News.class).where(Condition.column(News$Table.ROWNUM).notIn(1,2,4));
```

**Comment by agrosner** [comment]
the support for `Iterable` in `in()` and `notIn` has not been added back to 3.0.0+ yet. I will get it back in. For now you'll have to use `toArray()`

**Comment by agrosner** [comment]
fixed in `develop`

**Comment by answer1989** [comment]
thank you, it works
