### ISSUE TITLE
Model Caching doesn't appear to be working

### ISSUE THREAD

**Issue by relevante** [Raizlabs/DBFlow#571]
I have a model for which I just enabled caching. My Table annotation looks like:

`@Table(database = SensorDatabase.class, cachingEnabled = true, cacheSize = 100)`

But when I run this block of code:

```java
        CSSensor a = new Select()
                .from(CSSensor.class)
                .where(CSSensor_Table.deviceID.is(999999))
                .querySingle();

        CSSensor b = new Select()
                .from(CSSensor.class)
                .where(CSSensor_Table.deviceID.is(999999))
                .querySingle();

        Log.i("CSSensor", "a: " + a + " " + a.id + ", b: " + b + " " + b.id);
```

I get this in response:

`01-20 14:00:15.682 11335-11335/? I/CSSensor: a: com.cousins_sears.beaconthermometer.sensor.CSSensor@41f4c0e0 3, b: com.cousins_sears.beaconthermometer.sensor.CSSensor@41f4f390 3`

Two different objects with the same id (id is PrimaryKey).

Any ideas?

**Comment by agrosner** [comment]
are you saving the first object, or is this inserted manually somewhere? also is `deviceID` a single primary key?

**Comment by relevante** [comment]
They already exist in the table. id is the single auto incrementing primary
key. deviceID is just a regular field that I'm querying against. I don't
have to query specifically on the primary key for caching to work, do I?

**Comment by agrosner** [comment]
yes. model caching only works on primary keys.

**Comment by agrosner** [comment]
otherwise it's just creating a new instance. if you need the specific object the field must be a primary key as well, and in that case you'll need to define a :
```
@MultiCacheField
    public static IMultiKeyCacheConverter<String> multiKeyCacheModel = new IMultiKeyCacheConverter<String>() {

        @Override
        @NonNull
        public String getCachingKey(@NonNull Object[] values) {
            return "(" + values[0] + "," + values[1] + ")";
        }
    };
```

replace with your type of caching key you want. but what itll do is merge the values of two keys to create a key for mapping.
