### ISSUE TITLE
add call to suppress spurious warnings

### ISSUE THREAD

**Issue by kenkyee** [Raizlabs/DBFlow#572]
These show up a lot in the build output:
Users/kenyee/work/SiteSpect-Android/sitespect-sdk/build/generated/source/apt/runtime/release/com/sitespect/sdk/db/models/CampaignData$Adapter.java:38: warning: [unchecked] unchecked call to getDBValue(ModelClass) as a member of the raw type TypeConverter
    Object modellastViewedTime = FlowManager.getTypeConverterForClass(java.util.Date.class).getDBValue(model.getLastViewedTime());

but seem harmless...maybe preface this line with:
@SuppressWarnings (value="unchecked")

in the generator?

**Comment by agrosner** [comment]
@kenkyee what version of the library are you using? If you're using 3.0.0-beta1+, it doesn't render it as an object, rather it casts and assigns it to a variable within the Adapter so it need not do many lookups.

**Comment by agrosner** [comment]
for example:
```
private final DateConverter global_typeConverterDateConverter;

  public AModel_Adapter(DatabaseHolder holder) {
    global_typeConverterDateConverter = (DateConverter) holder.getTypeConverterForClass(Date.class);
  }

 @Override
  public final void bindToInsertValues(ContentValues values, AModel model) {
    Long refdate = model.date != null ? global_typeConverterDateConverter.getDBValue((java.util.Date) model.date) : null;
    if (refdate != null) {
      values.put("`date`", refdate);
    } else {
      values.putNull("`date`");
    }
  }

  @Override
  public final void bindToInsertStatement(DatabaseStatement statement, AModel model, int start) {
    Long refdate = model.date != null ? global_typeConverterDateConverter.getDBValue((java.util.Date) model.date) : null;
    if (refdate != null) {
      statement.bindLong(4 + start, refdate);
    } else {
      statement.bindNull(4 + start);
    }
  }
```
Left out other generated code, but I fundamentally changed how code is written in these generated classes.

**Comment by kenkyee** [comment]
2.2.1...too close to end and too much other stuff to finish before release to switch to 3.0 :-(
I'll try switching to 3.0 if we have time though.

**Comment by agrosner** [comment]
yeah i would because 3.0.0 supports DBFlow in multiple modules. If this is an SDK or anything of sorts, it will not allow you to use DBFlow in your own application without updating to 3.0.0.

**Comment by agrosner** [comment]
3.0.0-beta2 will be released within day or two I hope

**Comment by kenkyee** [comment]
hmm...good point about modules and SDK/app dual DBFlow usage..thanks :-)

**Comment by agrosner** [comment]
you're welcome.
