### ISSUE TITLE
Error:Could not find com.github.Raizlabs.DBFlow:dbflow-processor:3.0.0-beta2

### ISSUE THREAD

**Issue by TheLester** [Raizlabs/DBFlow#575]
I have set jCenter() and all apt plugin. 

`Error:Could not find com.github.Raizlabs.DBFlow:dbflow-processor:3.0.0-beta2.
Searched in the following locations:
    https://jcenter.bintray.com/com/github/Raizlabs/DBFlow/dbflow-processor/3.0.0-beta2/dbflow-processor-3.0.0-beta2.pom
    https://jcenter.bintray.com/com/github/Raizlabs/DBFlow/dbflow-processor/3.0.0-beta2/dbflow-processor-3.0.0-beta2.jar
    https://maven.fabric.io/public/com/github/Raizlabs/DBFlow/dbflow-processor/3.0.0-beta2/dbflow-processor-3.0.0-beta2.pom
    https://maven.fabric.io/public/com/github/Raizlabs/DBFlow/dbflow-processor/3.0.0-beta2/dbflow-processor-3.0.0-beta2.jar
    file:/home/dmitriy/soft/android-sdk-linux/extras/android/m2repository/com/github/Raizlabs/DBFlow/dbflow-processor/3.0.0-beta2/dbflow-processor-3.0.0-beta2.pom
    file:/home/dmitriy/soft/android-sdk-linux/extras/android/m2repository/com/github/Raizlabs/DBFlow/dbflow-processor/3.0.0-beta2/dbflow-processor-3.0.0-beta2.jar
    file:/home/dmitriy/soft/android-sdk-linux/extras/google/m2repository/com/github/Raizlabs/DBFlow/dbflow-processor/3.0.0-beta2/dbflow-processor-3.0.0-beta2.pom
    file:/home/dmitriy/soft/android-sdk-linux/extras/google/m2repository/com/github/Raizlabs/DBFlow/dbflow-processor/3.0.0-beta2/dbflow-processor-3.0.0-beta2.jar
Required by:
    CardStorage:app:unspecified`

**Comment by agrosner** [comment]
you're not including jitpack https://github.com/Raizlabs/DBFlow#including-in-your-project

**Comment by TheLester** [comment]
I have set maven { url "https://jitpack.io" } in my app.gradle

**Comment by agrosner** [comment]
if it was set as a repository, the logs here would show it.

**Comment by nikhilB93** [comment]
I am also facing same issue
below is my projectName.gradle file partly snapshot:

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

still getting same eeror as mentioned by @TheLester above...
any solutions??
Please Help...

**Comment by TheLester** [comment]
@nikhilB93  I moved 
`repositories {
    maven {
        url "https://jitpack.io"
    }
}` from buildscript{} to root of the app.gradle.

**Comment by nikhilB93** [comment]
@TheLester 
thanks for reply ...
but I did not get you ...
what you mean by  "root of the app.gradle"...?
may be it is a stupid question as I am new to android development world...

**Comment by TheLester** [comment]
@nikhilB93  Just put `repositories { maven { url "https://jitpack.io" } }` to app.gradle, in my case it was like this :`buildscript{repositories { maven { url "https://jitpack.io" } }}`

**Comment by nikhilB93** [comment]
@TheLester  thanks again ...
Its working fine...!!!
