### ISSUE TITLE
ConditionGroup question

### ISSUE THREAD

**Issue by marwfair** [Raizlabs/DBFlow#579]
I'm trying to create a query with multiple and/or grouped statements. Something like:

(pseudocode)
```
Select.from(Car.class).where(Car_Table.make.is("Ford")
    .and(Car_Table.model.is("Focus"))
    .and(((Car_Table.year.isGreaterThan(2000).and(Car_Table.year.isLessThan(2010)))
        .or(Car_Table.year.is(2015).and(Car_Table.color.is("blue"))))))
    .queryList();
```

So:
make = Ford AND
model = Focus AND
((year > 2000 and year < 2010) OR (year = 2015 and color = blue))

I'm guessing ConditionGroup is what I am looking for, but the docs didn't help out much and the example is invalid.
```
SQLite.select()
    .from(MyTable.class)
    .where(ConditionGroup.clause()
      .and(MyTable_Table.someColumn.is("SomeValue")
      .or(MyTable_Table.anotherColumn.is("ThisValue"));
```

Any help would be appreciated!

**Comment by dwaynehoy** [comment]
ConditionGroup doesn't appear to be working correctly at the moment, and doesn't group statements as expected. However based on the below bit of documentation ConditionGroup is what you need to provide the required grouping

Documentation
https://github.com/Raizlabs/DBFlow/blob/master/usage/Migration3Guide.md#replacement-of-the-conditionquerybuilder

ConditionGroup issue 
https://github.com/Raizlabs/DBFlow/issues/597

**Comment by agrosner** [comment]
fixed in `develop`. each `ConditionGroup.clause()` will use parenthesis when included in other `SQLCondition` statements but that can be turned on or off via `setUseParenthesis()`
