### ISSUE TITLE
How to get absolute path to db?

### ISSUE THREAD

**Issue by MGasztold** [Raizlabs/DBFlow#580]
Previously in version `3.0.0-beta1` i was able to do the following thing:

```
SQLiteDatabase db = FlowManager.getDatabase(NAME).getWritableDatabase();
String srcPath=db.getPath();
```

Now in the `3.0.0-beta2` i do not have access to SQLiteDatabase getter. How can I get the path of the db now ?

**Comment by arturonaredo** [comment]
For documentation.. FlowManager.getContext().getDatabasePath(AppDatabase.NAME) :)
