### ISSUE TITLE
sqlcipher question

### ISSUE THREAD

**Issue by Jackoder** [Raizlabs/DBFlow#586]
In your library, SQLCipher gets the secret like this:

``` java
public class SQLCipherHelperImpl extends SQLCipherOpenHelper {

    public SQLCipherHelperImpl(BaseDatabaseDefinition databaseDefinition, DatabaseHelperListener listener) {
        super(databaseDefinition, listener);
    }

    @Override
    protected String getCipherSecret() {
        return "dbflow-rules";
    }
}
```

If I want to modify the secret, how to solve the problems like database migration?

I have added SQLCipher support to [ActiveAndroid](https://github.com/pardom/ActiveAndroid). And I manage the secret by a xml file like this:

``` xml
<databases>
    <database version="1" password="***1"/>
    <database version="2" password="***2"/>
    ...
</databases>
```

I think this is not a good way, do you have any idea?

**Comment by agrosner** [comment]
hm thats a great point. I did not know something like this existed. I will have to look into it a little more. How does SQLCipher work, does the secret change between database versions?

**Comment by Jackoder** [comment]
There would be OK, if the secret doesn't change. 
After doing some practice, I found out a database can just have one secret, we cannot decrypt it by a historical or newly secret. So we should decrypt the database by the current secret and encrypt it by the new one, if we want to change the secret. SQLCipher work checklist like this:
- current secret is empty, just encrypt it by the new secret
- current secret is not empty and new one is empty, just decrypt it by current secret
- current secret and new one is not empty, decrypt it by current secret and encrypt by the new one

SQLCipher may throw exception if not follow the step the. So, there will be something concerned to manage the secert. I'm happy to share my idea with u :)

**Comment by agrosner** [comment]
not going to support it.
