### ISSUE TITLE
Keep version 2.2.1 and tag it

### ISSUE THREAD

**Issue by fabiendem** [Raizlabs/DBFlow#588]
Hi,

I am using the version 2.2.1 and don't have the time yet to migrate to the version 3.x.x.
Could you please tag the latest commit for 2.2.1? (in case I want to look at the source code).
Also, will you keep this version on jCenter? Would be useful in case someone else pulls my code.
Will migrate when I can :/

Thanks!

**Comment by fabiendem** [comment]
Found the proper commit:
https://github.com/Raizlabs/DBFlow/tree/319585975bc8480e7896be4319bf0d3c7be788f6

**Comment by ivanquirino** [comment]
We need tags to browse docs. I am using 2.2.1 at the moment.

**Comment by fabiendem** [comment]
Pretty sure you can browse the doc from there: https://github.com/Raizlabs/DBFlow/tree/319585975bc8480e7896be4319bf0d3c7be788f6/usage

**Comment by agrosner** [comment]
since pending 3.0.0, I will close this.
