### ISSUE TITLE
inserting row with value in primary key, value will be changed!

### ISSUE THREAD

**Issue by wintersandroid** [Raizlabs/DBFlow#59]
I have successfully implemented DBFlow in one of my apps, completly replacing the old database code - good work.. I wrote a process to copy the data from the old one to the new objects.

I had a crash at startup, rather weird, then found when inserting the old data into the new dbflow table, the "_id" primary key value was being changed..

Thus original table
_id  value
1     a
2    b 
4    c

became
_id 
1
2
3

which caused failures in lookups to this table from other tables. I had to implement a lookup list oldvalue->newvalue..

I would have expected that a value inserted into the primary key row will be kept, only updated if no value has been put in..

:)

**Comment by agrosner** [comment]
@wintersandroid can you give me more insight into the issue. Such as the ```Model``` class you are inserting and what code your'e using to do so. It would help me. Thanks!

**Comment by wintersandroid** [comment]
Ok, so I have table defined...

```java
@Table
//@ContainerAdapter
public class AccountTable extends BaseModel {

  @Column(columnType = Column.PRIMARY_KEY_AUTO_INCREMENT)
  public long _id;

  @Column
  public String name;

  @Column
  public String username;

  @Column
  public String password;

  @Column
  public String provider;

  @Column
  public Date lastUpdate;

  public String getUsername()
  {
    return AccountInformation.decode(username);
  }

}
```

and it is written to using some basic code..
```java
public void convertAccounts() {
//    new Delete().from(AccountTable.class).query();
    Cursor cursor = databaseHelper.db().query(DatabaseHelper.ACCOUNT_DATABASE_TABLE, null, null, null, null, null, DatabaseHelper.KEY_ROWID);
    try {
      cursor.moveToFirst();
      while (!cursor.isAfterLast()) {
        AccountTable tableRow = new AccountTable();
        long id = cursor.getInt(cursor.getColumnIndex(DatabaseHelper.KEY_ROWID));
        tableRow._id = id;
        tableRow.username = cursor.getString(cursor.getColumnIndex(DatabaseHelper.KEY_USERNAME));
        tableRow.password = cursor.getString(cursor.getColumnIndex(DatabaseHelper.KEY_PASSWORD));
        tableRow.provider = cursor.getString(cursor.getColumnIndex(DatabaseHelper.KEY_PROVIDER));
        Time lastupdate = new Time();
        lastupdate.parse(cursor.getString(cursor.getColumnIndex(DatabaseHelper.KEY_LAST_UPDATE)));
        tableRow.lastUpdate = new Date(lastupdate.toMillis(false));
        tableRow.name =  tableRow.getUsername();
        tableRow.save(false);

        if(tableRow._id != id)
        {
          accountIdChanges.put(id,tableRow._id);
        }

        cursor.moveToNext();
      }
    } finally {
      cursor.close();
    }
  }
```

**Comment by agrosner** [comment]
@wintersandroid its an autoincrementing primary key. that value will not be kept when inserting data.

**Comment by agrosner** [comment]
@wintersandroid just curious too, why you need to copy old data into new...wouldn't it make sense to keep it in the existing table?

**Comment by wintersandroid** [comment]
I was not sure how to do that to start with, the documentation was not clear on how to keep existing tables and columns with the new classes.. I thought it best to start with fresh tables and namespace, probably a daft idea.. But I like the ORM model..

**Comment by agrosner** [comment]
Its ok @wintersandroid. This library just wraps around the native calls to the database, so if the existing DB and table is there, you can use it!
