### ISSUE TITLE
Cannot insert model with no properties except autoincrement PK

### ISSUE THREAD

**Issue by john-latham** [Raizlabs/DBFlow#590]
dbflow_version = "3.0.0-beta2"

Error:
android.database.sqlite.SQLiteException: near ")": syntax error (code 1): , while compiling: INSERT INTO `Session`() VALUES ()

Model extract:
```
    @PrimaryKey(autoincrement = true)
    long id;

    // needs to be accessible for DELETE
    List<Photo> photos;...

    @OneToMany(methods = {OneToMany.Method.SAVE, OneToMany.Method.DELETE}, variableName = "photos")
    public List<Photo> getPhotos() {
```

Why would I want a model class with no properties? Because it exists as the parent of a one-many relationship.

Workaround is to add an extra dummy column.

**Comment by agrosner** [comment]
that would make sense. if you're using a `Model` class as a table, you need to make it a table. Can you provide more info on the `Model`?

**Comment by agrosner** [comment]
single field is now placed as NULL in db.
