### ISSUE TITLE
com.raizlabs.android.dbflow.structure.BaseModel missing w/ DBFlow 3.x?

### ISSUE THREAD

**Issue by kenkyee** [Raizlabs/DBFlow#594]
Hoping someone has seen this because I'm pretty baffled by this.

The entire com.raizlabs.android.dbflow.structure.* namespace is missing.
I'm migrating a 2.x project to 3.x.

Relevant parts of gradle file are:

`````
allprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
        }
    }

    repositories {
        maven { url "https://jitpack.io" }
    }
}


apt {
    arguments {
        // SiteSpect DBFlow module name
        targetModuleName 'SiteSpect'
    }
}

def dbflow_version = "3.0.0-beta2"

dependencies {
    apt "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
`````

**Comment by agrosner** [comment]
@kenkyee  you might need to fix other compile issues. there are a lot of changes to code gen, structure, and annotations. What ive learned is that the android gradle plugin hides errors from annotation processors pretty often

**Comment by agrosner** [comment]
if you need help, slack me on Android united when you can with questions :)

**Comment by whitewolf21** [comment]
I am also facing this same issue
