### ISSUE TITLE
[Kotlin] Table null needs to define at least one column

### ISSUE THREAD

**Issue by leisim** [Raizlabs/DBFlow#596]
I get the following error while building my app (it is written in Kotlin). But when I delete the build folder in Android Studio before building everything is fine.

When I build the next time, I get the error again.

```
:myapp:compileReleaseJavaWithJavac
Error:*==========*
  Table null needs to define at least one column
  *==========*
Error:*==========*
  Table null needs to define at least one primary key
  *==========*
Error:*==========*
  Table null needs to define at least one column
  *==========*
Error:*==========*
  Table null needs to define at least one primary key
  *==========*

Warning:The following options were not recognized by any processor: '[kapt.kotlin.generated]'
Error:Execution failed for task ':myapp:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.```

**Comment by Amagi82** [comment]
Same issue here. Haven't found a workaround yet besides using java for the database classes

**Comment by agrosner** [comment]
this is a Kotlin issue, that apparently is not solved. (http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/). I tested this and found writing it in Kotlin appears to work in the IDE, but when you reference those generated java files from DBFlow in Kotlin, the Kotlin compiler cannot find the generated classes.

**Comment by ubuntudroid** [comment]
Is it one of these Kotlin issues causing the problems? [KT-10352](https://youtrack.jetbrains.com/issue/KT-10352), [KT-8733](https://youtrack.jetbrains.com/issue/KT-8733), [KT-7277](https://youtrack.jetbrains.com/issue/KT-7277)

Some of them are already closed, although the issues still persist. Doesn't seem they are actively working on that at the moment. What a shame. The model classes looked so clean when defined in Kotlin. Back to verbose Java.

**Comment by agrosner** [comment]
@ubuntudroid no this is a different kind of issue (https://youtrack.jetbrains.com/issue/KT-11978). closing this b/c this is not dbflow issue.
