### ISSUE TITLE
[3.0.0-beta2] ConditionGroup not adding grouping parentheses

### ISSUE THREAD

**Issue by dwaynehoy** [Raizlabs/DBFlow#597]
It appears that GroupCondition is not providing grouping parentheses, as is expected from the documentation found here:
https://github.com/Raizlabs/DBFlow/blob/master/usage/Migration3Guide.md#replacement-of-the-conditionquerybuilder

The following code (which is not logic, just used to highlight the issue)

```java
String testQuery = new Select()
                .from(PoiCategoriesFilterPreference.class)
                .where(PoiCategoriesFilterPreference_Table.siteKey.eq("somevalue"))
                .and(
                        ConditionGroup.clause()
                                .and(PoiCategoriesFilterPreference_Table.siteKey.eq("somevalue"))
                        .or(PoiCategoriesFilterPreference_Table.siteKey.eq("thisvalue"))
                ).getQuery();
```

results in the following query
```sql
SELECT * 
FROM   `poicategoriesfilterpreference` 
WHERE  `sitekey` = 'somevalue' 
       AND `sitekey` = 'somevalue' 
        OR `sitekey` = 'thisvalue' 
```

the expected query is
```sql
SELECT * 
FROM   `poicategoriesfilterpreference` 
WHERE  `sitekey` = 'somevalue' 
       AND ( `sitekey` = 'somevalue' 
              OR `sitekey` = 'thisvalue' ) 
```

**Comment by agrosner** [comment]
fixed in `develop` can be controlled on or off when included in other `ConditonGroup` or general condition statements via `setUseParenthesis()`. By default they will be added when the list of conditions are greater than 0.
