### ISSUE TITLE
How to use it with already exists Database

### ISSUE THREAD

**Issue by iballan** [Raizlabs/DBFlow#598]
I fill my database myself, and i put it into **assets ** folder in android studio project, then i connect to the database using this library [https://github.com/jgilfelt/android-sqlite-asset-helper](https://github.com/jgilfelt/android-sqlite-asset-helper)

So how can I use DBFlow to connect to assets prefilled sqlite database ?

It is so important and it should be added to the official guide i think

**Comment by astrobread** [comment]
I haven't used that library before, but it looks like implementing it could be similar to this example:
https://github.com/Raizlabs/DBFlow/blob/master/usage/SQLCipherSupport.md

The difference is that instead of connecting the database to a SQLCipherOpenHelper, you'd connect it to a SQLiteAssetHelper from that outside library.

**Comment by iballan** [comment]
@astrobread  The idea of library is not doing anything but connecting to SQLite database file that already prefilled and put in assets folder. so without using the library can we connect to database sqlite set in the assets folder?

**Comment by agrosner** [comment]
https://github.com/Raizlabs/DBFlow/blob/master/usage/DBStructure.md#prepackaged-databases

Its same idea, but we do is copy over the DB for the first time on creation of the application. Once that occurs the DB in assets is no longer used/referenced.

**Comment by TheHemantKaushik** [comment]
@agrosner If I want to delete old database before DBFlow check for the first time execution. Please let me know fi that is possible.

**Why I want to delete?**
I have added some new data & columns to tables and put it to app assets.

**Comment by agrosner** [comment]
`context.deleteDatabase(databasefileName)`
