### ISSUE TITLE
jcenter is no avaiable.

### ISSUE THREAD

**Issue by jiqimaogou** [Raizlabs/DBFlow#599]
jcenter is no avaiable.    when I add  “maven { url "https://jitpack.io" }”, it resolve dependency so slow. can you push the lib in the jcenter?

**Comment by agrosner** [comment]
it is slow the first time whenever there's a new commit to build. once that happens, it should be fast. If you're still having trouble it might be gradle - you can turn on offline mode in studio to speed it up.

**Comment by Pedramrn** [comment]
Adding custom maven url in repositories section increases the sync time massively.
I am aware of the offline mode but that's not the case, most of the times, I need to download new releases or some other libraries which I don't have in my .gradle cache.
