### ISSUE TITLE
Add support for RxJava

### ISSUE THREAD

**Issue by davidschreiber** [Raizlabs/DBFlow#6]
Hi there!

DBFlow looks like a promising library! I will definitely give it a shot with one of my next projects. One thing I immediately found when looking into the querying wiki pages was the lacking support for RxJava and observables. As this is an emerging (and booming) pattern in Android development I would really love to see support for this!

Anybody interested too?

**Comment by digitalbuddha** [comment]
One of the reasons to add rx support is to allow easier combining of data.  Currently we use an rx observable network client, if we want to do things like load first from db/cache then load from network, it would be helpful to have a consistent stream interface to combine.  Amazing library btw

**Comment by Rainer-Lang** [comment]
@digitalbuddha Same here. Switching to rx - and it works really fine - only DBFlow could not really good integrated. I also want to have that DBFlow adds rx.

**Comment by Rainer-Lang** [comment]
btw is DBFlow thread-safe?

**Comment by Rainer-Lang** [comment]
@agrosner Is it possible to make upcoming DBFlow 3 rx-compatible?

Anyone else want this feature? I hope I'm not alone...

**Comment by kaeawc** [comment]
I'd definitely make use of it in my projects in order to remove complexity. We currently use RxJava with Retrofit to insert/update data and register FlowContentObserver where needed, but this means we have two types of concurrency going on in the app. I used to also use Otto or EventBus, but neither is needed with RxJava. The community behind RxJava is tackling Android concurrency issues (including issues with testing concurrent operations), which means they can have better focus and catch more bugs. I would hope there would be little or no performance advantage to either, if there was it would mean one is creating more overhead than the other.

**Comment by agrosner** [comment]
@Rainer-Lang What does it mean to be RX-Compatible, how is DBFlow not so right now? To add the dependency on RX-Android means a whole bunch of stuff pulled into the library that it does not need. If we're talking about something like "DBFlow-RXSupport" module, then that is certainly possible.

**Comment by Rainer-Lang** [comment]
@agrosner @kaeawc @davidschreiber @digitalbuddha @AndroidGecko Maybe it's possible to have a discussion what is really needed in DBFlow for rxjava. Maybe we should discuss this here or maybe anywhere else.
To be honest, I'm new to rxjava, but with it I can do really useful things really easy. I'm still learning. I like to combine the operators. I also use Retrofit and like @davidschreiber mentioned it is possible to use it with or without rxjava. Maybe this could be the same (future) way for DBFlow.
Like I wrote, I'm new - so please - this is an appeal to the adepts of rxjava, write what should be done and help all of us.

**Comment by kaeawc** [comment]
@agrosner An RxJava module would work. Wouldn't want to bloat the core of DBFlow.

**Comment by Rainer-Lang** [comment]
Any news on this?

@agrosner Could you please reopen this issue?

**Comment by agrosner** [comment]
@Rainer-Lang I am not sure of how it exactly works. Never actually used it before. That said, if you wanted to 
A: Put in a PR to `develop` with a new module named `dbflow-rx` or something with some example code of how this would work.
B. Create a sample lib or project that references DBFlow but with new classes that would help with RX.
That would be a great help. I only have limited time and something like this is not high on my priority list. Currently that includes: significantly improving the annotation processor module, improving DBFlow syntax, power charge the documentation, and lastly update and add more unit tests for edge cases as needed.

**Comment by AndreiD** [comment]
+1

**Comment by ajaykumarmeher** [comment]
+1

**Comment by perchi** [comment]
+1

**Comment by ebonet** [comment]
+1

**Comment by Rainer-Lang** [comment]
I changed to StorIO and it's great. 
I liked DBFlow.

**Comment by garmax1** [comment]
+1

**Comment by nateridderman** [comment]
+1. I don't like how TransactionManager posts results on the UI Thread. Rxjava would help this. I also don't like how SaveModelTransaction doesn't return a result. How do I know when the tx is done?

**Comment by therajanmaurya** [comment]
+1

**Comment by Ivru** [comment]
+1

**Comment by firasalmanna** [comment]
+1

**Comment by mlykotom** [comment]
+1

**Comment by michalbujalski** [comment]
+1

**Comment by aimanbaharum** [comment]
This is awesome. I'm sorry I should've use the emoji but what the hell.

**Comment by roadhouse-dev** [comment]
I've created a RxJava wrapper for DBFlow here, at some point I'll look at merging it into DBFlow https://github.com/roadhouse-dev/RxDbflow

**Comment by dwaynehoy** [comment]
I've created a RxJava wrapper for DBFlow here, give it was created as a Roadhouse library I'm still working through permission to merge it with DBFlow https://github.com/roadhouse-dev/RxDbflow

**Comment by michalbujalski** [comment]
Looks promising.

**Comment by jettbow** [comment]
+1

**Comment by RoRoche** [comment]
+1

**Comment by elsennov** [comment]
+1

**Comment by agrosner** [comment]
I have started work on this if anyone wants to contribute: https://github.com/Raizlabs/DBFlow/tree/feature/agrosner/RX/dbflow-rx/src/main/java/com/raizlabs/android/dbflow/rx
Also any feedback you have would be helpful!

**Comment by agrosner** [comment]
in `4.0.0-beta6`
