### ISSUE TITLE
ContentUtils.buildUri is impossible to use without ambiguity

### ISSUE THREAD

**Issue by TastyPi** [Raizlabs/DBFlow#600]
There are two overloads of `ContentUtils.buildUri`:

    ContentUtils.buildUri(String, String...)

    ContentUtils.buildUri(String, String, String...)

The only non-ambiguous call to this method is when passing a single `String` argument or wrapping the varargs in an array. Could you rename one of the methods to allow calling them without the ambiguity problem?

**Comment by agrosner** [comment]
in `develop`
