### ISSUE TITLE
Foreign key on primary key column

### ISSUE THREAD

**Issue by hilljh82** [Raizlabs/DBFlow#602]
Hi,

I have rows in two separate tables that have a one-to-one relationship with a row in a common table. A scenario that replicates the problem is representing inheritance in a SQL database. Instead of having a single table for all types in the hierarchy, you have base tables that have the common columns. Then, you have subtables that define the columns specific to the subtype. Both the base and subtable reference each other via the primary key in the base table. The primary key of the subtable is also a foreign key to the common base table.

The generated code that does reference the _id type of the column. Instead, it tries to perform equality on the model object of the foreign/primary key. To replicate the problem, just add a ```ForeignKey``` definition to a ```PimaryKey``` column.

Here is the error produced confidential information removed:

```
Foo_Adapter.java:121: error: no suitable method found for eq(Bar)
    return ConditionGroup.clause().and(Foo_Table.campaign.eq(model.bar));
                                                                         ^
    method BaseProperty.eq(ITypeConditional) is not applicable
      (argument mismatch; Campaign cannot be converted to ITypeConditional)
    method BaseProperty.eq(BaseModelQueriable) is not applicable
      (argument mismatch; Campaign cannot be converted to BaseModelQueriable)
    method Property.eq(String) is not applicable
      (argument mismatch; Bar cannot be converted to String)
```

It seems that the code generator just needs to call the _id attribute on the primary key object to resolve the compilation error. In other words:

```java
Foo_Table.campaign.eq(model.bar._id)
```

**Comment by hilljh82** [comment]
@agrosner I have resolved the problem in my fork of the repo. Basically, the code generation failed if the a primary key was also a foreign key, and the foreign was a model and not a model container. I refactored the code for the ```ColumnDefinition``` class such that the ```getPropertyComparisonAccessStatement()``` does not know about the ```ForeignKeyColumnDefinition``` as this is a bad design and tightly couples the code.

I have also implemented a new type of ```ForeignKey``` called ```ExternalForeignKey``` that is designed to emulate foreign key references across databases. This will become important now that we have module support in DBFlow. I have many use cases where this is needed. I will be adding the ```ExternalForeignKey``` on a separate issue/pull-request from this fix.

**Comment by GrahamRogers** [comment]
@hilljh82 I'd be interested in seeing your fork, I'd like to use a composite foreign key as a primary key and am getting the same error. I can't see it listed on your GitHub profile, could you create a pull request for it?

**Comment by agrosner** [comment]
wow this seems like a complex kind of table. lol can you send over example tables so I can add them to tests and figure out the best solution for this that will work?

**Comment by agrosner** [comment]
technically you could run into a @Primary key thats a model that references another model primary key, that happens N times. What I need to decide is how far to go and where should it be limited - or if such limitation should be necessary.

**Comment by GrahamRogers** [comment]
It's not that complex, we just have a table with a composite primary key that wants a one-to-many relationship with another table, e.g.

    @Table(database = MyDatabase.class)
    public class A extends BaseModel {

      @PrimaryKey
      long key1;

      @PrimaryKey
      long key2;
    }

    @Table(database = MyDatabase.class)
    public B extends BaseModel {

      @PrimaryKey
      @ForeignKey
      A a;

      @PrimaryKey
      long keyB;
    }

It looks like it's been fixed by https://github.com/Raizlabs/DBFlow/commit/16f9489f907b5c8c6979bb1478e23b4e067386b4 through, so that's cool! Feel free to close this bug, any idea when you'll be making a release which includes the fix?

**Comment by agrosner** [comment]
I fixed this in `develop` I believe yesterday. Here is a test class I am using:
```
@ModelContainer
@Table(database = TestDatabase.class)
public class ForeignAsPrimaryModel extends BaseModel {

    @PrimaryKey
    long id;

    @ForeignKey
    @PrimaryKey
    TestModel1 testModel1;

    @ForeignKey
    @PrimaryKey
    BoxedModel boxedModel;

    @ForeignKey
    @PrimaryKey
    ForeignKeyContainer<BoxedModel> boxedModelForeignKeyContainer;
}
```

works for both foreign key containers and regular models as primary and foreign keys.

**Comment by agrosner** [comment]
3.0.0-beta3 will have this fix in there or you can grab the 10 digit commit hash of latest in develop if wish not to live on the bleeding edge.

**Comment by GrahamRogers** [comment]
That test class doesn't match my issue which was that the foreign model has a composite primary key, both `TestModel1` and `BoxedModel` have a single field annotated with `PrimaryKey`. I believe your fix also fixes my case, but to be sure could you add something like this:

    @ModelContainer
    @Table(database = TestDatabase.class)
    public class CompositePrimaryKeyModel extends BaseModel {

        @PrimaryKey
        long key1;

        @PrimaryKey
        long key2;
    }

    @ModelContainer
    @Table(database = TestDatabase.class)
    public class ForeignAsPrimaryModel extends BaseModel {

        ...

        @ForeignKey
        @PrimaryKey
        CompositePrimaryKeyModel compositePrimaryKeyModel;
     }

**Comment by hilljh82** [comment]
So, is it safe to close this issue?!
