### ISSUE TITLE
Delete of Model triggers ContentObserver event with wrong sql condition

### ISSUE THREAD

**Issue by simplysoft** [Raizlabs/DBFlow#605]
The offending line at
https://github.com/Raizlabs/DBFlow/blob/develop/dbflow/src/main/java/com/raizlabs/android/dbflow/sql/SqlUtils.java#L386
reset the primary ID of the model to 0, and then dispatches a content observer change event with the wrong (reset) primary ID

Switching those two lines should fix the problem

**Comment by agrosner** [comment]
fixed in `develop`.
