### ISSUE TITLE
How can i a queen of an Ant in an ant list loaded via queryList()

### ISSUE THREAD

**Issue by DiegoTavares** [Raizlabs/DBFlow#608]
When I load a list of ants using Select().from(Ant.class).where().queryList() , the relative queen is not loaded. The queenForeignKeyContainer is null.

**Comment by agrosner** [comment]
Is the queen saved to the DB? and are each Ant associated with a `Queen`?

**Comment by DiegoTavares** [comment]
I've found the problem. The query was loading the queen correctly, but there were another problem in my code. Thanks.
