### ISSUE TITLE
Any way to Insert via model in migration?

### ISSUE THREAD

**Issue by calrsom** [Raizlabs/DBFlow#609]
Hi.

I am trying to insert data into the database as part of migration 0 to migrate from another database we were using.  Is there any way to do this using a model object?

I tried the naïve approach of just creating and saving a model object, but I get "java.lang.IllegalStateException: getDatabase called recursively".

I'm assuming I need to interact with the DatabaseWrapper passed into migrate(), but I'm not sure how to insert a model using that.  model.getModelAdapter().getInsertStatementQuery() is protected.

Am I really forced into doing a SQLite.insert() ? Seems fragile to hard-code column names.

Either way, InsertTableMigration might be nice.

 - Matthew Carlson

**Comment by agrosner** [comment]
This is def one of the things I am looking at improving. Currently statements and objects don't allow you to specify the database object when doing a migration. I need to evaluate this, but for now you will need to do it manually.

**Comment by calrsom** [comment]
Ok. Good to know.  Thanks for replying so quick.  I'll go with the manual approach; the transition between app versions should be fairly short-lived in my case, so I'm guessing it won't be a problem.

**Comment by agrosner** [comment]
sounds good. I did add ability to specify the `DatabaseWrapper` in most if not all queries of the DB, so you can take advantage of the wrapper classes for it if need be.
