### ISSUE TITLE
Poor Migrations documentation

### ISSUE THREAD

**Issue by AlokBansal8** [Raizlabs/DBFlow#614]
Documentation assumes a lot.
1. Is 2 the old version or new version in "@Migration(version = 2)"?
2. How will I write a single code which will take care of all migrations whether 2 to 4 or 1 to 4 or 3 to 4?
3. How will I use BaseMigration class?
4. How to add table?
5. How to remove a column?

Take a look at [Realm documentation](https://realm.io/docs/java/latest/#migrations). It is far more friendly.
Please improve the documentation. And also include a proper and much detailed page for foreign key relationships.

**Comment by agrosner** [comment]
@AlokBansal8 
1. "2" is the version its run at.
2. There is no single code to take care of multiple migrations - migrations are executed at each version of the DB until the DB catches up with the upgraded version. So a migration should only get you from one version to another, not multiple.
3. `BaseMigration` is a convenience for `Migration` interface.

```
@Migration(version = 2, database = AppDatabase.class)
public class Migration1 extends BaseMigration {

    @Override
    public void migrate(DatabaseWrapper database) {

    }
}
```
4. Tables are added automatically when upgrading DB version if new table is detected.
5. You cannot remove columns in SQLite, that's a limitation of SQLite. (http://stackoverflow.com/a/8442173)

Yeah, I am one person running this library, while Realm is managed by many developers. I can only do so much and rely on contributions from the community, so if you wish to make it better :)

**Comment by agrosner** [comment]
I admit the documentation is lacking, it helps to have others with different set of eyes contribute to it.

**Comment by agrosner** [comment]
https://github.com/Raizlabs/DBFlow/blob/develop/usage2/Migrations.md :) hope this helps.

**Comment by zmorris** [comment]
Old link was expired, here is the new link:

https://agrosner.gitbooks.io/dbflow/content/Migrations.html
