### ISSUE TITLE
Rename database filename?

### ISSUE THREAD

**Issue by StarWar** [Raizlabs/DBFlow#618]
I have a existing database with the app name without ".db" extension at the end. Now the database created with DBFlow adds ".db" extension at the end. How can specify that it shouldn't add the ".db" extension.
If It can't do that then please tell me a way so that I can rename my existing database to have a ".db" extension before DBFlow creates the database.

Thanks,

**Comment by agrosner** [comment]
You need to do a copy over to the new file name before calling `FlowManager.getDatabase(..).getWritableDatabase()`. so this would need to happen on app launch only once. You can probably use a preference to store this or some other fashion. But doing that should give you the result you need.
