### ISSUE TITLE
DBFlow <-> Ollie

### ISSUE THREAD

**Issue by Rainer-Lang** [Raizlabs/DBFlow#62]
http://www.raizlabs.com/dev/2015/02/go-dbflow-fastest-android-orm-database-library/?utm_source=Android+Weekly&utm_campaign=95a2a28863-Android_Weekly_139&utm_medium=email&utm_term=0_4eb677ad19-95a2a28863-337888185

Why not compare DBFlow with Ollie?
ActiveAndroid is really old. Ollie is the improved follower.

**Comment by agrosner** [comment]
@Rainer-Lang I chose ones that were more established and not in "beta", one's that I am familiar with, and ones with more than 500 stars on Github. That said, the Ollie creator as reached out to me for the performance test and I sent it over to him. It resides [here](https://github.com/Raizlabs/AndroidDatabaseLibraryComparison)
