### ISSUE TITLE
[feature proposal] Add support for association tables for many-to-many relationships.

### ISSUE THREAD

**Issue by arriolac** [Raizlabs/DBFlow#620]
Say a `Parent` object can have multiple `Child` objects and vice versa. These relationships can be stored in an association table, say `ParentToChild`, where when a relationship is specified you can provide it a secondary (association) table. This solution is similar to [Python SQLAlchemy](http://docs.sqlalchemy.org/en/latest/orm/basic_relationships.html#many-to-many).

The solution can look like:

```
@Table(database = Database.class) public class Parent {
    @PrimaryKey int id;
    @Secondary(table = ParentToChild.class) List<Child> children;
}

@Table(database = Database.class) public class Child {
   @PrimaryKey int id;
}

@Table(database = Database.class) public class ParentToChild {
    @ForeignKey Parent parent;
    @ForeignKey Child child;
}
```

**Comment by agrosner** [comment]
you mean something to the tune of:
```java
@Table(database = TestDatabase.class)
@ManyToMany(referencedTable = TestModel1.class)
public class ManyToManyModel extends BaseModel {

    @PrimaryKey
    String name;

    @PrimaryKey
    int id;

    @Column
    char anotherColumn;
}
```
with other table:
```java
@Table(database = TestDatabase.class)
public class TestModel1 extends BaseModel {
    @Column
    @PrimaryKey
    String name;
}
```

which outputs a `Model` class as:
```java
/**
 * This is generated code. Please do not modify */
@Table(
    database = TestDatabase.class
)
public final class ManyToManyModel_TestModel1 extends BaseModel {
  @PrimaryKey(
      autoincrement = true
  )
  long _id;

  @ForeignKey
  TestModel1 testModel1;

  @ForeignKey
  ManyToManyModel manyToManyModel;

  public final long getId() {
    return _id;
  }

  public final TestModel1 getTestModel1() {
    return testModel1;
  }

  public final void setTestModel1(TestModel1 param) {
    testModel1 = param;
  }

  public final ManyToManyModel getManyToManyModel() {
    return manyToManyModel;
  }

  public final void setManyToManyModel(ManyToManyModel param) {
    manyToManyModel = param;
  }
}
```
?

**Comment by agrosner** [comment]
that feature is near-ready for placing into `develop`. It will generate many to many associations for you as tables.

**Comment by arriolac** [comment]
Interesting, yes, this is exactly what I'm describing. Didn't realize you were working on this in `develop` simultaneously. :)

Looking forward to the docs, happy to give a review on it if needed.

**Comment by arriolac** [comment]
Btw, I don't think the generated table needs an autogenerated primary key. The foreign key pairs can both be primary keys.

**Comment by arriolac** [comment]
Sorry one more follow-up... 

Should there be a field accessible in `TestModel1`, say `List<ManyToManyModel>`? This way, you can save/delete/load the corresponding `ManyToManyModel` relationships of a `TestModel1` instance (similar to `@OneToMany` annotation).

So it could be:

```
@Table(database = TestDatabase.class)
public class TestModel1 extends BaseModel {
    @Column @PrimaryKey String name;
    @ManyToMany(associationTable = ManyToManyModel_TestModel1.class) List<ManyToManyModel> models;
}
```

Thoughts?
