### ISSUE TITLE
Create Iterable backed by Cursor (FlowQueryList for ContentProviders)

### ISSUE THREAD

**Issue by GrahamRogers** [Raizlabs/DBFlow#621]
We always access our database via a ContentProvider and it would be great if there was something like `FlowCursorList` for interacting with a ContentProvider.

Proposal: Create a very simple class that takes a `Cursor` and a `Class<? extends Model>` and has a restricted set of methods to `FlowCursorList` (i.e. anything that involves `refresh` is probably out). It should ideally support caching as well.

**Comment by GrahamRogers** [comment]
If you're happy with my proposal I'm happy to give it a go myself.

**Comment by agrosner** [comment]
It would be great to hear what the benefits would be here. `ContentProvider` has a set of `abstract` methods that DBFlow overrides and generates implementation for you. Deviating from that too far wouldn't be ideal

**Comment by agrosner** [comment]
```
Proposal: Create a very simple class that takes a Cursor and a Class<? extends Model> and has a restricted set of methods to FlowCursorList (i.e. anything that involves refresh is probably out). It should ideally support caching as well.
```
This could be used as a `CursorResult` class intro'd in 3.0.0-beta6

**Comment by agrosner** [comment]
Technically constructor is not public, but its package private.

**Comment by GrahamRogers** [comment]
The reason I want this is so that I can easily convert a query from a content provider into an rxjava `Observable`. The easiest way to do this would be with an `Iterable` backed by the `Cursor`, which is what `FlowCursorList` does. I don't want to create an ArrayList or something form the data since I will be manipulating it and having to load everything into memory first is wasteful.

`CursorResult` doesn't seem to have a way to get a list without loading them all into memory. Having `CursorResult` implement `Iterable` where `Iterator`s called the `Cursor` directly would be perfect.

Here's a code sample of what I currently do (using lambda notation):

    Observable.using(
            () -> getStuffFromContentProvider(),
            (cursor) -> Observable.from(new IterableCursor(cursor, instanceAdapter)),
            (cursor) -> cursor.close())
        .subscribeOn(Schedulers.io())
        .flatMap(someFacyTransformation)
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(showDataInRecyclerView)

Where `IterableCursor` simply iterates over the `Cursor` and gets objects from each row using an `InstanceAdapter`, similar to what `FlowCursorList` does. This solution works, but I think others would benefit from having something similar. Making `CursorResult` implement `Iterable` (without loading every row into memory first) and having a way to get one from a content provider would be perfect for my usage.

**Comment by agrosner** [comment]
so basically `FlowCursorList` is not an iterable, I think you're talking about `FlowQueryList` ?
Also, `CursorResult implement Iterable where Iterators called the Cursor directly would be perfect.` The `Iterable` method `Iterator<T> iterator();` on `FlowQueryList` loads all into memory, calling `iterator()` on the returned list.

**Comment by GrahamRogers** [comment]
I guess what I'm thinking of doesn't exist at all. My current solution is a custom class that implements `Iterable` and wraps a `Cursor`. It seems like something other people would want, hence this issue.

Perhaps adding a `Iterable<T> cursorBackedIterable()` method to `CursorResult` would make sense? It should of course have the caveat that the `CursorResult` needs to be closed once iterating has finished.

**Comment by agrosner** [comment]
in `develop`, use the `FlowCursorIterator` that allows you to iterate the `FlowQueryList` or `FlowCursorList`. if you use the `iterator()` method on either object it now uses that efficient class.
