### ISSUE TITLE
NullPointerException when running Gradle task compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by jdabrowski1337** [Raizlabs/DBFlow#623]
I'm having almost exactly the same issue as this one https://github.com/Raizlabs/DBFlow/issues/526#issuecomment-170304882

I was able to pinpoint where the issue occurs. It's in the file /dbflow/processor/definition/BaseDefinition.java, line 73
in the condition of this if block:
`if (!elementTypeName.isPrimitive()) { elementClassName = getElementClassName(element); }`

The exception thrown is nullPointerException which would suggest that the _elementTypeName_ variable is null at this point. It would be useful to display compiler error here to state which element caused the problem, as it is done with other problems of this type.

Below I'm attaching build stacktrace:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:compileDebugJavaWithJavac'.
> > java.lang.NullPointerException
> 
> * Try:
> Run with --info or --debug option to get more log output.
> 
> * Exception is:
> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
>         at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
>         at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
>         at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
>         at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
>         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
>         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
>         at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
>         at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
>         at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
>         at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
>         at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
>         at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
>         at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
>         at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
>         at org.gradle.internal.Factories$1.create(Factories.java:22)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
>         at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
>         at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
>         at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
>         at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
>         at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
>         at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
>         at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
>         at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
>         at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
>         at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
>         at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
>         at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
>         at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
>         at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
>         at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
>         at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
>         at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
>         at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
>         at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
>         at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
>         at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
>         at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
>         at org.gradle.launcher.Main.doAction(Main.java:33)
>         at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
>         at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
>         at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
>         at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
>         at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
>         at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
>         at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> Caused by: java.lang.RuntimeException: java.lang.NullPointerException
>         at com.sun.tools.javac.main.Main.compile(Main.java:469)
>         at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
>         at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:45)
>         at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
>         at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
>         at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
>         at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
>         at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
>         at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
>         at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
>         at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:139)
>         at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
>         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
>         ... 60 more
> Caused by: java.lang.NullPointerException
>         at com.raizlabs.android.dbflow.processor.definition.BaseDefinition.<init>(BaseDefinition.java:73)
>         at com.raizlabs.android.dbflow.processor.definition.method.DatabaseDefinition.<init>(DatabaseDefinition.java:71)
>         at com.raizlabs.android.dbflow.processor.handler.DatabaseHandler.onProcessElement(DatabaseHandler.java:48)
>         at com.raizlabs.android.dbflow.processor.handler.BaseContainerHandler.handle(BaseContainerHandler.java:23)
>         at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:276)
>         at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:100)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
>         at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
>         at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
>         at com.sun.tools.javac.main.Main.compile(Main.java:439)
>         ... 78 more

BUILD FAILED

**Comment by jdabrowski1337** [comment]
I was able to resolve this issue by trial and error.
I was using Retrofit library and for some reason the DBFlow tried to parse Retrofit annotations on an interface.

**Comment by gauravlucky** [comment]
@jdabrowski1337 - can you elaborate what did you do fix the above ? I am getting the same error. 
I'm also using RetroFit.

thanks

**Comment by jdabrowski1337** [comment]
@gauravlucky 
I just removed some redundant dependency in my build.gradle file. Can't remember which one.

Try to disable some dependencies one by one to find out which one is causing the problem, also try rebuilding the whole project.

Also make sure there are no other compiler errors in your files, because when processing annotations the annotation processor will throw NullPointerException, instead of a normal error message, when some other exception is not handled  properly, which I think is the case here.

Cheers

**Comment by grennis** [comment]
I updated retrofit from 2.0.0-beta2 to the 2.0 final version and suddenly started getting this error. (No other changes). Any advice exactly what the problem was here?

**Comment by grennis** [comment]
Just to update anyone else who ran into this issue: After updating retrofit/okhttp, you need to go in and manually clean up all your imports (in addition to whatever code changes are required) because the package names changed. you can't just rely on the compiler to show you the errors. After cleaning out the imports, the compiler worked. Not sure how dbflow fits into this picture, but it definitely does as I did not have this issue on any other project. The compiler freaks out if the imports are not right and just crashes.
