### ISSUE TITLE
Browse database records

### ISSUE THREAD

**Issue by filipemanuelofs** [Raizlabs/DBFlow#625]
Hi, 
I'm using a pre-populated database. As says in [tutorial](https://github.com/Raizlabs/DBFlow/blob/master/usage/DBStructure.md#prepackaged-databases), I put "app.db" in `src/main/assets/app.db`, but when I try browse them, continues without none record, even my code saying "_that record already exists_". 

Where can I see data being saved?

_Edit: I'm using real device, not emulated._

**Comment by filipemanuelofs** [comment]
> If you are using an actual device, you will not be able to see or access it from outside unless you root your phone.
> 
> If you are using the emulator, the DDMS view will let you navigate to it and pull it from there.

[Why SQLite Database not showing in File Explorer?](http://stackoverflow.com/a/11150168)

**Comment by fabiendem** [comment]
Stetho is the perfect tool for this: http://facebook.github.io/stetho/

**Comment by agrosner** [comment]
yeah if you place in assets as well, obviously it will not get modified. On launch the DB is copied into the internal app directory, so you have an extra DB floating around. This adds to app APK size, but helps you quickly populate your app with data.

**Comment by filipemanuelofs** [comment]
@fabiendem nice, thanks! 
@agrosner thanks again!
