### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Native method not found | DBFlow + SQLCipher 

### ISSUE THREAD

**Issue by MikeRzDev** [Raizlabs/DBFlow#630]
I have been trying to use DBFlow + SQLCipher as decribed on the tutorial but the app crashed with this error message : "java.lang.UnsatisfiedLinkError: Native method not found".  After some troubleshooting I finally discovered the answer, by adding this line you would fix this problem:

- net.sqlcipher.database.SQLiteDatabase.loadLibs(this);

I suppose the best place for this would be in "onCreate" method of Application Context ex:

```
public class AppContext extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        FlowManager.init(this);
        //required for using SQLCipher
        net.sqlcipher.database.SQLiteDatabase.loadLibs(this);
    }
```

Please if this line required to use SQLCipher with DBFlow, add this info on the tutorial, thank you!

**Comment by MikeRzDev** [comment]
well i have fixed the problem, dbflow automatically creates the database file if there is at least one insert in a table, but still there was the problem with the SQLCipher database, and the solution was hidden in the test cases. So please update the SQLCipher tutorial by adding a text that you must add this line before using SQLCipher DB 

net.sqlcipher.database.SQLiteDatabase.loadLibs(this);

I suppose the best place for this is on "onCreate" method of Application Context ex:

public class AppContext extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        FlowManager.init(this);

        //required for using SQLCipher
        net.sqlcipher.database.SQLiteDatabase.loadLibs(this);
    }

**Comment by agrosner** [comment]
Interesting, let me check my initialization.

**Comment by agrosner** [comment]
You're right, I should be there but appears not to be. Let me fix this ASAP.

**Comment by agrosner** [comment]
its on `develop` now.
