### ISSUE TITLE
[Feature] Multiple ManyToMany references

### ISSUE THREAD

**Issue by damson** [Raizlabs/DBFlow#632]
Ability to reference and auto-generate multiple many-to-many associations with the `@ManyToMany` annotation.

**Comment by agrosner** [comment]
I see so you want some that may have many `@ManyToMany` with different tables? If you need it for two, you can put the `@ManyToMany` in another table and point it back to the other table with it defined. But I can add this.

**Comment by arriolac** [comment]
+1 to this enhancement.

**Comment by mhemmings** [comment]
+1, most non-trivial databases require this :)

**Comment by agrosner** [comment]
fixed in `develop`. be out in next release!
