### ISSUE TITLE
eager loading @ManyToMany relationship

### ISSUE THREAD

**Issue by yellowapps** [Raizlabs/DBFlow#635]
I have a many to many relationship between recipes and ingredients.

Code currently looks like this in each class:

```
@Table(database = Db.class)
public class Recipe extends BaseModel {
```
```
@Table(database = Db.class)
@ManyToMany(referencedTable = Recipe.class)
public class Ingredient extends BaseModel {
```

How do I get a list of ingredients for a certain recipe?

And how to eagerly load all ingredients for each queried recipe. Is this possible?

**Comment by agrosner** [comment]
in the `Recipe` class you should define a `@OneToMany` method that lazy loads the relationship from the `Ingredient` table.

Something like this might suffice: 
```java
@OneToMany
public List<Ingredient> getIngredients() {
  if (ingredients == null) {
     List<Ingredient_Recipe> list = SQLite.select().from(Ingredient_Recipe.class)
          .where(columnName.eq(myId)).queryList();
     ingredients = new ArrayList<>();
     for (Ingredient_Recipe item: list) {
        ingredients.add(item.getIngredient());
     }
  }
  return ingredients;
} 
```
you need to ensure you are properly associating the two models with each other when saving them for the relation table to work.

**Comment by mhemmings** [comment]
@agrosner What do you mean by "properly saving"? I think I'm running into issues regarding not doing it properly!

In this case, would the Ingredients and Recipes be saved automatically, with a populated many-to-many table, or do you have to manually build each `Ingredient_Recipe` object and save each one?

**Comment by agrosner** [comment]
sorry for late reply. You have to manually build each one and save them. This just generates the table as a convenience for you.

**Comment by ivan-anic** [comment]
Hi @agrosner , a quick question. I am unsure whether I am or am I not doing this properly, but the items I save in the autogenerated table duplicate by its auto-incremented _id. Should I also be checking if the item already exists in the database, or is this an issue?

Let's say that in this case, I'm saving the items as following:

`
ingredients.forEach {
    val tableItem = Ingredient_Recipe()
    tableItem.ingredient = it
    tableItem.recipe = this
    tableItem.save()
`

If this is called n times for m ingredients, the following code returns n*m items. I could filter this, but I think that duplicate items shouldn't be saved at all.

`
val ingredients = Select().from(Ingredient_Recipe::class.java)
                .where((Ingredient_Recipe_Table.recipe_id.eq(id))) //recipe id from this class
                .queryList(wrapper)
`

Thanks in advance for your time.
