### ISSUE TITLE
Error while using @QueryModel with a TypeConverter<Blob, ?>

### ISSUE THREAD

**Issue by GrahamRogers** [Raizlabs/DBFlow#637]
This `@QueryModel`:

    @QueryModel(database = MyDatabase.class)
    public class DBFlowBug extends BaseQueryModel {

      public static class MyBlob {
        private final byte[] blob;

        public MyBlob(byte[] blob) {
          this.blob = blob;
        }
      }

      @com.raizlabs.android.dbflow.annotation.TypeConverter
      public static class MyTypeConverter extends TypeConverter<Blob, MyBlob> {

        @Override
        public Blob getDBValue(MyBlob model) {
          return new Blob(model.blob);
        }

        @Override
        public MyBlob getModelValue(Blob data) {
          return new MyBlob(data.getBlob());
        }
      }

      @Column
      MyBlob myBlob;
    }

Produces this error:

          model.myBlob = global_typeConverterMyTypeConverter.getModelValue((com.raizlabs.android.dbflow.data.Blob) new Blob(cursor.getBlob(indexmyBlob)));
                                                                                                                   ^
      symbol:   class Blob
      location: class DBFlowBug_QueryModelAdapter

The problem appears to be in `TypeConverterAccess#setColumnAccessString`:
    if (typeConverterDefinition.getDbTypeName().equals(ClassName.get(Blob.class))) {
        newCursorAccess = String.format("new Blob(%s)", newCursorAccess);
    }

Since this is just creating a String, javapoet doesn't add an import for it. The simple fix would be to fully qualify `Blob`, another fix would be to make `setColumnAccessString` return a `CodeBlock` so that it can keep track of imports.

**Comment by agrosner** [comment]
fixed in develop.
