### ISSUE TITLE
Generated ContentProviders are inflexible and UnSafeStringCondition is not a good alternative

### ISSUE THREAD

**Issue by GrahamRogers** [Raizlabs/DBFlow#639]
The generated providers should just use the SQLiteDatabase methods directly, as I have done in https://github.com/Raizlabs/DBFlow/pull/612. These methods already protect against SQL injection (it isn't just replacing ?s like `UnSafeStringCondition` does) and it avoids unnecessary of processing of strings.

**Comment by agrosner** [comment]
in `develop`
