### ISSUE TITLE
[beta3] Documentation unclear about @ForeignKey

### ISSUE THREAD

**Issue by DanChaltiel** [Raizlabs/DBFlow#640]
Hi,

In [GettingStarted.md](https://github.com/Raizlabs/DBFlow/blob/master/usage/GettingStarted.md#1-1-relationships), you declare your foreign key as a `Colony `(so as a BaseModel), but [just after](https://github.com/Raizlabs/DBFlow/blob/master/usage/GettingStarted.md#the-ant-table--1-to-many) you declare it as a `ForeignKeyContainer<Queen>`.

When should we be using a ForeignKeyContainer and why ?

Thanks.

PS: is there some sort of walkthrough to migrate from version 2 to version 3 ? I love the new version but have some new errors that I cannot figure out...

**Comment by agrosner** [comment]
in the [develop](https://github.com/Raizlabs/DBFlow/blob/develop/usage/GettingStarted.md#1-1-relationships) version ,I made this much clearer.
```
We use a ForeignKeyContainer in this instance, since we can have thousands of ants. For performance reasons this will "lazy-load" the relationship of the Queen and only run the query on the DB for the Queen when we call toModel(). With this said, in order to set the proper values on the ForeignKeyContainer you should call its generated method for converting itself into a ForeignKeyContainer via FlowManager.getContainerAdapter(Queen.class).toForeignKeyContainer(queen).
```

**Comment by agrosner** [comment]
this doc [migration3guide](https://github.com/Raizlabs/DBFlow/blob/master/usage/Migration3Guide.md) will help you on your way, but its not fully comprehensive and is a little outdated as we're in beta3 now. and beta4 will have some more changes.

**Comment by DanChaltiel** [comment]
Ah, sorry, I didn't understood the sentense (and I always understand your Colony example upside down :-s)
So we sould use a ForeignKeyContainer for "1 to many many" relationships and not for 1 to 1 or "1 to few", is that right ?

The migration guide is quite helping, thanks ! :-) 
Even if not complete, I think you should put it in your Getting Stared md.

**Comment by fabiendem** [comment]
@agrosner Do you plan to update the migration guide?

**Comment by agrosner** [comment]
most likely right before full release of 3.0.0 @fabiendem
