### ISSUE TITLE
Custom Data Loading after Multiple Joins

### ISSUE THREAD

**Issue by FarhanAhmad** [Raizlabs/DBFlow#642]
Hi, First of all, great work :) (Y)

My problem: I have 4 tables(**A,B,C,D**), and 2 of the tables(lets say **C,D**) have '**name**' column. In the final data model, i will get **_`C.name`_** but if _**`C.name`**_ is empty then check _**`D.name`**_ and put this info in final data set.

My solution: I think, i have to make a query and use something like this:

`Cursor cursor = query.query();`

and then loop through all the rows from cursor and make that empty comparison of 'name' for my self and load a model to return back. I also hope i don't have to do anything about the caching which i normally observe when fetching records.
Regards,

**Comment by GrahamRogers** [comment]
You could have a `QueryModel` view like this:

    @QueryModel(database = ...)
    public class Join extends BaseModelView<Join> {

      public static final String C_NAME = "cName";
      public static final String D_NAME = "dName";

      @Column(name = C_NAME)
      String cName;

      @Column(name = D_NAME)
      String dName;

      public String getName() {
        return Strings.isNullOrEmpty(cName) ? dName : cName;
      }
    }

Then do

    List<Join> joins = select(C_Table.name.as(Join.C_NAME), D_Table.name.as(Join.D_NAME))
        .from(C.class)
        .leftOuterJoin(D.class)
        .on(...)
        .queryCustomList(Join.class);

**Comment by FarhanAhmad** [comment]
Yes. That is working. Much thanx. Since we don't have a community like platform where help can be available i believe these questions will be of great help to other devs.
