### ISSUE TITLE
View Creation Order with Dependancy

### ISSUE THREAD

**Issue by brwskitime** [Raizlabs/DBFlow#644]
Just noticed something. I created 2 views and one depends on the other. If they get created in the wrong order you don't get your dependant views. For now I named them "view_01_xxxx" and "view_02_xxxx" to get both created. It's a hack though and certainly unstable going forward. Is there a better way?

**Comment by brwskitime** [comment]
On another machine, and my naming hack doesn't work, so not stable.

**Comment by agrosner** [comment]
Simple `priority = 1` should solve your issue. :) enjoy. in `develop`.
