### ISSUE TITLE
When Select, how to present A.*, B.id, MAX(`B`.`lastLogin`)?

### ISSUE THREAD

**Issue by kenneth2008** [Raizlabs/DBFlow#645]
Error message:
no such column: A.* (code 1): , while compiling: SELECT `A`.`*`,`B`.`account_no`,MAX(`B`.`lastLogin`)

Full SQL:
SELECT `A`.`*`,`B`.`account_no`,MAX(`B`.`lastLogin`) FROM `Account` AS `A` INNER JOIN `Account` AS `B` ON `A`.`account_no`=`B`.`account_no`

Code:
return SQLite
                .select(Method.ALL_PROPERTY.withTable(new NameAlias("A")),
                        Account_Table.account_no.withTable(new NameAlias("B")),
                        Method.max(Account_Table.lastLogin.withTable(new NameAlias("B"))))
                .from(Account.class).as("A")
                .innerJoin(Account.class).as("B")
                .on(Account_Table.account_no.withTable(new NameAlias("A")).eq(
                        Account_Table.account_no.withTable(new NameAlias("B"))))
                .querySingle();

**Comment by edison-jr** [comment]
You can solve with:

`Proprerty propertyAll = new Property(null, new NameAlias("*").tickName(false));`
` propertyAll.withTable(new NameAlias("A")):`

I have already proposed this change in `ALL_PROPERTY` constant to fix it.

**Comment by agrosner** [comment]
fixed in `develop`
