### ISSUE TITLE
Failed to build if model classes place in packages, started with capital letter

### ISSUE THREAD

**Issue by Rexee** [Raizlabs/DBFlow#646]
For example:
**not work:**
```
com.myapp.Model.Queen
```
_Build error: "error: cannot find symbol class Model"_  
**work:**
```
com.myapp.model.Queen
```

**Comment by agrosner** [comment]
I dont believe such a thing is looked upon in Java as standard and should always be lower to not conflict with inner class definitions...

**Comment by Rexee** [comment]
What standart? Can you give reference? Why if it's "standart" i still CAN create?
