### ISSUE TITLE
[Enhancement] Annotate field instance of Table for Many-To-Many relationships

### ISSUE THREAD

**Issue by arriolac** [Raizlabs/DBFlow#650]
Instead of:

```
@ManyToMany(referencedTable =  B.class)
public class A {
    @PrimaryKey @Unique @Column int id;
}

public class B {
    @PrimaryKey @Unique @Column int id;
}
```

The enhancement would be:

```
public class A {
    @PrimaryKey @Unique @Column int id;

    @ManyToMany() public List<B> getBs() {

    }
}

public class B {
    @PrimaryKey @Unique @Column int id;
}
```

This also would be a better pattern for implementing the enhancement mentioned in: https://github.com/Raizlabs/DBFlow/issues/632

**Comment by agrosner** [comment]
It would be, however this is not how the annotation works. All it does it conveniently generate a `Model` in which each table referenced `@ForeignKey` with an autoincrementing id column. You can change that to make each field the `@PrimaryKey` instead. You still need to manage the relationship yourself.

**Comment by agrosner** [comment]
I think what you're saying is that it should act like the `@OneToMany` annotation, where it conveniently will load, save, delete, etc the relationship of items?

**Comment by arriolac** [comment]
> It would be, however this is not how the annotation works. All it does it conveniently generate a Model in which each table referenced @ForeignKey with an autoincrementing id column. You can change that to make each field the @PrimaryKey instead. You still need to manage the relationship yourself.

Makes sense.

> I think what you're saying is that it should act like the @OneToMany annotation, where it conveniently will load, save, delete, etc the relationship of items?

Yes to this! Figuring out which association table to be used can be specified in the annotation.

**Comment by agrosner** [comment]
Original question is answered by a `@OneToMany` annotation.
