### ISSUE TITLE
[Enhancement] Support many-to-many on the same table

### ISSUE THREAD

**Issue by arriolac** [Raizlabs/DBFlow#651]
Add support for many-to-many against the same table. For example:

```
@Table(database = Database.class) @ManyToMany(referencedTable = User.class)
public class User {
    @PrimaryKey @Unique @Column int id;

    List<User> followers;  //Many-to-many
}
```

Currently the generated code will create a 2 foreignkey with the field names. A good enhancement would be to either: (1) append a number to the generated variable name as the default behavior, or (2) allow the relationship name to be specified.

**Comment by agrosner** [comment]
you want to create a `@ManyToMany` on itself? that's fine I can do that.

**Comment by agrosner** [comment]
now you can do that, also control the generated table class name if you dont like `User_User` hahahaha.

**Comment by arriolac** [comment]
Sweet! :100:
