### ISSUE TITLE
SQLite.insert does not work with blob columns

### ISSUE THREAD

**Issue by GrahamRogers** [Raizlabs/DBFlow#654]
If you have a `Blob` column in a table and try to do something like

    insert(MyTable.class).columnValues(MyTable_Table.blob.eq(new byte[] {...})).execute()

then rubbish gets inserted into the database because it executes a query like

    INSERT INTO `MyTable`(`blob`) VALUES ('[B@6fbf5db2')

I think the fix for this is to use `SQLiteDatabase.insert` and build the `ContentValue`s instead of trying to create an insert statement.

**Comment by gauravsak** [comment]
@GrahamRogers I was trying to investigate this issue but wasn't able to find the method

`eq(byte[])`

in any of the classes

`java.sql.Blob` OR `com.raizlabs.android.dbflow.data.Blob`.

Please post a bigger block of code so that it is easier to understand the context. Thanks.

**Comment by GrahamRogers** [comment]
Ah, I assumed it was there. Here's the actual code snippet I used (with some renaming):

    @SuppressWarnings("unchecked")
    private static <T extends Model> void insertOrFail(T model) {
      Class<T> modelClass = (Class<T>) model.getClass();
      ModelAdapter<T> adapter = FlowManager.getModelAdapter(modelClass);
      ContentValues values = new ContentValues();
      adapter.bindToContentValues(values, model);
      insert(modelClass).columnValues(values).or(ConflictAction.FAIL).execute();
    }

I use this method because I've set `insertConflict = REPLACE` on my `@Table`s but want to use `FAIL` other times.

**Comment by agrosner** [comment]
@GrahamRogers is the blob column a `Blob` or a `byte[]`?

**Comment by agrosner** [comment]
also the native `ModelAdapter` methods use the proper android `bindBlob()` for `SQLiteStatement` and `ContentValues.put()` so it gets converted. The SQLite wrapper language converts the passed in data into a String to use.

**Comment by agrosner** [comment]
in develop, added conversion from byte[] to hexString for insert. This method is not recommended, however it should work.
