### ISSUE TITLE
Delete/reset database.

### ISSUE THREAD

**Issue by italopaolo** [Raizlabs/DBFlow#658]
I'm using dbflow to store some data that I download in server. The "id" (primary key) of my entities is defined in server. When I logout of app, I call FlowManager().getDatabase(NAME).reset(context);
When I login again, with the same user return SQLiteConstraintException, because id must be UNIQUE in database, but I reset the database.
I tried deleteDatabase(NAME+".db), but the same error occurs.

What do I do to delete database and release the primary keys of my database?

**Comment by andrecrispim** [comment]
It is the same case of that one: #417, it still open.

I posted a workaround there.

**Comment by arturonaredo** [comment]
Another approach that works while the bug is fixed would be delete table y table.

**Comment by italopaolo** [comment]
I tried Delete.tables(table1.class, table2.class...); but not work to.

**Comment by italopaolo** [comment]
I'll close this issue, because is the same case of #417 ...
