### ISSUE TITLE
All column names are being created enclosed in grave accents.

### ISSUE THREAD

**Issue by romulof** [Raizlabs/DBFlow#659]
SQLite is understanding that the column name is `` `id` `` instead of `id`.

Here is my `Course_Adapter.java` generated code to create the table:
```java
  public final String getCreationQuery() {
    return "CREATE TABLE IF NOT EXISTS `Course`(`id` INTEGER,`name` TEXT,`duration` INTEGER,`cover` TEXT,`description` TEXT,`purchaseDate` INTEGER,`productId` TEXT,`transactionId` TEXT, PRIMARY KEY(`id`)" + ");";
  }
```
Here is the database exported from Android and opened with Valentina Studio:
![2016-02-24 08 55 58 pm](https://cloud.githubusercontent.com/assets/1225889/13305535/8c76b7e8-db3a-11e5-872d-76e2e659644a.png)

**Comment by filipemanuelofs** [comment]
Same here:
```
android.database.sqlite.SQLiteException: no such column: id_estado (code 1): , while compiling: SELECT * FROM `tb_cidade` WHERE `id_estado`=2
```

**Comment by gauravsak** [comment]
@agrosner Considering the SQLite docs (https://www.sqlite.org/lang_keywords.html) , I think we should start using `'` instead of ```.

**Comment by agrosner** [comment]
a change like that is impossible without breaking backwards compatibility or causing potential for bugs. These are used to allow keywords to be used in queries or tables. It is intentional so things like `order` can be used in columns since variable/field names may be the same name.

**Comment by gauravsak** [comment]
@agrosner But using keywords can also be done with single quote, so I thought. (https://www.sqlite.org/lang_keywords.html) What do you think could be a reason for this issue then? Thanks.

**Comment by romulof** [comment]
I update my app from DBFlow 2.x to 3.0, reseted all the data and the database was created the way I said in the first post.

Version 3.0 is unusable for me.

**Comment by agrosner** [comment]
working as intended.
