### ISSUE TITLE
Table property default

### ISSUE THREAD

**Issue by gnuhel** [Raizlabs/DBFlow#66]
It is possible to set a default for a column in a tablet?

**Comment by agrosner** [comment]
```@Column(defaultValue = "defaultValueStringhere")```

its a property on column. It must be in a String since it simply gets appended to the table creation as you would expect a SQL string to do so.

**Comment by gnuhel** [comment]
@agrosner sorry to have reopen the issue again. I added this column to a table
```
    @Column(defaultValue = "server")
    public String type;    // administrator, manager, server
```
but defaultValue is not set in the database.

**Comment by agrosner** [comment]
can you send me what the table creation query is from the ```$Adapter``` class for this table?

**Comment by gnuhel** [comment]
@agrosner ok here is what I have tried. I modified the column
```
    @Column(defaultValue = "'server'")
    public String type;    // administrator, manager, server
```
and DbFlow generate
```
  @Override
  public String getCreationQuery() {
    return "CREATE TABLE IF NOT EXISTS User(id INTEGER PRIMARY KEY AUTOINCREMENT, userId TEXT NOT NULL ON CONFLICT FAIL, password TEXT, name TEXT, type TEXT DEFAULT 'server');";
  }
```
It still return null for type

**Comment by agrosner** [comment]
did you reset the database? once a table is created, you need to 
  1. migrate data into a temp DB
  2. drop table
  3. create new table with the updated create statement
  4. copy data from temp table into new

**Comment by gnuhel** [comment]
I try to drop the database with 
```
FlowManager.getDatabase(PosDatabase.NAME).reset(this);
```
but it does not work. still return null

here is my model:
```
@Table(databaseName = PosDatabase.NAME)
public class User extends BaseModel {

    @Column(columnType = Column.PRIMARY_KEY_AUTO_INCREMENT)
    public int id;

    @Column(notNull = true)
    public String userId;

    @Column
    public String password;

    @Column
    public String name;

    @Column(defaultValue = "'server'")
    public String type;    // administrator, manager, server

    public String toString() {
        return "user (" + id + " : " + userId + " : " + name + " : " + type + ")";
    }
}
```
here the output code
```
        List <User> users = new Select().from(User.class).queryList();
        for (User u : users ) {
            Log.e("Test", "u: " + u);
        }

```

**Comment by agrosner** [comment]
@gnuhel escalating this to a bug for 1.5.1. It appears when you save a model into the DB, the default value is ignored.

**Comment by agrosner** [comment]
@gnuhel sorry. Actually for inserting this model with default values, it gets complicated. The ```ModelAdapter``` uses insert statements for all columns except auto incrementing primary keys. My suggestion is to (until I discover a fix for this)
A. have your model implement ```SQLiteStatementListener``` and ```ContentValuesListener``` and add the appropriate default value you need if you know its not set.
B. or assign the value of the Model at field declaration to the default value of the column.

**Comment by tsuharesu** [comment]
Just another comment about this: for me, DBFlow is creating the Create Table without quoting the default values:

```java
@Override
  public String getCreationQuery() {
    return "CREATE TABLE IF NOT EXISTS `SUBJECT`(`ID` INTEGER PRIMARY KEY AUTOINCREMENT, `NAME` TEXT DEFAULT Matéria sem nome, `FINAL_GRADE_FIRST_HALF` REAL DEFAULT -1, `NEC_GRADE` REAL DEFAULT 20, `PS_GRADE` REAL DEFAULT -1);";
  }
```

I must use quotes myself?

**Comment by AndreasBackx** [comment]
@agrosner regarding your comment before you added the question tag. You suggest some stuff that is documented nowhere. I don't think I'm the only one that thinks the documentation for DBFlow is severely lacking. It is imo the reason why DBFlow doesn't attract that big of an audience and I regret starting to use the library because of this. As soon as Realm adds support for null and custom methods I'm switching. Every step I take with DBFlow is met with annoyance because of the documentation that is close to non-existent. Relevant #312

**Comment by anpham1611** [comment]
@agrosner: can you give me code example on this guide:
1. migrate data into a temp DB
2. drop table
3. create new table with the updated create statement
4. copy data from temp table into new
