### ISSUE TITLE
How to use Transaction listener when I have a nested loop, not a list

### ISSUE THREAD

**Issue by kenneth2008** [Raizlabs/DBFlow#660]
```
for (FloorPlanR floorPlanR : floorPlanList) {
        FloorPlan floorPlan = new FloorPlan(floorPlanR.imageUrl, propertyId, flatId);
        int floorPlanId = floorPlan.saveAndGiveId();
        List<LocationCoordinateR> locationCoordinateRs = floorPlanR.locationList;
        for (LocationCoordinateR lcR : locationCoordinateRs) {
                List<CoordinateR> coordinateRs = lcR.coordList;
                for (CoordinateR cR : coordinateRs) {
                    new Coordinate(cR.x, cR.y, floorPlanId, lcR.locationId).save();
                }
         }
}


TransactionManager.transact(DFIntakeDatabase.NAME, runnable);
```
Requirement: I want to listen the complete event when all transaction done.

Q1. How to use TransactionListener when I have a nested loop, I need floorPlanId for each child, so I cannot prepare a Coordinate list because I don't know their parent's ID.
Q2. How and when the transaction will be start and finish, when using the following statement.
TransactionManager.getInstance().addTransaction(new SaveModelTransaction<>(processModelInfo));

**PS: In this case FloorPlan and Coordinate are DBFlow model class.**
I have seen this, which only support a prepared list.
[(https://github.com/Raizlabs/DBFlow/issues/370)]

Thank you

**Comment by agrosner** [comment]
just use your own subclass of `ProcessModelTransaction` to handle this case for you. It will allow you to run through each item in the larger list, and override `processModel(ModelClass model)`
