### ISSUE TITLE
How to write dynamic IN Condition?

### ISSUE THREAD

**Issue by DoubleTime** [Raizlabs/DBFlow#661]
Writing down manually works 
`Order_Table.refno.in("123","456")`

What if my value is dynamic how do I  write it??
```
       String[] in_value = {"123","456"};
        List<Order> list = SQLite.select().from(Order.class).where(
                Order_Table.refno.in(in_value)
        ).queryList();
```

**Comment by kenneth2008** [comment]
Did you test the code below?
I saw function in() support Collection<string> as parameter

**Comment by DoubleTime** [comment]
i got cannot resolve method 'in(java.lang.String[])

**Comment by kenneth2008** [comment]
String array may be not a child of Collection type

try to change it into ArrayList

**Comment by DoubleTime** [comment]
I change to this
```
ArrayList<String> in_value = new ArrayList<>();
        in_value.add("123");
        in_value.add("456");
```
get cannot resolve method message as well

**Comment by andrecrispim** [comment]
You can use the first method, like that:

    public List<T> getAll(@NonNull Integer[] ids) throws RepositoryException {
        try {
            return new Select().from(clazz)
                    .where(new ConditionQueryBuilder<>(clazz, Condition.column(primaryKeyColumn).in(0, (Object[]) ids)))
                    .queryList();
        } catch (Exception e) {
            throw new RepositoryException(e);
        }
    }

**Comment by kenneth2008** [comment]
I have it.

My version is def dbflow_version = "3.0.0-beta3"

**Comment by agrosner** [comment]
its def there since then. closing.
