### ISSUE TITLE
Exception on ContentProvider query

### ISSUE THREAD

**Issue by gorodechnyj** [Raizlabs/DBFlow#662]
If I generate ContentProvider with DBFlow, and query model with CursorLoader like this:

`return new CursorLoader(this, CustomModel.CONTENT_URI, null, null, null, CustomModel_Table._id + " DESC");`

I get exception

`java.lang.NullPointerException: Attempt to get length of null array
                                                             at com.raizlabs.android.dbflow.runtime.BaseContentProvider.toProperties(BaseContentProvider.java:57)
                                                             at ch.dotpay.db.DotpayDatabase_Provider.query(DotpayDatabase_Provider.java:136)`

The exception is caused by reading length property of null projection field. But in Android SDK it is valid to specify null projection - it only indicates that CursorLoader should query all fields.

**Comment by sp958857** [comment]
I have the problom

**Comment by sp958857** [comment]
By the way, the "selection and selectionargs" seems no work in cursorLoader.

**Comment by gorodechnyj** [comment]
@agrosner, I think you should make a special wiki page about how DBFlow can and should be used with CursorLoaders. And how Model instances could be restored from Cursor objects.

**Comment by agrosner** [comment]
in `develop` it now directly just calls down to native methods ...no conversions to worry about.
