### ISSUE TITLE
New/Old references for triggers in dbflow

### ISSUE THREAD

**Issue by adityasharma1912** [Raizlabs/DBFlow#665]
I want to use old reference to create trigger using dbflow library. Please tell me how i can use "old" table reference.

**Comment by agrosner** [comment]
please be more specific, by providing an example of what you mean. thank you!

**Comment by adityasharma1912** [comment]
Following is the SQL query I am using for triggers in my database : 
CREATE TRIGGER after_make_delete after delete on allmake
begin
	delete from allmodel where allmodel.make_id=old.make_id;
end

here "old" in old.make_id is the reference to the allmake table with deleted row.
I want to use the same reference using dbFlow library. I hope you understand now. Please revert in case of any concern or further query.

Any kind of quick reply from your side will be highly appreciated.

Thanks.

**Comment by GrahamRogers** [comment]
You should be able to use something like AllModel_Table.make_id.withTable(new NameAlias("OLD")).

**Comment by adityasharma1912** [comment]
Thanks Graham, at last it worked for me :)
