### ISSUE TITLE
Insert multiple objects in database create time

### ISSUE THREAD

**Issue by gorodechnyj** [Raizlabs/DBFlow#666]
How do I load my fixtures from database on create time?
I tried to extend FlowSQLiteOpenHelper and do some Model.insert() calls in onCreate method.
Obviously this leads to looping getDatabase() calls.

After that I have tried getting insert script from adapter, and couldn't get one for the same reason.
After that I have tried to get content values and insert them through native db.insert() call. No success, since to get ContentValues I need to get instance of adapter class as well.

Of course I can load my data in Application class or on login screen and put SharedPreferences flag indicating data has been loaded, but DBFlow really needs a simple way to load fixtures. One will not simply generate SQLite db file and use it as a holder for initial data since this way tests and development process becomes very complicated.

I suggest you a feature: use json file or series of files, containing initial values for tables, parse them in SQLiteOpenHelper and insert them after database is created. Or one can put those files in assets and point to them in @Table annotation.

**Comment by agrosner** [comment]
did you try a `@Migration` where version is 0?

**Comment by gorodechnyj** [comment]
This didn't help since I'm saving objects with Model.save()

**Comment by kenneth2008** [comment]
I think what you need is bulk insert or bulk update?
If yes, the answer is transaction.

**Comment by agrosner** [comment]
In a migration, you cannot recursively access the database object. So you need to pass in a `DatabaseWrapper`, however this does not exist for `Model`. In `develop` (will be in beta4). you can (for each model):
```java
  DatabaseStatement insertStatement = modelAdapter.getInsertStatement(databaseWrapper);
// for each model in list
        adapter.bindToInsertStatement(insertStatement, model);
        long id = insertStatement.executeInsert();
        adapter.updateAutoIncrement(model, id);
        notifyModelChanged(model, adapter, modelAdapter, Action.INSERT);
```

Which will provide the insert you need in this scenario.

**Comment by gorodechnyj** [comment]
Will be waiting for it, thx

**Comment by agrosner** [comment]
in beta 4 and in `develop` you can use the corresponding `ModelAdapter` to not recurse the DB: 

```java

final ModelAdapter<SomeModel> modelAdapter = FlowManager.getModelAdapter(SomeModel.class);

// for each in a transaction
    modelAdapter.save(model, databaseWrapper);

```

**Comment by mtaheri** [comment]
Hi 
I m new in dbflow , how can i create database wrapper ?
