### ISSUE TITLE
ModelView generation fails for blob columns

### ISSUE THREAD

**Issue by astrobread** [Raizlabs/DBFlow#667]
A ModelView that contains a blob will fail to compile due to getPrimaryConditionClause(), while other field types compile without issue. Example ModelView:
```
@ModelView(database = TheDatabase.class)
public class TestView extends BaseModelView<DataTable> {
    @ModelViewQuery
    public static final Query QUERY = new Select(DataTable_Table.data).from(DataTable.class);

    @Column
    public Blob data;
}
```
This is the code that's generated in TestView_View.java.
```
  public final ConditionGroup getPrimaryConditionClause(TestView model) {
    ConditionGroup clause = ConditionGroup.clause();
    clause.and(TestView_ViewTable.data.eq(model.data.getBlob()));return clause;
  }
```

The error produced is:

 Error:(37, 43) error: no suitable method found for eq(byte[])
method Property.eq(Blob) is not applicable
(actual argument byte[] cannot be converted to Blob by method invocation conversion)
method BaseProperty.eq(BaseModelQueriable) is not applicable
(actual argument byte[] cannot be converted to BaseModelQueriable by method invocation conversion)
method BaseProperty.eq(ITypeConditional) is not applicable
(actual argument byte[] cannot be converted to ITypeConditional by method invocation conversion)

**Comment by agrosner** [comment]
fixed in `develop`.
