### ISSUE TITLE
Escape Like clause

### ISSUE THREAD

**Issue by radvansky-tomas** [Raizlabs/DBFlow#670]
I use this method to get list from DB:
```java
SQLite.select()
  .from(Message.class)
  .where(Message_Table.message.like("%"+query+"%"))
    .and(Message_Table.ack.greaterThan(0))
  .orderBy(Message_Table.messageID, isASC)
  .queryList();
```

Thing is that query string needs to be somehow escaped. I tried different methods, but still I havent got any results.

I want to know how to escape chars properly in DBFlow, how to use ESCAPE sqllite statement, or how to make query with this type of string: "Test 123 ?! () + -"

THX in advance !!!!

**Comment by agrosner** [comment]
@radvansky-tomas can you send the output of the query, i.e. what is generated

**Comment by agrosner** [comment]
We do and escape the LIKE query using `DatabaseUtils.sqlEscapeString()`
