### ISSUE TITLE
the max date of a column

### ISSUE THREAD

**Issue by ervinsae** [Raizlabs/DBFlow#671]
how can i choose the max date from the date column

**Comment by ervinsae** [comment]
my DBFlow version is 2.2.1

**Comment by ervinsae** [comment]
i got it

**Comment by ervinsae** [comment]
Select Max, Min, Avg function? #169

**Comment by dleonett** [comment]
Hello @ervinsae I'm facing the same problem with DATE columns, how did you solve it?

**Comment by Mrxxy** [comment]
@dleonett  Use like this:
`int maxOrderNumber = 0;
Cursor cursor = new Select(Method.ALL_PROPERTY, Method.max(AppModel_Table.orderNumber)).from(AppModel.class).query();
        if (cursor != null && cursor.getCount() > 0) {
            while (cursor.moveToNext()) {
                maxOrderNumber = cursor.getInt(cursor.getColumnIndex("orderNumber"));
            }
        }`

**Comment by JavierSolis** [comment]
@dleonett 
I worked this function

```
public int getMaxLevel() {
        Cursor cursor = SQLite.select(Method.max(EntityBoss_Table.level).as("max")).from(EntityBoss.class).query();
        int max = cursor.getInt(0);
        cursor.close(); 
        return max;
    }
```
