### ISSUE TITLE
Return number of affected rows in Update/Delete operations and Uri in Insert.

### ISSUE THREAD

**Issue by gorodechnyj** [Raizlabs/DBFlow#675]
Neither SQLite.update(), .insert(), .delete() or Model.insert(), .update(), .delete() methods return number of affected rows. In some cases this is critical feature.

I'm migrating from old hand-written database module, and number of rows affected by CRUD operations is broadly used in my application logic.

You can easily add this feature for Model classes by returning what ContentUtils methods returns to you. For instance, in class `BaseSyncableProviderModel`:

    @Override
        public int update() { // return int instead of void
            super.update();
            return ContentUtils.update(getUpdateUri(), this);
        }

As for SQLite.update()... methods, they also can be processed through ContentResolver methods
For instance, now I have to rewrite simple update query

    SQLite.update(Plan.class)
        .set(Plan_Table.data18.is(Long.toString(calendarId)))
        .where(Plan_Table._id.is(planId))
        .execute();

in the following manner:

    ContentValues cv = new ContentValues();
    cv.put(Plan_Table.data18.toString(), Long.toString(calendarId));
    String condition = Plan_Table._id.is(planId).getQuery();
    return FlowManager.getContext().getContentResolver().update(Plan.CONTENT_URI, cv, condition, null);
        

What do you think of this?

**Comment by agrosner** [comment]
for the `Update` query if you do: 
```
SQLite.update(Plan.class)
    .set(Plan_Table.data18.is(Long.toString(calendarId)))
    .where(Plan_Table._id.is(planId))
    .count();
```

It returns the number of rows affected. Its behavior is not immediately apparent.

**Comment by agrosner** [comment]
as for the `Model` methods, I was thinking of the same thing.

**Comment by gorodechnyj** [comment]
Thanks, this is really helpful. And rather unobvious

**Comment by mohamed-habib** [comment]
What if i want the IDs of the inserted Rows ? @agrosner

**Comment by cdaringe** [comment]
@mohamed-habib, I skeptical that SQLite supports it.  i think that postgres does, however, unrelated

**Comment by baranowskinet** [comment]
Does this .count() still works in newer version (4.0.4). I tired but I have error:

**Comment by lawonga** [comment]
> for the Update query if you do:
> 
> SQLite.update(Plan.class)
>     .set(Plan_Table.data18.is(Long.toString(calendarId)))
>     .where(Plan_Table._id.is(planId))
>     .count();
> It returns the number of rows affected. Its behavior is not immediately apparent.

Hmm.. this doesn't actually return the count. I'm calling update and it's returning a 0 regardless
