### ISSUE TITLE
onModelStateChanged should only be called if there's actual changes

### ISSUE THREAD

**Issue by brucexia** [Raizlabs/DBFlow#677]
Looks like the listeners are getting notified regardless whether there's actual changes. e.g. an update/delete query should check the updated/deleted count and an insert query should check if insert success.

**Comment by agrosner** [comment]
if you wish to fix this in the interim you can subclass `ModelSaver` and for the tables set:
```java

FlowManager.getModelAdapter(MyTable.class).setModelSaver(new CustomModelSaver());`
```

**Comment by agrosner** [comment]
this is fixed as of beta5
