### ISSUE TITLE
Set more than value in Update Statement

### ISSUE THREAD

**Issue by mohamed-habib** [Raizlabs/DBFlow#679]
Hi, i want to update more than one column in single update statement

`
Where<TaskTable>update = SQLite.update(TaskTable.class)
     .set(TaskTable_Table.isOnline.eq(true))
     .set(TaskTable_Table.serverId.eq(Long.parseLong(serverTaskId)))
.where(TaskTable_Table.isOnline.eq(false))
.and(TaskTable_Table.taskId.eq(Integer.parseInt(localTaskId)));
`

this should be the solution but the second set() function not working,
what is the solution if i want to do this.

**Comment by agrosner** [comment]
its a varg of condition so you just pass it as such:
```java
SQLite.update(TaskTable.class).set(TaskTable_Table.isOnline.eq(true), TaskTable_Table.serverId.eq(Long.parseLong(serverTaskId))) .where(TaskTable_Table.isOnline.eq(false)) .and(TaskTable_Table.taskId.eq(Integer.parseInt(localTaskId)));
```

**Comment by mohamed-habib** [comment]
Thanks.
