### ISSUE TITLE
Get Id of an inserted entry

### ISSUE THREAD

**Issue by gnuhel** [Raizlabs/DBFlow#68]
I use
```
        Model model = new Model();
        model.save(false);
```
to insert new data to the table. It is possible to get the id of the inserted entry?

**Comment by agrosner** [comment]
are you running at least 1.4.4? If its an ```Column.PRIMARY_KEY_AUTO_INCREMENT``` on ```save()``` the key is stored in the model.

**Comment by gnuhel** [comment]
thanks
