### ISSUE TITLE
queryList() not retuen null

### ISSUE THREAD

**Issue by amorenew** [Raizlabs/DBFlow#680]
```
SQLite .select(Method.ALL_PROPERTY, Method.max(StatusModel_Table.Downloaded))
                .from(StatusModel.class)
               .queryList()
```
it's not return null however no rows in table

**Comment by agrosner** [comment]
it returns a `@NonNull` empty `List` if no rows in table. its by design and to prevent unnecessary `NullPointerException` from creeping up.
