### ISSUE TITLE
Execure raw query on db

### ISSUE THREAD

**Issue by sebastianmaz** [Raizlabs/DBFlow#681]
Is there any way to execute raw query ?
Something like SQLite.queryRaw("SELECT * FROM table");

Sample usage is to generate query in one activity and then pass it to another activity to execute.

**Comment by agrosner** [comment]
yeah, can I ask why you would need to? just use `StringQuery`

**Comment by sebastianmaz** [comment]
I did not know that such a thing exists :-) Thank you very much

**Comment by abeemukthees** [comment]
Is it available now ? I couldn't find StringQuery

**Comment by aimanbaharum** [comment]
@abeemukthees 

```
StringQuery query = new StringQuery(model.class, "select * from model where something");
query.execute();
```

**Comment by abeemukthees** [comment]
@aimanbaharum  thank you  👍

**Comment by FarhanAhmad** [comment]
a really valuable edition (Y)

**Comment by zmorris** [comment]
Java is so verbose (especially before 8) that something as simple as a raw query is pretty ugly compared to web languages like PHP.  Here are some breadcrumbs to get started, in this case performing something similar to "SHOW TABLES" in MySQL.  As you can see, each line is dense with conceptual gotchas.  I'm saving this for myself so I can find it again when I need to execute a query but don't have a model associated with the table:

	Cursor cursor = FlowManager.getDatabase("mydatabase").getWritableDatabase().rawQuery("select * from sqlite_master WHERE type=? order by name asc", new String[] {"table"});
	List<String> columns = Arrays.<String>asList(cursor.getColumnNames());
	List<List<String>> rows = new ArrayList<List<String>>();

	for (cursor.moveToFirst(); !cursor.isAfterLast(); cursor.moveToNext()) {
		List<String> row = new ArrayList<String>();

		for (String column: columns) {
			row.add(cursor.getString(cursor.getColumnIndex(column)));
		}

		rows.add(row);
	}

	new Object[] {columns, rows}    // show colums and rows in Android Studio expression evaluator
