### ISSUE TITLE
new SQLCondition()  how it works.

### ISSUE THREAD

**Issue by PrinceMidha** [Raizlabs/DBFlow#682]
I want condition check before execution of trigger like :

CREATE TRIGGER backTrackMake
   AFTER
   DELETE
   ON modeldetails
WHEN (SELECT COUNT(*) FROM modeldetails WHERE MakeId == old.MakeId) < 1 
BEGIN
   delete from make where MakeId = old.MakeId;
END

with dbflow i am trying like mentioned below  and not getting exact way to check count < 1.

```java
CompletedTrigger<TableModel> trigger = Trigger.create("after_model_delete")
                .after().delete(TableModel.class)
                .when(new SQLCondition() {
                    @Override
                    public void appendConditionToQuery(QueryBuilder queryBuilder) {
                            queryBuilder.appendNotEmpty(""+SQLite.select().from(TableModel.class).count());
                    }

                    @Override
                    public String columnName() {
                        return null;
                    }

                    @Override
                    public String separator() {
                        return null;
                    }

                    @Override
                    public SQLCondition separator(String separator) {
                        return null;
                    }

                    @Override
                    public boolean hasSeparator() {
                        return false;
                    }

                    @Override
                    public String operation() {


                        return null;
                    }

                    @Override
                    public Object value() {
                        return null;
                    }
                })
                                .begin(SQLite.delete(TableMake.class).where(TableMake_Table.makeId.eq(
                                        TableMake_Table.makeId.withTable(new NameAlias("OLD")))));

        trigger.enable();
```

Please help . .. . . . .

**Comment by agrosner** [comment]
try this:
```java
Trigger.create("after_model_delete")
                .after().delete(TableModel.class)
               .when(PropertyFactory.from(SQLite
                   .select(Method.count())
                   .from(ModelDetails.class).where(...)).lessthan((ITypeConditional) PropertyFactory.from(1))
                .begin(SQLite.delete(TableMake.class)
                                      .where(TableMake_Table.makeId.eq(
                                        TableMake_Table.makeId.withTable(new NameAlias("OLD")))));

        trigger.enable();
```

**Comment by PrinceMidha** [comment]
Hi Agrosner

Thanks for your reply. 

As per your comment i tried with code mentioned below : 

CODE SNIPPET FOR TRIGGER CREATION : 

CompletedTrigger<TableModel> trigger2 = Trigger.create("after_model_delete")
        .after().delete(TableModel.class)
        .when(PropertyFactory.from(SQLite.select(Method.count())
                .from(TableModel.class)
                .where(TableModel_Table.makeId.eq(TableModel_Table.makeId.withTable(new NameAlias("OLD")))))
                .lessThan((ITypeConditional) PropertyFactory.from(1)))
        .begin(SQLite.delete(TableMake.class)
                .where(TableModel_Table.makeId.eq(TableModel_Table.makeId.withTable(new NameAlias("OLD")))));


This is causing exception , ADB ERROR LOGs : 

Caused by :java.lang.ClassCastException:com.raizlabs.android.dbflow.sql.language.property.IntProperty cannot be cast to com.raizlabs.android.dbflow.sql.language.ITypeConditional

Please help to resolve that issue. 

Thanks

**Comment by agrosner** [comment]
`3.0.0-beta6`

**Comment by PrinceMidha** [comment]
Hi Agrosner

It works for me with beta5 ... Thanks alot... :)
