### ISSUE TITLE
bulk insert using thread 

### ISSUE THREAD

**Issue by nikhilB93** [Raizlabs/DBFlow#684]
I am inserting multiple records using [Batch Interactions](https://github.com/Raizlabs/DBFlow/blob/master/usage/Transactions.md#batch-interactions) 

code is --
```java
public void saveExpenses(List<Expense> expenses) {
       final DatabaseWrapper database= FlowManager.getDatabase(MyDatabase.NAME).getWritableDatabase();
        new Thread(new Runnable() {
            @Override
            public void run() {
                database.beginTransaction();
                try {
                    for (BaseModel b : myRecordsList) {
                                   b.save();
                    }
                    database.setTransactionSuccessful();
                }
          catch (Exception e){
                    e.printStackTrace();
                    mListener.onOperationFailed();
                }finally {
                    database.endTransaction();
                }
            }
        }).start();

           mListener.onSaveOperationComplete();
    }
```
I am implementing callback So that only after saving all records I wan to do some task ,
But the problem is my callback ( "mListener.onSaveOperationComplete();" ) gets called before saving starts and after this saving in executed.
Not able to find solution .
please help.

**Comment by agrosner** [comment]
This is not a DBFlow question. More of an implementation question and your `mListener.onSaveOperationComplete();` is happening outside the thread. so of course its possible that this happens out of order. you need to put it inside the runnable.
