### ISSUE TITLE
 I think , different user-assigned nowhere database files should be how to operate it

### ISSUE THREAD

**Issue by ybADMIN** [Raizlabs/DBFlow#689]
I think , different user-assigned nowhere database files should be how to operate it

user1-->db1
user2-->db2
db1 Same structure db2

Thanks

**Comment by agrosner** [comment]
can you please rephrase. The explanation is not clear. thank you

**Comment by ybADMIN** [comment]
Thank you for your reply, I would like to ask is whether this database supports the same database with a number of different instance
eg:
   user1-->db1
   user2-->db2

if the explanation is not clear .Can I use Chinese

**Comment by VankaIn** [comment]
源码里面的BaseDatabaseDefinition类中getDatabaseName()方法是获取dbname的途径，但是这个返回的值只能从注解生成。

**Comment by agrosner** [comment]
no, unfortunately that is not supported and probably won't. This lib relies on code generation and that would potentially be impossible.
