### ISSUE TITLE
ModelViewAdapter.getPrimaryConditionClause, wrong SQLCondition used

### ISSUE THREAD

**Issue by gorodechnyj** [Raizlabs/DBFlow#691]
When I create BaseModelView with column of type Boolean or Enum, I get compilation error in overloaded method ModelViewAdapter.getPrimaryConditionClause.
For example, 

    @ModelView(database = MyDatabase.class, name = "v_view") 
    public class MyView extends BaseModelView<MyView> {

        public static enum TestEnum {YES, NO};

        @Column public TestEnum value;
        @Column public Boolean isSet;
    }

And this generates MyView_View.getPrimaryConditionClause:

    @Override
    public final ConditionGroup getPrimaryConditionClause(MyView model) {
        ConditionGroup clause = ConditionGroup.clause();
        clause.and(MyView_ViewTable.value.eq(model.value.name()));
        clause.and(MyView_ViewTable.isSet.eq(model.isSet ? 1 : 0));return clause;
    }

When I browse available `.eq()` methods, I see available `.eq(Boolean)` and `.eq(TestEnum)` methods. So the problem is in selecting correct method call in generator, I suppose.

**Comment by agrosner** [comment]
fixed in `develop`
