### ISSUE TITLE
Get top row of each group [FEATURE - ModelQueriable inside  JOIN]

### ISSUE THREAD

**Issue by Dennis123789** [Raizlabs/DBFlow#692]
Hey, I'm trying to get the top row of each group.

Let's say you have this class (simplified for the example):
```java
@Table(database = MessageDb.class)
public class Message {
    
    @PrimaryKey(autoincrement = true)
    public int id;
    
    @Column
    public String phone;

    @Column
    public int timestamp;

    @Column
    public String text;
}
```

I want the last text message for each phone number. This could be done with this query, for example:

```sql
SELECT msg.*
FROM messages msg
INNER JOIN
    (SELECT id, MAX(timestamp) AS MaxTimestamp
    FROM messages
    GROUP BY phone) topmsg 
ON msg.id = topmsg.id 
AND msg.timestamp= topmsg.MaxTimestamp
```

However, a select within a join does not seem to be supported in this library. I couldn't get any other solutions to work too ([link 1](http://stackoverflow.com/questions/1313120/retrieving-the-last-record-in-each-group), [link 2](http://stackoverflow.com/questions/6841605/get-top-1-row-of-each-group)). Do you have any ideas? Thanks!

**Comment by agrosner** [comment]
Not currently. you can use a `StringQuery` for now to get around this. Ill file it under new feature to make `Join` support `ModelQueriable` statements.

**Comment by agrosner** [comment]
in develop :)
