### ISSUE TITLE
Default String Value in MigrationTable

### ISSUE THREAD

**Issue by mustansarsaeed** [Raizlabs/DBFlow#693]
Hi,

Can anyone please tell me how can I add the default value to the Migration table. I am using the following class:
```
@Migration(version = PictureDatabase.VERSION, databaseName = PictureDatabase.NAME)
public class MigrationPicture extends AlterTableMigration<Picture> {
    public MigrationPicture() {
        super(Picture.class);
    }


    @Override
    public void onPreMigrate() {
        // Simple ALTER TABLE migration wraps the statements into a nice builder notation
        super.onPreMigrate();
        if(PictureDatabase.VERSION == 2) {
            addColumn(String.class, Picture$Table.PICTURETYPE);
        }
    }
}
```

Any help will be appreciated.

**Comment by agrosner** [comment]
@mustansarsaeed what version of dbflow you on? Also I would def recommend that you put the migration into a specific version (i.e. 2) for this migration. Otherwise itll get run in strange scenarios or potentially everytime you upgrade database version.

**Comment by agrosner** [comment]
I would for that case simply manually execute the SQL on the database yourself here.

**Comment by mustansarsaeed** [comment]
You mean that when onPreMigrate is called, then I execute the sql query?
