### ISSUE TITLE
Counting the number of SELECT done in the app

### ISSUE THREAD

**Issue by glureau** [Raizlabs/DBFlow#695]
Hello!
I'm trying to measure performances of some apps and I would like to count the number of SQL request done. It's pretty easy to count the modification since we have notifications (via FlowContentObserver), but I don't know how to listen read-only request.
Is there a good way to do it?
And if no, does someone has a workaround to do it anyway?

**Comment by agrosner** [comment]
you want to listen to `SELECT` queries? you can override a `SingleModelLoader` and `ListModelLoader` for a specific table by subclassing it and for example:

```java

public class ListenModelLoader<TModel extends Model> extends SingleModelLoader<TModel> {
    
    public ListenModelLoader(Class<TModel> tModelClass) {
        super(tModelClass);
    }

    @Nullable
    @Override
    public TModel load(@NonNull DatabaseWrapper databaseWrapper, String query, @Nullable TModel data) {
        TModel model = super.load(databaseWrapper, query, data);
        // interject listener here.
        return model;
    }
}
```

**Comment by agrosner** [comment]
and then call `FlowManager.getModelAdapter(SomeTable.class).setSingleModelLoader(new ListenModelLoader<>(SomeTable.class));` etc for `ListModelLoader` too. just be careful if they're cacheable, youll need to override the corresponding `CacheableListModelLoader` and `CacheableModelLoader` classes. I may make this simpler at some point..

**Comment by agrosner** [comment]
probably will have to write some `ModelLoaderWrapper` so that subclassing every single one is not required...:)

**Comment by agrosner** [comment]
ill have to write up some documentation on how to make use of it.

**Comment by glureau** [comment]
Oh cool, thanks for the quick reply!
I forgot to mention that I'm still working with the 2.3.0.
At some point I'll probably look for an upgrade but currently not enough time for that.
Looks like these classes was not available before, have you a similar trick for the previous released version?

**Comment by agrosner** [comment]
np. Nope :) made sure to modularize pieces of the lib so people can do custom things with them where needed.
