### ISSUE TITLE
Conflict on one-to-many with LoganSquare and DBFlow

### ISSUE THREAD

**Issue by ppamorim** [Raizlabs/DBFlow#696]
Hi DBFlow team.

I'm trying to save my array of items on the database of the app.

```java
@JsonField(name = "subgenres")
@Column(typeConverter = SubGenreTypeConverter.class) 
List<SubGenre> subGenres;
```

 *List MUST be typed or LoganSquare cannot work.*

You can see the problem [here](1).

I tried to implement a converter to serialize/parse the info to use with DBFlow, as your tutorial recommend. [here](2).

Can you compile my project? I don't know what I do.

[1]: https://github.com/ppamorim/Amazing-MVP/tree/master/amazingmvp-rules/src/main/java/com/amazingmvprules/domain/model
[2]: https://github.com/ppamorim/Amazing-MVP/blob/master/amazingmvp-rules/src/main/java/com/amazingmvprules/domain/util/SubGenreTypeConverter.java

**Comment by agrosner** [comment]
My recommendation is to not use a `List<>` for a `@Column` but rather put that into another table by which the list in your model class inserts that data into the referenced table. Does that make sense?
