### ISSUE TITLE
Notifye after row deleted

### ISSUE THREAD

**Issue by mchenani** [Raizlabs/DBFlow#698]
I'm using below code to delete a row from my db with dbflow:
`    SQLite.delete(Document.class).where(Document_Table.parentID.eq(parentId)).query();`
But when it done successfully will not send notification to notify change listeners.

**Comment by agrosner** [comment]
You will need to manually notify using `SqlUtils.notify()`. Unfortunately wrapper statements do not support notifying (as of yet).
