### ISSUE TITLE
Set sqlcipher secret key at runtime

### ISSUE THREAD

**Issue by gafful** [Raizlabs/DBFlow#699]
Currently the secret key is set as a static value by overriding [getCipherSecret()](https://github.com/Raizlabs/DBFlow/blob/master/dbflow-sqlcipher/src/main/java/com/raizlabs/dbflow/android/sqlcipher/SQLCipherOpenHelper.java#L91). A more secure way to supply the key will be through a user provided option. Can anyone kindly point out how this can be done? Thanks in advance.

**Comment by agrosner** [comment]
from this test open helper:
```java
public class SQLCipherHelperImpl extends SQLCipherOpenHelper {

    public SQLCipherHelperImpl(BaseDatabaseDefinition databaseDefinition, DatabaseHelperListener listener) {
        super(databaseDefinition, listener);
    }

    @Override
    protected String getCipherSecret() {
        return "dbflow-rules";
    }
}
```
you would replace the static string with a variable in the open helper. It is initialized on creation of the DBFlow database when you first do a query, CRUD op, or call `FlowManager.getDatabase(...).getWritableDatabase()`. I would ensure that this variable is constant for the db as I am positive once you set the key, you'll need it to access the DB again.

**Comment by gafful** [comment]
@agrosner Thanks a lot for the tip. I have tested and monitored your suggestion for some time now and it's okay so far. I am yet to test what the behaviour would be like when the cipher key set is different from one that was used to create the db.
