### ISSUE TITLE
warning: File for type 'com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder' created in the last round will not be subject to annotation processing.

### ISSUE THREAD

**Issue by arriolac** [Raizlabs/DBFlow#701]
I'm receiving the following warning when building my project using DBFlow.

```
warning: File for type 'com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder' created in the last round will not be subject to annotation processing.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
```

Should this be a concern?

**Comment by derekcsm** [comment]
I'm getting this as well, and then all of my methods that access the DB get this error 

```Error:(341, 34) error: incompatible types: Object cannot be converted to Membership```

`Membership` in this case just being one example

**Comment by derekcsm** [comment]
Ok so here's an update on my issue, in Android Studio I moved some of my object models (not DBFlow) to a different package and when that happened all of my `List<SpecificObject>` values for those moved models were turned into `java.util.List` for some reason.

Long story short I had to fix those auto-generated regressions from Android studio, and ultimately my issues we're not related to DBFlow.

**Comment by agrosner** [comment]
removed `processingOver` execution and just execute write.
