### ISSUE TITLE
how can i set the name of database is dynamic

### ISSUE THREAD

**Issue by VankaIn** [Raizlabs/DBFlow#702]
Hi, We usually a user to a database。like:
UserA  --  id:123456  --- it should store data in db that name is 123456.
UserA  --  id:456789--- it should store data in db that name is 456789.
how can i do this by dbflow, thanks.

**Comment by edison-jr** [comment]
[https://github.com/Raizlabs/DBFlow/issues/203](url)

**Comment by agrosner** [comment]
not really positive that we can do this in DBFlow. It precompiles code and interactions for you, but it doesnt expect names of objects to be dynamic.

**Comment by agrosner** [comment]
I am open to some suggestions, however :)

**Comment by VankaIn** [comment]
@agrosner ,hi 
`@Database(name = ColonyDatabase.NAME, version = ColonyDatabase.VERSION)
public class ColonyDatabase {

  public static final String NAME = "Colonies";

  public static final int VERSION = 1;
}`
in this code,  i wan't make 'name' of db is Variable， but a constant.
how can i do that? thank you.

**Comment by MisterY** [comment]
+1, 
We have the case where databases can be swapped during runtime and am wondering if this is at all possible with DbFlow.

**Comment by agrosner** [comment]
probably not @MisterY . we rely on the database being constant for code gen and connections to tables. If this was dyamic, it would be impossible to generate a database hookup for all tables, views, etc since they can only exist in 1-1 in DBFlow.

**Comment by agrosner** [comment]
My recommendation is add a `userId` or some self identifying id field to the tables that are user specific and just run queries based on that. Multiple DB files also will unneedingly take up extra space.

**Comment by agrosner** [comment]
going to close this as im going to say dynamics are not currently supported, and may never be.

**Comment by MisterY** [comment]
@agrosner You're ignoring the case where the database schema **is constant** but an *instance* of the database gets swapped.
In any case, thank you for the clarification.

**Comment by WarrenFaith** [comment]
That is indeed a good point from @MisterY.
I am planing to implement a save/load functionality for my game so I am looking for a good way to do deal with the swapping.
I guess I need to handle renaming/transfering the database file and load/open it afterwards with a default name for the "currently used" database instance.

**Comment by kistitan** [comment]
May I ask if he opinion is still not changed in this?
I think it is not that uncommon approach, having different database (withe same scheme) for each user.
And actually browsing the code it seems everything is ready for it. The code is (s far as I see) already support it, the only thing is missing to offer it as an incoming parameter during init.
It seems to be a low hanging fruit for me.

Suggested solution same database with userId column is also fine, but it is also not easy.
Having like 50 tables and several hundreds of select, it is not very convenient to add each select, delete, the userid condition one by one.
I tried to create super model class with the extra column and extend Select, Delete classes, but the library is not very flexible in this area.

Any hint what would be the reasonable approach here?
