### ISSUE TITLE
DBFlow 3.0-beta5: SQLCipher Warning: "Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor"

### ISSUE THREAD

**Issue by MikeRzDev** [Raizlabs/DBFlow#706]
hello i just upgraded the version of the gradle dependencies of a project (dbflow3.0 beta4 to beta5) and noticed that when the app inserts values very fast to the SQLCipherDB the console shows the next warning message: "W/SQLiteCompiledSql: Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor...". this message wasn't displayed when using beta4, so it might worth a check on that.

**Comment by agrosner** [comment]
interesting. I will check it out. thank you

**Comment by fabiosassu-sysdata** [comment]
+1

**Comment by natangr** [comment]
+1

**Comment by ubuntudroid** [comment]
I observed exactly the same. We're also using SQLCipher to encrypt the database.

**Comment by ubuntudroid** [comment]
Think I found the culprit. In `ModelSaver` methods the `insert()` methods acquire a `DatabaseStatement`  which is never closed. Preparing a PR which changes this.

**Comment by ubuntudroid** [comment]
Okay, digged into the code and executed the tests and found out, that the insert statement actually is cached in the `ModelAdapter`. That prevents us from calling `close()` on that statement. Now the question is: @agrosner is it intended to keep the insert statement all the time and not releasing the reference to the database?

As far as I observed, it seems that this is only done with the insert statements. I understand that this is probably to avoid the overhead from recreating the statement again and again, but this comes at the cost of the above warnings and probably also leads to some other side effects.

**Comment by ubuntudroid** [comment]
I will test this change more thoroughly tomorrow before creating a PR. I'm very sure that it decreases performance, so maybe another one has a better idea how to handle this problem?

**Comment by ubuntudroid** [comment]
So I tested the changes and the finalizer warnings are gone indeed. Performance impact (at least in our app) wasn't noticeable, but of course that depends on the use case. We're not inserting huge amounts of data at a time into the DB. Maybe someone with a more demanding use case could also check the implementation. Creating the PR now for everyone to review.

**Comment by noinnion** [comment]
+1

**Comment by punitshah89** [comment]
Also found below stack trace. It's not crashing app. But creating bad impression while fetching data.
Using 3.0.0-beta6 version. Looks like it is related this issue.

```
net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
```

**Comment by gafful** [comment]
+1

**Comment by agrosner** [comment]
fixed in `develop`. if you pass in a `DatabaseWrapper` to your operations on a `Model` i.e. `model.save(wrapper)` it will close the `SQLiteStatement` upon usage.
