### ISSUE TITLE
How to encrypt an already existing database?

### ISSUE THREAD

**Issue by natangr** [Raizlabs/DBFlow#707]
Is it possible to encrypt an already existing database using migrations? There is no problem in losing the database data, but I don't want to force the users to uninstall the app. Please provide some code example. Thanks, =)

**Comment by agrosner** [comment]
Not that I know of, but this may help: https://www.zetetic.net/blog/2009/12/29/how-to-encrypt-a-plaintext-sqlite-database-to-use-sqlcipher.html. Just run a database migration on the database at version 0, given you are on version 0,. then when migration done, delete the old unencrypted database. It should be relatively fast, but not sure if there's a lot of data.

**Comment by agrosner** [comment]
did that help?
