### ISSUE TITLE
Failed to resolve Kotlin extensions in beta5

### ISSUE THREAD

**Issue by sigmabeta** [Raizlabs/DBFlow#708]
I'm unable to get my `build.gradle` to recognize the Kotlin extensions package.

    Error:Failed to resolve: com.github.Raizlabs.DBFlow:dbflow-kotlinextensions:3.0.0-beta5

Any ideas?

**Comment by LiHanGuang** [comment]
me too.

**Comment by MrDeus** [comment]
I'm having the same issue with beta4 and beta5. @agrosner can you please check

**Comment by LiHanGuang** [comment]
@MrDeus
@sigmabeta 

I think you should use greendao instead.

**Comment by agrosner** [comment]
sorry guys. itll be in beta6

**Comment by agrosner** [comment]
@LiHanGuang libs are a personal choice and promoting other libs inside this one prob isn't best idea ;).
