### ISSUE TITLE
[3.0beta5] count() throw SQLiteDoneException when equal to 0

### ISSUE THREAD

**Issue by FredJul** [Raizlabs/DBFlow#709]
Hi,

I saw a small bug in beta5: instead of returning 0, the count() methods just throw a SQLiteDoneException. Howerever it works perfectly when there is more than 0 entries.

Here is a typical workaround code:
```
try {
      return new Select().from(Task.class).where(Task_Table.isFinished.eq(true)).count();
} catch (SQLiteDoneException e) {
      // I do not know why this happen when count=0
      return 0;
}
```
But the real solution would be to directly return 0 I think.

**Comment by FredJul** [comment]
Also I noticed that the count itself is not working and can return any value: the generated SQL seems to be "SELECT * FROM..." and it should be "SELECT COUNT(*) FROM..."

**Comment by agrosner** [comment]
@FredJul  the `count()` method returns whatever the count of that query is, does not _have_ to be selecting a count of rows on a query. So thats why its confusing.

**Comment by agrosner** [comment]
in 3.0.0-beta5 I added this line of code: 
```java
 @Override
    public long count(DatabaseWrapper databaseWrapper) {
        try {
            return SqlUtils.longForQuery(databaseWrapper, getQuery());
        } catch (SQLiteDoneException sde) {
            // catch exception here, log it but return 0;
            FlowLog.log(FlowLog.Level.E, sde);
        }
        return 0;
    }
```
which does this catch here. Does it not work? (my guess is its not happening beta5)

**Comment by FredJul** [comment]
Well, yes sorry you're right: I still have an exception into the logs but I didn't noticed that it was a FlowLog one (so no real crash here, the issue can be closed).

But actually I didn't even expected an exception here: I still don't understand the point of having a count() method if it does not do a count by itself. If it's just about getting a long value then I think the name is not correct. What do you think?
