### ISSUE TITLE
Documentation for Migrate needs updating

### ISSUE THREAD

**Issue by wintersandroid** [Raizlabs/DBFlow#71]
Found that I needed to call through to the super of onPreMigrate()
and a constructor is needed!

Keep up the good work!
:)

**Comment by agrosner** [comment]
Thanks @wintersandroid, which ```Migration``` class are you using for this by the way?

**Comment by wintersandroid** [comment]
Hi..

What I am using is...

```java
@Migration(version=100, databaseName = AppDatabase.NAME)
public class MigrateAccountsTo100 extends AlterTableMigration<AccountTable> {
  public MigrateAccountsTo100() {
    super(AccountTable.class);
  }

  @Override
  public void onPreMigrate(){
    super.onPreMigrate();
    addColumn(String.class, AccountTable$Table.NAME);
  }
}
```

**Comment by agrosner** [comment]
makes sense, I guess I need to throw in an exception if ```super()``` is not called.
