### ISSUE TITLE
WithTable and As are not working together

### ISSUE THREAD

**Issue by gorodechnyj** [Raizlabs/DBFlow#710]
I have a query where I select ids from two joined tables

    Plan_Table._id.withTable(),
    Contact_Table._id.withTable().as("participant_id")

In generated select statement this fields are written this way:
    
    SELECT `Plan`.`_id`, `_id` AS `participant_id`

So I get "ambiguous column _id" sql exception

**Comment by kenneth2008** [comment]
Contact_Table._id.withTable("A")  = Where A._id = "participant_id"

To achieve SELECT `Plan`.`_id`, `_id` AS `participant_id`

You should work on SQLite.select() part, inside the ()

**Comment by gorodechnyj** [comment]
@kenneth2008 I'm sorry, but I can't get you

**Comment by gorodechnyj** [comment]
I end up doing this:

    PropertyFactory.from(Contact.class, Contact_Table._id.withTable().getQuery() + " as participant_id"),

But this looks hackish

**Comment by cmbarnett87** [comment]
@gorodechnyj Have you figured out a better non-hacky solution? I'm having the worst time as well with ambiguous column id too. I'm doing a JOIN of 2 tables (on the ID of course...). I can't seem to figure out where the PropertyFactory.from code would fit into my JOIN.

**Comment by gorodechnyj** [comment]
@cmbarnett87 Nope, but you probably having issues with ambiguous columns in conditions. If so, you can skip aliases and compare two like this:

    tableA_property1.withTable().eq(tableB_property2.withTable())

This will work

And don't forget to double check all orderBy, having, and group clauses.

**Comment by agrosner** [comment]
fixed in `develop`. this required me rewriting `NameAlias`
