### ISSUE TITLE
How I can use an other path for the database?

### ISSUE THREAD

**Issue by BarisF** [Raizlabs/DBFlow#713]
It's possible to change the directory for the database, and not use the databases folders of app ?

**Comment by Ealenn** [comment]
Why ? You can also create multiple database :X 
`@Database(name = AppDatabase.NAME, version = AppDatabase.VERSION) public class AppDatabaseOne{...}`
`@Database(name = AppDatabase.NAME, version = AppDatabase.VERSION) public class AppDatabaseTwo{...}`

**Comment by BarisF** [comment]
Because if we delete the app, the databases folders is erased too, and I would like to have another database in other directory.

**Comment by Ealenn** [comment]
Actually I had not thought about it
I look if I can do it

**Comment by BarisF** [comment]
Thanks if it's possible to do it.

**Comment by Ealenn** [comment]
I think it is possible if you touch the FlowManager
I dont know, sorry

**Comment by amorenew** [comment]
i think you can make backup on app destroy

**Comment by agrosner** [comment]
not possible to save it to another path unless you change the `Context` to a `ContextWrapper` which can specify a different `Context.getDatabasePath()` to load the db from. This is based off of the `SQliteOpenHelper`. You can also create a custom `OpenHelper`, however that is not recommended for this case. You would have to use the android backup apis if you want to persist app data between reinstalls. http://developer.android.com/training/backup/backupapi.html

**Comment by royben** [comment]
Hi there, I really like this library and I also really need to store the database file on sd card.
This is not for a commercial project so the requirements are a bit different than a standard android app.
Please advise on how to achieve this by using the API or modifying the source code.
Thanks!
