### ISSUE TITLE
Content observer

### ISSUE THREAD

**Issue by krzysiek-zgondek** [Raizlabs/DBFlow#715]
I have one global observer and all operations are performed in transactions. Normally i get only CHANGE action, but sometimes i get CHANGE, INSERT and SAVE instead of just CHANGE. Why is so? I'm struggling with this whole day and it seems that somehow save operations are performed outside the transaction. Any idea? [second guess was that i have two observers, but no, i double checked that]

**Comment by krzysiek-zgondek** [comment]
there is something strange going on with Transactions as sometimes onChange is called after transaction endTransactionAndNotify and this is why i get these SAVE, INSERT actions after CHANGE. This is probably a bug, because data is processed in Transaction and you shouldnt be notified in any other way than Action.CHANGE

**Comment by agrosner** [comment]
@krzysiek-zgondek if you have any kind of content observer _any_ operation on `Model` will get called if you register for a specific URI base.

So if you register for URI on dbflow://{tableName} you will receive all kinds of URI changes.

Ensure if you just want CHANGE to use `setNotifyAllUris(false)` combined with `beginTransaction()` and you should be good.
