### ISSUE TITLE
Error:Execution failed for task ':app:compileDebugJavaWithJavac'. > java.lang.NullPointerException

### ISSUE THREAD

**Issue by NivedhQburst** [Raizlabs/DBFlow#718]
Can i Know How to Solve this issue?

Information:Gradle tasks [:app:assembleDebug]
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2320Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72320Library UP-TO-DATE
:app:prepareComAndroidSupportCardviewV72320Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2320Library UP-TO-DATE
:app:prepareComAndroidSupportPercent2320Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72320Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42320Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2320Library UP-TO-DATE
:app:prepareComBraintreepaymentsApiBraintree223Library UP-TO-DATE
:app:prepareComBraintreepaymentsApiCore223Library UP-TO-DATE
:app:prepareComGithubRaizlabsDBFlowDbflowDevelopSNAPSHOTLibrary UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesLocation840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesMaps840Library UP-TO-DATE
:app:prepareComGoogleMapsAndroidAndroidMapsUtils04Library UP-TO-DATE
:app:prepareComJakewhartonRxbindingRxbinding040Library UP-TO-DATE
:app:prepareComJakewhartonRxbindingRxbindingAppcompatV7040Library UP-TO-DATE
:app:prepareComJakewhartonRxbindingRxbindingSupportV4040Library UP-TO-DATE
:app:prepareComPaypalAndroidSdkPaypalOneTouch223Library UP-TO-DATE
:app:prepareIoReactivexRxandroid110Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:compileDebugJavaWithJavac FAILED
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
 java.lang.NullPointerException
Information:BUILD FAILED

**Comment by carmas123** [comment]
Please provide a full log

**Comment by NivedhQburst** [comment]
@ModelContainer
@Table(database = PSMyOrderDatabase.class)
public class PSCreateShippingOrderDbFlow extends BaseModel {
    @PrimaryKey(autoincrement = true)
    long id;
    @Column
    private Integer promoCodeId;
    @Column
    private PSCreateShippingPickupAddressAttributesDbFlow pickupAddressAttributes;
    @Column
    private PSCreateShippingDeliveryAddressAttributesDbFlow deliveryAddressAttributes;
    @Column
    private List<PSCreateShippingLineItemsAttributesDbFlow> lineItemsAttributes;
    @Column
    private String pickupDisplayDate;

    public PSCreateShippingOrderDbFlow( Integer promoCodeId, PSCreateShippingPickupAddressAttributesDbFlow pickupAddressAttributes, PSCreateShippingDeliveryAddressAttributesDbFlow deliveryAddressAttributes, List<PSCreateShippingLineItemsAttributesDbFlow> lineItemsAttributes, String pickupDisplayDate) {
        this.promoCodeId = promoCodeId;
        this.pickupAddressAttributes = pickupAddressAttributes;
        this.deliveryAddressAttributes = deliveryAddressAttributes;
        this.lineItemsAttributes = lineItemsAttributes;
        this.pickupDisplayDate = pickupDisplayDate;
    }

   
    public int getPromoCodeId() {
        return promoCodeId;
    }

    public void setPromoCodeId(Integer promoCodeId) {
        this.promoCodeId = promoCodeId;
    }

    public PSCreateShippingPickupAddressAttributesDbFlow getPickupAddressAttributes() {
        return pickupAddressAttributes;
    }

    public void setPickupAddressAttributes(PSCreateShippingPickupAddressAttributesDbFlow pickupAddressAttributes) {
        this.pickupAddressAttributes = pickupAddressAttributes;
    }

    public PSCreateShippingDeliveryAddressAttributesDbFlow getDeliveryAddressAttributes() {
        return deliveryAddressAttributes;
    }

    public void setDeliveryAddressAttributes(PSCreateShippingDeliveryAddressAttributesDbFlow deliveryAddressAttributes) {
        this.deliveryAddressAttributes = deliveryAddressAttributes;
    }

    @OneToMany(methods = {OneToMany.Method.SAVE, OneToMany.Method.DELETE}, variableName = "lineItemsAttributes")
    public List<PSCreateShippingLineItemsAttributesDbFlow> getLineItemsAttributes() {
        if (lineItemsAttributes == null || lineItemsAttributes.isEmpty()) {
            lineItemsAttributes = SQLite.select()
                    .from(PSCreateShippingLineItemsAttributesDbFlow.class)
                    .where(shippingDeliveryAddressAttributes_id.eq(id))
                    .queryList();
        }
        return lineItemsAttributes;
    }


    public void setLineItemsAttributes(List<PSCreateShippingLineItemsAttributesDbFlow> lineItemsAttributes) {
        this.lineItemsAttributes = lineItemsAttributes;
    }

    public String getPickupDisplayDate() {
        return pickupDisplayDate;
    }

    public void setPickupDisplayDate(String pickupDisplayDate) {
        this.pickupDisplayDate = pickupDisplayDate;
    }

}
_________________________________________________________________________________


@ModelContainer
@Table(database = PSMyOrderDatabase.class)
public class PSCreateShippingLineItemsAttributesDbFlow  extends BaseModel {

    @PrimaryKey(autoincrement = true)
    long id;

    @Column
    private String itemTypeId;

    public PSCreateShippingLineItemsAttributesDbFlow(String itemTypeId) {
        this.itemTypeId = itemTypeId;



    public String getLineItemName() {
        return lineItemName;
    }

    public void setLineItemName(String lineItemName) {
        this.lineItemName = lineItemName;
    }

    @ForeignKey(saveForeignKeyModel = false)
    ForeignKeyContainer<PSCreateShippingOrderDbFlow> createShippingOrderForeignKeyContainer;

    public void associateCreateShippingOrder(PSCreateShippingOrderDbFlow createShippingOrder) {
        createShippingOrderForeignKeyContainer = FlowManager.
                getContainerAdapter(PSCreateShippingOrderDbFlow.class)
                .toForeignKeyContainer(createShippingOrder);
    }


}


_______________________________________________________________________


@Database(name = PSMyOrderDatabase.NAME, version = PSMyOrderDatabase.VERSION)
public class PSMyOrderDatabase {
    public static final String NAME = "MyOrders";
    public static final int VERSION = 1;
}

___________________________________________________


@ModelContainer
@Table(database = PSMyOrderDatabase.class)
public class PSCreateShippingDbFlow extends BaseModel {

    @PrimaryKey(autoincrement = true)
    long id;

    @Column
    @ForeignKey
    private PSCreateShippingOrderDbFlow order;


    public PSCreateShippingOrderDbFlow getOrder() {
        return order;
    }

    public void setOrder(PSCreateShippingOrderDbFlow order) {
        this.order = order;
    }
}
_______________________________________________________________________________


@ModelContainer
@Table(database = PSMyOrderDatabase.class)
public class PSCreateShippingDeliveryAddressAttributesDbFlow extends BaseModel {

    @PrimaryKey(autoincrement = true)
    long id;

    @Column
    private String name;

    public PSCreateShippingDeliveryAddressAttributesDbFlow(String name) {
        this.name = name;
      
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column
    @ForeignKey(saveForeignKeyModel = false)
    PSCreateShippingOrderDbFlow createShippingOrder;

}



Its getting error while compiling

**Comment by NivedhQburst** [comment]
@ModelContainer
@Table <https://github.com/Table>(database = PSMyOrderDatabase.class)
public class PSCreateShippingOrderDbFlow extends BaseModel {
@PrimaryKey <https://github.com/PrimaryKey>(autoincrement = true)
long id;
@Column <https://github.com/Column>
private Integer promoCodeId;
@Column <https://github.com/Column>
private PSCreateShippingPickupAddressAttributesDbFlow
pickupAddressAttributes;
@Column <https://github.com/Column>
private PSCreateShippingDeliveryAddressAttributesDbFlow
deliveryAddressAttributes;
@Column <https://github.com/Column>
private List lineItemsAttributes;
@Column <https://github.com/Column>
private String pickupDisplayDate;

public PSCreateShippingOrderDbFlow( Integer promoCodeId,
PSCreateShippingPickupAddressAttributesDbFlow pickupAddressAttributes,
PSCreateShippingDeliveryAddressAttributesDbFlow
deliveryAddressAttributes,
List<PSCreateShippingLineItemsAttributesDbFlow> lineItemsAttributes,
String pickupDisplayDate) {
    this.promoCodeId = promoCodeId;
    this.pickupAddressAttributes = pickupAddressAttributes;
    this.deliveryAddressAttributes = deliveryAddressAttributes;
    this.lineItemsAttributes = lineItemsAttributes;
    this.pickupDisplayDate = pickupDisplayDate;
}


public int getPromoCodeId() {
    return promoCodeId;
}

public void setPromoCodeId(Integer promoCodeId) {
    this.promoCodeId = promoCodeId;
}

public PSCreateShippingPickupAddressAttributesDbFlow
getPickupAddressAttributes() {
    return pickupAddressAttributes;
}

public void setPickupAddressAttributes(PSCreateShippingPickupAddressAttributesDbFlow
pickupAddressAttributes) {
    this.pickupAddressAttributes = pickupAddressAttributes;
}

public PSCreateShippingDeliveryAddressAttributesDbFlow
getDeliveryAddressAttributes() {
    return deliveryAddressAttributes;
}

public void setDeliveryAddressAttributes(PSCreateShippingDeliveryAddressAttributesDbFlow
deliveryAddressAttributes) {
    this.deliveryAddressAttributes = deliveryAddressAttributes;
}

@OneToMany(methods = {OneToMany.Method.SAVE, OneToMany.Method.DELETE},
variableName = "lineItemsAttributes")
public List<PSCreateShippingLineItemsAttributesDbFlow>
getLineItemsAttributes() {
    if (lineItemsAttributes == null || lineItemsAttributes.isEmpty()) {
        lineItemsAttributes = SQLite.select()
                .from(PSCreateShippingLineItemsAttributesDbFlow.class)
                .where(shippingDeliveryAddressAttributes_id.eq(id))
                .queryList();
    }
    return lineItemsAttributes;
}


public void setLineItemsAttributes(List<PSCreateShippingLineItemsAttributesDbFlow>
lineItemsAttributes) {
    this.lineItemsAttributes = lineItemsAttributes;
}

public String getPickupDisplayDate() {
    return pickupDisplayDate;
}

public void setPickupDisplayDate(String pickupDisplayDate) {
    this.pickupDisplayDate = pickupDisplayDate;
}

}
------------------------------

@ModelContainer
@Table <https://github.com/Table>(database = PSMyOrderDatabase.class)
public class PSCreateShippingLineItemsAttributesDbFlow extends BaseModel {

@PrimaryKey(autoincrement = true)
long id;

@Column
private String itemTypeId;

public PSCreateShippingLineItemsAttributesDbFlow(String itemTypeId) {
    this.itemTypeId = itemTypeId;



public String getLineItemName() {
    return lineItemName;
}

public void setLineItemName(String lineItemName) {
    this.lineItemName = lineItemName;
}

@ForeignKey(saveForeignKeyModel = false)
ForeignKeyContainer<PSCreateShippingOrderDbFlow>
createShippingOrderForeignKeyContainer;

public void associateCreateShippingOrder(PSCreateShippingOrderDbFlow
createShippingOrder) {
    createShippingOrderForeignKeyContainer = FlowManager.
            getContainerAdapter(PSCreateShippingOrderDbFlow.class)
            .toForeignKeyContainer(createShippingOrder);
}

}
------------------------------

@Database <https://github.com/Database>(name = PSMyOrderDatabase.NAME,
version = PSMyOrderDatabase.VERSION)
public class PSMyOrderDatabase {
public static final String NAME = "MyOrders";
public static final int VERSION = 1;
}
------------------------------

@ModelContainer
@Table <https://github.com/Table>(database = PSMyOrderDatabase.class)
public class PSCreateShippingDbFlow extends BaseModel {

@PrimaryKey(autoincrement = true)
long id;

@Column
@ForeignKey
private PSCreateShippingOrderDbFlow order;


public PSCreateShippingOrderDbFlow getOrder() {
    return order;
}

public void setOrder(PSCreateShippingOrderDbFlow order) {
    this.order = order;
}

}
------------------------------

@ModelContainer
@Table <https://github.com/Table>(database = PSMyOrderDatabase.class)
public class PSCreateShippingDeliveryAddressAttributesDbFlow extends
BaseModel {

@PrimaryKey(autoincrement = true)
long id;

@Column
private String name;

public PSCreateShippingDeliveryAddressAttributesDbFlow(String name) {
    this.name = name;

}

public String getName() {
    return name;
}

public void setName(String name) {
    this.name = name;
}

@Column
@ForeignKey(saveForeignKeyModel = false)
PSCreateShippingOrderDbFlow createShippingOrder;

}

Its getting error while compiling


Now there is error on creating <List> get list


@OneToMany(methods = {OneToMany.Method.SAVE, OneToMany.Method.DELETE},
variableName = "lineItemsAttributes")
public List<PSCreateShippingLineItemsAttributesDbFlow>
getLineItemsAttributes() {
    if (lineItemsAttributes == null || lineItemsAttributes.isEmpty()) {
        lineItemsAttributes = SQLite.select()
                .from(PSCreateShippingLineItemsAttributesDbFlow.class)

.where(PSCreateShippingLineItemsAttributesDbFlow_Table.shippingDeliveryAddressAttributes_id.eq(id))

                .queryList();
    }
    return lineItemsAttributes;
}

PSCreateShippingLineItemsAttributesDbFlow_Table is now not being created here.


On Thu, Mar 24, 2016 at 4:05 PM, carmas123 <notifications@github.com> wrote:

> Please provide a full log
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Raizlabs/DBFlow/issues/718#issuecomment-200780235>
>



-- 
Thanks,
Nivedh K S
Q*Burst*
www.qburst.com

**Comment by NivedhQburst** [comment]
I Got this error while compiling please help me to solve this issue.

**Comment by agrosner** [comment]
This appears to be an incremental compilation bug or an issue with the android gradle plugin. If it happens only sometimes.

**Comment by agrosner** [comment]
good thing I was able to repro it. So when `Table` rely on `Database`'s class separator or just assuming that it has been processed already, this would crash since the database element was not processed yet. What I changed in `develop`, is collect all elements in the annotation processor then evalaute them in the order that I expect, validate them, and then write everything as expected.
