### ISSUE TITLE
new LRU Cache fails on empty table.

### ISSUE THREAD

**Issue by wintersandroid** [Raizlabs/DBFlow#72]
When creating a FlowTableList on an empty table with cache=true
```
 propertiesTableList = new FlowTableList<PropertiesTable>(PropertiesTable.class);

  Caused by: java.lang.IllegalArgumentException: maxSize <= 0
            at com.raizlabs.android.dbflow.structure.cache.LruCache.<init>(LruCache.java:51)
            at com.raizlabs.android.dbflow.structure.cache.ModelLruCache.<init>(ModelLruCache.java:12)
            at com.raizlabs.android.dbflow.list.FlowTableList.getBackingCache(FlowTableList.java:103)
            at com.raizlabs.android.dbflow.list.FlowTableList$2.getBackingCache(FlowTableList.java:82)
            at com.raizlabs.android.dbflow.list.FlowCursorList.setCacheModels(FlowCursorList.java:120)
            at com.raizlabs.android.dbflow.list.FlowCursorList.setCacheModels(FlowCursorList.java:101)
            at com.raizlabs.android.dbflow.list.FlowCursorList.<init>(FlowCursorList.java:65)
            at com.raizlabs.android.dbflow.list.FlowCursorList.<init>(FlowCursorList.java:77)
            at com.raizlabs.android.dbflow.list.FlowTableList$2.<init>(FlowTableList.java:79)
            at com.raizlabs.android.dbflow.list.FlowTableList.<init>(FlowTableList.java:79)
```

**Comment by agrosner** [comment]
@wintersandroid thanks for the report. for now I would override ```getBackingCache()``` from FlowTableList and return:

```
return new ModelLruCache<>(MODEL_CACHE_SIZE);
```

of what size you wish it to be. Also its possible the ```Cursor``` from ```FlowCursorList``` is returning a -1, which probably shouldn't happen. Could you send me what ```Queriable``` or how your instantiating the ```FlowTableList``` so I can understand what's happening.

Thanks again

**Comment by wintersandroid** [comment]
Hi..

Quite simple, in one instance.. 
```java
private FlowTableList<PropertiesTable> propertiesTableList;

    propertiesTableList = new FlowTableList<PropertiesTable>(PropertiesTable.class);

```

Where PropertiesTable is a BaseModel (I have also tried BaseCacheableTable)

The other, which was worked around is 
```java
  private FlowCursorList<TagGroupTable> tagGroups;


tagGroups = new FlowCursorList<TagGroupTable>(TagGroupTable.class);
```
where I was able to change it to
```java 
tagGroups = new FlowCursorList<TagGroupTable>(false, TagGroupTable.class);
```

to stop it from crashing... In my instance the database of a new install is entirely empty until an "account" is created and the tables then populate with defaults and data..

**Comment by agrosner** [comment]
@wintersandroid right, can you debug and tell me what ```getCount()``` returns when this code block is executed?

```java

public FlowTableList(Class<ModelClass> table, Condition... conditions) {
        super(null);
        mCursorList = new FlowCursorList<ModelClass>(true, table, conditions) {
            @Override
            protected ModelCache<ModelClass, ?> getBackingCache() {
                return FlowTableList.this.getBackingCache(getCount());
            }
        };
    }

```

**Comment by wintersandroid** [comment]
Hi..

It is 0 (Zero).

:)

I created a test, simple one really. as expected it fails on the list creation.

```java
@Config(emulateSdk = 18, manifest = "WidgetsApps/src/test/TestAndroidManifest.xml")
@RunWith(RobolectricTestRunner.class)
public class testDatabase {
  Context context;

  @Before
  public void before() {
    System.out.println("Before");
    context = Robolectric.getShadowApplication().getApplicationContext();
    try {
      FlowManager.init(context);
    } catch (Exception e) {

    }

    assertNotNull("App Context Null", context);

  }

  @After
  public void after() {
    System.out.println("After");

  }

  @Test
  public void testEmptyPropertiesTable() {
    System.out.println("Testing");
    FlowTableList<PropertiesTable> propertiesTable = new FlowTableList<PropertiesTable>(PropertiesTable.class);

    assertTrue("Table Empty", propertiesTable.isEmpty());

    PropertiesHelper helper = PropertiesHelper_.getInstance_(context);

    helper.set("STRING", "A String Value");
    helper.set("BOOLEAN", true);
    helper.set("INTEGER", 100);
    helper.set("FLOAT", 1.2f);
    helper.set("LONG", 100l);


    propertiesTable = new FlowTableList<PropertiesTable>(PropertiesTable.class);
    assertFalse("Table Not Empty", propertiesTable.isEmpty());

    assertEquals("String Value Correct", helper.get("STRING", "DEFAULT"), "A String Value");
    assertEquals("Boolean Value Correct", helper.get("BOOLEAN", false), true);
    assertEquals("Integer Value Correct", helper.get("INTEGER", 0), 100);
    assertTrue("Float Value Correct", helper.get("FLOAT", 0f) == 1.2f);
    assertEquals("Long Value Correct", helper.get("STRING", 100l), 100l);


  }
}

```

**Comment by agrosner** [comment]
@wintersandroid looks like an Lru implementation that does not allow a cache size of 0, in 1.5.1 there will be a workaround that has a method called ```getCacheSize()``` that will enable you to get the size of the cache. It works better than using the ```Cursor.getCount()``` especially for large queries.

**Comment by gustahrodrigues** [comment]
The same happinig here. I am using ```FlowCursorList<MyClass> flowCursorList = new FlowCursorList<>(true, (new Select()).from(MyClass.class).where().limit(MY_LMIT).orderBy(MY_ORDER_BY));```

Probably MyClass table has no rows. Should i make some verification before create ```flowCursorList```?

**Comment by agrosner** [comment]
@gustahrodrigues 

1. use the constructor `FlowCursorList<>(size, query)` instead. If you don't it bases the cache size on the count of the `Cursor` that's returned from the query. 
2. or use a different backing cache such as a `SparseArrayBasedCache` by overriding `getBackingCache()`

**Comment by calrsom** [comment]
Just got bit by this bug on new install - just using an Adapter as shown in documentation to populate a list view with the contents of a table.  Pretty simple stuff.  But for a new install, there's no data in the table.

Couldn't you just implement a cache minimum size (like 1) where you determine the size from the cursor?

**Comment by calrsom** [comment]
Workaround that still uses cursor size:
```
        flowList = new FlowCursorList<>(false, Model.class);
        flowList .setCacheModels(true, Math.max(1, flowList.getCount()));
```
