### ISSUE TITLE
Auto save related models

### ISSUE THREAD

**Issue by Alxzu** [Raizlabs/DBFlow#720]
Hi, is there any way to save all related ants when saving a queen? I'm getting my data from a REST server & when I get the "queen" it has a lot of "ants" loaded, so I need something like **_queen.save()_** and automatically get all "ants" save.

Thanks

**Comment by agrosner** [comment]
`@OneToMany(methods = {OneToMany.Method.ALL}, variableName = "ants")` should save all related ants when saved by `queen.save()`
