### ISSUE TITLE
@ForeignKey support for @ModelView missing

### ISSUE THREAD

**Issue by MichaelSp** [Raizlabs/DBFlow#722]
That ModelView doesn't work:

    @ModelView(database = MyDatabase.class)
    public class WeekModelView extends BaseModelView<MyEntry> {
    
        @ModelViewQuery
        public static final Query QUERY = new Select(MyEntry_Table.task_id, MyEntry_Table.name, MyEntry_Table.id)
                .from(MyEntry.class)
                .groupBy(MyEntry_Table.task_id);
    
        @Column
        public long id;
    
        @Column
        public String name;
    
        @ForeignKey
        public ForeignKeyContainer<Task> task; // not loaded. Is always null
    
    }

Where MyEntry is pretty simple defined as

    @ModelContainer
    @Table(database = MyDatabase.class)
    public class MyEntry extends BaseModel {
        @PrimaryKey(autoincrement = true)
        public long id;
    
        @Column
        public String name;
    
        @ForeignKey(onDelete = ForeignKeyAction.SET_NULL)
        public ForeignKeyContainer<Task> task;
    
    }

As I'm new to this I'm not quite sure if it's actually missing or if I made a mistake.

**Comment by agrosner** [comment]
Views in SQLite cannot have `@ForeignKey`, if you need a field that matches it, you will need to make it a primitive `@Column`

**Comment by agrosner** [comment]
I am updating documentation, as well as some other major changes that should be merged into develop and released for next beta by End of Week
