### ISSUE TITLE
DBFlow for eclipse 

### ISSUE THREAD

**Issue by whatl** [Raizlabs/DBFlow#723]
地址
http://blog.csdn.net/tomcat_lgs/article/details/50978892

支持eclipse 
新增内容：支持数据库存储到sd卡
                    支持默认生成的数据库来自已经创建好的数据库

**Comment by agrosner** [comment]
hi can you please explain to me what the ticket is for? Also DBFlow is not officially supported for Eclipse, since Android Studio is the official IDE and uses gradle.

**Comment by agrosner** [comment]
closing

**Comment by whatl** [comment]
Sorry, I don't fully understand what you mean, what you want to express is why dbflow can migrate from studio eclipse to Android, right? If you ask is this I can answer, studio and eclipse Android are tools, and compile time annotation is a feature of the Java, not the characteristics of the tool, so support to eclipse tool to transplant.

**Comment by whatl** [comment]
hello 
I would like to consult you about, dbflow if you want to check the conditions of multi table data, the code should be how to write, thank you
