### ISSUE TITLE
ForeignKey question

### ISSUE THREAD

**Issue by PingForward** [Raizlabs/DBFlow#726]
Hi there! Many thanks for cool library!
I have a few questions that I haven't find the answer on the Internet.
1) For example I have a Payment Method

```
@Table(database = Database.class, name = "PaymentMethod")
@ModelContainer
public class PaymentMethod extends BaseModel {
 @PrimaryKey
    @JsonProperty("id")
    private int remoteId;

    @ForeignKey(saveForeignKeyModel = true, onDelete = ForeignKeyAction.CASCADE, onUpdate = ForeignKeyAction.CASCADE)
    @JsonProperty("billingAddress")
    AddressCache address;
//other staff
}

@Table(database = Database.class, name = "AddressCache", useIsForPrivateBooleans = true)
public class AddressCache extends BaseAddress {

    @Column
    @PrimaryKey(autoincrement = true)
    private int localId;

    public AddressCache() {
    }
//getters setters
}
```
When I save it (`pm.save();`) AddressCache saved too. But on delete ForeignKey not worked (`pm.delete();`) the payment deleted but not the AddressCache. Any suggestions?

2) How I can save all child models when I call ` test.save();`?
```
class Test extends BaseModel
{
// As I understand if it's filed I can use
@ForeignKey(saveForeignKeyModel = true)
SomeClass someClass;

//What is the best way to save this list of models?
List<Foo> foos;
}
```

**Comment by kenneth2008** [comment]
1. I suggest you to override the delete method on PaymentMethod by:{
address.delete();
delete(); 
}
2. 
`Runnable runnable = new Runnable() {
          @Override
          public void run() {
                 // Update UploadState
                 for (InspectionItem item : itemList) {
                        item.setUploadFinish();
                 }
                 myApp.inspection.setUploadFinish();
        }
};
TransactionManager.transact(DFIntakeDatabase.NAME, runnable);`

I am doing this like that.

**Comment by agrosner** [comment]
yeah I would override the `delete()` method to delete the associated `@ForeignKey` object.
