### ISSUE TITLE
AlterTableMigration not working properly

### ISSUE THREAD

**Issue by chandanrai** [Raizlabs/DBFlow#727]
Hi,

I am supposed to add a column in a existing database so, I wrote a migration which is 

Migration(version = 2, databaseName = AppDatabase.NAME)
public class LocationMigration extends AlterTableMigration<Location> {

    public LocationMigration() {
        super(Location.class);
    }

    @Override
    public void onPreMigrate() {
        super.onPreMigrate();
        addColumn(Integer.class, "allow_bookings");
    }
}

and in my Location model I also added column name with its setter and getters as

 @Column(name = "allow_bookings")
    private int allowBookings;

    public int getAllowBookings() {
        return allowBookings;
    }

    public void setAllowBookings(int allowBookings) {
        this.allowBookings = allowBookings;
    }

But, when while execution I am getting an error saying that

 E/SQLiteLog: (1) table Location has no column named ALLOW_BOOKINGS.

Can someone guide me in the right directions thanks.

**Comment by fabiendem** [comment]
Hi,

Have you increased your database version number also? Ex:
```
@Database(name = AppDatabase.NAME, version = AppDatabase.VERSION)
public class AppDatabase {

  public static final String NAME = "AppDatabase";

  public static final int VERSION = 2;
}
```

**Comment by chandanrai** [comment]
Thanks fabiendem for the quick response.

There was something wrong with my Android Studio as it magically worked after a restart.

**Comment by agrosner** [comment]
maybe it was instant run?
