### ISSUE TITLE
Transactions Saving Lists

### ISSUE THREAD

**Issue by mhemmings** [Raizlabs/DBFlow#729]
I am trying to save a list of items using a transaction. But it only works occasionally. The vast majority of the time it fails to save anything or even throw and error.

Following the docs here: https://github.com/Raizlabs/DBFlow/blob/master/usage/Transactions.md

I have tried both the `addTransaction()` and `saveOnSaveQueue()` and they both only persist the data once every 10 or so times.

Should I be committing the transaction? Should it be saved at the time the method is called? The docs are unclear.

**Comment by agrosner** [comment]
what kind of error? to note that transactions will be coming through with an overhaul soon to make it clearer and "hopefully" easier to use.

**Comment by mhemmings** [comment]
No error is thrown, but when I log the `save()` method on the model it is never called. Pulling the SQLite database using ADB shows that the data indeed hasn't been saved.

The weird bit is it _does_ work fine and save around 5-10% of the time.

**Comment by agrosner** [comment]
Its potentially a bug with the old `TransactionManager`. If you get time, it would be interesting to see if upgrading to `develop` (which soon will become beta6) fixes your issue

**Comment by agrosner** [comment]
try with beta6, you're problems should be solved.
