### ISSUE TITLE
Need a screencast for installation and basic usage 

### ISSUE THREAD

**Issue by mayuroks** [Raizlabs/DBFlow#73]
I am a noob to android development but I am an experienced developer. It would really help me if you guys can make a "Getting Started" screencast for DBFlow using a simple android app. Coz for a simple reason I feel getting started screencasts are way faster than text based documentation.

Thanks a lot.

**Comment by agrosner** [comment]
@mayuroks interesting! i could create a YouTube video with a demo that I can link to. That's a neat idea!

**Comment by Rainer-Lang** [comment]
+1

**Comment by mayuroks** [comment]
bump !! any updates ?

**Comment by agrosner** [comment]
Haven't had any time to do so yet... Hopefully in the next couple weeks

**Comment by tsuharesu** [comment]
@agrosner if you want, I can help with this :)

**Comment by mayuroks** [comment]
@tsuharesu .. plz do help

**Comment by tsuharesu** [comment]
@mayuroks I made this video showing how to install and create a basic Model, like the one in the documentation. I tried to make it fast at the same time explaining why each thing needs to be done. Hope you like it :) (and share to others hehe)

https://www.youtube.com/watch?v=UveI8_wfEoU

**Comment by agrosner** [comment]
Fantastic screencast! Thanks for doing it.

**Comment by Rainer-Lang** [comment]
@tsuharesu Thanks! Great. more.... :-)

**Comment by tsuharesu** [comment]
Here is the second "episode":
https://www.youtube.com/watch?v=1uBNhiwE9Tw

**Comment by Rainer-Lang** [comment]
@tsuharesu Very nice!
