### ISSUE TITLE
DBFlow will not build in helper class...?

### ISSUE THREAD

**Issue by BillTheGoat** [Raizlabs/DBFlow#730]
I am trying to build a simple hello world integration of DBFlow into my project using 3.0.0-beta5. I created an SQLiteIO.class helper which is in a subfolder/subproject. If I include the example db declaration it will build, but if I add a basic table with just a PrimaryKey and  a string Column, I get the following error on build:

`Error:(125, 12) error: an enclosing instance that contains SQLiteIO.Contacts is required`

referring to this code in the generated adapter class:

`@Override
  public final SQLiteIO.Contacts newInstance() {
    return new SQLiteIO.Contacts();
  }`

I have api 19 as my min, 23 as my target, using android studio.

**Comment by agrosner** [comment]
did you make the inner class `static`?

**Comment by BillTheGoat** [comment]
Just cut and paste from the example, so no.

**Comment by BillTheGoat** [comment]
Sorry for delayed update. I tried declaring `static`, which you seemed to be suggesting, and that worked. It would be nice to get a documentation update explaining the circumstances when this is required. I don't really understand, so I can't contribute myself. Thanks!
