### ISSUE TITLE
How Can i cast or convert?

### ISSUE THREAD

**Issue by wlgnsdi** [Raizlabs/DBFlow#731]
I want to take the list 1~10 ten data, not 1,10 two data. how can i do that? Isn't there use cast? or convert?

like that : 
`SELECT CAST(number as INT)
FROM table
WHERE number BETWEEN startNum AND endNum`

This is My Method : 
`public List<Object> findbyBetweenStartEnd(String startNum, String endNum){
return SQLite.select()
        .from(Object.class)
        .where(Object_Table.no.between(startNum).and(endNum))
        .queryList(); }`

**Comment by agrosner** [comment]
There's nothing like that right now, but you can create a custom `Method`. 
`new Method(new StringProperty("number as INT"))`
