### ISSUE TITLE
Support for arithmetic operators?

### ISSUE THREAD

**Issue by AAverin** [Raizlabs/DBFlow#732]
Does DBFlow support arithmetic operators? SQLite supports division, multiplication, plus, minus and modulus. I see plus and minus implemented as Properties, but no other operators are available.
Did I miss anything?

**Comment by brwskitime** [comment]
Good question. I'm trying to figure out how to .groupBy("column/"+30000)  
Doesn't take a String and using NameAlias quotes the expression.

**Comment by brwskitime** [comment]
Found a way

```
.groupBy(NameAlias.joinNames("/",TrackLocation_Table.time.toString(),String.valueOf(secondsDivide*1000)))
```

**Comment by agrosner** [comment]
the other operators will exist in `3.0.0-beta6`

**Comment by agrosner** [comment]
in `develop`
