### ISSUE TITLE
ConditionGroup is not working

### ISSUE THREAD

**Issue by razelsoco** [Raizlabs/DBFlow#733]
im trying to make a query like this:

`SELECT * FROM `Booking` WHERE `ShortDate`='2016-04-09' AND (`PatientName` LIKE '%n%' OR `OperationTheatre` LIKE '%n%' OR `DateOfBirth` LIKE '%n%' OR `IdentityNumber` LIKE '%n%')`

using this statement which is based on the documentation [https://github.com/Raizlabs/DBFlow/blob/master/usage/Conditions.md](url)

`SQLite.select().from(Booking.class).where(Booking_Table.ShortDate.eq(shortDate)).and(cgSearchFilter).queryList()`

cgSearchFilter is a ConditionGroup.clause()
but it is not working. if i check the query string the second condition clause is not enclosed in parenthesis

**Comment by kenneth2008** [comment]
```
SQLite.selectCountOf()
                .from(SnapShot.class)
                .where(SnapShot_Table.inspection_item_code.is(this.inspection_item_code))
                .and(ConditionGroup.clause()
                       .and(SnapShot_Table.expiry_date.greaterThan(String.valueOf(time.getTimeInMillis())))
                        .or(SnapShot_Table.expiry_date.isNull()))
                .count() > 0;
```

One of my working example.

**Comment by razelsoco** [comment]
@kenneth2008  that is the same with what i have, if i try to print out the actual query string the second condition is not enclosed in parenthesis. 
 
but i managed to do a work around on this issue by using SQLCondition

**Comment by agrosner** [comment]
@razelsoco what version of DBFlow are you on? thank you. but it definitely is enclosed in parentheses.

**Comment by razelsoco** [comment]
@agrosner my bad, i was using an old version where the issue happens, which 3.0.0-beta1. 
i updated to 3.0.0-beta5, and yes it is now enclosed in parentheses. thanks!
