### ISSUE TITLE
Saving objects is fast for the first time, but slows down for next

### ISSUE THREAD

**Issue by datdojp** [Raizlabs/DBFlow#737]
I am developing an application that fetches a lot of data from the server and saves to the local database. The number of objects to be saved is around 1000 objects.

- For the first time, it takes 9447 ms
- For 2nd time, it takes 15322 ms
- For 3rd time, it takes 44704 ms
and so on...

The app is not killed. I just bring it to background and bring it back to foreground to trigger synchronization with the server.

I have tried putting all object-savings into one transaction; I also tried saving the objects in multiple threads. Both solutions did not work.

It makes sense that it takes time due to large number of objects to be saved, but the time spent for saving keeps increasing each time we get the data from the server, which does not make sense at all.

I use `REPLACE` to resolve conflict when inserting
```java
@Database(
        name = "xxx.db",
        version = 1,
        insertConflict = ConflictAction.REPLACE,
        foreignKeysSupported = true,
        sqlHelperClass = XXXSQLiteOpenHelper.class
)
```
`REPLACE` happens very often because most of the objects are existing in database when we fetch the data for the 2nd time. Could this be the cause of this problem?

Any help would be greatly appreciated. =)

**Comment by agrosner** [comment]
yeah if it needs to replace and the size keeps growing, there's probably not much we can do here. You might need to consider using `save()` which will check if exists before saving, or if the data can be erased in between, you should consider deleting the table via `Delete.table()` then inserting again.
