### ISSUE TITLE
How to check when SaveModelTransaction finished

### ISSUE THREAD

**Issue by accursedm0** [Raizlabs/DBFlow#739]
How to check when a SaveModelTransaction is finished and call some function?

I'm storing a few models using SaveModelTransactions like this:

```
TransactionManager.getInstance().addTransaction(new SaveModelTransaction<>(ProcessModelInfo.withModels(companyList)));
TransactionManager.getInstance().addTransaction(new SaveModelTransaction<>(ProcessModelInfo.withModels(eventList)));
```

I'd just need to call a function after these transactions are finished to do some post-processing.
I guess there must be a simple solution for it, but although I checked the docs all over a few times already, unfortunately I can't figure out how to do it.
Any help on this would be much appreciated.

Using 3.0.0-beta5

**EDIT**

Ok, after reading this issue about onModelStateChanged: https://github.com/Raizlabs/DBFlow/issues/319

Using a FlowContentObserver seems to do the trick:

```
FlowContentObserver mFlowObserver = new FlowContentObserver();
mFlowObserver.registerForContentChanges(mContext, Event.class);
mFlowObserver.addModelChangeListener(new FlowContentObserver.OnModelStateChangedListener() {
  @Override
  public void onModelStateChanged(@Nullable Class<? extends Model> table, BaseModel.Action action, @NonNull SQLCondition[] primaryKeyValues) {

      mUpdateFinishedHandler.sendEmptyMessage(0);

    }
 });

TransactionManager.getInstance().addTransaction(new SaveModelTransaction<>(ProcessModelInfo.withModels(companyList)));
TransactionManager.getInstance().addTransaction(new SaveModelTransaction<>(ProcessModelInfo.withModels(eventList),mFlowObserver));

```

But, is this the correct way of checking when a Transaction is finished at all? 
And can I be sure that the second SaveModeTransaction with the FlowObserver will indeed be executed after the first one?

**Comment by agrosner** [comment]
That probably would be avoided for more complex scenarios if you end up listening for other operations. 

in 3.0.0-beta6, the Transactions system (and documentation) has gotten a huge overhaul. (released some point this week). If you like a [sneak-preview](https://github.com/Raizlabs/DBFlow/blob/develop/usage2/StoringData.md#transactions)

. It'll provide a very easy way : 
```java
transaction
    .success(new Transaction.Success() {
       @Override
       public void onSuccess(Transaction transaction) {
          // called post-execution on the UI thread.
       }
   })
```

In the meantime you can use the `ProcessModelInfo`'s `result()` method by specifying a `TransactionListenerAdapter` could give you what you need.

**Comment by accursedm0** [comment]
Yes that looks promising. Your hint using `ProcessModelInfo`'s `result() `method seems to work well, and much faster than my FlowContentObserver workaround. Thanks a lot!

So this is how I do it for the time being then:
```java
TransactionManager.getInstance().addTransaction(new SaveModelTransaction<>(ProcessModelInfo.withModels(companyList)));
TransactionManager.getInstance().addTransaction(new SaveModelTransaction<>(ProcessModelInfo.withModels(eventList).result(
              new TransactionListenerAdapter<List<EventType>>(){
                @Override
                public void onResultReceived(List<EventType> list) {
                  mUpdateFinishedHandler.sendEmptyMessage(0);
                }
              }
            )));
```
