### ISSUE TITLE
Database not copied from assets

### ISSUE THREAD

**Issue by spajdo** [Raizlabs/DBFlow#74]
I put my database into app/src/main/assets.
I named it AppDatabase. 
I have this class:
@Database(name = AppDatabase.NAME, version = AppDatabase.VERSION, foreignKeysSupported = true)
public class AppDatabase {
    public static final String NAME = "AppDatabase";
    public static final int VERSION = 1;
}
And when I start my app, and run select command (new Select().from(Additive.class).where(Condition.column("Code").is(code)).querySingle();), file not found exception is thown and new empty database is created. Do I something wrong?

**Comment by agrosner** [comment]
@spajdo ensure it ends in ".db".

**Comment by agrosner** [comment]
reopen if this does not fix it

**Comment by spajdo** [comment]
No, this not fix it.
If my database ends with ".db" compilation ends with error: 
C:\Projects\Ecka_new\Ecka\app\build\source\apt\debug\com\grosner\dbflow\config\Ecka\db$Database.java
Error:(13, 24) error: '{' expected
Error:(28, 26) error: <identifier> expected
Warning:File for type 'com.grosner.dbflow.config.Database$Holder' created in the last round will not be subject to annotation processing.
1 warning
Error:Execution failed for task ':app:compileDebugJava'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 2.317 secs
Information:3 errors

Can you help me with this please? I can send you my project or whatever.

**Comment by spajdo** [comment]
Ok, it works. Thanks.
