### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by anticafe** [Raizlabs/DBFlow#741]
Github allows us to create[ Issue Template](https://github.com/blog/2111-issue-and-pull-request-templates) so that later, user should provide necessary information (for example DBFlow version...)

If you're interested, please create a new one.

**Comment by carmas123** [comment]
+1

**Comment by carmas123** [comment]
Another thing that I think would be necessary to do is, create a chat room where we could compare in a more simple way.

**Comment by agrosner** [comment]
in `develop`.
