### ISSUE TITLE
Can I keep a database table data in memory？

### ISSUE THREAD

**Issue by hunter524** [Raizlabs/DBFlow#742]

**Comment by hunter524** [comment]
Not always in disk

**Comment by agrosner** [comment]
you can use [Caching](https://github.com/Raizlabs/DBFlow/blob/develop/usage2/Caching.md). By default it uses a `SimpleMapCache` which will greedily load all objects from the DB. But there doesnt appear to be a SQLite in-memory equivalent unless you want https://www.sqlite.org/inmemorydb.html
