### ISSUE TITLE
Support JSON If The Ant.class has ForeignKeyContainer Var?

### ISSUE THREAD

**Issue by wangsuicheng** [Raizlabs/DBFlow#743]
I create project-like follow the "Getting Started“, If i use JSON.toJSONString(queen); with fastjson.jar, It appears error "write javaBean error", Just because the Ant.class has the 
`public ForeignKeyContainer<Queen> queenForeignKeyContainer; ` ?
How could i do for this case?

**Comment by agrosner** [comment]
not familiar with fastJSON, but I'd imagine that there's a way to ignore it. I usually as a best practice do not use same objects for JSON as my database schema. I usually keep those isolated.
