### ISSUE TITLE
How to orderBy COLLATE UNICODE or LOCALIZED

### ISSUE THREAD

**Issue by accursedm0** [Raizlabs/DBFlow#744]
I'm using a SelectListTransaction to read Persons from DB and like the result to be orderBy Person.mName with COLLATE UNICODE since I have to deal with some special person names.

```
TransactionManager.getInstance().addTransaction(
        new SelectListTransaction<>(new Select()
          .from(Person.class)
          .orderBy(OrderBy.fromProperty(Person_Table.mName).collate(Collate.NOCASE).ascending()),
...));
```

Since there seems to be no Collate.UNICODE, how would you go about sorting unicode data?

Using 3.0.0-beta5

**Comment by agrosner** [comment]
in `develop`

**Comment by accursedm0** [comment]
Awesome, thank you very much!
