### ISSUE TITLE
ConcurrentModificationException with onChange in FlowContentObserver

### ISSUE THREAD

**Issue by krzysiek-zgondek** [Raizlabs/DBFlow#746]
I'm using one global **FlowContentObserver** within whole app and this problem came out. If i try to use **addModelChangeListener** when **onChange** is fired it goes through this loop:
>for (OnModelStateChangedListener modelChangeListener : modelChangeListeners) {
    modelChangeListener.onModelStateChanged(table, action, columnsChanged);
}

and **ConcurrentModificationException** is being thrown. As a solution i can use global **OnModelStateChangedListener** for all my tables and have my private list of listeners which would be synchronized but i don't think it's a proper solution. On the other hand I can use reflections to override this **private static final ArrayList** to **CopyOnWriteArrayList** but this is also wrong. 

Maybe creating some way to give us possibility to choose proper list implementation would be a nice solution here? (like method we can override or adding parameter to class implementation <T>) ?

**Comment by agrosner** [comment]
in `develop`.
