### ISSUE TITLE
Can LIMIT BY improve single entry retrieving ? in addition of querySingle()

### ISSUE THREAD

**Issue by damson** [Raizlabs/DBFlow#75]
On a table with a lot of entries, would it be faster to retrieve only one entry completing a standard request like ``` new Select().from().querySingle() ``` with a ```LIMIT BY```, for a final request like that: ``` new Select().from().where().limit(1).querySingle() ``` ?

**Comment by agrosner** [comment]
@damson yeah its certainly possible. currently it will only take the first result from the ```Cursor``` so it may result in a very marginal speed improvement. If you're doing some serious crunching on single models, I may suggest extending ```BaseCacheableModel``` and use a cache. it will use the Cache when running any query if it finds an existing ```Model``` with the specified Id in it.
