### ISSUE TITLE
Can ForeignKeyContainer has defalut Constructor?

### ISSUE THREAD

**Issue by wangsuicheng** [Raizlabs/DBFlow#755]
Because some xxx.jar need the default Constructor...
I look up the ForeignKeyContainer source ,find that It hasn't the default Constructor, 
can It has the defalut Constructor without params like that:
```public ForeignKeyContainer(){
   ...
}```

**Comment by agrosner** [comment]
In `develop` you must subclass the `ForeignKeyContainer` class and replace with table you want it to reference. you can include that subclass as the `@ForeignKeyContainer` with a default constructor.
