### ISSUE TITLE
How to update a column type?

### ISSUE THREAD

**Issue by kenneth2008** [Raizlabs/DBFlow#758]
I try to delete table in migrate, after that "no such table" will occur.

That means: Table will not create again by the Model class automatically after migrate

How to update a column type?
(SQLite don't have this function is a known issue.)

**Comment by agrosner** [comment]
you must delete, then re-execute its creation query by: `databaseWrapper.execSql(FlowManager.getModelAdapter(ModelClass.class).getModelAdapter().getCreationQuery())`
