### ISSUE TITLE
How to sanitize string?

### ISSUE THREAD

**Issue by knezmilos13** [Raizlabs/DBFlow#760]
I want to use a string to search records like this:

query.and(Person_Table.name.like("%" + searchQuery + "%"));

How do I sanitize my searchQuery if, for instance, it contains % or '? Is there a built in method for this? Or should I manually use regex or something to do it?

**Comment by agrosner** [comment]
I would advise you looking into (https://www.sqlite.org/lang_expr.html). This is more of a SQLite question at this point.

**Comment by knezmilos13** [comment]
I would suggest that this is an important element that could be a part of DBFlow. People usually say that you should not do your own sanitation but use prepared statements instead. Since prepared statements are not offered by DBFlow here (as far as I can see?), that implies that manual sanitation is required. So if ORM imposes manual sanitation, it should also provide for it. Or allow something like this:

query.and(Person_Table.name.like("%?%", searchQuery));
