### ISSUE TITLE
Updating parent after children update

### ISSUE THREAD

**Issue by waclock** [Raizlabs/DBFlow#761]
I'm trying to implement a pretty simple model: (Mission --> MissionPage --> PageElement --> Options)
Where each parent has many children (One mission has many pages, each page has many elements, each element has many options).

I'm currently facing an issue when I update an option, when I query the option from its parent, I get the old instance (as it was not updated). I'm using a ForeignKeyContainer and trying to set the "saveForeignKeyModel = true" is giving me the following error

`Cannot call save() on a foreign key container. Call load() and then save() instead`

This is thrown at the Option table, which contains the following (among other methods):

Option Model: 

    @Table(database = DatabaseModule.class)
    public class PageElementOption extends BaseModel {

    @SerializedName("id")
    @Column
    @PrimaryKey
    public long id;

    @ForeignKey(saveForeignKeyModel = true)
    ForeignKeyContainer<PageElement> elementContainer;

    public void associateElement(PageElement element) {
        elementContainer = FlowManager.getContainerAdapter(PageElement.class).toForeignKeyContainer(element);
    }

PageElement model

    @ModelContainer
    @Table(database = DatabaseModule.class)
    public class PageElement extends BaseModel {
    
    @PrimaryKey
    @SerializedName("id")
    @Column
    public long id;

        @SerializedName("page_element_options")
    @Expose
    public List<PageElementOption> pageElementOptions;

    @ForeignKey(saveForeignKeyModel = true)
    ForeignKeyContainer<MissionPage> pageContainer;

    @OneToMany(methods = {OneToMany.Method.ALL}, variableName = "pageElementOptions")
    public List<PageElementOption> getPageElementOptions() {
        if (pageElementOptions == null || pageElementOptions.isEmpty()) {
            pageElementOptions = SQLite.select()
                    .from(PageElementOption.class)
                    .where(PageElementOption_Table.elementContainer_id.eq(id))
                    .queryList();
        }
        return pageElementOptions;
    }

        @Override
    public void save() {
        super.save();

        //FIXME add transaction
        if(pageElementOptions !=null) {
            for(PageElementOption pao : pageElementOptions){
                pao.associateElement(this);
                pao.save();
            }
        }
    }
  

In the save method on PageElement, the error arises when it tries to save a PageElementOption. I'm not sure how I'm supposed to fix this as I've been following the documentation. The main issue is that each time I update a Child, the parent should have the update values of its children

**Comment by agrosner** [comment]
```
@ForeignKey(saveForeignKeyModel = true)
ForeignKeyContainer<MissionPage> pageContainer;
```
you cannot save `ForeignKeyContainer` as they're just glorified holders for the reference they point to. you'll have to manually save them via `toModel().save()`

**Comment by waclock** [comment]
Thank you for your response.

I'm having a problem when I try to modify a child, and then update the parent.

In this particular case, I'm setting an Option to true, after setting the option to true, I set one of the parameters of the PageElement to true, when I try saving the PageElement, I've come to realize debugging, that each child of the PageElement is saved, but with its old value.

Why is each child being saved automatically? How can I prevent this inconsistency?

Basically the code is the following in PageElement.java

```
    public void updateSelectedOption(int id) {
        for (PageElementOption peo : getPageElementOptions()) {
            peo.answerSelected = false;
            peo.save();
        }
        PageElementOption selectedPEO = PageElementOption.getPageElementOption(id);
        selectedPEO.answerSelected = true;
        selectedPEO.associateElement(this);
        selectedPEO.save();

        //Update that we have now answered the question
        this.isAnswered = true;
        this.update();
}
```

When this.update() is called, each Option is set to false again.

**Comment by agrosner** [comment]
```java
@OneToMany(methods = {OneToMany.Method.ALL}, variableName = "pageElementOptions")
public List<PageElementOption> getPageElementOptions() {
```

This line might be offending culprit. The `ALL` will generate a save on each item from that list of options. Potentially using stale data.

**Comment by waclock** [comment]
Thanks Andrew, that was indeed the problem. I changed my code a bit, now I update the object pageElementOption itself, so that there's no inconsistencies.

Thanks again

**Comment by agrosner** [comment]
Anytime man, glad to help.

**Comment by a1018875550** [comment]
how to use update method remove foreign value?
