### ISSUE TITLE
Extends class from module

### ISSUE THREAD

**Issue by ihariza** [Raizlabs/DBFlow#762]
I have a module that contains database model with dbflow, and I would like to know if it´s possible to extends my module class model from the app.

module app:

``` javascript
@Table(database = AppDataBase.class)
public class User extends BaseModel {

  @PrimaryKey 
   long id;

  @Column
   String name;
}
```

my app:

``` javascript
@Table(database = MyDbNameGeneratedDatabaseHolder.class)
public class CustomUser extends User {

  @Column
   String email;
}
```

I´m trying adding to the module 

``` javascript
apt {
    arguments {
        targetModuleName 'MyDbName'
    }
}
```

and in my app that extends from Application:

``` javascript
 FlowManager.init(this);
 FlowManager.initModule(MyDbNameGeneratedDatabaseHolder.class);
```

but I get :
  com.raizlabs.android.dbflow.structure.InvalidDBConfiguration: Table: com.myproject.model.entity.User is not registered with a Database. Did you forget the @Table annotation?

**Comment by agrosner** [comment]
Looks like you placed the:
```java
@Table(database = MyDbNameGeneratedDatabaseHolder.class)
public class CustomUser extends User {
....
```

pointing to the holder generated, not database.

**Comment by ihariza** [comment]
I´m trying pointing to AppDataBase of the module

```javascript
@Table(database = AppDataBase.class)
public class CustomUser extends User {

  @Column
   String email;
}
```

but then CustomUser is not generated.

**Comment by agrosner** [comment]
You can't have inter-module tables, unfortunately even if they point to same DB. this is due to limitations of annotation processing. Since each module is independently evaluated such that there's no way to know unless,I wrote some kind of gradle plugin to do this. But that's a little overkill. The only reason multiple modules work is that the class gets generated and is accessible within your project's scope. 

There might be a way that allows you to "merge" two database definition classes together (as long as the contents are unique) into a single holder. will look into this and see if that works.

**Comment by ihariza** [comment]
Hi! I see that you publish beta6, but I can´t find the way to do it. Thanks!

**Comment by agrosner** [comment]
@ihariza my apologies, it did not make it into this version, tabled it for 3.0 release as it will require a little more work to get working

**Comment by naeems** [comment]
@agrosner  any updates on it. I am using DBFlow 3.1.1, can you please tell me how to achieve following case. I have a scenario in which I am trying to create three library modules i.e LibA, LibB and LibC. LibA has Database class, which will be used by LibB and LibC to create its tables when LibB and C will be initialized. When I try to create a Table in LibB or LibC using Database class of LibA, It gives runtime exception of InvalidDBConfig and I have missed some Annotation.

Please suggest me what to do and how I can use same database in different library modules and modules can define their Tables in that common database.

Thanks

**Comment by skhanzada** [comment]
+1

**Comment by ravenfeld** [comment]
+1

**Comment by BuilovAlexey** [comment]
Hello. On this issue there is no progress?

**Comment by agrosner** [comment]
if its not updated, no progress.

**Comment by BuilovAlexey** [comment]
Why? Should I expect this functionality in the near future? Or is it impossible to realize?

**Comment by agrosner** [comment]
just place your models into same module and just use db inside one module.

**Comment by BuilovAlexey** [comment]
Captain obvious, I need exactly what I asked in this issue
