### ISSUE TITLE
There is no documentation about how to import DbFlow 2.x in project

### ISSUE THREAD

**Issue by krupalshah** [Raizlabs/DBFlow#764]
Hi,
I was planning to include DbFlow 2.1.0 in my project as I can't use 3.xbeta for production. But, It seems like the documentation for importing that is now not available.Also, I couldn't find any guide for importing and using different parts of library (core and others). Can you please put that doucmentation again?

**Comment by fabiendem** [comment]
Hi,

For the v2.2.1 you can access the readme from: https://github.com/Raizlabs/DBFlow/blob/319585975bc8480e7896be4319bf0d3c7be788f6/README.md
You can browse the usage folder from: https://github.com/Raizlabs/DBFlow/tree/319585975bc8480e7896be4319bf0d3c7be788f6/usage

For the version 2.1.0, you need to go through the commits history I think.

**Comment by krupalshah** [comment]
Thanks, @fabiendem

**Comment by krupalshah** [comment]
@agrosner Hey, but links are broken on the page. Can't you please put it on 'read me' until 3.x gets released?
