### ISSUE TITLE
Custom sqlHelperClass

### ISSUE THREAD

**Issue by carmas123** [Raizlabs/DBFlow#765]
I've created my custom sqlHelper class and I've linked it to my database by Database annotation but it will not created.
I trace it and found that in this method will create always FlowSQLiteOpenHelper and not mySQLiteOpenHelper
Why?
```
    public synchronized OpenHelper getHelper() {
        if (openHelper == null) {
            DatabaseConfig config = FlowManager.getConfig().databaseConfigMap()
                    .get(getAssociatedDatabaseClassFile());
            if (config == null || config.helperCreator() == null) {
                openHelper = new FlowSQLiteOpenHelper(this, helperListener);
            } else {
                openHelper = config.helperCreator().createHelper(this, helperListener);
            }
        }
        return openHelper;
    }
```

**Comment by agrosner** [comment]
Can you tell me what version of DBFlow you on, (based on this sample of code) it looks like unreleased beta6 in `develop`. What was a bug is leaving in old implementation in `@Database`. you must use the new way [here](https://github.com/Raizlabs/DBFlow/blob/develop/usage2/Databases.md#custom-flowsqliteopenhelper)

**Comment by carmas123** [comment]
Thank you so much
