### ISSUE TITLE
多张表查询怎么办

### ISSUE THREAD

**Issue by whatl** [Raizlabs/DBFlow#767]
请问一下，如果要根据A表的条件查询到B表的数据改怎样写代码

**Comment by agrosner** [comment]
I'm sorry, but can you translate into English? Thank you.

**Comment by whatl** [comment]
Example: to the SQL statement "select description and (select group concat codenum from jtvassetcode QR where t.assetnum =qr.assetnum) QRcode from asset T" conversion code for dbflow. I would like to ask the next should be how to write. Thank you.
