### ISSUE TITLE
Error:(56, 141) error: cannot find symbol variable BidModel_Table

### ISSUE THREAD

**Issue by RowlandOti** [Raizlabs/DBFlow#768]
DBFlow Version: 3.0.0-beta-6
Issue Kind (Bug, Question, Feature): Bug

Android Studio Project Conditions
- Instant Run is disabled
 - Using the [apt](https://bitbucket.org/hvisser/android-apt) plugins 
 - Incremental compilation is off.

Description: 

`Error:(56, 141) error: cannot find symbol variable BidModel_Table`

`Line 56: BidPayload bidPayloads = bitPayloadModelMapper.transformModelToPayload(new Select().from(BidModel.class).where(Condition.column(BidModel_Table.bidModelId).is(bidId)).querySingle());`

/**
 * Class that represents a bid in the presentation layer.
 */
```
@Table(database = XOverDatabase.class)
public class BidModel extends BaseModel {

  public static final String TABLE_NAME = "bid_table";

  public interface Columns {
    public static final String ID = "bid_id";
    public static final String TITLE = "bid_title";
    public static final String CREATED_AT = "bid_created_at";
    public static final String UPDATED_AT = "bid_updated_at";
    public static final String DESCRIPTION = "bid_description";
    public static final String STATUS = "bid_status";
  }

  @Column(name = Columns.ID)
  @Unique
  @PrimaryKey
  int bidModelId;

  @Column(name = Columns.TITLE)
  String title;

  @Column(name = Columns.DESCRIPTION)
  String description;

  @Column(name = Columns.STATUS)
  String status;
}
```

**Comment by carmas123** [comment]
Rebuild project, what is you Android Studio version?

**Comment by RowlandOti** [comment]
@carmas123 Android Studio 2.1 preview 5. I have already done countless
builds.

**Comment by carmas123** [comment]
Became to use 2.1 RC  :)
I found some problem from beta6 but if you Rebuild Project all work

**Comment by agrosner** [comment]
Are the classes gettting generated? are you using any other annotation processors?

**Comment by RowlandOti** [comment]
@agrosner,  the classes are not generated. I also use Dagger & Butterknife

**Comment by agrosner** [comment]
Are you using kapt or anything different than normal? Also are you sure you can't import the table classes?

**Comment by Suresh1988** [comment]
@agrosner  I am also facing the same issue. I am not using any library. For me the classes are generated but i am not able to import the tables classes. Still i am able to run the application

**Comment by agrosner** [comment]
importing classes would work when sources generated. not sure whats happening here.

**Comment by agrosner** [comment]
try with latest plugins (2.1.0 or higher), incremental off, incremental kotlin off (if kotlin)
