### ISSUE TITLE
Copy and replace DB file

### ISSUE THREAD

**Issue by noinnion** [Raizlabs/DBFlow#769]
DBFlow Version: 3.0.0-beta6
Issue Kind (Bug, Question, Feature): Question

Description: 

Hi, 
I have 2 versions of an app which use the same db structure. it is possible to duplicate the same content from 1 db to another? 

What I want to do is copy the db file from one device and replace it the one from another device. Init the app and use the new db file. It is possible with DbFlow?

Thanks

**Comment by agrosner** [comment]
if you can do a straight up file-copy before DBFlow is inialialized, I do not see why not. It's not out of the box supported, though.
