### ISSUE TITLE
Since beta6 json deserialization (by gson) of entities with @ForeignKey does not work

### ISSUE THREAD

**Issue by iostreamchik** [Raizlabs/DBFlow#770]
Success on 3.0.0-beta5 but not 3.0.0-beta6
Expose annotation / exclusion strategy doesn't help

`**TestModelContainer test = new Gson().fromJson(serializeJson, TestModelContainer.class);**`

```
@ModelContainer
@Table(database = Database.class, name = "TestModelContainer")
public class TestModelContainer extends BaseModel {
	@PrimaryKey(autoincrement = true)
	long id;
	@Column
	String name;
	@Column
	int age;
	@ForeignKey(saveForeignKeyModel = true)
	NestedModel nestedModel;
	List<NestArr> arrList;
}
```

```
@Table(database = Database.class, name = "NestedModel")
public class NestedModel extends BaseModel {
	@PrimaryKey
	long id;
	@Column
	String field1;
	@Column
	String field2;
	@Column
	String field3;
	@Column(typeConverter = StringListConverter.class)
	List strings;

	@ForeignKey
	ForeignKeyContainer<TestModelContainer> owner;

	public void associateOwner(TestModelContainer owner) {
		this.owner = FlowManager.getContainerAdapter(TestModelContainer.class)
				.toForeignKeyContainer(owner); // convenience conversion
	}
}
```

```
@Table(database = Database.class, name = "NestArr")
public class NestArr extends BaseModel {
	@PrimaryKey
	String id;

	@ForeignKey(saveForeignKeyModel = false)
	ForeignKeyContainer<TestModelContainer> container;

	public NestArr associate(TestModelContainer c) {
		container = FlowManager.getContainerAdapter(TestModelContainer.class).toForeignKeyContainer(c);
		return this;
	}
}
```

**Comment by agrosner** [comment]
Can you be more specific by "doesn't work"? Thank you.

**Comment by wajidp** [comment]
Attempt to invoke virtual method 'com.raizlabs.android.dbflow.structure.container.ForeignKeyContainer com.raizlabs.android.dbflow.structure.container.ModelContainerAdapter.toForeignKeyContainer(com.raizlabs.android.dbflow.structure.Model)' on a null object reference

**Comment by agrosner** [comment]
Looks like the `ModelContainerAdapter` is not found.

**Comment by agrosner** [comment]
Can't repro on my tests. Try rebuilding, reopen if still fails.

**Comment by thekalinga** [comment]
I'm facing the same issue.

```java
FlowManager.getContainerAdapter(TestModelContainer.class)
```

is returning null for reason. Any idea why this could happen?

**Comment by bytehala** [comment]
Same thing happens on my end. I debugged the app, and modelContainerAdapters is empty:

![empty-adapters]
(http://i.imgur.com/6U0dDSd.png)

Is there something I need to do?

**Comment by denisrai** [comment]
Having the same problem above 👎

**Comment by thekalinga** [comment]
In my case the issue was at my end.

I have kept the annotation `@ModelContainer` on the many side of the relationship, which is wrong. Make sure you keep `@ModelContainer` on the one side of one-to-many relationship.

See if this helps
