### ISSUE TITLE
Save Model Transaction

### ISSUE THREAD

**Issue by loctran106** [Raizlabs/DBFlow#772]
DBFlow Version: 3.0.0-beta6
Issue Kind: Question

In the current version of beta6, what is the new way of doing below? I simply can't figure out how to save a list of models...
`TransactionManager.getInstance().addTransaction(new SaveModelTransaction<>(ProcessModelInfo.withModels(listOfModels).result(new TransactionListener<List<Model>>() {
@Override
public void onResultReceived(List<Model> result) {
	//do something here
}

@Override
public boolean onReady(BaseTransaction<List<Model>> transaction) {
    return false;
}

@Override
public boolean hasResult(BaseTransaction<List<Model>> transaction, List<Model> result) {
    return result.size() > 0;
}
})));`

Also, can you explain what the DatabaseWrapper is?

`.beginTransactionAsync(new ITransaction() {
                @Override
                public void execute(DatabaseWrapper databaseWrapper) {
                    // do anything you want here.
                }`

Not exactly understanding this new update as well.  Could you point me to some solid examples of the above?

**Comment by agrosner** [comment]
its in the new docs I wrote: https://github.com/Raizlabs/DBFlow/blob/master/usage2/StoringData.md
or https://github.com/Raizlabs/DBFlow/blob/master/usage2/Migration3Guide.md#transactions-overhaul
