### ISSUE TITLE
How about the TypeConverter support List<String>,Set<String>

### ISSUE THREAD

**Issue by wangsuicheng** [Raizlabs/DBFlow#773]
The some like `List<T>` does't Support, but I think that It should support `List<String>` which only the type T is String.
That is your recommendation:
 `List<T>, Map<T>, etc. Best way to fix this is to create a separate table relationship`
But the String does't need to build a Table...

**Comment by agrosner** [comment]
If you use a `List` as `TypeConverter` that converts it to a string, that would suffice. Not something that's supported.
