### ISSUE TITLE
Cannot use withTable() in combination with as() when writing a query

### ISSUE THREAD

**Issue by dwaynehoy** [Raizlabs/DBFlow#775]
DBFlow Version: 3.0.0-beta6
Issue Kind: Bug

Description: 
Cannot use withTable() in combination of as() when writing a query, which means that retrieving columns with the same ids from table joins results in an ambiguous column name error.

The following code:
```
  SQLite.select(
                    Session_Table.id.withTable(), //This works fine
                    Program_Table.id.withTable().as("program_id"), //This doesn't work
                   ...
```

Results in the following query:
```
SELECT `session`.`id`,  `id` AS `program_id`, ...
```

**Comment by dwaynehoy** [comment]
For anybody with this issue I've written a small helper method below until this is fixed
```
public static IProperty withTableAs(BaseProperty property, String aliasName){
        NameAlias tableNameAlias = new NameAlias(FlowManager.getTableName(property.getTable()));
        NameAlias withTableNameAlias = new NameAlias(property.getNameAlias()).withTable(tableNameAlias.getAliasName());

        return  new LongProperty(property.getTable(), withTableNameAlias.getName(), aliasName);
    }
```

**Comment by agrosner** [comment]
fixed in `develop`. A new `NameAlias` and `NameAlias.Builder` class makes it work much easier now.

**Comment by agrosner** [comment]
but really the original query should work now, so workaround wont be needed
