### ISSUE TITLE
ForeignKeyContainer cannot find symbol variable

### ISSUE THREAD

**Issue by MarcoNica** [Raizlabs/DBFlow#776]
DBFlow Version: 
3.0.0-beta6

Issue Kind (Bug, Question, Feature): 
Bug

Description: 
When you have two classes(ModelA and ModelB) that extends BaseModel and one class (ModelB) uses the second(ModelA) as primary key, you will get a "cannot find symbol variable" error in ModelB_Container.ForeignKeyContainer<ModelB> toForeignKeyContainer(ModelB model).

Take a look at my example
[DBFlowTest.zip](https://github.com/Raizlabs/DBFlow/files/240082/DBFlowTest.zip)

**Comment by agrosner** [comment]
Im going to paste the tables here for reference.

ModelA
```java
@Table(database = MyDataBase.class)
@ModelContainer
public class ModelA extends BaseModel {
    @Column
    @PrimaryKey
    public int id;
    @Column
    public String Name;
}
```

ModelB
```java
@Table(database = MyDataBase.class)
@ModelContainer
public class ModelB extends BaseModel {
    @ForeignKey
    @PrimaryKey
    public ModelA modelA;
    @PrimaryKey
    public int subID;
}
```

**Comment by agrosner** [comment]
fixed i n`develop`
