### ISSUE TITLE
Support dynamically creating Db?

### ISSUE THREAD

**Issue by wangsuicheng** [Raizlabs/DBFlow#778]
I want to write a Content Provider, Having some different database named with MD5 value, these databases have the same Table. So, The demand is that, If I get the MD5 value which never match the database name,then create a new database named with the MD5 value, like "82926c5054b3fc5dc4df85eaadd418de.db", how to create database dynamically for this demand?

If I use this method:
`ContentUtils.insert(getContentResolver(), xxxx.CONTENT_URI, model);`
how do I judge which database I insert data into ?

**Comment by agrosner** [comment]
Dynamic databases are not supported as of now in DBFlow.
