### ISSUE TITLE
Documentation issue: String is used instead of int

### ISSUE THREAD

**Issue by csarnataro** [Raizlabs/DBFlow#780]
DBFlow Version: documentation in master branch
Issue Kind (Bug, Question, Feature): documentation issue

Description: 
On page https://github.com/Raizlabs/DBFlow/blob/master/usage2/Databases.md there are a couple of snippets where a wrong java declaration is used.

`public static final String VERSION = 1; `

should be

`public static final int VERSION = 1;`

And also

`public static final String VERSION = 2;`

should be

`public static final int VERSION = 2;`

**Comment by agrosner** [comment]
fixed in `develop`.
