### ISSUE TITLE
defaultValue for empty strings doesn't work

### ISSUE THREAD

**Issue by jozn** [Raizlabs/DBFlow#782]
DBFlow Version: "3.0.0-beta6"
Issue Kind: Bug

@Column(defaultValue="") for empty strings doesn't work, It  returns null, it doesn't save  to sqlite .

even for non empty string it fails to build correct (table)_Adaptor.java class
.
@Column(defaultValue = "")
    public String PhoneFamilyName;

Also has tried(this ones doesn't  build a correct (table)_Adaptor.java class)
@Column(defaultValue = "''")
@Column(defaultValue = "\"\"")
@Column(defaultValue = "ss")

**Comment by agrosner** [comment]
Nice catch! seems my null or empty check fails for this case :) ha.

**Comment by agrosner** [comment]
So for `String` you _must_ enclose itself in string literal "\"" so that DBFlow knows. So actually this is not a a bug. Doing a simple:
```
    @Column(defaultValue = "\"\"")

```
should do the trick.

**Comment by jozn** [comment]
Hi again:
The trick works tanks.
But there is still a problem:
 
```
@Column(defaultValue = "18")
   public int time;
```
defaultValue for numbers set to none zero doesn't works and it always is 0. (i check (table)_Adaptor.java class) for different combinations)

plus, i have switched from squidb to DBFlow, for simplicity. In squidb defaultValue was based on sqlite itself at creation time , but in DBFlow it is at saving, and loading time, it would be a good feather to add this "option" to DBFlow, because sometimes it makes more scene this way.
