### ISSUE TITLE
Saving large amounts of data is extremely slow with new Transactions?

### ISSUE THREAD

**Issue by marwfair** [Raizlabs/DBFlow#784]
DBFlow Version: 3.0.0-beta6
Issue Kind (Bug, Question, Feature): Question

Description: It is possible in my app to have to store several thousand models at once. I followed the docs and came up with this to save my models. It is taking 20+ minutes to save all of the data.

```java
FlowManager.getDatabase(AppDatabase.class)
                .beginTransactionAsync(new ProcessModelTransaction.Builder<> (
                        new ProcessModelTransaction.ProcessModel<Model>() {
                            @Override
                            public void processModel(Model model) {
                                model.save();
                            }
                        }).addAll(modelList).build())
                .error(new Transaction.Error() {
                    @Override
                    public void onError(Transaction transaction, Throwable error) {
                        Log.e(TAG, "Database transaction failed.", error);
                    }
                })
                .success(new Transaction.Success() {
                    @Override
                    public void onSuccess(Transaction transaction) {
                    }
                }).build().execute();
```

Something is definitely not right. In 3.0.0-beta5, saving the exact same data would only take ~3 minutes by doing this:

```java
TransactionManager.getInstance().addTransaction(new SaveModelTransaction<>(ProcessModelInfo.withModels(modelList)));
```

Any help would be appreciate!

**Comment by agrosner** [comment]
Quick questions: Are you using any kind of `ConflictAction`? Also can you specify your table that you're using here, so I can profile it. Thanks!

**Comment by marwfair** [comment]
@agrosner No, I'm not using any kind of ConflictAction. My database has around 50 tables in it, and the models that I am loading are a mix of most of them. I'm also populating helper tables to create relationships between models. Is there anything is particular that you are looking for?

**Comment by agrosner** [comment]
Are you possibly doing anything else with DB on different thread while this executes?

**Comment by agrosner** [comment]
It's plausible some of that is due to this line: 
```java
 Transaction.TRANSACTION_HANDLER.post(new Runnable() {
                    @Override
                    public void run() {
                        if (processListener != null) {
                            processListener.onModelProcessed(finalI, size, model);
                        }
                    }
                });
```
If should check if listener engaged outside the `ProcessModelTransaction` instead. So we're probably overloading the Main thread with unused calls here.

**Comment by agrosner** [comment]
I wrote a test that simply saves 10000 models at a time reverses the check simply reverses the `if` condition:
```
if (processListener != null) {
                    Transaction.TRANSACTION_HANDLER.post(new Runnable() {
                        @Override
                        public void run() {
                            processListener.onModelProcessed(finalI, size, model);
                        }
                    });
                }
```

Doing this on running JUNIT4 on my machine, cut execution time down by 33% at least. this might be more on a mobile device.

**Comment by agrosner** [comment]
in `develop`. I won't close this until it's tested more.

**Comment by agrosner** [comment]
should be faster now.

**Comment by marwfair** [comment]
@agrosner Awesome! Thank you so much
