### ISSUE TITLE
QueryResultCallback with List parameter 

### ISSUE THREAD

**Issue by comann** [Raizlabs/DBFlow#786]
DBFlow Version: 3.0.0-beta6
Issue Kind (Feature):
**Description:**
Is there an existing way to create an asynchronous query that returns a list?

**Existing Code:**
  ```java
 SQLite.select()
                    .from(CustomBaseModel.class)
                    .where(CustomBaseModel_Table.Id.eq(id))
                    .async()
                    .queryResultCallback(new QueryTransaction.QueryResultCallback<InspireColor>() {
                        @Override
                        public void onQueryResult(QueryTransaction transaction, @NonNull CursorResult<InspireColor> tResult) {
                        }
                    })
                    .execute();
```

**Proposed Code:**
```java
  SQLite.select()
                    .from(CustomBaseModel.class)
                    .where(CustomBaseModel_Table.Id.eq(id))
                    .async()
                    .queryResultCallback(new QueryTransaction.QueryResultCallback<InspireColor>() {
                        @Override
                        public void onQueryResult(QueryTransaction transaction, @NonNull List<TResult> results) {
                        }
                    })
                    .execute();
```

This would help offload the time it takes to process the cursor off the main ui thread and put it in the background.

**Comment by agrosner** [comment]
I see. that makes perfect sense.

**Comment by agrosner** [comment]
Use `queryListResult()` method which will provide what you're lookin for :)

**Comment by comann** [comment]
Awesome. Thanks for the speedy reply and enhancement. Do I need to pull in the source into my project or is there a new beta release (i.e. 3.0.0-beta7)?

**Comment by agrosner** [comment]
Probably will be 3.0.0. For now you'll need to pull in `develop` to see the
change or pull in latest commit from jitpack.io

**Comment by agrosner** [comment]
compile
'com.github.Raizlabs.DBFlow:dbflow:develop-3.0.0-beta6-g816c5cd-37'

**Comment by agrosner** [comment]
ensure you use same version on all pieces of dbflow
