### ISSUE TITLE
Classes in sub-packages are not properly recognized

### ISSUE THREAD

**Issue by BlacksWise** [Raizlabs/DBFlow#788]
DBFlow Version: 3.0.6 Beta
Question / (Issue): Classes in sub-packages are not properly recognized

Description: 
I experienced a stranged issue, when I tried to integrate DBFlow in my project. If I put the classes I want to connect with the Database into the main-package everything works fine. On the other hand, if I put them into a sub package the Adapter-Classes of the packages throws an error.

My package Structure:
Main -> AppDatabase
Main -> LevelAPI -> Levels
Main -> LevelAPI -> Listener
Main -> LevelAPI -> Mapper
Main -> LevelAPI -> Restrictions

The classes I want to integrate into the DB are all placed unter Levels. For each of those Classes I get the same Error: error: cannot find symbol class LevelAPI. 

This is the import Declaration of one of the Adapter Classes.

```
package com.raizlabs.android.dbflow.config;

import de.uni_muenster.algo_git.pspsy.AppDatabase.AppDatabase;
>>> import de.uni_muenster.algo_git.pspsy.LevelAPI;
import de.uni_muenster.algo_git.pspsy.LevelAPI.Levels.Level_Adapter;
import de.uni_muenster.algo_git.pspsy.LevelAPI.Levels.Levelelement_Adapter;
import java.lang.Class;
import java.lang.Override;
import java.lang.String;
```
The Line marked with >>>> is marked as an unused import Statement by Android Studio, but those things fail with the error: Can not resolve Symbol 'LevelAPI'.

holder.putDatabaseForTable(LevelAPI.Levels.Levelelement.class, this);

I'm pretty sure I did something wrong there, but have no clue whatsoever.

Best Regards,
Andre

**Comment by agrosner** [comment]
Package names with **C**apital names are not supported.

**Comment by agrosner** [comment]
Since the Annotation processor treats them as classes and not packages.
