### ISSUE TITLE
Error:(3, 0) Cause: com/raizlabs/GriddlePlugin : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by jiqimaogou** [Raizlabs/DBFlow#79]
can you compile GriddlePlugin with java 1.6?

**Comment by boxlady** [comment]
I'm getting the same error but I'm compiling with 1.7

**Comment by ianrumac** [comment]
Use Griddle version 1.0.3.

**Comment by agrosner** [comment]
I'll update the usage docs. I compiled the plugin with 1.8 vs specifying a 1.5 compatibility so people using jdk < 1.8 could use it.

**Comment by agrosner** [comment]
updated usage docs, closing. Reopen if it fails.
