### ISSUE TITLE
Additional Setup for Unit Tests

### ISSUE THREAD

**Issue by jdrider** [Raizlabs/DBFlow#791]
**DBFlow Version**: 3.0.0-beta6
**Issue Kind**: Question

**Description**: Currently, out of the box, 106/107 unit tests fail on the develop branch.  The error in a majority of them is `com.raizlabs.android.dbflow.structure.InvalidDBConfiguration: Database: com.raizlabs.android.dbflow.test.TestDatabase is not a registered Database. Did you forget the @Database annotation?`.  I run the command `gradlew dbflow-tests:test`.

Is there some additional setup or configuration needed for the tests to work?  Or are the tests currently broken?

**Comment by agrosner** [comment]
No its a Kotlin KAPT issue. https://youtrack.jetbrains.com/issue/KT-11978

**Comment by AdamSHurwitz** [comment]
What is the best way to write tests for DBFlow?
