### ISSUE TITLE
Order of ModelView creations is incorrect

### ISSUE THREAD

**Issue by tranngoclam** [Raizlabs/DBFlow#793]
DBFlow Version: 3.0.0-beta5
Issue Kind (Bug, Question, Feature): Question

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
Hi.

I'm working with ModelView in DBFlow and having some questions below:

1. How to run a ModelViewQuery with JOIN statement to multiple tables? I tried with some tables but the JOIN statement returned the JOIN class, not the VIEW after using SELECT statement.

2. How to run a ModelViewQuery in a ModelView using some child ModelView ? The ORDER of Views creations is not correct, so maybe the VIEW A (include JOIN statement with VIEW B) is created after VIEW B was created.

Thanks

**Comment by agrosner** [comment]
1. `queryCustomList(SomeQueryModelClass.class)`. If you're doing some complicated join and it might not map to an existing table, use [query models](/usage2/QueryModels.md)

2. `@ModelView(priority = )`

**Comment by agrosner** [comment]
2 is in `develop` currently. pending 3.0.0 release
