### ISSUE TITLE
How to log the sql query that i used ?

### ISSUE THREAD

**Issue by mohamed-habib** [Raizlabs/DBFlow#798]
DBFlow Version: 3.0.0-beta5
Issue Kind (Question):

Description: 
Is there a way to know the sql statement that is queried ?

for example, i made this query: 

`SQLite.select()
  .from(Location.class)
  .where(Location_Table.latitude.eq(home.getLatitude()))
  .and(ConditionGroup.clause()
      .and(Location_Table.latitude
        .minus(PropertyFactory.from(home.getLatitude())
        .eq(1000L))))`

 i want to know the translation of it which is:

`SELECT * FROM `Location` WHERE `latitude`=45.05 AND (`latitude` - 45.05) = 1000`

**Comment by agrosner** [comment]
`getQuery()` and then you can log it.

**Comment by mohamed-habib** [comment]
Another thing, can i write native sql query ?
