### ISSUE TITLE
Manual / Non gradle Setup?

### ISSUE THREAD

**Issue by Willey1986** [Raizlabs/DBFlow#80]
Is it possible to install this library manually in my project? I'm working on a project without any automated build tools and need to import a *.jar to my project. Unfortunately there is only a *.aar file which I cannot use (or don't know how to use)

**Comment by agrosner** [comment]
If you're not using Gradle, you probably are out of luck. This project requires using APT and is built to work on gradle. If you are using Eclipse, I would recommend forking, cloning as submodule and modifying it to fit your needs. I do not support that the old way, sorry.
