### ISSUE TITLE
SQLite._case not support to select column

### ISSUE THREAD

**Issue by JamesKarl** [Raizlabs/DBFlow#803]
I am not sure that whether DBFlow doesn't support such a feature.
**SQLite Table**
`
CREATE TABLE Message
(
    id INTEGER PRIMARY KEY,
    sender TEXT,
    receiver TEXT,
    body TEXT,
    type TEXT,
    birthday INTEGER,
    status INTEGER
);
`

**What I want to do**
`
SELECT
  CASE sender
  WHEN 'SELF'
    THEN receiver
  ELSE sender END AS username,
  type,
  body
FROM Message
GROUP BY username;
`
**_NOTE_**: both receiver and sender are columns of table Message.

**What DBFlow does**
`
SELECT
  CASE sender
  WHEN 'SELF'
    THEN 'receiver'
  ELSE 'sender' END AS username,
  type,
  body
FROM Message
GROUP BY username;
`
**_NOTE_**: both receiver and sender are constant strings here.

**My Code**
`@ModelView(database = DemoDatabase.class)
public class Conversation extends BaseModelView<Message> {

    public static final String COLUMN_USERNAME = "username";

    @Column
    public String username;

    @Column
    public String type;

    @Column
    public String body;

    @Column
    public long birthday;

    private static IProperty PROPERTY_USERNAME = SQLite._case(Message_Table.sender)
            .when(Message.SENDER_SELF)
            .then(Message_Table.receiver.getNameAlias().getName())
            ._else(Message_Table.sender.getNameAlias().getName())
            .end(COLUMN_USERNAME);

    @ModelViewQuery
    public static final Query QUERY = SQLite.select(
            PROPERTY_USERNAME,
            Message_Table.type,
            Message_Table.body,
            Message_Table.birthday)
            .from(Message.class)
            .groupBy(new NameAlias(COLUMN_USERNAME))
            .orderBy(Message_Table.birthday, false);

}
`

**Comment by agrosner** [comment]
Oh I see what you are talking about. Is this valid SQLite, passing column names in a case statement?

**Comment by JamesKarl** [comment]
Thanks very much for your response.

Yes. It's valid. I have tested the following SQL stmt from the command line (sqlite3).

`SELECT CASE sender WHEN 'SELF' THEN receiver ELSE sender END AS username, type, body FROM Message GROUP BY username;`

**Comment by agrosner** [comment]
done. in `develop`.

**Comment by JamesKarl** [comment]
Thanks very much for your efforts.
