### ISSUE TITLE
Is it possible to generate the AUTHORITY of the ContentProvider using App pageName 

### ISSUE THREAD

**Issue by sp958857** [Raizlabs/DBFlow#805]
I want to use the contentProvider in variant package. So the AUTHORITY should be different with each other. Is it possible?

I want something like that:
 ``<provider android:authorities="${applicationId}"
/>
``

``
@ContentProvider(
        authority = CompulsoryBase.AUTHORITY,
        database = CompulsoryBase.class,
        baseContentUri = CompulsoryBase.BASE_CONTENT_URI)
@Database(name = CompulsoryBase.NAME, version = CompulsoryBase.VERSION)
public class CompulsoryBase {
    public static final String NAME = "CompulsoryLearning";

    public static final int VERSION = 1;

    public static final String AUTHORITY = ******;//which should be same with packageName, for example: context.getPackageName(), but the annonation value should be constant, what can I do?

    public static final String BASE_CONTENT_URI = "content://";

}
``

**Comment by agrosner** [comment]
create a `BuildConfigField` object that creates the value for you in the `BuildConfig` class.
