### ISSUE TITLE
OrderBy CaseSensitive

### ISSUE THREAD

**Issue by carmas123** [Raizlabs/DBFlow#809]
DBFlow Version: 3.0.0beta6
Issue Kind (Bug, Question, Feature):Question. Bug

Description: 
I'm try to sort my query of Model that have a column with NOCASE collation but it doesn't work.
How can I use orderBy or like filter without case sensitive?

**Comment by agrosner** [comment]
http://stackoverflow.com/a/973785 maybe this helps?

**Comment by agrosner** [comment]
it also only works with ASCII text

**Comment by carmas123** [comment]
Oh, yes it's true thank you...can be closed :)
