### ISSUE TITLE
How to store a list of object in Sqlite database

### ISSUE THREAD

**Issue by pascalito007** [Raizlabs/DBFlow#810]
DBFlow Version:3.0.0-beta5
Issue Kind (Bug, Question, Feature):Question

Description: Please how to store list of object table in sqlite database. 
Thanks

**Comment by agrosner** [comment]
its in the the documentation under [storing data](/usage2/StoringData.md)

**Comment by pascalito007** [comment]
In documentation I read this:
ProcessModelTransaction<TestModel1> processModelTransaction =
        new ProcessModelTransaction.Builder<>(new ProcessModelTransaction.ProcessModel<TestModel1>() {
            @Override
            public void processModel(TestModel1 model) {
                processCalled.set(true);
            }
        }).processListener(new ProcessModelTransaction.OnModelProcessListener<TestModel1>() {
            @Override
            public void onModelProcessed(long current, long total, TestModel1 modifiedModel) {
                modelProcessedCount.incrementAndGet();
            }
        }).addAll(items).build();
Transaction transaction = database.beginTransactionAsync(processModelTransaction).build();
transaction.execute();

In my case:
I have a list of Country in java.util.List for exemple: I want to store countryList (List<Country> countryList) but I do not know how to apply the code in documentation.
I am french. Sorry for my bad english.
Thanks
