### ISSUE TITLE
Store in Sqlite database

### ISSUE THREAD

**Issue by pascalito007** [Raizlabs/DBFlow#811]
DBFlow Version:3.0.0-beta5
Issue Kind (Bug, Question, Feature):Bug

Description: 
In documentation, to store list of object, I read this:

`ProcessModelTransaction<TestModel1> processModelTransaction =
        new ProcessModelTransaction.Builder<>(new ProcessModelTransaction.ProcessModel<TestModel1>() {
            @Override
            public void processModel(TestModel1 model) {
                processCalled.set(true);
            }
        }).processListener(new ProcessModelTransaction.OnModelProcessListener<TestModel1>() {
            @Override
            public void onModelProcessed(long current, long total, TestModel1 modifiedModel) {
                modelProcessedCount.incrementAndGet();
            }
        }).addAll(items).build();
Transaction transaction = database.beginTransactionAsync(processModelTransaction).build();
transaction.execute();`

 In my case I wante to store a list of country (countryList). When I past this code in my Editor,  new ProcessModelTransaction.Builder<> is not found and Transaction class is not found. How can I apply this code for my exemple.
Please.

`ProcessModelTransaction<Country> processModelTransaction =
        new ProcessModelTransaction.Builder<>(new ProcessModelTransaction.ProcessModel<Country>() {
            @Override
            public void processModel(Countrymodel) {
                processCalled.set(true);
            }
        }).addAll(countryList).build();
Transaction transaction = database.beginTransactionAsync(processModelTransaction).build();
transaction.execute();`

Thanks

**Comment by agrosner** [comment]
ah you're on beta5 nott beta6. Beta6 has significant changes in that sense. if you can upgrade do it, otherwise use:
```
TransactionManager.getInstance().addTransaction(new SaveModelListTransaction<>(models));
```

**Comment by pascalito007** [comment]
Thanks.
Please what is the Class of  database => `database.beginTransactionAsync` and what is can I put at  `processCalled.set(true);`
