### ISSUE TITLE
.AAR library using DBFlow

### ISSUE THREAD

**Issue by romulolemes** [Raizlabs/DBFlow#812]
I had previously opened an issue #804. But just to clarify, so it's possible to create a library (that uses DBFlow) using .aar format, then add it to my application (that also uses DBFlow)?

**Comment by agrosner** [comment]
yeah to do it use multiple modules (https://github.com/Raizlabs/DBFlow/blob/master/usage2/MultipleModules.md). If you need help creating the aar, this is not the place to ask it :P
