### ISSUE TITLE
how to use  CAST(expr AS target_type) ?

### ISSUE THREAD

**Issue by wsy858** [Raizlabs/DBFlow#817]
i want to write sql like  " SELECT max(CAST(orderIndex as integer)) from Portfolio  where groupId='0';   " ,  because the orderIndex 's type is TEXT

**Comment by agrosner** [comment]
now you can via: 
```java
SQLite.select(Method.max(Method.cast(Portfolio_Table.orderIndex).as(SQLiteType.INTEGER)))
    .from(Portfolio.class)
    .where(Portfolio_Table.groupId.eq("0"))
```
in `develop`, for 3.0
