### ISSUE TITLE
OOM Crash In  Version: 3.0.0-beta5 

### ISSUE THREAD

**Issue by JeremyLam1** [Raizlabs/DBFlow#818]
DBFlow Version: 3.0.0-beta5
Issue Kind (Bug, Question, Feature): Bug

Description: 
 hi，i use DBFlow Version: 3.0.0-beta5 in my project，i run my app is normal for the first time，but run my app for the second time , OOM Crash happened. i just use the annotation like this:

@Database(name = AppDatabase.NAME, version = AppDatabase.VERSION, **backupEnabled = true, consistencyCheckEnabled = true**)
public class AppDatabase {
...
...
}

i want to support the function that DB backup, so i add this: **backupEnabled = true, consistencyCheckEnabled = true**, then the question happened.

**Comment by agrosner** [comment]
Fixed in develop
