### ISSUE TITLE
DBFlow global logging of successful queries

### ISSUE THREAD

**Issue by filipc** [Raizlabs/DBFlow#820]
DBFlow Version: 3.0.0-beta6
Issue Kind (Question):

During development process I'd like to turn on global logging of all SQL queries that are executed by DBFlow.

I've found that there is:  

```FlowLog.setMinimumLoggingLevel(FlowLog.Level.V); ``` 

but it is not logging anything but errors since nowhere in code FlowLog is used to log success queries.
It is possible to log all queries by now?

**Comment by agrosner** [comment]
You can always call `getQuery()` on whatever you execute and log it yourself.

**Comment by agrosner** [comment]
wont do logging on successful queries, but will do on any raw query run through the language wrappers.

**Comment by agrosner** [comment]
in `develop`.

**Comment by zmorris** [comment]
If someone needs to also log `insert` and `update`, please see my attempts at https://github.com/Raizlabs/DBFlow/issues/607#issuecomment-360009079
