### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by maestr0ua** [Raizlabs/DBFlow#821]
DBFlow Version: 3.0.0-beta6
Issue Kind: Bug

Description: getting this error
android.database.sqlite.SQLiteException, near ")": syntax error (code 1): , while compiling: SELECT * FROM `LocationTable` WHERE (`type`='country' AND (`_id`='572b60d432f3d0985041994c' OR `_id`='572b60d432f3d0985041994c') AND )

```
ConditionGroup conditionGroup = ConditionGroup.clause()
                .and(LocationTable_Table.type.eq(Constants.COUNTRY))
                .and(ConditionGroup.clause()
                        .and(LocationTable_Table._id.eq(ids.get(0)))
                        .or(LocationTable_Table._id.eq(ids.get(1))));

SQLite.select()
      .from(LocationTable.class)
      .where(conditionGroup)
      .queryList());

```

Somehow in the end of the query shows up operator AND

**Comment by agrosner** [comment]
good catch!

**Comment by agrosner** [comment]
fixed in `develop`.

**Comment by maestr0ua** [comment]
Thank you for a quick answer!
