### ISSUE TITLE
can we listen to migration status?

### ISSUE THREAD

**Issue by TheWhiteLlama** [Raizlabs/DBFlow#822]
DBFlow Version: 3.0.0-beta6
Issue Kind (Bug, Question, Feature): Question

Hi there!
Is it currently possible to listen to the current status of a migration? Since I've a migration that takes a couple of seconds for converting data into a new schema I'd like to show the user some kind of migration-progress or even that there's kind of a conversion running. Is that somehow possible at the moment?

Description: Is it possible to listen to the status of an ongoing migration?

**Comment by agrosner** [comment]
@TheWhiteLlama not currently, unless you register statically to some class in `onPreMigrate()` and `onPostMigrate()`

**Comment by TheWhiteLlama** [comment]
thanks for the quick answer I will try that!
