### ISSUE TITLE
comparing formatted dates

### ISSUE THREAD

**Issue by maestr0ua** [Raizlabs/DBFlow#823]
DBFlow Version:3.0.0-beta6
Issue Kind (Bug, Question, Feature):Question

Description: How can I make query for comparing two dates as string parameter?
This is how a I`m trying, but this is not working
```
@Table(database = ***.class)
public class InStoreTable extends BaseModel {

    @PrimaryKey
    String _id;

    @Column
    String creationDate;
}

SQLite.select()
         .from(InStoreTable.class)
         .where(InStoreTable_Table.creationDate.greaterThanOrEq("strftime('%Y-%m-%dT%H:%M:%S.%f', '2016-05-01T10:22:50.878Z')"));
```

**Comment by agrosner** [comment]
what is the RAW SQLite query of this? the result of `getQuery()` on the statement?

**Comment by maestr0ua** [comment]
SELECT * FROM `InStoreTable` WHERE `creationDate`>='strftime(''%Y-%m-%dT%H:%M:%S.%f'', 2016-05-01T18:48:17.329Z)'

**Comment by maestr0ua** [comment]
Maybe the problem is in the duplicated quotes? **'**'%Y-%m-%dT%H:%M:%S.%f**'**'

I put the time format in the single quotes, but in the query they are dupliceted

**Comment by maestr0ua** [comment]
and the second question. How can I format Property (in my case - InStoreTable_Table.creationDate)? I want to make something like this:

SELECT * FROM InStoreTable WHERE strftime('''%Y-%m-%d', creationDate)>='strftime('%Y-%m-%d', 2016-05-01T18:48:17.329Z)'

**Comment by maestr0ua** [comment]
I guess the problem is in duplicated single quotes. Cause next code works correctly.

```
String query = SELECT * FROM 'InStoreTable' WHERE  (`creationDate` >= strftime('%Y-%m-%dT%H:%M:%S.%f', '2016-05-10T00:00:00.000Z')) 

SqlUtils.queryList(InStoreTable.class, query);
```

**Comment by agrosner** [comment]
as a hack try this:
```java
SQLite.select()
         .from(InStoreTable.class)
         .where(InStoreTable_Table.creationDate.greaterThanOrEq(PropertyFactory.from(new StringQuery<>(InStoreTable.class, "strftime('%Y-%m-%dT%H:%M:%S.%f', '2016-05-01T10:22:50.878Z')")));
```

**Comment by agrosner** [comment]
remove unnecessary wrap in `StringQuery` just now.
