### ISSUE TITLE
How can I set the database file path

### ISSUE THREAD

**Issue by purebaba** [Raizlabs/DBFlow#825]

**Comment by agrosner** [comment]
not supported. We use the `SQLiteOpenHelper` which stores it in app private storage.

**Comment by StormKern** [comment]
You are incorrect @agrosner.  You can specify the location of the database.  SQLiteOpenHelper inevitably calls Context#getDatabaseFile(String name).  In your main Application class, override that method and specify the location you want, you'll need to do your own integrity checks however.

**Comment by liyinyin** [comment]
@StormKern Testing Override Application#getDatabasePath(String name), Not working. Have any  suggestions? Without solution, I will change to other db libs.

**Comment by trevjonez** [comment]
@liyinyin you are doing it wrong if it isn't working. I have used that method before to facilitate migration testing

**Comment by carmas123** [comment]
You can use applicationContext when init FlowManager with a FlowConfig.Builder and override getDatabasePath into your application class.
