### ISSUE TITLE
Generated code should utilize JSR250

### ISSUE THREAD

**Issue by trevjonez** [Raizlabs/DBFlow#826]
DBFlow Version:3.0.0-beta6
Issue Kind: Enhancement

Description: 
Generated code has javadoc labeling the code as generated, javax.annotation.Generated should be considered a more appropriate marking mechanism.

The consuming module can optionally add this line if seeing red in generated source is bothersom. 
I speculate that the annotations `@Retention(SOURCE)` causes it to be optional
`provided 'javax.annotation:jsr250-api:1.0'`

The processor module can then include the dependency with this line:
`compileOnly 'javax.annotation:jsr250-api:1.0'`
although the `compileOnly` config does require upgrading to gradle 2.12 ([source](http://gradle.org/blog/compile-only-dependencies/))

**Comment by agrosner** [comment]
not high on priority list. what benefit does this provide?

**Comment by trevjonez** [comment]
Just a more formal way of labeling things, after all they wrote the spec so people could use it.

The main think I like is the dedicated location for the time stamp, can help if you are fighting with build issues like we seem to do in the ever changing android tools landscape.

**Comment by agrosner** [comment]
not going to implement. I think it adds another dependency in the lib.
