### ISSUE TITLE
Add support for collections when passing to In clause

### ISSUE THREAD

**Issue by ursusursus** [Raizlabs/DBFlow#827]
DBFlow Version:
Issue Kind (Feature):

Description: 
Please add support for collections as arguments for In clause, varargs are pretty useless when I have arraylist of ids and dont want to create array just to be able to pass it in, thrashing memory. 

Looking at source it should not be a problem.
Plus I dont understand the need of "firstValue" argument anyways, cant the library just pick 0th item and then iterate the rest?

Thanks

**Comment by agrosner** [comment]
its already in there since like beta5 or 4

**Comment by ursusursus** [comment]
Ive synced with beta6 and I dont see it. Looking at sources, where should it be? https://github.com/Raizlabs/DBFlow/blob/develop/dbflow/src/main/java/com/raizlabs/android/dbflow/sql/language/property/IntProperty.java#L130
