### ISSUE TITLE
Multi-database query and read-only database

### ISSUE THREAD

**Issue by kvid** [Raizlabs/DBFlow#828]
DBFlow Version: 3.0.0-beta6
Issue Kind (Bug, Question, Feature): Question

Description: 

1) I there a way to make a combined query from tables in two different databases?
    1.1) Is there a way to ATTACH one or more databases to a main database connection?

2) Does it help if one of the databases can be read-only?
2.1) Does DBFlow allow opening a database in read-only mode to inhibit write access?
2.2) Is it possible to append "mode=ro" as a query parameter in the filename as an URI?
        https://www.sqlite.org/uri.html

3) One use case is a main read-write database at the default location that can relate to entries in a large read-only database (shipped in APK assets or downloaded).
3.1) The ideal solution would perhaps be to read-only-open a database directly from assets to avoid extra space requirements by copying it first, but this seems to be impossible.
       http://stackoverflow.com/questions/9911004/open-sqlite-in-readonly-directly-from-assets
3.2) On phones with a small internal storage, the large read-only database could be located on the external SD-card, but according to issue #825, this seems to be unsupported.

**Comment by agrosner** [comment]
1. Not supported but is plausible
1.1. Not a question for DBFlow, not supported

2. Not supported
2.1. Not supported
2.2. not supported, might be possible

3. Id suggest that you just share the same DB. It seems like its pretty complicated from your end.

**Comment by kvid** [comment]
Thank you for the fast responce.

1) SQLite supports something like:
ATTACH DATABASE 'big_database.db3' AS dict;
SELECT * FROM main.w UNION SELECT * FROM dict.w ORDER BY key;
SELECT main.w.*, dict.w.value AS dvalue FROM main.w LEFT JOIN dict.w USING key;

Is this something that DBFlow could support in a future version? A DBFlow query syntax could be the same as if the two tables are located in the same database, but the ATTACH statement must be added somehow.

2.2) Is that a "might be possible" in the current version or in a future version?

3) I agree that it might make the queries simpler. However, it creates some challenges when it comes to deploying updated versions of the big database without touching the user updated main database.
3.2) Do you consider supporting custom file paths (e.g. to external SD) in a future version?

**Comment by agrosner** [comment]
1. It could be supported in a future version if you mean the SQlite query language. But alas you can just call to the database directly via `FlowManager.getDatabase(...).execSql("ATTACH DATABASE 'big_database.db3' AS dict)"` then use the wrapper language to construct `@QueryModel` that result of each complex select statements. I am not sure though of the cross DB queries if theres a specific db you must run the query on and if dbflow would work for that.
2.2. Can't remember now. haha been too long.
3.2. Potentially, but not on my radar as of now. You can pass a `ContextWrapper` which overrides `getDatabasePath()` to provide your URI I believe.
