### ISSUE TITLE
Table's many-to-many relations with itself should allow to specify field names

### ISSUE THREAD

**Issue by bryant1410** [Raizlabs/DBFlow#829]
_DBFlow version:_ 3.0.0-beta6
_Issue Kind:_ Feature

_Description:_

It would be nice if `@ManyToMany` allows you to define field names. This is especially useful when using tables' relations with themselves, in which `table0` and `table1` can be confusing field names.

Maybe 2 new fields can be added in the attribute `@ManyToMany` allowing to specify the fields names. Then in `ManyToManyDefinition` when creating the column the class could save the field names and check for them when defining the columns.

/cc @matir91

**Comment by agrosner** [comment]
Pretty simple to implement.

**Comment by agrosner** [comment]
done. in `develop`

**Comment by bryant1410** [comment]
Woow that was fast. Thanks! :smile:
