### ISSUE TITLE
DBBatcheSaveQueue does not save models

### ISSUE THREAD

**Issue by trevjonez** [Raizlabs/DBFlow#830]
DBFlow Version: 3.0,0-beta6
Issue Kind: bug

Description: In file [DBBatchSaveQueue.java @ line 126](https://github.com/Raizlabs/DBFlow/blob/master/dbflow/src/main/java/com/raizlabs/android/dbflow/runtime/DBBatchSaveQueue.java#L126) the tmpModels list is never added to the ProcessModelTransaction thus the models are never saved to the database.

adding `.addAll(tmpModels)` should suffice?

**Comment by agrosner** [comment]
Wow. Good find. Haha! Thank you. That'll be fixed soon

**Comment by agrosner** [comment]
fixed in `develop`.
