### ISSUE TITLE
Database Migration fails with Views.

### ISSUE THREAD

**Issue by danvwells** [Raizlabs/DBFlow#831]
DBFlow Version: 3.0.0-beta6
Issue Kind: Bug

Description: 

In version 1, I create a @ModelView, as well as some @Models.  In version 2, I add a @Column to one of the @Models, and implement a @Migration for adding that column.  When onUpgrade of BaseDatabaseHelper occurs, during executeCreations, the view is attempted to be created again, throwing an exception.

**Comment by danvwells** [comment]
submitted pull request: https://github.com/Raizlabs/DBFlow/pull/832

**Comment by agrosner** [comment]
made it into `3.0.0` :)

**Comment by danvwells** [comment]
great, thank you!
