### ISSUE TITLE
Store data with ManyToMany relationship

### ISSUE THREAD

**Issue by tranngoclam** [Raizlabs/DBFlow#833]
DBFlow Version: 3.0.0-beta5
Issue Kind (Bug, Question, Feature): Question

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
Hi, I have 2 models like `Room` and `User` which they have @ManyToMany relationship. How do I define these models in order to when I store 2 instance of them, the Room_User table has 2 row accordingly.

Thanks

**Comment by agrosner** [comment]
`@ManyToMany` is not a managed relationship, but rather a compile time generation relationship. Meaning only the join table is created. There is no management like `@OneToMany` provides. you will have to do it manually.
