### ISSUE TITLE
Where is the TransactionManager? how can i use Transaction easily？

### ISSUE THREAD

**Issue by purebaba** [Raizlabs/DBFlow#839]
I find some docs for DBFlow,all those docs say using TransactionManager like this:
TransactionManager.getInstance().addTransaction()
....

but i could not find TransactionManager class

**Comment by agrosner** [comment]
Gone. look at (https://github.com/Raizlabs/DBFlow/blob/master/usage2/Migration3Guide.md#transactions-overhaul)
