### ISSUE TITLE
How can create listView via simpleCursorAdapter   

### ISSUE THREAD

**Issue by msoa** [Raizlabs/DBFlow#840]
DBFlow Version: 3.0.0-beta6
Issue Kind (Question):
How can create list view with **SimpleCursorAdapter** ? Following is my code but i get the fatal error:

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.saraylu.khayyatan/com.example.saraylu.khayyatan.CustomerListActivity}: java.lang.IllegalArgumentException: column '_id' does not exist

```
    FlowCursorList<Customer> cursor = new     FlowCursorList<>SQLite.select().from(Customer.class));
        SimpleCursorAdapter adapter = new SimpleCursorAdapter(this,
                R.layout.customer_list,
                cursor.getCursor(),
                new String[]{"name", "mobile"},
                new int[]{R.id.textView1, R.id.textView2});
        ListView listView = (ListView) findViewById(R.id.listView);
        listView.setAdapter(adapter);
```

**Comment by msoa** [comment]
I resolved the above issue with this change: change column **id** to **_id** with **alias**
```
        FlowCursorList<Customer> cursor = new FlowCursorList<>(SQLite.select(
                Customer_Table.id.as("_id"),
                Customer_Table.name.as("name"),Customer_Table.mobile.as("mobile"),Customer_Table.tel.as("tel")
        ).from(Customer.class));
```

Know on line `listView.setAdapter(adapter);` i get this error:

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.saraylu.khayyatan/com.example.saraylu.khayyatan.CustomerListActivity}: java.lang.NullPointerException

**Comment by agrosner** [comment]
Do you know that 
```
Customer_Table.id.as("_id"),            Customer_Table.name.as("name"),Customer_Table.mobile.as("mobile"),Customer_Table.tel.as("tel")
```
Is redundant? 

Also is the table's column name in SQLite "_id" or "id" ? Might make sense to set that in code too.

**Comment by msoa** [comment]
Yes, `Customer_Table.name.as("name"),Customer_Table.mobile.as("mobile"),Customer_Table.tel.as("tel")` are redundant, but `Customer_Table.id.as("_id"), ` no, because **SimpleCursorAdapter** need a column named `_id`. It's right?
**id** column is defined in model and dbflow take it. 
Model is:
```
package com.example.saraylu.khayyatan;

import com.raizlabs.android.dbflow.annotation.Column;
import com.raizlabs.android.dbflow.annotation.PrimaryKey;
import com.raizlabs.android.dbflow.annotation.Table;
import com.raizlabs.android.dbflow.structure.BaseModel;

@Table(database = MyDatabase.class)
public class Customer extends BaseModel {

    @PrimaryKey(autoincrement = true)
    long id;

    @Column
    String name;

    @Column
    String tel;

    @Column
    String mobile;

    @Column
    String address;

    @Column
    String createDate;


    public void setName(String name) {
        this.name = name;
    }
    public void setTel(String tel) {
        this.tel = tel;
    }
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public void setAddress(String address) {
        this.address = address;
    }
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

}

```

**Comment by msoa** [comment]
@agrosner  Is there other way without aliasing **id** column?

**Comment by agrosner** [comment]
`@Column(name="_id")`
