### ISSUE TITLE
 Cannot find symbol class XXXX_Table used like field reference in a select condition

### ISSUE THREAD

**Issue by pablopatarca** [Raizlabs/DBFlow#841]
DBFlow Version: 3.0.0-beta2
Issue Kind (Bug, Question, Feature): Cannot find symbol class XXXX_Table generated by dbflow

Description: 
Hi, I'm using gradle build tools v2.1.0 on android studio and I've this query:

SQLite.select()
           .from(Episode.class)
           .where(Episode_Table.id.is(id))
           .queryList();

and after to execute "run app" I get the following error:

:app:compileDebugJavaWithJavac
/my_path/data/dao/EpisodeDAO.java
Error:(4, 37) error: cannot find symbol class Episode_Table
/my_path/data/dao/VisitDAO.java
Error:(4, 37) error: cannot find symbol class Visit_Table
/my_path/loaders/VisitCheckInLoader.java
Error:(10, 37) error: cannot find symbol class Visit_Table
/my_path/loaders/VisitCheckOutLoader.java
Error:(10, 37) error: cannot find symbol class Visit_Table
/my_path/loaders/VisitScheduleLoader.java
Error:(9, 37) error: cannot find symbol class Visit_Table
/my_path/loaders/VisitSubmitLoader.java
Error:(9, 37) error: cannot find symbol class Visit_Table
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NullPointerException
Information:BUILD FAILED

**Comment by agrosner** [comment]
1. Update to 3.0.1 when you can.
2. This is likely due to incremental compilation or a compile issue with generated code.
3. Are you using KAPT?

**Comment by tuanchauict** [comment]
I get this bug with 3.0.1. I'm not using KAPT.

This is my gradle setup with DBFlow:

```apt "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
```

**Comment by pablopatarca** [comment]
Thanks for answering.
1. Ok.
2. I suspected about incremental compilation and tried adding the following lines:
**
dexOptions {
        incremental false
}
org.gradle.parallel=true**
but I had no success.
3. Nop, I'm using apt (https://bitbucket.org/hvisser/android-apt)
Note: I think that this is happening because glradle is running the clean task before some construct task or something like that.

**Comment by pablopatarca** [comment]
I fixed the issue.
It seems that after to update to 3.0.1 begin to manifest an error that could not see before.
Something like this..
> Error:*==========*
  No type converter for: com.xxx.xxx.data.models.Person -> person from class: com.xxx.xxx.data.models.User. Pleaseregister with a TypeConverter.
  *==========*

Previously, I had models with the next structure:

 `@Table(...)`
`public class ModelA extends BaseModel {`
`@Column`
` private ModelB;`
`}`

That is a wrong relationship definition. So I add, for example, **@ForeingKey** notation to **ModelB**, and that It's all. It's working.
Note: this runs..
- Using apt (https://bitbucket.org/hvisser/android-apt)
- Updating DBFlow version to 3.0.1

**Comment by agrosner** [comment]
yeah I fixed some bugs since beta2 and included some better error handling/messaging. You cannot define a `Model` for a `@Column` unless its a `@ForeignKey`.

**Comment by tuanchauict** [comment]
I figured out why my case happened. I used DBFlow along with new version of ButterKnife (8.0.1) that uses `apt` instead of reflection. Don't know why DBFlow and ButterKnife 8 cannot work together
