### ISSUE TITLE
Add onConflict() method to @PrimaryKey annotation

### ISSUE THREAD

**Issue by dleonett** [Raizlabs/DBFlow#842]
DBFlow Version: 3.0.1
Issue Kind (Bug, Question, Feature): Feature

Description:

DBFlow does not support adding ON CONFLICT clause to `@PrimaryKey` annotation. Trying to add `@Unique(onUniqueConflict = ConflictAction.REPLACE)` to our primary key column does not seem to work. For example:

```java
@Table(database = AppDatabase.class, name = "tbl_persona", allFields = true)
public class Persona extends BaseModel {

    @PrimaryKey
    @Unique(onUniqueConflict = ConflictAction.REPLACE)
    @Column(name = "id_persona")
    int idPersona;

    @NotNull
    String nombre;

    // ...
}
```

results in the following creation SQL query:

```sql
CREATE TABLE `tbl_persona`(`id_persona` INTEGER UNIQUE ON CONFLICT REPLACE,`nombre` TEXT NOT NULL, PRIMARY KEY(`id_persona`))
```

wich is not as expected.

According to [SQLite documentation](https://www.sqlite.org/syntax/column-constraint.html) and own testing, the correct creation SQL query for the ON CONFLICT clause in primary key should be like this:

```sql
CREATE TABLE `tbl_persona`(`id_persona` INTEGER PRIMARY KEY ON CONFLICT REPLACE,`nombre` TEXT NOT NULL)
```

or like this:

```sql
CREATE TABLE `tbl_persona`(`id_persona` INTEGER,`nombre` TEXT NOT NULL, PRIMARY KEY(`id_persona`) ON CONFLICT REPLACE)
```

Any suggestion is welcome :)

**Comment by agrosner** [comment]
@dleonett if you make your PK `@PrimaryKey(autoincrement = true)` that should fix your issue.

**Comment by agrosner** [comment]
Ignore my last comment after reading this a little more.

**Comment by dleonett** [comment]
@agrosner I made it work for me using `insertConflict = ConflictAction.REPLACE` in `@Table` annotation like this:

```java
@Table(database = AppDatabase.class, name = "tbl_persona", allFields = true, insertConflict = ConflictAction.REPLACE)
public class Persona extends BaseModel {

    @PrimaryKey
    @Column(name = "id_persona")
    int idPersona;

    @NotNull
    String nombre;

    // ...
}
```

**Comment by agrosner** [comment]
so this is technically fixed?

**Comment by agrosner** [comment]
anyways its in `develop` and works. you can add `@Table(primaryKeyConflict = {ConflictAction})` and it'll insert it into the table's creation statement.

**Comment by dleonett** [comment]
Thank you @agrosner!

**Comment by luorenyu** [comment]
@agrosner   I encounter the same issue.but I use the DBFlow version is 4.0.0-beta5.

**Comment by luorenyu** [comment]
@agrosner I encounter the same issue.but My DBFlow version is 4.0.0-beta5.
and I try to add this  annotation @Table(primaryKeyConflict = ConflictAction.REPLACE),but it doesn't work .but @dleonett 's solution did work!
