### ISSUE TITLE
Cascade Delete Notifications

### ISSUE THREAD

**Issue by georgbachmann** [Raizlabs/DBFlow#844]
DBFlow Version: 3.0.1
Issue Kind (Bug, Question, Feature): Bug/Feature
Description: 

I have a table A and table B with a 1:n relation between them
If i delete A, B should be cascade deleted. That works as expected.

B has some data that it refers to on my phone. So when B get's deleted, if should clean that up.

Is there any way to get notified about that cascaded delete of B? I was hoping for `FlowContentObserver` but it's only telling me about the deletion of A.

Cheers,
Georg

**Comment by agrosner** [comment]
Since its done at a SQLite level, no. You would have to use the `@OneToMany` annotation and do the associated deletion by overriding the `delete()` method in B. Look [here](https://github.com/Raizlabs/DBFlow/blob/master/usage2/Relationships.md#one-to-many)
