### ISSUE TITLE
Add a description for throwed error

### ISSUE THREAD

**Issue by PingForward** [Raizlabs/DBFlow#846]
DBFlow Version: 3.0.1
Feature

Description: 
Need an explanation(description) when exception thrown `android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)` it is thrown in many cases when there is non trivial relations between the models and stack trace not always help. Is it possible?

**Comment by agrosner** [comment]
This is passing through Android standard exceptions. Im not going to modify those as it would put a layer on top of standard error messages.
