### ISSUE TITLE
documentation 1.7

### ISSUE THREAD

**Issue by yassinejhon** [Raizlabs/DBFlow#847]
Hi,
i have a project that i worked on last  year with the version 1.7 , know i want to use some of the ready code in it , the problem is i cant find the old documentation for the version 1.7 ?

**Comment by agrosner** [comment]
It would require some time to track the specific commit. I would look back a year ago in commit history and look in usage docs. I can't remember, otherwise it might be gone since it might have been in the wiki' (no longer used)
