### ISSUE TITLE
Create a column with default current date time value

### ISSUE THREAD

**Issue by msoa** [Raizlabs/DBFlow#848]
DBFlow Version: 3
Issue Kind (Question):

In model how can create a column with default current date time value?
In this example i defined **create_date** as **Date**. It's true? How can implement Sqlite data types in model?
Like this:
```
@Column(defaultValue = "default CURRENT_DATE")
Date create_date
```

**Comment by agrosner** [comment]
yes 

You can try simply

```java
Date create_date = System.currentTimeMillis();
```

This should get executed at object creation time.

**Comment by agrosner** [comment]
There isnt support for columns as true date columns.
