### ISSUE TITLE
@Column "name" does not work properly with @ForeignKeyReference "foreignKeyColumnName"

### ISSUE THREAD

**Issue by Wafel** [Raizlabs/DBFlow#849]
DBFlow Version: 3.0.1
Issue Kind: Bug

Description: 
If you set column name different from field name and then you reference that column in @ForeignKeyReference( foreignKeyColumnName ) you cannot resolve corresponding model.
Values are properly stored in database, but cannot be fetched. 

---
```
@ModelContainer
@Table(name = PlayerEntity.NAME, database = SquashDatabase.class)
public class PlayerEntity extends BaseModel {

    public static final String NAME = "PLAYER";

    @Column(name = "ID")
    @PrimaryKey(autoincrement = true)
    Long id;
```
---
```
@ModelContainer
@Table(name = MatchEntity.NAME, database = SquashDatabase.class)
public class MatchEntity extends BaseModel {

    public static final String NAME = "MATCH";

    @Column(name = "ID")
    @PrimaryKey(autoincrement = true)
    Long id;

    @NotNull(onNullConflict = ConflictAction.ROLLBACK)
    @Column(name = "DATE")
    Date date;

    @NotNull(onNullConflict = ConflictAction.ROLLBACK)
    @ForeignKey(saveForeignKeyModel = false,
                onDelete = ForeignKeyAction.CASCADE,
                references = @ForeignKeyReference(columnName = "PLAYER_ONE_ID",
                                                  foreignKeyColumnName = "ID",
                                                  columnType = Long.class,
                                                  referencedFieldIsPackagePrivate = true))
    ForeignKeyContainer<PlayerEntity> playerOne;
```
---

In generated code in class PlayerEntity_Container there is reference to "id" instead of "ID"
```
@Override
public final ConditionGroup getPrimaryConditionClause(ModelContainer<PlayerEntity, ?> modelContainer) {
    ConditionGroup clause = ConditionGroup.clause();
    clause.and(PlayerEntity_Table.ID.eq(modelContainer.getLongValue("id")));return clause;
}
```
---
If you replace

`@Column(name = "ID")` with `@Column(name = "id")`
and
`foreignKeyColumnName = "ID"` with `foreignKeyColumnName = "id"`
then it works properly.

Code in attachments
[entities.zip](https://github.com/Raizlabs/DBFlow/files/296416/entities.zip)
[generated.zip](https://github.com/Raizlabs/DBFlow/files/296417/generated.zip)

**Comment by agrosner** [comment]
foreign key containers in 4.0.0-beta1 are gone, and replacement is `stubbedRelationship` on `ForeignKey` annotation. A new way for parsing JSON directly to DB will be concocted hopefully before 4.0.0 release. But it will look different than it is in pre-4.0.0
