### ISSUE TITLE
Add end() method with zero parameters to CASE expression

### ISSUE THREAD

**Issue by dleonett** [Raizlabs/DBFlow#852]
DBFlow Version: 3.0.1
Issue Kind: Feature 

Description: 

Currently there's a `end(String columnName)` method for the CASE expression that seems to work with SELECT clause. But when we try to use a CASE inside a COUNT function it does not work because this method appends the _columnName_ to the "END" word resulting in syntax error. 

Generated SQL query:

```sql
SELECT COUNT( CASE `id_persona` WHEN 1 THEN `id_persona` END `myColumnName`)
```

wich is wrong.

This is the actual code in Case.java

```java
if (columnName != null) {
    queryBuilder.append(" END " + columnName);
}
```

According to [SQLite documentation](https://www.sqlite.org/lang_expr.html#case) and own testing, the correct syntax for CASE expression in COUNT function is:

```sql
SELECT COUNT( CASE x WHEN w1 THEN r1 WHEN w2 THEN r2 ELSE r3 END ) AS alias

SELECT COUNT ( CASE WHEN x=w1 THEN r1 WHEN x=w2 THEN r2 ELSE r3 END ) AS alias
```

with no _identifier_ right after "END"

I think there should be an extra `end()` method with no paremeters that doesn't append the _columnName_ to the "END" word in CASE expression.

**Note**: In current version, one approach would be passing _NULL_ to the current `end(columnName)` method, but this does not even include the "END" word in the resulting query.

**Comment by agrosner** [comment]
great find. in `develop`

**Comment by dleonett** [comment]
Nice! @agrosner
