### ISSUE TITLE
How to use StringQuery?

### ISSUE THREAD

**Issue by dleonett** [Raizlabs/DBFlow#853]
DBFlow Version: 3.0.1
Issue Kind: Question

Description: 

Hi, is there any documentation of how to use StringQuery?

**Comment by agrosner** [comment]
No if you look at source, it only runs the string as a SQLite query..its a string query. Just requires you passing the table you wish to run the query on.

**Comment by tryadelion** [comment]
so, how does it work? magically? SQLite.select().magicalStringQueryCodeNotOnTheDocs("myQuery")..... ?

**Comment by jurmeneta** [comment]
It's much simpler if you look in the documentation.
`StringQuery<Model> query = new StringQuery(Model.class,"SELECT * FROM table");
        List<Model> myList = query.queryList();`

**Comment by AlyssonPHN** [comment]
did not find any documentation

**Comment by dleonett** [comment]
# Sync 

```
String rawQuery = "SELECT * FROM table WHERE blabla";
StringQuery<YourModel> stringQuery = new StringQuery<>(YourModel.class, rawQuery);
List<YourModel> models = stringQuery.queryList();
```

# Async

```
StringQuery<Aviso> stringQuery = new StringQuery<>(Aviso.class, rawQuery);
stringQuery
    .async()
    .queryListResultCallback(callback)
    .execute();
```

**Comment by AlyssonPHN** [comment]
@dleonett Thank's
