### ISSUE TITLE
[Bug] Sorting ModelView by priority after creating in database

### ISSUE THREAD

**Issue by tranngoclam** [Raizlabs/DBFlow#855]
DBFlow Version: 3.0.1
Issue Kind (Bug, Question, Feature): Bug

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

Hi, I'm using `priority` in @ModelView, but after creating multiple ModelViews in project with different priorities, they aren't sorted. Maybe before adding each ModelView to database, you forget sorting them.

Thanks.

**Comment by agrosner** [comment]
fixed in `develop`, as a temp hotfix, assign any non priority model views a priority >= 0. Its due to the `compareTo()` method not liking the default priority of `@ModelView` as -1
