### ISSUE TITLE
Sum of column and sum of column multiply by integer

### ISSUE THREAD

**Issue by mustansarsaeed** [Raizlabs/DBFlow#856]
Hi, 

I am trying to select data from table. I want to select sum of column and multiply that sum with integer with group by statement. I have tried to use the following approach, but its not working:

```
new Select(MyTable$Table.GROUP_COLUMN, 
  "SUM(upvote) as totalUpvote",
  "SUM(downVote) * 2 ", )
.from(MyTable.class).groupBy("groupColumn").orderBy("totalVote DESC").queryList()
```

> Issue is I am not allowed to use SUM statements.

Can anyone please let me know how to resolve this issue?

**Comment by agrosner** [comment]
Be helpful to state version. Also DBFlow has changed a lot, as it looks like youre using pre-3.0.0. Please do not report issues on old versions unless its still relevant in latest version :). If you use 3.0.0:
```
SQLite.select(MyTable_Table.group_column, 
  sum(upvote).as("totalUpvote"),
  sum(downVote).multipliedBy(2))
.from(MyTable.class).groupBy("groupColumn").orderBy(totalVote, false).queryList()
```

**Comment by amugox** [comment]
@agrosner I am using 3.0.1 but the sum seem not to work.

_SQLite.select(sum(SentReq_Table.amount)).from(SentReq.class).where(SentReq_Table.reqCode.eq(this.reqCode));_

What am i missing out?
