### ISSUE TITLE
save() operation is very slow

### ISSUE THREAD

**Issue by samoilovich** [Raizlabs/DBFlow#857]
DBFlow Version: 3.0.1, 2.2.1
Issue Kind (Bug, Question, Feature): Question

Hello, my name is Natali.
I have problem with save() operation in dbflow_version = "3.0.1"
Saving of 1000 records takes 30 seconds.
BUT
I check the same case on the dbflow_version = "2.2.1" and it takes only 1,5 second.

Can you point to my mistakes or may be can you explain why it happens?
I read DBFlow documentation and related topics and don't understand what I'm doing wrong.
Please, doesn't pay attention to missed foreign key. It a simple example for checking time of saving.

Thanks.

Description: 
//-------------------------------------------------------------------------
`public long saveInDb() {
        TestModel testModel = new TestModel();
        List<TestTextModel> testTextModels = new ArrayList<>();
        for (int i = 0; i < 1000; i++) {
            TestTextModel temp = new TestTextModel();
            temp.setText(String.valueOf(i));
            testTextModels.add(temp);
        }
        testModel.setStrings(testTextModels);

        long time2 = System.currentTimeMillis();
        testModel.save();
        long time = (System.currentTimeMillis() - time2);
        Log.i("time", "time " + time);

        return time;
    }`
//-------------------------------------------------------------------------
`public class TestModel extends BaseModel {

    @Column
    @PrimaryKey(autoincrement = true)
    private int id;

    List<TestTextModel> strings;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @OneToMany(methods = {OneToMany.Method.ALL}, variableName = "strings")
    public List<TestTextModel> getStrings() {
        return strings;
    }

    public void setStrings(List<TestTextModel> strings) {
        this.strings = strings;
    }
}`
//-------------------------------------------------------------------------
`public class TestTextModel extends BaseModel {

    @Column
    @PrimaryKey(autoincrement = true)
    private int id;

    @Column
    private String text;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }
}`

**Comment by agrosner** [comment]
Use `FastStoreModelTransaction`. Also you're not wrapping it in a DB transaction anyways, so obviously its going to be slower.
