### ISSUE TITLE
Keep old version tags

### ISSUE THREAD

**Issue by WarrenFaith** [Raizlabs/DBFlow#858]
Please recreate the tags to previously released versions. It is hard to understand possible issues when we can't look at the exact code that is used by our project.

Also the documentation (inside usage2 directory) is already updated to the latest version and therefore useless if you want to read about the usage of the specific version that we are using.

Thanks! :)

**Comment by agrosner** [comment]
```
Also the documentation (inside usage2 directory) is already updated to the latest version and therefore useless if you want to read about the usage of the specific version that we are using.
```
Its actually perfect if you just read it from the specific commit you want to get it from. In 3.0.0 it changed location, but the docs would be relevant to that version you were in. It would be helpful to state what version you're in (thats why i have an issue template with that specified.) Going forward all releases will have tags, but its not worth it to go back and do older versions.

**Comment by WarrenFaith** [comment]
If I could have pinpoint the commit I needed, I wouldn't have asked for a tag.
I was just asking for the tag for the latest released 2 major version.

As it might not be worth it for you, it is worth it for me. Now I have to clone it and search for it hoping that you mentioned the version number in the commit message.

"Would be relevant" is sadly not the same as "are relevant". I need documentation and code for the version I use, thats why I asked for the tag.

Anyway, glad to hear that ongoing version will have tags.
