### ISSUE TITLE
FlowManager.init(this) give compilation Error.

### ISSUE THREAD

**Issue by dineshprjpt** [Raizlabs/DBFlow#859]
DBFlow Version: 3.0.1

I have followed the ReadMe file and integrated this library in my project and I am stuck here.
FlowManager.init(this) gives compilation error like FlowManager cannot be applied to application object.

**Comment by trevjonez** [comment]
https://github.com/Raizlabs/DBFlow/blob/3.0.0-beta6/usage2/GettingStarted.md#initialize-flowmanager

**Comment by agrosner** [comment]
Did you read the README? (https://github.com/Raizlabs/DBFlow/blob/master/usage2/GettingStarted.md#initialize-flowmanager)
