### ISSUE TITLE
FlowContentObserver: no notification of content changes when using multiple processes

### ISSUE THREAD

**Issue by panzerfahrer** [Raizlabs/DBFlow#86]
I just updated from 1.2.0 to 1.5.2 and noticed that content change notification stopped beeing triggered. After quite some testing I might found the cause:

I'm using a SyncAdapter which runs in it's own process. Since the UI runs in another process, the `FlowContentObservers` fills its `mObserverList` in that process. In the SyncAdapter's process `mObserverList` is always empty, which results in no notifications.

**Comment by agrosner** [comment]
Could you send me a snippet of how you are using the ```FlowContentObserver``` ? I changed it so that once you register one, the changes will get triggered since doing this all the time created a significant performance hit for those not interested in the changes.

**Comment by panzerfahrer** [comment]
Well, actually I'm not doing anything fancy:

- using `new Select()` a query is prepared
- in an `AsyncTaskLoader` the query is executed, a `FlowContentObserver` is created and registered for content changes
- the database is manipulated from a `SyncAdapter`
- the `SyncAdapter` runs in a `Service` which lives in a separat process

**Comment by agrosner** [comment]
Interesting, so the ```SyncAdapter``` runs in separate process? you may need to create the ```FlowContentObserver``` in the same process then. Maybe what would help is some code examples if you can provide of how its being implemented.

**Comment by panzerfahrer** [comment]
Running a `SyncAdapter` in its own process is a pretty standard scenario, I'd say. See the [implementation guide](http://developer.android.com/training/sync-adapters/creating-sync-adapter.html#DeclareSyncAdapterManifest).

Creating the `FlowContentObserver`in the `SyncAdapter`'s process would help either, since the `FlowContentObserver` uses a static member field to decide if notifications are needed. Changes to this static member don't reflect across processes. So the observer in the main process would be independent of the one in the sync process.

Some code excerpts:
```
public class SyncAdapter extends AbstractThreadedSyncAdapter {

    @Override
    public void onPerformSync(Account account, Bundle extras, String authority, ContentProviderClient provider, SyncResult syncResult) {
      // download, process, do stuff...
      TransactionManager.getInstance().save(ProcessModelInfo.withModels(data));
   }
}

public class MyFragment extends Fragment {

    @Override
    public Loader<Cursor> onCreateLoader(int id, Bundle args) {
        ModelQueriable query = new Select().from(Data.class);
        return new FlowCursorLoader<Data>(getActivity(), query);
    }

    @Override
    public void onLoadFinished(Loader<Cursor> loader, Cursor data) {
        mAdapter.swapCursor(data);
    }

}
```

Does this make my case more clear?

**Comment by agrosner** [comment]
I can add a setter to _force_ notification of content changes. This may result in some performance degradation (by as much as 60% for large changes). I can see what can be optimized.
