### ISSUE TITLE
Database file from assets folder is not copied to mobile when installing App

### ISSUE THREAD

**Issue by juamocag** [Raizlabs/DBFlow#860]
DBFlow Version: 3.0.1, 3.0.0
Issue Kind (Bug, Feature):

Description: 
The project was using version 3.0.0-beta6, this version copies the database file from the assets folder to the mobile. However, we moved to version 3.0.1 and this new one doesn’t do that. We checked also version 3.0.0 and it neither did it.
Do you have any clue about how to get back this feature?
Thanks in advance.

**Comment by michaellct** [comment]
I also meet this question,please help me!

**Comment by juamocag** [comment]
We had to downgrade to 3.0.0-beta6.

**Comment by michaellct** [comment]
@juamocag  so disappointment,I had to downgrade to 3.0.0-beta6 too.

**Comment by carmas123** [comment]
I think you need to call `performRestoreFromBackup` to do that!

**Comment by agrosner** [comment]
In `DatabaseDefinition`:

```java
public synchronized OpenHelper getHelper() {
        if (openHelper == null) {
            DatabaseConfig config = FlowManager.getConfig().databaseConfigMap()
                .get(getAssociatedDatabaseClassFile());
            if (config == null || config.helperCreator() == null) {
                openHelper = new FlowSQLiteOpenHelper(this, helperListener);
            } else {
                openHelper = config.helperCreator().createHelper(this, helperListener);
            }
            openHelper.performRestoreFromBackup();
        }
        return openHelper;
    }
```

When you call `FlowManager.getDatabase(...).getWritableDatabase()` it will call the restore from backup method. If you need that earlier, then yes you should call `performRestoreFromBackup()` or `FlowConfig.Builder.openDatabasesOnInit()` when you initialize DBFlow.

**Comment by juamocag** [comment]
Sorry,
We have tried this in the class that extends Application:
`FlowManager.init(new FlowConfig.Builder(this).openDatabasesOnInit(true).build());`
But it does not copy the database to the mobile.
We have also add this line after init:
`FlowManager.getDatabase(AppDatabase.class).getHelper().performRestoreFromBackup();`
But it does not work.
We have checked the current doc available, however, we were not able to find a solution.
I have checked the version of `DatabaseHelperDelegate` for 3.0.0-beta6, and I have found that the constructor made a call to `movePrepackagedDB`. In version 3.0.1 it is called from `performRestoreFromBackup`, but at this point the `dbPath.exists()` on `movePrepackagedDB `returns true.

**Comment by jonathangerbaud** [comment]
Hello,

I can't make it work either. The database is not copied and is empty after the first launch.

Do you have a code snippet that we could use to make this restore from backup feature work ? (I've use the same code as juamocag without success).

Thank you !
