### ISSUE TITLE
Migrating to DBFlow from existing Content Provider.

### ISSUE THREAD

**Issue by supareek** [Raizlabs/DBFlow#863]
DBFlow Version:
Issue Kind (Bug, Question, Feature):
Feature

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
I have an existing application which uses the Content provider storage model. I went through your library, used it in few of my other projects and it looks much simpler.  Is there any way I can migrate from from my existing legacy COntent provider to this ORM model without troubling my users? Any help will be appreciated. 

Thank you.

**Comment by agrosner** [comment]
Not sure what specifically you're asking here. I would read up on the (https://github.com/Raizlabs/DBFlow/blob/master/usage2/ContentProviderGeneration.md) to see if it fits your needs.
