### ISSUE TITLE
How can I execute SaveQueue

### ISSUE THREAD

**Issue by purebaba** [Raizlabs/DBFlow#865]
DBFlow Version:3.0.0-beta6
Issue Kind:Question

I use this:
FlowManager.getDatabase(CDBimDatabase.class).getTransactionManager().getSaveQueue().addAll(stageModels);
                FlowManager.getDatabase(CDBimDatabase.class).getTransactionManager().getSaveQueue().run();
but it cannot run
any problems ?

**Comment by trevjonez** [comment]
https://github.com/Raizlabs/DBFlow/blob/master/dbflow/src/main/java/com/raizlabs/android/dbflow/runtime/DBBatchSaveQueue.java#L143

`FlowManager.getDatabase(CDBimDatabase.class).getTransactionManager().getSaveQueue().purgeQueue();`

**Comment by purebaba** [comment]
i used this, but it make following method very very slow
public static SupervisionTaskModel getTaskById(String taskId) {
        return new Select().from(SupervisionTaskModel.class).where(SupervisionTaskModel_Table.id.eq(taskId)).querySingle();
    }
@trevjonez

**Comment by purebaba** [comment]
and while I only user BaseModel.save(); it works well

**Comment by trevjonez** [comment]
How do you mean slow? Are you still on 3.0.0-beta6? If so there was a bug which rendered the save queue non functioning. https://github.com/Raizlabs/DBFlow/issues/830

You should update to the latest release and try again.

**Comment by purebaba** [comment]
now i update to 3.0.1;
I used like this:
//it used in loops
public static InspectionTaskModel fromData(InspectionTask task){
  //this line execute very slowly about 0.5 seconds,and I think it  should not be slow like this.
  InspectionTaskModel inspectionTaskModel = getTaskById(task.getId());
  //some update
   FlowManager.getDatabase(CDBimDatabase.class).getTransactionManager().getSaveQueue().add(inspectionTaskModel);
}


public static InspectionTaskModel getTaskById(String id) {
        return new Select().from(InspectionTaskModel.class).where(InspectionTaskModel_Table.id.eq(id)).querySingle();
 }

**Comment by purebaba** [comment]
@trevjonez

**Comment by purebaba** [comment]
new problem #874
