### ISSUE TITLE
App Freezing on FastStoreModelTransaction

### ISSUE THREAD

**Issue by natangr** [Raizlabs/DBFlow#866]
DBFlow Version: 3.0.1
Issue Kind (Bug, Question, Feature): Critical Bug

Description: 
When I attempt a FastStoreModelTransaction my app freezes and pops a dialog asking if I want to close it. I'm using sqlcipher to encrypt my database according to the documentation.
Maybe I'm doing something wrong, here's my code:

    final FastStoreModelTransaction<MyModelClass> fastStoreModelTransaction = FastStoreModelTransaction
            .insertBuilder(FlowManager.getModelAdapter(MyModelClass.class))
            .addAll(myModelList)
            .build();

    DatabaseDefinition database = FlowManager.getDatabase(MyEncryptedDatabase.class);
    Transaction transaction = database.beginTransactionAsync(fastStoreModelTransaction).build();
    transaction.execute();

I apologize for not being able to provide more data about it.

**Comment by agrosner** [comment]
Are you performing any kind of retrieval or saves simultaneously on a different thread or main thread?

**Comment by natangr** [comment]
I'm performing saves for other tables on other threads. None of them is on the main thread.

**Comment by agrosner** [comment]
Different threads is most likely the issue. Best bet is to throw all of the saves into `async()` operations so that they all run on the same `TransactionManager` to sure they do not lock up other threads.

**Comment by xudjx** [comment]
I think we can use lock to avoid table save conflicts in multithreading environments.

**Comment by mseroczynski** [comment]
@agrosner Are you planning to implement any multithread transaction strategy? My app uses only async().save() and async transactions and i constantly get deadlocks.

**Comment by agrosner** [comment]
No, Database writes can only happen synchronously, such that it blocks reading from the database when writing in a transaction. The best thing to do is to put all operations into the transaction queue for the database and await the results. Im going to lock this issue as its outdated, and please file a new issue with version, what kind of calls you are making, and I can try to help @mseroczynski !
