### ISSUE TITLE
How can i use dbflow from sql?

### ISSUE THREAD

**Issue by Swordce** [Raizlabs/DBFlow#871]
SELECT * FROM Attendee WHERE eventId = ? AND payStatus = ? AND (attendeeMap like '%%%@%%' OR pinyinName like '%%%@%%' OR weixinId like '%%%@%%' OR barcode like '%%%@%%' OR ref_code like '%%%@%%' OR orderId like '%%%@%%' OR emailAddr like '%%%@%%' OR name like '%%%@%%' OR otherMessage like '%%%@%%') limit %i OFFSET %i"

Thank You!

**Comment by agrosner** [comment]
please read up on the usage docs. (https://github.com/Raizlabs/DBFlow/blob/master/usage2/SQLiteWrapperLanguage.md)
