### ISSUE TITLE
check if migration is necessary before migration of dbflow starts

### ISSUE THREAD

**Issue by TheWhiteLlama** [Raizlabs/DBFlow#872]
DBFlow Version:
Question

Description: 
Hi there! Is it currently possible to check if a migration of the database is required before the automatic migration of the dbflow database is triggered?

As posted in my last question I am trying to inform the user for bigger migrations with a screen, but I'm not finding any methods for checking if a migration is needed.

Is the only solution the SQLite classes from android?

Thanks!

**Comment by agrosner** [comment]
Thats not really how database migrations work in SQLite. You use them to update your schema with additional fields, or renaming tables. Most other modifications are custom migrations not immediately supported by SQLite. They aren't really meant for users but backend.
