### ISSUE TITLE
GsonConverter

### ISSUE THREAD

**Issue by sergbek** [Raizlabs/DBFlow#873]
**DBFlow Version: dbflow_version = "3.0.1"
Issue Kind (Bug, Question, Feature): Feature**

**Description:** 

Hi, I have a suggestion.
Often it is necessary to create for objects converters. So in this converter we need to serialize / deserialize the object using gson. It would be nice if you add an annotation , on the similarity , @GsonConverter that will generate classes
![image](https://cloud.githubusercontent.com/assets/13929986/16257088/e4d67244-385e-11e6-80c3-36434f8599b9.png)

Thanks!

**Comment by agrosner** [comment]
Not sure what you're asking, we support `@TypeConverter` if thats what you're asking. (https://github.com/Raizlabs/DBFlow/blob/master/usage2/TypeConverters.md)

**Comment by agrosner** [comment]
You are asking for DBFlow to provide an annotation to generate GSON converters? not supported.

**Comment by bryant1410** [comment]
In order to support this, I think DBFlow needs to support abstract and generic type converters. If this is the case, it'd be something like:

```java
public abstract class GsonConverter<T> extends TypeConverter<String, T> {
    private Gson gson = Gson();

    @Override
    public String getDBValue(T model) {
        return gson.toJson(model, getModelClass());
    }

    @Override
    public T getModelValue(String data) {
        return gson.fromJson(data, getModelClass());
    }

    public abstract Class<T> getModelClass();
}
```

**Comment by ubaierbhat** [comment]
@bryant1410 .. it will be nice to have this feature.

**Comment by agrosner** [comment]
You can create subclass for generic type converter and then associate it with the field you like. FWIW if you are serializing / deserializing json in this way, then a relational DB is not what you want. Also, in 4.1.0 DBFlow will support `@ColumnMap` objects, which allow you to flatten hierarchy into a single table just like Room does.

**Comment by ubaierbhat** [comment]
```@ColumnMap``` should like a good idea :) ,.. Creating a extra table for every small nested object is a bit painful specially as we have to add primary keys which are only for database and don't exists in the remote models. I haven't tried ```@Embedded``` in room yet. It will be interesting to how it deals with more complex nested objects.
