### ISSUE TITLE
Does Foreignkey lower the database performance？

### ISSUE THREAD

**Issue by purebaba** [Raizlabs/DBFlow#874]
DBFlow Version:3.0.1
Issue Kind (Bug, Question, Feature):Question
Description: 
I instert 1000 records
 use SaveQueue
without Foreignkey about 4s
has Foreignkey about 10s
is it Normal？

**Comment by trevjonez** [comment]
It is likely that it is trying to validate the foreign key constraint as it inserts them. In which case this seems plausible. If it has to do 1 or more read for every write it could slow down quite a bit.

**Comment by agrosner** [comment]
potentially. ensure your `@ForeignKey` reference has `saveForeignKeyModel = false`.
