### ISSUE TITLE
Updating a specified row in DBFLow

### ISSUE THREAD

**Issue by stntmaniiac** [Raizlabs/DBFlow#875]
DBFlow Version: dbflow_version = "3.0.1"
Issue Kind (Bug, Question, Feature):cannot update database using DBFlow

Description: 
I am trying to update one of my row in the database using DBFlow update.

![image](https://cloud.githubusercontent.com/assets/20105003/16294828/c6f0bb74-3942-11e6-8931-a7ed8134cade.png)

Whats wrong here??

**Comment by agrosner** [comment]
please read the wrapper docs (https://github.com/Raizlabs/DBFlow/blob/master/usage2/SQLiteWrapperLanguage.md)

**Comment by abiemann** [comment]
https://github.com/agrosner/DBFlowDocs/blob/master/SQLiteWrapperLanguage.md
