### ISSUE TITLE
Async Transactions

### ISSUE THREAD

**Issue by comann** [Raizlabs/DBFlow#878]
DBFlow Version:
Issue Kind (Question, Feature):

Is there a way to make async transactions. For example if I have two models A and B, where A is related to B. Therefore, when creating an entity from B, an async transaction would look like 

Start Async
Create A 
Create B with attaching the new created A's id.
End Async

Keep up the good work. Love the lib.

**Comment by agrosner** [comment]
please read the usage docs (https://github.com/Raizlabs/DBFlow/blob/master/usage2/StoringData.md#async-transactions)
