### ISSUE TITLE
Combining AND & OR operations in parentheses 

### ISSUE THREAD

**Issue by faifai21** [Raizlabs/DBFlow#88]
I've been trying to execute the following query: SELECT * FROM Table WHERE loc_id = "21" AND (first_name LIKE '%adam%' OR last_name LIKE '%adam%').

I can't seem to find any straight forward way to start a group in the Where class. Since the and() functions take either a Condition or build one from their parameters, I attempted passing in the clause within the parentheses to Condition.column() and setting the operator and value to an empty String, but that just resulted in DBFlow building the clause as an actual condition (by surrounding it in back ticks).

**Comment by faifai21** [comment]
I've worked around this temporarily by having two ConditionQueryBuilder's: one for the clause in parentheses (via a call to ConditionQueryBuilder.appendParenthesisEnclosed()), and another for the rest of the conditions. Then I join the two queries in a String with an AND in between, and pass that String to where.whereClause(). Not exactly the prettiest thing, but it works.

It would be great if Where had support for starting and closing groups, e.g. `where.and(Condition.column("id").is(20)).beginGroupAnd().putCondition(condition1).or(condition2).endGroup()`
which would result in the SQL Statement of "... WHERE id = '20' AND ( condition1 OR condition2)"

**Comment by agrosner** [comment]
yeah this is sort of an enhancement I was going to do at some point. Not a bad idea. Also possibly add sub-queries too as a feature. Sort of related (http://www.tutorialspoint.com/sqlite/sqlite_sub_queries.htm)

**Comment by tsuharesu** [comment]
The where clause that accepts string should be better detailed on the Usage docs, or at least cited :)

If you need help with documentation, I can help. I love doing docs hehe

**Comment by rjam** [comment]
:+1: for the sub-queries support
