### ISSUE TITLE
OneToMany when many is a list of One .. or something like that.

### ISSUE THREAD

**Issue by darktanker89** [Raizlabs/DBFlow#882]
Hi, how can I save and retrieve a cascade model with DBFlow?
Here is a simple example :

```Java
public class Dog {
      @PrimaryKey(autoincrement = true) int id;
      @Column String name;
      List<Dog> dog_kiddos;
}
```
Is such thing possible?

**Comment by agrosner** [comment]
Take a look at (https://github.com/Raizlabs/DBFlow/blob/master/usage2/Relationships.md#one-to-many)
