### ISSUE TITLE
@OneToMany not saving foreign key column in child table

### ISSUE THREAD

**Issue by austynmahoney** [Raizlabs/DBFlow#885]
DBFlow Version: 3.0.1
Issue Kind (Bug, Question, Feature): Question/Bug?

Description: 
I have two models: `Country` and `Subdivision`. Country is composed of a list of Subdivisions.
## Models

 **Country**

```
@Table(database = AppDatabase.class)
@ModelContainer
public class Country extends BaseModel {

    @PrimaryKey(autoincrement = true)
    @NotNull
    long id;

    @Column
    String name;

    private List<Subdivision> subdivisions;

    @OneToMany(
            methods = {OneToMany.Method.ALL},
            variableName = "subdivisions",
            isVariablePrivate = true
    )
    public List<Subdivision> getSubdivisions() {
        if (subdivisions == null || subdivisions.isEmpty()) {
            subdivisions = new Select()
                    .from(Subdivision.class)
                    .where(Subdivision_Table.country_id.eq(id))
                    .queryList();
        }
        return subdivisions;
    }

    public void setSubdivisions(List<Subdivision> subdivisions) {
        this.subdivisions = subdivisions;
    }
}
```

**Subdivision**

```
@Table(database = AppDatabase.class)
public class Subdivision extends BaseModel {

    @PrimaryKey(autoincrement = true)
    @NotNull
    long id;

    @Column
    String name;

    @ForeignKey(tableClass = Country.class,
            onDelete = ForeignKeyAction.CASCADE,
            onUpdate = ForeignKeyAction.CASCADE,
            saveForeignKeyModel = false)
    public ForeignKeyContainer<Country> country;
}
```
## Test Code

When I call `.save()` on a `Country` that has Subdivisions, the `Subdivision` rows are created but the foreign key column (`country_id`) is not set. Is this a bug or am I doing something wrong?

**MainActivity**

```
    Country country = new Country();
    country.setId(1);
    country.setName("United States");

    Subdivision subdivision = new Subdivision();
    subdivision.id = 1;
    subdivision.name = "California";

    ArrayList<Subdivision> subdivisionList = new ArrayList<>();
    subdivisionList.add(subdivision);

    country.setSubdivisions(subdivisionList);

    country.save(); // Saves 1 row in Country and 3 in Subdivision. Subdivision.country_id is null on each row
```

Also, should the following statement return a `Country` with the `subdivision` List set, or do I have to call the `getSubdivisions()` method every time? I'm confused about the functionality of `OneToMany.Method.ALL` here.

```
List<Country> countries = new Select().from(Country.class).queryList();
```

**Comment by agrosner** [comment]
you need to associate the `Country` in each subdivison:

```java
 Subdivision subdivision = new Subdivision();
    subdivision.id = 1;
    subdivision.name = "California";
```
you're not setting the `Country` object here..ForeignKeyContainers are no longer used in 4.0.0-beta1 +, rather we use `stubbedRelationship`. So much easier to work with.

**Comment by ubaierbhat** [comment]
Does this mean that if we get an object of ```Country``` from backend we have to iterate over its list of ```Subdivision```, add the refrence of parent country to each and then save to db? Is there a better way to do this. For me it becomes more complicated as I receive a list of parent objects, lets say countries in this example, then i have to iterate over each parent object first...
