### ISSUE TITLE
Converting foreign key container to model with enums gives NPE

### ISSUE THREAD

**Issue by nsatvik** [Raizlabs/DBFlow#886]
DBFlow Version: 3.0.1
Issue Kind (Bug, Question, Feature): Bug
Description: 
Foreign key container has data map of only the ids. But when creating the model it tries to populate all the fields and in case of enums it calls valueOf on null and fails with a NPE. 
Code snippet in generated Container class.
`model.setId(modelContainer.getStringValue("id"));
  model.setType(com.example.Type.valueOf(modelContainer.getStringValue("type")));
`

**Comment by agrosner** [comment]
`ModelContainer` support removed in 4.0.0+ now use `stubbedRelationship`, it might fix your issue here.
