### ISSUE TITLE
Managing Custom Transactions?

### ISSUE THREAD

**Issue by spierce7** [Raizlabs/DBFlow#89]
I'm using a custom background threading framework. It has a hook (ActionRunner) that allows us to run all the database actions in a transaction, and I've made a habit of doing this in the past. 

For instance, with GreenDao I would just do the following:
``` Java
.actionRunner(new ActionRunner() {
          @Override
          public void execute(final ActionRunnable actionRunnable, Action[] actions) {
            daoSession.runInTx(new Runnable() {
              @Override public void run() {
                actionRunnable.execute();  // All database interactions are run inside of #execute(), and are all single threaded.
              }
            });
          }
        })
```

DBFlow has a very sophisticated transactions system with the TransactionManager, but I'm not looking for any thread management or queue as that's already handled with the framework I'm using. I've dived into DBFlow code, but can't actually find where the transactions are started/ended at the DB level to try and replicate in the ActionRunner (shown above).

<b>What would be the best way to continue using transactions as we've been using them (Everything is run in a transaction by default) as we migrate to DBFlow?</b>

**Comment by agrosner** [comment]
```ProcessModelHelper.process()``` or ```TransactionManager.transact()```

**Comment by agrosner** [comment]
recommend the second one for this instance, you just need to supply the database name or actual ```SQLiteDatabase``` object.

**Comment by agrosner** [comment]
if this doesn't help, please reopen.
