### ISSUE TITLE
Bug in get count()

### ISSUE THREAD

**Issue by z-zghiba** [Raizlabs/DBFlow#890]
DBFlow Version:3.0.1
Issue Kind :bug

Description: 

When i try to get count() with 

    SQLite.select().from(Users.class).where(Users_Table.organizationId.eq(organization.getId())).count()

OR

    new Select().from(Users.class).where(Users_Table.organizationId.eq(organization.getId())).count()

it returns me only the first value (0) that is goood, for the others it's stil fixed to the value 1

**Comment by agrosner** [comment]
you have to use `SQLite.selectCountOf()` Its not a bug, rather if you want to get a count of rows such as `COUNT(*)` thats the method. Its a little misleading.

**Comment by imosmanyilmaz** [comment]
@agrosner you should note that  wiki document. SQLite.selectCountOf() is a good method
