### ISSUE TITLE
Support different database extension?

### ISSUE THREAD

**Issue by mehere** [Raizlabs/DBFlow#891]
DBFlow Version: 3.0.1
Issue Kind (Bug, Question, Feature): Feature

Description: 
I see the database extension '.db' is hard-coded in "DatabaseDefinition". Actually we can have a field in "Database" annotation to allow user to specify extension. (We can have a default value ".db" for backward compatibility)

if there is no concern, I will open a pull request :)

**Comment by agrosner** [comment]
Sure that is fine :) issue a PR against `develop` please.

**Comment by agrosner** [comment]
in `develop`
