### ISSUE TITLE
Error when appending to empty Method()

### ISSUE THREAD

**Issue by syvlabs** [Raizlabs/DBFlow#895]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Bug

Description:
The bug is inside the `Method` class. 
`new Method().append(...)` gives an error when on `.execute`, due to different array lengths on `operationsList` and `propertyList`. The error happens exactly on `operationsList.get(i)` inside `getNameAlias()`. It happens because `propertyList` is one element longer than `operationsList` due to `propertyList.add(Property.ALL_PROPERTY);` on the default `Method` constructor.

**Comment by agrosner** [comment]
fixed in `develop` for 4.0.0-beta4
