### ISSUE TITLE
DBFlow 3.1.1 version issue

### ISSUE THREAD

**Issue by billywen88** [Raizlabs/DBFlow#896]
DBFlow Version:
Issue Kind (Bug, Question, Feature):

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
when I upgrade the version to 3.1.1, I can't build the project when I add the compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:${dbflow_version}" into gradle file.

the error is as follows.

Error:Module 'com.github.Raizlabs.DBFlow:dbflow-sqlcipher:3.1.1' depends on one or more Android Libraries but is a jar

**Comment by hannesa2** [comment]
I run in the same issue. What's the solution ?

**Comment by hannesa2** [comment]
sorry, I see it's a duplicate of  #897

**Comment by CapnSpellcheck** [comment]
Guys any tips if I get this issue adding 4.0.0-beta4 to new project, never used DBFlow before? :(

**Comment by gdogaru** [comment]
I get the same error using 4.0.0-beta4, worked fine with 3.1.1

**Comment by CapnSpellcheck** [comment]
Agreed. I hope there aren't any major fixes in beta4, I'm stuck with 3 :(
