### ISSUE TITLE
DBFlow 3.1.1 version issue

### ISSUE THREAD

**Issue by billywen88** [Raizlabs/DBFlow#897]
DBFlow Version:
Issue Kind (Bug, Question, Feature):

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

I upgrade the DBFlow version to 3.1.1
then it raised gradle error.

Error:Module 'com.github.Raizlabs.DBFlow:dbflow-sqlcipher:3.1.1' depends on one or more Android Libraries but is a jar

the Android appcompat library version is 23.4.0.

Regards.
Billy

**Comment by MarcusBrooks** [comment]
Using 'com.github.Raizlabs.DBFlow:dbflow-sqlcipher:3.1.1@aar' will fix this issue temporarily

**Comment by WesleyDonk** [comment]
If I use 'com.github.Raizlabs.DBFlow:dbflow-sqlcipher:3.1.1@aar' to fix the 3.1.1 dependency, the inner dependency 'net.zetetic:android-database-sqlcipher:3.5.1' is not loaded. Due to that the app cannot even compile and throws the error: 

Error:(7, 8) error: cannot access SQLiteOpenHelper
class file for net.sqlcipher.database.SQLiteOpenHelper not found

Is there a different way to use the 3.1.1 version?

Regards,

Wesley

**Comment by agrosner** [comment]
try adding the `'net.zetetic:android-database-sqlcipher:3.5.1' line dependency and see if that fixes it.

**Comment by jdrider** [comment]
I have the following in the build.gradle and am seeing a similar error when building.

 `apt "com.github.Raizlabs.DBFlow:dbflow-processor:3.1.1"`
`compile "com.github.Raizlabs.DBFlow:dbflow-core:3.1.1"`
`compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:3.1.1@aar"`

`compile 'net.zetetic:android-database-sqlcipher:3.5.1' `

The first error is `Error:(8, 8) error: cannot access OpenHelper
class file for com.raizlabs.android.dbflow.structure.database.OpenHelper not found`

There are other errors after that one which are probably side effects of the first one.

`Error:Type Element was null for: com.raizlabs.android.dbflow.structure.listener.LoadFromCursorListenerensure that the visibility of the class is not private.
Error:Type Element was null for: com.raizlabs.android.dbflow.structure.listener.ContentValuesListenerensure that the visibility of the class is not private.`

**Comment by taosimple** [comment]
I have the same problem , and  adding the `'net.zetetic:android-database-sqlcipher:3.5.1' the probloem resolved.

**Comment by AAverin** [comment]
Additinally to all that, having Kotlin + Kapt, upgrading dbflow to 3.1.1 results in many compilation issues - seems like main dbflow module isn't compiled somehow.
Adding @aar for the sqlCypher doesn't fix the issue

**Comment by therajanmaurya** [comment]
Why we need to add ```compile 'net.zetetic:android-database-sqlcipher:3.5.1'``` because this library already exists in Sqlchiper DbFlow Library Gradle.

**Comment by therajanmaurya** [comment]
Here is my gradle : 
```
//DBFlow dependencies
apt "com.github.Raizlabs.DBFlow:dbflow-processor:3.1.1"
compile "com.github.Raizlabs.DBFlow:dbflow-core:3.1.1"
compile "com.github.Raizlabs.DBFlow:dbflow:3.1.1"
compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:3.1.1@aar"
compile "net.zetetic:android-database-sqlcipher:3.5.1"
```
My project building successfully.

But I am confused, Why we are adding 
```
compile "net.zetetic:android-database-sqlcipher:3.5.1"
```
It Already exists in Sqlcipher Gradle.

and DBFlow README says DBFlow Sqlcipher is the stable at version 3.1.1.
then why I need to add  
```
compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:3.1.1@aar"
```
instead of 
```
compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:3.1.1"
```
@agrosner Please help.

**Comment by agrosner** [comment]
was importing wrong artifact. fixed in `develop`.

**Comment by DavidMont** [comment]
Its not working for me... Please reopen this 

    ```gradle
apt "com.github.Raizlabs.DBFlow:dbflow-processor:3.1.1"
    compile "com.github.Raizlabs.DBFlow:dbflow-core:3.1.1"
    compile "com.github.Raizlabs.DBFlow:dbflow:3.1.1"
    compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:3.1.1@aar"
    compile "net.zetetic:android-database-sqlcipher:3.5.1"
```

**Comment by ramib85** [comment]
I have the same error when using 4.0.0-beta4 .

**Comment by MahdiPishguy** [comment]
I have the same error when using 4.0.0-beta7 .

**Comment by akkuprin** [comment]
I have the same error for version 4.1.1 when create jar library for using in other project.
That works ok, if I define db-classes in android app that works ok, but I want having library.
