### ISSUE TITLE
Migrate from 2.1.1 to 3.1.1

### ISSUE THREAD

**Issue by Informaticore** [Raizlabs/DBFlow#899]
I read the migration3guide but I am not 100% sure.
I want to migrate from 2.1.1 to 3.1.1 with already released Apps in the Play Store. 
If I change everything like in the guide, there will be no problems after an update?

I am just wondering because it will generate new classes and f.e. boolean values are now different.
Also the generated classes are different. 
I just want to check that maybe someone already has done it before I start it. It is a Big project (the database part isn't that big) with many users who will be effected. Of course I will test everything, I just want to be sure.

**Comment by agrosner** [comment]
No problems for sure. The lib only gets better and better. Just ensure you cover your cases when upgrading as the syntax and classes have nearly completely changed since then, for the better :)
