### ISSUE TITLE
Consider Replacing '$' usage with '_' for Kotlin Users

### ISSUE THREAD

**Issue by spierce7** [Raizlabs/DBFlow#90]
Kotlin is going to start becoming more popular as a language for Android. Jake Wharton recently [suggested the switch from Java to Kotlin](https://plus.google.com/+JakeWharton/posts/WSCoqkJ5MBj) for Android developers. Kotlin has also been [known not to play very nice with $ characters in class names](https://github.com/google/dagger/issues/58).

Please consider swapping out the generated table classes with '$' in the class name for another character, such as '_' in future versions, or at least allowing the option of using a different character.

**Comment by agrosner** [comment]
Interesting take on the library. Something like this would need to go in a 2.0 release or further. If I get enough support from the Kotlin community that wishes to do this, I will consider it. Its just a major change and those who have been using the library, it will pretty much break code especially if they use the ```$Table``` classes.

**Comment by Fi5t** [comment]
@agrosner What support do you need from community?

**Comment by agrosner** [comment]
ok so I added ```generatedClassSeparator()``` to the ```@Database``` in develop and it will make it in for 1.7.0! So Kotlin will be supported given you define the separator something other than "$"

**Comment by agrosner** [comment]
now on master 1.7.0
