### ISSUE TITLE
How to set NULL to primitive type model properties?

### ISSUE THREAD

**Issue by dleonett** [Raizlabs/DBFlow#901]
DBFlow Version: 3.0.1
Issue Kind: Question

Description:

Hi! How can I set NULL to an integer property using SQLite language wrapper?

**Comment by agrosner** [comment]
use the boxed class `Integer` instead. You also must cast it to `Integer` or this:
```
.where(column.is((Integer) null))

// or
Integer value = null; // come from somewhere else maybe?
.where(column.is(value))

```
The compiler does not know what method you meant to call if you use a Null since we require strict type safety.
