### ISSUE TITLE
How to get access to SQLiteDatabase

### ISSUE THREAD

**Issue by Pedramrn** [Raizlabs/DBFlow#902]
DBFlow Version: 3.1.1
Issue Kind (Question):

Description: I need to access to `SQLiteDatabase ` in order to performing a `beginTransactionWithListenerNonExclusive` on it, in olders version I could access it with `FlowManager.getDatabase(DatabasePush.NAME).getWritableDatabase()`
However it returns `DataBaseWrapper` in this version!!

**Comment by agrosner** [comment]
`AndroidDatabase.getDatabase()`. i'd suggest you look at the class for more information.

**Comment by dreamcatcha** [comment]
This new way cannot be accessed within a static context
