### ISSUE TITLE
How to async Select Count?

### ISSUE THREAD

**Issue by ursusursus** [Raizlabs/DBFlow#906]
DBFlow Version:
Issue Kind - Question

Description: 
Im trying to async this sync call that returns count

SQLite.selectCountOf()
	.from(Article.class)
	.where(Article_Table.mSeen.eq(false))
	.and(Article_Table.mTrashed.eq(false))
	.count();

I tried using async transaction but couldnt figure out how to pass a the result to the UI via the success callback..

Thanks

**Comment by z-zghiba** [comment]
see this : https://github.com/Raizlabs/DBFlow/blob/master/usage2/StoringData.md#transactions

**Comment by agrosner** [comment]
@ursusursus there is no current way to call `count()` asychronously with an `AsyncQuery`. Best bet is to wrap it in a  custom `ITransaction` you create and do on the `TransactionQueue`.
