### ISSUE TITLE
This library support JDBC?

### ISSUE THREAD

**Issue by y2k** [Raizlabs/DBFlow#907]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Question

Description: 
Some questions:
1. This library support JDBC (can i use it for Java SE/Libgdx/RoboVM/Intel MOE)?
2. This library support build via Ant / Maven?
3. Can i use this library without plugin for "Annotation Processing" (only jar)?

**Comment by agrosner** [comment]
1. no
2. Maven yes 
3. No
