### ISSUE TITLE
First launch of application

### ISSUE THREAD

**Issue by alexbeville** [Raizlabs/DBFlow#908]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Question / Bug (?)

Description: 
Before all, thank you for this amazing ORM. I'm currently facing an issue that I can't understand. After some Google search, it seems that I'm the only one. So I guess, it's an implementation problem (or a PEBKAC).

The first time the application is launched, I have a white screen (so my setContentView isn't called) but I can see this in my logcat (see the 9 seconds between logs) :

`07-12 14:28:06.189 19540-19540/my.package.debug W/System: ClassLoader referenced unknown path: /data/app/my.package.debug-1/lib/arm64`
`07-12 14:28:15.708 19540-19540/my.package.debug W/System: ClassLoader referenced unknown path: /data/app/com.mana.igloo.debug-1/lib/arm64`

Here is my initiatlisation : 

Android Manifest : 
```xml
<application
        android:name=".MyApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity
            android:screenOrientation="portrait"
            android:name=".activities.SplashcreenActivity"
            android:theme="@style/AppTheme.NoActionBar" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
...
</application>
````

SplashcreenActivity
```Java
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splashscreen);
        progressBar = findViewById(R.id.progressBar);
        progressBar.setVisibility(View.VISIBLE);
        new AsyncTask<Void, Void, Void>() {
            @Override
            protected Void doInBackground(Void... params) {
                MyApplication.getInstance().initApplication();
                return null;
            }

            @Override
            protected void onPostExecute(Void aVoid) {
                goToNextScreen();
                super.onPostExecute(aVoid);
            }
        }.execute();
    }
```

MyApplication 
```Java
@Override
    public void onCreate() {
        super.onCreate();
        instance = this ;
    }

    public void initApplication(){
        FlowManager.init(new FlowConfig.Builder(this).build());
        if(BuildConfig.DEBUG)
            FlowLog.setMinimumLoggingLevel(FlowLog.Level.V);
    }

    public static MyApplication getInstance(){
        return instance ;
    }
```

What am I doing wrong ?

**Comment by agrosner** [comment]
First of all I would def not creating a new `AsyncTask` inside an `Activity`, but thats for another time. I def also would not initialize dbflow asynchronously. It happens almost instantly and should not block UI at all. I strongly prefer to initialize it directly in the `Application.onCreate()` method.

**Comment by alexbeville** [comment]
I'm sorry, you close it too quickly.

Originally, I was doing it in MyApplication.OnCreate but it was the same result. As I must do some synchronize tasks with server, I have to create a SplashScreen that is juste a view with my logo app and a loader. 

My SplashscreenActivity isn't showed, so the setContentView isn't called until 9 seconds.

**Comment by alexbeville** [comment]
I found the problem and now I can consider this issue as fixed. I had to disable "Instant Run" in Android Studio.
