### ISSUE TITLE
@ManyToMany produces table with duplicate entries

### ISSUE THREAD

**Issue by hilljh82** [Raizlabs/DBFlow#909]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Bug

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

The class auto-generated from `@ManyToMany` is missing uniqueGroups property in `@Table` annotation. Otherwise, you are able to have the same relation between either model appear multiple times in the table. If this is the intention, then `@ManyToMany` needs an additional property that allows developers to choose what kind of fail action to apply the relation if it appears multiple times in the database. From the scenarios where I have wanted to use `@ManyToMany`, I wanted the insert to just fail if it was already present in the relation table.

**Comment by agrosner** [comment]
to prevent dupes, use `generateAutoIncrement=false` to use both primary keys as the objects. Otherwise Id just code in manually your own table for that.
