### ISSUE TITLE
Customize table name for @ManyToMany

### ISSUE THREAD

**Issue by hilljh82** [Raizlabs/DBFlow#910]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Feature/Bug

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

You can customize the generated class name for `@ManyToMany`, but you cannot customize the name of the table in the database. This feature is needed so developers can ensure consistency in their naming conventions. Moreover, with support for modules, there is even more risk to table name clashes if multiple modules have the same relation between models even though the actual model classes will not clash.

**Comment by agrosner** [comment]
the `generatedTableClassName` is the same as what itll be in the DB.
