### ISSUE TITLE
IfNull method

### ISSUE THREAD

**Issue by hilljh82** [Raizlabs/DBFlow#911]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Feature

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

It would be great if you can add support for the `IFNULL` method. I was able to create a new `Method` on-the-fly for IFNULL below. We could support this method by default in DBFlow.

``` java
new Method ("IFNULL", [property], [property])).as ([alias])
```

**Comment by rhespanhol** [comment]
I also need to use IfNull method. How can I do this?

**Comment by agrosner** [comment]
in 4.0.0-beta4

**Comment by hilljh82** [comment]
Awesome!!!! I have more coming as well. 😉

**Comment by hilljh82** [comment]
Also, do you want me to write usage file for the loaders?
