### ISSUE TITLE
Request to create Git Page website for DBFlow

### ISSUE THREAD

**Issue by msimar** [Raizlabs/DBFlow#916]
DBFlow is promising database for Android, but the information is scattered and examples are not up to date. It is hard to find information and easy to lost in .md files.

Description: 

Please create a website and put relevant information like api's and examples at one place. 

Git pages are free and it can be easily integrated with Git repository:  https://pages.github.com, you can also go for better option. 

You can take Square Otto (http://square.github.io/otto/) as example.  

Thanks in advance.

**Comment by jesseiqmi** [comment]
Yes!  We're using it for our project internally and have had to hunt as far down as the testing levels to figure out how to use some of the advanced features of query building using the ORM, or best ways to use Cursors for scalar methods (assuming that one is coming straight to DBFlow directly without having used cursors before), etc.

**Comment by rspl17** [comment]
@jesseiqmi any update on this, as it helps us to create a right database structure

**Comment by agrosner** [comment]
got gitbook https://agrosner.gitbooks.io/dbflow/content/ so I believe this covers it.
