### ISSUE TITLE
boolean getter isIs...

### ISSUE THREAD

**Issue by aliusa** [Raizlabs/DBFlow#917]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): bug

Description: 
I have private column named **IsDeleted**, and ColumnValidator showing that element should have getter named **isIsDeleted**.  
I have method **isDeleted()**, and ColumnValidator should accept predefined **is**.

**Comment by aliusa** [comment]
For now I just have

```java
@Column(name = "IsDeleted")
private boolean Deleted;

public boolean isDeleted() {
  return Deleted;
}
```

**Comment by agrosner** [comment]
in `develop` should be fixed.
