### ISSUE TITLE
Generated content provider customisation

### ISSUE THREAD

**Issue by dwaynehoy** [Raizlabs/DBFlow#918]
DBFlow Version: 3.1.1
Issue Kind: Feature/Bug

Description: 

I currently need to add customised Uri's to my generated content provider in order to create some union queries that cannot be handled with simple views, however the content provider is a final class so I cannot extend it. 

If final was removed from this class I could extend it and make the modifications where necessary, passing back non-customised URI's to the generated provider to handle

**Comment by agrosner** [comment]
its `final` for a reason, in that you shouldn't ever extend or (try to avoid) using generated code directly. In the unlikely event the underlying code is refactored and you can no longer do what you wanted to do. 

As for customized uris, my best bet is for more advanced implementations..what kind of URis are you talking about? sorry for the late reply.
