### ISSUE TITLE
Updating primary key field

### ISSUE THREAD

**Issue by danielulrik** [Raizlabs/DBFlow#919]
DBFlow Version: 3.0.1

Since the method save() doesn't return the saved id, i was hoping that DbFlow would handle that task of updating my model, but this happens only if the @PrimaryKey field has the attribute (autoincrement = true) . Is there any other way that i can update my Id field without making another query?

**Comment by agrosner** [comment]
You can specify a custom `ModelSaver` within a `TableConfig` that you specify within a `DatabaseConfig` class. There isn't great documentation on that but you would do something like:

```
FlowManager.init(new FlowConfig.Builder(this)
    .addDatabaseConfig(new DatabaseConfig.Builder(MyDatabase.class)
        .addTableConfig(new TableConfig.Builder(MyTable.class).
              .modelAdapterSaver(new CustomModelSaver())
              .build())
     .build())
    .build());
```

Custom Model Saver would do something like:

```
public class CustomModelSaver extends ModelSaver<MyModel, MyModel, ModelAdapter<MyModel>> {

    @Override
    public synchronized long insert(@NonNull MyModel model, @NonNull DatabaseStatement insertStatement) {
        long rowId = super.insert(model, insertStatement);
        model.setId(rowId);
        return rowId;
    }
}

```

**Comment by danielulrik** [comment]
It works only if i do this:

`public class CustomModelSaver extends ModelSaver<MyModel, MyModel, ModelAdapter<MyModel>> {

 public CustomModelSaver() {
    }

    @Override
    public synchronized long insert(@NonNull MyModel model, @NonNull DatabaseStatement insertStatement) {
        setAdapter(FlowManager.getModelAdapter(MyModel.class));
        setModelAdapter(FlowManager.getModelAdapter(MyModel.class));
        long rowId = super.insert(model, insertStatement);
        model.setId(rowId);
        return rowId;
    }
}`

If i set the adapter at the constructor, i get the exception: 
InvalidDBConfiguration
Table: MyModel is not registered with a Database.  Did you forget the @Table annotation?

Thanks for the reply.

**Comment by aimanbaharum** [comment]
Can this be done by default? 

For example, in BaseModel, `insert()` would return `long rowId`. I'm thinking something along these lines:

```java
public long insert() {
    getModelAdapter().insert(this);
    ...
    return rowId;
}
```

Not sure how to do this by hand. I need to fully explore the library first, if it's possible.

**Comment by Alfiva** [comment]
The insert method in ModelAdapter is like this:

`    @Override
    public void insert(TModel model) {
        getModelSaver().insert(model);
    }`

And that .insert(model) does return the id, but it is ignored there because it is "void". It would only need to return that id and you could get it in BaseModel.

**Comment by agrosner** [comment]
in 4.0.0-beta2 and the `insert()` returns `long`.
