### ISSUE TITLE
async insert doesn't exist

### ISSUE THREAD

**Issue by alvarogtx300** [Raizlabs/DBFlow#921]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Bug

Description:
I'm trying to make an asynchronous insertion as in the example of the documentation:

``` java
SQLite.insert(SomeTable.class)
  .columns(SomeTable_Table.name, SomeTable_Table.phoneNumber)
  .values("Default", "5555555")
  .async()
  .execute()
```

But the async method is not defined for this operation. Is an error of documentation or a code bug?

**Comment by agrosner** [comment]
Can you be more specific, as in the method exists, but is it not inserting data? Im confused.

**Comment by alvarogtx300** [comment]
When I do an operation like the above example, I get a compile error. _Cannot resolve method 'async()'_
If I remove the _async()_, it works correctly, but I wanted to do it asynchronously.

I tried it with other operations such as select, update, delete and it works. So it seems pretty strange.

**Comment by agrosner** [comment]
Looks like its not in those classes. Its an ehancement.

**Comment by agrosner** [comment]
By mistake it is part of the `BaseQueriable` interface, not the `BaseModelQueriable`

**Comment by agrosner** [comment]
But you can construct an `AsyncQuery` manually.

**Comment by alvarogtx300** [comment]
Thanks, I'll keep that in mind.

**Comment by agrosner** [comment]
now you can do:
```java
SQLite.insert(SomeTable.class)
  .columns(SomeTable_Table.name, SomeTable_Table.phoneNumber)
  .values("Default", "5555555")
  .async()
  .execute()
```
in `develop` for 4.0.0-beta4.
