### ISSUE TITLE
No way to reopen closed database

### ISSUE THREAD

**Issue by douo** [Raizlabs/DBFlow#925]
DBFlow Version: 3.1.1
Issue Kind : Bug
Description: 

`FlowSQLiteOpenHelper#getDatabase` always return same `SQLiteDatabase`. I think `FlowSQLiteOpenHelper#getDatabase` should work like `SQLiteOpenHelper#getWritableDatabase`: if the database is closed it will create new database instead.

**Comment by agrosner** [comment]
in `develop`.

**Comment by jermainedilao** [comment]
Im using 3.1.1, and I experience this issue too. Is the fix gonna be available to that release too?

**Comment by felipezf** [comment]
@agrosner This is not working on version 4.0.4. I received this after a reset and insert:
The database '/xxx/xxx/App.db' is not open. Could you check?

**Comment by CapnSpellcheck** [comment]
@douo What about addressing the cached prepared statements? ModelAdapter.java @ 4.0.0-beta3:

```
    /**
     * @return The pre-compiled insert statement for this table model adapter. This is reused and cached.
     */
    public DatabaseStatement getInsertStatement() {
        if (insertStatement == null) {
            insertStatement = getInsertStatement(
                    FlowManager.getDatabaseForTable(getModelClass()).getWritableDatabase());
        }

        return insertStatement;
    }
```

I still got a stack trace

>                                      java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
>                                          at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
>                                          at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
>                                          at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
>                                          at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
>                                          at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:786)
>                                          at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
>                                          at com.raizlabs.android.dbflow.structure.database.AndroidDatabaseStatement.executeInsert(AndroidDatabaseStatement.java:77)
>                                          at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.insert(ModelSaver.java:104)
>                                          at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:48)
>                                          at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:31)
>                                          at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:102)
>                                          at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:62)

See how we use the cached statement, and in SQLiteStatement it goes to SQLSession. So the cached session is bad -- we need to clear all cached statements. Is there a way to do this? I don't know if this has been updated post beta3, unfortunately, I'm stil lon 4.0.0.

**Comment by CapnSpellcheck** [comment]
Best idea for how to resolve. Critiques? Suggestions?

```
// workaround for https://github.com/Raizlabs/DBFlow/issues/925 my comment (CapnSpellcheck)
            val insertStatementField = ModelAdapter::class.java.getDeclaredField("insertStatement")
            insertStatementField.isAccessible = true
            val compiledStatementField = ModelAdapter::class.java.getDeclaredField("compiledStatement")
            compiledStatementField.isAccessible = true

            val adapters = FlowManager.getDatabase(Database::class.java).modelAdapters
            for (mad in adapters) {
                Log.d(tag_, "Resetting model adapter ${mad.javaClass.simpleName}")
                insertStatementField.set(mad, null)
                compiledStatementField.set(mad, null)
            }
```
