### ISSUE TITLE
TypeConverter is not called during execution of select queries

### ISSUE THREAD

**Issue by schatekar** [Raizlabs/DBFlow#930]
This is linked to #929 

I could make my custom type converter  by applying it on individual fields but now I have noticed that type converter kicks in only when I am saving entities. I am trying to select entities and where clause of select has an equality condition on the field which has this type converter applied but type converter just does not kick in at all. Are type converter evaluated only during projection?

**Comment by rhespanhol** [comment]
I'm having the same problem. Were you able to solve it @schatekar ?

**Comment by schatekar** [comment]
@rhespanhol I needed a custom type converter for date types as I wanted to store dates in a string format. I ended up changing my implementation to store the dates in long format using the OOTB type converter for date types. Not what you may have expected but I was not too fussed about it in the short run.

**Comment by agrosner** [comment]
I see what you mean. You mean that you'd prefer that the `Property` generated for the field obey the database type of the `TypeConverter`?

**Comment by agrosner** [comment]
adding a class called `TypeConvertedProperty` which will allow you to call `databaseProperty()`, inverting the `Property` to one that accepts the database value of the property.

**Comment by agrosner** [comment]
to update this, for any field with a `TypeConverter` we use a `TypeConverterProperty` which will use the same field used in the `ModelAdapter` for its operations that matches what the individual field defines as type converter! 4.0.0-beta2
