### ISSUE TITLE
Unable to save child object fields with its parent

### ISSUE THREAD

**Issue by Ambujesh** [Raizlabs/DBFlow#931]
I have an object from server -

@Table(database = DataBase.class, insertConflict = ConflictAction.REPLACE, updateConflict = ConflictAction.REPLACE)
public class Version extends BaseModel {
    @Column
    @PrimaryKey(autoincrement = true)
    public int id;

    @Column
    @Unique
    public String version_id;

    @Column
    public String version;
    @Column
    public String make_id;

    @Column
    public String model_id;

    @Column
    public String fuelType;

    @Column
    public String makeModelVersion;

    @SerializedName("fuel")
    @Expose
    public Fuel fuel;

    public class Fuel {

        @Column
        @SerializedName("fuelId")
        @Expose
        public Integer fuelId;

        @Column
        @SerializedName("fuelName")
        @Expose
        public String fuelName;

        @Column
        @SerializedName("unit")
        @Expose
        public String unit;

        @Column
        @SerializedName("updatedAt")
        @Expose
        public String updatedAt;
    }
}

i 
I want -
1 - Fuel object to be saved as a field in Version and not to create another table for fuel ?

                                        OR

2 - If i have to create a table for fuel then how can i map the fuel fields with that of versions??

**Comment by agrosner** [comment]
`Fuel` should be defined as a `@ForeignKey(saveForeignKeyModel = true)` and when top level class saved, the foreign key is also saved.
