### ISSUE TITLE
FastStoreModelTransaction.saveBuilder,will call each item .save() method?

### ISSUE THREAD

**Issue by wangsuicheng** [Raizlabs/DBFlow#932]
DBFlow Version3.1.1:
FastStoreModelTransaction.saveBuilder(FlowManager.getModelAdapter(TestModel2.class)).addAll(modelList).build().execute()

This FastStoreModelTransaction will call TestModel2.save() method of each item of modelList??
how does it deal with in dbflow source code?

```
myModel{
   @Override
    public void save() {
        beforeSave();
        super.save();
    }
}
```
because when myModel save , I must do some my owner operation...

**Comment by agrosner** [comment]
no, `FastStoreModelTransaction` is operating as fast as possible, meaning reusing everything where plausible. If you need to actually call `save()` on each model, use the `ProcessModelTransaction`.
