### ISSUE TITLE
Cannot Use External Models

### ISSUE THREAD

**Issue by MiguelChan** [Raizlabs/DBFlow#933]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Bug

Description: 
I'm trying to use DbFlow external Models and is not working.

I have a jar file, that contains all the Models (I cannot modify them). When I try to create Entity objects when extending the Jar Models, DbFlow will simply not generate the correct Helpers. It does generate the module local Helpers but then, It references a Helper from the other Jar.

**Comment by agrosner** [comment]
Yes, the helpers are needed to reside in the same package as class created. Not sure what generate correct helpers mean?

**Comment by agrosner** [comment]
It must be in same module to generate the correct helpers as they are processed in different annotation processing environments. Creating a helper in the local package might clash with the helper potentially generated in the library project package.

**Comment by agrosner** [comment]
closing this, not going to implement. sorry.
