### ISSUE TITLE
Method class should be made generic

### ISSUE THREAD

**Issue by trevjonez** [Raizlabs/DBFlow#936]
DBFlow Version: 3.1.1
Description: The `Method` class should be made generic to follow the same pattern of type safety that the property class exposes.

Consider the following query:

```
SQLite.select()
.from(SomeModel.class)
.where(new Method("LOWER", SomeModel_Table.name).eq(name.toLowerCase())
.querySingle();
```

Because the `Method` class is not typed like the base property class the call to `eq(...)` becomes unchecked.

Also it would be great if we could add some of the other sqlite supported methods to the predefined set within the `Method` class

Current workaround is a method with an unchecked assignment:
```
Property<String> lower(@NonNull Property<String> property) { return new Method("LOWER", property); }

**Comment by agrosner** [comment]
By typing it, it will limit the kind of `Property` that can go into the class, and that's not what I would like.
