### ISSUE TITLE
Problem with inheritance

### ISSUE THREAD

**Issue by mhswtf** [Raizlabs/DBFlow#938]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Bug

Description: 
I have a model with a superclass called `RemoteObject,` which provides, among other things, a primary key id.

I have different subclasses of `RemoteObject` that reference each other. If these subclasses have limited access to the inherited fields, like `id,` if they are placed in a different package for example, the generated code uses a `RemoteObject_Helper` class that does not exist, to access these fields. 

Example:
`RemoteObject` is in the package `..model`
`RemoteObject` has protected field `id`
`Friend` is a subclass of `RemoteObject,` and is in package `..model.social`
Generated `Friend_Helper` class now uses `RemoteObject_Helper.getId()` method to retrieve the `Friend` id, but the `RemoteObject_Helper` class has not been generated.

This is easily fixable by making the inherited fields public, but I thought I might bring it to your attention.

Thanks!

**Comment by agrosner** [comment]
thank you for report. We only generate helper methods for fields that are referenced dynamically. This is to cut down on actual code gen for these helpers, instead of generating one for every class used. Ill keep this on my radar.

**Comment by agrosner** [comment]
should be fixed in 4.0.0 - but if you see this again, please reopen.
