### ISSUE TITLE
Can't use existing SQLite database

### ISSUE THREAD

**Issue by AlexanderKutoviy** [Raizlabs/DBFlow#939]
@agrosner Hi, I've got my database in assets folder, the name of the file and name of the db in placeholder class are the same. I've got all @Table classes  that refer to the prepackaged db. But after starting the app the database file under assets is not copied to data/data/<app>/databases but an empty DB is created there. How can I solve this issue?
Thanks!

**Comment by trevjonez** [comment]
A quick workaround would be check if copying from assets is appropriate and if so just copy the file yourself. All of this needs to happen before you setup the flow manager instance.

I am doing a similar song and dance to facilitate a migration from active android to db flow in an app that has already been in the wild for over a year.

**Comment by AlexanderKutoviy** [comment]
@trevjonez Thanks, your answer was helpful=)

**Comment by indioalba** [comment]
@agrosner , I am rewriting an app trying to reuse a .sqlite file, I put it in the app/src/main/assets folder I renamed it to .db but seems that is not copied and instead when I make any query it's empty. Do I need to create a   BaseDatabaseHelper class ? do I need to copy the file manually to 
 /data/user/0/.../databases/mydatabase  ?
