### ISSUE TITLE
Using Prepared / Compiled Statements?

### ISSUE THREAD

**Issue by ScottPierce** [Raizlabs/DBFlow#941]
Forgive me if this is documented, but I can't seem to find anything about using prepared / compiled statements with DB Flow? Is this something that's possible?

**Comment by agrosner** [comment]
no documentation really but doing queries in the SQLite query language you can create a precompiled statement using the `compileStatement()` method. 

For example:
```
DatabaseStatement statement = SQLite.select().from(...).compileStatement();
```

`DatabaseStatement` is just a wrapper around `SQLiteStatement` which allows us to use both Android + SQLCipher.
