### ISSUE TITLE
using SqlCipher is still err

### ISSUE THREAD

**Issue by Swordce** [Raizlabs/DBFlow#942]
![image](https://cloud.githubusercontent.com/assets/16829238/17505776/0986330c-5e36-11e6-90a8-8db0da844189.png)
![image](https://cloud.githubusercontent.com/assets/16829238/17505782/1303f838-5e36-11e6-961c-4c2c10bd22f0.png)
![image](https://cloud.githubusercontent.com/assets/16829238/17505790/2018100e-5e36-11e6-9c11-44733cee47ce.png)

Should I how to do ?

**Comment by agrosner** [comment]
Did you try including the dependency:
```
    compile "net.zetetic:android-database-sqlcipher:3.5.1"

```
directly?
