### ISSUE TITLE
One to many relations broken?

### ISSUE THREAD

**Issue by leovanhaaren** [Raizlabs/DBFlow#944]
DBFlow Version: **3.1.1**
Issue Kind: **Bug**

Description: 
I'm currently stuck on a problem with DBFlow v3.1.1

**EventEntity.java**

```
@Table(database = AppDatabase.class)
@ModelContainer
public class EventEntity extends BaseModel {

    @PrimaryKey
    public int id;

    @Column
    public Boolean deleted;

    @Column
    public String imageUrl;

    public List<EventTextEntity> eventText;

    @OneToMany(methods = {OneToMany.Method.ALL}, variableName = "eventText")
    public List<EventTextEntity> getEventTexts() {
        if (eventText == null) {
            eventText = new Select().from(EventTextEntity.class)
                    .where(EventTextEntity_Table.eventEntity_id.eq(id))
                    .queryList();
        }
        return eventText;
    }

```

**EventTextEntity.java**

```
@Table(database = AppDatabase.class)
@ModelContainer
public class EventTextEntity extends BaseModel {

    @PrimaryKey
    public int id;

    @Column
    public String title;

    @Column
    public String description;

    @ForeignKey
    ForeignKeyContainer<EventEntity> eventEntity;

    public void associateEventEntity(EventEntity eventEntity) {
        this.eventEntity = FlowManager.getContainerAdapter(EventEntity.class).toForeignKeyContainer(eventEntity);
    }
}

```

The ForeignKeyContainer<EventEntity> causes the app to freeze on start-up and it simply won't boot. When I remove it, the app works but the relations are not how I want them. No errors/warnings show up in logcat. I've read the documentation and even checked the dbflow tests for code samples but still cannot get it to work.

Any advice or is this simply a bug?

**Comment by agrosner** [comment]
Is this due to a recursion problem and have you debugged to see what is going on?

**Comment by leovanhaaren** [comment]
I've tried to debug but the app won't even boot so there is no DBFlow related debugging output. It's really weird, seems to me that somewhere inside DBFlow, where it creates the database, it fails/freezes.

Maybe I'm doing something wrong, but the only thing I want is that a EventEntity can have multiple EventTextEntities and the EventTextEntity should also know to which EventEntity it belongs. The above code is based on the documentation, but the documentation does not cover this case totally so I might be overlooking something here?

**Comment by agrosner** [comment]
not sure. did you end up discovering the issue here?
