### ISSUE TITLE
No result callback with query

### ISSUE THREAD

**Issue by rashaverak** [Raizlabs/DBFlow#945]
DBFlow Version: 3.1.1.

Description: Is it really true that in 3.1.1 there is no way to get callback when there is no result ? Because this is total showstopper to use this library. I mean this is pretty basic.

**Comment by rashaverak** [comment]
Seems the listener is not called even when there is result, I mean for no result it is not even supposed to get called (not sure why it is annotated as Nullable) but it does not trigger the callback even when there is  the result. Reverted back to 3.0.0-beta5 a will look for some other stable working db library.

**Comment by agrosner** [comment]
you need to call `execute()` to actually execute the query.
