### ISSUE TITLE
InvalidDBConfiguration error when adding a table in child project

### ISSUE THREAD

**Issue by FarhanAhmad** [Raizlabs/DBFlow#948]
DBFlow Version: 3.1.1
Issue Kind: Question

Description: 
I added dbflow in my library project(A) and its working as expected. My Question is, I created another library project lets say B. now B has A added as dependency. and created a table TableB in B. when I run it, it gives following error:
com.raizlabs.android.dbflow.structure.InvalidDBConfiguration: Model object: com.package.TableB is not registered with a Database. Did you forget an annotation?

**Comment by agrosner** [comment]
cross module models that belong to same DB are not supported. Not sure if thats same isssue, please reopen if its not.
