### ISSUE TITLE
Multiple modules with one database

### ISSUE THREAD

**Issue by skhanzada** [Raizlabs/DBFlow#951]
how does it work when one module is dependent on another module?

I have a shared module that defines some model classes lets say ClassA. I have another module that has ClassB which uses ClassA in a foreignKeyContainer. Now since both modules have their own Database classes i am getting the following error:

@Table(database = ModuleADB.class)
public class ClassA extends BaseModel implements Serializable {
@PrimaryKey
String code;
}

@Table(database = ModuleBDB.class)
public class ClassB extends BaseModel implements Serializable {

@ForeignKey
ForeignKeyContainer<ClassA> classA;

}

class com.raizlabs.android.dbflow.processor.definition.column.ForeignKeyColumnDefinition: Could not find the referenced table definition my.package.ClassA from ClassB Ensure it exists in the samedatabase my.package.ModuleBDB

I have two database holder added in my flow manager but the error i am getting is on compile time.

```
FlowManager.init(new FlowConfig.Builder(this).
        addDatabaseHolder(ModuleAGeneratedDatabaseHolder.class).
        addDatabaseHolder(ModuleBGeneratedDatabaseHolder.class).
        build());
```

I don't want to create the two databases because i want to link tables from ModuleA in ModuleB.

Thanks,

**Comment by agrosner** [comment]
Not supported as of now. Might consider adding it to future release.

**Comment by agrosner** [comment]
cant do cross DB references in the lib. Not supported.
