### ISSUE TITLE
Indexes on Galaxy S4 Mini Android 4.4.2

### ISSUE THREAD

**Issue by relevante** [Raizlabs/DBFlow#953]
DBFlow Version: 3.1.1

We've been using DBFlow for about 6 months in an app with around 600 active Android users on a variety of devices. It's working fine for almost everyone, but we just recently got two complaints that it wasn't working on the Galaxy S4 Mini (only the mini - coincidentally, one of the S4 mini users with this issue has a partner with a regular S4 and it works perfectly on the regular S4 and is broken on the mini).

I had no idea, so I just bought a device to test and it turns out that DBFlow is throwing a SQLite error that it cannot use an index. It's being created at startup using a version zero migration as discussed in #160. It works fine on all of our other test devices (and our users) across versions 4.3+, 5 and 6 of Android.

I just checked the logs and the version zero migration to create the index is running on the initial app launch (or at least its getIndexProperty() is getting called).

Any ideas where I should start looking? Is SQLite baked into DBFlow or is it using a version that's somehow shared with the rest of the Android install? Other thoughts?

Thanks!

**Comment by agrosner** [comment]
No. Each device is responsible for its own version of SQLite. It may be that the version of it on the device doesnt support indexes. That to me sounds strange though. can you send log of what error it says.
