### ISSUE TITLE
Generate a template database

### ISSUE THREAD

**Issue by ovidiucp** [Raizlabs/DBFlow#954]
DBFlow Version: 3.1.1
Issue Kind (Feature): Enhancement

Description: 

I'd like to ship with my app a template, pre-built database.

For the equivalent app I have running on iOS I use Apple's CoreData on MacOS X as a separate step in the build process. In this step I build and run a program which uses the same model classes as I have in the mobile app which populates the database with the data I need. The build process then simply copies the SQLite files as resources for the mobile app. The first time the app is run, these template files are used to create the real database.

Is there a way to do the same with DBFlow using an automated build rule? I've tried doing this by putting the model classes in a separate `model` module for my Android app. My `model` module's `build.gradle` looks like this:

```
apply plugin: 'java'
apply plugin: 'com.neenbedankt.android-apt'

def dbflow_version = "3.1.1"

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    apt "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    // use kapt for kotlin apt
    compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
    // sql-cipher database encyrption (optional)
    compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:${dbflow_version}@aar"
}
```

However it looks like the annotation processor requires the `android` gradle plugin:

`Error:(3, 0) The android or android-library plugin must be applied to the project
`

Any thoughts on how this could be done?

**Comment by ovidiucp** [comment]
It looks like there's no easy way of doing this, since the generated code depends heavily on the Android database code.

What I ended up doing is to write a small Python helper program that uses [SQLAlchemy](http://www.sqlalchemy.org/), which is an excellent ORM library I'm already using on the server side. I wrote few SQLAlchemy-based classes very similar to the classes written in Java for DBFlow, then wrote a small program that uses those classes to generate the schema, fetch the data from a server, and populate the database using the SQL. I copied the resulting database file in the `src/main/assets/` directory of my Android project. The first time the Android application runs, the DBFlow uses the file as a template database. It copies it over to the appropriate directory and uses it from then on.

It works beautifully, including using SQLCipher.

It would still be nice to have a different set of classes that can be generated by the DBFlow processor that could run on the desktop, to avoid duplication of code. Still, since the template database does not need to contain all the tables the Android app needs, this solution is quite satisfactory.

**Comment by agrosner** [comment]
I think it sounds like you mean [Prepackaged Databases](https://github.com/Raizlabs/DBFlow/blob/master/usage2/Databases.md#prepackaged-databases) ? I dont believe theres a good way of making the DB before DBflow uses it unless you just add that prepopulation code in a 0-Migration.
