### ISSUE TITLE
Migrations doesn't work at all.... 

### ISSUE THREAD

**Issue by wajahatkarim3** [Raizlabs/DBFlow#955]
DBFlow Version: 3.1.3
Issue Kind (Bug, Question, Feature): Question

Description: 
So, its been three days, I have trying to figure out how exactly migrations work. I tried adding subclass in the Database file of migrations and adding column in preMigrate() method but nothing I got. 

I also tried sql statements in migrations folder of assets but still nothing I got. 

Can you please tell me with some proper and complete example about how exactly migrations work here. I also have looked at the documentation but that doesn't tell much as well.

All I am trying to do is add new column and initialize default values in all records of that column.

**Comment by fabiendem** [comment]
It may sound obvious but have you increased the version number of your DB via the annotation
`@Database(version = 2, name = AppDatabase.NAME)`?

**Comment by wajahatkarim3** [comment]
Yes, I tried all kinds of methods mentioned in this repository issues, documents, but I am unable to merge all the pieces. I think I am missing something but there is no proper complete example of how to do it?

**Comment by wajahatkarim3** [comment]
I finally got it working with migrations directory in Assets. Thanks
