### ISSUE TITLE
Getting warning on every build.

### ISSUE THREAD

**Issue by therajanmaurya** [Raizlabs/DBFlow#957]
DBFlow Version: 3.1.1
Issue Kind : Question

Description: This version is working fine with my GSoC project but getting  warning whenever I am building the project 
```java
Warning:File for type 'com.raizlabs.android.dbflow.config.MifosDatabaseMifos_Database' created in the last round will not be subject to annotation processing.
Warning:File for type 'com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder' created in the last round will not be subject to annotation processing.
```

How can I remove this warning?

**Comment by trevjonez** [comment]
These warnings are a result of the way the annotation processor defers the generation of those files until the final round of processing. This allows tables that are generated in the first round of processing to not be missed when the database and holder are generated. (I have a PR #947 that adds the content provider to the list of final round deferred classes as well).

There may be a way to silence the warning but they are nothing to worry about and can be disregarded. You might even consider the warning to be a good sign as it is quick proof of how robust the annotation processor is and shows some of how it works, thus enabling advanced work flows.
