### ISSUE TITLE
'new Select().from(DownloadInfo.class).count()' always return 0

### ISSUE THREAD

**Issue by MagicianCui** [Raizlabs/DBFlow#958]
DBFlow Version:3.1.1
Issue Kind (Bug, Question, Feature): Question

I want to count the number of table rows, when I use 'new Select().from(DownloadInfo.class).count()', always return 0, only using 'SQLite.select().from(DownloadInfo.class).queryList().size()' returns the correct number.  But I just want the number of table rows , not the model list.

**Comment by trevjonez** [comment]
Do `SelectCount()` so the resulting query is `select count(*) where ...`

**Comment by MagicianCui** [comment]
Thanks, and I use 'SQLite.selectCountOf().from(DownloadInfo.class).count()' and it returns the correct number
