### ISSUE TITLE
Create relationships from ids

### ISSUE THREAD

**Issue by marwfair** [Raizlabs/DBFlow#960]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Question

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description:  I looked through the Relationships documentation but didn't see a way to create table relationships from only using an id.

Here is my case:
I fetch data from an api. I have to hit several endpoints to get my data, and they could be in any order and fetched at different times. I want to be able to create relationships between "cars" and "owners" so in my app, I could just call car.getOwner() or owner.getCars().

cars.json

``` json
{
  "cars": [
    {
      "id": 1,
      "name": "car 1",
      "owner_id": 2
    },
    {
      "id": 2,
      "name": "car 2",
      "owner_id": 1
    },
    {
      "id": 5,
      "name": "car 5",
      "owner_id": 2
    }]
}
```

owners.json

``` json
{
  "owners": [
    {
      "id": 1,
      "name": "owner 1",
      "car_ids": [2]
    },
    {
      "id": 2,
      "name": "owner 2",
      "car_ids": [1,5]
    }]
}
```

If I fetch owners.json first and store it in my database, I do not have the cars available yet to create that relationship. From looking at the documentation, it looks like that I would have to associate the  owner to the car by creating an "associateCar" method in the Owner class and pass in the car object to create that relationship. The only thing I know about the car at this point is the id.

For now, I am just writing my own queries when I need to find the owner of the car or the cars that belong to the owner.

This is just an example of my data. I also have many-to-many relationships. For those, I am creating my own "join" tables containing only the ids of the objects that are associated. All of this is working fine, but I would like to do it the DBFlow way and remove a lot of my code.

Please let me know if this is possible. Thanks!

**Comment by agrosner** [comment]
I'd take a look at (https://github.com/Raizlabs/DBFlow/blob/master/usage2/Relationships.md) 
And the `OneToMany` relationships section. You can use `car_ids` and have it based on the cars that exist by a lazy loaded query.
