### ISSUE TITLE
about migrations issues

### ISSUE THREAD

**Issue by fingerart** [Raizlabs/DBFlow#961]
DBFlow Version:3.1.1
Issue Kind (Bug, Question, Feature):Question

Description: 
I have 3 versions, now upgrading from version 1 to version 3. version 2 adds a column of fields to the A table, version 3 modifies the table name of the A table from A1 to A2

I install version 1 from version 3 directly to apk, 
``` java
@Migration(version = 2, database = OrangeDatabase.class)
public class Migration2 extends AlterTableMigration<AppUpgrade> {
    private static final String TAG = Migration2.class.getSimpleName();

    public Migration2(Class<AppUpgrade> table) {
        super(table);
    }

    @Override
    public void onPreMigrate() {
        Log.d(TAG, "onPreMigrate() called with: " + "");
        addColumn(SQLiteType.TEXT, AppUpgrade_Table.date.toString());
    }
}

@Migration(version = 3, database = OrangeDatabase.class)
public class Migration3 extends AlterTableMigration<AppUpgrade> {
    private static final String TAG = Migration3.class.getSimpleName();

    public Migration3(Class<AppUpgrade> table) {
        super(table);
    }

    @Override
    public void onPreMigrate() {
        Log.d(TAG, "onPreMigrate() called with: " + "");
        renameFrom("AppUpgrade");
    }
}
```
Error:
android.database.sqlite.SQLiteException: there is already another table or index with this name: app_upgrade (code 1): , while compiling: ALTER TABLE `AppUpgrade` RENAME TO `app_upgrade`

**Comment by trevjonez** [comment]
You can use the following query (kotlin syntax shown)
```kotlin
val cursor = database.rawQuery("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = '$tableName';", emptyArray())
```

Then from the resulting cursor you can get the create statement for the table as it currently is. At which point you can examine it and determine the correct migration logic.
```kotlin
val sqlCreateStatement = cursor.getString(0)
```

Keep in mind that DBFlow creates missing tables first, then attempts to do any migrations. So in your case you can end up doing migration from 1 to 2 with a table that was pre created at the newest level 3 schema.

I would strongly recommend you keep a sqlite file from each schema version you release to the public and write unit tests that walk through the migrations for every version.

The test suite I wrote for my project checks my master.sqlite file against the schema of a freshly created database file to ensure that my master file is up to date. From there you have one test for each version of the schema, the test needs to copy the sqlite file from resources and place it where dbflow will try to open it, then initialize the flow manager to trigger migrations. once the migration is finished you need to compare the result with the master.sqlite file schema to ensure it is a correct migration.

So in your case you would have 3 tests.
`testMasterIsUpToDate()` this ensures that the file your other tests will compare against is up to date.

`testVersionOneThroughLatest()` this ensures that your version one schema database correctly migrates to version two then to version three.

`testVersionTwoThroughLatest()`this ensures that your version two schema database correctly migrates to version three.

**Comment by fingerart** [comment]
@trevjonez 
Thank you for answering my question.
This is my creat table sql:
```sql
CREATE TABLE `AppUpgrade`(`versionCode` INTEGER,`info` TEXT,`url` TEXT,`localPath` TEXT,
`forceUpgrade` INTEGER,`ignore` INTEGER, PRIMARY KEY(`versionCode`))
```
I think it's no problem, but i through `renameFrom("AppUpgrade")` rename table to `app_upgrade` is fail. In cmd execute sql `ALTER TABLE 'AppUpgrade' RENAME TO 'app_upgrade'` is success;

**Comment by trevjonez** [comment]
Can you post a copy of each different versions create schema for me? Im still confused as to what is going on and what your intent is.
