### ISSUE TITLE
Multiple column update migration not working for version 2.2.1

### ISSUE THREAD

**Issue by ankush19902** [Raizlabs/DBFlow#962]
DBFlow Version:2.2.1
Issue Kind : Question

Description:

I am doing a update migration like this but only first statement gets updated the next statement get ignored, i mean the previous value is retained.

```
@Migration(version = 5, databaseName = FadeDatabase.NAME)
public class MessageTableUpdateMigration_3 extends UpdateTableMigration<Message> {
    public MessageTableUpdateMigration_3() {
        super(Message.class);
    }
    @Override
    public void onPreMigrate() {
        super.onPreMigrate();
        set(Condition.column(Message$Table.YOU).eq(false));
        set(Condition.column(Message$Table.OTH).eq(false));
    }
}
````

I also tried putting the these condition as combined condition under one set call. 

```
set(Condition.column(Message$Table.YOU).eq(false),Condition.column(Message$Table.OTH).eq(false));
```

Whats wrong here, is there any other way of updating these multiple column. I can't upgrade to latest version of dbflow one at the moment.

**Comment by agrosner** [comment]
I would highly suggest migrating to the newest stable version, 3.1.1.

**Comment by agrosner** [comment]
reopen if you get time to migrate and update to latest.
