### ISSUE TITLE
Adapter generation fails to produce valid java for ForeignKeyContainer targeting PrimaryKey of custom type

### ISSUE THREAD

**Issue by trevjonez** [Raizlabs/DBFlow#963]
DBFlow Version:3.1.1
Issue Kind (Bug, Question, Feature): Bug

Description: 

Given a `PrimaryModel` with primary key such as:
```java
@PrimaryKey
@Unique(onUniqueConflict = ConflictAction.REPLACE )
java.util.UUID id;
```

Using a global type converter of type:
```java
TypeConverter<java.lang.String, java.util.UUID>
```

and a `LinkModel` with reference to the `PrimaryModel` such as:
```java
@ForeignKey
ForeignKeyContainer<PrimaryModel> model;
```

processor fails to generate valid adaptor code for `LinkModel`

from `bindToInsertValues(ContentValues values, LinkModel model)`:
```java
if (model.model != null) {
  if (model.model.getValue("id") != null) {
    values.put(LinkModel_Table.model_id.getCursorKey(), model.model.getValue("id")); //Cannot resolve method 'put(java.lang.String, java.lang.Object)'
  } else {
    values.putNull(LinkModel_Table.model_id.getCursorKey());
  }
} else {
  values.putNull("`model_id`");
}
```

from `bindToInsertStatement(DatabaseStatement statement, LinkModel model, int start)`:
```java
if (model.model != null) {
  if (model.model.getValue("id") != null) {
    statement.bindString(2 + start, model.model.getValue("id")); //Wrong 2nd argument type. Found: 'java.lang.Object', Required: 'java.lang.String'
  } else {
    statement.bindNull(2 + start);
  }
} else {
  statement.bindNull(2 + start);
}
```

from `loadFromCursor(Cursor cursor, LinkModel model)`:
```java
//// Only load model if references match, for efficiency
int indexmodel_id = cursor.getColumnIndex("model_id");
if (indexmodel_id != -1 && !cursor.isNull(indexmodel_id)) {
  ForeignKeyContainer<PrimaryModel> refmodel = new ForeignKeyContainer<PrimaryModel>(PrimaryModel.class);

  refmodel.put("id", cursor.(indexmodel_id)); //Identifier expected
  model.model = refmodel;
}
```

The generation code is quite clearly not equipped to handle this, it looks like this may touch a handful of files to fix. Trying to figure it out now, any direction you can provide is much appreciated.

**Comment by agrosner** [comment]
currently this specific scenario is not currently supported. will look into it.

**Comment by agrosner** [comment]
fixed. Dont use `ModelContainer`/`ForeignKeyContainer`. replaced with `stubbedRelationship` which will makes things much cleaner.
