### ISSUE TITLE
Relations - lazy vs eager

### ISSUE THREAD

**Issue by MFlisar** [Raizlabs/DBFlow#964]
I can't find anything in the docs about the relations that tells me how dbflow will handle them.

Using 1:1 relations like following

    @ForeignKey
    @PrimaryKey
    ForeignKeyContainer<Data> data;

When will this foreign key be loaded? Will this be loaded with a left join when directly when loading the model itself or will it be loaded lazily on access only?

Actually, I would have the same question about 1:many and many:many relations as well...

I think this lazy vs eager thing is missing in the docs (although the docs are really good already!).

**Comment by leovanhaaren** [comment]
+1 on this

**Comment by agrosner** [comment]
1:1 relationship - > foreign keys loaded on load from DB if the keys are present, otherwise `null`. If not null, to load the full model up, as soon as containing table loads, call `load()`.

**Comment by agrosner** [comment]
best bet is you can look at generated code and get an idea of whats happening.

**Comment by agrosner** [comment]
`ForeignKeyContainer` are lazily loaded. regular Model objects as `ForeignKey` are eager.
