### ISSUE TITLE
The demo/app needs to be updated

### ISSUE THREAD

**Issue by roblav96** [Raizlabs/DBFlow#965]
I'm experimenting with this lovely library and the [master/app](https://github.com/Raizlabs/DBFlow/tree/master/app/src/main/java/com/raizlabs/android/dbflow) folder is very resourcful.

My only issue with it is that it doesn't seem to be up to date with the latest DBFlow syntax.

For example:
[DemoActivity.java](https://github.com/Raizlabs/DBFlow/blob/master/app/src/main/java/com/raizlabs/android/dbflow/DemoActivity.java#L19)
```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_demo);

        FlowManager.init(getApplicationContext());
    }
```
It says in the [GettingStarted.md#initialize-flowmanager](https://github.com/Raizlabs/DBFlow/blob/master/usage2/GettingStarted.md#initialize-flowmanager) to initialize `FlowManager` like so:
```java
    @Override
    public void onCreate() {
        super.onCreate();
        FlowManager.init(new FlowConfig.Builder(this).build());
    }
```
Is this `app` project up to date?

**Comment by agrosner** [comment]
no app project is not. and deleted in `develop` (among other changes that are slated for 4.0.0-beta1
