### ISSUE TITLE
Strategy for filling Model from select join

### ISSUE THREAD

**Issue by cbiasiolo** [Raizlabs/DBFlow#969]
DBFlow Version:
def dbflow_version = "3.1.1"

Issue Kind:
Question, Request

Description: 
If I have a oneToMany relationship between a Model1 and Model2 like
public class Model1 extends BaseModel {
 ...
  @OneToMany(variableName = "model2", methods = {OneToMany.Method.ALL})
  public List<Model2> getModel2(){
 ...
}
and a query  
 SELECT Model1._, Model2._ FROM Model1 JOIN Model2 ON Model1.id=Model2.id AND Model2.field='some condition'

It's possibile to obtain Model1 filled with only Model2 that fullfil Model2.field='some condition' by select projection? How?

Actually loadFromCursor of the generated class Model1_Adapter call the method 
  public List<Model2> getModel2(){
        if (model2==null || model2.isEmpty()){
            model2 = SQLite.select()....
}
first.

Thx 
Claudio

**Comment by agrosner** [comment]
yeah just add it to the condition by which the `List<Model2>` get retrieved.
