### ISSUE TITLE
BaseModel vs JSONModel

### ISSUE THREAD

**Issue by Rainer-Lang** [Raizlabs/DBFlow#97]
When should I use BaseModel - and when should I use JSONModel?
I also use a rest-api, so JSONModel is an option...

I found nothing in the docu. Maybe someone could help me.

**Comment by agrosner** [comment]
```JsonModel``` is type of ```ModelContainer``` [here](https://github.com/Raizlabs/DBFlow/blob/master/usage/ModelContainers.md). BaseModel is simply a convenience class for models. If you want ModelContainer functionality for your model class, use the ```@ContainerAdapter``` at the top of your ```Model``` class.
