### ISSUE TITLE
Case with multiple conditions

### ISSUE THREAD

**Issue by shinwan2** [Raizlabs/DBFlow#970]
DBFlow Version: 3.0.1
Issue Kind (Bug, Question, Feature): Bug
Description: 
According to [specification](https://www.sqlite.org/lang_expr.html#case), [this line](https://github.com/Raizlabs/DBFlow/blob/master/dbflow/src/main/java/com/raizlabs/android/dbflow/sql/language/Case.java#L107) should not append each CaseCondition with a comma. I get `android.database.sqlite.SQLiteException: near ",": syntax error` which is caused by resulting query
`CASE x WHEN 1 THEN a,  WHEN 2 THEN b END 'alias' ASC`.

**Comment by rhespanhol** [comment]
@shinwan2 Did you find a solution for this?

I'm running 3.1.2 and also have this problem

**Comment by shinwan2** [comment]
@rhespanhol I did a quick fix by building raw SQL query using StringBuilder. But taking a quick look at closed Pull Requests, #987 should have solved this.

**Comment by rhespanhol** [comment]
@shinwan2 yeah that was also my approach. I guess that fix is only for version 4
