### ISSUE TITLE
How to use  Query builder ?

### ISSUE THREAD

**Issue by QFilu** [Raizlabs/DBFlow#971]
DBFlow Version:3.1.1
Issue Kind ( Question, Feature):

Description: 
 how can i build a query based on certain  conditions ...

something like 

    QueryBuilder builder = SQlite.Select().from(Table)
        if(condition) {
             builder.where(something)
        }
    Cursor c = builder.query;

**Comment by trevjonez** [comment]
It would be something like:
```java
Where<SomeModel> query = SQLite.select()
                               .from(SomeModel.class)
                               .where(SomeModel_Table.date_field.greaterThan(someValue));

if(someCondition) {
   query = query.and(SomeModel_Table.other_field.eq(someOtherValue));
} else {
   query = query.and(SomeModel_Table.another_field.isNotNull());
}

Cursor cursor = query.query();
//do stuff with cursor and close it
```

**Comment by QFilu** [comment]
@trevjonez  had figured & used this functionality some other way for now  ...  but this code looks better so next time will try this way ... thanks
