### ISSUE TITLE
Drop table

### ISSUE THREAD

**Issue by katepratik** [Raizlabs/DBFlow#974]
DBFlow Version : 3.1.1
Issue Kind (Question & Bug):
Description : 

Delete.table(clazz); 

Does't drop table? Right? It only deletes the entry in the table. 
Then how to drop a table?

**Comment by trevjonez** [comment]
A drop table would need to be ran during a migration because it is a schema change.

Keep in mind that when DBFlow runs migrations it first creates any missing tables then steps through migration scripts.

**Comment by agrosner** [comment]
I dont support it directly without manually executing SQL since it is a schema change and thus migration needed. It could lead to improper use and bug tickets filed.
