### ISSUE TITLE
DBFlow 3.1.1 + SQLCipher 3.5.3 count() error

### ISSUE THREAD

**Issue by ghost1980** [Raizlabs/DBFlow#975]
On all code, like this:
> count = SQLite.select().from(Table.class).query().getCount();

sqlCipher provide an error, that cursor has not been deactivated or closed.

Logcat error:
> E/Cursor: Finalizing a Cursor that has not been deactivated or closed. database = /data/user/0/com.xxx.xxx/databases/DB.db, table = null, query = SELECT * FROM `Table`
> .sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here

build.gradle:
> def dbflow_version = "3.1.1"
> apt "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
>     compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
>     compile "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
>     // sql-cipher database encryption (optional)
>     compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:${dbflow_version}@aar"
>     compile 'net.zetetic:android-database-sqlcipher:3.5.3@aar'

**Comment by agrosner** [comment]
Not a dbflow issue, by calling `query()` you are effectively opening a `Cursor` and leaving it to garbage collection by calling `getCount()`. use the `count()` method instead.
