### ISSUE TITLE
Primitive column types will not respect default values

### ISSUE THREAD

**Issue by aimanbaharum** [Raizlabs/DBFlow#976]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Bug

Description: 

Hey guys, what is `Primitive column types will not respect default values` means?

I get this in the logcat when I noticed not all of the property is generated by @Column annotation:

```
@Table(database = MyDatabase.class)
public class Group extends BaseModel {

    @Column
    @PrimaryKey(autoincrement = true)
    private long id;

    @Column
    private String uid;

    @Column
    private String name;

    @Column
    private boolean haveGroupImg;

    @Column
    private String desc;

    @Column(defaultValue = "0")
    private boolean onlineGroup;

    @Column(defaultValue = "1")
    private boolean currentStatus;

    @Column
    private long timestamp;

    @Column
    private String currentProgress;

    @Column
    private String totalProgress;

    @Column(defaultValue = "0")
    private boolean isMute;

    @Column(defaultValue = "0")
    private boolean isSynced;

    // getters setters
}
```

In my case, `currentStatus` isn't generated.

Any fix to this?

**Comment by aimanbaharum** [comment]
Solved it.

Found out that my getters and setters for boolean type isn't properly named.

`getCurrentStatus()` whilst the correct one is `isCurrentStatus()`. The latter works fine with @Column annotation.

Before closing this issue, may I know why it behaves like this?

**Comment by agrosner** [comment]
add `@Table(useBooleanGetterSetters = true)`
