### ISSUE TITLE
Saving Model from JsonReader

### ISSUE THREAD

**Issue by fievx** [Raizlabs/DBFlow#977]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Question

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
I need to save a big Json array into the database and I can't process it as one List because on low memory devices I get Out of memory. 
So I am reading the Json array with with a JsonReader and would like to save into the database as I read it.

I tried simply calling save() each time I get a new object from the reader but it takes way too long. 

Any suggestion on the proper way to do it in DBFlow would be great.

Thanks a lot.

**Comment by trevjonez** [comment]
Have you tried using the save queue? That usually speeds thing along.

**Comment by fievx** [comment]
No I haven't.
But I solved my issue by saving the Json file into List without passing by
a JsonObject. Creating the JsonObject was the real problem.

And saving a List to database is so much faster than anything else I've
tried that I'll leave it like this.

Thanks for answering so fast.
