### ISSUE TITLE
from hibernate

### ISSUE THREAD

**Issue by Rainer-Lang** [Raizlabs/DBFlow#98]
Is this also possible or maybe there are plans to implement this...
for columns:
1)
@Pattern(regexp = "(STANDARD|GOOGLE|FACEBOOK)", message = "Value not supported/allowed. Available values are STANDARD, GOOGLE or FACEBOOK")

2)
@Length(max=45, message="Allowed value length 1-45")

**Comment by agrosner** [comment]
you can specify a ```@Column(length = {length})``` as for validation for specific columns. For pattern checking you might mean a ```SQLite check()``` function and that is not currently supported. The ```@Pattern``` here may operate differently and sounds like an intriguing idea. No current plans to implement that aspect and not sure it's particular use.
