### ISSUE TITLE
Setting condition to update an object

### ISSUE THREAD

**Issue by aimanbaharum** [Raizlabs/DBFlow#980]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Question

Description: 

Guys, how do I set conditions to update an object?

**Comment by trevjonez** [comment]
I personally have not used the syntax but would imagine it would be something along these lines.

```java
SQLite.update(SomeModel.class)
      .set(SomeModel_Table.value.eq(someValue)
      .where(SomeModel_Table.id.eq(someId)
      .execute();
```

**Comment by aimanbaharum** [comment]
I have several properties to update, is there a way to just set by model class (pojo) and have it processed in `.set()`? Or I have to set it individually?

**Comment by trevjonez** [comment]
You can just update the pojo and call `.save()` on the model.
