### ISSUE TITLE
Can't find proguard rules for dbflow

### ISSUE THREAD

**Issue by ghost1980** [Raizlabs/DBFlow#982]
DBFlow Version: 3.1.1

This is not working:

> -keep class com.raizlabs.android.dbflow.** { *; }
> -keep class com.project.db.**

Error on code "SQLite.select().from(MyTable.class).querySingle()"

> Fatal Exception: com.raizlabs.android.dbflow.structure.InvalidDBConfiguration: Model object: com.project.a.g is not registered with a Database. Did you forget an annotation?

So what is the proguard rules to avoid obfuscation for dbflow model objects?

**Comment by trevjonez** [comment]
Have you tried annotating you model class with @Keep?

**Comment by ghost1980** [comment]
> @Keep
> @Database(name = DBMain.NAME, version = DBMain.VERSION)
> public class DBMain {
> ..

and 

all tables like this:

> @Keep
> @Table(database = DBMain.class)
> public class Logs extends BaseModel {

it don't help me :(

**Comment by fabiendem** [comment]
What about: 
`-keep class com.yourapp.models.** { *; }`

**Comment by ghost1980** [comment]
> -keep class com.raizlabs.android.dbflow.** { *; }
> -keep class com.myapp.db.** { *; }
> -keep class com.myapp.models.** { *; }
> -keep class com.myapp.db.models.** { *; }
> -keep class com.google.gson.**  { *; }

This is not working too :(

Can someone provide working proguard rules?

**Comment by ghost1980** [comment]
ProGuard + DBFlow working fine with rules:

> -keepattributes *Annotation*
> -keep class net.sqlcipher.**
> -keep class com.raizlabs.android.dbflow.** { *; }
> -keep class com.test.dbflow.dbflowproguardtest.db.** { *; }
> -keep class com.test.dbflow.dbflowproguardtest.model.** { *; }
> -keep class * extends com.raizlabs.android.dbflow.config.DatabaseHolder { *; }

But if I use the same **ProGuard rules & DBFlow + SQLCipher** my app **crushes** again and again :(

So the problem is how set up ProGuard with DBFlow+SQLCipher?
Any suggestions would be accepted for tests.

**Comment by hannesa2** [comment]
I've no solution, but run into a similar issue #997

**Comment by ghost1980** [comment]
Solution:

> -keepattributes *Annotation*
> -keep class net.sqlcipher.** { *; }
> -keep class * extends com.raizlabs.android.dbflow.config.DatabaseHolder { *; }
> -dontwarn net.sqlcipher.**

works fine on Gradle 2.1.3 & a lot of mistakes on Gradle 2.2.0

main difference is use 
 -keep class net.sqlcipher.** { *; }
instead of  -keep class net.sqlcipher.**
