### ISSUE TITLE
Why db is hit irrespective of whether cached entry is present or not?

### ISSUE THREAD

**Issue by thekalinga** [Raizlabs/DBFlow#984]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Question/Feature

Description: 
Currently dbflow tries to get the data from the database even for cached entries, only ORM part is skipped if the object is already cached. I would like to know the reason behind this.

Pulling data from sqllite even if cached entry is present seems odd. My assumption is that db access is expensive as it involves disk IO (correct me if I'm wrong)

Is it possible to allow the user to decide whether (blind db hit + cache lookup)/(cache lookup + db hit if no entry could be found) should happen first

**Comment by agrosner** [comment]
To ensure that the results set we get back from cache actually exists in the current db. also since the varying queries with different selection result in different rows returned, its much easier + safer to query DB for ids of the rows returned first.

**Comment by thekalinga** [comment]
@agrosner My assumption is that we invalidate the cache when the write happens (not based on code walk thru).

My overall understanding is that

a. Clear all cache entries for a table if user executes native update/delete (direct sql) as we will not have a clue about what rows might have been updated
b. If the user runs entity.save()/entity.update() update just this specific entry in the cache corresponding to the current row (based on identifier)

If the above steps are followed, there is no need for hitting the db blindly as we always know when & how the user hit the database & we are making sure that only the entries that we are certain match the db are cached.

Please let me know your views.
