### ISSUE TITLE
Update existing instance

### ISSUE THREAD

**Issue by waclock** [Raizlabs/DBFlow#985]
I'm facing an issue trying to update an existing object in my DB.

Let's say I have a User with certain columns with information (first name, last name, birthday).

When I go to a specific activity, I send a request to the server, which responds with a User object (with the same PK), but only with the column image_url (no first name, last name, birthday this time).

What I'd expect to happen if I did user.save() was to get a User containing first name, last name, birthday and image_url, however I'm ending up with a User with only image_url (and all other columns set as NULL).

Is there a way to update only the new non-null columns on a object? The real case-scenario has some nested models that are received, which is why calling .save() actually saves more objects to the DB.

Thanks in advance

**Comment by trevjonez** [comment]
If I am understanding your question correctly, you are saying that the server response looks like this:
```javascript
{
  id : 12345,
  image_url : "https://some.image.url/12345"
}
```

From the above json you can see that missing fields should be skipped, but the deserializing library is filling in the blanks and interpreting it as:
```javascript
{
  id : 12345,
  first_name : null,
  last_name : null,
  image_url : "https://some.image.url/12345"
}
```

Without knowing more specifics I can't aid in a path to fixing the issue but if the above is correct the issue is most definitely in your deserialization step not your persistance step.

**Comment by waclock** [comment]
Thanks Trevor, that's exactly the issue. I'll check out if GSON is doing what you're proposing, which would make sense why it's adding null values to existing instances. I'll give an update as soon as I find out if that was the issue.

Thanks again!

**Comment by waclock** [comment]
I gave it a shot, but I think I'm not following what should happen with the object created when parsing the server response. I'm currently using Retrofit with GSON converter, which generates a User object when I parse it.

Since it's an Object, if the JSON only contained "image_url" the object generated will obviously only contain this attribute as a non-null value, however, all other attributes of the class will be null (as they were never initialized when the object was created).

Am I missing something here? I'm not sure what's supposed to happen in order to "merge" both users. The first thing that comes to mind is first to perform a Search by the PK of the model, however I don't feel this is the correct way to proceed.

Is there a way to just "merge" both users and ignore null values?

**Comment by trevjonez** [comment]
I think any way you proceed you will need to do some of the merging manually since you are the only one that will understand what that particular `null` means. 

If you have both instances it may be as simple as just saying `member1.image_url(member2.image_url())`

If not you could do a special query for just this.

```java
SQLite.update(Member_Model.class)
      .set(Member_Model_Table.image_url.eq(member.image_url()))
      .where(Member_Model_Table.id.eq(member.id()))
      .execute();
```

That query will update only that field on the object. If you want to immediately consume it it may be easier to fetch the local instance, update it, call save. then return the updated instance.

**Comment by waclock** [comment]
Thanks Trevor,

the thing that has drawn my attention is in the docs, the following appears:

`Automobile venza = new Automobile();
venza.vin = "499499449";
venza.make = "Toyota";
venza.model = "Venza";
venza.year = 2013;
venza.save(); // inserts if not exists by primary key, updates if exists.`

The thing is, how can the automobile only update the "new" values? If it's an object it will obviously contain all the non initialized values as null. Wouldn't this mean every update will update the old record, and be replace with the new "object" (not only the values that were set in the example).

**Comment by trevjonez** [comment]
Draw your eyes over to the generated code in what would be `Automobile_Adapter` in the above. Then look at the `bindToInsertValues` method along with the `getInsertStatementQuery` method.

You can hopefully start to see how the result of bind to insert values will be paired to the sql provided by get insert statement.

You can then hopefully see that "update if exists" means that it will update the in database version with the exact state of the in memory version. So long as it doesn't validate any integrity constraints that is.

**Comment by waclock** [comment]
Thank you very much, I see what you mean now. I think I've got a good idea on how to handle things from now on.

Thank you again
