### ISSUE TITLE
Get last row id after insert

### ISSUE THREAD

**Issue by aimanbaharum** [Raizlabs/DBFlow#988]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Question

Description: 

Hey guys, how do you get the last row id after an insert operation? Can't seem to find any API that does this, or am I missing something? Is there any workaround for this process?

This is what I did currently, feels rather hack-ish

```java
Routine routine = new Routine();
routine.setName(name);
routine.save();
StringQuery<Routine> stringQuery = new StringQuery<>(Routine.class, "SELECT id FROM Routine ORDER BY id DESC LIMIT 1;");
Routine derp = stringQuery.querySingle();
if (derp != null) {
    L.w("last insert: " + derp.getId());
} else {
    L.w("last insert null");
}
```

**Comment by trevjonez** [comment]
That would work however you technically could get back a bad value from the string query since it is not synchronized. I would thinking doing what you are doing inside of a transaction block would give you the desired result.

**Comment by alfdev** [comment]
Hi aimanbaharum, 

after the insert() (also i think is the same for save method) your model "routine" has the ID property correctly populated.

**Comment by agrosner** [comment]
in 4.0.0-beta1, all single insert methods now return `long`. :)
