### ISSUE TITLE
@OneToMany Adapter bug

### ISSUE THREAD

**Issue by carmas123** [Raizlabs/DBFlow#989]
DBFlow Version:
Issue Kind Bug:

I use Kotlin

Description: 
The problem with @OneToMany is that when generate the Adapter (with Annotation) it generata an erroneus save() method.

```
    if (model.getRows() != null)  {
      for (BaseModel value: model.getRows())  {
        value.save();
      }
    }
    super.save(model);
```

needed to be:

```
  super.save(model);
    if (model.getRows() != null)  {
      for (BaseModel value: model.getRows())  {
        value.save();
      }
    }
```

because If you don't save the Parent model before children can have a foreignkey problem with children.

**Comment by agrosner** [comment]
in `develop`, note its going in 4.0.0-beta1 which will require some significant changes depending on implementation. But most people shouldnt see any drastic change.
