### ISSUE TITLE
Add a new @Table annotation option to prevent the default table creation

### ISSUE THREAD

**Issue by Rainer-Lang** [Raizlabs/DBFlow#99]
```
@Table
```
Possible to define a table name?

eg I have a Model "Device" but the table name is "devices".

**Comment by damson** [comment]
``` @Table(value = "Devices") ```

[Source](https://github.com/Raizlabs/DBFlow/blob/a0a5ee6a935005a857e976f5d3ba58d141b570ba/app/src/main/java/com/raizlabs/android/dbflow/OtherModel.java)

**Comment by Rainer-Lang** [comment]
@damson Thanks a lot.

**Comment by agrosner** [comment]
Hey, for questions like these, I would suffice a quick look at the documentation before opening an issue. If its not explicitly clear in the docs or javadocs, of course ask a question. 
Thank you and I appreciate your interest in this library.

**Comment by Rainer-Lang** [comment]
@agrosner OK, I will spend more time to read the docu. I have to apologize.
