### ISSUE TITLE
Creating Table in DBFlow getting error

### ISSUE THREAD

**Issue by AnujZ** [Raizlabs/DBFlow#990]
DBFlow Version:
Issue Kind (Bug, Question, Feature):

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

C:\Users\AnujZunjarraoBPRISE\Desktop\projects\dagger2-example\app\src\main\java\com\codepath\daggerexample\Application\MyApp.java
Error:(5, 45) error: cannot find symbol class DaggerGitHubComponent
Error:(6, 45) error: cannot find symbol class DaggerNetComponent
Error:*==========*
Error:java.lang.Thread.getStackTrace(Thread.java:1552)
Error:com.raizlabs.android.dbflow.processor.model.ProcessorManager.logError(ProcessorManager.java:255)
Error:com.raizlabs.android.dbflow.processor.model.ProcessorManager.logError(ProcessorManager.java:262)
Error:com.raizlabs.android.dbflow.processor.validator.TableValidator.validate(TableValidator.java:38)
Error:com.raizlabs.android.dbflow.processor.definition.method.DatabaseDefinition.validateDefinitions(DatabaseDefinition.java:134)
Error:com.raizlabs.android.dbflow.processor.definition.method.DatabaseDefinition.validateAndPrepareToWrite(DatabaseDefinition.java:126)
Error:com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:326)
Error:com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:98)
Error:com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
Error:com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
Error:com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
Error:com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
Error:com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
Error:com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
Error:com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
Error:com.sun.tools.javac.main.Main.compile(Main.java:523)
Error:com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
Error:com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
Error:org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)
Error:org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
Error:org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
Error:org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
Error:org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
Error:org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
Error:org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
Error:org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
Error:org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:145)
Error:org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
Error:com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
Error:sun.reflect.GeneratedMethodAccessor846.invoke(Unknown Source)
Error:sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:java.lang.reflect.Method.invoke(Method.java:498)
Error:org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
Error:org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
Error:org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
Error:org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
Error:org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
Error:org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
Error:org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
Error:org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
Error:org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
Error:org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
Error:org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
Error:org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
Error:org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
Error:org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
Error:org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
Error:org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
Error:org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
Error:org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
Error:org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
Error:org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
Error:org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
Error:org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
Error:org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
Error:org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
Error:org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
Error:org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
Error:org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
Error:org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
Error:org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
Error:org.gradle.internal.Factories$1.create(Factories.java:22)
Error:org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
Error:org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
Error:org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
Error:org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
Error:org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
Error:org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
Error:org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
Error:org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
Error:org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
Error:org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
Error:org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
Error:org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:46)
Error:org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
Error:org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)
Error:org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
Error:org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
Error:org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
Error:org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
Error:org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
Error:org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
Error:org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
Error:org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
Error:org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
Error:org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
Error:org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
Error:org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
Error:org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
Error:org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
Error:org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
Error:org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
Error:org.gradle.util.Swapper.swap(Swapper.java:38)
Error:org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
Error:org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
Error:org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
Error:org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
Warning:File for type 'com.raizlabs.android.dbflow.config.MyDatabaseMyDataBase_Database' created in the last round will not be subject to annotation processing.
Warning:File for type 'com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder' created in the last round will not be subject to annotation processing.
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by AnujZ** [comment]
I am using dagger 2 with retrofit and now i am integrate DBFlow in same project but when i try to create table this error come while run. Please anyone help me

**Comment by trevjonez** [comment]
Can you provide sample code for how to reproduce? As is the table validation is failing but there is no way to tell what it is failing on.

Although the top two Items are usually related to a dagger2 configuration issue, and this error pointing at DBFlow may be a side effect of previous compile errors.

**Comment by agrosner** [comment]
yes to me this seems like a dagger2 error finding its way to DBflow.

**Comment by aldrinjoemathew** [comment]
I'm having the same issue. Please help out.

**Comment by Pimmetje** [comment]
Just for people like me who and up searching for a error and ending up here. 

A very similar error will be thrown when u use Column types that are unsupported. I found this by looking at the generated file (I searched for usage of the class i added).

**Comment by okasurya** [comment]
I also got this error when I use a private field for column without providing public setter & getter. Change the field to public or provide setter getter will solve the problem.
