### ISSUE TITLE
Index on foreign key

### ISSUE THREAD

**Issue by mhswtf** [Raizlabs/DBFlow#993]
DBFlow Version: 3.1.1.
Issue Kind (Bug, Question, Feature): Bug

Description: 
When creating an index on a foreign key column, the auto generated foreign key column name ([fk table]_[fk primary key] is not used in the generated index property. Instead it uses the name of the field. Example:

java class:
`@ForeignKey()
@Index(indexGroups = 1)
ForeignKeyContainer<Label> label;`

generated code (asterisks mark troubled code):
`public static final Property<String> *label_name* 
    = new Property<String>(ItemLabel.class, "label_name");
public static final IndexProperty<ItemLabel> index_LabelIndex 
    = new IndexProperty<>("LabelIndex", false, ItemLabel.class, *label*);`

Compile errors ensue.
The problem can be circumvented by explicitly declaring the foreign key with a `@ForeignKeyReference` like so:
`@ForeignKey(references = @ForeignKeyReference(columnName = "label", columnType = String.class, foreignKeyColumnName = "name"))
@Index(indexGroups = 1)
ForeignKeyContainer<Label> label;`

**Comment by relevante** [comment]
I'm seeing this same issue. What's the preferred way to add an index to an existing foreign key relationship?

**Comment by agrosner** [comment]
fixed in 4.0.0-beta2+
