### ISSUE TITLE
where replace query in DBFlow

### ISSUE THREAD

**Issue by sasikumar** [Raizlabs/DBFlow#994]
DBFlow Version: 3.1.1
Issue Kind : Question

Description: 

how can i execute the below sql query in dbflow ?

select * from sample where replace("field_name", '.', ' ' LIKE + field_value)

**Comment by trevjonez** [comment]
`SQLite.select().from(Sample.class).where(Sample_Table.field_name.like("%someSqlRegex")).querySingle()`

**Comment by agrosner** [comment]
yep @trevjonez  is right. Only a few factory methods. Dont want to bloat the library up with every single method, but I tend to add more as more people request them.

**Comment by agrosner** [comment]
in 4.0.0-beta1 youll be able to do:
```
Method.replace(SomeTable_name, "ro", "or")
```

For now, the method I simply added, use: 
```
public static Method replace(IProperty property, String findString, String replacement) {
        return new Method("REPLACE", property, PropertyFactory.from(findString), PropertyFactory.from(replacement));
    }
```

**Comment by tpnet** [comment]
@agrosner  How to replace a entity, not one property
