### ISSUE TITLE
Is this suitable to use within an android library / sdk? 

### ISSUE THREAD

**Issue by aaronbond** [Raizlabs/DBFlow#995]
I'm wondering if this project is suitable for the internals of an sdk / android lib.

i get to this part in the instructions:

>Finally, add the definition to the manifest (with the name that you chose for your custom application):

><application
  android:name="{packageName}.ExampleApplication"
  ...>
</application>

and draw a blank

**Comment by trevjonez** [comment]
Yes it will work fine inside of a library or sdk, so long as you are ok with adding it as a dependency of your library.

If you are setting up the provider entry in the manifest you can simple do it inside the library manifest and it will get merged in by the build system when you compile the app.

**Comment by aaronbond** [comment]
that's as i thought, thanks for your help / advice.
