### ISSUE TITLE
SQLCipher proguard rule

### ISSUE THREAD

**Issue by hannesa2** [Raizlabs/DBFlow#997]
DBFlow Version:
```
    apt "com.github.Raizlabs.DBFlow:dbflow-processor:3.1.1"
    compile "com.github.Raizlabs.DBFlow:dbflow-core:3.1.1"
    compile "com.github.Raizlabs.DBFlow:dbflow:3.1.1"
    compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:3.1.1@aar"
```
Question
What are recommended proguard rules for SQLCipher

Description: 
When I use it with proguard I already use some rules 
```
-keep class info.max.db.model.** { *; }
-keep class * extends com.raizlabs.android.dbflow.config.DatabaseHolder { *; }
-keep class com.raizlabs.android.dbflow.** { *; }
-keep class * extends com.raizlabs.android.dbflow.config.BaseDatabaseDefinition { *; }
-keep class net.sqlcipher.** { *; }
-dontwarn net.sqlcipher.**
```

but I receive this too, any clue how to solve it ?
```
Warning: com.raizlabs.dbflow.android.sqlcipher.SQLCipherOpenHelper: can't find referenced method 'net.sqlcipher.database.SQLiteDatabase getWritableDatabase(java.lang.String)' in program class com.raizlabs.dbflow.android.sqlcipher.SQLCipherOpenHelper
Warning: com.raizlabs.dbflow.android.sqlcipher.SQLCipherOpenHelper$BackupHelper: can't find referenced method 'net.sqlcipher.database.SQLiteDatabase getWritableDatabase(java.lang.String)' in program class com.raizlabs.dbflow.android.sqlcipher.SQLCipherOpenHelper$BackupHelper
```

**Comment by ghost1980** [comment]
I still have no solution :(

**Comment by agrosner** [comment]
try:
```
-keep class net.sqlcipher.** { *; }
-dontwarn net.sqlcipher.**
```

**Comment by agrosner** [comment]
https://discuss.zetetic.net/t/native-runtime-crash-from-sqlcipher-for-android/1096/8

**Comment by hannesa2** [comment]
your recommendation to add my missing 

`-keep class net.sqlcipher.** { *; }`

didn't help

**Comment by hannesa2** [comment]
but when I follow your hint in #942 

```
ext {
   dbflow_version = "3.1.1"
}
...
   compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:${dbflow_version}@aar"
   compile "net.zetetic:android-database-sqlcipher:3.5.4@aar"
```

I receive tons of errors 
![abc](https://cloud.githubusercontent.com/assets/3314607/19022241/f6066536-88d3-11e6-9b93-d91930bf0c31.png)

> :app:prepareIoReactivexRxandroid120Library
> :app:prepareNetZeteticAndroidDatabaseSqlcipher354Library
> Jar found at unexpected path (jni/sqlcipher-javadoc.jar) in /Users/aaa/.gradle/caches/modules-2/files-2.1/net.zetetic/android-database-sqlcipher/3.5.4/ae14715c148b40e3f1c4479e7efefb74de669abf/android-database-sqlcipher-3.5.4.aar and will be ignored. Jars should be placed inside 'jars' folder to be merged into dex. Jars that are in assets/ or res/raw/ will be copied as-is.
> Jar found at unexpected path (jni/sqlcipher.jar) in /Users/aaa/.gradle/caches/modules-2/files-2.1/net.zetetic/android-database-sqlcipher/3.5.4/ae14715c148b40e3f1c4479e7efefb74de669abf/android-database-sqlcipher-3.5.4.aar and will be ignored. Jars should be placed inside 'jars' folder to be merged into dex. Jars that are in assets/ or res/raw/ will be copied as-is.
> 

but it build and starts my APK

I hope in DBFlow 4.0.0 it works much better

**Comment by agrosner** [comment]
I see, so adding the lib to the explicit dependency of the project works ok?

**Comment by hannesa2** [comment]
more or less, at least for compile. 
Actually I did only the compile test, now I test it during runtime, if db is encrypted and works properbly

**Comment by agrosner** [comment]
let me know and ill update docs.

**Comment by hannesa2** [comment]
cool, it's working perfect.

(only the tons of proguard errors are disturbing)
![bbb](https://cloud.githubusercontent.com/assets/3314607/19023170/b982e65c-88e7-11e6-931f-f489e3e65fcf.png)

**Comment by ghost1980** [comment]
Do you have tons of errors on gradle 2.2.0?
Try downgrade grade to 2.1.3.

**Comment by hannesa2** [comment]
I can confirm with gradle build tools 2.1.3 it works perfect.
Does anyone has a clue, what's wrong with 2.2.0. We all have to go to 2.2.0 sooner or later
