### ISSUE TITLE
Cannot have an Boolean column in Kotlin

### ISSUE THREAD

**Issue by alilotfi** [Raizlabs/DBFlow#999]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Bug
Description: 
Hi
I'm using kotlin v1.0.4. I created a database and I have a model named `App`.
`App` class has several columns with different types as follow:
```kotlin
@Table(database = VTDatabase::class)
class App(@PrimaryKey @Column var packageName: String = "",
          @Column var name: String = "") : BaseModel()
```
This code will compile successfully, but when I add another column with `Boolean` type, it doesn't.
```kotlin
@Table(database = VTDatabase::class)
class App(@PrimaryKey @Column var packageName: String = "",
          @Column var name: String = "",
          @Column var systemApp: Boolean = false) : BaseModel()
```
The stacktrace* of the compiler points to this line of code:
```java
// com.raizlabs.android.dbflow.processor.validator.ColumnValidator.validate(ColumnValidator.java:29)
"Could not find getter for private element: \"%1s\" from table class: %1s. Consider adding a getter with name %1s or making it more accessible."
```

Can someone explain is there any bug or I'm doing something wrong?

*I was unable to read the message because there wasn't any message shown in the android studio, so I used stacktrace to find the issue.

**Comment by trevjonez** [comment]
The logic in dbflow assumes that the getter would be named `isSystemApp` but in reality kotlin creates a getter method named `getSystemApp`

If you change your `@Column` to be `@Column(getterName = "getSystemApp")` it should work.

**Comment by alilotfi** [comment]
Thank you very much. This solves the problem.
I guessed so but I did not look at `@Column` arguments.

**Comment by ianmcxa** [comment]
Can this be fixed so that we don't have to specify the getterName?

**Comment by pyus-13** [comment]
Awesome, Thanks
